YUP: yup::Line< ValueType > Class Template Reference
yup::Line< ValueType > Class Template Reference
Defines a class for a geometric line in a 2D space.
Public Member Functions
constexpr Line () noexcept=default
Default constructor which initializes a line where both points are at the origin.
constexpr Line (ValueType x1, ValueType y1, ValueType x2, ValueType y2) noexcept
Constructs a line from four coordinate values.
constexpr Line (const Point< ValueType > &s, const Point< ValueType > &e) noexcept
Constructs a line from two points.
template<class T, std::enable_if_t<! std::is_same_v< T, ValueType >, int > = 0>
constexpr Line (T x1, T y1, T x2, T y2) noexcept
Constructs a line from four coordinate values of a different type, converting them to ValueType.
constexpr Line (const Line &other) noexcept=default
Copy and move constructors and assignment operators.
constexpr Line (Line &&other) noexcept=default
constexpr Line & operator= (const Line &other) noexcept=default
constexpr Line & operator= (Line &&other) noexcept=default
constexpr Point< ValueType > getStart () const noexcept
Retrieves the start point of the line.
constexpr Line & setStart (const Point< ValueType > &newStart) noexcept
Sets the start point of the line.
constexpr Line withStart (const Point< ValueType > &newStart) const noexcept
Creates a new line with the specified start point while keeping the end point unchanged.
constexpr ValueType getStartX () const noexcept
Retrieves the start point value X of the line.
constexpr ValueType getStartY () const noexcept
Retrieves the start point value Y of the line.
constexpr Point< ValueType > getEnd () const noexcept
Retrieves the end point of the line.
constexpr Line & setEnd (const Point< ValueType > &newEnd) noexcept
Sets the end point of the line.
constexpr Line withEnd (const Point< ValueType > &newEnd) const noexcept
Creates a new line with the specified end point while keeping the start point unchanged.
constexpr ValueType getEndX () const noexcept
Retrieves the end point value X of the line.
constexpr ValueType getEndY () const noexcept
Retrieves the end point value Y of the line.
constexpr Line & reverse () noexcept
Reverses the direction of the line by swapping the start and end points.
constexpr Line reversed () const noexcept
Creates a new line that is a reversed version of this line.
constexpr float length () const noexcept
Calculates the length of the line.
constexpr float slope () const noexcept
Calculates the slope of the line.
constexpr bool contains (const Point< ValueType > &point) const noexcept
Checks if a given point lies on the line, with a default very small tolerance.
constexpr bool contains (const Point< ValueType > &point, float tolerance) const noexcept
Checks if a given point lies on the line, considering a specified tolerance.
constexpr Point< ValueType > pointAlong (float proportionOfLength) const noexcept
Finds a point along the line at a specified proportion of its length.
constexpr Line & translate (ValueType deltaX, ValueType deltaY) noexcept
Translates the line by a specified amount in x and y directions.
constexpr Line & translate (const Point< ValueType > &delta) noexcept
Translates the line by a vector represented by a point.
constexpr Line translated (ValueType deltaX, ValueType deltaY) const noexcept
Creates a new line that is a translated version of this line by specified x and y values.
constexpr Line translated (const Point< ValueType > &delta) const noexcept
Creates a new line that is a translated version of this line by a vector represented by a point.
constexpr Line & extend (ValueType length) noexcept
Extends the line symmetrically before and after by a specified length.
constexpr Line extended (ValueType length) const noexcept
Creates a new line that is an extended version of this line by a specified length.
constexpr Line & extendBefore (ValueType length) noexcept
Extends the line before the start point by a specified length.
constexpr Line extendedBefore (ValueType length) const noexcept
Creates a new line that is an extended version of this line before the start point by a specified length.
constexpr Line & extendAfter (ValueType length) noexcept
Extends the line after the end point by a specified length.
constexpr Line extendedAfter (ValueType length) const noexcept
Creates a new line that is an extended version of this line after the end point by a specified length.
constexpr Line keepOnlyStart (float proportionOfLength) noexcept
Creates a new line segment from the start point to a specified proportion along the line.
constexpr Line keepOnlyEnd (float proportionOfLength) noexcept
Creates a new line segment from a specified proportion along the line to the original end point.
constexpr Line rotateAtPoint (const Point< ValueType > &point, float angleRadians) const noexcept
Rotates the line around a specified point by a given angle in radians.
constexpr Line & transform (const AffineTransform &t) noexcept
constexpr Line transformed (const AffineTransform &t) const noexcept
template<class T>
constexpr Line< T > to () const noexcept
Converts the line to another type.
template<class T = ValueType>
constexpr auto roundToInt () const noexcept -> std::enable_if_t< std::is_floating_point_v< T >, Line< int > >
constexpr Line operator- () const noexcept
Unary minus operator to negate both points of the line.
constexpr bool operator== (const Line &other) const noexcept
Equality comparison operator.
constexpr bool operator!= (const Line &other) const noexcept
Inequality comparison operator.
Detailed Description
template<class ValueType>
class yup::Line< ValueType >
Defines a class for a geometric line in a 2D space.
The Line class encapsulates a line defined by two points (start and end) in 2D space. It provides constructors for creating lines from individual coordinates or from Point objects. The class supports operations such as getting and setting start/end points, checking containment of a point with tolerance, translating, extending, and rotating the line, and converting to another type.
Template Parameters
ValueType The data type of the coordinates (e.g., int, float, double).
Constructor & Destructor Documentation
Line() [1/6]
template<class ValueType> yup::Line< ValueType >::Line () constexpr default noexcept
Default constructor which initializes a line where both points are at the origin.
Referenced by extend(), extendAfter(), extendBefore(), extended(), extendedAfter(), extendedBefore(), keepOnlyEnd(), keepOnlyStart(), Line(), Line(), Line(), operator!=(), operator-(), operator=(), operator=(), operator==(), reverse(), reversed(), rotateAtPoint(), roundToInt(), setEnd(), setStart(), to(), transform(), transformed(), translate(), translate(), translated(), translated(), withEnd(), and withStart().
Line() [2/6]
template<class ValueType> yup::Line< ValueType >::Line (ValueType x1, ValueType y1, ValueType x2, ValueType y2) constexpr noexcept
Constructs a line from four coordinate values.
This constructor initializes a line from two pairs of coordinates representing the start (x1, y1) and end (x2, y2) points of the line.
Parameters
x1 The x-coordinate of the start point.
y1 The y-coordinate of the start point.
x2 The x-coordinate of the end point.
y2 The y-coordinate of the end point.
References Line().
Line() [3/6]
template<class ValueType> yup::Line< ValueType >::Line (const Point< ValueType > & s, const Point< ValueType > & e) constexpr noexcept
Constructs a line from two points.
This constructor creates a line defined by start point s and end point e.
Parameters
s The start point of the line as a Point object.
e The end point of the line as a Point object.
Line() [4/6]
template<class ValueType> template<class T, std::enable_if_t<! std::is_same_v< T, ValueType >, int > = 0> yup::Line< ValueType >::Line (T x1, T y1, T x2, T y2) constexpr noexcept
Constructs a line from four coordinate values of a different type, converting them to ValueType.
This template constructor allows the creation of a line from coordinates of a different type T, which are then statically cast to ValueType. This constructor checks for possible overflow issues in the casting process.
Parameters
x1 The x-coordinate of the start point, of type T.
y1 The y-coordinate of the start point, of type T.
x2 The x-coordinate of the end point, of type T.
y2 The y-coordinate of the end point, of type T.
Line() [5/6]
template<class ValueType> yup::Line< ValueType >::Line (const Line< ValueType > & other) constexpr default noexcept
Copy and move constructors and assignment operators.
References Line().
Line() [6/6]
template<class ValueType> yup::Line< ValueType >::Line (Line< ValueType > && other) constexpr default noexcept
References Line().
Member Function Documentation
operator=() [1/2]
template<class ValueType> Line & yup::Line< ValueType >::operator= (const Line< ValueType > & other) constexpr default noexcept
References Line().
operator=() [2/2]
template<class ValueType> Line & yup::Line< ValueType >::operator= (Line< ValueType > && other) constexpr default noexcept
References Line().
getStart()
template<class ValueType> Point< ValueType > yup::Line< ValueType >::getStart () const constexpr noexcept
Retrieves the start point of the line.
Returns
The start point of the line as a Point<ValueType>.
Referenced by yup::Path::addLine().
setStart()
template<class ValueType> Line & yup::Line< ValueType >::setStart (const Point< ValueType > & newStart) constexpr noexcept
Sets the start point of the line.
Parameters
newStart The new start point of the line as a Point<ValueType>.
Returns
A reference to this line after modification.
References Line().
withStart()
template<class ValueType> Line yup::Line< ValueType >::withStart (const Point< ValueType > & newStart) const constexpr noexcept
Creates a new line with the specified start point while keeping the end point unchanged.
Parameters
newStart The new start point of the line as a Point<ValueType>.
Returns
A new Line object with the updated start point.
References Line().
getStartX()
template<class ValueType> ValueType yup::Line< ValueType >::getStartX () const constexpr noexcept
Retrieves the start point value X of the line.
Returns
The start point value X of the line.
getStartY()
template<class ValueType> ValueType yup::Line< ValueType >::getStartY () const constexpr noexcept
Retrieves the start point value Y of the line.
Returns
The start point value Y of the line.
getEnd()
template<class ValueType> Point< ValueType > yup::Line< ValueType >::getEnd () const constexpr noexcept
Retrieves the end point of the line.
Returns
The end point of the line as a Point<ValueType>.
Referenced by yup::Path::addLine().
setEnd()
template<class ValueType> Line & yup::Line< ValueType >::setEnd (const Point< ValueType > & newEnd) constexpr noexcept
Sets the end point of the line.
Parameters
newEnd The new end point of the line as a Point<ValueType>.
Returns
A reference to this line after modification.
References Line().
withEnd()
template<class ValueType> Line yup::Line< ValueType >::withEnd (const Point< ValueType > & newEnd) const constexpr noexcept
Creates a new line with the specified end point while keeping the start point unchanged.
Parameters
newEnd The new end point of the line as a Point<ValueType>.
Returns
A new Line object with the updated end point.
References Line().
getEndX()
template<class ValueType> ValueType yup::Line< ValueType >::getEndX () const constexpr noexcept
Retrieves the end point value X of the line.
Returns
The end point value X of the line.
getEndY()
template<class ValueType> ValueType yup::Line< ValueType >::getEndY () const constexpr noexcept
Retrieves the end point value Y of the line.
Returns
The end point value Y of the line.
reverse()
template<class ValueType> Line & yup::Line< ValueType >::reverse () constexpr noexcept
Reverses the direction of the line by swapping the start and end points.
Returns
A reference to this line after the start and end points have been swapped.
References Line().
Referenced by reversed().
reversed()
template<class ValueType> Line yup::Line< ValueType >::reversed () const constexpr noexcept
Creates a new line that is a reversed version of this line.
Returns
A new Line object with the start and end points swapped compared to this line.
References Line(), and reverse().
length()
template<class ValueType> float yup::Line< ValueType >::length () const constexpr noexcept
Calculates the length of the line.
Returns
The length of the line as a float.
Referenced by extend(), extendAfter(), extendBefore(), extended(), extendedAfter(), and extendedBefore().
slope()
template<class ValueType> float yup::Line< ValueType >::slope () const constexpr noexcept
Calculates the slope of the line.
This function computes the slope as the ratio of the difference in y-coordinates to the difference in x-coordinates of the end and start points. If the line is vertical (divisor is zero), the function returns zero.
Returns
The slope of the line as a float.
Referenced by extend(), extendAfter(), and extendBefore().
contains() [1/2]
template<class ValueType> bool yup::Line< ValueType >::contains (const Point< ValueType > & point) const constexpr noexcept
Checks if a given point lies on the line, with a default very small tolerance.
Parameters
point The point to check as a Point<ValueType>.
Returns
true if the point is on the line within the default tolerance; otherwise, false.
References contains().
Referenced by contains().
contains() [2/2]
template<class ValueType> bool yup::Line< ValueType >::contains (const Point< ValueType > & point, float tolerance) const constexpr noexcept
Checks if a given point lies on the line, considering a specified tolerance.
This function checks if the specified point is on the line segment within a given tolerance. The tolerance accounts for floating-point precision issues in calculations.
Parameters
point The point to check as a Point<ValueType>.
tolerance The tolerance for considering a point to be on the line, as a float.
Returns
true if the point is on the line within the specified tolerance; otherwise, false.
pointAlong()
template<class ValueType> Point< ValueType > yup::Line< ValueType >::pointAlong (float proportionOfLength) const constexpr noexcept
Finds a point along the line at a specified proportion of its length.
This function calculates a point that lies a certain proportion along the line, from the start to the end. The proportion is specified as a fraction of the total line length.
Parameters
proportionOfLength The proportion of the line's total length, as a float.
Returns
A Point<ValueType> that is located at the specified proportion along the line.
translate() [1/2]
template<class ValueType> Line & yup::Line< ValueType >::translate (ValueType deltaX, ValueType deltaY) constexpr noexcept
Translates the line by a specified amount in x and y directions.
This method modifies both the start and end points of the line by adding the specified deltas to their coordinates.
Parameters
deltaX The amount to translate along the x-axis.
deltaY The amount to translate along the y-axis.
Returns
A reference to this line after translation.
References Line().
translate() [2/2]
template<class ValueType> Line & yup::Line< ValueType >::translate (const Point< ValueType > & delta) constexpr noexcept
Translates the line by a vector represented by a point.
This method modifies both the start and end points of the line by adding the coordinates of the given Point to them, effectively translating the line by the vector represented by the point.
Parameters
delta The translation vector as a Point<ValueType>.
Returns
A reference to this line after translation.
References Line().
translated() [1/2]
template<class ValueType> Line yup::Line< ValueType >::translated (ValueType deltaX, ValueType deltaY) const constexpr noexcept
Creates a new line that is a translated version of this line by specified x and y values.
Parameters
deltaX The x-value to translate by.
deltaY The y-value to translate by.
Returns
A new Line object representing the translated line.
References Line().
translated() [2/2]
template<class ValueType> Line yup::Line< ValueType >::translated (const Point< ValueType > & delta) const constexpr noexcept
Creates a new line that is a translated version of this line by a vector represented by a point.
Parameters
delta The translation vector as a Point<ValueType>.
Returns
A new Line object representing the translated line.
References Line().
extend()
template<class ValueType> Line & yup::Line< ValueType >::extend (ValueType length) constexpr noexcept
Extends the line symmetrically before and after by a specified length.
This function extends the line by moving the start and end points away from each other along the line's current direction, by the specified length. The extension is divided equally between the start and end points.
Parameters
length The total length by which to extend the line, as a ValueType.
Returns
A reference to this line after extension.
References length(), Line(), and slope().
Referenced by extended().
extended()
template<class ValueType> Line yup::Line< ValueType >::extended (ValueType length) const constexpr noexcept
Creates a new line that is an extended version of this line by a specified length.
Parameters
length The total length by which to extend the line, as a ValueType.
Returns
A new Line object representing the extended line.
References extend(), length(), and Line().
extendBefore()
template<class ValueType> Line & yup::Line< ValueType >::extendBefore (ValueType length) constexpr noexcept
Extends the line before the start point by a specified length.
This method extends the line by increasing the distance of the start point from the end point by the specified length, effectively elongating the line before its start point.
Parameters
length The length by which to extend the line before the start point, as a ValueType.
Returns
A reference to this line after extension.
References length(), Line(), and slope().
Referenced by extendedBefore().
extendedBefore()
template<class ValueType> Line yup::Line< ValueType >::extendedBefore (ValueType length) const constexpr noexcept
Creates a new line that is an extended version of this line before the start point by a specified length.
Parameters
length The length by which to extend the line before the start point, as a ValueType.
Returns
A new Line object representing the extended line.
References extendBefore(), length(), and Line().
extendAfter()
template<class ValueType> Line & yup::Line< ValueType >::extendAfter (ValueType length) constexpr noexcept
Extends the line after the end point by a specified length.
This method extends the line by increasing the distance of the end point from the start point by the specified length, effectively elongating the line after its end point.
Parameters
length The length by which to extend the line after the end point, as a ValueType.
Returns
A reference to this line after extension.
References length(), Line(), and slope().
Referenced by extendedAfter().
extendedAfter()
template<class ValueType> Line yup::Line< ValueType >::extendedAfter (ValueType length) const constexpr noexcept
Creates a new line that is an extended version of this line after the end point by a specified length.
Parameters
length The length by which to extend the line after the end point, as a ValueType.
Returns
A new Line object representing the extended line.
References extendAfter(), length(), and Line().
keepOnlyStart()
template<class ValueType> Line yup::Line< ValueType >::keepOnlyStart (float proportionOfLength) constexpr noexcept
Creates a new line segment from the start point to a specified proportion along the line.
This method computes a new end point along the line at a given proportion of the total line length, starting from the original start point. The proportion is clamped between 0.0 and 1.0 to ensure the new end point lies within the original line segment.
Parameters
proportionOfLength The proportion of the total line length where the new end point will be located, as a float. This value is clamped to the range [0.0, 1.0].
Returns
A new Line object representing the segment from the start point to the calculated end point.
References yup::jlimit(), and Line().
keepOnlyEnd()
template<class ValueType> Line yup::Line< ValueType >::keepOnlyEnd (float proportionOfLength) constexpr noexcept
Creates a new line segment from a specified proportion along the line to the original end point.
This method computes a new start point along the line at a given proportion of the total line length, ending at the original end point. The proportion is clamped between 0.0 and 1.0 to ensure the new start point lies within the original line segment.
Parameters
proportionOfLength The proportion of the total line length where the new start point will be located, as a float. This value is clamped to the range [0.0, 1.0].
Returns
A new Line object representing the segment from the calculated start point to the end point.
References yup::jlimit(), and Line().
rotateAtPoint()
template<class ValueType> Line yup::Line< ValueType >::rotateAtPoint (const Point< ValueType > & point, float angleRadians) const constexpr noexcept
Rotates the line around a specified point by a given angle in radians.
This function rotates both the start and end points of the line around a given point by the specified angle, measured in radians. The rotation follows the right-hand rule (counter-clockwise direction).
Parameters
point The center point around which to rotate the line, as a Point<ValueType>.
angleRadians The angle by which to rotate the line, in radians.
Returns
A new Line object representing the rotated line.
References Line(), and to().
transform()
template<class ValueType> Line & yup::Line< ValueType >::transform (const AffineTransform & t) constexpr noexcept
References Line().
Referenced by transformed().
transformed()
template<class ValueType> Line yup::Line< ValueType >::transformed (const AffineTransform & t) const constexpr noexcept
References Line(), and transform().
to()
template<class ValueType> template<class T> Line< T > yup::Line< ValueType >::to () const constexpr noexcept
Converts the line to another type.
This template function converts both the start and end points of the line to another specified type T, effectively creating a new Line<T> with points of the new type.
Template Parameters
T The new type to which the line's points should be converted.
Returns
A new Line<T> object with points of type T.
References Line(), and to().
Referenced by rotateAtPoint(), and to().
roundToInt()
template<class ValueType> template<class T = ValueType> auto yup::Line< ValueType >::roundToInt () const -> std::enable_if_t<std::is_floating_point_v<T>, Line<int>> constexpr noexcept
References Line().
operator-()
template<class ValueType> Line yup::Line< ValueType >::operator- () const constexpr noexcept
Unary minus operator to negate both points of the line.
This operator creates a new line where both the start and end points have their coordinates negated, effectively reflecting the line across the origin.
Returns
A new Line object with both points negated.
References Line().
operator==()
template<class ValueType> bool yup::Line< ValueType >::operator== (const Line< ValueType > & other) const constexpr noexcept
Equality comparison operator.
This operator compares two lines for equality, based on the equality of their start and end points.
Parameters
other The other line to compare against.
Returns
true if the lines are equal (both start and end points match); otherwise, false.
References Line().
operator!=()
template<class ValueType> bool yup::Line< ValueType >::operator!= (const Line< ValueType > & other) const constexpr noexcept
Inequality comparison operator.
This operator checks if two lines are not equal by comparing their start and end points.
Parameters
other The other line to compare against.
Returns
true if the lines are not equal (either start or end points do not match); otherwise, false.
References Line().