YUP: yup::Identifier Class Reference
yup::Identifier Class Reference final
Represents a string identifier, designed for accessing properties by name.
Public Member Functions
Identifier () noexcept
Creates a null identifier.
Identifier (const char *name)
Creates an identifier with a specified name.
Identifier (const String &name)
Creates an identifier with a specified name.
Identifier (StringRef name)
Creates an identifier with a specified name.
Identifier (String::CharPointerType nameStart, String::CharPointerType nameEnd)
Creates an identifier with a specified name.
Identifier (const Identifier &other) noexcept
Creates a copy of another identifier.
Identifier & operator= (const Identifier &other) noexcept
Creates a copy of another identifier.
Identifier (Identifier &&other) noexcept
Creates a copy of another identifier.
Identifier & operator= (Identifier &&other) noexcept
Creates a copy of another identifier.
~Identifier () noexcept
Destructor.
bool operator== (const Identifier &other) const noexcept
Compares two identifiers.
bool operator!= (const Identifier &other) const noexcept
Compares two identifiers.
bool operator== (StringRef other) const noexcept
Compares the identifier with a string.
bool operator!= (StringRef other) const noexcept
Compares the identifier with a string.
bool operator< (StringRef other) const noexcept
Compares the identifier with a string.
bool operator<= (StringRef other) const noexcept
Compares the identifier with a string.
bool operator> (StringRef other) const noexcept
Compares the identifier with a string.
bool operator>= (StringRef other) const noexcept
Compares the identifier with a string.
const String & toString () const noexcept
Returns this identifier as a string.
operator String::CharPointerType () const noexcept
Returns this identifier's raw string pointer.
String::CharPointerType getCharPointer () const noexcept
Returns this identifier's raw string pointer.
operator StringRef () const noexcept
Returns this identifier as a StringRef.
bool isValid () const noexcept
Returns true if this Identifier is not null.
bool isNull () const noexcept
Returns true if this Identifier is null.
Static Public Member Functions
static bool isValidIdentifier (const String &possibleIdentifier) noexcept
Checks a given string for characters that might not be valid in an Identifier.
Static Public Attributes
static Identifier null
A null identifier.
Detailed Description
Represents a string identifier, designed for accessing properties by name.
Comparing two Identifier objects is very fast (an O(1) operation), but creating them can be slower than just using a String directly, so the optimal way to use them is to keep some static Identifier objects for the things you use often.
See also
NamedValueSet, ValueTree
Constructor & Destructor Documentation
Identifier() [1/7]
yup::Identifier::Identifier () noexcept
Creates a null identifier.
Referenced by Identifier(), Identifier(), operator!=(), operator=(), operator=(), and operator==().
Identifier() [2/7]
yup::Identifier::Identifier (const char * name)
Creates an identifier with a specified name.
Because this name may need to be used in contexts such as script variables or XML tags, it must only contain ascii letters and digits, or the underscore character.
Identifier() [3/7]
yup::Identifier::Identifier (const String & name)
Creates an identifier with a specified name.
Because this name may need to be used in contexts such as script variables or XML tags, it must only contain ascii letters and digits, or the underscore character.
References yup::String::isNotEmpty().
Identifier() [4/7]
yup::Identifier::Identifier (StringRef name)
Creates an identifier with a specified name.
Because this name may need to be used in contexts such as script variables or XML tags, it must only contain ascii letters and digits, or the underscore character.
References yup::StringRef::isNotEmpty().
Identifier() [5/7]
yup::Identifier::Identifier (String::CharPointerType nameStart, String::CharPointerType nameEnd)
Creates an identifier with a specified name.
Because this name may need to be used in contexts such as script variables or XML tags, it must only contain ascii letters and digits, or the underscore character.
References yup::end().
Identifier() [6/7]
yup::Identifier::Identifier (const Identifier & other) noexcept
Creates a copy of another identifier.
References Identifier().
Identifier() [7/7]
yup::Identifier::Identifier (Identifier && other) noexcept
Creates a copy of another identifier.
References Identifier().
~Identifier()
yup::Identifier::~Identifier () noexcept
Destructor.
Member Function Documentation
operator=() [1/2]
Identifier & yup::Identifier::operator= (const Identifier & other) noexcept
Creates a copy of another identifier.
References Identifier().
operator=() [2/2]
Identifier & yup::Identifier::operator= (Identifier && other) noexcept
Creates a copy of another identifier.
References Identifier().
operator==() [1/2]
bool yup::Identifier::operator== (const Identifier & other) const noexcept
Compares two identifiers.
This is a very fast operation.
References yup::String::getCharPointer(), and Identifier().
operator!=() [1/2]
bool yup::Identifier::operator!= (const Identifier & other) const noexcept
Compares two identifiers.
This is a very fast operation.
References yup::String::getCharPointer(), and Identifier().
operator==() [2/2]
bool yup::Identifier::operator== (StringRef other) const noexcept
Compares the identifier with a string.
operator!=() [2/2]
bool yup::Identifier::operator!= (StringRef other) const noexcept
Compares the identifier with a string.
operator<()
bool yup::Identifier::operator< (StringRef other) const noexcept
Compares the identifier with a string.
operator<=()
bool yup::Identifier::operator<= (StringRef other) const noexcept
Compares the identifier with a string.
operator>()
bool yup::Identifier::operator> (StringRef other) const noexcept
Compares the identifier with a string.
operator>=()
bool yup::Identifier::operator>= (StringRef other) const noexcept
Compares the identifier with a string.
toString()
const String & yup::Identifier::toString () const noexcept
Returns this identifier as a string.
operator String::CharPointerType()
yup::Identifier::operator String::CharPointerType () const noexcept
Returns this identifier's raw string pointer.
getCharPointer()
String::CharPointerType yup::Identifier::getCharPointer () const noexcept
Returns this identifier's raw string pointer.
operator StringRef()
yup::Identifier::operator StringRef () const noexcept
Returns this identifier as a StringRef.
isValid()
bool yup::Identifier::isValid () const noexcept
Returns true if this Identifier is not null.
isNull()
bool yup::Identifier::isNull () const noexcept
Returns true if this Identifier is null.
isValidIdentifier()
bool yup::Identifier::isValidIdentifier (const String & possibleIdentifier) static noexcept
Checks a given string for characters that might not be valid in an Identifier.
Since Identifiers are used as a script variables and XML attributes, they should only contain alphanumeric characters, underscores, or the '-' and ':' characters.
Member Data Documentation
null
Identifier yup::Identifier::null static
A null identifier.