YUP: yup::Process Class Reference
yup::Process Class Reference
Represents the current executable's process.
Public Types
enum ProcessPriority { LowPriority = 0 , NormalPriority = 1 , HighPriority = 2 , RealtimePriority = 3 }
Static Public Member Functions
static void YUP_CALLTYPE setPriority (ProcessPriority priority)
Changes the current process's priority.
static void YUP_CALLTYPE terminate ()
Kills the current process immediately.
static bool YUP_CALLTYPE isForegroundProcess ()
Returns true if this application process is the one that the user is currently using.
static void YUP_CALLTYPE makeForegroundProcess ()
Attempts to make the current process the active one.
static void YUP_CALLTYPE hide ()
Hides the application (on an OS that supports this, e.g.
static void YUP_CALLTYPE raisePrivilege ()
Raises the current process's privilege level.
static void YUP_CALLTYPE lowerPrivilege ()
Lowers the current process's privilege level.
static bool YUP_CALLTYPE isRunningUnderDebugger () noexcept
Returns true if this process is being hosted by a debugger.
static bool YUP_CALLTYPE openDocument (const String &documentURL, const String &parameters)
Tries to launch the OS's default reader application for a given file or URL.
static bool YUP_CALLTYPE openDocument (const String &documentURL, const String &parameters, const StringPairArray &environment)
Tries to launch the OS's default reader application for a given file or URL, using an explicit environment.
static bool YUP_CALLTYPE openEmailWithAttachments (const String &targetEmailAddress, const String &emailSubject, const String &bodyText, const StringArray &filesToAttach)
Tries to launch the OS's default email application to let the user create a message.
static void *YUP_CALLTYPE getCurrentModuleInstanceHandle () noexcept
WINDOWS ONLY - This returns the HINSTANCE of the current module.
static void YUP_CALLTYPE setCurrentModuleInstanceHandle (void *newHandle) noexcept
WINDOWS ONLY - Sets a new module handle to be used by the library.
static void setDockIconVisible (bool isVisible)
OSX ONLY - Shows or hides the OSX dock icon for this app.
static bool setMaxNumberOfFileHandles (int maxNumberOfFiles) noexcept
UNIX ONLY - Attempts to use setrlimit to change the maximum number of file handles that the app can open.
Detailed Description
Represents the current executable's process.
This contains methods for controlling the current application at the process-level.
See also
Thread, YUPApplicationBase
Member Enumeration Documentation
ProcessPriority
enum yup::Process::ProcessPriority
Enumerator
LowPriority
NormalPriority
HighPriority
RealtimePriority
Member Function Documentation
setPriority()
void YUP_CALLTYPE yup::Process::setPriority (ProcessPriority priority) static
Changes the current process's priority.
Parameters
priority the process priority, where 0=low, 1=normal, 2=high, 3=realtime
terminate()
void YUP_CALLTYPE yup::Process::terminate () static
Kills the current process immediately.
This is an emergency process terminator that kills the application immediately - it's intended only for use only when something goes horribly wrong.
See also
YUPApplicationBase::quit
isForegroundProcess()
bool YUP_CALLTYPE yup::Process::isForegroundProcess () static
Returns true if this application process is the one that the user is currently using.
makeForegroundProcess()
void YUP_CALLTYPE yup::Process::makeForegroundProcess () static
Attempts to make the current process the active one.
(This is not possible on some platforms).
hide()
void YUP_CALLTYPE yup::Process::hide () static
Hides the application (on an OS that supports this, e.g.
OSX, iOS, Android)
raisePrivilege()
void YUP_CALLTYPE yup::Process::raisePrivilege () static
Raises the current process's privilege level.
Does nothing if this isn't supported by the current OS, or if process privilege level is fixed.
lowerPrivilege()
void YUP_CALLTYPE yup::Process::lowerPrivilege () static
Lowers the current process's privilege level.
Does nothing if this isn't supported by the current OS, or if process privilege level is fixed.
References isRunningUnderDebugger().
isRunningUnderDebugger()
bool YUP_CALLTYPE yup::Process::isRunningUnderDebugger () static noexcept
Returns true if this process is being hosted by a debugger.
References yup::yup_isRunningUnderDebugger().
Referenced by lowerPrivilege().
openDocument() [1/2]
bool YUP_CALLTYPE yup::Process::openDocument (const String & documentURL, const String & parameters) static
Tries to launch the OS's default reader application for a given file or URL.
References openDocument().
Referenced by yup::URL::launchInDefaultBrowser(), openDocument(), openDocument(), yup::File::startAsProcess(), yup::File::startAsProcess(), and yup::File::startAsProcess().
openDocument() [2/2]
bool YUP_CALLTYPE yup::Process::openDocument (const String & documentURL, const String & parameters, const StringPairArray & environment) static
Tries to launch the OS's default reader application for a given file or URL, using an explicit environment.
References openDocument().
openEmailWithAttachments()
bool YUP_CALLTYPE yup::Process::openEmailWithAttachments (const String & targetEmailAddress, const String & emailSubject, const String & bodyText, const StringArray & filesToAttach) static
Tries to launch the OS's default email application to let the user create a message.
References openEmailWithAttachments().
Referenced by openEmailWithAttachments().
getCurrentModuleInstanceHandle()
void *YUP_CALLTYPE yup::Process::getCurrentModuleInstanceHandle () static noexcept
WINDOWS ONLY - This returns the HINSTANCE of the current module.
The return type is a void* to avoid being dependent on windows.h - just cast it to a HINSTANCE to use it.
In a normal JUCE application, this will be automatically set to the module handle of the executable.
If you've built a DLL and plan to use any JUCE messaging or windowing classes, you'll need to make sure you call the setCurrentModuleInstanceHandle() to provide the correct module handle in your DllMain() function, because the system relies on the correct instance handle when opening windows.
setCurrentModuleInstanceHandle()
void YUP_CALLTYPE yup::Process::setCurrentModuleInstanceHandle (void * newHandle) static noexcept
WINDOWS ONLY - Sets a new module handle to be used by the library.
The parameter type is a void* to avoid being dependent on windows.h, but it actually expects a HINSTANCE value.
See also
getCurrentModuleInstanceHandle()
References setCurrentModuleInstanceHandle().
Referenced by setCurrentModuleInstanceHandle().
setDockIconVisible()
void yup::Process::setDockIconVisible (bool isVisible) static
OSX ONLY - Shows or hides the OSX dock icon for this app.
setMaxNumberOfFileHandles()
bool yup::Process::setMaxNumberOfFileHandles (int maxNumberOfFiles) static noexcept
UNIX ONLY - Attempts to use setrlimit to change the maximum number of file handles that the app can open.
Pass 0 or less as the parameter to mean 'infinite'. Returns true if it succeeds.