YUP: yup::NewLine Class Reference
yup::NewLine Class Reference
This class is used for represent a new-line character sequence.
Public Member Functions
operator String () const
Returns the default new-line sequence that the library uses.
operator StringRef () const noexcept
Returns the default new-line sequence that the library uses.
Static Public Member Functions
static const char * getDefault () noexcept
Returns the default new-line sequence that the library uses.
Detailed Description
This class is used for represent a new-line character sequence.
To write a new-line to a stream, you can use the predefined 'newLine' variable, e.g.
myOutputStream << "Hello World" << newLine << newLine;
The exact character sequence that will be used for the new-line can be set and retrieved with OutputStream::setNewLineString() and OutputStream::getNewLineString().
Member Function Documentation
getDefault()
const char * yup::NewLine::getDefault () static noexcept
Returns the default new-line sequence that the library uses.
See also
OutputStream::setNewLineString()
Referenced by operator String(), operator StringRef(), yup::operator+(), yup::operator+(), yup::operator+(), yup::operator+=(), and yup::operator<<().
operator String()
yup::NewLine::operator String () const
Returns the default new-line sequence that the library uses.
See also
getDefault()
References getDefault().
operator StringRef()
yup::NewLine::operator StringRef () const noexcept
Returns the default new-line sequence that the library uses.
See also
OutputStream::setNewLineString()
References getDefault().