YUP: yup::AffineTransform Class Reference
yup::AffineTransform Class Reference
Class representing a 2D affine transformation.
Public Member Functions
constexpr AffineTransform () noexcept
Default constructor.
constexpr AffineTransform (float scaleX, float shearX, float translateX, float shearY, float scaleY, float translateY) noexcept
Parameterized constructor.
constexpr AffineTransform (const AffineTransform &other) noexcept=default
Copy and move constructors and assignment operators.
constexpr AffineTransform (AffineTransform &&other) noexcept=default
constexpr AffineTransform & operator= (const AffineTransform &other) noexcept=default
constexpr AffineTransform & operator= (AffineTransform &&other) noexcept=default
constexpr float getScaleX () const noexcept
Get scaleX component.
constexpr float getShearX () const noexcept
Get shearX component.
constexpr float getTranslateX () const noexcept
Get translateX component.
constexpr float getShearY () const noexcept
Get shearY component.
constexpr float getScaleY () const noexcept
Get scaleY component.
constexpr float getTranslateY () const noexcept
Get translateY component.
constexpr Span< const float > getMatrixPoints () const noexcept
Get span of matrix array.
constexpr bool isIdentity () const noexcept
Check if the transformation is the identity matrix.
constexpr AffineTransform & resetToIdentity () noexcept
Reset to identity transformation.
constexpr AffineTransform inverted () const noexcept
Create an inverted transformation.
constexpr AffineTransform translated (float tx, float ty) const noexcept
Create a translated transformation.
constexpr AffineTransform withAbsoluteTranslation (float tx, float ty) const noexcept
Create a translated transformation.
constexpr AffineTransform rotated (float angleInRadians) const noexcept
Create a rotated transformation.
constexpr AffineTransform rotated (float angleInRadians, float centerX, float centerY) const noexcept
Create a rotated transformation around a point.
constexpr AffineTransform scaled (float factor) const noexcept
Create a scaled transformation.
constexpr AffineTransform scaled (float factorX, float factorY) const noexcept
Create a scaled transformation non-uniformly.
constexpr AffineTransform scaled (float factorX, float factorY, float centerX, float centerY) const noexcept
Create a scaled transformation non-uniformly around a point.
constexpr AffineTransform sheared (float factorX, float factorY) const noexcept
Create a sheared transformation.
constexpr AffineTransform followedBy (const AffineTransform &other) const noexcept
Create a transformation that follows another.
constexpr AffineTransform prependedBy (const AffineTransform &other) const noexcept
constexpr float getDeterminant () const noexcept
constexpr float getScaleFactor () const noexcept
template<class T>
constexpr void transformPoint (T &x, T &y) const noexcept
Transform a point.
template<class T, class... Args>
constexpr void transformPoints (T &x, T &y, Args &&... args) const noexcept
Transform multiple points.
constexpr bool operator== (const AffineTransform &other) const noexcept
Equality operator.
constexpr bool operator!= (const AffineTransform &other) const noexcept
Inequality operator.
rive::Mat2D toMat2D () const
Static Public Member Functions
static constexpr AffineTransform identity () noexcept
Create identity transformation.
static constexpr AffineTransform translation (float tx, float ty) noexcept
Create a translation transformation.
static constexpr AffineTransform rotation (float angleInRadians) noexcept
Create a rotation transformation.
static constexpr AffineTransform rotation (float angleInRadians, float centerX, float centerY) noexcept
Create a rotation transformation around a point.
static constexpr AffineTransform scaling (float factor) noexcept
Create a scaling transformation.
static constexpr AffineTransform scaling (float factorX, float factorY) noexcept
Create a scaling transformation non-uniformly.
static constexpr AffineTransform scaling (float factorX, float factorY, float centerX, float centerY) noexcept
Create a scaling transformation non-uniformly around a point.
static constexpr AffineTransform shearing (float factorX, float factorY) noexcept
Create a shearing transformation.
static constexpr AffineTransform shearing (float factorX, float factorY, float centerX, float centerY) noexcept
Create a shearing transformation around a point.
Detailed Description
Class representing a 2D affine transformation.
This class encapsulates a transformation matrix for performing various linear transformations such as translation, rotation, and scaling in 2D space. An affine transformation is a geometric operation that modifies the spatial relationships between points while preserving lines and parallelism (but not necessarily distances and angles). It allows for the transformation of coordinates and can be modified or combined with other transformations to execute complex changes in the geometry of graphics and other spatial data.
Constructor & Destructor Documentation
AffineTransform() [1/4]
yup::AffineTransform::AffineTransform () constexpr noexcept
Default constructor.
Constructs an AffineTransform object initialized to the identity transformation, which does not modify any points that it is applied to.
References AffineTransform(), and identity().
Referenced by AffineTransform(), AffineTransform(), AffineTransform(), followedBy(), identity(), inverted(), isIdentity(), operator!=(), operator=(), operator=(), operator==(), prependedBy(), resetToIdentity(), rotated(), rotated(), rotation(), rotation(), scaled(), scaled(), scaled(), scaling(), scaling(), scaling(), sheared(), shearing(), shearing(), translated(), translation(), and withAbsoluteTranslation().
AffineTransform() [2/4]
yup::AffineTransform::AffineTransform (float scaleX, float shearX, float translateX, float shearY, float scaleY, float translateY) constexpr noexcept
Parameterized constructor.
Constructs an AffineTransform object with specified matrix components.
Parameters
scaleX Component that scales the x-coordinate.
shearX Component that skews the x-coordinate.
translateX Component that translates the x-coordinate.
shearY Component that skews the y-coordinate.
scaleY Component that scales the y-coordinate.
translateY Component that translates the y-coordinate.
References scaleX, scaleY, shearX, shearY, translateX, and translateY.
AffineTransform() [3/4]
yup::AffineTransform::AffineTransform (const AffineTransform & other) constexpr default noexcept
Copy and move constructors and assignment operators.
References AffineTransform().
AffineTransform() [4/4]
yup::AffineTransform::AffineTransform (AffineTransform && other) constexpr default noexcept
References AffineTransform().
Member Function Documentation
operator=() [1/2]
AffineTransform & yup::AffineTransform::operator= (const AffineTransform & other) constexpr default noexcept
References AffineTransform().
operator=() [2/2]
AffineTransform & yup::AffineTransform::operator= (AffineTransform && other) constexpr default noexcept
References AffineTransform().
getScaleX()
float yup::AffineTransform::getScaleX () const constexpr noexcept
Get scaleX component.
Returns the scaleX component of the AffineTransform object.
Returns
The scaleX component of this AffineTransform.
References scaleX.
Referenced by toMat2D().
getShearX()
float yup::AffineTransform::getShearX () const constexpr noexcept
Get shearX component.
Returns the shearX component of the AffineTransform object.
Returns
The shearX component of this AffineTransform.
References shearX.
Referenced by toMat2D().
getTranslateX()
float yup::AffineTransform::getTranslateX () const constexpr noexcept
Get translateX component.
Returns the translateX component of the AffineTransform object.
Returns
The translateX component of this AffineTransform.
References translateX.
Referenced by toMat2D().
getShearY()
float yup::AffineTransform::getShearY () const constexpr noexcept
Get shearY component.
Returns the shearY component of the AffineTransform object.
Returns
The shearY component of this AffineTransform.
References shearY.
Referenced by toMat2D().
getScaleY()
float yup::AffineTransform::getScaleY () const constexpr noexcept
Get scaleY component.
Returns the scaleY component of the AffineTransform object.
Returns
The scaleY component of this AffineTransform.
References scaleY.
Referenced by toMat2D().
getTranslateY()
float yup::AffineTransform::getTranslateY () const constexpr noexcept
Get translateY component.
Returns the translateY component of the AffineTransform object.
Returns
The translateY component of this AffineTransform.
References translateY.
Referenced by toMat2D().
getMatrixPoints()
Span< const float > yup::AffineTransform::getMatrixPoints () const nodiscard constexpr noexcept
Get span of matrix array.
Returns a span of constant values of the underlying array representing the matrix components of the AffineTransform.
Returns
A span to constant matrix components array.
References m.
isIdentity()
bool yup::AffineTransform::isIdentity () const constexpr noexcept
Check if the transformation is the identity matrix.
Checks if the AffineTransform object represents the identity transformation, which does not modify any points.
Returns
True if this is the identity transformation, false otherwise.
References AffineTransform().
Referenced by yup::Component::isTransformed().
resetToIdentity()
AffineTransform & yup::AffineTransform::resetToIdentity () constexpr noexcept
Reset to identity transformation.
Resets the AffineTransform to the identity transformation, which does not modify any points that it is applied to.
Returns
A reference to this reset AffineTransform object.
References AffineTransform(), and identity().
identity()
constexpr AffineTransform yup::AffineTransform::identity () static nodiscard constexpr noexcept
Create identity transformation.
Creates an AffineTransform object representing the identity transformation, which does not modify any points.
Returns
An AffineTransform object initialized as the identity transformation.
References AffineTransform().
Referenced by AffineTransform(), resetToIdentity(), rotation(), and rotation().
inverted()
AffineTransform yup::AffineTransform::inverted () const nodiscard constexpr noexcept
Create an inverted transformation.
Creates a new AffineTransform object that represents this transformation inverted, or the identity.
Returns
A new AffineTransform object representing the inverted transformation.
References AffineTransform(), yup::approximatelyEqual(), getDeterminant(), and m.
translated()
AffineTransform yup::AffineTransform::translated (float tx, float ty) const nodiscard constexpr noexcept
Create a translated transformation.
Creates a new AffineTransform object that represents this transformation translated by specified amounts in the x and y directions.
Parameters
tx The amount to translate in the x-direction.
ty The amount to translate in the y-direction.
Returns
A new AffineTransform object representing the translated transformation.
References AffineTransform(), scaleX, scaleY, shearX, shearY, translateX, and translateY.
Referenced by yup::Graphics::clipPath(), and yup::Path::scaleToFit().
translation()
constexpr AffineTransform yup::AffineTransform::translation (float tx, float ty) static nodiscard constexpr noexcept
Create a translation transformation.
Creates an AffineTransform object representing a translation by specified amounts in the x and y directions.
Parameters
tx The amount to translate in the x-direction.
ty The amount to translate in the y-direction.
Returns
An AffineTransform object representing the specified translation.
References AffineTransform().
withAbsoluteTranslation()
AffineTransform yup::AffineTransform::withAbsoluteTranslation (float tx, float ty) const nodiscard constexpr noexcept
Create a translated transformation.
Creates a new AffineTransform object that represents this transformation translated absolutely in the x and y directions.
Parameters
tx The absolute amount to translate in the x-direction.
ty The absolute amount to translate in the y-direction.
Returns
A new AffineTransform object representing the translated transformation.
References AffineTransform(), scaleX, scaleY, shearX, and shearY.
rotated() [1/2]
AffineTransform yup::AffineTransform::rotated (float angleInRadians) const nodiscard constexpr noexcept
Create a rotated transformation.
Creates a new AffineTransform object that represents this transformation rotated by a specified angle around the origin.
Parameters
angleInRadians The angle in radians by which to rotate.
Returns
A new AffineTransform object representing the rotated transformation.
References AffineTransform(), scaleX, scaleY, shearX, shearY, translateX, and translateY.
rotated() [2/2]
AffineTransform yup::AffineTransform::rotated (float angleInRadians, float centerX, float centerY) const nodiscard constexpr noexcept
Create a rotated transformation around a point.
Creates a new AffineTransform object that represents this transformation rotated by a specified angle around a specified point.
Parameters
angleInRadians The angle in radians by which to rotate.
centerX The x-coordinate of the point around which to rotate.
centerY The y-coordinate of the point around which to rotate.
Returns
A new AffineTransform object representing the rotated transformation.
References AffineTransform(), followedBy(), and rotation().
rotation() [1/2]
constexpr AffineTransform yup::AffineTransform::rotation (float angleInRadians) static nodiscard constexpr noexcept
Create a rotation transformation.
Creates an AffineTransform object representing a rotation by a specified angle around the origin.
Parameters
angleInRadians The angle in radians by which to rotate.
Returns
An AffineTransform object representing the specified rotation.
References AffineTransform(), and identity().
Referenced by rotated().
rotation() [2/2]
constexpr AffineTransform yup::AffineTransform::rotation (float angleInRadians, float centerX, float centerY) static nodiscard constexpr noexcept
Create a rotation transformation around a point.
Creates an AffineTransform object representing a rotation by a specified angle around a specified point.
Parameters
angleInRadians The angle in radians by which to rotate.
centerX The x-coordinate of the point around which to rotate.
centerY The y-coordinate of the point around which to rotate.
Returns
An AffineTransform object representing the specified rotation around the point.
References AffineTransform(), and identity().
scaled() [1/3]
AffineTransform yup::AffineTransform::scaled (float factor) const nodiscard constexpr noexcept
Create a scaled transformation.
Creates a new AffineTransform object that represents this transformation scaled uniformly by a specified factor.
Parameters
factor The uniform scale factor to apply.
Returns
A new AffineTransform object representing the scaled transformation.
References AffineTransform(), scaleX, scaleY, shearX, shearY, translateX, and translateY.
Referenced by yup::Graphics::clipPath().
scaled() [2/3]
AffineTransform yup::AffineTransform::scaled (float factorX, float factorY) const nodiscard constexpr noexcept
Create a scaled transformation non-uniformly.
Creates a new AffineTransform object that represents this transformation scaled by specified factors along the x and y axes.
Parameters
factorX The scale factor to apply to the x-axis.
factorY The scale factor to apply to the y-axis.
Returns
A new AffineTransform object representing the non-uniformly scaled transformation.
References AffineTransform(), scaleX, scaleY, shearX, shearY, translateX, and translateY.
scaled() [3/3]
AffineTransform yup::AffineTransform::scaled (float factorX, float factorY, float centerX, float centerY) const nodiscard constexpr noexcept
Create a scaled transformation non-uniformly around a point.
Creates a new AffineTransform object that represents this transformation scaled by specified factors along the x and y axes around a specified point.
Parameters
factorX The scale factor to apply to the x-axis.
factorY The scale factor to apply to the y-axis.
centerX The x-coordinate of the center point for scaling.
centerY The y-coordinate of the center point for scaling.
Returns
A new AffineTransform object representing the non-uniformly scaled transformation around the point.
References AffineTransform(), scaleX, scaleY, shearX, shearY, translateX, and translateY.
scaling() [1/3]
constexpr AffineTransform yup::AffineTransform::scaling (float factor) static nodiscard constexpr noexcept
Create a scaling transformation.
Creates an AffineTransform object representing a uniform scaling by a specified factor.
Parameters
factor The uniform scale factor to apply.
Returns
An AffineTransform object representing the specified scaling.
References AffineTransform().
Referenced by yup::Path::scaleToFit().
scaling() [2/3]
constexpr AffineTransform yup::AffineTransform::scaling (float factorX, float factorY) static nodiscard constexpr noexcept
Create a scaling transformation non-uniformly.
Creates an AffineTransform object representing a non-uniform scaling by specified factors along the x and y axes.
Parameters
factorX The scale factor to apply to the x-axis.
factorY The scale factor to apply to the y-axis.
Returns
An AffineTransform object representing the specified non-uniform scaling.
References AffineTransform().
scaling() [3/3]
constexpr AffineTransform yup::AffineTransform::scaling (float factorX, float factorY, float centerX, float centerY) static nodiscard constexpr noexcept
Create a scaling transformation non-uniformly around a point.
Creates an AffineTransform object representing a non-uniform scaling by specified factors along the x and y axes around a specified point.
Parameters
factorX The scale factor to apply to the x-axis.
factorY The scale factor to apply to the y-axis.
centerX The x-coordinate of the center point for scaling.
centerY The y-coordinate of the center point for scaling.
Returns
An AffineTransform object representing the specified non-uniform scaling around the point.
References AffineTransform().
sheared()
AffineTransform yup::AffineTransform::sheared (float factorX, float factorY) const nodiscard constexpr noexcept
Create a sheared transformation.
Creates a new AffineTransform object that represents this transformation sheared by specified factors along the x and y axes.
Parameters
factorX The shear factor to apply to the x-axis.
factorY The shear factor to apply to the y-axis.
Returns
A new AffineTransform object representing the sheared transformation.
References AffineTransform(), scaleX, scaleY, shearX, shearY, translateX, and translateY.
shearing() [1/2]
constexpr AffineTransform yup::AffineTransform::shearing (float factorX, float factorY) static nodiscard constexpr noexcept
Create a shearing transformation.
Creates an AffineTransform object representing a shearing by specified factors along the x and y axes.
Parameters
factorX The shear factor to apply to the x-axis.
factorY The shear factor to apply to the y-axis.
Returns
An AffineTransform object representing the specified shearing.
References AffineTransform().
shearing() [2/2]
constexpr AffineTransform yup::AffineTransform::shearing (float factorX, float factorY, float centerX, float centerY) static nodiscard constexpr noexcept
Create a shearing transformation around a point.
Creates an AffineTransform object representing a shearing by specified factors along the x and y axes around a specified point.
Parameters
factorX The shear factor to apply to the x-axis.
factorY The shear factor to apply to the y-axis.
centerX The x-coordinate of the center point for shearing.
centerY The y-coordinate of the center point for shearing.
Returns
An AffineTransform object representing the specified shearing around the point.
References AffineTransform().
followedBy()
AffineTransform yup::AffineTransform::followedBy (const AffineTransform & other) const nodiscard constexpr noexcept
Create a transformation that follows another.
Creates a new AffineTransform object that represents this transformation followed by another specified AffineTransform.
Parameters
other The AffineTransform to follow this one.
Returns
A new AffineTransform object representing the combined transformation.
References AffineTransform(), scaleX, scaleY, shearX, shearY, translateX, and translateY.
Referenced by rotated().
prependedBy()
AffineTransform yup::AffineTransform::prependedBy (const AffineTransform & other) const nodiscard constexpr noexcept
References AffineTransform(), scaleX, scaleY, shearX, shearY, translateX, and translateY.
getDeterminant()
float yup::AffineTransform::getDeterminant () const nodiscard constexpr noexcept
References scaleX, scaleY, shearX, and shearY.
Referenced by inverted().
getScaleFactor()
float yup::AffineTransform::getScaleFactor () const nodiscard constexpr noexcept
References scaleX, scaleY, and yup::yup_abs().
transformPoint()
template<class T> void yup::AffineTransform::transformPoint (T & x, T & y) const constexpr noexcept
Transform a point.
Applies the transformation to a point represented by its x and y coordinates, modifying the coordinates in place.
Parameters
x A reference to the x-coordinate of the point.
y A reference to the y-coordinate of the point.
References scaleX, scaleY, shearX, shearY, translateX, and translateY.
Referenced by transformPoints().
transformPoints()
template<class T, class... Args> void yup::AffineTransform::transformPoints (T & x, T & y, Args &&... args) const constexpr noexcept
Transform multiple points.
Applies the transformation to multiple points, modifying each point's coordinates in place. This method handles pairs of coordinates and can process multiple pairs at once.
Parameters
x A reference to the x-coordinate of the first point.
y A reference to the y-coordinate of the first point.
args Additional pairs of coordinates to be transformed.
Returns
A tuple representing the transformed coordinates of the last point processed.
References transformPoint(), and transformPoints().
Referenced by transformPoints().
operator==()
bool yup::AffineTransform::operator== (const AffineTransform & other) const constexpr noexcept
Equality operator.
Compares this AffineTransform with another AffineTransform for equality.
Parameters
other A reference to the other AffineTransform to compare with.
Returns
True if all corresponding matrix components are equal, false otherwise.
References AffineTransform(), and m.
operator!=()
bool yup::AffineTransform::operator!= (const AffineTransform & other) const constexpr noexcept
Inequality operator.
Compares this AffineTransform with another AffineTransform for inequality.
Parameters
other A reference to the other AffineTransform to compare with.
Returns
True if any corresponding matrix components are not equal, false otherwise.
References AffineTransform().
toMat2D()
rive::Mat2D yup::AffineTransform::toMat2D () const
References getScaleX(), getScaleY(), getShearX(), getShearY(), getTranslateX(), and getTranslateY().
Referenced by yup::Path::transform(), and yup::Path::transformed().
Member Data Documentation
m
float yup::AffineTransform::m[6]
Referenced by getMatrixPoints(), inverted(), and operator==().
scaleX
float yup::AffineTransform::scaleX
Referenced by AffineTransform(), followedBy(), getDeterminant(), getScaleFactor(), getScaleX(), prependedBy(), rotated(), scaled(), scaled(), scaled(), sheared(), transformPoint(), translated(), and withAbsoluteTranslation().
shearX
float yup::AffineTransform::shearX
Referenced by AffineTransform(), followedBy(), getDeterminant(), getShearX(), prependedBy(), rotated(), scaled(), scaled(), scaled(), sheared(), transformPoint(), translated(), and withAbsoluteTranslation().
translateX
float yup::AffineTransform::translateX
Referenced by AffineTransform(), followedBy(), getTranslateX(), prependedBy(), rotated(), scaled(), scaled(), scaled(), sheared(), transformPoint(), and translated().
shearY
float yup::AffineTransform::shearY
Referenced by AffineTransform(), followedBy(), getDeterminant(), getShearY(), prependedBy(), rotated(), scaled(), scaled(), scaled(), sheared(), transformPoint(), translated(), and withAbsoluteTranslation().
scaleY
float yup::AffineTransform::scaleY
Referenced by AffineTransform(), followedBy(), getDeterminant(), getScaleFactor(), getScaleY(), prependedBy(), rotated(), scaled(), scaled(), scaled(), sheared(), transformPoint(), translated(), and withAbsoluteTranslation().
translateY
float yup::AffineTransform::translateY
Referenced by AffineTransform(), followedBy(), getTranslateY(), prependedBy(), rotated(), scaled(), scaled(), scaled(), sheared(), transformPoint(), and translated().