YUP: yup::FlagSet< T, Ts > Class Template Reference
yup::FlagSet< T, Ts > Class Template Reference
Manages a set of flags using integral types.
Public Member Functions
constexpr FlagSet () noexcept=default
Constructs a default FlagSet with all flags cleared.
constexpr void set (FlagSet other) noexcept
Sets flags that are set in another FlagSet to this one.
constexpr FlagSet withSet (FlagSet other) const noexcept
Creates a new FlagSet with combined flags from this and another FlagSet.
constexpr void unset (FlagSet other) noexcept
Unsets flags that are set in another FlagSet from this one.
constexpr FlagSet withUnset (FlagSet other) const noexcept
Creates a new FlagSet with flags unset from this one based on another FlagSet.
constexpr bool test (FlagSet other) const noexcept
Tests if any flags from another FlagSet are set in this one.
constexpr FlagSet operator| (FlagSet other) const noexcept
Binary OR operator to combine flags from two FlagSets.
constexpr FlagSet & operator|= (FlagSet other) noexcept
Binary OR operator to combine this FlagSet with another.
constexpr FlagSet operator& (FlagSet other) const noexcept
Binary AND operator to intersect flags from two FlagSets.
constexpr FlagSet & operator&= (FlagSet other) noexcept
Binary AND operator to combine this FlagSet with another.
constexpr FlagSet operator~ () const noexcept
Unary NOT operator to invert flags in the FlagSet.
constexpr bool operator== (const FlagSet &other) const noexcept
Equality operator between two FlagSet.
constexpr bool operator!= (const FlagSet &other) const noexcept
Inequality operator between two FlagSet.
String toString () const
Converts the flag bits to a string representation.
Static Public Member Functions
template<class... Us>
static constexpr FlagSet declareValue () noexcept
Declares a new FlagSet with specific flags set using template parameters.
static FlagSet fromString (const String &text)
Converts a string of '0' and '1' to a flag set.
Detailed Description
template<class T, class... Ts>
class yup::FlagSet< T, Ts >
Manages a set of flags using integral types.
The FlagSet class is designed to operate on flags efficiently using bitwise operations. It utilizes templates to support any integral type as a flag container, ensuring type safety and compile-time checks. It can be used to manipulate sets of options or features represented as bits within an integral type. This class allows setting, unsetting, testing, and combining flag sets, as well as creating custom flag sets from specified bits.
Template Parameters
T An integral type used for storing the flags.
Ts Variadic template types representing individual flag positions or meanings.
namespace detail {
struct verboseLog;
struct noErrorLog;
}
using LogOption = FlagSet<uint32, detail::verboseLog, detail::noErrorLog>;
static inline constexpr LogOption defaultLog = LogOption();
static inline constexpr LogOption verboseLog = LogOption::declareValue<detail::verboseLog>();
static inline constexpr LogOption noErrorLog = LogOption::declareValue<detail::noErrorLog>();
LogOption option = verboseLog | noErrorLog;
if (option.test (verboseLog))
    ...
Constructor & Destructor Documentation
FlagSet()
template<class T, class... Ts> yup::FlagSet< T, Ts >::FlagSet () constexpr default noexcept
Constructs a default FlagSet with all flags cleared.
Referenced by yup::FlagSet< uint32, decoratedWindowTag, resizableWindowTag, renderContinuousTag, allowHighDensityDisplayTag >::fromString(), yup::FlagSet< uint32, decoratedWindowTag, resizableWindowTag, renderContinuousTag, allowHighDensityDisplayTag >::operator&(), yup::FlagSet< uint32, decoratedWindowTag, resizableWindowTag, renderContinuousTag, allowHighDensityDisplayTag >::operator|(), and yup::FlagSet< uint32, decoratedWindowTag, resizableWindowTag, renderContinuousTag, allowHighDensityDisplayTag >::operator~().
Member Function Documentation
declareValue()
template<class T, class... Ts> template<class... Us> constexpr FlagSet yup::FlagSet< T, Ts >::declareValue () static constexpr noexcept
Declares a new FlagSet with specific flags set using template parameters.
Utilizes template metaprogramming to generate a FlagSet with flags set at positions determined by the template arguments relative to the base template types. This static method allows for compile-time declaration of flag values.
Template Parameters
Us Variadic template types used to determine which flags to set.
Returns
A FlagSet with the specified flags set.
set()
template<class T, class... Ts> void yup::FlagSet< T, Ts >::set (FlagSet< T, Ts > other) constexpr noexcept
Sets flags that are set in another FlagSet to this one.
Performs a bitwise OR on the current flags with another set of flags, modifying this FlagSet to include all lags that are either already set or set in the other FlagSet.
Parameters
other Another FlagSet whose flags are to be set in this FlagSet.
withSet()
template<class T, class... Ts> FlagSet yup::FlagSet< T, Ts >::withSet (FlagSet< T, Ts > other) const constexpr noexcept
Creates a new FlagSet with combined flags from this and another FlagSet.
Returns a new FlagSet resulting from the bitwise OR of this FlagSet's flags and another FlagSet's flags. This method does not modify the original FlagSet.
Parameters
other Another FlagSet whose flags are combined with this one.
Returns
A new FlagSet with the combined flags.
unset()
template<class T, class... Ts> void yup::FlagSet< T, Ts >::unset (FlagSet< T, Ts > other) constexpr noexcept
Unsets flags that are set in another FlagSet from this one.
Performs a bitwise AND with the complement of the other FlagSet's flags, effectively unsetting flags that are set in the other FlagSet.
Parameters
other Another FlagSet whose flags are to be unset in this FlagSet.
withUnset()
template<class T, class... Ts> FlagSet yup::FlagSet< T, Ts >::withUnset (FlagSet< T, Ts > other) const constexpr noexcept
Creates a new FlagSet with flags unset from this one based on another FlagSet.
Returns a new FlagSet resulting from the bitwise AND of this FlagSet's flags with the complement of another FlagSet's flags. This method creates a new FlagSet with specific flags unset.
Parameters
other Another FlagSet whose flags are used to unset flags from this FlagSet.
Returns
A new FlagSet with the specified flags unset.
test()
template<class T, class... Ts> bool yup::FlagSet< T, Ts >::test (FlagSet< T, Ts > other) const constexpr noexcept
Tests if any flags from another FlagSet are set in this one.
Checks if any flags that are set in another FlagSet are also set in this FlagSet using a bitwise AND operation.
Parameters
other Another FlagSet to test against this FlagSet.
Returns
True if any flags are both set in this and the other FlagSet, false otherwise.
operator|()
template<class T, class... Ts> FlagSet yup::FlagSet< T, Ts >::operator| (FlagSet< T, Ts > other) const constexpr noexcept
Binary OR operator to combine flags from two FlagSets.
Combines the flags of this FlagSet with another by performing a bitwise OR operation, producing a new FlagSet.
Parameters
other Another FlagSet to combine with this one.
Returns
A new FlagSet with the combined flags.
operator|=()
template<class T, class... Ts> FlagSet & yup::FlagSet< T, Ts >::operator|= (FlagSet< T, Ts > other) constexpr noexcept
Binary OR operator to combine this FlagSet with another.
Combines the flags of this FlagSet with another by performing a bitwise OR operation.
Parameters
other Another FlagSet to combine with this one.
Returns
The current FlagSet.
operator&()
template<class T, class... Ts> FlagSet yup::FlagSet< T, Ts >::operator& (FlagSet< T, Ts > other) const constexpr noexcept
Binary AND operator to intersect flags from two FlagSets.
Produces a new FlagSet containing only the flags that are set in both this and another FlagSet by performing a bitwise AND operation.
Parameters
other Another FlagSet to intersect with this one.
Returns
A new FlagSet with the intersected flags.
operator&=()
template<class T, class... Ts> FlagSet & yup::FlagSet< T, Ts >::operator&= (FlagSet< T, Ts > other) constexpr noexcept
Binary AND operator to combine this FlagSet with another.
Combines the flags of this FlagSet with another by performing a bitwise AND operation.
Parameters
other Another FlagSet to combine with this one.
Returns
The current FlagSet.
operator~()
template<class T, class... Ts> FlagSet yup::FlagSet< T, Ts >::operator~ () const constexpr noexcept
Unary NOT operator to invert flags in the FlagSet.
Creates a new FlagSet where all flags are inverted (i.e., 1's become 0's and vice versa) from this FlagSet.
Returns
A new FlagSet with all flags inverted.
operator==()
template<class T, class... Ts> bool yup::FlagSet< T, Ts >::operator== (const FlagSet< T, Ts > & other) const constexpr noexcept
Equality operator between two FlagSet.
operator!=()
template<class T, class... Ts> bool yup::FlagSet< T, Ts >::operator!= (const FlagSet< T, Ts > & other) const constexpr noexcept
Inequality operator between two FlagSet.
toString()
template<class T, class... Ts> String yup::FlagSet< T, Ts >::toString () const
Converts the flag bits to a string representation.
Constructs a binary string representation of the flags, where each bit is represented by '1' or '0'.
Returns
A string representing the binary state of the flags.
fromString()
template<class T, class... Ts> FlagSet yup::FlagSet< T, Ts >::fromString (const String & text) static
Converts a string of '0' and '1' to a flag set.
Returns
A string representing the binary state of the flags.