YUP: yup::ComponentStyle Class Reference
yup::ComponentStyle Class Reference abstract
The ComponentStyle class is the base class for all components styles.
Public Types
using Ptr = ReferenceCountedObjectPtr<ComponentStyle>
A pointer to a ComponentStyle object.
using ConstPtr = ReferenceCountedObjectPtr<const ComponentStyle>
A pointer to a const ComponentStyle object.
Public Member Functions
virtual ~ComponentStyle ()=default
Destructor.
virtual void paint (Graphics &g, const ApplicationTheme &theme, const Component &component)=0
Paints the component with the specified style.
Public Member Functions inherited from yup::ReferenceCountedObject
void incReferenceCount () const noexcept
Increments the object's reference count.
void decReferenceCount () const noexcept
Decreases the object's reference count.
bool decReferenceCountWithoutDeleting () const noexcept
Decreases the object's reference count.
int getReferenceCount () const noexcept
Returns the object's current reference count.
Static Public Member Functions
template<class ComponentType, class F>
static ComponentStyle::Ptr createStyle (F &&paintCallback)
Creates a style for a specific component type with a custom paint callback.
Protected Member Functions
ComponentStyle ()=default
Protected Member Functions inherited from yup::ReferenceCountedObject
ReferenceCountedObject ()=default
Creates the reference-counted object (with an initial ref count of zero).
ReferenceCountedObject (const ReferenceCountedObject &) noexcept
Copying from another object does not affect this one's reference-count.
ReferenceCountedObject (ReferenceCountedObject &&) noexcept
Copying from another object does not affect this one's reference-count.
ReferenceCountedObject & operator= (const ReferenceCountedObject &) noexcept
Copying from another object does not affect this one's reference-count.
ReferenceCountedObject & operator= (ReferenceCountedObject &&) noexcept
Copying from another object does not affect this one's reference-count.
virtual ~ReferenceCountedObject ()
Destructor.
void resetReferenceCount () const noexcept
Resets the reference count to zero without deleting the object.
Detailed Description
The ComponentStyle class is the base class for all components styles.
Member Typedef Documentation
Ptr
using yup::ComponentStyle::Ptr = ReferenceCountedObjectPtr<ComponentStyle>
A pointer to a ComponentStyle object.
ConstPtr
using yup::ComponentStyle::ConstPtr = ReferenceCountedObjectPtr<const ComponentStyle>
A pointer to a const ComponentStyle object.
Constructor & Destructor Documentation
~ComponentStyle()
virtual yup::ComponentStyle::~ComponentStyle () virtual default
Destructor.
ComponentStyle()
yup::ComponentStyle::ComponentStyle () protected default
Referenced by createStyle().
Member Function Documentation
paint()
virtual void yup::ComponentStyle::paint (Graphics & g, const ApplicationTheme & theme, const Component & component) pure virtual
Paints the component with the specified style.
This is the main method that derived classes must implement to define how a component should be painted with this style.
Parameters
g The graphics context to use for drawing.
theme The application theme to use when painting.
component The component to be painted.
Referenced by createStyle().
createStyle()
template<class ComponentType, class F> ComponentStyle::Ptr yup::ComponentStyle::createStyle (F && paintCallback) static
Creates a style for a specific component type with a custom paint callback.
This factory method creates a ComponentStyle that will call the provided paint callback when the component needs to be painted. The callback will receive a reference to the component cast to the specified ComponentType.
Parameters
paintCallback A function or lambda that will be called to paint the component.
Returns
A new ComponentStyle object that uses the provided paint callback.
// Example usage:
auto buttonStyle = ComponentStyle::createStyle<Button>(
    [](Graphics& g, const ApplicationTheme& theme, const Button& button) {
        // Custom painting code for buttons
    });
References ComponentStyle(), and paint().
Referenced by yup::createThemeVersion1().