YUP: yup::ADSR Class Reference
yup::ADSR Class Reference
A very simple ADSR envelope class.
Classes
struct Parameters
Holds the parameters being used by an ADSR object.
Public Member Functions
ADSR ()
void setParameters (const Parameters &newParameters)
Sets the parameters that will be used by an ADSR object.
const Parameters & getParameters () const noexcept
Returns the parameters currently being used by an ADSR object.
bool isActive () const noexcept
Returns true if the envelope is in its attack, decay, sustain or release stage.
void setSampleRate (double newSampleRate) noexcept
Sets the sample rate that will be used for the envelope.
void reset () noexcept
Resets the envelope to an idle state.
void noteOn () noexcept
Starts the attack phase of the envelope.
void noteOff () noexcept
Starts the release phase of the envelope.
float getNextSample () noexcept
Returns the next sample value for an ADSR object.
template<typename FloatType>
void applyEnvelopeToBuffer (AudioBuffer< FloatType > &buffer, int startSample, int numSamples)
This method will conveniently apply the next numSamples number of envelope values to an AudioBuffer.
Detailed Description
A very simple ADSR envelope class.
To use it, call setSampleRate() with the current sample rate and give it some parameters with setParameters() then call getNextSample() to get the envelope value to be applied to each audio sample or applyEnvelopeToBuffer() to apply the envelope to a whole buffer.
Do not change the parameters during playback. If you change the parameters before the release stage has completed then you must call reset() before the next call to noteOn().
Constructor & Destructor Documentation
ADSR()
yup::ADSR::ADSR ()
Member Function Documentation
setParameters()
void yup::ADSR::setParameters (const Parameters & newParameters)
Sets the parameters that will be used by an ADSR object.
You must have called setSampleRate() with the correct sample rate before this otherwise the values may be incorrect!
See also
getParameters
getParameters()
const Parameters & yup::ADSR::getParameters () const noexcept
Returns the parameters currently being used by an ADSR object.
See also
setParameters
isActive()
bool yup::ADSR::isActive () const noexcept
Returns true if the envelope is in its attack, decay, sustain or release stage.
setSampleRate()
void yup::ADSR::setSampleRate (double newSampleRate) noexcept
Sets the sample rate that will be used for the envelope.
This must be called before the getNextSample() or setParameters() methods.
reset()
void yup::ADSR::reset () noexcept
Resets the envelope to an idle state.
Referenced by noteOff().
noteOn()
void yup::ADSR::noteOn () noexcept
Starts the attack phase of the envelope.
noteOff()
void yup::ADSR::noteOff () noexcept
Starts the release phase of the envelope.
References reset().
getNextSample()
float yup::ADSR::getNextSample () noexcept
Returns the next sample value for an ADSR object.
See also
applyEnvelopeToBuffer
Referenced by applyEnvelopeToBuffer().
applyEnvelopeToBuffer()
template<typename FloatType> void yup::ADSR::applyEnvelopeToBuffer (AudioBuffer< FloatType > & buffer, int startSample, int numSamples)
This method will conveniently apply the next numSamples number of envelope values to an AudioBuffer.
See also
getNextSample
References yup::AudioBuffer< Type >::applyGain(), yup::AudioBuffer< Type >::clear(), getNextSample(), yup::AudioBuffer< Type >::getNumChannels(), yup::AudioBuffer< Type >::getNumSamples(), and yup::AudioBuffer< Type >::getWritePointer().