YUP: yup::RelativeTime Class Reference
yup::RelativeTime Class Reference
A relative measure of time.
Public Member Functions
RelativeTime (double seconds=0.0) noexcept
Creates a RelativeTime.
RelativeTime (const RelativeTime &other) noexcept
Copies another relative time.
RelativeTime & operator= (const RelativeTime &other) noexcept
Copies another relative time.
~RelativeTime () noexcept
Destructor.
int64 inMilliseconds () const noexcept
Returns the number of milliseconds this time represents.
double inSeconds () const noexcept
Returns the number of seconds this time represents.
double inMinutes () const noexcept
Returns the number of minutes this time represents.
double inHours () const noexcept
Returns the number of hours this time represents.
double inDays () const noexcept
Returns the number of days this time represents.
double inWeeks () const noexcept
Returns the number of weeks this time represents.
String getDescription (const String &returnValueForZeroTime="0") const
Returns a readable textual description of the time.
String getApproximateDescription () const
This returns a string that roughly describes how long ago this time was, which can be handy for showing ages of files, etc.
RelativeTime operator+= (RelativeTime timeToAdd) noexcept
Adds another RelativeTime to this one.
RelativeTime operator-= (RelativeTime timeToSubtract) noexcept
Subtracts another RelativeTime from this one.
RelativeTime operator+= (double secondsToAdd) noexcept
Adds a number of seconds to this time.
RelativeTime operator-= (double secondsToSubtract) noexcept
Subtracts a number of seconds from this time.
Static Public Member Functions
static RelativeTime milliseconds (int milliseconds) noexcept
Creates a new RelativeTime object representing a number of milliseconds.
static RelativeTime milliseconds (int64 milliseconds) noexcept
Creates a new RelativeTime object representing a number of milliseconds.
static RelativeTime seconds (double seconds) noexcept
Creates a new RelativeTime object representing a number of seconds.
static RelativeTime minutes (double numberOfMinutes) noexcept
Creates a new RelativeTime object representing a number of minutes.
static RelativeTime hours (double numberOfHours) noexcept
Creates a new RelativeTime object representing a number of hours.
static RelativeTime days (double numberOfDays) noexcept
Creates a new RelativeTime object representing a number of days.
static RelativeTime weeks (double numberOfWeeks) noexcept
Creates a new RelativeTime object representing a number of weeks.
Detailed Description
A relative measure of time.
The time is stored as a number of seconds, at double-precision floating point accuracy, and may be positive or negative.
If you need an absolute time, (i.e. a date + time), see the Time class.
Constructor & Destructor Documentation
RelativeTime() [1/2]
yup::RelativeTime::RelativeTime (double seconds = 0.0) explicit noexcept
Creates a RelativeTime.
Parameters
seconds the number of seconds, which may be +ve or -ve.
See also
milliseconds, minutes, hours, days, weeks
Referenced by days(), getDescription(), hours(), milliseconds(), milliseconds(), minutes(), operator+=(), operator+=(), operator-=(), operator-=(), operator=(), RelativeTime(), seconds(), and weeks().
RelativeTime() [2/2]
yup::RelativeTime::RelativeTime (const RelativeTime & other) noexcept
Copies another relative time.
References RelativeTime().
~RelativeTime()
yup::RelativeTime::~RelativeTime () noexcept
Destructor.
Member Function Documentation
operator=()
RelativeTime & yup::RelativeTime::operator= (const RelativeTime & other) noexcept
Copies another relative time.
References RelativeTime().
milliseconds() [1/2]
RelativeTime yup::RelativeTime::milliseconds (int milliseconds) static noexcept
Creates a new RelativeTime object representing a number of milliseconds.
See also
seconds, minutes, hours, days, weeks
References milliseconds(), and RelativeTime().
Referenced by yup::TimeSliceThread::addTimeSliceClient(), milliseconds(), milliseconds(), and yup::operator-().
milliseconds() [2/2]
RelativeTime yup::RelativeTime::milliseconds (int64 milliseconds) static noexcept
Creates a new RelativeTime object representing a number of milliseconds.
See also
seconds, minutes, hours, days, weeks
References milliseconds(), and RelativeTime().
seconds()
RelativeTime yup::RelativeTime::seconds (double seconds) static noexcept
Creates a new RelativeTime object representing a number of seconds.
See also
milliseconds, minutes, hours, days, weeks
References RelativeTime().
minutes()
RelativeTime yup::RelativeTime::minutes (double numberOfMinutes) static noexcept
Creates a new RelativeTime object representing a number of minutes.
See also
milliseconds, hours, days, weeks
References RelativeTime().
Referenced by getApproximateDescription().
hours()
RelativeTime yup::RelativeTime::hours (double numberOfHours) static noexcept
Creates a new RelativeTime object representing a number of hours.
See also
milliseconds, minutes, days, weeks
References RelativeTime().
Referenced by getApproximateDescription().
days()
RelativeTime yup::RelativeTime::days (double numberOfDays) static noexcept
Creates a new RelativeTime object representing a number of days.
See also
milliseconds, minutes, hours, weeks
References RelativeTime().
Referenced by getApproximateDescription().
weeks()
RelativeTime yup::RelativeTime::weeks (double numberOfWeeks) static noexcept
Creates a new RelativeTime object representing a number of weeks.
See also
milliseconds, minutes, hours, days
References RelativeTime().
Referenced by getApproximateDescription().
inMilliseconds()
int64 yup::RelativeTime::inMilliseconds () const noexcept
Returns the number of milliseconds this time represents.
See also
milliseconds, inSeconds, inMinutes, inHours, inDays, inWeeks
Referenced by getDescription().
inSeconds()
double yup::RelativeTime::inSeconds () const noexcept
Returns the number of seconds this time represents.
See also
inMilliseconds, inMinutes, inHours, inDays, inWeeks
Referenced by getDescription().
inMinutes()
double yup::RelativeTime::inMinutes () const noexcept
Returns the number of minutes this time represents.
See also
inMilliseconds, inSeconds, inHours, inDays, inWeeks
Referenced by getApproximateDescription(), and getDescription().
inHours()
double yup::RelativeTime::inHours () const noexcept
Returns the number of hours this time represents.
See also
inMilliseconds, inSeconds, inMinutes, inDays, inWeeks
Referenced by getApproximateDescription(), and getDescription().
inDays()
double yup::RelativeTime::inDays () const noexcept
Returns the number of days this time represents.
See also
inMilliseconds, inSeconds, inMinutes, inHours, inWeeks
Referenced by getApproximateDescription(), and getDescription().
inWeeks()
double yup::RelativeTime::inWeeks () const noexcept
Returns the number of weeks this time represents.
See also
inMilliseconds, inSeconds, inMinutes, inHours, inDays
Referenced by getApproximateDescription(), and getDescription().
getDescription()
String yup::RelativeTime::getDescription (const String & returnValueForZeroTime = "0") const
Returns a readable textual description of the time.
The exact format of the string returned will depend on the magnitude of the time - e.g.
"1 min 4 secs", "1 hr 45 mins", "2 weeks 5 days", "140 ms"
so that only the two most significant units are printed.
The returnValueForZeroTime value is the result that is returned if the length is zero. Depending on your application you might want to use this to return something more relevant like "empty" or "0 secs", etc.
See also
inMilliseconds, inSeconds, inMinutes, inHours, inDays, inWeeks
References yup::StringArray::add(), inDays(), inHours(), inMilliseconds(), inMinutes(), inSeconds(), inWeeks(), yup::StringArray::isEmpty(), yup::StringArray::joinIntoString(), RelativeTime(), and yup::StringArray::size().
getApproximateDescription()
String yup::RelativeTime::getApproximateDescription () const
This returns a string that roughly describes how long ago this time was, which can be handy for showing ages of files, etc.
This will only attempt to be accurate to within the nearest order of magnitude so returns strings such as "5 years", "2 weeks", "< 1 minute", "< 1 sec" etc.
References days(), hours(), inDays(), inHours(), inMinutes(), inWeeks(), minutes(), and weeks().
operator+=() [1/2]
RelativeTime yup::RelativeTime::operator+= (RelativeTime timeToAdd) noexcept
Adds another RelativeTime to this one.
References RelativeTime().
operator-=() [1/2]
RelativeTime yup::RelativeTime::operator-= (RelativeTime timeToSubtract) noexcept
Subtracts another RelativeTime from this one.
References RelativeTime().
operator+=() [2/2]
RelativeTime yup::RelativeTime::operator+= (double secondsToAdd) noexcept
Adds a number of seconds to this time.
References RelativeTime().
operator-=() [2/2]
RelativeTime yup::RelativeTime::operator-= (double secondsToSubtract) noexcept
Subtracts a number of seconds from this time.
References RelativeTime().