YUP: yup::CharPointer_ASCII Class Reference
yup::CharPointer_ASCII Class Reference final
Wraps a pointer to a null-terminated ASCII character string, and provides various methods to operate on the data.
Public Types
using CharType = char
Public Member Functions
CharPointer_ASCII (const CharType *rawPointer) noexcept
CharPointer_ASCII (const CharPointer_ASCII &other)=default
CharPointer_ASCII operator= (const CharPointer_ASCII other) noexcept
CharPointer_ASCII operator= (const CharType *text) noexcept
bool operator== (CharPointer_ASCII other) const noexcept
This is a pointer comparison, it doesn't compare the actual text.
bool operator!= (CharPointer_ASCII other) const noexcept
bool operator<= (CharPointer_ASCII other) const noexcept
bool operator< (CharPointer_ASCII other) const noexcept
bool operator>= (CharPointer_ASCII other) const noexcept
bool operator> (CharPointer_ASCII other) const noexcept
CharType * getAddress () const noexcept
Returns the address that this pointer is pointing to.
operator const CharType * () const noexcept
Returns the address that this pointer is pointing to.
bool isEmpty () const noexcept
Returns true if this pointer is pointing to a null character.
bool isNotEmpty () const noexcept
Returns true if this pointer is not pointing to a null character.
yup_wchar operator* () const noexcept
Returns the unicode character that this pointer is pointing to.
CharPointer_ASCII operator++ () noexcept
Moves this pointer along to the next character in the string.
CharPointer_ASCII operator-- () noexcept
Moves this pointer to the previous character in the string.
yup_wchar getAndAdvance () noexcept
Returns the character that this pointer is currently pointing to, and then advances the pointer to point to the next character.
CharPointer_ASCII operator++ (int) noexcept
Moves this pointer along to the next character in the string.
void operator+= (const int numToSkip) noexcept
Moves this pointer forwards by the specified number of characters.
void operator-= (const int numToSkip) noexcept
yup_wchar operator[] (const int characterIndex) const noexcept
Returns the character at a given character index from the start of the string.
CharPointer_ASCII operator+ (const int numToSkip) const noexcept
Returns a pointer which is moved forwards from this one by the specified number of characters.
CharPointer_ASCII operator- (const int numToSkip) const noexcept
Returns a pointer which is moved backwards from this one by the specified number of characters.
void write (const yup_wchar charToWrite) noexcept
Writes a unicode character to this string, and advances this pointer to point to the next position.
void replaceChar (const yup_wchar newChar) noexcept
void writeNull () const noexcept
Writes a null character to this string (leaving the pointer's position unchanged).
size_t length () const noexcept
Returns the number of characters in this string.
size_t lengthUpTo (const size_t maxCharsToCount) const noexcept
Returns the number of characters in this string, or the given value, whichever is lower.
size_t lengthUpTo (const CharPointer_ASCII end) const noexcept
Returns the number of characters in this string, or up to the given end pointer, whichever is lower.
size_t sizeInBytes () const noexcept
Returns the number of bytes that are used to represent this string.
CharPointer_ASCII findTerminatingNull () const noexcept
Returns a pointer to the null character that terminates this string.
template<typename CharPointer>
void writeAll (const CharPointer src) noexcept
Copies a source string to this pointer, advancing this pointer as it goes.
template<typename CharPointer>
size_t writeWithDestByteLimit (const CharPointer src, const size_t maxDestBytes) noexcept
Copies a source string to this pointer, advancing this pointer as it goes.
template<typename CharPointer>
void writeWithCharLimit (const CharPointer src, const int maxChars) noexcept
Copies a source string to this pointer, advancing this pointer as it goes.
template<typename CharPointer>
int compare (const CharPointer other) const noexcept
Compares this string with another one.
int compare (const CharPointer_ASCII other) const noexcept
Compares this string with another one.
template<typename CharPointer>
int compareUpTo (const CharPointer other, const int maxChars) const noexcept
Compares this string with another one, up to a specified number of characters.
int compareUpTo (const CharPointer_ASCII other, const int maxChars) const noexcept
Compares this string with another one, up to a specified number of characters.
template<typename CharPointer>
int compareIgnoreCase (const CharPointer other) const
Compares this string with another one.
int compareIgnoreCase (const CharPointer_ASCII other) const
template<typename CharPointer>
int compareIgnoreCaseUpTo (const CharPointer other, const int maxChars) const noexcept
Compares this string with another one, up to a specified number of characters.
template<typename CharPointer>
int indexOf (const CharPointer stringToFind) const noexcept
Returns the character index of a substring, or -1 if it isn't found.
int indexOf (const yup_wchar charToFind) const noexcept
Returns the character index of a unicode character, or -1 if it isn't found.
int indexOf (const yup_wchar charToFind, const bool ignoreCase) const noexcept
Returns the character index of a unicode character, or -1 if it isn't found.
bool isWhitespace () const
Returns true if the first character of this string is whitespace.
bool isDigit () const
Returns true if the first character of this string is a digit.
bool isLetter () const
Returns true if the first character of this string is a letter.
bool isLetterOrDigit () const
Returns true if the first character of this string is a letter or digit.
bool isUpperCase () const
Returns true if the first character of this string is upper-case.
bool isLowerCase () const
Returns true if the first character of this string is lower-case.
yup_wchar toUpperCase () const noexcept
Returns an upper-case version of the first character of this string.
yup_wchar toLowerCase () const noexcept
Returns a lower-case version of the first character of this string.
int getIntValue32 () const noexcept
Parses this string as a 32-bit integer.
int64 getIntValue64 () const noexcept
Parses this string as a 64-bit integer.
double getDoubleValue () const noexcept
Parses this string as a floating point double.
CharPointer_ASCII findEndOfWhitespace () const noexcept
Returns the first non-whitespace character in the string.
void incrementToEndOfWhitespace () noexcept
Move this pointer to the first non-whitespace character in the string.
Static Public Member Functions
static size_t getBytesRequiredFor (const yup_wchar) noexcept
Returns the number of bytes that would be needed to represent the given unicode character in this encoding format.
template<class CharPointer>
static size_t getBytesRequiredFor (const CharPointer text) noexcept
Returns the number of bytes that would be needed to represent the given string in this encoding format.
static bool canRepresent (yup_wchar character) noexcept
Returns true if the given unicode character can be represented in this encoding.
static bool isValidString (const CharType *dataToTest, int maxBytesToRead)
Returns true if this data contains a valid string in this encoding.
Detailed Description
Wraps a pointer to a null-terminated ASCII character string, and provides various methods to operate on the data.
A valid ASCII string is assumed to not contain any characters above 127.
See also
CharPointer_UTF8, CharPointer_UTF16, CharPointer_UTF32
Member Typedef Documentation
CharType
using yup::CharPointer_ASCII::CharType = char
Constructor & Destructor Documentation
CharPointer_ASCII() [1/2]
yup::CharPointer_ASCII::CharPointer_ASCII (const CharType * rawPointer) explicit noexcept
Referenced by CharPointer_ASCII(), compare(), compareIgnoreCase(), compareUpTo(), findEndOfWhitespace(), findTerminatingNull(), lengthUpTo(), operator!=(), operator+(), operator++(), operator++(), operator-(), operator--(), operator<(), operator<=(), operator=(), operator=(), operator==(), operator>(), and operator>=().
CharPointer_ASCII() [2/2]
yup::CharPointer_ASCII::CharPointer_ASCII (const CharPointer_ASCII & other) default
References CharPointer_ASCII().
Member Function Documentation
operator=() [1/2]
CharPointer_ASCII yup::CharPointer_ASCII::operator= (const CharPointer_ASCII other) noexcept
References CharPointer_ASCII().
operator=() [2/2]
CharPointer_ASCII yup::CharPointer_ASCII::operator= (const CharType * text) noexcept
References CharPointer_ASCII().
operator==()
bool yup::CharPointer_ASCII::operator== (CharPointer_ASCII other) const noexcept
This is a pointer comparison, it doesn't compare the actual text.
References CharPointer_ASCII().
operator!=()
bool yup::CharPointer_ASCII::operator!= (CharPointer_ASCII other) const noexcept
References CharPointer_ASCII().
operator<=()
bool yup::CharPointer_ASCII::operator<= (CharPointer_ASCII other) const noexcept
References CharPointer_ASCII().
operator<()
bool yup::CharPointer_ASCII::operator< (CharPointer_ASCII other) const noexcept
References CharPointer_ASCII().
operator>=()
bool yup::CharPointer_ASCII::operator>= (CharPointer_ASCII other) const noexcept
References CharPointer_ASCII().
operator>()
bool yup::CharPointer_ASCII::operator> (CharPointer_ASCII other) const noexcept
References CharPointer_ASCII().
getAddress()
CharType * yup::CharPointer_ASCII::getAddress () const noexcept
Returns the address that this pointer is pointing to.
operator const CharType *()
yup::CharPointer_ASCII::operator const CharType * () const noexcept
Returns the address that this pointer is pointing to.
isEmpty()
bool yup::CharPointer_ASCII::isEmpty () const noexcept
Returns true if this pointer is pointing to a null character.
isNotEmpty()
bool yup::CharPointer_ASCII::isNotEmpty () const noexcept
Returns true if this pointer is not pointing to a null character.
operator*()
yup_wchar yup::CharPointer_ASCII::operator* () const noexcept
Returns the unicode character that this pointer is pointing to.
operator++() [1/2]
CharPointer_ASCII yup::CharPointer_ASCII::operator++ () noexcept
Moves this pointer along to the next character in the string.
References CharPointer_ASCII().
operator--()
CharPointer_ASCII yup::CharPointer_ASCII::operator-- () noexcept
Moves this pointer to the previous character in the string.
References CharPointer_ASCII().
getAndAdvance()
yup_wchar yup::CharPointer_ASCII::getAndAdvance () noexcept
Returns the character that this pointer is currently pointing to, and then advances the pointer to point to the next character.
operator++() [2/2]
CharPointer_ASCII yup::CharPointer_ASCII::operator++ (int) noexcept
Moves this pointer along to the next character in the string.
References CharPointer_ASCII().
operator+=()
void yup::CharPointer_ASCII::operator+= (const int numToSkip) noexcept
Moves this pointer forwards by the specified number of characters.
operator-=()
void yup::CharPointer_ASCII::operator-= (const int numToSkip) noexcept
operator[]()
yup_wchar yup::CharPointer_ASCII::operator[] (const int characterIndex) const noexcept
Returns the character at a given character index from the start of the string.
operator+()
CharPointer_ASCII yup::CharPointer_ASCII::operator+ (const int numToSkip) const noexcept
Returns a pointer which is moved forwards from this one by the specified number of characters.
References CharPointer_ASCII().
operator-()
CharPointer_ASCII yup::CharPointer_ASCII::operator- (const int numToSkip) const noexcept
Returns a pointer which is moved backwards from this one by the specified number of characters.
References CharPointer_ASCII().
write()
void yup::CharPointer_ASCII::write (const yup_wchar charToWrite) noexcept
Writes a unicode character to this string, and advances this pointer to point to the next position.
replaceChar()
void yup::CharPointer_ASCII::replaceChar (const yup_wchar newChar) noexcept
writeNull()
void yup::CharPointer_ASCII::writeNull () const noexcept
Writes a null character to this string (leaving the pointer's position unchanged).
length()
size_t yup::CharPointer_ASCII::length () const noexcept
Returns the number of characters in this string.
Referenced by findTerminatingNull(), and sizeInBytes().
lengthUpTo() [1/2]
size_t yup::CharPointer_ASCII::lengthUpTo (const size_t maxCharsToCount) const noexcept
Returns the number of characters in this string, or the given value, whichever is lower.
References yup::CharacterFunctions::lengthUpTo().
lengthUpTo() [2/2]
size_t yup::CharPointer_ASCII::lengthUpTo (const CharPointer_ASCII end) const noexcept
Returns the number of characters in this string, or up to the given end pointer, whichever is lower.
References CharPointer_ASCII(), yup::end(), and yup::CharacterFunctions::lengthUpTo().
sizeInBytes()
size_t yup::CharPointer_ASCII::sizeInBytes () const noexcept
Returns the number of bytes that are used to represent this string.
This includes the terminating null character.
References length().
getBytesRequiredFor() [1/2]
size_t yup::CharPointer_ASCII::getBytesRequiredFor (const yup_wchar) static noexcept
Returns the number of bytes that would be needed to represent the given unicode character in this encoding format.
getBytesRequiredFor() [2/2]
template<class CharPointer> size_t yup::CharPointer_ASCII::getBytesRequiredFor (const CharPointer text) static noexcept
Returns the number of bytes that would be needed to represent the given string in this encoding format.
The value returned does NOT include the terminating null character.
findTerminatingNull()
CharPointer_ASCII yup::CharPointer_ASCII::findTerminatingNull () const noexcept
Returns a pointer to the null character that terminates this string.
References CharPointer_ASCII(), and length().
writeAll()
template<typename CharPointer> void yup::CharPointer_ASCII::writeAll (const CharPointer src) noexcept
Copies a source string to this pointer, advancing this pointer as it goes.
References yup::CharacterFunctions::copyAll().
writeWithDestByteLimit()
template<typename CharPointer> size_t yup::CharPointer_ASCII::writeWithDestByteLimit (const CharPointer src, const size_t maxDestBytes) noexcept
Copies a source string to this pointer, advancing this pointer as it goes.
The maxDestBytes parameter specifies the maximum number of bytes that can be written to the destination buffer before stopping.
References yup::CharacterFunctions::copyWithDestByteLimit().
writeWithCharLimit()
template<typename CharPointer> void yup::CharPointer_ASCII::writeWithCharLimit (const CharPointer src, const int maxChars) noexcept
Copies a source string to this pointer, advancing this pointer as it goes.
The maxChars parameter specifies the maximum number of characters that can be written to the destination buffer before stopping (including the terminating null).
References yup::CharacterFunctions::copyWithCharLimit().
compare() [1/2]
template<typename CharPointer> int yup::CharPointer_ASCII::compare (const CharPointer other) const noexcept
Compares this string with another one.
References yup::CharacterFunctions::compare().
compare() [2/2]
int yup::CharPointer_ASCII::compare (const CharPointer_ASCII other) const noexcept
Compares this string with another one.
References CharPointer_ASCII().
compareUpTo() [1/2]
template<typename CharPointer> int yup::CharPointer_ASCII::compareUpTo (const CharPointer other, const int maxChars) const noexcept
Compares this string with another one, up to a specified number of characters.
References yup::CharacterFunctions::compareUpTo().
compareUpTo() [2/2]
int yup::CharPointer_ASCII::compareUpTo (const CharPointer_ASCII other, const int maxChars) const noexcept
Compares this string with another one, up to a specified number of characters.
References CharPointer_ASCII().
compareIgnoreCase() [1/2]
template<typename CharPointer> int yup::CharPointer_ASCII::compareIgnoreCase (const CharPointer other) const
Compares this string with another one.
References yup::CharacterFunctions::compareIgnoreCase().
compareIgnoreCase() [2/2]
int yup::CharPointer_ASCII::compareIgnoreCase (const CharPointer_ASCII other) const
References CharPointer_ASCII(), and yup::CharacterFunctions::compareIgnoreCase().
compareIgnoreCaseUpTo()
template<typename CharPointer> int yup::CharPointer_ASCII::compareIgnoreCaseUpTo (const CharPointer other, const int maxChars) const noexcept
Compares this string with another one, up to a specified number of characters.
References yup::CharacterFunctions::compareIgnoreCaseUpTo().
indexOf() [1/3]
template<typename CharPointer> int yup::CharPointer_ASCII::indexOf (const CharPointer stringToFind) const noexcept
Returns the character index of a substring, or -1 if it isn't found.
References yup::CharacterFunctions::indexOf().
indexOf() [2/3]
int yup::CharPointer_ASCII::indexOf (const yup_wchar charToFind) const noexcept
Returns the character index of a unicode character, or -1 if it isn't found.
indexOf() [3/3]
int yup::CharPointer_ASCII::indexOf (const yup_wchar charToFind, const bool ignoreCase) const noexcept
Returns the character index of a unicode character, or -1 if it isn't found.
References yup::CharacterFunctions::indexOfChar(), and yup::CharacterFunctions::indexOfCharIgnoreCase().
isWhitespace()
bool yup::CharPointer_ASCII::isWhitespace () const
Returns true if the first character of this string is whitespace.
References yup::CharacterFunctions::isWhitespace().
isDigit()
bool yup::CharPointer_ASCII::isDigit () const
Returns true if the first character of this string is a digit.
References yup::CharacterFunctions::isDigit().
isLetter()
bool yup::CharPointer_ASCII::isLetter () const
Returns true if the first character of this string is a letter.
References yup::CharacterFunctions::isLetter().
isLetterOrDigit()
bool yup::CharPointer_ASCII::isLetterOrDigit () const
Returns true if the first character of this string is a letter or digit.
References yup::CharacterFunctions::isLetterOrDigit().
isUpperCase()
bool yup::CharPointer_ASCII::isUpperCase () const
Returns true if the first character of this string is upper-case.
References yup::CharacterFunctions::isUpperCase().
isLowerCase()
bool yup::CharPointer_ASCII::isLowerCase () const
Returns true if the first character of this string is lower-case.
References yup::CharacterFunctions::isLowerCase().
toUpperCase()
yup_wchar yup::CharPointer_ASCII::toUpperCase () const noexcept
Returns an upper-case version of the first character of this string.
References yup::CharacterFunctions::toUpperCase().
toLowerCase()
yup_wchar yup::CharPointer_ASCII::toLowerCase () const noexcept
Returns a lower-case version of the first character of this string.
References yup::CharacterFunctions::toLowerCase().
getIntValue32()
int yup::CharPointer_ASCII::getIntValue32 () const noexcept
Parses this string as a 32-bit integer.
getIntValue64()
int64 yup::CharPointer_ASCII::getIntValue64 () const noexcept
Parses this string as a 64-bit integer.
References yup::CharacterFunctions::getIntValue().
getDoubleValue()
double yup::CharPointer_ASCII::getDoubleValue () const noexcept
Parses this string as a floating point double.
References yup::CharacterFunctions::getDoubleValue().
findEndOfWhitespace()
CharPointer_ASCII yup::CharPointer_ASCII::findEndOfWhitespace () const noexcept
Returns the first non-whitespace character in the string.
References CharPointer_ASCII(), and yup::CharacterFunctions::findEndOfWhitespace().
incrementToEndOfWhitespace()
void yup::CharPointer_ASCII::incrementToEndOfWhitespace () noexcept
Move this pointer to the first non-whitespace character in the string.
References yup::CharacterFunctions::incrementToEndOfWhitespace().
canRepresent()
bool yup::CharPointer_ASCII::canRepresent (yup_wchar character) static noexcept
Returns true if the given unicode character can be represented in this encoding.
isValidString()
bool yup::CharPointer_ASCII::isValidString (const CharType * dataToTest, int maxBytesToRead) static
Returns true if this data contains a valid string in this encoding.
Referenced by yup::String::String(), yup::String::String(), and yup::StringRef::StringRef().