YUP: yup::Font Class Reference
yup::Font Class Reference
Classes
struct Axis
struct AxisOption
Public Member Functions
Font ()=default
Font (const Font &other) noexcept=default
Copy and move constructors and assignment operators.
Font (Font &&other) noexcept=default
Font & operator= (const Font &other) noexcept=default
Font & operator= (Font &&other) noexcept=default
Result loadFromData (const MemoryBlock &fontBytes)
Result loadFromFile (const File &fontFile)
float getAscent () const
float getDescent () const
int getWeight () const
bool isItalic () const
int getNumAxis () const
std::optional< Font::Axis > getAxisDescription (int index) const
std::optional< Font::Axis > getAxisDescription (StringRef tagName) const
float getAxisValue (int index) const
float getAxisValue (StringRef tagName) const
void setAxisValue (int index, float value)
void setAxisValue (StringRef tagName, float value)
Font withAxisValue (int index, float value) const
Font withAxisValue (StringRef tagName, float value) const
void setAxisValues (std::initializer_list< AxisOption > axisOptions)
Font withAxisValues (std::initializer_list< AxisOption > axisOptions) const
void resetAxisValue (int index)
void resetAxisValue (StringRef tagName)
void resetAllAxisValues ()
bool operator== (const Font &other) const
bool operator!= (const Font &other) const
Font (rive::rcp< rive::Font > font)
rive::rcp< rive::Font > getFont () const
Constructor & Destructor Documentation
Font() [1/4]
yup::Font::Font () default
Referenced by Font(), Font(), operator!=(), operator=(), operator=(), operator==(), withAxisValue(), withAxisValue(), and withAxisValues().
Font() [2/4]
yup::Font::Font (const Font & other) default noexcept
Copy and move constructors and assignment operators.
References Font().
Font() [3/4]
yup::Font::Font (Font && other) default noexcept
References Font().
Font() [4/4]
yup::Font::Font (rive::rcp< rive::Font > font)
Member Function Documentation
operator=() [1/2]
Font & yup::Font::operator= (const Font & other) default noexcept
References Font().
operator=() [2/2]
Font & yup::Font::operator= (Font && other) default noexcept
References Font(), getAscent(), getDescent(), getWeight(), isItalic(), loadFromData(), and loadFromFile().
loadFromData()
Result yup::Font::loadFromData (const MemoryBlock & fontBytes)
References yup::Result::fail(), yup::MemoryBlock::getData(), yup::MemoryBlock::getSize(), and yup::Result::ok().
Referenced by yup::createThemeVersion1(), loadFromFile(), and operator=().
loadFromFile()
Result yup::Font::loadFromFile (const File & fontFile)
References yup::File::createInputStream(), yup::File::existsAsFile(), yup::Result::fail(), loadFromData(), and yup::Result::ok().
Referenced by operator=().
getAscent()
float yup::Font::getAscent () const
Referenced by operator=().
getDescent()
float yup::Font::getDescent () const
Referenced by operator=().
getWeight()
int yup::Font::getWeight () const
Referenced by operator=().
isItalic()
bool yup::Font::isItalic () const
Referenced by operator=().
getNumAxis()
int yup::Font::getNumAxis () const
Referenced by getAxisDescription(), getAxisValue(), resetAllAxisValues(), resetAxisValue(), setAxisValue(), and withAxisValue().
getAxisDescription() [1/2]
std::optional< Font::Axis > yup::Font::getAxisDescription (int index) const
References yup::Font::Axis::defaultValue, getNumAxis(), yup::isPositiveAndBelow(), yup::Font::Axis::maximumValue, yup::Font::Axis::minimumValue, and yup::Font::Axis::tagName.
Referenced by setAxisValue(), setAxisValues(), withAxisValue(), withAxisValue(), and withAxisValues().
getAxisDescription() [2/2]
std::optional< Font::Axis > yup::Font::getAxisDescription (StringRef tagName) const
References yup::Font::Axis::defaultValue, yup::StringRef::length(), yup::Font::Axis::maximumValue, yup::Font::Axis::minimumValue, and yup::Font::Axis::tagName.
getAxisValue() [1/2]
float yup::Font::getAxisValue (int index) const
References getNumAxis(), and yup::isPositiveAndBelow().
getAxisValue() [2/2]
float yup::Font::getAxisValue (StringRef tagName) const
References yup::StringRef::length().
setAxisValue() [1/2]
void yup::Font::setAxisValue (int index, float value)
References getNumAxis(), yup::isPositiveAndBelow(), and yup::jlimit().
Referenced by resetAxisValue(), and resetAxisValue().
setAxisValue() [2/2]
void yup::Font::setAxisValue (StringRef tagName, float value)
References getAxisDescription(), yup::jlimit(), and yup::StringRef::length().
withAxisValue() [1/2]
Font yup::Font::withAxisValue (int index, float value) const
References Font(), getAxisDescription(), getNumAxis(), and yup::isPositiveAndBelow().
withAxisValue() [2/2]
Font yup::Font::withAxisValue (StringRef tagName, float value) const
References Font(), getAxisDescription(), and yup::StringRef::length().
setAxisValues()
void yup::Font::setAxisValues (std::initializer_list< AxisOption > axisOptions)
References getAxisDescription(), and yup::jlimit().
withAxisValues()
Font yup::Font::withAxisValues (std::initializer_list< AxisOption > axisOptions) const
References Font(), getAxisDescription(), and yup::jlimit().
resetAxisValue() [1/2]
void yup::Font::resetAxisValue (int index)
References getNumAxis(), yup::isPositiveAndBelow(), and setAxisValue().
resetAxisValue() [2/2]
void yup::Font::resetAxisValue (StringRef tagName)
References yup::StringRef::length(), and setAxisValue().
resetAllAxisValues()
void yup::Font::resetAllAxisValues ()
References getNumAxis().
operator==()
bool yup::Font::operator== (const Font & other) const
References Font().
operator!=()
bool yup::Font::operator!= (const Font & other) const
References Font().
getFont()
rive::rcp< rive::Font > yup::Font::getFont () const