YUP: yup::CharPointer_UTF8 Class Reference
yup::CharPointer_UTF8 Class Reference final
Wraps a pointer to a null-terminated UTF-8 character string, and provides various methods to operate on the data.
Public Types
enum { byteOrderMark1 = 0xef , byteOrderMark2 = 0xbb , byteOrderMark3 = 0xbf }
These values are the byte-order mark (BOM) values for a UTF-8 stream.
using CharType = char
Public Member Functions
CharPointer_UTF8 (const CharType *rawPointer) noexcept
CharPointer_UTF8 (const CharPointer_UTF8 &other)=default
CharPointer_UTF8 operator= (CharPointer_UTF8 other) noexcept
CharPointer_UTF8 operator= (const CharType *text) noexcept
bool operator== (CharPointer_UTF8 other) const noexcept
This is a pointer comparison, it doesn't compare the actual text.
bool operator!= (CharPointer_UTF8 other) const noexcept
bool operator<= (CharPointer_UTF8 other) const noexcept
bool operator< (CharPointer_UTF8 other) const noexcept
bool operator>= (CharPointer_UTF8 other) const noexcept
bool operator> (CharPointer_UTF8 other) const noexcept
CharType * getAddress () const noexcept
Returns the address that this pointer is pointing to.
operator const CharType * () const noexcept
Returns the address that this pointer is pointing to.
bool isEmpty () const noexcept
Returns true if this pointer is pointing to a null character.
bool isNotEmpty () const noexcept
Returns true if this pointer is not pointing to a null character.
yup_wchar operator* () const noexcept
Returns the unicode character that this pointer is pointing to.
CharPointer_UTF8 & operator++ () noexcept
Moves this pointer along to the next character in the string.
CharPointer_UTF8 operator-- () noexcept
Moves this pointer back to the previous character in the string.
yup_wchar getAndAdvance () noexcept
Returns the character that this pointer is currently pointing to, and then advances the pointer to point to the next character.
CharPointer_UTF8 operator++ (int) noexcept
Moves this pointer along to the next character in the string.
void operator+= (int numToSkip) noexcept
Moves this pointer forwards by the specified number of characters.
void operator-= (int numToSkip) noexcept
Moves this pointer backwards by the specified number of characters.
yup_wchar operator[] (int characterIndex) const noexcept
Returns the character at a given character index from the start of the string.
CharPointer_UTF8 operator+ (int numToSkip) const noexcept
Returns a pointer which is moved forwards from this one by the specified number of characters.
CharPointer_UTF8 operator- (int numToSkip) const noexcept
Returns a pointer which is moved backwards from this one by the specified number of characters.
size_t length () const noexcept
Returns the number of characters in this string.
size_t lengthUpTo (const size_t maxCharsToCount) const noexcept
Returns the number of characters in this string, or the given value, whichever is lower.
size_t lengthUpTo (const CharPointer_UTF8 end) const noexcept
Returns the number of characters in this string, or up to the given end pointer, whichever is lower.
size_t sizeInBytes () const noexcept
Returns the number of bytes that are used to represent this string.
CharPointer_UTF8 findTerminatingNull () const noexcept
Returns a pointer to the null character that terminates this string.
void write (const yup_wchar charToWrite) noexcept
Writes a unicode character to this string, and advances this pointer to point to the next position.
void writeNull () const noexcept
Writes a null character to this string (leaving the pointer's position unchanged).
template<typename CharPointer>
void writeAll (const CharPointer src) noexcept
Copies a source string to this pointer, advancing this pointer as it goes.
void writeAll (const CharPointer_UTF8 src) noexcept
Copies a source string to this pointer, advancing this pointer as it goes.
template<typename CharPointer>
size_t writeWithDestByteLimit (const CharPointer src, const size_t maxDestBytes) noexcept
Copies a source string to this pointer, advancing this pointer as it goes.
template<typename CharPointer>
void writeWithCharLimit (const CharPointer src, const int maxChars) noexcept
Copies a source string to this pointer, advancing this pointer as it goes.
template<typename CharPointer>
int compare (const CharPointer other) const noexcept
Compares this string with another one.
template<typename CharPointer>
int compareUpTo (const CharPointer other, const int maxChars) const noexcept
Compares this string with another one, up to a specified number of characters.
template<typename CharPointer>
int compareIgnoreCase (const CharPointer other) const noexcept
Compares this string with another one.
int compareIgnoreCase (const CharPointer_UTF8 other) const noexcept
Compares this string with another one.
template<typename CharPointer>
int compareIgnoreCaseUpTo (const CharPointer other, const int maxChars) const noexcept
Compares this string with another one, up to a specified number of characters.
template<typename CharPointer>
int indexOf (const CharPointer stringToFind) const noexcept
Returns the character index of a substring, or -1 if it isn't found.
int indexOf (const yup_wchar charToFind) const noexcept
Returns the character index of a unicode character, or -1 if it isn't found.
int indexOf (const yup_wchar charToFind, const bool ignoreCase) const noexcept
Returns the character index of a unicode character, or -1 if it isn't found.
bool isWhitespace () const noexcept
Returns true if the first character of this string is whitespace.
bool isDigit () const noexcept
Returns true if the first character of this string is a digit.
bool isLetter () const noexcept
Returns true if the first character of this string is a letter.
bool isLetterOrDigit () const noexcept
Returns true if the first character of this string is a letter or digit.
bool isUpperCase () const noexcept
Returns true if the first character of this string is upper-case.
bool isLowerCase () const noexcept
Returns true if the first character of this string is lower-case.
yup_wchar toUpperCase () const noexcept
Returns an upper-case version of the first character of this string.
yup_wchar toLowerCase () const noexcept
Returns a lower-case version of the first character of this string.
int getIntValue32 () const noexcept
Parses this string as a 32-bit integer.
int64 getIntValue64 () const noexcept
Parses this string as a 64-bit integer.
double getDoubleValue () const noexcept
Parses this string as a floating point double.
CharPointer_UTF8 findEndOfWhitespace () const noexcept
Returns the first non-whitespace character in the string.
void incrementToEndOfWhitespace () noexcept
Move this pointer to the first non-whitespace character in the string.
CharPointer_UTF8 atomicSwap (const CharPointer_UTF8 newValue)
Atomically swaps this pointer for a new value, returning the previous value.
Static Public Member Functions
static size_t getBytesRequiredFor (const yup_wchar charToWrite) noexcept
Returns the number of bytes that would be needed to represent the given unicode character in this encoding format.
template<class CharPointer>
static size_t getBytesRequiredFor (CharPointer text) noexcept
Returns the number of bytes that would be needed to represent the given string in this encoding format.
static bool canRepresent (yup_wchar character) noexcept
Returns true if the given unicode character can be represented in this encoding.
static bool isValidString (const CharType *dataToTest, int maxBytesToRead)
Returns true if this data contains a valid string in this encoding.
static bool isByteOrderMark (const void *possibleByteOrder) noexcept
Returns true if the first three bytes in this pointer are the UTF8 byte-order mark (BOM).
Detailed Description
Wraps a pointer to a null-terminated UTF-8 character string, and provides various methods to operate on the data.
See also
CharPointer_UTF16, CharPointer_UTF32
Member Typedef Documentation
CharType
using yup::CharPointer_UTF8::CharType = char
Member Enumeration Documentation
anonymous enum
anonymous enum
These values are the byte-order mark (BOM) values for a UTF-8 stream.
Enumerator
byteOrderMark1
byteOrderMark2
byteOrderMark3
Constructor & Destructor Documentation
CharPointer_UTF8() [1/2]
yup::CharPointer_UTF8::CharPointer_UTF8 (const CharType * rawPointer) explicit noexcept
Referenced by atomicSwap(), CharPointer_UTF8(), compareIgnoreCase(), findEndOfWhitespace(), findTerminatingNull(), isValidString(), lengthUpTo(), operator!=(), operator+(), operator++(), operator++(), operator-(), operator--(), operator<(), operator<=(), operator=(), operator=(), operator==(), operator>(), operator>=(), and writeAll().
CharPointer_UTF8() [2/2]
yup::CharPointer_UTF8::CharPointer_UTF8 (const CharPointer_UTF8 & other) default
References CharPointer_UTF8().
Member Function Documentation
operator=() [1/2]
CharPointer_UTF8 yup::CharPointer_UTF8::operator= (CharPointer_UTF8 other) noexcept
References CharPointer_UTF8().
operator=() [2/2]
CharPointer_UTF8 yup::CharPointer_UTF8::operator= (const CharType * text) noexcept
References CharPointer_UTF8().
operator==()
bool yup::CharPointer_UTF8::operator== (CharPointer_UTF8 other) const noexcept
This is a pointer comparison, it doesn't compare the actual text.
References CharPointer_UTF8().
operator!=()
bool yup::CharPointer_UTF8::operator!= (CharPointer_UTF8 other) const noexcept
References CharPointer_UTF8().
operator<=()
bool yup::CharPointer_UTF8::operator<= (CharPointer_UTF8 other) const noexcept
References CharPointer_UTF8().
operator<()
bool yup::CharPointer_UTF8::operator< (CharPointer_UTF8 other) const noexcept
References CharPointer_UTF8().
operator>=()
bool yup::CharPointer_UTF8::operator>= (CharPointer_UTF8 other) const noexcept
References CharPointer_UTF8().
operator>()
bool yup::CharPointer_UTF8::operator> (CharPointer_UTF8 other) const noexcept
References CharPointer_UTF8().
getAddress()
CharType * yup::CharPointer_UTF8::getAddress () const noexcept
Returns the address that this pointer is pointing to.
Referenced by yup::String::appendCharPointer(), yup::StringArray::appendNumbersToDuplicates(), yup::operator<<(), yup::String::replaceSection(), and yup::MidiMessage::textMetaEvent().
operator const CharType *()
yup::CharPointer_UTF8::operator const CharType * () const noexcept
Returns the address that this pointer is pointing to.
isEmpty()
bool yup::CharPointer_UTF8::isEmpty () const noexcept
Returns true if this pointer is pointing to a null character.
Referenced by yup::StringArray::addLines(), yup::Base64::convertFromBase64(), yup::StringPool::getPooledString(), and yup::Path::parsePathData().
isNotEmpty()
bool yup::CharPointer_UTF8::isNotEmpty () const noexcept
Returns true if this pointer is not pointing to a null character.
operator*()
yup_wchar yup::CharPointer_UTF8::operator* () const noexcept
Returns the unicode character that this pointer is pointing to.
operator++() [1/2]
CharPointer_UTF8 & yup::CharPointer_UTF8::operator++ () noexcept
Moves this pointer along to the next character in the string.
References CharPointer_UTF8().
operator--()
CharPointer_UTF8 yup::CharPointer_UTF8::operator-- () noexcept
Moves this pointer back to the previous character in the string.
References CharPointer_UTF8().
getAndAdvance()
yup_wchar yup::CharPointer_UTF8::getAndAdvance () noexcept
Returns the character that this pointer is currently pointing to, and then advances the pointer to point to the next character.
Referenced by yup::XmlElement::isValidXmlName(), yup::String::removeCharacters(), yup::String::replaceCharacter(), yup::String::replaceCharacters(), and yup::String::retainCharacters().
operator++() [2/2]
CharPointer_UTF8 yup::CharPointer_UTF8::operator++ (int) noexcept
Moves this pointer along to the next character in the string.
References CharPointer_UTF8().
operator+=()
void yup::CharPointer_UTF8::operator+= (int numToSkip) noexcept
Moves this pointer forwards by the specified number of characters.
Referenced by operator-=().
operator-=()
void yup::CharPointer_UTF8::operator-= (int numToSkip) noexcept
Moves this pointer backwards by the specified number of characters.
References operator+=().
operator[]()
yup_wchar yup::CharPointer_UTF8::operator[] (int characterIndex) const noexcept
Returns the character at a given character index from the start of the string.
operator+()
CharPointer_UTF8 yup::CharPointer_UTF8::operator+ (int numToSkip) const noexcept
Returns a pointer which is moved forwards from this one by the specified number of characters.
References CharPointer_UTF8().
operator-()
CharPointer_UTF8 yup::CharPointer_UTF8::operator- (int numToSkip) const noexcept
Returns a pointer which is moved backwards from this one by the specified number of characters.
References CharPointer_UTF8().
length()
size_t yup::CharPointer_UTF8::length () const noexcept
Returns the number of characters in this string.
lengthUpTo() [1/2]
size_t yup::CharPointer_UTF8::lengthUpTo (const size_t maxCharsToCount) const noexcept
Returns the number of characters in this string, or the given value, whichever is lower.
References yup::CharacterFunctions::lengthUpTo().
lengthUpTo() [2/2]
size_t yup::CharPointer_UTF8::lengthUpTo (const CharPointer_UTF8 end) const noexcept
Returns the number of characters in this string, or up to the given end pointer, whichever is lower.
References CharPointer_UTF8(), yup::end(), and yup::CharacterFunctions::lengthUpTo().
sizeInBytes()
size_t yup::CharPointer_UTF8::sizeInBytes () const noexcept
Returns the number of bytes that are used to represent this string.
This includes the terminating null character.
Referenced by yup::StringArray::joinIntoString(), and yup::MidiMessage::textMetaEvent().
getBytesRequiredFor() [1/2]
size_t yup::CharPointer_UTF8::getBytesRequiredFor (const yup_wchar charToWrite) static noexcept
Returns the number of bytes that would be needed to represent the given unicode character in this encoding format.
Referenced by yup::String::appendCharPointer(), yup::String::appendCharPointer(), yup::MemoryOutputStream::appendUTF8Char(), yup::String::charToString(), getBytesRequiredFor(), yup::String::getNumBytesAsUTF8(), yup::operator<<(), yup::String::paddedLeft(), and yup::String::paddedRight().
getBytesRequiredFor() [2/2]
template<class CharPointer> size_t yup::CharPointer_UTF8::getBytesRequiredFor (CharPointer text) static noexcept
Returns the number of bytes that would be needed to represent the given string in this encoding format.
The value returned does NOT include the terminating null character.
References getBytesRequiredFor().
findTerminatingNull()
CharPointer_UTF8 yup::CharPointer_UTF8::findTerminatingNull () const noexcept
Returns a pointer to the null character that terminates this string.
References CharPointer_UTF8().
Referenced by yup::String::appendCharPointer(), and yup::String::trim().
write()
void yup::CharPointer_UTF8::write (const yup_wchar charToWrite) noexcept
Writes a unicode character to this string, and advances this pointer to point to the next position.
Referenced by yup::MemoryOutputStream::appendUTF8Char(), yup::String::charToString(), yup::String::paddedLeft(), and yup::MemoryBlock::toBase64Encoding().
writeNull()
void yup::CharPointer_UTF8::writeNull () const noexcept
Writes a null character to this string (leaving the pointer's position unchanged).
Referenced by yup::String::charToString(), yup::StringArray::joinIntoString(), and yup::String::toHexString().
writeAll() [1/2]
template<typename CharPointer> void yup::CharPointer_UTF8::writeAll (const CharPointer src) noexcept
Copies a source string to this pointer, advancing this pointer as it goes.
References yup::CharacterFunctions::copyAll().
Referenced by yup::operator<<(), yup::String::paddedRight(), and yup::String::repeatedString().
writeAll() [2/2]
void yup::CharPointer_UTF8::writeAll (const CharPointer_UTF8 src) noexcept
Copies a source string to this pointer, advancing this pointer as it goes.
References CharPointer_UTF8().
writeWithDestByteLimit()
template<typename CharPointer> size_t yup::CharPointer_UTF8::writeWithDestByteLimit (const CharPointer src, const size_t maxDestBytes) noexcept
Copies a source string to this pointer, advancing this pointer as it goes.
The maxDestBytes parameter specifies the maximum number of bytes that can be written to the destination buffer before stopping.
References yup::CharacterFunctions::copyWithDestByteLimit().
writeWithCharLimit()
template<typename CharPointer> void yup::CharPointer_UTF8::writeWithCharLimit (const CharPointer src, const int maxChars) noexcept
Copies a source string to this pointer, advancing this pointer as it goes.
The maxChars parameter specifies the maximum number of characters that can be written to the destination buffer before stopping (including the terminating null).
References yup::CharacterFunctions::copyWithCharLimit().
compare()
template<typename CharPointer> int yup::CharPointer_UTF8::compare (const CharPointer other) const noexcept
Compares this string with another one.
References yup::CharacterFunctions::compare().
compareUpTo()
template<typename CharPointer> int yup::CharPointer_UTF8::compareUpTo (const CharPointer other, const int maxChars) const noexcept
Compares this string with another one, up to a specified number of characters.
References yup::CharacterFunctions::compareUpTo().
compareIgnoreCase() [1/2]
template<typename CharPointer> int yup::CharPointer_UTF8::compareIgnoreCase (const CharPointer other) const noexcept
Compares this string with another one.
References yup::CharacterFunctions::compareIgnoreCase().
compareIgnoreCase() [2/2]
int yup::CharPointer_UTF8::compareIgnoreCase (const CharPointer_UTF8 other) const noexcept
Compares this string with another one.
References CharPointer_UTF8(), and yup::CharacterFunctions::compareIgnoreCase().
compareIgnoreCaseUpTo()
template<typename CharPointer> int yup::CharPointer_UTF8::compareIgnoreCaseUpTo (const CharPointer other, const int maxChars) const noexcept
Compares this string with another one, up to a specified number of characters.
References yup::CharacterFunctions::compareIgnoreCaseUpTo().
indexOf() [1/3]
template<typename CharPointer> int yup::CharPointer_UTF8::indexOf (const CharPointer stringToFind) const noexcept
Returns the character index of a substring, or -1 if it isn't found.
References yup::CharacterFunctions::indexOf().
Referenced by yup::File::hasFileExtension(), yup::String::initialSectionContainingOnly(), yup::String::initialSectionNotContaining(), yup::String::removeCharacters(), yup::String::replaceCharacters(), yup::String::retainCharacters(), yup::String::trimCharactersAtEnd(), and yup::String::trimCharactersAtStart().
indexOf() [2/3]
int yup::CharPointer_UTF8::indexOf (const yup_wchar charToFind) const noexcept
Returns the character index of a unicode character, or -1 if it isn't found.
References yup::CharacterFunctions::indexOfChar().
indexOf() [3/3]
int yup::CharPointer_UTF8::indexOf (const yup_wchar charToFind, const bool ignoreCase) const noexcept
Returns the character index of a unicode character, or -1 if it isn't found.
References yup::CharacterFunctions::indexOfChar(), and yup::CharacterFunctions::indexOfCharIgnoreCase().
isWhitespace()
bool yup::CharPointer_UTF8::isWhitespace () const noexcept
Returns true if the first character of this string is whitespace.
References yup::CharacterFunctions::isWhitespace().
isDigit()
bool yup::CharPointer_UTF8::isDigit () const noexcept
Returns true if the first character of this string is a digit.
isLetter()
bool yup::CharPointer_UTF8::isLetter () const noexcept
Returns true if the first character of this string is a letter.
References yup::CharacterFunctions::isLetter().
isLetterOrDigit()
bool yup::CharPointer_UTF8::isLetterOrDigit () const noexcept
Returns true if the first character of this string is a letter or digit.
References yup::CharacterFunctions::isLetterOrDigit().
isUpperCase()
bool yup::CharPointer_UTF8::isUpperCase () const noexcept
Returns true if the first character of this string is upper-case.
References yup::CharacterFunctions::isUpperCase().
isLowerCase()
bool yup::CharPointer_UTF8::isLowerCase () const noexcept
Returns true if the first character of this string is lower-case.
References yup::CharacterFunctions::isLowerCase().
toUpperCase()
yup_wchar yup::CharPointer_UTF8::toUpperCase () const noexcept
Returns an upper-case version of the first character of this string.
References yup::CharacterFunctions::toUpperCase().
Referenced by yup::String::toUpperCase().
toLowerCase()
yup_wchar yup::CharPointer_UTF8::toLowerCase () const noexcept
Returns a lower-case version of the first character of this string.
References yup::CharacterFunctions::toLowerCase().
Referenced by yup::String::toLowerCase().
getIntValue32()
int yup::CharPointer_UTF8::getIntValue32 () const noexcept
Parses this string as a 32-bit integer.
getIntValue64()
int64 yup::CharPointer_UTF8::getIntValue64 () const noexcept
Parses this string as a 64-bit integer.
getDoubleValue()
double yup::CharPointer_UTF8::getDoubleValue () const noexcept
Parses this string as a floating point double.
References yup::CharacterFunctions::getDoubleValue().
findEndOfWhitespace()
CharPointer_UTF8 yup::CharPointer_UTF8::findEndOfWhitespace () const noexcept
Returns the first non-whitespace character in the string.
References CharPointer_UTF8(), and yup::CharacterFunctions::findEndOfWhitespace().
Referenced by yup::BigInteger::parseString(), and yup::String::trim().
incrementToEndOfWhitespace()
void yup::CharPointer_UTF8::incrementToEndOfWhitespace () noexcept
Move this pointer to the first non-whitespace character in the string.
References yup::CharacterFunctions::incrementToEndOfWhitespace().
canRepresent()
bool yup::CharPointer_UTF8::canRepresent (yup_wchar character) static noexcept
Returns true if the given unicode character can be represented in this encoding.
isValidString()
bool yup::CharPointer_UTF8::isValidString (const CharType * dataToTest, int maxBytesToRead) static
Returns true if this data contains a valid string in this encoding.
References CharPointer_UTF8().
Referenced by yup::String::createStringFromData(), and yup::String::fromUTF8().
atomicSwap()
CharPointer_UTF8 yup::CharPointer_UTF8::atomicSwap (const CharPointer_UTF8 newValue)
Atomically swaps this pointer for a new value, returning the previous value.
References CharPointer_UTF8().
isByteOrderMark()
bool yup::CharPointer_UTF8::isByteOrderMark (const void * possibleByteOrder) static noexcept
Returns true if the first three bytes in this pointer are the UTF8 byte-order mark (BOM).
The pointer must not be null, and must point to at least 3 valid bytes.
References byteOrderMark1, byteOrderMark2, and byteOrderMark3.
Referenced by yup::String::createStringFromData(), and yup::XmlDocument::getDocumentElement().