YUP: yup::AudioBusLayout Class Reference
yup::AudioBusLayout Class Reference
Represents the full input/output bus layout of a plugin processor.
Public Member Functions
AudioBusLayout ()=default
Constructs an empty AudioBusLayout.
AudioBusLayout (std::vector< AudioBus > inputs, std::vector< AudioBus > outputs)
Constructs an AudioBusLayout from lists of buses.
AudioBusLayout (const AudioBusLayout &other)=default
Copy constructor.
AudioBusLayout & operator= (const AudioBusLayout &other)=default
Assignment operator.
AudioBusLayout (AudioBusLayout &&other) noexcept=default
Move constructor.
AudioBusLayout & operator= (AudioBusLayout &&other) noexcept=default
Move assignment operator.
~AudioBusLayout ()=default
Destructor.
Span< const AudioBus > getInputBuses () const noexcept
Returns all input buses.
Span< const AudioBus > getOutputBuses () const noexcept
Returns all output buses.
Detailed Description
Represents the full input/output bus layout of a plugin processor.
This layout is immutable after construction and supports multiple types of buses, grouped by input/output.
Constructor & Destructor Documentation
AudioBusLayout() [1/4]
yup::AudioBusLayout::AudioBusLayout () default
Constructs an empty AudioBusLayout.
Referenced by AudioBusLayout(), AudioBusLayout(), operator=(), and operator=().
AudioBusLayout() [2/4]
yup::AudioBusLayout::AudioBusLayout (std::vector< AudioBus > inputs, std::vector< AudioBus > outputs)
Constructs an AudioBusLayout from lists of buses.
AudioBusLayout() [3/4]
yup::AudioBusLayout::AudioBusLayout (const AudioBusLayout & other) default
Copy constructor.
References AudioBusLayout().
AudioBusLayout() [4/4]
yup::AudioBusLayout::AudioBusLayout (AudioBusLayout && other) default noexcept
Move constructor.
References AudioBusLayout().
~AudioBusLayout()
yup::AudioBusLayout::~AudioBusLayout () default
Destructor.
Member Function Documentation
operator=() [1/2]
AudioBusLayout & yup::AudioBusLayout::operator= (const AudioBusLayout & other) default
Assignment operator.
References AudioBusLayout().
operator=() [2/2]
AudioBusLayout & yup::AudioBusLayout::operator= (AudioBusLayout && other) default noexcept
Move assignment operator.
References AudioBusLayout().
getInputBuses()
Span< const AudioBus > yup::AudioBusLayout::getInputBuses () const noexcept
Returns all input buses.
getOutputBuses()
Span< const AudioBus > yup::AudioBusLayout::getOutputBuses () const noexcept
Returns all output buses.