YUP: yup::DynamicLibrary Class Reference
yup::DynamicLibrary Class Reference
Handles the opening and closing of DLLs.
Public Member Functions
DynamicLibrary ()=default
Creates an unopened DynamicLibrary object.
DynamicLibrary (const String &name)
DynamicLibrary (DynamicLibrary &&other) noexcept
Move constructor.
~DynamicLibrary ()
Destructor.
bool open (const String &name)
Opens a DLL.
void close ()
Releases the currently-open DLL, or has no effect if none was open.
void * getFunction (const String &functionName) noexcept
Tries to find a named function in the currently-open DLL, and returns a pointer to it.
void * getNativeHandle () const noexcept
Returns the platform-specific native library handle.
Detailed Description
Handles the opening and closing of DLLs.
This class can be used to open a DLL and get some function pointers from it. Since the DLL is freed when this object is deleted, it's handy for managing library lifetimes using RAII.
Constructor & Destructor Documentation
DynamicLibrary() [1/3]
yup::DynamicLibrary::DynamicLibrary () default
Creates an unopened DynamicLibrary object.
Call open() to actually open one.
Referenced by DynamicLibrary().
DynamicLibrary() [2/3]
yup::DynamicLibrary::DynamicLibrary (const String & name)
References open().
DynamicLibrary() [3/3]
yup::DynamicLibrary::DynamicLibrary (DynamicLibrary && other) noexcept
Move constructor.
References DynamicLibrary().
~DynamicLibrary()
yup::DynamicLibrary::~DynamicLibrary ()
Destructor.
If a library is currently open, it will be closed when this object is destroyed.
References close().
Member Function Documentation
open()
bool yup::DynamicLibrary::open (const String & name)
Opens a DLL.
The name and the method by which it gets found is of course platform-specific, and may or may not include a path, depending on the OS. If a library is already open when this method is called, it will first close the library before attempting to load the new one.
Returns
true if the library was successfully found and opened.
Referenced by DynamicLibrary().
close()
void yup::DynamicLibrary::close ()
Releases the currently-open DLL, or has no effect if none was open.
Referenced by ~DynamicLibrary().
getFunction()
void * yup::DynamicLibrary::getFunction (const String & functionName) noexcept
Tries to find a named function in the currently-open DLL, and returns a pointer to it.
If no library is open, or if the function isn't found, this will return a null pointer.
getNativeHandle()
void * yup::DynamicLibrary::getNativeHandle () const noexcept
Returns the platform-specific native library handle.
You'll need to cast this to whatever is appropriate for the OS that's in use.