YUP: yup::Color Class Reference
yup::Color Class Reference
Represents an RGBA color for graphical use.
Public Member Functions
constexpr Color () noexcept
Default constructor, initializes the color to transparent black.
constexpr Color (uint32 color) noexcept
Constructs a color from a 32-bit integer.
constexpr Color (uint8 r, uint8 g, uint8 b) noexcept
Constructs a color with specified red, green, and blue components, defaulting alpha to opaque.
constexpr Color (uint8 a, uint8 r, uint8 g, uint8 b) noexcept
Constructs a color with specified alpha, red, green, and blue components.
constexpr Color (const Color &other) noexcept=default
Copy and move constructors and assignment operators.
constexpr Color (Color &&other) noexcept=default
constexpr Color & operator= (const Color &other) noexcept=default
constexpr Color & operator= (Color &&other) noexcept=default
constexpr uint32 getARGB () const noexcept
Returns the color as a 32-bit integer in ARGB format.
constexpr operator uint32 () const noexcept
Implicit conversion to a 32-bit integer.
constexpr bool isTransparent () const noexcept
Returns of the color is fully transparent.
constexpr bool isSemiTransparent () const noexcept
Returns of the color is semi transparent.
constexpr bool isOpaque () const noexcept
Returns of the color is opaque.
constexpr uint8 getAlpha () const noexcept
Returns the alpha component of the color.
constexpr float getAlphaFloat () const noexcept
Returns the alpha component of the color as a floating point value.
constexpr Color & setAlpha (uint8 alpha) noexcept
Sets the alpha component of the color.
constexpr Color & setAlpha (float alpha) noexcept
Sets the alpha component of the color using a floating point value.
constexpr Color withAlpha (uint8 alpha) const noexcept
Returns a new color with the specified alpha value.
constexpr Color withAlpha (float alpha) const noexcept
constexpr Color withMultipliedAlpha (uint8 alpha) const noexcept
constexpr Color withMultipliedAlpha (float alpha) const noexcept
constexpr uint8 getRed () const noexcept
Returns the red component of the color.
constexpr float getRedFloat () const noexcept
Returns the red component of the color as a floating point value.
constexpr Color & setRed (uint8 red) noexcept
Sets the red component of the color.
constexpr Color & setRed (float red) noexcept
Sets the red component of the color using a floating point value.
constexpr Color withRed (uint8 red) const noexcept
Returns a new color with the specified red value.
constexpr Color withRed (float red) const noexcept
constexpr uint8 getGreen () const noexcept
Returns the green component of the color.
constexpr float getGreenFloat () const noexcept
Returns the green component of the color as a floating point value.
constexpr Color & setGreen (uint8 green) noexcept
Sets the green component of the color.
constexpr Color & setGreen (float green) noexcept
Sets the green component of the color using a floating point value.
constexpr Color withGreen (uint8 green) const noexcept
Returns a new color with the specified green value.
constexpr Color withGreen (float green) const noexcept
constexpr uint8 getBlue () const noexcept
Returns the blue component of the color.
constexpr float getBlueFloat () const noexcept
Returns the blue component of the color as a floating point value.
constexpr Color & setBlue (uint8 blue) noexcept
Sets the blue component of the color.
constexpr Color & setBlue (float blue) noexcept
Sets the blue component of the color using a floating point value.
constexpr Color withBlue (uint8 blue) const noexcept
Returns a new color with the specified blue value.
constexpr Color withBlue (float blue) const noexcept
constexpr float getHue () const noexcept
Calculates the hue component of the color in HSL representation.
constexpr float getSaturation () const noexcept
Calculates the saturation component of the color in HSL representation.
constexpr float getLuminance () const noexcept
Calculates the luminance of the color.
constexpr std::tuple< float, float, float > toHSL () const noexcept
Converts the color to its HSL (Hue, Saturation, Luminance) components.
constexpr std::tuple< float, float, float > toHSV () const noexcept
Converts the color to its HSV (Hue, Saturation, Value) components.
constexpr Color brighter (float amount) const noexcept
Makes the color brighter by a specified amount.
constexpr Color darker (float amount) const noexcept
Makes the color darker by a specified amount.
constexpr Color contrasting () const noexcept
Returns a contrasting color.
constexpr Color contrasting (float amount) const noexcept
Returns a contrasting color adjusted by a specified amount.
constexpr Color & invert () noexcept
Inverts the color components (RGB) of the current color.
constexpr Color inverted () const noexcept
Returns a new color that is the inverse of the current color.
constexpr Color & invertAlpha () noexcept
Inverts the alpha component of the current color.
constexpr Color invertedAlpha () const noexcept
Returns a new color that is the inverse of the current color in terms of alpha transparency.
String toString () const
String toStringRGB (bool withAlpha) const
Static Public Member Functions
static constexpr Color fromHSL (float h, float s, float l, float a=1.0f) noexcept
Constructs a color from HSL values.
static constexpr Color fromHSV (float h, float s, float v, float a=1.0f) noexcept
Constructs a color from HSV values.
static Color opaqueRandom () noexcept
static Color fromString (const String &colourString)
Detailed Description
Represents an RGBA color for graphical use.
This class encapsulates color information in RGBA format, where each component (red, green, blue, alpha) is represented as an 8-bit value. It provides methods for adjusting color components individually, converting to and from HSL (Hue, Saturation, Luminance), and for performing operations like brightening, darkening, and contrasting.
Constructor & Destructor Documentation
Color() [1/6]
yup::Color::Color () constexpr noexcept
Default constructor, initializes the color to transparent black.
Creates a color with all components set to zero, which is fully transparent black.
References data.
Referenced by brighter(), Color(), Color(), contrasting(), contrasting(), darker(), fromHSL(), fromHSV(), fromString(), invert(), invertAlpha(), inverted(), invertedAlpha(), opaqueRandom(), operator=(), operator=(), setAlpha(), setAlpha(), setBlue(), setBlue(), setGreen(), setGreen(), setRed(), setRed(), withAlpha(), withAlpha(), withBlue(), withBlue(), withGreen(), withGreen(), withMultipliedAlpha(), withMultipliedAlpha(), withRed(), and withRed().
Color() [2/6]
yup::Color::Color (uint32 color) constexpr noexcept
Constructs a color from a 32-bit integer.
This constructor initializes the color from a 32-bit integer, assuming a format where the highest byte is alpha, followed by red, green, and blue.
Parameters
color The 32-bit integer representing the color.
References data.
Color() [3/6]
yup::Color::Color (uint8 r, uint8 g, uint8 b) constexpr noexcept
Constructs a color with specified red, green, and blue components, defaulting alpha to opaque.
Parameters
r The red component, from 0 to 255.
g The green component, from 0 to 255.
b The blue component, from 0 to 255.
References a, b, g, and r.
Color() [4/6]
yup::Color::Color (uint8 a, uint8 r, uint8 g, uint8 b) constexpr noexcept
Constructs a color with specified alpha, red, green, and blue components.
Parameters
a The alpha component, from 0 (transparent) to 255 (opaque).
r The red component, from 0 to 255.
g The green component, from 0 to 255.
b The blue component, from 0 to 255.
References a, b, g, and r.
Color() [5/6]
yup::Color::Color (const Color & other) constexpr default noexcept
Copy and move constructors and assignment operators.
References Color().
Color() [6/6]
yup::Color::Color (Color && other) constexpr default noexcept
References Color().
Member Function Documentation
operator=() [1/2]
Color & yup::Color::operator= (const Color & other) constexpr default noexcept
References Color().
operator=() [2/2]
Color & yup::Color::operator= (Color && other) constexpr default noexcept
References Color().
getARGB()
uint32 yup::Color::getARGB () const constexpr noexcept
Returns the color as a 32-bit integer in ARGB format.
Returns
The color as a 32-bit integer.
References data.
operator uint32()
yup::Color::operator uint32 () const constexpr noexcept
Implicit conversion to a 32-bit integer.
Allows the color to be used wherever a 32-bit integer color is expected.
Returns
The color as a 32-bit integer.
References data.
isTransparent()
bool yup::Color::isTransparent () const constexpr noexcept
Returns of the color is fully transparent.
References a.
isSemiTransparent()
bool yup::Color::isSemiTransparent () const constexpr noexcept
Returns of the color is semi transparent.
References isOpaque().
isOpaque()
bool yup::Color::isOpaque () const constexpr noexcept
Returns of the color is opaque.
References a.
Referenced by isSemiTransparent().
getAlpha()
uint8 yup::Color::getAlpha () const constexpr noexcept
Returns the alpha component of the color.
Returns
The alpha component as an 8-bit integer.
References a.
getAlphaFloat()
float yup::Color::getAlphaFloat () const constexpr noexcept
Returns the alpha component of the color as a floating point value.
Returns
The alpha component, normalized to the range [0, 1].
References a.
setAlpha() [1/2]
Color & yup::Color::setAlpha (uint8 alpha) constexpr noexcept
Sets the alpha component of the color.
Parameters
alpha The new alpha value as an 8-bit integer.
Returns
A reference to this color object to allow for method chaining.
References a, and Color().
setAlpha() [2/2]
Color & yup::Color::setAlpha (float alpha) constexpr noexcept
Sets the alpha component of the color using a floating point value.
Parameters
alpha The new alpha value, normalized to the range [0, 1].
Returns
A reference to this color object to allow for method chaining.
References a, and Color().
withAlpha() [1/2]
Color yup::Color::withAlpha (uint8 alpha) const constexpr noexcept
Returns a new color with the specified alpha value.
This method creates a new color with the same red, green, and blue values but a different alpha.
Parameters
alpha The new alpha value as an 8-bit integer.
Returns
A new color with the specified alpha value.
References b, Color(), g, and r.
Referenced by toStringRGB().
withAlpha() [2/2]
Color yup::Color::withAlpha (float alpha) const constexpr noexcept
References b, Color(), g, and r.
withMultipliedAlpha() [1/2]
Color yup::Color::withMultipliedAlpha (uint8 alpha) const constexpr noexcept
References a, b, Color(), g, and r.
Referenced by yup::ColorGradient::withMultipliedAlpha(), and yup::ColorGradient::withMultipliedAlpha().
withMultipliedAlpha() [2/2]
Color yup::Color::withMultipliedAlpha (float alpha) const constexpr noexcept
References a, b, Color(), g, and r.
getRed()
uint8 yup::Color::getRed () const constexpr noexcept
Returns the red component of the color.
Returns
The red component as an 8-bit integer.
References r.
getRedFloat()
float yup::Color::getRedFloat () const constexpr noexcept
Returns the red component of the color as a floating point value.
Returns
The red component, normalized to the range [0, 1].
References r.
Referenced by brighter(), getHue(), getLuminance(), getSaturation(), toHSL(), and toHSV().
setRed() [1/2]
Color & yup::Color::setRed (uint8 red) constexpr noexcept
Sets the red component of the color.
Parameters
red The new red value as an 8-bit integer.
Returns
A reference to this color object to allow for method chaining.
References Color(), and r.
setRed() [2/2]
Color & yup::Color::setRed (float red) constexpr noexcept
Sets the red component of the color using a floating point value.
Parameters
red The new red value, normalized to the range [0, 1].
Returns
A reference to this color object to allow for method chaining.
References Color(), and r.
withRed() [1/2]
Color yup::Color::withRed (uint8 red) const constexpr noexcept
Returns a new color with the specified red value.
This method creates a new color with the same green, blue, and alpha values but a different red.
Parameters
red The new red value as an 8-bit integer.
Returns
A new color with the specified red value.
References a, b, Color(), and g.
withRed() [2/2]
Color yup::Color::withRed (float red) const constexpr noexcept
References a, b, Color(), and g.
getGreen()
uint8 yup::Color::getGreen () const constexpr noexcept
Returns the green component of the color.
Returns
The green component as an 8-bit integer.
References g.
getGreenFloat()
float yup::Color::getGreenFloat () const constexpr noexcept
Returns the green component of the color as a floating point value.
Returns
The green component, normalized to the range [0, 1].
References g.
Referenced by brighter(), getHue(), getLuminance(), getSaturation(), toHSL(), and toHSV().
setGreen() [1/2]
Color & yup::Color::setGreen (uint8 green) constexpr noexcept
Sets the green component of the color.
Parameters
green The new green value as an 8-bit integer.
Returns
A reference to this color object to allow for method chaining.
References Color(), and g.
setGreen() [2/2]
Color & yup::Color::setGreen (float green) constexpr noexcept
Sets the green component of the color using a floating point value.
Parameters
green The new green value, normalized to the range [0, 1].
Returns
A reference to this color object to allow for method chaining.
References Color(), and g.
withGreen() [1/2]
Color yup::Color::withGreen (uint8 green) const constexpr noexcept
Returns a new color with the specified green value.
This method creates a new color with the same red, blue, and alpha values but a different green.
Parameters
green The new green value as an 8-bit integer.
Returns
A new color with the specified green value.
References a, b, Color(), and r.
withGreen() [2/2]
Color yup::Color::withGreen (float green) const constexpr noexcept
References a, b, Color(), and r.
getBlue()
uint8 yup::Color::getBlue () const constexpr noexcept
Returns the blue component of the color.
Returns
The blue component as an 8-bit integer.
References b.
getBlueFloat()
float yup::Color::getBlueFloat () const constexpr noexcept
Returns the blue component of the color as a floating point value.
Returns
The blue component, normalized to the range [0, 1].
References b.
Referenced by brighter(), getHue(), getLuminance(), getSaturation(), toHSL(), and toHSV().
setBlue() [1/2]
Color & yup::Color::setBlue (uint8 blue) constexpr noexcept
Sets the blue component of the color.
Parameters
blue The new blue value as an 8-bit integer.
Returns
A reference to this color object to allow for method chaining.
References b, and Color().
setBlue() [2/2]
Color & yup::Color::setBlue (float blue) constexpr noexcept
Sets the blue component of the color using a floating point value.
Parameters
blue The new blue value, normalized to the range [0, 1].
Returns
A reference to this color object to allow for method chaining.
References b, and Color().
withBlue() [1/2]
Color yup::Color::withBlue (uint8 blue) const constexpr noexcept
Returns a new color with the specified blue value.
This method creates a new color with the same red, green, and alpha values but a different blue.
Parameters
blue The new blue value as an 8-bit integer.
Returns
A new color with the specified blue value.
References a, Color(), g, and r.
withBlue() [2/2]
Color yup::Color::withBlue (float blue) const constexpr noexcept
References a, Color(), g, and r.
getHue()
float yup::Color::getHue () const constexpr noexcept
Calculates the hue component of the color in HSL representation.
Hue is measured as a location on the standard color wheel, expressed as a fraction between 0 and 1.0. This function calculates hue by converting RGB values to HSL and then extracting the hue component.
Returns
The hue component of the color, normalized to the range [0, 1].
References getBlueFloat(), getGreenFloat(), getRedFloat(), yup::jmax(), and yup::jmin().
getSaturation()
float yup::Color::getSaturation () const constexpr noexcept
Calculates the saturation component of the color in HSL representation.
Saturation measures the intensity of color. A saturation value of 0 corresponds to a shade of grey, while a value of 1 indicates the full intensity of the color. This method calculates saturation by converting RGB values to HSL and then extracting the saturation component.
Returns
The saturation component of the color, normalized to the range [0, 1].
References getBlueFloat(), getGreenFloat(), getRedFloat(), yup::jmax(), and yup::jmin().
getLuminance()
float yup::Color::getLuminance () const constexpr noexcept
Calculates the luminance of the color.
Luminance is a measure of the brightness of a color, normalized to a range from 0 (black) to 1 (white). This method calculates luminance by averaging the maximum and minimum RGB components.
Returns
The luminance component of the color, normalized to the range [0, 1].
References getBlueFloat(), getGreenFloat(), getRedFloat(), yup::jmax(), and yup::jmin().
toHSL()
std::tuple< float, float, float > yup::Color::toHSL () const constexpr noexcept
Converts the color to its HSL (Hue, Saturation, Luminance) components.
This method provides a way to obtain the HSL representation of the color, which can be useful for color manipulation and effects. The returned tuple contains the hue, saturation, and luminance components, respectively.
Returns
A tuple consisting of hue, saturation, and luminance.
References getBlueFloat(), getGreenFloat(), getRedFloat(), yup::jmax(), and yup::jmin().
fromHSL()
constexpr Color yup::Color::fromHSL (float h, float s, float l, float a = 1.0f) static constexpr noexcept
Constructs a color from HSL values.
This static method allows for the creation of a color from its HSL representation. It is useful for generating colors based on more perceptual components rather than direct color component manipulation.
Parameters
h The hue component, normalized to [0, 1].
s The saturation component, normalized to [0, 1].
l The luminance component, normalized to [0, 1].
a The alpha component, normalized to [0, 1].
Returns
A Color object corresponding to the given HSL values.
References a, b, Color(), g, and r.
Referenced by contrasting().
toHSV()
std::tuple< float, float, float > yup::Color::toHSV () const constexpr noexcept
Converts the color to its HSV (Hue, Saturation, Value) components.
This method provides a way to obtain the HSV representation of the color, which can be useful for color manipulation and effects. The returned tuple contains the hue, saturation, and value components, respectively.
Returns
A tuple consisting of hue, saturation, and value.
References getBlueFloat(), getGreenFloat(), getRedFloat(), yup::jmax(), and yup::jmin().
fromHSV()
constexpr Color yup::Color::fromHSV (float h, float s, float v, float a = 1.0f) static constexpr noexcept
Constructs a color from HSV values.
This static method allows for the creation of a color from its HSV representation. It is useful for generating colors based on more perceptual components rather than direct color component manipulation.
Parameters
h The hue component, normalized to [0, 1].
s The saturation component, normalized to [0, 1].
v The value component, normalized to [0, 1].
a The alpha component, normalized to [0, 1].
Returns
A Color object corresponding to the given HSV values.
References a, b, Color(), g, yup::modulo(), and r.
brighter()
Color yup::Color::brighter (float amount) const constexpr noexcept
Makes the color brighter by a specified amount.
This method increases the RGB components of the color by the given amount, capped at 1.0 to maintain valid color values. It is useful for creating lighter variations of the color without altering the hue and saturation significantly.
Parameters
amount The amount by which to increase the RGB components, normalized to the range [0, 1].
Returns
A new Color object that is brighter than the original.
References a, Color(), getBlueFloat(), getGreenFloat(), and getRedFloat().
Referenced by darker(), and yup::paintTextButton().
darker()
Color yup::Color::darker (float amount) const constexpr noexcept
Makes the color darker by a specified amount.
This method decreases the RGB components of the color by the given amount, capped at 0 to maintain valid color values. It is useful for creating darker variations of the color without altering the hue and saturation significantly.
Parameters
amount The amount by which to decrease the RGB components, normalized to the range [0, 1].
Returns
A new Color object that is darker than the original.
References brighter(), and Color().
contrasting() [1/2]
Color yup::Color::contrasting () const constexpr noexcept
Returns a contrasting color.
This method calculates a color that contrasts with the current color based on its luminance. It is particularly useful for ensuring text or UI elements are readable when placed on backgrounds of varying colors.
Returns
A new Color object that contrasts with the current color.
References Color(), and contrasting().
Referenced by contrasting().
contrasting() [2/2]
Color yup::Color::contrasting (float amount) const constexpr noexcept
Returns a contrasting color adjusted by a specified amount.
This method provides finer control over the contrast calculation by allowing adjustment of the hue shift used in determining the contrasting color. The luminance and saturation of the original color are maintained.
Parameters
amount The amount to adjust the hue by, normalized to the range [0, 1].
Returns
A new Color object that contrasts with the current color.
References a, Color(), fromHSL(), inverted(), yup::jlimit(), and yup::modulo().
invert()
Color & yup::Color::invert () constexpr noexcept
Inverts the color components (RGB) of the current color.
This method changes each RGB component to its complementary value, which is useful for creating negative effects or for visual highlights.
Returns
A reference to this Color object, now with inverted RGB values.
References b, Color(), g, and r.
Referenced by inverted().
inverted()
Color yup::Color::inverted () const constexpr noexcept
Returns a new color that is the inverse of the current color.
This method creates a new Color object with each RGB component set to its complementary value, effectively providing the negative of the color.
Returns
A new Color object with inverted RGB values.
References Color(), and invert().
Referenced by contrasting().
invertAlpha()
Color & yup::Color::invertAlpha () constexpr noexcept
Inverts the alpha component of the current color.
This method changes the alpha component to its complementary value, which is useful for reversing transparency effects.
Returns
A reference to this Color object, now with an inverted alpha value.
References a, and Color().
Referenced by invertedAlpha().
invertedAlpha()
Color yup::Color::invertedAlpha () const constexpr noexcept
Returns a new color that is the inverse of the current color in terms of alpha transparency.
This method creates a new Color object with the alpha component set to its complementary value, effectively reversing the transparency of the color.
Returns
A new Color object with an inverted alpha value.
References Color(), and invertAlpha().
opaqueRandom()
Color yup::Color::opaqueRandom () static noexcept
References Color().
toString()
String yup::Color::toString () const
References a, b, g, r, and yup::String::toHexString().
toStringRGB()
String yup::Color::toStringRGB (bool withAlpha) const
References b, g, r, and withAlpha().
fromString()
Color yup::Color::fromString (const String & colourString) static
References Color(), yup::String::startsWith(), and yup::String::startsWithIgnoreCase().
Member Data Documentation
data
uint32 yup::Color::data = 0xff000000
Referenced by Color(), Color(), getARGB(), and operator uint32().
b
uint8 yup::Color::b
Referenced by Color(), Color(), fromHSL(), fromHSV(), getBlue(), getBlueFloat(), invert(), setBlue(), setBlue(), toString(), toStringRGB(), withAlpha(), withAlpha(), withGreen(), withGreen(), withMultipliedAlpha(), withMultipliedAlpha(), withRed(), and withRed().
g
uint8 yup::Color::g
Referenced by Color(), Color(), fromHSL(), fromHSV(), getGreen(), getGreenFloat(), invert(), setGreen(), setGreen(), toString(), toStringRGB(), withAlpha(), withAlpha(), withBlue(), withBlue(), withMultipliedAlpha(), withMultipliedAlpha(), withRed(), and withRed().
r
uint8 yup::Color::r
Referenced by Color(), Color(), fromHSL(), fromHSV(), getRed(), getRedFloat(), invert(), setRed(), setRed(), toString(), toStringRGB(), withAlpha(), withAlpha(), withBlue(), withBlue(), withGreen(), withGreen(), withMultipliedAlpha(), and withMultipliedAlpha().
a
uint8 yup::Color::a
Referenced by brighter(), Color(), Color(), contrasting(), fromHSL(), fromHSV(), getAlpha(), getAlphaFloat(), invertAlpha(), isOpaque(), isTransparent(), setAlpha(), setAlpha(), toString(), withBlue(), withBlue(), withGreen(), withGreen(), withMultipliedAlpha(), withMultipliedAlpha(), withRed(), and withRed().