YUP: yup::PositionableAudioSource Class Reference
yup::PositionableAudioSource Class Reference abstract
A type of AudioSource which can be repositioned.
Public Member Functions
~PositionableAudioSource () override=default
Destructor.
virtual void setNextReadPosition (int64 newPosition)=0
Tells the stream to move to a new position.
virtual int64 getNextReadPosition () const =0
Returns the position from which the next block will be returned.
virtual int64 getTotalLength () const =0
Returns the total length of the stream (in samples).
virtual bool isLooping () const =0
Returns true if this source is actually playing in a loop.
virtual void setLooping (bool shouldLoop)
Tells the source whether you'd like it to play in a loop.
Public Member Functions inherited from yup::AudioSource
virtual ~AudioSource ()=default
Destructor.
virtual void prepareToPlay (int samplesPerBlockExpected, double sampleRate)=0
Tells the source to prepare for playing.
virtual void releaseResources ()=0
Allows the source to release anything it no longer needs after playback has stopped.
virtual void getNextAudioBlock (const AudioSourceChannelInfo &bufferToFill)=0
Called repeatedly to fetch subsequent blocks of audio data.
Protected Member Functions
PositionableAudioSource ()=default
Creates the PositionableAudioSource.
Protected Member Functions inherited from yup::AudioSource
AudioSource ()=default
Creates an AudioSource.
Detailed Description
A type of AudioSource which can be repositioned.
The basic AudioSource just streams continuously with no idea of a current time or length, so the PositionableAudioSource is used for a finite stream that has a current read position.
See also
AudioSource, AudioTransportSource
Constructor & Destructor Documentation
PositionableAudioSource()
yup::PositionableAudioSource::PositionableAudioSource () protected default
Creates the PositionableAudioSource.
Referenced by yup::BufferingAudioSource::BufferingAudioSource(), and yup::AudioTransportSource::setSource().
~PositionableAudioSource()
yup::PositionableAudioSource::~PositionableAudioSource () override default
Destructor.
Member Function Documentation
setNextReadPosition()
virtual void yup::PositionableAudioSource::setNextReadPosition (int64 newPosition) pure virtual
Tells the stream to move to a new position.
Calling this indicates that the next call to AudioSource::getNextAudioBlock() should return samples from this position.
Note that this may be called on a different thread to getNextAudioBlock(), so the subclass should make sure it's synchronised.
Implemented in yup::AudioTransportSource, yup::BufferingAudioSource, and yup::MemoryAudioSource.
Referenced by yup::AudioTransportSource::setSource().
getNextReadPosition()
virtual int64 yup::PositionableAudioSource::getNextReadPosition () const pure virtual
Returns the position from which the next block will be returned.
See also
setNextReadPosition
Implemented in yup::AudioTransportSource, yup::BufferingAudioSource, and yup::MemoryAudioSource.
getTotalLength()
virtual int64 yup::PositionableAudioSource::getTotalLength () const pure virtual
Returns the total length of the stream (in samples).
Implemented in yup::AudioTransportSource, yup::BufferingAudioSource, and yup::MemoryAudioSource.
isLooping()
virtual bool yup::PositionableAudioSource::isLooping () const pure virtual
Returns true if this source is actually playing in a loop.
Implemented in yup::AudioTransportSource, yup::BufferingAudioSource, and yup::MemoryAudioSource.
References setLooping().
setLooping()
void yup::PositionableAudioSource::setLooping (bool shouldLoop) virtual
Tells the source whether you'd like it to play in a loop.
Reimplemented in yup::MemoryAudioSource.
Referenced by isLooping().