YUP: yup::ArrayAllocationBase< ElementType, TypeOfCriticalSectionToUse > Class Template Reference
yup::ArrayAllocationBase< ElementType, TypeOfCriticalSectionToUse > Class Template Reference
Implements some basic array storage allocation functions.
Inherits TypeOfCriticalSectionToUse.
Public Member Functions
ArrayAllocationBase ()=default
Creates an empty array.
~ArrayAllocationBase ()=default
Destructor.
ArrayAllocationBase (ArrayAllocationBase &&other) noexcept
ArrayAllocationBase & operator= (ArrayAllocationBase &&other) noexcept
void setAllocatedSize (int numElements)
Changes the amount of storage allocated.
void ensureAllocatedSize (int minNumElements)
Increases the amount of storage allocated if it is less than a given amount.
void shrinkToNoMoreThan (int maxNumElements)
Minimises the amount of storage allocated so that it's no more than the given number of elements.
void swapWith (ArrayAllocationBase &other) noexcept
Swap the contents of two objects.
Public Attributes
HeapBlock< ElementType > elements
int numAllocated = 0
Detailed Description
template<class ElementType, class TypeOfCriticalSectionToUse>
class yup::ArrayAllocationBase< ElementType, TypeOfCriticalSectionToUse >
Implements some basic array storage allocation functions.
This class isn't really for public use - it used to be part of the container classes but has since been superseded by ArrayBase. Eventually it will be removed from the API.
Constructor & Destructor Documentation
ArrayAllocationBase() [1/2]
template<class ElementType, class TypeOfCriticalSectionToUse> yup::ArrayAllocationBase< ElementType, TypeOfCriticalSectionToUse >::ArrayAllocationBase () default
Creates an empty array.
Referenced by ArrayAllocationBase(), operator=(), and swapWith().
~ArrayAllocationBase()
template<class ElementType, class TypeOfCriticalSectionToUse> yup::ArrayAllocationBase< ElementType, TypeOfCriticalSectionToUse >::~ArrayAllocationBase () default
Destructor.
ArrayAllocationBase() [2/2]
template<class ElementType, class TypeOfCriticalSectionToUse> yup::ArrayAllocationBase< ElementType, TypeOfCriticalSectionToUse >::ArrayAllocationBase (ArrayAllocationBase< ElementType, TypeOfCriticalSectionToUse > && other) noexcept
References ArrayAllocationBase().
Member Function Documentation
operator=()
template<class ElementType, class TypeOfCriticalSectionToUse> ArrayAllocationBase & yup::ArrayAllocationBase< ElementType, TypeOfCriticalSectionToUse >::operator= (ArrayAllocationBase< ElementType, TypeOfCriticalSectionToUse > && other) noexcept
References ArrayAllocationBase(), elements, and numAllocated.
setAllocatedSize()
template<class ElementType, class TypeOfCriticalSectionToUse> void yup::ArrayAllocationBase< ElementType, TypeOfCriticalSectionToUse >::setAllocatedSize (int numElements)
Changes the amount of storage allocated.
This will retain any data currently held in the array, and either add or remove extra space at the end.
Parameters
numElements the number of elements that are needed
References elements, and numAllocated.
Referenced by ensureAllocatedSize(), and shrinkToNoMoreThan().
ensureAllocatedSize()
template<class ElementType, class TypeOfCriticalSectionToUse> void yup::ArrayAllocationBase< ElementType, TypeOfCriticalSectionToUse >::ensureAllocatedSize (int minNumElements)
Increases the amount of storage allocated if it is less than a given amount.
This will retain any data currently held in the array, but will add extra space at the end to make sure there it's at least as big as the size passed in. If it's already bigger, no action is taken.
Parameters
minNumElements the minimum number of elements that are needed
References elements, numAllocated, and setAllocatedSize().
shrinkToNoMoreThan()
template<class ElementType, class TypeOfCriticalSectionToUse> void yup::ArrayAllocationBase< ElementType, TypeOfCriticalSectionToUse >::shrinkToNoMoreThan (int maxNumElements)
Minimises the amount of storage allocated so that it's no more than the given number of elements.
References numAllocated, and setAllocatedSize().
swapWith()
template<class ElementType, class TypeOfCriticalSectionToUse> void yup::ArrayAllocationBase< ElementType, TypeOfCriticalSectionToUse >::swapWith (ArrayAllocationBase< ElementType, TypeOfCriticalSectionToUse > & other) noexcept
Swap the contents of two objects.
References ArrayAllocationBase(), elements, and numAllocated.
Member Data Documentation
elements
template<class ElementType, class TypeOfCriticalSectionToUse> HeapBlock<ElementType> yup::ArrayAllocationBase< ElementType, TypeOfCriticalSectionToUse >::elements
Referenced by ensureAllocatedSize(), operator=(), setAllocatedSize(), and swapWith().
numAllocated
template<class ElementType, class TypeOfCriticalSectionToUse> int yup::ArrayAllocationBase< ElementType, TypeOfCriticalSectionToUse >::numAllocated = 0
Referenced by ensureAllocatedSize(), operator=(), setAllocatedSize(), shrinkToNoMoreThan(), and swapWith().