YUP: yup::AudioParameter::Listener Class Reference
yup::AudioParameter::Listener Class Reference abstract
A listener for parameter changes.
Public Member Functions
virtual ~Listener ()=default
virtual void parameterValueChanged (const AudioParameter::Ptr &parameter, int indexInContainer)=0
Called when the parameter value changes.
virtual void parameterGestureBegin (const AudioParameter::Ptr &parameter, int indexInContainer)=0
Called when a gesture begins.
virtual void parameterGestureEnd (const AudioParameter::Ptr &parameter, int indexInContainer)=0
Called when a gesture ends.
Detailed Description
A listener for parameter changes.
Constructor & Destructor Documentation
~Listener()
virtual yup::AudioParameter::Listener::~Listener () virtual default
Member Function Documentation
parameterValueChanged()
virtual void yup::AudioParameter::Listener::parameterValueChanged (const AudioParameter::Ptr & parameter, int indexInContainer) pure virtual
Called when the parameter value changes.
Referenced by yup::AudioParameter::setValueNotifyingHost().
parameterGestureBegin()
virtual void yup::AudioParameter::Listener::parameterGestureBegin (const AudioParameter::Ptr & parameter, int indexInContainer) pure virtual
Called when a gesture begins.
Referenced by yup::AudioParameter::beginChangeGesture().
parameterGestureEnd()
virtual void yup::AudioParameter::Listener::parameterGestureEnd (const AudioParameter::Ptr & parameter, int indexInContainer) pure virtual
Called when a gesture ends.
Referenced by yup::AudioParameter::endChangeGesture().