YUP: yup::UndoManager Class Reference
yup::UndoManager Class Reference
Manages undo and redo functionality for a set of actions.
Classes
struct ScopedTransaction
Helper class to ensure that certain actions are grouped as a single action.
Public Types
using Ptr = ReferenceCountedObjectPtr<UndoManager>
Public Member Functions
UndoManager ()
Creates a new UndoManager and starts the timer.
UndoManager (int maxHistorySize)
Creates a new UndoManager and starts the timer.
UndoManager (RelativeTime actionGroupThreshold)
Creates a new UndoManager and starts the timer.
UndoManager (int maxHistorySize, RelativeTime actionGroupThreshold)
Creates a new UndoManager and starts the timer.
bool perform (UndoableAction::Ptr f)
Adds a new action to the timeline and performs its redo method.
template<class T, class F>
bool perform (T object, F &&function)
Adds a new action to the timeline and performs its redo method.
void beginNewTransaction ()
Begins a new transaction.
void beginNewTransaction (StringRef transactionName)
Begins a new transaction with a given name.
int getNumTransactions () const
Returns the number of transactions in the undo manager.
String getTransactionName (int index) const
Retrieves the name of a transaction at the specified index.
String getCurrentTransactionName () const
Returns the name of the current transaction.
void setCurrentTransactionName (StringRef newName)
Sets the name of the current transaction.
bool canUndo () const
Check if undo action can be performed.
bool undo ()
Reverses the action in the current timeline position.
bool canRedo () const
Check if redo action can be performed.
bool redo ()
Performs the action in the current timeline position.
void clear ()
Clears the undo manager.
void setEnabled (bool shouldBeEnabled)
Enables or disables the undo manager.
bool isEnabled () const
Checks if the undo manager is enabled.
Public Member Functions inherited from yup::ReferenceCountedObject
void incReferenceCount () const noexcept
Increments the object's reference count.
void decReferenceCount () const noexcept
Decreases the object's reference count.
bool decReferenceCountWithoutDeleting () const noexcept
Decreases the object's reference count.
int getReferenceCount () const noexcept
Returns the object's current reference count.
Additional Inherited Members
Protected Member Functions inherited from yup::ReferenceCountedObject
ReferenceCountedObject ()=default
Creates the reference-counted object (with an initial ref count of zero).
ReferenceCountedObject (const ReferenceCountedObject &) noexcept
Copying from another object does not affect this one's reference-count.
ReferenceCountedObject (ReferenceCountedObject &&) noexcept
Copying from another object does not affect this one's reference-count.
ReferenceCountedObject & operator= (const ReferenceCountedObject &) noexcept
Copying from another object does not affect this one's reference-count.
ReferenceCountedObject & operator= (ReferenceCountedObject &&) noexcept
Copying from another object does not affect this one's reference-count.
virtual ~ReferenceCountedObject ()
Destructor.
void resetReferenceCount () const noexcept
Resets the reference count to zero without deleting the object.
Detailed Description
Manages undo and redo functionality for a set of actions.
The UndoManager class provides a way to manage undo and redo functionality for a set of actions. It allows you to perform actions, undo them, redo them, enable or disable the undo manager, and group actions together as a single action.
To use the UndoManager, create an instance of the class and call the perform method to add actions to the timeline. You can also use the undo and redo methods to reverse or perform the action in the current timeline position.
The UndoManager class also provides a ScopedActionIsolator helper class that allows you to group certain actions as a single action. This can be useful when you want to ensure that multiple actions are treated as a single unit for undo and redo purposes.
See also
UndoableAction
Member Typedef Documentation
Ptr
using yup::UndoManager::Ptr = ReferenceCountedObjectPtr<UndoManager>
Constructor & Destructor Documentation
UndoManager() [1/4]
yup::UndoManager::UndoManager ()
Creates a new UndoManager and starts the timer.
References setEnabled().
Referenced by yup::UndoManager::ScopedTransaction::ScopedTransaction(), and yup::UndoManager::ScopedTransaction::ScopedTransaction().
UndoManager() [2/4]
yup::UndoManager::UndoManager (int maxHistorySize)
Creates a new UndoManager and starts the timer.
Parameters
maxHistorySize The maximum number of items to keep in the history.
References setEnabled().
UndoManager() [3/4]
yup::UndoManager::UndoManager (RelativeTime actionGroupThreshold)
Creates a new UndoManager and starts the timer.
Parameters
actionGroupThreshold The time used to coalesce actions in the same transaction.
References setEnabled().
UndoManager() [4/4]
yup::UndoManager::UndoManager (int maxHistorySize, RelativeTime actionGroupThreshold)
Creates a new UndoManager and starts the timer.
Parameters
maxHistorySize The maximum number of items to keep in the history.
actionGroupThreshold The time used to coalesce actions in the same transaction.
References setEnabled().
Member Function Documentation
perform() [1/2]
bool yup::UndoManager::perform (UndoableAction::Ptr f)
Adds a new action to the timeline and performs its redo method.
Parameters
f The action to be performed.
Returns
true if the action was added and performed successfully, false otherwise.
References beginNewTransaction(), isEnabled(), yup::UndoableAction::perform(), and yup::Redo.
Referenced by perform().
perform() [2/2]
template<class T, class F> bool yup::UndoManager::perform (T object, F && function)
Adds a new action to the timeline and performs its redo method.
This method allows you to create an action using a weak referenceable object and a lambda that will be performed if the object is still alive.
Template Parameters
T The type of the object.
Parameters
object The object to be used in the action.
f The lambda function to be performed.
Returns
true if the action was added and performed successfully, false otherwise.
References perform().
beginNewTransaction() [1/2]
void yup::UndoManager::beginNewTransaction ()
Begins a new transaction.
References beginNewTransaction().
Referenced by beginNewTransaction(), and perform().
beginNewTransaction() [2/2]
void yup::UndoManager::beginNewTransaction (StringRef transactionName)
Begins a new transaction with a given name.
Parameters
transactionName The name of the transaction.
getNumTransactions()
int yup::UndoManager::getNumTransactions () const
Returns the number of transactions in the undo manager.
Returns
The number of transactions.
Referenced by getTransactionName().
getTransactionName()
String yup::UndoManager::getTransactionName (int index) const
Retrieves the name of a transaction at the specified index.
Parameters
index The index of the transaction.
Returns
The name of the transaction.
References getNumTransactions(), and yup::isPositiveAndBelow().
getCurrentTransactionName()
String yup::UndoManager::getCurrentTransactionName () const
Returns the name of the current transaction.
Returns
The name of the current transaction as a String.
setCurrentTransactionName()
void yup::UndoManager::setCurrentTransactionName (StringRef newName)
Sets the name of the current transaction.
Parameters
newName the new name for the transaction
canUndo()
bool yup::UndoManager::canUndo () const
Check if undo action can be performed.
Returns
true if an undo action can be performed, false otherwise.
References yup::isPositiveAndBelow().
undo()
bool yup::UndoManager::undo ()
Reverses the action in the current timeline position.
Returns
true if an action was reversed, false otherwise.
References yup::Undo.
canRedo()
bool yup::UndoManager::canRedo () const
Check if redo action can be performed.
Returns
true if a redo action can be performed, false otherwise.
References yup::isPositiveAndBelow().
redo()
bool yup::UndoManager::redo ()
Performs the action in the current timeline position.
Returns
true if an action was performed, false otherwise.
References yup::Redo.
clear()
void yup::UndoManager::clear ()
Clears the undo manager.
This function clears the undo manager, removing all the stored undo/redo actions.
setEnabled()
void yup::UndoManager::setEnabled (bool shouldBeEnabled)
Enables or disables the undo manager.
Parameters
shouldBeEnabled true to enable the undo manager, false to disable it.
Disabling the undo manager will clear the history and stop the timer.
References isEnabled(), yup::Timer::startTimer(), and yup::Timer::stopTimer().
Referenced by UndoManager(), UndoManager(), UndoManager(), and UndoManager().
isEnabled()
bool yup::UndoManager::isEnabled () const
Checks if the undo manager is enabled.
Returns
true if the undo manager is enabled, false otherwise.
Referenced by perform(), and setEnabled().