YUP: yup::AudioProcessor Class Reference
yup::AudioProcessor Class Reference abstract
Base class for all audio processors.
Public Member Functions
AudioProcessor (StringRef name, AudioBusLayout busLayout)
Constructs an AudioProcessor.
virtual ~AudioProcessor ()
Destructs an AudioProcessor.
String getName () const
Returns the name of the processor.
Span< const AudioParameter::Ptr > getParameters () const
Returns the parameters.
void addParameter (AudioParameter::Ptr parameter)
Adds a parameter.
const AudioBusLayout & getBusLayout () const noexcept
Returns the bus layout.
int getNumAudioOutputs () const
Returns the number of audio outputs.
int getNumAudioInputs () const
Returns the number of audio inputs.
virtual void prepareToPlay (float sampleRate, int maxBlockSize)=0
Prepares the processor for playback.
virtual void releaseResources ()=0
Releases resources.
virtual void processBlock (AudioBuffer< float > &audioBuffer, MidiBuffer &midiBuffer)=0
Processes a block of audio.
virtual void processBlock (AudioBuffer< double > &audioBuffer, MidiBuffer &midiBuffer)
Processes a block of audio.
virtual void flush ()
Flushes the processor.
CriticalSection & getProcessLock ()
bool isSuspended () const
virtual void suspendProcessing (bool shouldSuspend)
float getSampleRate () const
int getSamplesPerBlock () const
virtual int getTailSamples ()
virtual int getLatencySamples ()
void setPlayHead (AudioPlayHead *playHead)
AudioPlayHead * getPlayHead ()
virtual int getCurrentPreset () const noexcept=0
Returns the current preset index.
virtual void setCurrentPreset (int index) noexcept=0
Sets the current preset index.
virtual int getNumPresets () const =0
Returns the number of available user presets.
virtual String getPresetName (int index) const =0
Returns the name of a preset by index.
virtual void setPresetName (int index, StringRef newName)=0
Returns the name of a preset by index.
virtual Result loadStateFromMemory (const MemoryBlock &memoryBlock)=0
Loads a preset from a memory block.
virtual Result saveStateIntoMemory (MemoryBlock &memoryBlock)=0
Saves the current state as a memory block.
virtual bool hasEditor () const =0
Returns true if the processor has an editor.
virtual AudioProcessorEditor * createEditor ()
Creates an editor for the processor.
void setPlaybackConfiguration (float sampleRate, int samplesPerBlock)
Detailed Description
Base class for all audio processors.
See also
AudioProcessorEditor
Constructor & Destructor Documentation
AudioProcessor()
yup::AudioProcessor::AudioProcessor (StringRef name, AudioBusLayout busLayout)
Constructs an AudioProcessor.
~AudioProcessor()
yup::AudioProcessor::~AudioProcessor () virtual
Destructs an AudioProcessor.
Member Function Documentation
getName()
String yup::AudioProcessor::getName () const
Returns the name of the processor.
getParameters()
Span< const AudioParameter::Ptr > yup::AudioProcessor::getParameters () const
Returns the parameters.
Referenced by yup::clapEventToParameterChange().
addParameter()
void yup::AudioProcessor::addParameter (AudioParameter::Ptr parameter)
Adds a parameter.
References yup::AudioParameter::getID(), and yup::AudioParameter::setIndexInContainer().
getBusLayout()
const AudioBusLayout & yup::AudioProcessor::getBusLayout () const noexcept
Returns the bus layout.
getNumAudioOutputs()
int yup::AudioProcessor::getNumAudioOutputs () const
Returns the number of audio outputs.
getNumAudioInputs()
int yup::AudioProcessor::getNumAudioInputs () const
Returns the number of audio inputs.
prepareToPlay()
virtual void yup::AudioProcessor::prepareToPlay (float sampleRate, int maxBlockSize) pure virtual
Prepares the processor for playback.
Referenced by setPlaybackConfiguration().
releaseResources()
virtual void yup::AudioProcessor::releaseResources () pure virtual
Releases resources.
Referenced by setPlaybackConfiguration().
processBlock() [1/2]
virtual void yup::AudioProcessor::processBlock (AudioBuffer< float > & audioBuffer, MidiBuffer & midiBuffer) pure virtual
Processes a block of audio.
Parameters
audioBuffer The audio buffer to process.
midiBuffer The MIDI buffer to process.
processBlock() [2/2]
virtual void yup::AudioProcessor::processBlock (AudioBuffer< double > & audioBuffer, MidiBuffer & midiBuffer) virtual
Processes a block of audio.
Parameters
audioBuffer The audio buffer to process.
midiBuffer The MIDI buffer to process.
flush()
virtual void yup::AudioProcessor::flush () virtual
Flushes the processor.
getProcessLock()
CriticalSection & yup::AudioProcessor::getProcessLock ()
isSuspended()
bool yup::AudioProcessor::isSuspended () const
suspendProcessing()
void yup::AudioProcessor::suspendProcessing (bool shouldSuspend) virtual
getSampleRate()
float yup::AudioProcessor::getSampleRate () const
getSamplesPerBlock()
int yup::AudioProcessor::getSamplesPerBlock () const
getTailSamples()
virtual int yup::AudioProcessor::getTailSamples () virtual
getLatencySamples()
virtual int yup::AudioProcessor::getLatencySamples () virtual
setPlayHead()
void yup::AudioProcessor::setPlayHead (AudioPlayHead * playHead)
getPlayHead()
AudioPlayHead * yup::AudioProcessor::getPlayHead ()
getCurrentPreset()
virtual int yup::AudioProcessor::getCurrentPreset () const pure virtual noexcept
Returns the current preset index.
setCurrentPreset()
virtual void yup::AudioProcessor::setCurrentPreset (int index) pure virtual noexcept
Sets the current preset index.
References setCurrentPreset().
Referenced by setCurrentPreset().
getNumPresets()
virtual int yup::AudioProcessor::getNumPresets () const pure virtual
Returns the number of available user presets.
References getNumPresets().
Referenced by getNumPresets().
getPresetName()
virtual String yup::AudioProcessor::getPresetName (int index) const pure virtual
Returns the name of a preset by index.
References getPresetName().
Referenced by getPresetName().
setPresetName()
virtual void yup::AudioProcessor::setPresetName (int index, StringRef newName) pure virtual
Returns the name of a preset by index.
References setPresetName().
Referenced by setPresetName().
loadStateFromMemory()
virtual Result yup::AudioProcessor::loadStateFromMemory (const MemoryBlock & memoryBlock) pure virtual
Loads a preset from a memory block.
Parameters
memoryBlock The memory block to load the state from.
Returns
The result of the operation.
References loadStateFromMemory().
Referenced by loadStateFromMemory().
saveStateIntoMemory()
virtual Result yup::AudioProcessor::saveStateIntoMemory (MemoryBlock & memoryBlock) pure virtual
Saves the current state as a memory block.
Parameters
memoryBlock The memory block to save the state to.
Returns
The result of the operation.
References saveStateIntoMemory().
Referenced by saveStateIntoMemory().
hasEditor()
virtual bool yup::AudioProcessor::hasEditor () const pure virtual
Returns true if the processor has an editor.
References hasEditor().
Referenced by hasEditor().
createEditor()
virtual AudioProcessorEditor * yup::AudioProcessor::createEditor () virtual
Creates an editor for the processor.
References createEditor().
Referenced by createEditor().
setPlaybackConfiguration()
void yup::AudioProcessor::setPlaybackConfiguration (float sampleRate, int samplesPerBlock)
References prepareToPlay(), and releaseResources().