YUP: yup::Graphics Class Reference
yup::Graphics Class Reference
A graphical interface for drawing operations within a defined rendering context.
Classes
class SavedState
Represents a saved state of the Graphics object.
Public Member Functions
Graphics (GraphicsContext &context, rive::Renderer &renderer, float scale=1.0f) noexcept
Constructs a Graphics object with a specific GraphicsContext and Renderer.
SavedState saveState ()
Saves the current state of the Graphics object.
void setFillColor (Color color)
Sets the current drawing fill color.
Color getFillColor () const
Retrieves the current drawing fill color.
void setStrokeColor (Color color)
Sets the current drawing stroke color.
Color getStrokeColor () const
Retrieves the current drawing stroke color.
void setFillColorGradient (ColorGradient gradient)
Sets the current color gradient for fills.
ColorGradient getFillColorGradient () const
Retrieves the current color gradient for fills.
void setStrokeColorGradient (ColorGradient gradient)
Sets the current color gradient for strokes.
ColorGradient getStrokeColorGradient () const
Retrieves the current color gradient for strokes.
void setStrokeWidth (float strokeWidth)
float getStrokeWidth () const
void setFeather (float feather)
float getFeather () const
void setOpacity (float opacity)
Sets the opacity for subsequent drawing operations.
float getOpacity () const
Retrieves the current opacity setting.
void setStrokeJoin (StrokeJoin join)
Sets the stroke join style for drawing lines and paths.
StrokeJoin getStrokeJoin () const
Retrieves the current stroke join style.
void setStrokeCap (StrokeCap cap)
Sets the stroke cap style for drawing lines and paths.
StrokeCap getStrokeCap () const
Retrieves the current stroke cap style.
void setBlendMode (BlendMode blendMode)
BlendMode getBlendMode () const
void setDrawingArea (const Rectangle< float > &r)
Defines the area within which drawing operations are clipped.
Rectangle< float > getDrawingArea () const
Retrieves the current drawing area, within which all drawing operations are clipped.
void setTransform (const AffineTransform &transform)
Defines the affine transformation to use when drawing.
AffineTransform getTransform () const
Retrieves the current affine transformation.
void setClipPath (const Rectangle< float > &clipRect)
void setClipPath (const Path &clipPath)
Path getClipPath () const
void strokeLine (float x1, float y1, float x2, float y2)
Draws a line between two points with a specified thickness.
void strokeLine (const Point< float > &p1, const Point< float > &p2)
Draws a line between two points with a specified thickness.
void fillAll ()
Fills the entire drawing area with the current color or gradient.
void fillRect (float x, float y, float width, float height)
Fills a rectangle with the current color or gradient.
void fillRect (const Rectangle< float > &r)
Fills a rectangle with the current color or gradient.
void strokeRect (float x, float y, float width, float height)
Draws a rectangle with a specified thickness.
void strokeRect (const Rectangle< float > &r)
Draws a rectangle with a specified thickness.
void fillRoundedRect (float x, float y, float width, float height, float radiusTopLeft, float radiusTopRight, float radiusBottomLeft, float radiusBottomRight)
Fills a rounded rectangle with specific corner radii.
void fillRoundedRect (const Rectangle< float > &r, float radiusTopLeft, float radiusTopRight, float radiusBottomLeft, float radiusBottomRight)
Fills a rounded rectangle with specific corner radii.
void fillRoundedRect (float x, float y, float width, float height, float radius)
Fills a rounded rectangle with a uniform corner radius.
void fillRoundedRect (const Rectangle< float > &r, float radius)
Fills a rounded rectangle with a uniform corner radius.
void strokeRoundedRect (float x, float y, float width, float height, float radiusTopLeft, float radiusTopRight, float radiusBottomLeft, float radiusBottomRight)
Draws a rounded rectangle with specific corner radii and a specified thickness.
void strokeRoundedRect (const Rectangle< float > &r, float radiusTopLeft, float radiusTopRight, float radiusBottomLeft, float radiusBottomRight)
Draws a rounded rectangle with specific corner radii and a specified thickness.
void strokeRoundedRect (float x, float y, float width, float height, float radius)
Draws a rounded rectangle with a uniform corner radius and a specified thickness.
void strokeRoundedRect (const Rectangle< float > &r, float radius)
Draws a rounded rectangle with a uniform corner radius and a specified thickness.
void strokePath (const Path &path)
Draws a path with a specified thickness.
void fillPath (const Path &path)
Fills a path with the current color or gradient.
void drawImageAt (const Image &image, const Point< float > &pos)
void fillFittedText (const StyledText &text, const Rectangle< float > &rect)
Draws an attributed text.
void strokeFittedText (const StyledText &text, const Rectangle< float > &rect)
void clipPath (const Rectangle< float > &r)
Clips the drawing area to the specified rectangle.
void clipPath (const Path &path)
Clips the drawing area to the specified path.
float getContextScale () const
Retrieves the global context scale, the one used to construct the graphics instance.
rive::Factory * getFactory ()
Retrieves the factory used for creating graphical objects.
rive::Renderer * getRenderer ()
Retrieves the renderer used for drawing operations.
Detailed Description
A graphical interface for drawing operations within a defined rendering context.
This class provides a high-level drawing interface to perform various graphical operations such as drawing shapes, setting colors, and managing the state of a drawing context. It utilizes an underlying GraphicsContext and Renderer for actual drawing operations.
Constructor & Destructor Documentation
Graphics()
yup::Graphics::Graphics (GraphicsContext & context, rive::Renderer & renderer, float scale = 1.0f) noexcept
Constructs a Graphics object with a specific GraphicsContext and Renderer.
Parameters
context Reference to the GraphicsContext that defines the drawing surface and capabilities.
renderer Reference to the Renderer that executes the drawing commands.
Referenced by yup::Graphics::SavedState::operator=(), and yup::Graphics::SavedState::SavedState().
Member Function Documentation
saveState()
Graphics::SavedState yup::Graphics::saveState () nodiscard
Saves the current state of the Graphics object.
Returns
A SavedState object that can be used to restore the state later.
setFillColor()
void yup::Graphics::setFillColor (Color color)
Sets the current drawing fill color.
Parameters
color The new color to use for subsequent fill drawing operations.
Referenced by yup::DocumentWindow::paint(), yup::paintLabel(), yup::paintSlider(), yup::paintTextButton(), and yup::paintTextEditor().
getFillColor()
Color yup::Graphics::getFillColor () const
Retrieves the current drawing fill color.
Returns
The current color for fill drawing.
Referenced by clipPath().
setStrokeColor()
void yup::Graphics::setStrokeColor (Color color)
Sets the current drawing stroke color.
Parameters
color The new color to use for subsequent stroke drawing operations.
Referenced by yup::paintLabel(), yup::paintSlider(), yup::paintTextButton(), and yup::paintTextEditor().
getStrokeColor()
Color yup::Graphics::getStrokeColor () const
Retrieves the current drawing stroke color.
Returns
The current color for stroke drawing.
Referenced by clipPath().
setFillColorGradient()
void yup::Graphics::setFillColorGradient (ColorGradient gradient)
Sets the current color gradient for fills.
Parameters
gradient The new color gradient to use for subsequent fill drawing operations.
getFillColorGradient()
ColorGradient yup::Graphics::getFillColorGradient () const
Retrieves the current color gradient for fills.
Returns
The current color gradient for fill drawing.
Referenced by clipPath().
setStrokeColorGradient()
void yup::Graphics::setStrokeColorGradient (ColorGradient gradient)
Sets the current color gradient for strokes.
Parameters
gradient The new color gradient to use for subsequent stroke drawing operations.
getStrokeColorGradient()
ColorGradient yup::Graphics::getStrokeColorGradient () const
Retrieves the current color gradient for strokes.
Returns
The current color gradient for stroke drawing.
Referenced by clipPath().
setStrokeWidth()
void yup::Graphics::setStrokeWidth (float strokeWidth)
References yup::jmax().
Referenced by yup::paintLabel(), yup::paintSlider(), yup::paintTextButton(), and yup::paintTextEditor().
getStrokeWidth()
float yup::Graphics::getStrokeWidth () const
Referenced by clipPath().
setFeather()
void yup::Graphics::setFeather (float feather)
References yup::jmax().
getFeather()
float yup::Graphics::getFeather () const
Referenced by clipPath().
setOpacity()
void yup::Graphics::setOpacity (float opacity)
Sets the opacity for subsequent drawing operations.
Parameters
opacity The new opacity level (0.0-1.0).
References yup::jlimit().
getOpacity()
float yup::Graphics::getOpacity () const
Retrieves the current opacity setting.
Returns
The current opacity level.
setStrokeJoin()
void yup::Graphics::setStrokeJoin (StrokeJoin join)
Sets the stroke join style for drawing lines and paths.
Parameters
join The join style to use.
getStrokeJoin()
StrokeJoin yup::Graphics::getStrokeJoin () const
Retrieves the current stroke join style.
Returns
The stroke join style.
setStrokeCap()
void yup::Graphics::setStrokeCap (StrokeCap cap)
Sets the stroke cap style for drawing lines and paths.
Parameters
cap The cap style to use.
Referenced by yup::paintSlider().
getStrokeCap()
StrokeCap yup::Graphics::getStrokeCap () const
Retrieves the current stroke cap style.
Returns
The stroke cap style.
setBlendMode()
void yup::Graphics::setBlendMode (BlendMode blendMode)
getBlendMode()
BlendMode yup::Graphics::getBlendMode () const
setDrawingArea()
void yup::Graphics::setDrawingArea (const Rectangle< float > & r)
Defines the area within which drawing operations are clipped.
Parameters
r The rectangle that defines the clipping region.
getDrawingArea()
Rectangle< float > yup::Graphics::getDrawingArea () const
Retrieves the current drawing area, within which all drawing operations are clipped.
Returns
The current clipping rectangle.
Referenced by clipPath().
setTransform()
void yup::Graphics::setTransform (const AffineTransform & transform)
Defines the affine transformation to use when drawing.
Parameters
transform The affine transformation used when drawing.
References yup::Rectangle< ValueType >::transform().
getTransform()
AffineTransform yup::Graphics::getTransform () const
Retrieves the current affine transformation.
Returns
The current affine transformation.
Referenced by clipPath().
setClipPath() [1/2]
void yup::Graphics::setClipPath (const Rectangle< float > & clipRect)
References yup::Path::addRectangle(), and setClipPath().
Referenced by setClipPath().
setClipPath() [2/2]
void yup::Graphics::setClipPath (const Path & clipPath)
References clipPath().
getClipPath()
Path yup::Graphics::getClipPath () const
strokeLine() [1/2]
void yup::Graphics::strokeLine (float x1, float y1, float x2, float y2)
Draws a line between two points with a specified thickness.
Parameters
x1 The x-coordinate of the first point.
y1 The y-coordinate of the first point.
x2 The x-coordinate of the second point.
y2 The y-coordinate of the second point.
thickness The thickness of the line.
References yup::Path::lineTo(), yup::Path::moveTo(), and yup::Path::reserveSpace().
Referenced by strokeLine().
strokeLine() [2/2]
void yup::Graphics::strokeLine (const Point< float > & p1, const Point< float > & p2)
Draws a line between two points with a specified thickness.
Parameters
p1 The first point.
p2 The second point.
thickness The thickness of the line.
References yup::Point< ValueType >::getX(), yup::Point< ValueType >::getY(), and strokeLine().
fillAll()
void yup::Graphics::fillAll ()
Fills the entire drawing area with the current color or gradient.
References yup::Path::addRectangle().
Referenced by yup::DocumentWindow::paint().
fillRect() [1/2]
void yup::Graphics::fillRect (float x, float y, float width, float height)
Fills a rectangle with the current color or gradient.
Parameters
x The x-coordinate of the rectangle's top-left corner.
y The y-coordinate of the rectangle's top-left corner.
width The width of the rectangle.
height The height of the rectangle.
References yup::Path::addRectangle().
Referenced by fillRect(), and yup::paintTextEditor().
fillRect() [2/2]
void yup::Graphics::fillRect (const Rectangle< float > & r)
Fills a rectangle with the current color or gradient.
Parameters
r The rectangle to fill.
References fillRect(), yup::Rectangle< ValueType >::getHeight(), yup::Rectangle< ValueType >::getWidth(), yup::Rectangle< ValueType >::getX(), and yup::Rectangle< ValueType >::getY().
strokeRect() [1/2]
void yup::Graphics::strokeRect (float x, float y, float width, float height)
Draws a rectangle with a specified thickness.
Parameters
x The x-coordinate of the rectangle's top-left corner.
y The y-coordinate of the rectangle's top-left corner.
width The width of the rectangle.
height The height of the rectangle.
thickness The thickness of the line used to draw the rectangle.
References yup::Path::addRectangle().
Referenced by yup::paintSlider(), and strokeRect().
strokeRect() [2/2]
void yup::Graphics::strokeRect (const Rectangle< float > & r)
Draws a rectangle with a specified thickness.
Parameters
r The rectangle to draw.
thickness The thickness of the line used to draw the rectangle.
References yup::Rectangle< ValueType >::getHeight(), yup::Rectangle< ValueType >::getWidth(), yup::Rectangle< ValueType >::getX(), yup::Rectangle< ValueType >::getY(), and strokeRect().
fillRoundedRect() [1/4]
void yup::Graphics::fillRoundedRect (float x, float y, float width, float height, float radiusTopLeft, float radiusTopRight, float radiusBottomLeft, float radiusBottomRight)
Fills a rounded rectangle with specific corner radii.
Parameters
x The x-coordinate of the rounded rectangle's top-left corner.
y The y-coordinate of the rounded rectangle's top-left corner.
width The width of the rounded rectangle.
height The height of the rounded rectangle.
radiusTopLeft The radius of the top-left corner.
radiusTopRight The radius of the top-right corner.
radiusBottomLeft The radius of the bottom-left corner.
radiusBottomRight The radius of the bottom-right corner.
References yup::Path::addRoundedRectangle().
Referenced by fillRoundedRect(), fillRoundedRect(), fillRoundedRect(), yup::paintTextButton(), and yup::paintTextEditor().
fillRoundedRect() [2/4]
void yup::Graphics::fillRoundedRect (const Rectangle< float > & r, float radiusTopLeft, float radiusTopRight, float radiusBottomLeft, float radiusBottomRight)
Fills a rounded rectangle with specific corner radii.
Parameters
r The rectangle to fill.
radiusTopLeft The radius of the top-left corner.
radiusTopRight The radius of the top-right corner.
radiusBottomLeft The radius of the bottom-left corner.
radiusBottomRight The radius of the bottom-right corner.
References fillRoundedRect(), yup::Rectangle< ValueType >::getHeight(), yup::Rectangle< ValueType >::getWidth(), yup::Rectangle< ValueType >::getX(), and yup::Rectangle< ValueType >::getY().
fillRoundedRect() [3/4]
void yup::Graphics::fillRoundedRect (float x, float y, float width, float height, float radius)
Fills a rounded rectangle with a uniform corner radius.
Parameters
x The x-coordinate of the rounded rectangle's top-left corner.
y The y-coordinate of the rounded rectangle's top-left corner.
width The width of the rounded rectangle.
height The height of the rounded rectangle.
radius The radius of all corners.
References fillRoundedRect().
fillRoundedRect() [4/4]
void yup::Graphics::fillRoundedRect (const Rectangle< float > & r, float radius)
Fills a rounded rectangle with a uniform corner radius.
Parameters
r The rectangle to fill.
radius The radius of all corners.
References fillRoundedRect(), yup::Rectangle< ValueType >::getHeight(), yup::Rectangle< ValueType >::getWidth(), yup::Rectangle< ValueType >::getX(), and yup::Rectangle< ValueType >::getY().
strokeRoundedRect() [1/4]
void yup::Graphics::strokeRoundedRect (float x, float y, float width, float height, float radiusTopLeft, float radiusTopRight, float radiusBottomLeft, float radiusBottomRight)
Draws a rounded rectangle with specific corner radii and a specified thickness.
Parameters
x The x-coordinate of the rounded rectangle's top-left corner.
y The y-coordinate of the rounded rectangle's top-left corner.
width The width of the rounded rectangle.
height The height of the rounded rectangle.
radiusTopLeft The radius of the top-left corner.
radiusTopRight The radius of the top-right corner.
radiusBottomLeft The radius of the bottom-left corner.
radiusBottomRight The radius of the bottom-right corner.
thickness The thickness of the line used to draw the rounded rectangle.
References yup::Path::addRoundedRectangle().
Referenced by yup::paintTextButton(), yup::paintTextEditor(), strokeRoundedRect(), strokeRoundedRect(), and strokeRoundedRect().
strokeRoundedRect() [2/4]
void yup::Graphics::strokeRoundedRect (const Rectangle< float > & r, float radiusTopLeft, float radiusTopRight, float radiusBottomLeft, float radiusBottomRight)
Draws a rounded rectangle with specific corner radii and a specified thickness.
Parameters
r The rectangle to draw.
radiusTopLeft The radius of the top-left corner.
radiusTopRight The radius of the top-right corner.
radiusBottomLeft The radius of the bottom-left corner.
radiusBottomRight The radius of the bottom-right corner.
thickness The thickness of the line used to draw the rounded rectangle.
References yup::Rectangle< ValueType >::getHeight(), yup::Rectangle< ValueType >::getWidth(), yup::Rectangle< ValueType >::getX(), yup::Rectangle< ValueType >::getY(), and strokeRoundedRect().
strokeRoundedRect() [3/4]
void yup::Graphics::strokeRoundedRect (float x, float y, float width, float height, float radius)
Draws a rounded rectangle with a uniform corner radius and a specified thickness.
Parameters
x The x-coordinate of the rounded rectangle's top-left corner.
y The y-coordinate of the rounded rectangle's top-left corner.
width The width of the rounded rectangle.
height The height of the rounded rectangle.
radius The radius of all corners.
thickness The thickness of the line used to draw the rounded rectangle.
References strokeRoundedRect().
strokeRoundedRect() [4/4]
void yup::Graphics::strokeRoundedRect (const Rectangle< float > & r, float radius)
Draws a rounded rectangle with a uniform corner radius and a specified thickness.
Parameters
r The rectangle to draw.
radius The radius of all corners.
thickness The thickness of the line used to draw the rounded rectangle.
References yup::Rectangle< ValueType >::getHeight(), yup::Rectangle< ValueType >::getWidth(), yup::Rectangle< ValueType >::getX(), yup::Rectangle< ValueType >::getY(), and strokeRoundedRect().
strokePath()
void yup::Graphics::strokePath (const Path & path)
Draws a path with a specified thickness.
Parameters
path The path to draw.
thickness The thickness of the line used to draw the path.
Referenced by yup::paintSlider().
fillPath()
void yup::Graphics::fillPath (const Path & path)
Fills a path with the current color or gradient.
Parameters
path The path to fill.
Referenced by yup::paintSlider().
drawImageAt()
void yup::Graphics::drawImageAt (const Image & image, const Point< float > & pos)
References yup::Image::createTextureIfNotPresent(), yup::Image::getHeight(), yup::Image::getTexture(), yup::Image::getWidth(), and yup::jlimit().
fillFittedText()
void yup::Graphics::fillFittedText (const StyledText & text, const Rectangle< float > & rect)
Draws an attributed text.
References yup::StyledText::isEmpty(), and yup::StyledText::needsUpdate().
Referenced by yup::paintLabel(), yup::paintTextButton(), and yup::paintTextEditor().
strokeFittedText()
void yup::Graphics::strokeFittedText (const StyledText & text, const Rectangle< float > & rect)
References yup::StyledText::isEmpty(), and yup::StyledText::needsUpdate().
Referenced by yup::paintLabel().
clipPath() [1/2]
void yup::Graphics::clipPath (const Rectangle< float > & r)
Clips the drawing area to the specified rectangle.
Parameters
r The rectangle to clip to.
References clipPath().
Referenced by clipPath(), clipPath(), and setClipPath().
clipPath() [2/2]
void yup::Graphics::clipPath (const Path & path)
Clips the drawing area to the specified path.
Parameters
path The path to clip to.
References clipPath(), getContextScale(), getDrawingArea(), getFactory(), getFeather(), getFillColor(), getFillColorGradient(), getRenderer(), getStrokeColor(), getStrokeColorGradient(), getStrokeWidth(), getTransform(), yup::Miter, yup::AffineTransform::scaled(), yup::Square, yup::SrcOver, and yup::AffineTransform::translated().
getContextScale()
float yup::Graphics::getContextScale () const
Retrieves the global context scale, the one used to construct the graphics instance.
Referenced by clipPath().
getFactory()
rive::Factory * yup::Graphics::getFactory ()
Retrieves the factory used for creating graphical objects.
Returns
Pointer to a rive::Factory object.
Referenced by clipPath().
getRenderer()
rive::Renderer * yup::Graphics::getRenderer ()
Retrieves the renderer used for drawing operations.
Returns
Pointer to a rive::Renderer object.
Referenced by clipPath(), and yup::Artboard::paint().