YUP: yup::YUPApplication Class Reference
yup::YUPApplication Class Reference
Main application class for the YUPApplication, extending YUP application functionality.
Public Member Functions
YUPApplication ()
Constructor for the YUPApplication.
~YUPApplication () override
Destructor for the YUPApplication.
bool moreThanOneInstanceAllowed () override
Determines if multiple instances of the application are allowed.
void anotherInstanceStarted (const String &commandLine) override
Called when another instance of the application has been started.
void systemRequestedQuit () override
Called when the system requests the application to quit.
void suspended () override
Called when the application is suspended.
void resumed () override
Called when the application is resumed from a suspended state.
void unhandledException (const std::exception *, const String &sourceFilename, int lineNumber) override
Called when an unhandled exception occurs.
Public Member Functions inherited from yup::YUPApplicationBase
virtual ~YUPApplicationBase ()
Destructor.
virtual const String getApplicationName ()=0
Returns the application's name.
virtual const String getApplicationVersion ()=0
Returns the application's version number.
virtual void initialise (const String &commandLineParameters)=0
Called when the application starts.
virtual void shutdown ()=0
virtual void memoryWarningReceived ()
Called by the operating system to indicate that you should reduce your memory footprint.
virtual bool backButtonPressed ()
This will be called when the back button on a device is pressed.
void setApplicationReturnValue (int newReturnValue) noexcept
Sets the value that should be returned as the application's exit code when the app quits.
int getApplicationReturnValue () const noexcept
Returns the value that has been set as the application's exit code.
bool isInitialising () const noexcept
Returns true if the application hasn't yet completed its initialise() method and entered the main event loop.
Additional Inherited Members
Static Public Member Functions inherited from yup::YUPApplicationBase
static YUPApplicationBase * getInstance () noexcept
Returns the global instance of the application object that's running.
static void quit ()
Signals that the main message loop should stop and the application should terminate.
static StringArray YUP_CALLTYPE getCommandLineParameterArray ()
Returns the application's command line parameters as a set of strings.
static String YUP_CALLTYPE getCommandLineParameters ()
Returns the application's command line parameters as a single string.
static bool isStandaloneApp () noexcept
Returns true if this executable is running as an app (as opposed to being a plugin or other kind of shared library.
Protected Member Functions inherited from yup::YUPApplicationBase
YUPApplicationBase ()
Detailed Description
Main application class for the YUPApplication, extending YUP application functionality.
This class defines the lifecycle and behavior of the application using the YUP framework, handling events such as application start and quit, as well as managing application instances.
Constructor & Destructor Documentation
YUPApplication()
yup::YUPApplication::YUPApplication ()
Constructor for the YUPApplication.
Initializes the application, potentially setting up necessary state or resources.
References yup::initialiseYup_Windowing().
~YUPApplication()
yup::YUPApplication::~YUPApplication () override
Destructor for the YUPApplication.
Cleans up any resources or state before the application is closed.
References yup::shutdownYup_Windowing().
Member Function Documentation
moreThanOneInstanceAllowed()
bool yup::YUPApplication::moreThanOneInstanceAllowed () override virtual
Determines if multiple instances of the application are allowed.
Returns
True if more than one instance is allowed, false otherwise.
Implements yup::YUPApplicationBase.
anotherInstanceStarted()
void yup::YUPApplication::anotherInstanceStarted (const String & commandLine) override virtual
Called when another instance of the application has been started.
This method can handle arguments passed from the new instance, allowing for inter-instance communication.
Parameters
commandLine The command line string from the starting instance.
Implements yup::YUPApplicationBase.
References yup::ignoreUnused().
systemRequestedQuit()
void yup::YUPApplication::systemRequestedQuit () override virtual
Called when the system requests the application to quit.
This method can perform cleanup operations before the application exits. If the quit request needs to be denied (to ask user for unsaved changes, etc.), this method can be overridden to handle such scenarios.
Implements yup::YUPApplicationBase.
References yup::YUPApplicationBase::quit().
suspended()
void yup::YUPApplication::suspended () override virtual
Called when the application is suspended.
This could occur when the application is minimized or not the focus on the device, allowing for resource conservation operations to take place.
Implements yup::YUPApplicationBase.
resumed()
void yup::YUPApplication::resumed () override virtual
Called when the application is resumed from a suspended state.
This method can be used to re-initialize resources or state that was released or altered upon suspension.
Implements yup::YUPApplicationBase.
unhandledException()
void yup::YUPApplication::unhandledException (const std::exception * ex, const String & sourceFilename, int lineNumber) override virtual
Called when an unhandled exception occurs.
This method provides a way to handle exceptions that are not caught elsewhere in the application, possibly allowing the application to recover or to log additional diagnostic information.
Parameters
e Pointer to the exception object.
sourceFilename Name of the file where the exception occurred.
lineNumber Line number in the source file where the exception occurred.
Implements yup::YUPApplicationBase.
References yup::ignoreUnused().