YUP: yup::DeletedAtShutdown Class Reference
yup::DeletedAtShutdown Class Reference
Classes derived from this will be automatically deleted when the application exits.
Static Public Member Functions
static void deleteAll ()
Deletes all extant objects.
Protected Member Functions
DeletedAtShutdown ()
Creates a DeletedAtShutdown object.
virtual ~DeletedAtShutdown ()
Destructor.
Detailed Description
Classes derived from this will be automatically deleted when the application exits.
After YUPApplicationBase::shutdown() has been called, any objects derived from DeletedAtShutdown which are still in existence will be deleted in the reverse order to that in which they were created.
So if you've got a singleton and don't want to have to explicitly delete it, just inherit from this and it'll be taken care of.
Constructor & Destructor Documentation
DeletedAtShutdown()
yup::DeletedAtShutdown::DeletedAtShutdown () protected
Creates a DeletedAtShutdown object.
Referenced by deleteAll().
~DeletedAtShutdown()
yup::DeletedAtShutdown::~DeletedAtShutdown () protected virtual
Destructor.
It's ok to delete these objects explicitly - it's only the ones left dangling at the end that will be deleted automatically.
Member Function Documentation
deleteAll()
void yup::DeletedAtShutdown::deleteAll () static
Deletes all extant objects.
This shouldn't be used by applications, as it's called automatically in the shutdown code of the YUPApplicationBase class.
References deleteAll(), DeletedAtShutdown(), and yup::Array< ElementType, TypeOfCriticalSectionToUse, minimumAllocatedSize >::size().
Referenced by deleteAll(), and yup::shutdownYup_GUI().