YUP: yup::StatisticsAccumulator< FloatType > Class Template Reference
yup::StatisticsAccumulator< FloatType > Class Template Reference
A class that measures various statistics about a series of floating point values that it is given.
Public Member Functions
StatisticsAccumulator ()=default
Constructs a new StatisticsAccumulator.
void addValue (FloatType v) noexcept
Add a new value to the accumulator.
void reset () noexcept
Reset the accumulator.
FloatType getAverage () const noexcept
Returns the average (arithmetic mean) of all previously added values.
FloatType getEnergy () const noexcept
Returns the energy of all the previously added values.
FloatType getVariance () const noexcept
Returns the variance of all previously added values.
FloatType getStandardDeviation () const noexcept
Returns the standard deviation of all previously added values.
FloatType getMinValue () const noexcept
Returns the smallest of all previously added values.
FloatType getMaxValue () const noexcept
Returns the largest of all previously added values.
size_t getCount () const noexcept
Returns how many values have been added to this accumulator.
Detailed Description
template<typename FloatType>
class yup::StatisticsAccumulator< FloatType >
A class that measures various statistics about a series of floating point values that it is given.
Constructor & Destructor Documentation
StatisticsAccumulator()
template<typename FloatType> yup::StatisticsAccumulator< FloatType >::StatisticsAccumulator () default
Constructs a new StatisticsAccumulator.
Referenced by reset().
Member Function Documentation
addValue()
template<typename FloatType> void yup::StatisticsAccumulator< FloatType >::addValue (FloatType v) noexcept
Add a new value to the accumulator.
This will update all running statistics accordingly.
References yup::yup_isfinite().
reset()
template<typename FloatType> void yup::StatisticsAccumulator< FloatType >::reset () noexcept
Reset the accumulator.
This will reset all currently saved statistcs.
References StatisticsAccumulator().
getAverage()
template<typename FloatType> FloatType yup::StatisticsAccumulator< FloatType >::getAverage () const noexcept
Returns the average (arithmetic mean) of all previously added values.
If no values have been added yet, this will return zero.
getEnergy()
template<typename FloatType> FloatType yup::StatisticsAccumulator< FloatType >::getEnergy () const noexcept
Returns the energy of all the previously added values.
If no values have been added yet, this returns zero.
getVariance()
template<typename FloatType> FloatType yup::StatisticsAccumulator< FloatType >::getVariance () const noexcept
Returns the variance of all previously added values.
If no values have been added yet, this will return zero.
Referenced by getStandardDeviation().
getStandardDeviation()
template<typename FloatType> FloatType yup::StatisticsAccumulator< FloatType >::getStandardDeviation () const noexcept
Returns the standard deviation of all previously added values.
If no values have been added yet, this will return zero.
References getVariance().
getMinValue()
template<typename FloatType> FloatType yup::StatisticsAccumulator< FloatType >::getMinValue () const noexcept
Returns the smallest of all previously added values.
If no values have been added yet, this will return positive infinity.
getMaxValue()
template<typename FloatType> FloatType yup::StatisticsAccumulator< FloatType >::getMaxValue () const noexcept
Returns the largest of all previously added values.
If no values have been added yet, this will return negative infinity.
getCount()
template<typename FloatType> size_t yup::StatisticsAccumulator< FloatType >::getCount () const noexcept
Returns how many values have been added to this accumulator.