YUP: yup::LocalisedStrings Class Reference
yup::LocalisedStrings Class Reference
Used to convert strings to localised foreign-language versions.
Public Member Functions
LocalisedStrings (const String &fileContents, bool ignoreCaseOfKeys)
Creates a set of translations from the text of a translation file.
LocalisedStrings (const File &fileToLoad, bool ignoreCaseOfKeys)
Creates a set of translations from a file.
LocalisedStrings (const LocalisedStrings &)
LocalisedStrings & operator= (const LocalisedStrings &)
~LocalisedStrings ()=default
Destructor.
String translate (const String &text) const
Attempts to look up a string and return its localised version.
String translate (const String &text, const String &resultIfNotFound) const
Attempts to look up a string and return its localised version.
String getLanguageName () const
Returns the name of the language specified in the translation file.
const StringArray & getCountryCodes () const
Returns the list of suitable country codes listed in the translation file.
const StringPairArray & getMappings () const
Provides access to the actual list of mappings.
void addStrings (const LocalisedStrings &)
Adds and merges another set of translations into this set.
void setFallback (LocalisedStrings *fallbackStrings)
Gives this object a set of strings to use as a fallback if a string isn't found.
Static Public Member Functions
static void setCurrentMappings (LocalisedStrings *newTranslations)
Selects the current set of mappings to be used by the system.
static LocalisedStrings * getCurrentMappings ()
Returns the currently selected set of mappings.
static String translateWithCurrentMappings (const String &text)
Tries to translate a string using the currently selected set of mappings.
static String translateWithCurrentMappings (const char *text)
Tries to translate a string using the currently selected set of mappings.
Detailed Description
Used to convert strings to localised foreign-language versions.
This is basically a look-up table of strings and their translated equivalents. It can be loaded from a text file, so that you can supply a set of localised versions of strings that you use in your app.
To use it in your code, simply call the translate() method on each string that might have foreign versions, and if none is found, the method will just return the original string.
The translation file should start with some lines specifying a description of the language it contains, and also a list of ISO country codes where it might be appropriate to use the file. After that, each line of the file should contain a pair of quoted strings with an '=' sign.
E.g. for a french translation, the file might be:
language: French
countries: fr be mc ch lu
"hello" = "bonjour"
"goodbye" = "au revoir"
If the strings need to contain a quote character, they can use " instead, and if the first non-whitespace character on a line isn't a quote, then it's ignored, (you can use this to add comments).
Note that this is a singleton class, so don't create or destroy the object directly. There's also a TRANS (text) macro defined to make it easy to use the this.
printSomething (TRANS ("hello"));
This macro is used in the YUP classes themselves, so your application has a chance to intercept and translate any internal YUP text strings that might be shown. (You can easily get a list of all the messages by searching for the TRANS() macro in the YUP source code).
Constructor & Destructor Documentation
LocalisedStrings() [1/3]
yup::LocalisedStrings::LocalisedStrings (const String & fileContents, bool ignoreCaseOfKeys)
Creates a set of translations from the text of a translation file.
When you create one of these, you can call setCurrentMappings() to make it the set of mappings that the system's using.
Referenced by addStrings(), getCurrentMappings(), LocalisedStrings(), operator=(), setCurrentMappings(), setFallback(), and ~LocalisedStrings().
LocalisedStrings() [2/3]
yup::LocalisedStrings::LocalisedStrings (const File & fileToLoad, bool ignoreCaseOfKeys)
Creates a set of translations from a file.
When you create one of these, you can call setCurrentMappings() to make it the set of mappings that the system's using.
References yup::File::loadFileAsString().
LocalisedStrings() [3/3]
yup::LocalisedStrings::LocalisedStrings (const LocalisedStrings & other)
References yup::createCopyIfNotNull(), yup::get(), and LocalisedStrings().
~LocalisedStrings()
yup::LocalisedStrings::~LocalisedStrings () default
Destructor.
References getCurrentMappings(), LocalisedStrings(), setCurrentMappings(), translate(), and translateWithCurrentMappings().
Member Function Documentation
operator=()
LocalisedStrings & yup::LocalisedStrings::operator= (const LocalisedStrings & other)
References yup::createCopyIfNotNull(), and LocalisedStrings().
setCurrentMappings()
void yup::LocalisedStrings::setCurrentMappings (LocalisedStrings * newTranslations) static
Selects the current set of mappings to be used by the system.
The object you pass in will be automatically deleted when no longer needed, so don't keep a pointer to it. You can also pass in nullptr to remove the current mappings.
See also the TRANS() macro, which uses the current set to do its translation.
See also
translateWithCurrentMappings
References LocalisedStrings().
Referenced by ~LocalisedStrings().
getCurrentMappings()
LocalisedStrings * yup::LocalisedStrings::getCurrentMappings () static
Returns the currently selected set of mappings.
This is the object that was last passed to setCurrentMappings(). It may be nullptr if none has been created.
References LocalisedStrings().
Referenced by yup::translate(), and ~LocalisedStrings().
translateWithCurrentMappings() [1/2]
String yup::LocalisedStrings::translateWithCurrentMappings (const String & text) static
Tries to translate a string using the currently selected set of mappings.
If no mapping has been set, or if the mapping doesn't contain a translation for the string, this will just return the original string.
See also the TRANS() macro, which uses this method to do its translation.
See also
setCurrentMappings, getCurrentMappings
References yup::translate().
Referenced by ~LocalisedStrings().
translateWithCurrentMappings() [2/2]
String yup::LocalisedStrings::translateWithCurrentMappings (const char * text) static
Tries to translate a string using the currently selected set of mappings.
If no mapping has been set, or if the mapping doesn't contain a translation for the string, this will just return the original string.
See also the TRANS() macro, which uses this method to do its translation.
See also
setCurrentMappings, getCurrentMappings
References yup::translate().
translate() [1/2]
String yup::LocalisedStrings::translate (const String & text) const
Attempts to look up a string and return its localised version.
If the string isn't found in the list, the original string will be returned.
Referenced by ~LocalisedStrings().
translate() [2/2]
String yup::LocalisedStrings::translate (const String & text, const String & resultIfNotFound) const
Attempts to look up a string and return its localised version.
If the string isn't found in the list, the resultIfNotFound string will be returned.
getLanguageName()
String yup::LocalisedStrings::getLanguageName () const
Returns the name of the language specified in the translation file.
This is specified in the file using a line starting with "language:", e.g.
language: german
getCountryCodes()
const StringArray & yup::LocalisedStrings::getCountryCodes () const
Returns the list of suitable country codes listed in the translation file.
These is specified in the file using a line starting with "countries:", e.g.
countries: fr be mc ch lu
The country codes are supposed to be 2-character ISO compliant codes.
getMappings()
const StringPairArray & yup::LocalisedStrings::getMappings () const
Provides access to the actual list of mappings.
addStrings()
void yup::LocalisedStrings::addStrings (const LocalisedStrings & other)
Adds and merges another set of translations into this set.
Note that the language name and country codes of the new LocalisedStrings object must match that of this object - an assertion will be thrown if they don't match.
Any existing values will have their mappings overwritten by the new ones.
References LocalisedStrings().
setFallback()
void yup::LocalisedStrings::setFallback (LocalisedStrings * fallbackStrings)
Gives this object a set of strings to use as a fallback if a string isn't found.
The object that is passed-in will be owned and deleted by this object when no longer needed. It can be nullptr to clear the existing fallback object.
References LocalisedStrings().