YUP: yup::FileChooser Class Reference
yup::FileChooser Class Reference
A cross-platform file chooser dialog that allows users to select files or directories.
Public Types
using Ptr = ReferenceCountedObjectPtr<FileChooser>
using CompletionCallback = std::function<void (bool, const Array<File>&)>
A callback function type used by the async file chooser methods.
Public Member Functions
~FileChooser ()
Destructor.
void browseForFileToOpen (CompletionCallback callback)
Shows a dialog box to choose a file to open asynchronously.
void browseForMultipleFilesToOpen (CompletionCallback callback)
Same as browseForFileToOpen, but allows the user to select multiple files.
void browseForMultipleFilesOrDirectoriesToOpen (CompletionCallback callback)
Same as browseForMultipleFilesToOpen and browseForDirectory, but allows the user to select multiple files or directories.
void browseForFileToSave (CompletionCallback callback, bool warnAboutOverwritingExistingFiles)
Shows a dialog box to choose a file to save asynchronously.
void browseForDirectory (CompletionCallback callback)
Shows a dialog box to choose a directory asynchronously.
void showDialog (CompletionCallback callback, int flags)
Runs a modal file browser asynchronously.
Public Member Functions inherited from yup::ReferenceCountedObject
void incReferenceCount () const noexcept
Increments the object's reference count.
void decReferenceCount () const noexcept
Decreases the object's reference count.
bool decReferenceCountWithoutDeleting () const noexcept
Decreases the object's reference count.
int getReferenceCount () const noexcept
Returns the object's current reference count.
Static Public Member Functions
static Ptr create (const String &dialogBoxTitle, const File &initialFileOrDirectory=File(), const String &filePatternsAllowed=String(), bool useOSNativeDialogBox=true, bool treatFilePackagesAsDirs=false)
Creates a FileChooser.
Additional Inherited Members
Protected Member Functions inherited from yup::ReferenceCountedObject
ReferenceCountedObject ()=default
Creates the reference-counted object (with an initial ref count of zero).
ReferenceCountedObject (const ReferenceCountedObject &) noexcept
Copying from another object does not affect this one's reference-count.
ReferenceCountedObject (ReferenceCountedObject &&) noexcept
Copying from another object does not affect this one's reference-count.
ReferenceCountedObject & operator= (const ReferenceCountedObject &) noexcept
Copying from another object does not affect this one's reference-count.
ReferenceCountedObject & operator= (ReferenceCountedObject &&) noexcept
Copying from another object does not affect this one's reference-count.
virtual ~ReferenceCountedObject ()
Destructor.
void resetReferenceCount () const noexcept
Resets the reference count to zero without deleting the object.
Detailed Description
A cross-platform file chooser dialog that allows users to select files or directories.
This class provides a native file dialog experience on each platform, supporting:
Single file selection
Multiple file selection
File saving with optional default filename
Directory selection
File type filtering with extensions
Custom dialog titles and initial directories
Example usage:
// For opening a single file
auto chooser = FileChooser::create ("Select an audio file", File::getSpecialLocation(File::userDocumentsDirectory), "*.wav;*.mp3;*.aiff");
chooser->browseForFileToOpen ([](bool success, const Array<File>& results)
{
    if (success && results.size() > 0)
    {
        File selectedFile = results[0];
        // Process the selected file...
    }
});
// For opening multiple files
auto chooser = FileChooser::create ("Select audio files", File(), "*.wav;*.mp3");
chooser->browseForMultipleFilesToOpen ([](bool success, const Array<File>& results)
{
    if (success && results.size() > 0)
    {
        // Process the selected files...
        for (const auto& file : results)
        {
            // Process each file...
        }
    }
});
// For saving a file
auto chooser = FileChooser::create ("Save project", File(), "*.proj", true);
chooser->browseForFileToSave ([](bool success, const Array<File>& results)
{
    if (success && results.size() > 0)
    {
        File saveLocation = results[0];
        // Save to the selected location...
    }
}, true);
Member Typedef Documentation
Ptr
using yup::FileChooser::Ptr = ReferenceCountedObjectPtr<FileChooser>
CompletionCallback
using yup::FileChooser::CompletionCallback = std::function<void (bool, const Array<File>&)>
A callback function type used by the async file chooser methods.
Parameters
success true if the user selected files, false if they cancelled
results the array of selected files (may be empty if cancelled)
Constructor & Destructor Documentation
~FileChooser()
yup::FileChooser::~FileChooser () default
Destructor.
References create().
Member Function Documentation
create()
FileChooser::Ptr yup::FileChooser::create (const String & dialogBoxTitle, const File & initialFileOrDirectory = File(), const String & filePatternsAllowed = String(), bool useOSNativeDialogBox = true, bool treatFilePackagesAsDirs = false) static
Creates a FileChooser.
Parameters
dialogBoxTitle a text string to display in the dialog box to tell the user what the dialog is for.
initialFileOrDirectory the file or directory that should be selected when the dialog opens. If this is File(), a sensible default location will be used.
filePatternsAllowed a set of file patterns to specify which files can be selected - each pattern should be separated by a comma or semicolon, e.g. "*.wav;*.aiff" or "*.txt,*.doc". An empty string means that all files are allowed. To specify that sub-directories can also be selected, add "<Directories>" to the end of the pattern.
useOSNativeDialogBox if true, then on platforms that support it, a native dialog box will be used; if false, then a YUP-based browser dialog box will be displayed. Some platforms may not support native dialogs, in which case the YUP dialog will be used regardless of this setting.
treatFilePackagesAsDirs if true, then the file chooser will allow the selection of files inside packages when they are opened in the OS.
Referenced by ~FileChooser().
browseForFileToOpen()
void yup::FileChooser::browseForFileToOpen (CompletionCallback callback)
Shows a dialog box to choose a file to open asynchronously.
This will display the dialog, and when the user makes a selection or cancels, the callback will be invoked on the message thread.
Parameters
callback function to call when the dialog completes
See also
browseForMultipleFilesToOpen, browseForFileToSave, browseForDirectory
References showDialog().
browseForMultipleFilesToOpen()
void yup::FileChooser::browseForMultipleFilesToOpen (CompletionCallback callback)
Same as browseForFileToOpen, but allows the user to select multiple files.
Parameters
callback function to call when the dialog completes
See also
browseForFileToOpen
References showDialog().
browseForMultipleFilesOrDirectoriesToOpen()
void yup::FileChooser::browseForMultipleFilesOrDirectoriesToOpen (CompletionCallback callback)
Same as browseForMultipleFilesToOpen and browseForDirectory, but allows the user to select multiple files or directories.
Parameters
callback function to call when the dialog completes
See also
browseForMultipleFilesToOpen
References showDialog().
browseForFileToSave()
void yup::FileChooser::browseForFileToSave (CompletionCallback callback, bool warnAboutOverwritingExistingFiles)
Shows a dialog box to choose a file to save asynchronously.
This will display the dialog, and when the user makes a selection or cancels, the callback will be invoked on the message thread.
Parameters
callback function to call when the dialog completes
warnAboutOverwritingExistingFiles if true, the dialog will ask the user if they're sure they want to overwrite a file that already exists
See also
browseForFileToOpen
References showDialog().
browseForDirectory()
void yup::FileChooser::browseForDirectory (CompletionCallback callback)
Shows a dialog box to choose a directory asynchronously.
This will display the dialog, and when the user makes a selection or cancels, the callback will be invoked on the message thread.
Parameters
callback function to call when the dialog completes
See also
browseForFileToOpen
References showDialog().
showDialog()
void yup::FileChooser::showDialog (CompletionCallback callback, int flags)
Runs a modal file browser asynchronously.
Parameters
callback function to call when the dialog completes
flags a set of flags to specify which type of browser to use
Referenced by browseForDirectory(), browseForFileToOpen(), browseForFileToSave(), browseForMultipleFilesOrDirectoriesToOpen(), and browseForMultipleFilesToOpen().