YUP: yup::ArtboardFile Class Reference
yup::ArtboardFile Class Reference
Represents a Rive file.
Classes
struct AssetInfo
Public Types
using LoadResult = ResultValue<std::shared_ptr<ArtboardFile>>
The result of loading a Rive file.
using AssetLoadCallback = std::function<bool (const AssetInfo&, Span<const uint8>, rive::Factory& factory)>
Public Member Functions
const rive::File * getRiveFile () const
Returns the underlying Rive file.
rive::File * getRiveFile ()
Returns the underlying Rive file.
Static Public Member Functions
static LoadResult load (const File &file, rive::Factory &factory)
Loads a Rive file from a file.
static LoadResult load (const File &file, rive::Factory &factory, const AssetLoadCallback &assetCallback)
Loads a Rive file from a file.
static LoadResult load (InputStream &is, rive::Factory &factory)
Loads a Rive file from an input stream.
static LoadResult load (InputStream &is, rive::Factory &factory, const AssetLoadCallback &assetCallback)
Loads a Rive file from an input stream.
Detailed Description
Represents a Rive file.
This class is used to load Rive binary files (aka .riv files).
Member Typedef Documentation
LoadResult
using yup::ArtboardFile::LoadResult = ResultValue<std::shared_ptr<ArtboardFile>>
The result of loading a Rive file.
AssetLoadCallback
using yup::ArtboardFile::AssetLoadCallback = std::function<bool (const AssetInfo&, Span<const uint8>, rive::Factory& factory)>
Member Function Documentation
load() [1/4]
ArtboardFile::LoadResult yup::ArtboardFile::load (const File & file, rive::Factory & factory) static
Loads a Rive file from a file.
Parameters
file The file to load.
factory The factory to use to create the Rive file.
Returns
The result of loading the Rive file.
References load().
Referenced by load(), load(), load(), and load().
load() [2/4]
ArtboardFile::LoadResult yup::ArtboardFile::load (const File & file, rive::Factory & factory, const AssetLoadCallback & assetCallback) static
Loads a Rive file from a file.
Parameters
file The file to load.
factory The factory to use to create the Rive file.
Returns
The result of loading the Rive file.
References yup::File::createInputStream(), yup::File::existsAsFile(), yup::ResultValue< std::shared_ptr< ArtboardFile > >::fail(), and load().
load() [3/4]
ArtboardFile::LoadResult yup::ArtboardFile::load (InputStream & is, rive::Factory & factory) static
Loads a Rive file from an input stream.
Parameters
is The input stream to load the Rive file from.
factory The factory to use to create the Rive file.
Returns
The result of loading the Rive file.
References load().
load() [4/4]
ArtboardFile::LoadResult yup::ArtboardFile::load (InputStream & is, rive::Factory & factory, const AssetLoadCallback & assetCallback) static
Loads a Rive file from an input stream.
Parameters
is The input stream to load the Rive file from.
factory The factory to use to create the Rive file.
assetCallback The callback that will be invoked when loading to use to create the Rive file.
Returns
The result of loading the Rive file.
References yup::ResultValue< std::shared_ptr< ArtboardFile > >::fail(), yup::MemoryBlock::getData(), yup::MemoryBlock::getSize(), load(), yup::ResultValue< std::shared_ptr< ArtboardFile > >::ok(), and yup::InputStream::readIntoMemoryBlock().
getRiveFile() [1/2]
const rive::File * yup::ArtboardFile::getRiveFile () const
Returns the underlying Rive file.
References getRiveFile().
Referenced by getRiveFile(), and getRiveFile().
getRiveFile() [2/2]
rive::File * yup::ArtboardFile::getRiveFile ()
Returns the underlying Rive file.
References getRiveFile().