YUP: yup::Size< ValueType > Class Template Reference
yup::Size< ValueType > Class Template Reference
Represents a 2D size with width and height.
Public Member Functions
constexpr Size () noexcept=default
Constructs a default size object with zero width and height.
constexpr Size (ValueType newWidth, ValueType newHeight) noexcept
Constructs a size object with specified width and height.
constexpr Size (const Size &other) noexcept=default
Copy and move constructors and assignment operators.
constexpr Size (Size &&other) noexcept=default
constexpr Size & operator= (const Size &other) noexcept=default
constexpr Size & operator= (Size &&other) noexcept=default
constexpr ValueType getWidth () const noexcept
Gets the width of the size.
constexpr Size & setWidth (ValueType newWidth) noexcept
Sets the width of the size.
constexpr Size withWidth (ValueType newWidth) const noexcept
Returns a new size object with the specified width.
constexpr ValueType getHeight () const noexcept
Gets the height of the size.
constexpr Size & setHeight (ValueType newHeight) noexcept
Sets the height of the size.
constexpr Size withHeight (ValueType newHeight) const noexcept
Returns a new size object with the specified height.
constexpr bool isZero () const noexcept
Checks if both dimensions are zero.
constexpr bool isEmpty () const noexcept
Checks if either dimension is zero.
constexpr bool isVerticallyEmpty () const noexcept
Checks if the height is zero but not the width.
constexpr bool isHorizontallyEmpty () const noexcept
Checks if the width is zero but not the height.
constexpr bool isSquare () const noexcept
Checks if the width and height are equal.
constexpr ValueType area () const noexcept
Calculate area of the Size.
constexpr Size & reverse () noexcept
Reverse dimensions.
constexpr Size reversed () const noexcept
Create a reversed Size object.
constexpr Size & enlarge (ValueType amount) noexcept
Enlarge dimensions uniformly.
constexpr Size & enlarge (ValueType widthAmount, ValueType heightAmount) noexcept
Enlarge dimensions separately.
constexpr Size enlarged (ValueType amount) const noexcept
Create an enlarged Size object uniformly.
constexpr Size enlarged (ValueType widthAmount, ValueType heightAmount) const noexcept
Create an enlarged Size object separately.
constexpr Size & reduce (ValueType amount) noexcept
Reduce dimensions uniformly.
constexpr Size & reduce (ValueType widthAmount, ValueType heightAmount) noexcept
Reduce dimensions separately.
constexpr Size reduced (ValueType amount) const noexcept
Create a reduced Size object uniformly.
constexpr Size reduced (ValueType widthAmount, ValueType heightAmount) const noexcept
Create a reduced Size object separately.
template<class T>
constexpr auto scale (T scaleFactor) noexcept -> std::enable_if_t< std::is_floating_point_v< T >, Size & >
Scale Size dimensions.
template<class T>
constexpr auto scale (T scaleFactorX, T scaleFactorY) noexcept -> std::enable_if_t< std::is_floating_point_v< T >, Size & >
Scale Size dimensions separately.
template<class T>
constexpr auto scaled (T scaleFactor) const noexcept -> std::enable_if_t< std::is_floating_point_v< T >, Size >
Create a scaled Size object.
template<class T>
constexpr auto scaled (T scaleFactorX, T scaleFactorY) const noexcept -> std::enable_if_t< std::is_floating_point_v< T >, Size >
Create a scaled Size object separately.
template<class T>
constexpr Size< T > to () const noexcept
Convert Size to another type.
template<class T = ValueType>
constexpr auto roundToInt () const noexcept -> std::enable_if_t< std::is_floating_point_v< T >, Size< int > >
template<class T>
constexpr auto operator* (T scaleFactor) const noexcept -> std::enable_if_t< std::is_floating_point_v< T >, Size >
Multiplication operator.
template<class T>
constexpr auto operator*= (T scaleFactor) noexcept -> std::enable_if_t< std::is_floating_point_v< T >, Size & >
Multiplication assignment operator.
template<class T>
constexpr auto operator/ (T scaleFactor) const noexcept -> std::enable_if_t< std::is_floating_point_v< T >, Size >
Division operator.
template<class T>
constexpr auto operator/= (T scaleFactor) noexcept -> std::enable_if_t< std::is_floating_point_v< T >, Size & >
Division assignment operator.
constexpr bool approximatelyEqualTo (const Size &other) const noexcept
Returns true if the two sizes are approximately equal.
constexpr bool operator== (const Size &other) const noexcept
Equality operator.
constexpr bool operator!= (const Size &other) const noexcept
Inequality operator.
Detailed Description
template<class ValueType>
class yup::Size< ValueType >
Represents a 2D size with width and height.
This template class encapsulates a 2-dimensional size defined by width and height. It provides methods to manipulate and query the size dimensions, such as getting and setting the width and height, checking if the size is zero, empty, square, or has specific orientation emptiness, and performing arithmetic operations to modify or compare sizes. It supports both copy and move operations efficiently with default constructors and assignment operators.
Template Parameters
ValueType The type of the width and height (typically numeric).
Constructor & Destructor Documentation
Size() [1/4]
template<class ValueType> yup::Size< ValueType >::Size () constexpr default noexcept
Constructs a default size object with zero width and height.
Referenced by approximatelyEqualTo(), enlarge(), enlarge(), enlarged(), enlarged(), operator!=(), operator*(), operator*=(), operator/(), operator/=(), operator=(), operator=(), operator==(), reduce(), reduce(), reduced(), reduced(), reverse(), reversed(), roundToInt(), scale(), scale(), scaled(), scaled(), setHeight(), setWidth(), Size(), Size(), Size(), to(), withHeight(), and withWidth().
Size() [2/4]
template<class ValueType> yup::Size< ValueType >::Size (ValueType newWidth, ValueType newHeight) constexpr noexcept
Constructs a size object with specified width and height.
Initializes the size object to the given width and height values.
Parameters
newWidth The initial width of the size.
newHeight The initial height of the size.
References Size().
Size() [3/4]
template<class ValueType> yup::Size< ValueType >::Size (const Size< ValueType > & other) constexpr default noexcept
Copy and move constructors and assignment operators.
References Size().
Size() [4/4]
template<class ValueType> yup::Size< ValueType >::Size (Size< ValueType > && other) constexpr default noexcept
References Size().
Member Function Documentation
operator=() [1/2]
template<class ValueType> Size & yup::Size< ValueType >::operator= (const Size< ValueType > & other) constexpr default noexcept
References Size().
operator=() [2/2]
template<class ValueType> Size & yup::Size< ValueType >::operator= (Size< ValueType > && other) constexpr default noexcept
References Size().
getWidth()
template<class ValueType> ValueType yup::Size< ValueType >::getWidth () const constexpr noexcept
Gets the width of the size.
Returns the current width of the size object.
Returns
The current width.
Referenced by yup::Path::addCenteredArc(), and yup::Path::addCenteredEllipse().
setWidth()
template<class ValueType> Size & yup::Size< ValueType >::setWidth (ValueType newWidth) constexpr noexcept
Sets the width of the size.
Updates the width of the size object to the specified value and returns a reference to the size object.
Parameters
newWidth The new width to set.
Returns
Reference to this size object.
References Size().
withWidth()
template<class ValueType> Size yup::Size< ValueType >::withWidth (ValueType newWidth) const constexpr noexcept
Returns a new size object with the specified width.
Creates a new size object with the given width while keeping the height of this size object unchanged.
Parameters
newWidth The new width for the created size object.
Returns
A new size object with the specified width and current height.
References Size().
getHeight()
template<class ValueType> ValueType yup::Size< ValueType >::getHeight () const constexpr noexcept
Gets the height of the size.
Returns the current height of the size object.
Returns
The current height.
Referenced by yup::Path::addCenteredArc(), and yup::Path::addCenteredEllipse().
setHeight()
template<class ValueType> Size & yup::Size< ValueType >::setHeight (ValueType newHeight) constexpr noexcept
Sets the height of the size.
Updates the height of the size object to the specified value and returns a reference to the size object.
Parameters
newHeight The new height to set.
Returns
Reference to this size object.
References Size().
withHeight()
template<class ValueType> Size yup::Size< ValueType >::withHeight (ValueType newHeight) const constexpr noexcept
Returns a new size object with the specified height.
Creates a new size object with the given height while keeping the width of this size object unchanged.
Parameters
newHeight The new height for the created size object.
Returns
A new size object with the current width and specified height.
References Size().
isZero()
template<class ValueType> bool yup::Size< ValueType >::isZero () const constexpr noexcept
Checks if both dimensions are zero.
Determines if both the width and height of the size are zero, indicating a zero size.
Returns
True if both width and height are zero, false otherwise.
isEmpty()
template<class ValueType> bool yup::Size< ValueType >::isEmpty () const constexpr noexcept
Checks if either dimension is zero.
Determines if either the width or height of the size is zero, indicating an empty dimension.
Returns
True if either width or height is zero, false otherwise.
isVerticallyEmpty()
template<class ValueType> bool yup::Size< ValueType >::isVerticallyEmpty () const constexpr noexcept
Checks if the height is zero but not the width.
Determines if the height is zero while the width is not, indicating an empty vertical dimension.
Returns
True if height is zero and width is not, false otherwise.
isHorizontallyEmpty()
template<class ValueType> bool yup::Size< ValueType >::isHorizontallyEmpty () const constexpr noexcept
Checks if the width is zero but not the height.
Determines if the width is zero while the height is not, indicating an empty horizontal dimension.
Returns
True if width is zero and height is not, false otherwise.
isSquare()
template<class ValueType> bool yup::Size< ValueType >::isSquare () const constexpr noexcept
Checks if the width and height are equal.
Determines if the size is a square by checking if the width equals the height.
Returns
True if the size is a square, false otherwise.
area()
template<class ValueType> ValueType yup::Size< ValueType >::area () const constexpr noexcept
Calculate area of the Size.
Calculates and returns the area of the Size object.
Returns
The area calculated as width multiplied by height.
reverse()
template<class ValueType> Size & yup::Size< ValueType >::reverse () constexpr noexcept
Reverse dimensions.
Swaps the width and height of the Size object.
Returns
A reference to this Size object with its dimensions reversed.
References Size().
Referenced by reversed().
reversed()
template<class ValueType> Size yup::Size< ValueType >::reversed () const constexpr noexcept
Create a reversed Size object.
Creates a new Size object with reversed dimensions compared to this Size object.
Returns
A new Size object with reversed dimensions.
References reverse(), and Size().
enlarge() [1/2]
template<class ValueType> Size & yup::Size< ValueType >::enlarge (ValueType amount) constexpr noexcept
Enlarge dimensions uniformly.
Increases both the width and height of the Size object by a uniform amount and returns a reference to this Size object.
Parameters
amount The amount to add to both width and height.
Returns
A reference to this updated Size object.
References Size().
Referenced by enlarged(), and enlarged().
enlarge() [2/2]
template<class ValueType> Size & yup::Size< ValueType >::enlarge (ValueType widthAmount, ValueType heightAmount) constexpr noexcept
Enlarge dimensions separately.
Increases the width and height of the Size object by separate amounts and returns a reference to this Size object.
Parameters
widthAmount The amount to add to the width.
heightAmount The amount to add to the height.
Returns
A reference to this updated Size object.
References Size().
enlarged() [1/2]
template<class ValueType> Size yup::Size< ValueType >::enlarged (ValueType amount) const constexpr noexcept
Create an enlarged Size object uniformly.
Creates a new Size object with both dimensions increased by a uniform amount based on this Size object.
Parameters
amount The amount to add to both width and height.
Returns
A new Size object with enlarged dimensions.
References enlarge(), and Size().
enlarged() [2/2]
template<class ValueType> Size yup::Size< ValueType >::enlarged (ValueType widthAmount, ValueType heightAmount) const constexpr noexcept
Create an enlarged Size object separately.
Creates a new Size object with dimensions increased by separate amounts based on this Size object.
Parameters
widthAmount The amount to add to the width.
heightAmount The amount to add to the height.
Returns
A new Size object with enlarged dimensions.
References enlarge(), and Size().
reduce() [1/2]
template<class ValueType> Size & yup::Size< ValueType >::reduce (ValueType amount) constexpr noexcept
Reduce dimensions uniformly.
Decreases both the width and height of the Size object by a uniform amount and returns a reference to this Size object.
Parameters
amount The amount to subtract from both width and height.
Returns
A reference to this updated Size object.
References Size().
Referenced by reduced(), and reduced().
reduce() [2/2]
template<class ValueType> Size & yup::Size< ValueType >::reduce (ValueType widthAmount, ValueType heightAmount) constexpr noexcept
Reduce dimensions separately.
Decreases the width and height of the Size object by separate amounts and returns a reference to this Size object.
Parameters
widthAmount The amount to subtract from the width.
heightAmount The amount to subtract from the height.
Returns
A reference to this updated Size object.
References Size().
reduced() [1/2]
template<class ValueType> Size yup::Size< ValueType >::reduced (ValueType amount) const constexpr noexcept
Create a reduced Size object uniformly.
Creates a new Size object with both dimensions decreased by a uniform amount based on this Size object.
Parameters
amount The amount to subtract from both width and height.
Returns
A new Size object with reduced dimensions.
References reduce(), and Size().
reduced() [2/2]
template<class ValueType> Size yup::Size< ValueType >::reduced (ValueType widthAmount, ValueType heightAmount) const constexpr noexcept
Create a reduced Size object separately.
Creates a new Size object with dimensions decreased by separate amounts based on this Size object.
Parameters
widthAmount The amount to subtract from the width.
heightAmount The amount to subtract from the height.
Returns
A new Size object with reduced dimensions.
References reduce(), and Size().
scale() [1/2]
template<class ValueType> template<class T> auto yup::Size< ValueType >::scale (T scaleFactor) -> std::enable_if_t<std::is_floating_point_v<T>, Size&> constexpr noexcept
Scale Size dimensions.
Scales the dimensions of the Size object by a uniform factor and returns a reference to this Size object.
Parameters
scaleFactor The uniform scale factor to apply to both width and height.
Returns
A reference to this updated Size object.
References scale(), and Size().
Referenced by scale(), scaled(), and scaled().
scale() [2/2]
template<class ValueType> template<class T> auto yup::Size< ValueType >::scale (T scaleFactorX, T scaleFactorY) -> std::enable_if_t<std::is_floating_point_v<T>, Size&> constexpr noexcept
Scale Size dimensions separately.
Scales the dimensions of the Size object by separate factors for width and height and returns a reference to this Size object.
Parameters
scaleFactorX The scale factor to apply to the width.
scaleFactorY The scale factor to apply to the height.
Returns
A reference to this updated Size object.
References Size().
scaled() [1/2]
template<class ValueType> template<class T> auto yup::Size< ValueType >::scaled (T scaleFactor) const -> std::enable_if_t<std::is_floating_point_v<T>, Size> constexpr noexcept
Create a scaled Size object.
Creates a new Size object with dimensions scaled by a uniform factor based on this Size object.
Parameters
scaleFactor The uniform scale factor to apply to both width and height.
Returns
A new Size object with scaled dimensions.
References scale(), and Size().
scaled() [2/2]
template<class ValueType> template<class T> auto yup::Size< ValueType >::scaled (T scaleFactorX, T scaleFactorY) const -> std::enable_if_t<std::is_floating_point_v<T>, Size> constexpr noexcept
Create a scaled Size object separately.
Creates a new Size object with dimensions scaled by separate factors for width and height based on this Size object.
Parameters
scaleFactorX The scale factor to apply to the width.
scaleFactorY The scale factor to apply to the height.
Returns
A new Size object with scaled dimensions.
References scale(), and Size().
to()
template<class ValueType> template<class T> Size< T > yup::Size< ValueType >::to () const constexpr noexcept
Convert Size to another type.
Converts the dimensions of this Size object to another numeric type and returns a new Size object of that type.
Template Parameters
T The type to convert the dimensions to.
Returns
A new Size object with dimensions converted to type T.
References Size().
Referenced by yup::DocumentWindow::centreWithSize(), yup::Component::getSize(), and yup::Component::setSize().
roundToInt()
template<class ValueType> template<class T = ValueType> auto yup::Size< ValueType >::roundToInt () const -> std::enable_if_t<std::is_floating_point_v<T>, Size<int>> constexpr noexcept
References yup::roundToInt(), and Size().
operator*()
template<class ValueType> template<class T> auto yup::Size< ValueType >::operator* (T scaleFactor) const -> std::enable_if_t<std::is_floating_point_v<T>, Size> constexpr noexcept
Multiplication operator.
Multiplies the dimensions of this Size object by a scale factor and returns a new Size object with the scaled dimensions.
Template Parameters
T The type of the scale factor.
Parameters
scaleFactor The scale factor to multiply the dimensions by.
Returns
A new Size object with dimensions scaled by the given factor.
References Size().
operator*=()
template<class ValueType> template<class T> auto yup::Size< ValueType >::operator*= (T scaleFactor) -> std::enable_if_t<std::is_floating_point_v<T>, Size&> constexpr noexcept
Multiplication assignment operator.
Multiplies the dimensions of this Size object by a scale factor and updates this Size object.
Template Parameters
T The type of the scale factor.
Parameters
scaleFactor The scale factor to multiply the dimensions by.
Returns
A reference to this updated Size object.
References Size().
operator/()
template<class ValueType> template<class T> auto yup::Size< ValueType >::operator/ (T scaleFactor) const -> std::enable_if_t<std::is_floating_point_v<T>, Size> constexpr noexcept
Division operator.
Divides the dimensions of this Size object by a scale factor and returns a new Size object with the scaled dimensions.
Template Parameters
T The type of the scale factor.
Parameters
scaleFactor The scale factor to divide the dimensions by.
Returns
A new Size object with dimensions scaled down by the given factor.
References Size().
operator/=()
template<class ValueType> template<class T> auto yup::Size< ValueType >::operator/= (T scaleFactor) -> std::enable_if_t<std::is_floating_point_v<T>, Size&> constexpr noexcept
Division assignment operator.
Divides the dimensions of this Size object by a scale factor and updates this Size object.
Template Parameters
T The type of the scale factor.
Parameters
scaleFactor The scale factor to divide the dimensions by.
Returns
A reference to this updated Size object.
References Size().
approximatelyEqualTo()
template<class ValueType> bool yup::Size< ValueType >::approximatelyEqualTo (const Size< ValueType > & other) const constexpr noexcept
Returns true if the two sizes are approximately equal.
References yup::approximatelyEqual(), and Size().
operator==()
template<class ValueType> bool yup::Size< ValueType >::operator== (const Size< ValueType > & other) const constexpr noexcept
Equality operator.
Compares this Size object with another Size object for equality.
Parameters
other A reference to the other Size object to compare with.
Returns
True if both the width and height are equal, false otherwise.
References Size().
operator!=()
template<class ValueType> bool yup::Size< ValueType >::operator!= (const Size< ValueType > & other) const constexpr noexcept
Inequality operator.
Compares this Size object with another Size object for inequality.
Parameters
other A reference to the other Size object to compare with.
Returns
True if either the width or height are not equal, false otherwise.
References Size().