YUP: yup::AudioSourcePlayer Class Reference
yup::AudioSourcePlayer Class Reference
Wrapper class to continuously stream audio from an audio source to an AudioIODevice.
Public Member Functions
AudioSourcePlayer ()
Creates an empty AudioSourcePlayer.
~AudioSourcePlayer () override
Destructor.
void setSource (AudioSource *newSource)
Changes the current audio source to play from.
AudioSource * getCurrentSource () const noexcept
Returns the source that's playing.
void setGain (float newGain) noexcept
Sets a gain to apply to the audio data.
float getGain () const noexcept
Returns the current gain.
void audioDeviceIOCallbackWithContext (const float *const *inputChannelData, int totalNumInputChannels, float *const *outputChannelData, int totalNumOutputChannels, int numSamples, const AudioIODeviceCallbackContext &context) override
Implementation of the AudioIODeviceCallbackWithContext method.
void audioDeviceAboutToStart (AudioIODevice *device) override
Implementation of the AudioIODeviceCallback method.
void audioDeviceStopped () override
Implementation of the AudioIODeviceCallback method.
void prepareToPlay (double sampleRate, int blockSize)
An alternative method for initialising the source without an AudioIODevice.
Public Member Functions inherited from yup::AudioIODeviceCallback
virtual ~AudioIODeviceCallback ()=default
Destructor.
virtual void audioDeviceError (const String &errorMessage)
This can be overridden to be told if the device generates an error while operating.
Detailed Description
Wrapper class to continuously stream audio from an audio source to an AudioIODevice.
This object acts as an AudioIODeviceCallback, so can be attached to an output device, and will stream audio from an AudioSource.
Constructor & Destructor Documentation
AudioSourcePlayer()
yup::AudioSourcePlayer::AudioSourcePlayer ()
Creates an empty AudioSourcePlayer.
~AudioSourcePlayer()
yup::AudioSourcePlayer::~AudioSourcePlayer () override
Destructor.
Make sure this object isn't still being used by an AudioIODevice before deleting it!
References setSource().
Member Function Documentation
setSource()
void yup::AudioSourcePlayer::setSource (AudioSource * newSource)
Changes the current audio source to play from.
If the source passed in is already being used, this method will do nothing. If the source is not null, its prepareToPlay() method will be called before it starts being used for playback.
If there's another source currently playing, its releaseResources() method will be called after it has been swapped for the new one.
Parameters
newSource the new source to use - this will NOT be deleted by this object when no longer needed, so it's the caller's responsibility to manage it.
References yup::AudioSource::prepareToPlay().
Referenced by ~AudioSourcePlayer().
getCurrentSource()
AudioSource * yup::AudioSourcePlayer::getCurrentSource () const noexcept
Returns the source that's playing.
May return nullptr if there's no source.
setGain()
void yup::AudioSourcePlayer::setGain (float newGain) noexcept
Sets a gain to apply to the audio data.
See also
getGain
getGain()
float yup::AudioSourcePlayer::getGain () const noexcept
Returns the current gain.
See also
setGain
audioDeviceIOCallbackWithContext()
void yup::AudioSourcePlayer::audioDeviceIOCallbackWithContext (const float *const * inputChannelData, int totalNumInputChannels, float *const * outputChannelData, int totalNumOutputChannels, int numSamples, const AudioIODeviceCallbackContext & context) override virtual
Implementation of the AudioIODeviceCallbackWithContext method.
Reimplemented from yup::AudioIODeviceCallback.
References yup::AudioBuffer< Type >::applyGainRamp(), yup::AudioSourceChannelInfo::buffer, yup::AudioBuffer< Type >::getNumChannels(), yup::numElementsInArray(), yup::AudioSourceChannelInfo::numSamples, yup::AudioSourceChannelInfo::startSample, and yup::zeromem().
audioDeviceAboutToStart()
void yup::AudioSourcePlayer::audioDeviceAboutToStart (AudioIODevice * device) override virtual
Implementation of the AudioIODeviceCallback method.
Implements yup::AudioIODeviceCallback.
References yup::AudioIODevice::getCurrentBufferSizeSamples(), yup::AudioIODevice::getCurrentSampleRate(), and prepareToPlay().
audioDeviceStopped()
void yup::AudioSourcePlayer::audioDeviceStopped () override virtual
Implementation of the AudioIODeviceCallback method.
Implements yup::AudioIODeviceCallback.
prepareToPlay()
void yup::AudioSourcePlayer::prepareToPlay (double sampleRate, int blockSize)
An alternative method for initialising the source without an AudioIODevice.
References yup::zeromem().
Referenced by audioDeviceAboutToStart().