YUP: yup::JSON::FormatOptions Class Reference
yup::JSON::FormatOptions Class Reference
Allows formatting var objects as JSON with various configurable options.
Public Member Functions
FormatOptions withSpacing (Spacing x) const
Returns a copy of this Formatter with the specified spacing.
FormatOptions withMaxDecimalPlaces (int x) const
Returns a copy of this Formatter with the specified maximum number of decimal places.
FormatOptions withIndentLevel (int x) const
Returns a copy of this Formatter with the specified indent level.
Spacing getSpacing () const
Returns the spacing used by this Formatter.
int getMaxDecimalPlaces () const
Returns the maximum number of decimal places used by this Formatter.
int getIndentLevel () const
Returns the indent level of this Formatter.
Detailed Description
Allows formatting var objects as JSON with various configurable options.
Member Function Documentation
withSpacing()
FormatOptions yup::JSON::FormatOptions::withSpacing (Spacing x) const
Returns a copy of this Formatter with the specified spacing.
References yup::withMember().
Referenced by yup::JSON::toString(), and yup::JSON::writeToStream().
withMaxDecimalPlaces()
FormatOptions yup::JSON::FormatOptions::withMaxDecimalPlaces (int x) const
Returns a copy of this Formatter with the specified maximum number of decimal places.
This option determines the precision of floating point numbers in scientific notation.
References yup::withMember().
withIndentLevel()
FormatOptions yup::JSON::FormatOptions::withIndentLevel (int x) const
Returns a copy of this Formatter with the specified indent level.
This should only be necessary when serialising multiline nested types.
References yup::withMember().
Referenced by yup::DynamicObject::writeAsJSON().
getSpacing()
Spacing yup::JSON::FormatOptions::getSpacing () const
Returns the spacing used by this Formatter.
Referenced by yup::DynamicObject::writeAsJSON().
getMaxDecimalPlaces()
int yup::JSON::FormatOptions::getMaxDecimalPlaces () const
Returns the maximum number of decimal places used by this Formatter.
Referenced by yup::JSON::writeToStream().
getIndentLevel()
int yup::JSON::FormatOptions::getIndentLevel () const
Returns the indent level of this Formatter.
Referenced by yup::DynamicObject::writeAsJSON().