YUP: yup::Tolerance< Type > Class Template Reference
yup::Tolerance< Type > Class Template Reference
A class encapsulating both relative and absolute tolerances for use in floating-point comparisons.
Public Member Functions
constexpr Tolerance ()=default
constexpr Tolerance withAbsolute (Type newAbsolute)
Returns a copy of this Tolerance object with a new absolute tolerance.
constexpr Tolerance withRelative (Type newRelative)
Returns a copy of this Tolerance object with a new relative tolerance.
constexpr Type getAbsolute () const
constexpr Type getRelative () const
Detailed Description
template<typename Type>
class yup::Tolerance< Type >
A class encapsulating both relative and absolute tolerances for use in floating-point comparisons.
See also
approximatelyEqual, absoluteTolerance, relativeTolerance
Constructor & Destructor Documentation
Tolerance()
template<typename Type> yup::Tolerance< Type >::Tolerance () constexpr default
Referenced by withAbsolute(), and withRelative().
Member Function Documentation
withAbsolute()
template<typename Type> Tolerance yup::Tolerance< Type >::withAbsolute (Type newAbsolute) nodiscard constexpr
Returns a copy of this Tolerance object with a new absolute tolerance.
If you just need a Tolerance object with an absolute tolerance, it might be worth using the absoluteTolerance() function.
See also
getAbsolute, absoluteTolerance
References Tolerance(), yup::withMember(), and yup::yup_abs().
Referenced by yup::absoluteTolerance().
withRelative()
template<typename Type> Tolerance yup::Tolerance< Type >::withRelative (Type newRelative) nodiscard constexpr
Returns a copy of this Tolerance object with a new relative tolerance.
If you just need a Tolerance object with a relative tolerance, it might be worth using the relativeTolerance() function.
See also
getRelative, relativeTolerance
References Tolerance(), yup::withMember(), and yup::yup_abs().
Referenced by yup::relativeTolerance().
getAbsolute()
template<typename Type> Type yup::Tolerance< Type >::getAbsolute () const nodiscard constexpr
getRelative()
template<typename Type> Type yup::Tolerance< Type >::getRelative () const nodiscard constexpr