YUP: yup::MixerAudioSource Class Reference
yup::MixerAudioSource Class Reference
An AudioSource that mixes together the output of a set of other AudioSources.
Public Member Functions
MixerAudioSource ()
Creates a MixerAudioSource.
~MixerAudioSource () override
Destructor.
void addInputSource (AudioSource *newInput, bool deleteWhenRemoved)
Adds an input source to the mixer.
void removeInputSource (AudioSource *input)
Removes an input source.
void removeAllInputs ()
Removes all the input sources.
void prepareToPlay (int samplesPerBlockExpected, double sampleRate) override
Implementation of the AudioSource method.
void releaseResources () override
Implementation of the AudioSource method.
void getNextAudioBlock (const AudioSourceChannelInfo &) override
Implementation of the AudioSource method.
Public Member Functions inherited from yup::AudioSource
virtual ~AudioSource ()=default
Destructor.
Additional Inherited Members
Protected Member Functions inherited from yup::AudioSource
AudioSource ()=default
Creates an AudioSource.
Detailed Description
An AudioSource that mixes together the output of a set of other AudioSources.
Input sources can be added and removed while the mixer is running as long as their prepareToPlay() and releaseResources() methods are called before and after adding them to the mixer.
Constructor & Destructor Documentation
MixerAudioSource()
yup::MixerAudioSource::MixerAudioSource ()
Creates a MixerAudioSource.
~MixerAudioSource()
yup::MixerAudioSource::~MixerAudioSource () override
Destructor.
References removeAllInputs().
Member Function Documentation
addInputSource()
void yup::MixerAudioSource::addInputSource (AudioSource * newInput, bool deleteWhenRemoved)
Adds an input source to the mixer.
If the mixer is running you'll need to make sure that the input source is ready to play by calling its prepareToPlay() method before adding it. If the mixer is stopped, then its input sources will be automatically prepared when the mixer's prepareToPlay() method is called.
Parameters
newInput the source to add to the mixer
deleteWhenRemoved if true, then this source will be deleted when no longer needed by the mixer.
References yup::AudioSource::AudioSource(), and yup::AudioSource::prepareToPlay().
removeInputSource()
void yup::MixerAudioSource::removeInputSource (AudioSource * input)
Removes an input source.
If the source was added by calling addInputSource() with the deleteWhenRemoved flag set, it will be deleted by this method.
References yup::AudioSource::AudioSource(), and yup::AudioSource::releaseResources().
removeAllInputs()
void yup::MixerAudioSource::removeAllInputs ()
Removes all the input sources.
Any sources which were added by calling addInputSource() with the deleteWhenRemoved flag set will be deleted by this method.
References yup::OwnedArray< ObjectClass, TypeOfCriticalSectionToUse >::add(), yup::OwnedArray< ObjectClass, TypeOfCriticalSectionToUse >::getUnchecked(), and yup::OwnedArray< ObjectClass, TypeOfCriticalSectionToUse >::size().
Referenced by ~MixerAudioSource().
prepareToPlay()
void yup::MixerAudioSource::prepareToPlay (int samplesPerBlockExpected, double sampleRate) override virtual
Implementation of the AudioSource method.
This will call prepareToPlay() on all its input sources.
Implements yup::AudioSource.
releaseResources()
void yup::MixerAudioSource::releaseResources () override virtual
Implementation of the AudioSource method.
This will call releaseResources() on all its input sources.
Implements yup::AudioSource.
getNextAudioBlock()
void yup::MixerAudioSource::getNextAudioBlock (const AudioSourceChannelInfo & info) override virtual
Implementation of the AudioSource method.
Implements yup::AudioSource.
References yup::AudioBuffer< Type >::addFrom(), yup::AudioSourceChannelInfo::buffer, yup::AudioSourceChannelInfo::clearActiveBufferRegion(), yup::AudioBuffer< Type >::getNumChannels(), yup::AudioBuffer< Type >::getNumSamples(), yup::jmax(), yup::AudioSourceChannelInfo::numSamples, and yup::AudioSourceChannelInfo::startSample.