YUP: yup::ToneGeneratorAudioSource Class Reference
yup::ToneGeneratorAudioSource Class Reference
A simple AudioSource that generates a sine wave.
Public Member Functions
ToneGeneratorAudioSource ()
Creates a ToneGeneratorAudioSource.
~ToneGeneratorAudioSource () override
Destructor.
void setAmplitude (float newAmplitude)
Sets the signal's amplitude.
void setFrequency (double newFrequencyHz)
Sets the signal's frequency.
void prepareToPlay (int samplesPerBlockExpected, double sampleRate) override
Implementation of the AudioSource method.
void releaseResources () override
Implementation of the AudioSource method.
void getNextAudioBlock (const AudioSourceChannelInfo &) override
Implementation of the AudioSource method.
Public Member Functions inherited from yup::AudioSource
virtual ~AudioSource ()=default
Destructor.
Additional Inherited Members
Protected Member Functions inherited from yup::AudioSource
AudioSource ()=default
Creates an AudioSource.
Detailed Description
A simple AudioSource that generates a sine wave.
Constructor & Destructor Documentation
ToneGeneratorAudioSource()
yup::ToneGeneratorAudioSource::ToneGeneratorAudioSource ()
Creates a ToneGeneratorAudioSource.
~ToneGeneratorAudioSource()
yup::ToneGeneratorAudioSource::~ToneGeneratorAudioSource () override
Destructor.
Member Function Documentation
setAmplitude()
void yup::ToneGeneratorAudioSource::setAmplitude (float newAmplitude)
Sets the signal's amplitude.
setFrequency()
void yup::ToneGeneratorAudioSource::setFrequency (double newFrequencyHz)
Sets the signal's frequency.
prepareToPlay()
void yup::ToneGeneratorAudioSource::prepareToPlay (int samplesPerBlockExpected, double sampleRate) override virtual
Implementation of the AudioSource method.
Implements yup::AudioSource.
releaseResources()
void yup::ToneGeneratorAudioSource::releaseResources () override virtual
Implementation of the AudioSource method.
Implements yup::AudioSource.
getNextAudioBlock()
void yup::ToneGeneratorAudioSource::getNextAudioBlock (const AudioSourceChannelInfo & info) override virtual
Implementation of the AudioSource method.
Implements yup::AudioSource.
References yup::approximatelyEqual(), yup::AudioSourceChannelInfo::buffer, yup::AudioBuffer< Type >::getNumChannels(), yup::AudioSourceChannelInfo::numSamples, yup::AudioBuffer< Type >::setSample(), yup::AudioSourceChannelInfo::startSample, and yup::MathConstants< FloatType >::twoPi.