YUP: yup::Watchdog Class Reference
yup::Watchdog Class Reference
Watches a folder in the file system for changes.
Inherits std::enable_shared_from_this< Watchdog >.
Classes
struct Event
This struct represents a filesystem event.
Public Types
enum class EventType {
undefined , file_created , file_deleted , file_updated ,
file_renamed
}
This enum represents the different filesystem event types.
using EventsCallback = std::function<void (std::vector<Event>)>
Dispatches the events to the callback.
Public Member Functions
~Watchdog ()
Destroys the watchdog object.
void watchFolder (const File &folder)
Watches a folder for changes.
void unwatchFolder (const File &folder)
Unwatches a folder for changes.
void unwatchAllFolders ()
Unwatches all folders.
std::size_t dispatchEvents (const EventsCallback &callback)
std::vector< File > getAllWatchedFolders () const
Returns all watched folders.
Static Public Member Functions
static std::shared_ptr< Watchdog > createInstance (std::chrono::milliseconds timeout)
Constructs a new watchdog object.
Detailed Description
Watches a folder in the file system for changes.
This is only available on macOS, windows, and Linux.
The class watchdog will also recursively watch all subfolders on macOS, windows, and Linux.
Member Typedef Documentation
EventsCallback
using yup::Watchdog::EventsCallback = std::function<void (std::vector<Event>)>
Dispatches the events to the callback.
Member Enumeration Documentation
EventType
enum class yup::Watchdog::EventType strong
This enum represents the different filesystem event types.
Enumerator
undefined
file_created
file_deleted
file_updated
file_renamed
Constructor & Destructor Documentation
~Watchdog()
yup::Watchdog::~Watchdog ()
Destroys the watchdog object.
References unwatchAllFolders().
Member Function Documentation
createInstance()
std::shared_ptr< Watchdog > yup::Watchdog::createInstance (std::chrono::milliseconds timeout) static
Constructs a new watchdog object.
Parameters
timeout The timeout for the watchdog.
watchFolder()
void yup::Watchdog::watchFolder (const File & folder)
Watches a folder for changes.
References yup::File::getFullPathName(), and yup::File::isDirectory().
unwatchFolder()
void yup::Watchdog::unwatchFolder (const File & folder)
Unwatches a folder for changes.
References yup::File::getFullPathName().
unwatchAllFolders()
void yup::Watchdog::unwatchAllFolders ()
Unwatches all folders.
Referenced by ~Watchdog().
dispatchEvents()
std::size_t yup::Watchdog::dispatchEvents (const EventsCallback & callback)
getAllWatchedFolders()
std::vector< File > yup::Watchdog::getAllWatchedFolders () const
Returns all watched folders.