YUP: yup::AudioParameter Class Reference
yup::AudioParameter Class Reference
A flexible, thread-safe parameter class with support for custom mapping, string conversion, smoothing, and different parameter types (linear, log, dB, enum, etc).
Classes
class Listener
A listener for parameter changes.
Public Types
using Ptr = ReferenceCountedObjectPtr<AudioParameter>
A pointer to an AudioParameter.
using ValueToString = std::function<String (float)>
A function that converts a real value to a string.
using StringToValue = std::function<float (const String&)>
A function that converts a string to a real value.
Public Member Functions
AudioParameter (const String &id, const String &name, float minValue, float maxValue, float defaultValue, ValueToString valueToString=nullptr, StringToValue stringToValue=nullptr, bool smoothingEnabled=false, float smoothingTimeMs=0.0f)
Constructs an AudioParameter instance.
AudioParameter (const String &id, const String &name, NormalisableRange< float > valueRange, float defaultValue, ValueToString valueToString=nullptr, StringToValue stringToValue=nullptr, bool smoothingEnabled=false, float smoothingTimeMs=0.0f)
Constructs an AudioParameter instance.
~AudioParameter ()
Destructor.
const String & getID () const
Returns the parameter ID.
const String & getName () const
Returns the parameter name.
int getIndexInContainer () const
void setIndexInContainer (int newIndex)
float getMinimumValue () const
Returns the minimum value.
float getMaximumValue () const
Returns the maximum value.
float getDefaultValue () const
Returns the default value.
void beginChangeGesture ()
void endChangeGesture ()
bool isPerformingChangeGesture () const
void setValueNotifyingHost (float value)
Sets the real (un-normalized) parameter value and notifies the host.
void setValue (float newValue)
Sets the real (un-normalized) parameter value.
float getValue () const
Gets the real (un-normalized) parameter value.
void setNormalizedValue (float normalizedValue)
Sets the normalized [0..1] value.
float getNormalizedValue () const
Gets the normalized [0..1] value.
float convertToNormalizedValue (float denormalizedValue) const
float convertToDenormalizedValue (float normalizedValue) const
String toString () const
Converts a real value to its display string.
void fromString (const String &string)
Parses a string into a real parameter value.
String convertToString (float value) const
float convertFromString (const String &string) const
bool isSmoothingEnabled () const
Returns true if smoothing is enabled.
float getSmoothingTimeMs () const
Returns the smoothing time in milliseconds.
void addListener (Listener *listener)
Adds a listener to the parameter.
void removeListener (Listener *listener)
Removes a listener from the parameter.
Public Member Functions inherited from yup::ReferenceCountedObject
void incReferenceCount () const noexcept
Increments the object's reference count.
void decReferenceCount () const noexcept
Decreases the object's reference count.
bool decReferenceCountWithoutDeleting () const noexcept
Decreases the object's reference count.
int getReferenceCount () const noexcept
Returns the object's current reference count.
Additional Inherited Members
Protected Member Functions inherited from yup::ReferenceCountedObject
ReferenceCountedObject ()=default
Creates the reference-counted object (with an initial ref count of zero).
ReferenceCountedObject (const ReferenceCountedObject &) noexcept
Copying from another object does not affect this one's reference-count.
ReferenceCountedObject (ReferenceCountedObject &&) noexcept
Copying from another object does not affect this one's reference-count.
ReferenceCountedObject & operator= (const ReferenceCountedObject &) noexcept
Copying from another object does not affect this one's reference-count.
ReferenceCountedObject & operator= (ReferenceCountedObject &&) noexcept
Copying from another object does not affect this one's reference-count.
virtual ~ReferenceCountedObject ()
Destructor.
void resetReferenceCount () const noexcept
Resets the reference count to zero without deleting the object.
Detailed Description
A flexible, thread-safe parameter class with support for custom mapping, string conversion, smoothing, and different parameter types (linear, log, dB, enum, etc).
Use AudioParameterBuilder to construct instances of this class.
See also
AudioParameterBuilder
Member Typedef Documentation
Ptr
using yup::AudioParameter::Ptr = ReferenceCountedObjectPtr<AudioParameter>
A pointer to an AudioParameter.
ValueToString
using yup::AudioParameter::ValueToString = std::function<String (float)>
A function that converts a real value to a string.
StringToValue
using yup::AudioParameter::StringToValue = std::function<float (const String&)>
A function that converts a string to a real value.
Constructor & Destructor Documentation
AudioParameter() [1/2]
yup::AudioParameter::AudioParameter (const String & id, const String & name, float minValue, float maxValue, float defaultValue, ValueToString valueToString = nullptr, StringToValue stringToValue = nullptr, bool smoothingEnabled = false, float smoothingTimeMs = 0.0f)
Constructs an AudioParameter instance.
Parameters
id The parameter ID (used in the state tree).
name The display name.
minValue The minimum real value.
maxValue The maximum real value.
defaultValue The default real value.
valueToString Converts real value to display string (optional).
stringToValue Parses display string to real value (optional).
References setValue().
AudioParameter() [2/2]
yup::AudioParameter::AudioParameter (const String & id, const String & name, NormalisableRange< float > valueRange, float defaultValue, ValueToString valueToString = nullptr, StringToValue stringToValue = nullptr, bool smoothingEnabled = false, float smoothingTimeMs = 0.0f)
Constructs an AudioParameter instance.
Parameters
id The parameter ID (used in the state tree).
name The display name.
valueRange The value range.
defaultValue The default real value.
valueToString Converts real value to display string (optional).
stringToValue Parses display string to real value (optional).
References setValue().
~AudioParameter()
yup::AudioParameter::~AudioParameter ()
Destructor.
Member Function Documentation
getID()
const String & yup::AudioParameter::getID () const
Returns the parameter ID.
Referenced by yup::AudioProcessor::addParameter().
getName()
const String & yup::AudioParameter::getName () const
Returns the parameter name.
getIndexInContainer()
int yup::AudioParameter::getIndexInContainer () const
setIndexInContainer()
void yup::AudioParameter::setIndexInContainer (int newIndex)
Referenced by yup::AudioProcessor::addParameter().
getMinimumValue()
float yup::AudioParameter::getMinimumValue () const
Returns the minimum value.
getMaximumValue()
float yup::AudioParameter::getMaximumValue () const
Returns the maximum value.
getDefaultValue()
float yup::AudioParameter::getDefaultValue () const
Returns the default value.
beginChangeGesture()
void yup::AudioParameter::beginChangeGesture ()
References yup::AudioParameter::Listener::parameterGestureBegin().
endChangeGesture()
void yup::AudioParameter::endChangeGesture ()
References yup::AudioParameter::Listener::parameterGestureEnd().
isPerformingChangeGesture()
bool yup::AudioParameter::isPerformingChangeGesture () const
setValueNotifyingHost()
void yup::AudioParameter::setValueNotifyingHost (float value)
Sets the real (un-normalized) parameter value and notifies the host.
Parameters
value The new real value.
References yup::AudioParameter::Listener::parameterValueChanged(), and setValue().
setValue()
void yup::AudioParameter::setValue (float newValue)
Sets the real (un-normalized) parameter value.
Parameters
newValue The new real value.
Referenced by AudioParameter(), AudioParameter(), fromString(), setNormalizedValue(), and setValueNotifyingHost().
getValue()
float yup::AudioParameter::getValue () const
Gets the real (un-normalized) parameter value.
Referenced by getNormalizedValue(), and toString().
setNormalizedValue()
void yup::AudioParameter::setNormalizedValue (float normalizedValue)
Sets the normalized [0..1] value.
Parameters
normalizedValue The new normalized value.
References convertToDenormalizedValue(), and setValue().
getNormalizedValue()
float yup::AudioParameter::getNormalizedValue () const
Gets the normalized [0..1] value.
References convertToNormalizedValue(), and getValue().
convertToNormalizedValue()
float yup::AudioParameter::convertToNormalizedValue (float denormalizedValue) const
Referenced by getNormalizedValue().
convertToDenormalizedValue()
float yup::AudioParameter::convertToDenormalizedValue (float normalizedValue) const
Referenced by setNormalizedValue().
toString()
String yup::AudioParameter::toString () const
Converts a real value to its display string.
References getValue().
fromString()
void yup::AudioParameter::fromString (const String & string)
Parses a string into a real parameter value.
References setValue().
convertToString()
String yup::AudioParameter::convertToString (float value) const
convertFromString()
float yup::AudioParameter::convertFromString (const String & string) const
isSmoothingEnabled()
bool yup::AudioParameter::isSmoothingEnabled () const
Returns true if smoothing is enabled.
getSmoothingTimeMs()
float yup::AudioParameter::getSmoothingTimeMs () const
Returns the smoothing time in milliseconds.
addListener()
void yup::AudioParameter::addListener (Listener * listener)
Adds a listener to the parameter.
removeListener()
void yup::AudioParameter::removeListener (Listener * listener)
Removes a listener from the parameter.