YUP: yup::RectangleList< ValueType > Class Template Reference
yup::RectangleList< ValueType > Class Template Reference
A class that manages a list of rectangles.
Public Types
using RectangleType = Rectangle<ValueType>
Public Member Functions
RectangleList ()=default
Default constructor, initializes an empty list of rectangles.
RectangleList (std::initializer_list< RectangleType > rects)
Construct from initializer list of rectangles.
template<class OtherValueType, class = std::enable_if_t<! std::is_same_v<OtherValueType, ValueType>>>
RectangleList (std::initializer_list< Rectangle< OtherValueType > > rects)
Construct from initializer list of rectangles of different type.
constexpr RectangleList (const RectangleList &other) noexcept=default
Copy and move constructors and assignment operators.
constexpr RectangleList (RectangleList &&other) noexcept=default
constexpr RectangleList & operator= (const RectangleList &other) noexcept=default
constexpr RectangleList & operator= (RectangleList &&other) noexcept=default
RectangleList & add (const RectangleType &newRect)
Adds a rectangle to the list.
RectangleList & addWithoutMerge (const RectangleType &newRect)
Adds a rectangle to the list without merging it with any existing rectangles.
RectangleList & remove (const RectangleType &rect)
Removes a rectangle from the list.
bool isEmpty () const
Returns true if the list is empty.
void clear ()
Clears all rectangles from the list.
void clearQuick ()
Quickly clears all rectangles from the list.
bool contains (ValueType x, ValueType y, ValueType width, ValueType height) const
Checks if the list contains a specified rectangle.
bool contains (const RectangleType &rect) const
bool contains (ValueType x, ValueType y) const
Checks if the given point (x, y) is contained within any of the rectangles in the list.
bool contains (const Point< ValueType > &point) const
bool intersects (ValueType x, ValueType y, ValueType width, ValueType height) const
Checks if the list intersects a specified rectangle.
bool intersects (const RectangleType &rect) const
int getNumRectangles () const
Returns the number of rectangles in the list.
RectangleType getRectangle (int index) const
Returns one of the rectangles at a specified index.
Span< const RectangleType > getRectangles () const
Returns the list of rectangles.
RectangleType getBoundingBox () const
Returns the bounding box of the whole list of rectangles.
RectangleList & offset (ValueType deltaX, ValueType deltaY)
Offset all rectangles in the list by the specified x and y offsets.
RectangleList & offset (const Point< ValueType > &delta)
Offset all rectangles in the list by the specified point.
RectangleList & scale (float factor)
Scales all rectangles in the list by the specified factor.
RectangleList & scale (float factorX, float factorY)
Scales all rectangles in the list by the specified factor.
const Rectangle< ValueType > * begin () const
const Rectangle< ValueType > * end () const
Rectangle< ValueType > * begin ()
Rectangle< ValueType > * end ()
Detailed Description
template<class ValueType>
class yup::RectangleList< ValueType >
A class that manages a list of rectangles.
This class provides a collection of rectangles and supports operations such as adding rectangles (with optional merging), removing rectangles, checking for containment and intersection, scaling, and offsetting. It also provides methods to get the bounding box of all rectangles, the number of rectangles, and access to individual rectangles.
RectangleList<int> list;
list.add ({ 0, 0, 10, 10 });
list.add ({ 5, 5, 15, 15 });
bool contains = list.contains (7, 7);
Member Typedef Documentation
RectangleType
template<class ValueType> using yup::RectangleList< ValueType >::RectangleType = Rectangle<ValueType>
Constructor & Destructor Documentation
RectangleList() [1/5]
template<class ValueType> yup::RectangleList< ValueType >::RectangleList () default
Default constructor, initializes an empty list of rectangles.
Referenced by add(), addWithoutMerge(), offset(), offset(), operator=(), operator=(), RectangleList(), RectangleList(), remove(), scale(), and scale().
RectangleList() [2/5]
template<class ValueType> yup::RectangleList< ValueType >::RectangleList (std::initializer_list< RectangleType > rects)
Construct from initializer list of rectangles.
RectangleList() [3/5]
template<class ValueType> template<class OtherValueType, class = std::enable_if_t<! std::is_same_v<OtherValueType, ValueType>>> yup::RectangleList< ValueType >::RectangleList (std::initializer_list< Rectangle< OtherValueType > > rects)
Construct from initializer list of rectangles of different type.
RectangleList() [4/5]
template<class ValueType> yup::RectangleList< ValueType >::RectangleList (const RectangleList< ValueType > & other) constexpr default noexcept
Copy and move constructors and assignment operators.
References RectangleList().
RectangleList() [5/5]
template<class ValueType> yup::RectangleList< ValueType >::RectangleList (RectangleList< ValueType > && other) constexpr default noexcept
References RectangleList().
Member Function Documentation
operator=() [1/2]
template<class ValueType> RectangleList & yup::RectangleList< ValueType >::operator= (const RectangleList< ValueType > & other) constexpr default noexcept
References RectangleList().
operator=() [2/2]
template<class ValueType> RectangleList & yup::RectangleList< ValueType >::operator= (RectangleList< ValueType > && other) constexpr default noexcept
References RectangleList().
add()
template<class ValueType> RectangleList & yup::RectangleList< ValueType >::add (const RectangleType & newRect)
Adds a rectangle to the list.
Parameters
rect The rectangle to add.
Returns
A reference to the RectangleList object.
References addWithoutMerge(), and RectangleList().
addWithoutMerge()
template<class ValueType> RectangleList & yup::RectangleList< ValueType >::addWithoutMerge (const RectangleType & newRect)
Adds a rectangle to the list without merging it with any existing rectangles.
Parameters
rect The rectangle to add.
Returns
A reference to the RectangleList object.
References RectangleList().
Referenced by add().
remove()
template<class ValueType> RectangleList & yup::RectangleList< ValueType >::remove (const RectangleType & rect)
Removes a rectangle from the list.
Parameters
rect The rectangle to remove.
Returns
A reference to the RectangleList object.
References RectangleList().
isEmpty()
template<class ValueType> bool yup::RectangleList< ValueType >::isEmpty () const nodiscard
Returns true if the list is empty.
Returns
True if the list is empty, otherwise false.
clear()
template<class ValueType> void yup::RectangleList< ValueType >::clear ()
Clears all rectangles from the list.
clearQuick()
template<class ValueType> void yup::RectangleList< ValueType >::clearQuick ()
Quickly clears all rectangles from the list.
contains() [1/4]
template<class ValueType> bool yup::RectangleList< ValueType >::contains (ValueType x, ValueType y, ValueType width, ValueType height) const nodiscard
Checks if the list contains a specified rectangle.
Parameters
rect The rectangle to check for.
Returns
True if the rectangle is in the list, otherwise false.
Referenced by contains().
contains() [2/4]
template<class ValueType> bool yup::RectangleList< ValueType >::contains (const RectangleType & rect) const nodiscard
contains() [3/4]
template<class ValueType> bool yup::RectangleList< ValueType >::contains (ValueType x, ValueType y) const nodiscard
Checks if the given point (x, y) is contained within any of the rectangles in the list.
Parameters
x The x-coordinate of the point to check.
y The y-coordinate of the point to check.
Returns
true if the point is contained within any rectangle in the list, false otherwise.
contains() [4/4]
template<class ValueType> bool yup::RectangleList< ValueType >::contains (const Point< ValueType > & point) const nodiscard
References contains(), yup::Point< ValueType >::getX(), and yup::Point< ValueType >::getY().
intersects() [1/2]
template<class ValueType> bool yup::RectangleList< ValueType >::intersects (ValueType x, ValueType y, ValueType width, ValueType height) const nodiscard
Checks if the list intersects a specified rectangle.
Parameters
rect The rectangle to check for.
Returns
True if the rectangle intersects the list, otherwise false.
Referenced by intersects().
intersects() [2/2]
template<class ValueType> bool yup::RectangleList< ValueType >::intersects (const RectangleType & rect) const nodiscard
References yup::Rectangle< ValueType >::getHeight(), yup::Rectangle< ValueType >::getWidth(), yup::Rectangle< ValueType >::getX(), yup::Rectangle< ValueType >::getY(), and intersects().
getNumRectangles()
template<class ValueType> int yup::RectangleList< ValueType >::getNumRectangles () const nodiscard
Returns the number of rectangles in the list.
Returns
The number of rectangles.
getRectangle()
template<class ValueType> RectangleType yup::RectangleList< ValueType >::getRectangle (int index) const nodiscard
Returns one of the rectangles at a specified index.
Parameters
index The index of the rectangle to return.
Returns
A new instance of the requested rectangle.
References yup::isPositiveAndBelow().
getRectangles()
template<class ValueType> Span< const RectangleType > yup::RectangleList< ValueType >::getRectangles () const nodiscard
Returns the list of rectangles.
Returns
A const reference to the vector of rectangles.
getBoundingBox()
template<class ValueType> RectangleType yup::RectangleList< ValueType >::getBoundingBox () const nodiscard
Returns the bounding box of the whole list of rectangles.
Returns
A new instance of the requested rectangle.
offset() [1/2]
template<class ValueType> RectangleList & yup::RectangleList< ValueType >::offset (ValueType deltaX, ValueType deltaY)
Offset all rectangles in the list by the specified x and y offsets.
Parameters
deltaX The amount to add to the x-coordinates.
deltaY The amount to add to the y-coordinates.
References RectangleList().
offset() [2/2]
template<class ValueType> RectangleList & yup::RectangleList< ValueType >::offset (const Point< ValueType > & delta)
Offset all rectangles in the list by the specified point.
Parameters
delta The point containing the amounts to add to the x and y coordinates.
References RectangleList().
scale() [1/2]
template<class ValueType> RectangleList & yup::RectangleList< ValueType >::scale (float factor)
Scales all rectangles in the list by the specified factor.
Parameters
factor The scaling factor.
References RectangleList(), and scale().
Referenced by scale(), and scale().
scale() [2/2]
template<class ValueType> RectangleList & yup::RectangleList< ValueType >::scale (float factorX, float factorY)
Scales all rectangles in the list by the specified factor.
Parameters
factor The scaling factor.
References RectangleList(), and scale().
begin() [1/2]
template<class ValueType> const Rectangle< ValueType > * yup::RectangleList< ValueType >::begin () const
end() [1/2]
template<class ValueType> const Rectangle< ValueType > * yup::RectangleList< ValueType >::end () const
begin() [2/2]
template<class ValueType> Rectangle< ValueType > * yup::RectangleList< ValueType >::begin ()
end() [2/2]
template<class ValueType> Rectangle< ValueType > * yup::RectangleList< ValueType >::end ()