YUP: yup::BitmapData Class Reference
yup::BitmapData Class Reference
Represents bitmap pixel data with accessors.
Public Types
using Ptr = ReferenceCountedObjectPtr<BitmapData>
Public Member Functions
BitmapData ()=default
Default constructor.
BitmapData (int w, int h, PixelFormat fmt)
Constructs bitmap data with specified dimensions and pixel format.
BitmapData (int w, int h, PixelFormat fmt, std::unique_ptr< const uint8[]> pixelData)
BitmapData (const BitmapData &other)=delete
Copy constructor.
BitmapData (BitmapData &&other) noexcept
Move constructor.
BitmapData & operator= (const BitmapData &other)=delete
Copy assignment operator.
BitmapData & operator= (BitmapData &&other) noexcept
Move assignment operator.
~BitmapData ()=default
Destructor.
int getWidth () const noexcept
Returns the width of the bitmap in pixels.
int getHeight () const noexcept
Returns the height of the bitmap in pixels.
PixelFormat getPixelFormat () const noexcept
Returns the pixel format of the bitmap.
int getPixelStride () const noexcept
Returns the pixel stride.
void setPixel (int x, int y, uint32_t color)
Sets the pixel at (x, y) with the specified color.
uint32_t getPixel (int x, int y) const
Gets the pixel color at (x, y).
void fill (uint32_t color)
Fills the entire bitmap with the specified color.
void clear ()
Clears the bitmap by setting all pixels to zero.
Span< const uint8 > getRawData () const noexcept
Returns a pointer to the raw pixel data.
Span< uint8 > getRawData () noexcept
Returns a mutable pointer to the raw pixel data.
Public Member Functions inherited from yup::ReferenceCountedObject
void incReferenceCount () const noexcept
Increments the object's reference count.
void decReferenceCount () const noexcept
Decreases the object's reference count.
bool decReferenceCountWithoutDeleting () const noexcept
Decreases the object's reference count.
int getReferenceCount () const noexcept
Returns the object's current reference count.
Additional Inherited Members
Protected Member Functions inherited from yup::ReferenceCountedObject
ReferenceCountedObject ()=default
Creates the reference-counted object (with an initial ref count of zero).
ReferenceCountedObject (const ReferenceCountedObject &) noexcept
Copying from another object does not affect this one's reference-count.
ReferenceCountedObject (ReferenceCountedObject &&) noexcept
Copying from another object does not affect this one's reference-count.
ReferenceCountedObject & operator= (const ReferenceCountedObject &) noexcept
Copying from another object does not affect this one's reference-count.
ReferenceCountedObject & operator= (ReferenceCountedObject &&) noexcept
Copying from another object does not affect this one's reference-count.
virtual ~ReferenceCountedObject ()
Destructor.
void resetReferenceCount () const noexcept
Resets the reference count to zero without deleting the object.
Detailed Description
Represents bitmap pixel data with accessors.
Supports different pixel formats and provides methods to manipulate individual pixels.
Member Typedef Documentation
Ptr
using yup::BitmapData::Ptr = ReferenceCountedObjectPtr<BitmapData>
Constructor & Destructor Documentation
BitmapData() [1/5]
yup::BitmapData::BitmapData () default
Default constructor.
Creates empty bitmap data.
Referenced by BitmapData(), BitmapData(), operator=(), and operator=().
BitmapData() [2/5]
yup::BitmapData::BitmapData (int w, int h, PixelFormat fmt)
Constructs bitmap data with specified dimensions and pixel format.
Parameters
w The width of the bitmap in pixels.
h The height of the bitmap in pixels.
fmt The pixel format of the bitmap.
BitmapData() [3/5]
yup::BitmapData::BitmapData (int w, int h, PixelFormat fmt, std::unique_ptr< const uint8[]> pixelData)
BitmapData() [4/5]
yup::BitmapData::BitmapData (const BitmapData & other) delete
Copy constructor.
References BitmapData().
BitmapData() [5/5]
yup::BitmapData::BitmapData (BitmapData && other) noexcept
Move constructor.
References BitmapData().
~BitmapData()
yup::BitmapData::~BitmapData () default
Destructor.
Member Function Documentation
operator=() [1/2]
BitmapData & yup::BitmapData::operator= (const BitmapData & other) delete
Copy assignment operator.
References BitmapData().
operator=() [2/2]
BitmapData & yup::BitmapData::operator= (BitmapData && other) noexcept
Move assignment operator.
References BitmapData().
getWidth()
int yup::BitmapData::getWidth () const noexcept
Returns the width of the bitmap in pixels.
getHeight()
int yup::BitmapData::getHeight () const noexcept
Returns the height of the bitmap in pixels.
getPixelFormat()
PixelFormat yup::BitmapData::getPixelFormat () const noexcept
Returns the pixel format of the bitmap.
getPixelStride()
int yup::BitmapData::getPixelStride () const noexcept
Returns the pixel stride.
setPixel()
void yup::BitmapData::setPixel (int x, int y, uint32_t color)
Sets the pixel at (x, y) with the specified color.
Parameters
x The x-coordinate of the pixel.
y The y-coordinate of the pixel.
color The color value to set.
References yup::Grayscale, yup::RGB, and yup::RGBA.
getPixel()
uint32_t yup::BitmapData::getPixel (int x, int y) const
Gets the pixel color at (x, y).
Parameters
x The x-coordinate of the pixel.
y The y-coordinate of the pixel.
Returns
The color value of the pixel.
References yup::Grayscale, yup::RGB, and yup::RGBA.
fill()
void yup::BitmapData::fill (uint32_t color)
Fills the entire bitmap with the specified color.
Parameters
color The color value to fill the bitmap with.
References yup::Grayscale, yup::RGB, and yup::RGBA.
clear()
void yup::BitmapData::clear ()
Clears the bitmap by setting all pixels to zero.
getRawData() [1/2]
Span< const uint8 > yup::BitmapData::getRawData () const noexcept
Returns a pointer to the raw pixel data.
getRawData() [2/2]
Span< uint8 > yup::BitmapData::getRawData () noexcept
Returns a mutable pointer to the raw pixel data.