YUP: yup::DynamicObject Class Reference
yup::DynamicObject Class Reference
Represents a dynamically implemented object.
Public Types
using Ptr = ReferenceCountedObjectPtr<DynamicObject>
Public Member Functions
DynamicObject ()
DynamicObject (const DynamicObject &)
~DynamicObject () override
virtual bool hasProperty (const Identifier &propertyName) const
Returns true if the object has a property with this name.
virtual const var & getProperty (const Identifier &propertyName) const
Returns a named property.
virtual void setProperty (const Identifier &propertyName, const var &newValue)
Sets a named property.
virtual void removeProperty (const Identifier &propertyName)
Removes a named property.
virtual bool hasMethod (const Identifier &methodName) const
Checks whether this object has the specified method.
virtual var invokeMethod (Identifier methodName, const var::NativeFunctionArgs &args)
Invokes a named method on this object.
void setMethod (Identifier methodName, var::NativeFunction function)
Adds a method to the class.
void clear ()
Removes all properties and methods from the object.
NamedValueSet & getProperties () noexcept
Returns the NamedValueSet that holds the object's properties.
const NamedValueSet & getProperties () const noexcept
Returns the NamedValueSet that holds the object's properties.
void cloneAllProperties ()
Calls var::clone() on all the properties that this object contains.
virtual std::unique_ptr< DynamicObject > clone () const
Returns a clone of this object.
virtual void writeAsJSON (OutputStream &, const JSON::FormatOptions &)
Writes this object to a text stream in JSON format.
Public Member Functions inherited from yup::ReferenceCountedObject
void incReferenceCount () const noexcept
Increments the object's reference count.
void decReferenceCount () const noexcept
Decreases the object's reference count.
bool decReferenceCountWithoutDeleting () const noexcept
Decreases the object's reference count.
int getReferenceCount () const noexcept
Returns the object's current reference count.
Additional Inherited Members
Protected Member Functions inherited from yup::ReferenceCountedObject
ReferenceCountedObject ()=default
Creates the reference-counted object (with an initial ref count of zero).
ReferenceCountedObject (const ReferenceCountedObject &) noexcept
Copying from another object does not affect this one's reference-count.
ReferenceCountedObject (ReferenceCountedObject &&) noexcept
Copying from another object does not affect this one's reference-count.
ReferenceCountedObject & operator= (const ReferenceCountedObject &) noexcept
Copying from another object does not affect this one's reference-count.
ReferenceCountedObject & operator= (ReferenceCountedObject &&) noexcept
Copying from another object does not affect this one's reference-count.
virtual ~ReferenceCountedObject ()
Destructor.
void resetReferenceCount () const noexcept
Resets the reference count to zero without deleting the object.
Detailed Description
Represents a dynamically implemented object.
This class is primarily intended for wrapping scripting language objects, but could be used for other purposes.
An instance of a DynamicObject can be used to store named properties, and by subclassing hasMethod() and invokeMethod(), you can give your object methods.
Member Typedef Documentation
Ptr
using yup::DynamicObject::Ptr = ReferenceCountedObjectPtr<DynamicObject>
Constructor & Destructor Documentation
DynamicObject() [1/2]
yup::DynamicObject::DynamicObject ()
Referenced by DynamicObject().
DynamicObject() [2/2]
yup::DynamicObject::DynamicObject (const DynamicObject & other)
References DynamicObject(), and yup::ReferenceCountedObject::ReferenceCountedObject().
~DynamicObject()
yup::DynamicObject::~DynamicObject () override
Member Function Documentation
hasProperty()
bool yup::DynamicObject::hasProperty (const Identifier & propertyName) const virtual
Returns true if the object has a property with this name.
Note that if the property is actually a method, this will return false.
References yup::var::isMethod().
getProperty()
const var & yup::DynamicObject::getProperty (const Identifier & propertyName) const virtual
Returns a named property.
This returns var() if no such property exists.
Referenced by hasMethod().
setProperty()
void yup::DynamicObject::setProperty (const Identifier & propertyName, const var & newValue) virtual
Sets a named property.
Referenced by yup::Artboard::getAllInputs().
removeProperty()
void yup::DynamicObject::removeProperty (const Identifier & propertyName) virtual
Removes a named property.
References yup::var::remove().
hasMethod()
bool yup::DynamicObject::hasMethod (const Identifier & methodName) const virtual
Checks whether this object has the specified method.
The default implementation of this just checks whether there's a property with this name that's actually a method, but this can be overridden for building objects with dynamic invocation.
References getProperty(), and yup::var::isMethod().
invokeMethod()
var yup::DynamicObject::invokeMethod (Identifier methodName, const var::NativeFunctionArgs & args) virtual
Invokes a named method on this object.
The default implementation looks up the named property, and if it's a method call, then it invokes it.
This method is virtual to allow more dynamic invocation to used for objects where the methods may not already be set as properties.
setMethod()
void yup::DynamicObject::setMethod (Identifier methodName, var::NativeFunction function)
Adds a method to the class.
This is basically the same as calling setProperty (methodName, (var::NativeFunction) myFunction), but helps to avoid accidentally invoking the wrong type of var constructor. It also makes the code easier to read.
clear()
void yup::DynamicObject::clear ()
Removes all properties and methods from the object.
getProperties() [1/2]
NamedValueSet & yup::DynamicObject::getProperties () noexcept
Returns the NamedValueSet that holds the object's properties.
Referenced by yup::JSONUtils::deepEqual().
getProperties() [2/2]
const NamedValueSet & yup::DynamicObject::getProperties () const noexcept
Returns the NamedValueSet that holds the object's properties.
cloneAllProperties()
void yup::DynamicObject::cloneAllProperties ()
Calls var::clone() on all the properties that this object contains.
clone()
std::unique_ptr< DynamicObject > yup::DynamicObject::clone () const virtual
Returns a clone of this object.
The default implementation of this method just returns a new DynamicObject with a (deep) copy of all of its properties. Subclasses can override this to implement their own custom copy routines.
writeAsJSON()
void yup::DynamicObject::writeAsJSON (OutputStream & out, const JSON::FormatOptions & format) virtual
Writes this object to a text stream in JSON format.
This method is used by JSON::toString and JSON::writeToStream, and you should never need to call it directly, but it's virtual so that custom object types can stringify themselves appropriately.
References yup::JSON::FormatOptions::getIndentLevel(), yup::JSON::FormatOptions::getSpacing(), yup::JSON::multiLine, yup::newLine, yup::JSON::none, yup::JSON::singleLine, yup::JSON::FormatOptions::withIndentLevel(), and yup::JSON::writeToStream().