YUP: yup::ApplicationTheme Class Reference
yup::ApplicationTheme Class Reference final
Manages the application-wide theme settings.
Public Types
using Ptr = ReferenceCountedObjectPtr<ApplicationTheme>
Typedef for a reference-counted pointer to an ApplicationTheme object.
using ConstPtr = ReferenceCountedObjectPtr<const ApplicationTheme>
Typedef for a reference-counted pointer to a const ApplicationTheme object.
Public Member Functions
ApplicationTheme ()
Constructs an ApplicationTheme object.
~ApplicationTheme ()
template<class ComponentType>
void setComponentStyle (ComponentStyle::Ptr style)
Sets the style for a specific component type.
void setColor (const Identifier &colorId, const Color &color)
void setColors (std::initializer_list< std::pair< const Identifier &, const Color & > > colors)
void setDefaultFont (Font font)
Sets the default font for the application theme.
const Font & getDefaultFont () const
Returns the default font for the application theme.
Public Member Functions inherited from yup::ReferenceCountedObject
void incReferenceCount () const noexcept
Increments the object's reference count.
void decReferenceCount () const noexcept
Decreases the object's reference count.
bool decReferenceCountWithoutDeleting () const noexcept
Decreases the object's reference count.
int getReferenceCount () const noexcept
Returns the object's current reference count.
Static Public Member Functions
static void setGlobalTheme (ApplicationTheme::Ptr s)
Sets the global application theme.
static ApplicationTheme::ConstPtr getGlobalTheme ()
Returns the global application theme.
template<class ComponentType>
static auto findComponentStyle (ComponentType &component) -> std::enable_if_t< std::is_base_of_v< Component, ComponentType >, ComponentStyle::Ptr >
Resolves the style for a specific component type.
static Color findColor (const Identifier &colorId)
Additional Inherited Members
Protected Member Functions inherited from yup::ReferenceCountedObject
ReferenceCountedObject ()=default
Creates the reference-counted object (with an initial ref count of zero).
ReferenceCountedObject (const ReferenceCountedObject &) noexcept
Copying from another object does not affect this one's reference-count.
ReferenceCountedObject (ReferenceCountedObject &&) noexcept
Copying from another object does not affect this one's reference-count.
ReferenceCountedObject & operator= (const ReferenceCountedObject &) noexcept
Copying from another object does not affect this one's reference-count.
ReferenceCountedObject & operator= (ReferenceCountedObject &&) noexcept
Copying from another object does not affect this one's reference-count.
virtual ~ReferenceCountedObject ()
Destructor.
void resetReferenceCount () const noexcept
Resets the reference count to zero without deleting the object.
Detailed Description
Manages the application-wide theme settings.
The ApplicationTheme class provides methods to set and retrieve component-specific themes and the default font. It is reference-counted for safe usage across multiple parts of the application.
Member Typedef Documentation
Ptr
using yup::ApplicationTheme::Ptr = ReferenceCountedObjectPtr<ApplicationTheme>
Typedef for a reference-counted pointer to an ApplicationTheme object.
ConstPtr
using yup::ApplicationTheme::ConstPtr = ReferenceCountedObjectPtr<const ApplicationTheme>
Typedef for a reference-counted pointer to a const ApplicationTheme object.
Constructor & Destructor Documentation
ApplicationTheme()
yup::ApplicationTheme::ApplicationTheme () default
Constructs an ApplicationTheme object.
~ApplicationTheme()
yup::ApplicationTheme::~ApplicationTheme () default
References getGlobalTheme(), and setGlobalTheme().
Member Function Documentation
setGlobalTheme()
void yup::ApplicationTheme::setGlobalTheme (ApplicationTheme::Ptr s) static
Sets the global application theme.
This method sets a global instance of the ApplicationTheme, which can be retrieved and used throughout the application.
Parameters
s The ApplicationTheme object to set as the global theme.
Referenced by ~ApplicationTheme().
getGlobalTheme()
ApplicationTheme::ConstPtr yup::ApplicationTheme::getGlobalTheme () static
Returns the global application theme.
This method retrieves the global instance of the ApplicationTheme.
Returns
A reference-counted pointer to the global ApplicationTheme.
Referenced by yup::Label::paint(), yup::Slider::paint(), yup::TextEditor::paint(), yup::TextButton::paintButton(), yup::TextButton::resized(), and ~ApplicationTheme().
findComponentStyle()
template<class ComponentType> auto yup::ApplicationTheme::findComponentStyle (ComponentType & component) -> std::enable_if_t<std::is_base_of_v<Component, ComponentType>, ComponentStyle::Ptr> static
Resolves the style for a specific component type.
This template method returns the style for the specified component type. If a style is provided as an argument, it will be returned; otherwise, the global style will be used.
Parameters
instanceStyle An optional style to use instead of the global style.
Returns
The resolved style for the component type.
Referenced by yup::Label::paint(), yup::Slider::paint(), yup::TextEditor::paint(), and yup::TextButton::paintButton().
setComponentStyle()
template<class ComponentType> void yup::ApplicationTheme::setComponentStyle (ComponentStyle::Ptr style)
Sets the style for a specific component type.
This template method allows setting the style for a specific type of component. The component type must be part of the componentStyles tuple.
Parameters
instanceStyle The style to set for the component type.
Referenced by yup::createThemeVersion1().
findColor()
Color yup::ApplicationTheme::findColor (const Identifier & colorId) static
References yup::Color.
setColor()
void yup::ApplicationTheme::setColor (const Identifier & colorId, const Color & color)
Referenced by yup::createThemeVersion1().
setColors()
void yup::ApplicationTheme::setColors (std::initializer_list< std::pair< const Identifier &, const Color & > > colors)
setDefaultFont()
void yup::ApplicationTheme::setDefaultFont (Font font)
Sets the default font for the application theme.
Parameters
font The font to set as the default.
Referenced by yup::createThemeVersion1().
getDefaultFont()
const Font & yup::ApplicationTheme::getDefaultFont () const
Returns the default font for the application theme.
Returns
The default font.
Referenced by yup::TextButton::resized().