YUP: yup::AbstractFifo::ScopedReadWrite< mode > Class Template Reference
yup::AbstractFifo::ScopedReadWrite< mode > Class Template Reference final
Class for a scoped reader/writer.
Public Member Functions
ScopedReadWrite ()=default
Construct an unassigned reader/writer.
ScopedReadWrite (AbstractFifo &f, int num) noexcept
Construct a reader/writer and immediately call prepareRead/prepareWrite on the abstractFifo which was passed in.
ScopedReadWrite (const ScopedReadWrite &)=delete
ScopedReadWrite (ScopedReadWrite &&) noexcept
ScopedReadWrite & operator= (const ScopedReadWrite &)=delete
ScopedReadWrite & operator= (ScopedReadWrite &&) noexcept
~ScopedReadWrite () noexcept
Calls finishedRead or finishedWrite if this is a non-null scoped reader/writer.
template<typename FunctionToApply>
void forEach (FunctionToApply &&func) const
Calls the passed function with each index that was deemed valid for the current read/write operation.
Public Attributes
int startIndex1
int blockSize1
int startIndex2
int blockSize2
Detailed Description
template<ReadOrWrite mode>
class yup::AbstractFifo::ScopedReadWrite< mode >
Class for a scoped reader/writer.
Constructor & Destructor Documentation
ScopedReadWrite() [1/4]
template<ReadOrWrite mode> yup::AbstractFifo::ScopedReadWrite< mode >::ScopedReadWrite () default
Construct an unassigned reader/writer.
Doesn't do anything upon destruction.
Referenced by operator=(), and ScopedReadWrite().
ScopedReadWrite() [2/4]
template<ReadOrWrite mode> yup::AbstractFifo::ScopedReadWrite< mode >::ScopedReadWrite (AbstractFifo & f, int num) noexcept
Construct a reader/writer and immediately call prepareRead/prepareWrite on the abstractFifo which was passed in.
This object will hold a pointer back to the fifo, so make sure that the fifo outlives this object.
ScopedReadWrite() [3/4]
template<ReadOrWrite mode> yup::AbstractFifo::ScopedReadWrite< mode >::ScopedReadWrite (const ScopedReadWrite< mode > &) delete
ScopedReadWrite() [4/4]
template<ReadOrWrite mode> yup::AbstractFifo::ScopedReadWrite< mode >::ScopedReadWrite (ScopedReadWrite< mode > && other) noexcept
References blockSize1, blockSize2, ScopedReadWrite(), startIndex1, and startIndex2.
~ScopedReadWrite()
template<ReadOrWrite mode> yup::AbstractFifo::ScopedReadWrite< mode >::~ScopedReadWrite () noexcept
Calls finishedRead or finishedWrite if this is a non-null scoped reader/writer.
Member Function Documentation
operator=() [1/2]
template<ReadOrWrite mode> ScopedReadWrite & yup::AbstractFifo::ScopedReadWrite< mode >::operator= (const ScopedReadWrite< mode > &) delete
operator=() [2/2]
template<ReadOrWrite mode> AbstractFifo::ScopedReadWrite< mode > & yup::AbstractFifo::ScopedReadWrite< mode >::operator= (ScopedReadWrite< mode > && other) noexcept
References ScopedReadWrite().
forEach()
template<ReadOrWrite mode> template<typename FunctionToApply> void yup::AbstractFifo::ScopedReadWrite< mode >::forEach (FunctionToApply && func) const
Calls the passed function with each index that was deemed valid for the current read/write operation.
Member Data Documentation
startIndex1
template<ReadOrWrite mode> int yup::AbstractFifo::ScopedReadWrite< mode >::startIndex1
Referenced by ScopedReadWrite().
blockSize1
template<ReadOrWrite mode> int yup::AbstractFifo::ScopedReadWrite< mode >::blockSize1
Referenced by ScopedReadWrite().
startIndex2
template<ReadOrWrite mode> int yup::AbstractFifo::ScopedReadWrite< mode >::startIndex2
Referenced by ScopedReadWrite().
blockSize2
template<ReadOrWrite mode> int yup::AbstractFifo::ScopedReadWrite< mode >::blockSize2
Referenced by ScopedReadWrite().