YUP: yup::Result Class Reference
yup::Result Class Reference
Represents the 'success' or 'failure' of an operation, and holds an associated error message to describe the error when there's a failure.
Public Member Functions
bool wasOk () const noexcept
Returns true if this result indicates a success.
bool failed () const noexcept
Returns true if this result indicates a failure.
operator bool () const noexcept
Returns true if this result indicates a success.
bool operator! () const noexcept
Returns true if this result indicates a failure.
const String & getErrorMessage () const noexcept
Returns the error message that was set when this result was created.
Result (const Result &)
Result & operator= (const Result &)
Result (Result &&) noexcept
Result & operator= (Result &&) noexcept
bool operator== (const Result &other) const noexcept
bool operator!= (const Result &other) const noexcept
Static Public Member Functions
static Result ok () noexcept
Creates and returns a 'successful' result.
static Result fail (const String &errorMessage) noexcept
Creates a 'failure' result.
Detailed Description
Represents the 'success' or 'failure' of an operation, and holds an associated error message to describe the error when there's a failure.
E.g.
Result myOperation()
{
    if (doSomeKindOfFoobar())
        return Result::ok();
    else
        return Result::fail ("foobar didn't work!");
}
const Result result (myOperation());
if (result.wasOk())
{
    ...it's all good...
}
else
{
    warnUserAboutFailure ("The foobar operation failed! Error message was: "
                            + result.getErrorMessage());
}
Constructor & Destructor Documentation
Result() [1/2]
yup::Result::Result (const Result & other)
References Result().
Referenced by fail(), ok(), operator!=(), operator=(), operator=(), operator==(), Result(), and Result().
Result() [2/2]
yup::Result::Result (Result && other) noexcept
References Result().
Member Function Documentation
ok()
Result yup::Result::ok () static noexcept
Creates and returns a 'successful' result.
References Result().
Referenced by yup::JavascriptEngine::callFunction(), yup::JavascriptEngine::callFunctionObject(), yup::File::create(), yup::File::createDirectory(), yup::JavascriptEngine::evaluate(), yup::JavascriptEngine::execute(), yup::Font::loadFromData(), yup::Font::loadFromFile(), yup::JSON::parse(), yup::JSON::parseQuotedString(), yup::FileOutputStream::truncate(), yup::ZipFile::uncompressEntry(), and yup::ZipFile::uncompressTo().
fail()
Result yup::Result::fail (const String & errorMessage) static noexcept
Creates a 'failure' result.
If you pass a blank error message in here, a default "Unknown Error" message will be used instead.
References Result().
Referenced by yup::JavascriptEngine::callFunction(), yup::JavascriptEngine::callFunctionObject(), yup::File::create(), yup::File::createDirectory(), yup::JavascriptEngine::evaluate(), yup::JavascriptEngine::execute(), yup::Font::loadFromData(), yup::Font::loadFromFile(), yup::JSON::parseQuotedString(), and yup::ZipFile::uncompressEntry().
wasOk()
bool yup::Result::wasOk () const noexcept
Returns true if this result indicates a success.
References yup::String::isEmpty().
Referenced by yup::SHA1::SHA1().
failed()
bool yup::Result::failed () const noexcept
Returns true if this result indicates a failure.
You can use getErrorMessage() to retrieve the error message associated with the failure.
Referenced by yup::createThemeVersion1(), and yup::XmlElement::writeTo().
operator bool()
yup::Result::operator bool () const noexcept
Returns true if this result indicates a success.
This is equivalent to calling wasOk().
operator!()
bool yup::Result::operator! () const noexcept
Returns true if this result indicates a failure.
This is equivalent to calling failed().
getErrorMessage()
const String & yup::Result::getErrorMessage () const noexcept
Returns the error message that was set when this result was created.
For a successful result, this will be an empty string;
operator=() [1/2]
Result & yup::Result::operator= (const Result & other)
References Result().
operator=() [2/2]
Result & yup::Result::operator= (Result && other) noexcept
References Result().
operator==()
bool yup::Result::operator== (const Result & other) const noexcept
References Result().
operator!=()
bool yup::Result::operator!= (const Result & other) const noexcept
References Result().