YUP: yup::GZIPDecompressorInputStream Class Reference
yup::GZIPDecompressorInputStream Class Reference
This stream will decompress a source-stream using zlib.
Public Types
enum Format { zlibFormat = 0 , deflateFormat , gzipFormat }
Public Member Functions
GZIPDecompressorInputStream (InputStream *sourceStream, bool deleteSourceWhenDestroyed, Format sourceFormat=zlibFormat, int64 uncompressedStreamLength=-1)
Creates a decompressor stream.
GZIPDecompressorInputStream (InputStream &sourceStream)
Creates a decompressor stream.
~GZIPDecompressorInputStream () override
Destructor.
int64 getPosition () override
Returns the offset of the next byte that will be read from the stream.
bool setPosition (int64 pos) override
Tries to move the current read position of the stream.
int64 getTotalLength () override
Returns the total number of bytes available for reading in this stream.
bool isExhausted () override
Returns true if the stream has no more data to read.
int read (void *destBuffer, int maxBytesToRead) override
Reads some data from the stream into a memory buffer.
Public Member Functions inherited from yup::InputStream
virtual ~InputStream ()=default
Destructor.
int64 getNumBytesRemaining ()
Returns the number of bytes available for reading, or a negative value if the remaining length is not known.
ssize_t read (void *destBuffer, size_t maxBytesToRead)
virtual char readByte ()
Reads a byte from the stream.
virtual bool readBool ()
Reads a boolean from the stream.
virtual short readShort ()
Reads two bytes from the stream as a little-endian 16-bit value.
virtual short readShortBigEndian ()
Reads two bytes from the stream as a little-endian 16-bit value.
virtual int readInt ()
Reads four bytes from the stream as a little-endian 32-bit value.
virtual int readIntBigEndian ()
Reads four bytes from the stream as a big-endian 32-bit value.
virtual int64 readInt64 ()
Reads eight bytes from the stream as a little-endian 64-bit value.
virtual int64 readInt64BigEndian ()
Reads eight bytes from the stream as a big-endian 64-bit value.
virtual float readFloat ()
Reads four bytes as a 32-bit floating point value.
virtual float readFloatBigEndian ()
Reads four bytes as a 32-bit floating point value.
virtual double readDouble ()
Reads eight bytes as a 64-bit floating point value.
virtual double readDoubleBigEndian ()
Reads eight bytes as a 64-bit floating point value.
virtual int readCompressedInt ()
Reads an encoded 32-bit number from the stream using a space-saving compressed format.
virtual String readNextLine ()
Reads a UTF-8 string from the stream, up to the next linefeed or carriage return.
virtual String readString ()
Reads a zero-terminated UTF-8 string from the stream.
virtual String readEntireStreamAsString ()
Tries to read the whole stream and turn it into a string.
virtual size_t readIntoMemoryBlock (MemoryBlock &destBlock, ssize_t maxNumBytesToRead=-1)
Reads from the stream and appends the data to a MemoryBlock.
virtual void skipNextBytes (int64 numBytesToSkip)
Reads and discards a number of bytes from the stream.
Additional Inherited Members
Protected Member Functions inherited from yup::InputStream
InputStream ()=default
Detailed Description
This stream will decompress a source-stream using zlib.
Tip: if you're reading lots of small items from one of these streams, you can increase the performance enormously by passing it through a BufferedInputStream, so that it has to read larger blocks less often.
See also
GZIPCompressorOutputStream
Member Enumeration Documentation
Format
enum yup::GZIPDecompressorInputStream::Format
Enumerator
zlibFormat
deflateFormat
gzipFormat
Constructor & Destructor Documentation
GZIPDecompressorInputStream() [1/2]
yup::GZIPDecompressorInputStream::GZIPDecompressorInputStream (InputStream * sourceStream, bool deleteSourceWhenDestroyed, Format sourceFormat = zlibFormat, int64 uncompressedStreamLength = -1)
Creates a decompressor stream.
Parameters
sourceStream the stream to read from
deleteSourceWhenDestroyed whether or not to delete the source stream when this object is destroyed
sourceFormat can be used to select which of the supported formats the data is expected to be in
uncompressedStreamLength if the creator knows the length that the uncompressed stream will be, then it can supply this value, which will be returned by getTotalLength()
References getPosition(), and yup::InputStream::InputStream().
GZIPDecompressorInputStream() [2/2]
yup::GZIPDecompressorInputStream::GZIPDecompressorInputStream (InputStream & sourceStream)
Creates a decompressor stream.
Parameters
sourceStream the stream to read from - the source stream must not be deleted until this object has been destroyed
References getPosition(), yup::InputStream::InputStream(), and zlibFormat.
~GZIPDecompressorInputStream()
yup::GZIPDecompressorInputStream::~GZIPDecompressorInputStream () override
Destructor.
Member Function Documentation
getPosition()
int64 yup::GZIPDecompressorInputStream::getPosition () override virtual
Returns the offset of the next byte that will be read from the stream.
See also
setPosition
Implements yup::InputStream.
Referenced by GZIPDecompressorInputStream(), and GZIPDecompressorInputStream().
setPosition()
bool yup::GZIPDecompressorInputStream::setPosition (int64 newPosition) override virtual
Tries to move the current read position of the stream.
The position is an absolute number of bytes from the stream's start.
Some streams might not be able to do this, in which case they should do nothing and return false. Others might be able to manage it by resetting themselves and skipping to the correct position, although this is obviously a bit slow.
Returns
true if the stream manages to reposition itself correctly
See also
getPosition
Implements yup::InputStream.
References yup::InputStream::skipNextBytes().
getTotalLength()
int64 yup::GZIPDecompressorInputStream::getTotalLength () override virtual
Returns the total number of bytes available for reading in this stream.
Note that this is the number of bytes available from the start of the stream, not from the current position.
If the size of the stream isn't actually known, this will return -1.
See also
getNumBytesRemaining
Implements yup::InputStream.
isExhausted()
bool yup::GZIPDecompressorInputStream::isExhausted () override virtual
Returns true if the stream has no more data to read.
Implements yup::InputStream.
read()
int yup::GZIPDecompressorInputStream::read (void * destBuffer, int maxBytesToRead) override virtual
Reads some data from the stream into a memory buffer.
This is the only read method that subclasses actually need to implement, as the InputStream base class implements the other read methods in terms of this one (although it's often more efficient for subclasses to implement them directly).
Parameters
destBuffer the destination buffer for the data. This must not be null.
maxBytesToRead the maximum number of bytes to read - make sure the memory block passed in is big enough to contain this many bytes. This value must not be negative.
Returns
the actual number of bytes that were read, which may be less than maxBytesToRead if the stream is exhausted before it gets that far
Implements yup::InputStream.