YUP: yup::XmlElement Class Reference
yup::XmlElement Class Reference
Used to build a tree of elements representing an XML document.
Classes
struct TextFormat
A struct containing options for formatting the text when representing an XML element as a string.
Public Member Functions
XmlElement (const String &tagName)
Creates an XmlElement with this tag name.
XmlElement (const char *tagName)
Creates an XmlElement with this tag name.
XmlElement (const Identifier &tagName)
Creates an XmlElement with this tag name.
XmlElement (StringRef tagName)
Creates an XmlElement with this tag name.
XmlElement (String::CharPointerType tagNameBegin, String::CharPointerType tagNameEnd)
Creates an XmlElement with this tag name.
XmlElement (const XmlElement &)
Creates a (deep) copy of another element.
XmlElement & operator= (const XmlElement &)
Creates a (deep) copy of another element.
XmlElement & operator= (XmlElement &&) noexcept
Move assignment operator.
XmlElement (XmlElement &&) noexcept
Move constructor.
~XmlElement () noexcept
Deleting an XmlElement will also delete all of its child elements.
bool isEquivalentTo (const XmlElement *other, bool ignoreOrderOfAttributes) const noexcept
Compares two XmlElements to see if they contain the same text and attributes.
String toString (const TextFormat &format={}) const
Returns a text version of this XML element.
void writeTo (OutputStream &output, const TextFormat &format={}) const
Writes the document to a stream as UTF-8.
bool writeTo (const File &destinationFile, const TextFormat &format={}) const
Writes the document to a file as UTF-8.
const String & getTagName () const noexcept
Returns this element's tag type name.
String getNamespace () const
Returns the namespace portion of the tag-name, or an empty string if none is specified.
String getTagNameWithoutNamespace () const
Returns the part of the tag-name that follows any namespace declaration.
bool hasTagName (StringRef possibleTagName) const noexcept
Tests whether this element has a particular tag name.
bool hasTagNameIgnoringNamespace (StringRef possibleTagName) const
Tests whether this element has a particular tag name, ignoring any XML namespace prefix.
void setTagName (StringRef newTagName)
Changes this elements tag name.
int getNumAttributes () const noexcept
Returns the number of XML attributes this element contains.
const String & getAttributeName (int attributeIndex) const noexcept
Returns the name of one of the elements attributes.
const String & getAttributeValue (int attributeIndex) const noexcept
Returns the value of one of the elements attributes.
bool hasAttribute (StringRef attributeName) const noexcept
Checks whether the element contains an attribute with a certain name.
const String & getStringAttribute (StringRef attributeName) const noexcept
Returns the value of a named attribute.
String getStringAttribute (StringRef attributeName, const String &defaultReturnValue) const
Returns the value of a named attribute.
bool compareAttribute (StringRef attributeName, StringRef stringToCompareAgainst, bool ignoreCase=false) const noexcept
Compares the value of a named attribute with a value passed-in.
int getIntAttribute (StringRef attributeName, int defaultReturnValue=0) const
Returns the value of a named attribute as an integer.
double getDoubleAttribute (StringRef attributeName, double defaultReturnValue=0.0) const
Returns the value of a named attribute as floating-point.
bool getBoolAttribute (StringRef attributeName, bool defaultReturnValue=false) const
Returns the value of a named attribute as a boolean.
void setAttribute (const Identifier &attributeName, const String &newValue)
Adds a named attribute to the element.
void setAttribute (const Identifier &attributeName, int newValue)
Adds a named attribute to the element, setting it to an integer value.
void setAttribute (const Identifier &attributeName, double newValue)
Adds a named attribute to the element, setting it to a floating-point value.
void removeAttribute (const Identifier &attributeName) noexcept
Removes a named attribute from the element.
void removeAllAttributes () noexcept
Removes all attributes from this element.
XmlElement * getFirstChildElement () const noexcept
Returns the first of this element's sub-elements.
XmlElement * getNextElement () const noexcept
Returns the next of this element's siblings.
XmlElement * getNextElementWithTagName (StringRef requiredTagName) const
Returns the next of this element's siblings which has the specified tag name.
int getNumChildElements () const noexcept
Returns the number of sub-elements in this element.
XmlElement * getChildElement (int index) const noexcept
Returns the sub-element at a certain index.
XmlElement * getChildByName (StringRef tagNameToLookFor) const noexcept
Returns the first sub-element with a given tag-name.
XmlElement * getChildByAttribute (StringRef attributeName, StringRef attributeValue) const noexcept
Returns the first sub-element which has an attribute that matches the given value.
void addChildElement (XmlElement *newChildElement) noexcept
Appends an element to this element's list of children.
void insertChildElement (XmlElement *newChildElement, int indexToInsertAt) noexcept
Inserts an element into this element's list of children.
void prependChildElement (XmlElement *newChildElement) noexcept
Inserts an element at the beginning of this element's list of children.
XmlElement * createNewChildElement (StringRef tagName)
Creates a new element with the given name and returns it, after adding it as a child element.
bool replaceChildElement (XmlElement *currentChildElement, XmlElement *newChildNode) noexcept
Replaces one of this element's children with another node.
void removeChildElement (XmlElement *childToRemove, bool shouldDeleteTheChild) noexcept
Removes a child element.
void deleteAllChildElements () noexcept
Deletes all the child elements in the element.
void deleteAllChildElementsWithTagName (StringRef tagName) noexcept
Deletes all the child elements with a given tag name.
bool containsChildElement (const XmlElement *possibleChild) const noexcept
Returns true if the given element is a child of this one.
XmlElement * findParentElementOf (const XmlElement *childToSearchFor) noexcept
Recursively searches all sub-elements of this one, looking for an element which is the direct parent of the specified element.
template<class ElementComparator>
void sortChildElements (ElementComparator &comparator, bool retainOrderOfEquivalentItems=false)
Sorts the child elements using a comparator.
bool isTextElement () const noexcept
Returns true if this element is a section of text.
const String & getText () const noexcept
Returns the text for a text element.
void setText (const String &newText)
Sets the text in a text element.
String getAllSubText () const
Returns all the text from this element's child nodes.
String getChildElementAllSubText (StringRef childTagName, const String &defaultReturnValue) const
Returns all the sub-text of a named child element.
void addTextElement (const String &text)
Appends a section of text to this element.
void deleteAllTextElements () noexcept
Removes all the text elements from this element.
Iterator< GetNextElement > getChildIterator () const
Allows iterating the children of an XmlElement using range-for syntax.
Iterator< GetNextElementWithTagName > getChildWithTagNameIterator (StringRef name) const
Allows iterating children of an XmlElement with a specific tag using range-for syntax.
Static Public Member Functions
static XmlElement * createTextElement (const String &text)
Creates a text element that can be added to a parent element.
static bool isValidXmlName (StringRef possibleName) noexcept
Checks if a given string is a valid XML name.
Detailed Description
Used to build a tree of elements representing an XML document.
An XML document can be parsed into a tree of XmlElements, each of which represents an XML tag structure, and which may itself contain other nested elements.
An XmlElement can also be converted back into a text document, and has lots of useful methods for manipulating its attributes and sub-elements, so XmlElements can actually be used as a handy general-purpose data structure.
Here's an example of parsing some elements:
// check we're looking at the right kind of document..
if (myElement->hasTagName ("ANIMALS"))
{
    // now we'll iterate its sub-elements looking for 'giraffe' elements..
    for (auto* e : myElement->getChildIterator())
    {
        if (e->hasTagName ("GIRAFFE"))
        {
            // found a giraffe, so use some of its attributes..
            String giraffeName  = e->getStringAttribute ("name");
            int giraffeAge      = e->getIntAttribute ("age");
            bool isFriendly     = e->getBoolAttribute ("friendly");
        }
    }
}
And here's an example of how to create an XML document from scratch:
// create an outer node called "ANIMALS"
XmlElement animalsList ("ANIMALS");
for (int i = 0; i < numAnimals; ++i)
{
    // create an inner element..
    XmlElement* giraffe = new XmlElement ("GIRAFFE");
    giraffe->setAttribute ("name", "nigel");
    giraffe->setAttribute ("age", 10);
    giraffe->setAttribute ("friendly", true);
    // ..and add our new element to the parent node
    animalsList.addChildElement (giraffe);
}
// now we can turn the whole thing into textual XML
auto xmlString = animalsList.toString();
See also
parseXML, parseXMLIfTagMatches, XmlDocument
Constructor & Destructor Documentation
XmlElement() [1/7]
yup::XmlElement::XmlElement (const String & tagName) explicit
Creates an XmlElement with this tag name.
References isValidXmlName(), and XmlElement().
Referenced by addChildElement(), containsChildElement(), createNewChildElement(), createTextElement(), findParentElementOf(), getChildByAttribute(), getChildByName(), getChildElement(), getFirstChildElement(), getNextElement(), getNextElementWithTagName(), insertChildElement(), isEquivalentTo(), LinkedListPointer< XmlAttributeNode >, LinkedListPointer< XmlElement >::Appender, NamedValueSet, operator=(), operator=(), prependChildElement(), removeChildElement(), replaceChildElement(), sortChildElements(), XmlElement(), XmlElement(), and XmlElement().
XmlElement() [2/7]
yup::XmlElement::XmlElement (const char * tagName) explicit
Creates an XmlElement with this tag name.
References isValidXmlName().
XmlElement() [3/7]
yup::XmlElement::XmlElement (const Identifier & tagName) explicit
Creates an XmlElement with this tag name.
References isValidXmlName(), and toString().
XmlElement() [4/7]
yup::XmlElement::XmlElement (StringRef tagName) explicit
Creates an XmlElement with this tag name.
References isValidXmlName().
XmlElement() [5/7]
yup::XmlElement::XmlElement (String::CharPointerType tagNameBegin, String::CharPointerType tagNameEnd)
Creates an XmlElement with this tag name.
References isValidXmlName().
XmlElement() [6/7]
yup::XmlElement::XmlElement (const XmlElement & other)
Creates a (deep) copy of another element.
References XmlElement().
XmlElement() [7/7]
yup::XmlElement::XmlElement (XmlElement && other) noexcept
Move constructor.
References XmlElement().
~XmlElement()
yup::XmlElement::~XmlElement () noexcept
Deleting an XmlElement will also delete all of its child elements.
Member Function Documentation
operator=() [1/2]
XmlElement & yup::XmlElement::operator= (const XmlElement & other)
Creates a (deep) copy of another element.
References deleteAllChildElements(), removeAllAttributes(), and XmlElement().
operator=() [2/2]
XmlElement & yup::XmlElement::operator= (XmlElement && other) noexcept
Move assignment operator.
References deleteAllChildElements(), removeAllAttributes(), and XmlElement().
isEquivalentTo()
bool yup::XmlElement::isEquivalentTo (const XmlElement * other, bool ignoreOrderOfAttributes) const noexcept
Compares two XmlElements to see if they contain the same text and attributes.
The elements are only considered equivalent if they contain the same attributes with the same values, and have the same sub-nodes.
Parameters
other the other element to compare to
ignoreOrderOfAttributes if true, this means that two elements with the same attributes in a different order will be considered the same; if false, the attributes must be in the same order as well
References compareAttribute(), yup::LinkedListPointer< ObjectType >::get(), getNumAttributes(), and XmlElement().
toString()
String yup::XmlElement::toString (const TextFormat & format = {}) const
Returns a text version of this XML element.
If your intention is to write the XML to a file or stream, it's probably more efficient to use writeTo() instead of creating an intermediate string.
See also
writeTo
References yup::MemoryOutputStream::toUTF8(), and writeTo().
Referenced by yup::PropertySet::setValue(), and XmlElement().
writeTo() [1/2]
void yup::XmlElement::writeTo (OutputStream & output, const TextFormat & format = {}) const
Writes the document to a stream as UTF-8.
See also
writeTo, toString
References yup::XmlElement::TextFormat::addDefaultHeader, yup::XmlElement::TextFormat::customEncoding, yup::XmlElement::TextFormat::customHeader, yup::XmlElement::TextFormat::dtd, yup::String::isNotEmpty(), yup::XmlElement::TextFormat::lineWrapLength, yup::XmlElement::TextFormat::newLineChars, and yup::OutputStream::writeByte().
Referenced by toString(), and writeTo().
writeTo() [2/2]
bool yup::XmlElement::writeTo (const File & destinationFile, const TextFormat & format = {}) const
Writes the document to a file as UTF-8.
See also
writeTo, toString
References yup::Result::failed(), yup::FileOutputStream::flush(), yup::TemporaryFile::getFile(), yup::FileOutputStream::getStatus(), yup::FileOutputStream::openedOk(), yup::TemporaryFile::overwriteTargetFileWithTemporary(), and writeTo().
getTagName()
const String & yup::XmlElement::getTagName () const noexcept
Returns this element's tag type name.
E.g. for an element such as <MOOSE legs="4" antlers="2">, this would return "MOOSE".
See also
hasTagName
getNamespace()
String yup::XmlElement::getNamespace () const
Returns the namespace portion of the tag-name, or an empty string if none is specified.
References yup::String::upToFirstOccurrenceOf().
getTagNameWithoutNamespace()
String yup::XmlElement::getTagNameWithoutNamespace () const
Returns the part of the tag-name that follows any namespace declaration.
References yup::String::fromLastOccurrenceOf().
Referenced by hasTagNameIgnoringNamespace().
hasTagName()
bool yup::XmlElement::hasTagName (StringRef possibleTagName) const noexcept
Tests whether this element has a particular tag name.
Parameters
possibleTagName the tag name you're comparing it with
See also
getTagName
Referenced by hasTagNameIgnoringNamespace(), yup::AudioDeviceManager::initialise(), and yup::ChannelRemappingAudioSource::restoreFromXml().
hasTagNameIgnoringNamespace()
bool yup::XmlElement::hasTagNameIgnoringNamespace (StringRef possibleTagName) const
Tests whether this element has a particular tag name, ignoring any XML namespace prefix.
So a test for e.g. "xyz" will return true for "xyz" and also "foo:xyz", "bar::xyz", etc.
See also
getTagName
References getTagNameWithoutNamespace(), and hasTagName().
setTagName()
void yup::XmlElement::setTagName (StringRef newTagName)
Changes this elements tag name.
See also
getTagName
References yup::StringPool::getGlobalPool(), yup::StringPool::getPooledString(), and isValidXmlName().
getNumAttributes()
int yup::XmlElement::getNumAttributes () const noexcept
Returns the number of XML attributes this element contains.
E.g. for an element such as <MOOSE legs="4" antlers="2">, this would return 2.
Referenced by isEquivalentTo().
getAttributeName()
const String & yup::XmlElement::getAttributeName (int attributeIndex) const noexcept
Returns the name of one of the elements attributes.
E.g. for an element such as <MOOSE legs="4" antlers="2">, then getAttributeName (1) would return "antlers".
See also
getAttributeValue, getStringAttribute
References yup::get().
getAttributeValue()
const String & yup::XmlElement::getAttributeValue (int attributeIndex) const noexcept
Returns the value of one of the elements attributes.
E.g. for an element such as <MOOSE legs="4" antlers="2">, then getAttributeName (1) would return "2".
See also
getAttributeName, getStringAttribute
References yup::get().
hasAttribute()
bool yup::XmlElement::hasAttribute (StringRef attributeName) const noexcept
Checks whether the element contains an attribute with a certain name.
getStringAttribute() [1/2]
const String & yup::XmlElement::getStringAttribute (StringRef attributeName) const noexcept
Returns the value of a named attribute.
Parameters
attributeName the name of the attribute to look up
Referenced by getText(), and yup::ChannelRemappingAudioSource::restoreFromXml().
getStringAttribute() [2/2]
String yup::XmlElement::getStringAttribute (StringRef attributeName, const String & defaultReturnValue) const
Returns the value of a named attribute.
Parameters
attributeName the name of the attribute to look up
defaultReturnValue a value to return if the element doesn't have an attribute with this name
compareAttribute()
bool yup::XmlElement::compareAttribute (StringRef attributeName, StringRef stringToCompareAgainst, bool ignoreCase = false) const noexcept
Compares the value of a named attribute with a value passed-in.
Parameters
attributeName the name of the attribute to look up
stringToCompareAgainst the value to compare it with
ignoreCase whether the comparison should be case-insensitive
Returns
true if the value of the attribute is the same as the string passed-in; false if it's different (or if no such attribute exists)
Referenced by isEquivalentTo().
getIntAttribute()
int yup::XmlElement::getIntAttribute (StringRef attributeName, int defaultReturnValue = 0) const
Returns the value of a named attribute as an integer.
This will try to find the attribute and convert it to an integer (using the String::getIntValue() method).
Parameters
attributeName the name of the attribute to look up
defaultReturnValue a value to return if the element doesn't have an attribute with this name
See also
setAttribute
References yup::String::getIntValue().
getDoubleAttribute()
double yup::XmlElement::getDoubleAttribute (StringRef attributeName, double defaultReturnValue = 0.0) const
Returns the value of a named attribute as floating-point.
This will try to find the attribute and convert it to a double (using the String::getDoubleValue() method).
Parameters
attributeName the name of the attribute to look up
defaultReturnValue a value to return if the element doesn't have an attribute with this name
See also
setAttribute
getBoolAttribute()
bool yup::XmlElement::getBoolAttribute (StringRef attributeName, bool defaultReturnValue = false) const
Returns the value of a named attribute as a boolean.
This will try to find the attribute and interpret it as a boolean. To do this, it'll return true if the value is "1", "true", "y", etc, or false for other values.
Parameters
attributeName the name of the attribute to look up
defaultReturnValue a value to return if the element doesn't have an attribute with this name
setAttribute() [1/3]
void yup::XmlElement::setAttribute (const Identifier & attributeName, const String & newValue)
Adds a named attribute to the element.
If the element already contains an attribute with this name, it's value will be updated to the new value. If there's no such attribute yet, a new one will be added.
Note that there are other setAttribute() methods that take integers, doubles, etc. to make it easy to store numbers.
Parameters
attributeName the name of the attribute to set
newValue the value to set it to
See also
removeAttribute
Referenced by yup::NamedValueSet::copyToXmlAttributes(), setAttribute(), setAttribute(), and setText().
setAttribute() [2/3]
void yup::XmlElement::setAttribute (const Identifier & attributeName, int newValue)
Adds a named attribute to the element, setting it to an integer value.
If the element already contains an attribute with this name, it's value will be updated to the new value. If there's no such attribute yet, a new one will be added.
Note that there are other setAttribute() methods that take integers, doubles, etc. to make it easy to store numbers.
Parameters
attributeName the name of the attribute to set
newValue the value to set it to
References setAttribute().
setAttribute() [3/3]
void yup::XmlElement::setAttribute (const Identifier & attributeName, double newValue)
Adds a named attribute to the element, setting it to a floating-point value.
If the element already contains an attribute with this name, it's value will be updated to the new value. If there's no such attribute yet, a new one will be added.
Note that there are other setAttribute() methods that take integers, doubles, etc. to make it easy to store numbers.
Parameters
attributeName the name of the attribute to set
newValue the value to set it to
References yup::serialiseDouble(), and setAttribute().
removeAttribute()
void yup::XmlElement::removeAttribute (const Identifier & attributeName) noexcept
Removes a named attribute from the element.
Parameters
attributeName the name of the attribute to remove
See also
removeAllAttributes
removeAllAttributes()
void yup::XmlElement::removeAllAttributes () noexcept
Removes all attributes from this element.
Referenced by operator=(), and operator=().
getFirstChildElement()
XmlElement * yup::XmlElement::getFirstChildElement () const noexcept
Returns the first of this element's sub-elements.
see getNextElement() for an example of how to iterate the sub-elements.
See also
getChildIterator
References getFirstChildElement(), and XmlElement().
Referenced by getChildIterator(), and getFirstChildElement().
getNextElement()
XmlElement * yup::XmlElement::getNextElement () const noexcept
Returns the next of this element's siblings.
This can be used for iterating an element's sub-elements, e.g.
XmlElement* child = myXmlDocument->getFirstChildElement();
while (child != nullptr)
{
    ...do stuff with this child..
    child = child->getNextElement();
}
Note that when iterating the child elements, some of them might be text elements as well as XML tags - use isTextElement() to work this out.
Also, it's much easier and neater to use this method indirectly via the getChildIterator() method.
Returns
the sibling element that follows this one, or a nullptr if this is the last element in its parent
See also
getNextElement, isTextElement, getChildIterator
References XmlElement().
getNextElementWithTagName()
XmlElement * yup::XmlElement::getNextElementWithTagName (StringRef requiredTagName) const
Returns the next of this element's siblings which has the specified tag name.
This is like getNextElement(), but will scan through the list until it finds an element with the given tag name.
See also
getNextElement, getChildIterator
References XmlElement().
getNumChildElements()
int yup::XmlElement::getNumChildElements () const noexcept
Returns the number of sub-elements in this element.
See also
getChildElement
Referenced by getAllSubText(), and sortChildElements().
getChildElement()
XmlElement * yup::XmlElement::getChildElement (int index) const noexcept
Returns the sub-element at a certain index.
It's not very efficient to iterate the sub-elements by index - see getNextElement() for an example of how best to iterate.
Returns
the n'th child of this element, or nullptr if the index is out-of-range
See also
getNextElement, isTextElement, getChildByName
References XmlElement().
getChildByName()
XmlElement * yup::XmlElement::getChildByName (StringRef tagNameToLookFor) const noexcept
Returns the first sub-element with a given tag-name.
Parameters
tagNameToLookFor the tag name of the element you want to find
Returns
the first element with this tag name, or nullptr if none is found
See also
getNextElement, isTextElement, getChildElement, getChildByAttribute
References XmlElement().
Referenced by getChildElementAllSubText(), and getChildWithTagNameIterator().
getChildByAttribute()
XmlElement * yup::XmlElement::getChildByAttribute (StringRef attributeName, StringRef attributeValue) const noexcept
Returns the first sub-element which has an attribute that matches the given value.
Parameters
attributeName the name of the attribute to check
attributeValue the target value of the attribute
Returns
the first element with this attribute value, or nullptr if none is found
See also
getChildByName
References XmlElement().
addChildElement()
void yup::XmlElement::addChildElement (XmlElement * newChildElement) noexcept
Appends an element to this element's list of children.
Child elements are deleted automatically when their parent is deleted, so make sure the object that you pass in will not be deleted by anything else, and make sure it's not already the child of another element.
Note that due to the XmlElement using a singly-linked-list, prependChildElement() is an O(1) operation, but addChildElement() is an O(N) operation - so if you're adding large number of elements, you may prefer to do so in reverse order!
See also
getFirstChildElement, getNextElement, getNumChildElements, getChildElement, removeChildElement
References XmlElement().
Referenced by addTextElement(), and createNewChildElement().
insertChildElement()
void yup::XmlElement::insertChildElement (XmlElement * newChildElement, int indexToInsertAt) noexcept
Inserts an element into this element's list of children.
Child elements are deleted automatically when their parent is deleted, so make sure the object that you pass in will not be deleted by anything else, and make sure it's not already the child of another element.
Parameters
newChildElement the element to add
indexToInsertAt the index at which to insert the new element - if this is below zero, it will be added to the end of the list
See also
addChildElement, insertChildElement
References XmlElement().
prependChildElement()
void yup::XmlElement::prependChildElement (XmlElement * newChildElement) noexcept
Inserts an element at the beginning of this element's list of children.
Child elements are deleted automatically when their parent is deleted, so make sure the object that you pass in will not be deleted by anything else, and make sure it's not already the child of another element.
Note that due to the XmlElement using a singly-linked-list, prependChildElement() is an O(1) operation, but addChildElement() is an O(N) operation - so if you're adding large number of elements, you may prefer to do so in reverse order!
See also
addChildElement, insertChildElement
References XmlElement().
createNewChildElement()
XmlElement * yup::XmlElement::createNewChildElement (StringRef tagName)
Creates a new element with the given name and returns it, after adding it as a child element.
This is a handy method that means that instead of writing this:
XmlElement* newElement = new XmlElement ("foobar");
myParentElement->addChildElement (newElement);
..you could just write this:
XmlElement* newElement = myParentElement->createNewChildElement ("foobar");
References addChildElement(), and XmlElement().
replaceChildElement()
bool yup::XmlElement::replaceChildElement (XmlElement * currentChildElement, XmlElement * newChildNode) noexcept
Replaces one of this element's children with another node.
If the current element passed-in isn't actually a child of this element, this will return false and the new one won't be added. Otherwise, the existing element will be deleted, replaced with the new one, and it will return true.
References XmlElement().
removeChildElement()
void yup::XmlElement::removeChildElement (XmlElement * childToRemove, bool shouldDeleteTheChild) noexcept
Removes a child element.
Parameters
childToRemove the child to look for and remove
shouldDeleteTheChild if true, the child will be deleted, if false it'll just remove it
References containsChildElement(), and XmlElement().
Referenced by deleteAllChildElementsWithTagName(), and deleteAllTextElements().
deleteAllChildElements()
void yup::XmlElement::deleteAllChildElements () noexcept
Deletes all the child elements in the element.
See also
removeChildElement, deleteAllChildElementsWithTagName
Referenced by operator=(), and operator=().
deleteAllChildElementsWithTagName()
void yup::XmlElement::deleteAllChildElementsWithTagName (StringRef tagName) noexcept
Deletes all the child elements with a given tag name.
See also
removeChildElement
References removeChildElement().
containsChildElement()
bool yup::XmlElement::containsChildElement (const XmlElement * possibleChild) const noexcept
Returns true if the given element is a child of this one.
References XmlElement().
Referenced by removeChildElement().
findParentElementOf()
XmlElement * yup::XmlElement::findParentElementOf (const XmlElement * childToSearchFor) noexcept
Recursively searches all sub-elements of this one, looking for an element which is the direct parent of the specified element.
Because elements don't store a pointer to their parent, if you have one and need to find its parent, the only way to do so is to exhaustively search the whole tree for it.
If the given child is found somewhere in this element's hierarchy, then this method will return its parent. If not, it will return nullptr.
References XmlElement().
sortChildElements()
template<class ElementComparator> void yup::XmlElement::sortChildElements (ElementComparator & comparator, bool retainOrderOfEquivalentItems = false)
Sorts the child elements using a comparator.
This will use a comparator object to sort the elements into order. The object passed must have a method of the form:
int compareElements (const XmlElement* first, const XmlElement* second);
..and this method must return:
a value of < 0 if the first comes before the second
a value of 0 if the two objects are equivalent
a value of > 0 if the second comes before the first
To improve performance, the compareElements() method can be declared as static or const.
Parameters
comparator the comparator to use for comparing elements.
retainOrderOfEquivalentItems if this is true, then items which the comparator says are equivalent will be kept in the order in which they currently appear in the array. This is slower to perform, but may be important in some cases. If it's false, a faster algorithm is used, but equivalent elements may be rearranged.
References getNumChildElements(), sortChildElements(), and XmlElement().
Referenced by sortChildElements().
isTextElement()
bool yup::XmlElement::isTextElement () const noexcept
Returns true if this element is a section of text.
Elements can either be an XML tag element or a section of text, so this is used to find out what kind of element this one is.
See also
getAllText, addTextElement, deleteAllTextElements
Referenced by getAllSubText(), getText(), and setText().
getText()
const String & yup::XmlElement::getText () const noexcept
Returns the text for a text element.
Note that if you have an element like this:
<xyz>hello</xyz>
then calling getText on the "xyz" element won't return "hello", because that is actually stored in a special text sub-element inside the xyz element. To get the "hello" string, you could either call getText on the (unnamed) sub-element, or use getAllSubText() to do this automatically.
Note that leading and trailing whitespace will be included in the string - to remove if, just call String::trim() on the result.
See also
isTextElement, getAllSubText, getChildElementAllSubText
References getStringAttribute(), and isTextElement().
Referenced by getAllSubText().
setText()
void yup::XmlElement::setText (const String & newText)
Sets the text in a text element.
Note that this is only a valid call if this element is a text element. If it's not, then no action will be performed. If you're trying to add text inside a normal element, you probably want to use addTextElement() instead.
References isTextElement(), and setAttribute().
getAllSubText()
String yup::XmlElement::getAllSubText () const
Returns all the text from this element's child nodes.
This iterates all the child elements and when it finds text elements, it concatenates their text into a big string which it returns.
E.g.
<xyz>hello <x>there</x> world</xyz>
if you called getAllSubText on the "xyz" element, it'd return "hello there world".
Note that leading and trailing whitespace will be included in the string - to remove if, just call String::trim() on the result.
See also
isTextElement, getChildElementAllSubText, getText, addTextElement
References getNumChildElements(), getText(), isTextElement(), and yup::MemoryOutputStream::toUTF8().
getChildElementAllSubText()
String yup::XmlElement::getChildElementAllSubText (StringRef childTagName, const String & defaultReturnValue) const
Returns all the sub-text of a named child element.
If there is a child element with the given tag name, this will return all of its sub-text (by calling getAllSubText() on it). If there is no such child element, this will return the default string passed-in.
See also
getAllSubText
References getChildByName().
addTextElement()
void yup::XmlElement::addTextElement (const String & text)
Appends a section of text to this element.
See also
isTextElement, getText, getAllSubText
References addChildElement(), and createTextElement().
deleteAllTextElements()
void yup::XmlElement::deleteAllTextElements () noexcept
Removes all the text elements from this element.
See also
isTextElement, getText, getAllSubText, addTextElement
References removeChildElement().
createTextElement()
XmlElement * yup::XmlElement::createTextElement (const String & text) static
Creates a text element that can be added to a parent element.
References XmlElement().
Referenced by addTextElement().
isValidXmlName()
bool yup::XmlElement::isValidXmlName (StringRef possibleName) static noexcept
Checks if a given string is a valid XML name.
References yup::CharPointer_UTF8::getAndAdvance(), and yup::String::isEmpty().
Referenced by setTagName(), XmlElement(), XmlElement(), XmlElement(), XmlElement(), and XmlElement().
getChildIterator()
Iterator< GetNextElement > yup::XmlElement::getChildIterator () const
Allows iterating the children of an XmlElement using range-for syntax.
void doSomethingWithXmlChildren (const XmlElement& myParentXml)
{
    for (auto* element : myParentXml.getChildIterator())
        doSomethingWithXmlElement (element);
}
References getFirstChildElement().
getChildWithTagNameIterator()
Iterator< GetNextElementWithTagName > yup::XmlElement::getChildWithTagNameIterator (StringRef name) const
Allows iterating children of an XmlElement with a specific tag using range-for syntax.
void doSomethingWithXmlChildren (const XmlElement& myParentXml)
{
    for (auto* element : myParentXml.getChildWithTagNameIterator ("MYTAG"))
        doSomethingWithXmlElement (element);
}
References getChildByName().
Referenced by yup::PropertySet::restoreFromXml().