YUP: yup::AudioProcessLoadMeasurer Class Reference
yup::AudioProcessLoadMeasurer Class Reference
Maintains an ongoing measurement of the proportion of time which is being spent inside an audio callback.
Classes
struct ScopedTimer
This class measures the time between its construction and destruction and adds it to an AudioProcessLoadMeasurer.
Public Member Functions
AudioProcessLoadMeasurer ()
~AudioProcessLoadMeasurer ()
Destructor.
void reset ()
Resets the state.
void reset (double sampleRate, int blockSize)
Resets the counter, in preparation for use with the given sample rate and block size.
double getLoadAsProportion () const
Returns the current load as a proportion 0 to 1.0.
double getLoadAsPercentage () const
Returns the current load as a percentage 0 to 100.0.
int getXRunCount () const
Returns the number of over- (or under-) runs recorded since the state was reset.
void registerBlockRenderTime (double millisecondsTaken)
Can be called manually to add the time of a callback to the stats.
void registerRenderTime (double millisecondsTaken, int numSamples)
Can be called manually to add the time of a callback to the stats.
Detailed Description
Maintains an ongoing measurement of the proportion of time which is being spent inside an audio callback.
Constructor & Destructor Documentation
AudioProcessLoadMeasurer()
yup::AudioProcessLoadMeasurer::AudioProcessLoadMeasurer () default
Referenced by yup::AudioProcessLoadMeasurer::ScopedTimer::ScopedTimer(), and yup::AudioProcessLoadMeasurer::ScopedTimer::ScopedTimer().
~AudioProcessLoadMeasurer()
yup::AudioProcessLoadMeasurer::~AudioProcessLoadMeasurer () default
Destructor.
References getLoadAsPercentage(), getLoadAsProportion(), getXRunCount(), and reset().
Member Function Documentation
reset() [1/2]
void yup::AudioProcessLoadMeasurer::reset ()
Resets the state.
References reset().
Referenced by reset(), and ~AudioProcessLoadMeasurer().
reset() [2/2]
void yup::AudioProcessLoadMeasurer::reset (double sampleRate, int blockSize)
Resets the counter, in preparation for use with the given sample rate and block size.
getLoadAsProportion()
double yup::AudioProcessLoadMeasurer::getLoadAsProportion () const
Returns the current load as a proportion 0 to 1.0.
References yup::jlimit().
Referenced by getLoadAsPercentage(), and ~AudioProcessLoadMeasurer().
getLoadAsPercentage()
double yup::AudioProcessLoadMeasurer::getLoadAsPercentage () const
Returns the current load as a percentage 0 to 100.0.
References getLoadAsProportion().
Referenced by ~AudioProcessLoadMeasurer().
getXRunCount()
int yup::AudioProcessLoadMeasurer::getXRunCount () const
Returns the number of over- (or under-) runs recorded since the state was reset.
Referenced by ~AudioProcessLoadMeasurer().
registerBlockRenderTime()
void yup::AudioProcessLoadMeasurer::registerBlockRenderTime (double millisecondsTaken)
Can be called manually to add the time of a callback to the stats.
Normally you probably would never call this - it's simpler and more robust to use a ScopedTimer to measure the time using an RAII pattern.
References yup::GenericScopedTryLock< LockType >::isLocked().
registerRenderTime()
void yup::AudioProcessLoadMeasurer::registerRenderTime (double millisecondsTaken, int numSamples)
Can be called manually to add the time of a callback to the stats.
Normally you probably would never call this - it's simpler and more robust to use a ScopedTimer to measure the time using an RAII pattern.
References yup::GenericScopedTryLock< LockType >::isLocked().