YUP: yup::MouseCursor Class Reference
yup::MouseCursor Class Reference
Represents a mouse cursor image.
Public Types
enum Type {
None = 0 , Default , Arrow = Default , Text ,
Wait , WaitArrow , Hand , Crosshair ,
Crossbones , ResizeLeftRight , ResizeUpDown , ResizeTopLeftRightBottom ,
ResizeBottomLeftRightTop , ResizeAll
}
The set of available standard system mouse cursors.
Public Member Functions
MouseCursor () noexcept=default
Creates a default mouse cursor (an arrow).
MouseCursor (Type newType) noexcept
Creates a standard system cursor.
MouseCursor (const MouseCursor &other) noexcept=default
Copy constructor.
MouseCursor (MouseCursor &&other) noexcept=default
Move constructor.
MouseCursor & operator= (const MouseCursor &other) noexcept=default
Copy assignment operator.
MouseCursor & operator= (MouseCursor &&other) noexcept=default
Move assignment operator.
bool operator== (const MouseCursor &other) const noexcept
Checks if two cursors are the same.
bool operator!= (const MouseCursor &other) const noexcept
Checks if two cursors are different.
Type getType () const noexcept
Returns the type of this cursor.
Detailed Description
Represents a mouse cursor image.
This class is used to set the mouse cursor's appearance. You can create a custom cursor from an image, or use one of the standard system cursors.
See also
Component::setMouseCursor, Component::getMouseCursor
Member Enumeration Documentation
Type
enum yup::MouseCursor::Type
The set of available standard system mouse cursors.
See also
MouseCursor::MouseCursor
Enumerator
None
Default
Arrow
Text
Wait
WaitArrow
Hand
Crosshair
Crossbones
ResizeLeftRight
ResizeUpDown
ResizeTopLeftRightBottom
ResizeBottomLeftRightTop
ResizeAll
Constructor & Destructor Documentation
MouseCursor() [1/4]
yup::MouseCursor::MouseCursor () default noexcept
Creates a default mouse cursor (an arrow).
References MouseCursor().
Referenced by MouseCursor(), MouseCursor(), MouseCursor(), operator!=(), operator=(), operator=(), and operator==().
MouseCursor() [2/4]
yup::MouseCursor::MouseCursor (Type newType) noexcept
Creates a standard system cursor.
Parameters
type The type of cursor to create - this can be one of the values from the Type enum.
See also
Type
MouseCursor() [3/4]
yup::MouseCursor::MouseCursor (const MouseCursor & other) default noexcept
Copy constructor.
References MouseCursor().
MouseCursor() [4/4]
yup::MouseCursor::MouseCursor (MouseCursor && other) default noexcept
Move constructor.
References MouseCursor().
Member Function Documentation
operator=() [1/2]
MouseCursor & yup::MouseCursor::operator= (const MouseCursor & other) default noexcept
Copy assignment operator.
References MouseCursor().
operator=() [2/2]
MouseCursor & yup::MouseCursor::operator= (MouseCursor && other) default noexcept
Move assignment operator.
References MouseCursor().
operator==()
bool yup::MouseCursor::operator== (const MouseCursor & other) const noexcept
Checks if two cursors are the same.
Parameters
other The other cursor to compare with
Returns
True if the cursors are identical, false otherwise
References MouseCursor().
operator!=()
bool yup::MouseCursor::operator!= (const MouseCursor & other) const noexcept
Checks if two cursors are different.
Parameters
other The other cursor to compare with
Returns
True if the cursors are different, false if they're identical
References MouseCursor(), and yup::operator==().
getType()
Type yup::MouseCursor::getType () const noexcept
Returns the type of this cursor.
Returns
The cursor's type, as set when it was created.
See also
Type
References getType().
Referenced by getType().