YUP: yup::ColorGradient Class Reference
yup::ColorGradient Class Reference
Represents a gradient for graphical use, defined by two colors and their positions.
Public Types
enum Type : unsigned int { Linear , Radial }
Enumeration for gradient types.
Public Member Functions
ColorGradient () noexcept=default
Default constructor, initializes an empty gradient.
ColorGradient (Color color1, float x1, float y1, Color color2, float x2, float y2, Type type) noexcept
Constructs a gradient with specified attributes.
ColorGradient (const ColorGradient &other)=default
Copy and move constructors and assignment operators.
ColorGradient (ColorGradient &&other)=default
ColorGradient & operator= (const ColorGradient &other)=default
ColorGradient & operator= (ColorGradient &&other)=default
Type getType () const noexcept
Gets the type of the gradient.
Color getStartColor () const
Gets the starting color of the gradient.
float getStartX () const
Gets the x-coordinate of the starting color position.
float getStartY () const
Gets the y-coordinate of the starting color position.
float getStartDelta () const
Gets the relative position of the starting color in the gradient.
Color getFinishColor () const
Gets the ending color of the gradient.
float getFinishX () const
Gets the x-coordinate of the ending color position.
float getFinishY () const
Gets the y-coordinate of the ending color position.
float getFinishDelta () const
Gets the relative position of the ending color in the gradient.
float getRadius () const
Gets the radius of the radial gradient.
void setAlpha (uint8 alpha)
Sets the alpha value for both color stops in the gradient.
void setAlpha (float alpha)
ColorGradient withAlpha (uint8 alpha) const
Creates a new gradient with a specified alpha value for both color stops.
ColorGradient withAlpha (float alpha) const
ColorGradient withMultipliedAlpha (uint8 alpha) const
ColorGradient withMultipliedAlpha (float alpha) const
Detailed Description
Represents a gradient for graphical use, defined by two colors and their positions.
This class encapsulates a gradient, which can be either linear or radial, specified by two color stops. Each stop has a color and a position, and in the case of radial gradients, a radius is calculated.
Member Enumeration Documentation
Type
enum yup::ColorGradient::Type : unsigned int
Enumeration for gradient types.
Enumerator
Linear
A linear gradient transitions smoothly between colors along a straight line.
Radial
A radial gradient transitions smoothly between colors in a circular pattern.
Constructor & Destructor Documentation
ColorGradient() [1/4]
yup::ColorGradient::ColorGradient () default noexcept
Default constructor, initializes an empty gradient.
Constructs a gradient with default values, typically used as a placeholder before setting specific gradient parameters.
Referenced by ColorGradient(), ColorGradient(), ColorGradient(), operator=(), operator=(), withAlpha(), withAlpha(), withMultipliedAlpha(), and withMultipliedAlpha().
ColorGradient() [2/4]
yup::ColorGradient::ColorGradient (Color color1, float x1, float y1, Color color2, float x2, float y2, Type type) noexcept
Constructs a gradient with specified attributes.
Parameters
color1 The starting color of the gradient.
x1 The x-coordinate of the starting color.
y1 The y-coordinate of the starting color.
color2 The ending color of the gradient.
x2 The x-coordinate of the ending color.
y2 The y-coordinate of the ending color.
type The type of gradient (Linear or Radial).
References ColorGradient(), Radial, and yup::square().
ColorGradient() [3/4]
yup::ColorGradient::ColorGradient (const ColorGradient & other) default
Copy and move constructors and assignment operators.
References ColorGradient().
ColorGradient() [4/4]
yup::ColorGradient::ColorGradient (ColorGradient && other) default
References ColorGradient().
Member Function Documentation
operator=() [1/2]
ColorGradient & yup::ColorGradient::operator= (const ColorGradient & other) default
References ColorGradient().
operator=() [2/2]
ColorGradient & yup::ColorGradient::operator= (ColorGradient && other) default
References ColorGradient().
getType()
Type yup::ColorGradient::getType () const noexcept
Gets the type of the gradient.
Returns
The type of the gradient, either Linear or Radial.
getStartColor()
Color yup::ColorGradient::getStartColor () const
Gets the starting color of the gradient.
Returns
The starting color.
getStartX()
float yup::ColorGradient::getStartX () const
Gets the x-coordinate of the starting color position.
Returns
The x-coordinate of the start position.
getStartY()
float yup::ColorGradient::getStartY () const
Gets the y-coordinate of the starting color position.
Returns
The y-coordinate of the start position.
getStartDelta()
float yup::ColorGradient::getStartDelta () const
Gets the relative position of the starting color in the gradient.
Returns
The relative position (delta value) of the start position, typically 0.0f for the start.
getFinishColor()
Color yup::ColorGradient::getFinishColor () const
Gets the ending color of the gradient.
Returns
The ending color.
getFinishX()
float yup::ColorGradient::getFinishX () const
Gets the x-coordinate of the ending color position.
Returns
The x-coordinate of the finish position.
getFinishY()
float yup::ColorGradient::getFinishY () const
Gets the y-coordinate of the ending color position.
Returns
The y-coordinate of the finish position.
getFinishDelta()
float yup::ColorGradient::getFinishDelta () const
Gets the relative position of the ending color in the gradient.
Returns
The relative position (delta value) of the finish position, typically 1.0f for the end.
getRadius()
float yup::ColorGradient::getRadius () const
Gets the radius of the radial gradient.
This value is only relevant for radial gradients and represents the distance from the start to the finish position.
Returns
The radius of the radial gradient.
setAlpha() [1/2]
void yup::ColorGradient::setAlpha (uint8 alpha)
Sets the alpha value for both color stops in the gradient.
Parameters
alpha The alpha value to set, affecting the transparency of the entire gradient.
Referenced by withAlpha(), and withAlpha().
setAlpha() [2/2]
void yup::ColorGradient::setAlpha (float alpha)
withAlpha() [1/2]
ColorGradient yup::ColorGradient::withAlpha (uint8 alpha) const
Creates a new gradient with a specified alpha value for both color stops.
This method allows you to create a new gradient identical to the current one but with a different transparency level.
Parameters
alpha The alpha value for the new gradient.
Returns
A new ColorGradient object with the specified alpha value.
References ColorGradient(), and setAlpha().
withAlpha() [2/2]
ColorGradient yup::ColorGradient::withAlpha (float alpha) const
References ColorGradient(), and setAlpha().
withMultipliedAlpha() [1/2]
ColorGradient yup::ColorGradient::withMultipliedAlpha (uint8 alpha) const
References ColorGradient(), and yup::Color::withMultipliedAlpha().
withMultipliedAlpha() [2/2]
ColorGradient yup::ColorGradient::withMultipliedAlpha (float alpha) const
References ColorGradient(), and yup::Color::withMultipliedAlpha().