YUP: yup::Component::BailOutChecker Class Reference
yup::Component::BailOutChecker Class Reference
A bail out checker for the component.
Public Member Functions
BailOutChecker (Component *component)
Constructor for the BailOutChecker class.
BailOutChecker (const BailOutChecker &other)=default
Copy and move constructors and assignment operators for the BailOutChecker class.
BailOutChecker (BailOutChecker &&other)=default
BailOutChecker & operator= (const BailOutChecker &other)=default
BailOutChecker & operator= (BailOutChecker &&other)=default
bool shouldBailOut () const
Check if the component should bail out.
Detailed Description
A bail out checker for the component.
Constructor & Destructor Documentation
BailOutChecker() [1/3]
yup::Component::BailOutChecker::BailOutChecker (Component * component) explicit
Constructor for the BailOutChecker class.
Parameters
component The component to check.
References yup::Component::Component().
Referenced by BailOutChecker(), BailOutChecker(), operator=(), and operator=().
BailOutChecker() [2/3]
yup::Component::BailOutChecker::BailOutChecker (const BailOutChecker & other) default
Copy and move constructors and assignment operators for the BailOutChecker class.
References BailOutChecker().
BailOutChecker() [3/3]
yup::Component::BailOutChecker::BailOutChecker (BailOutChecker && other) default
References BailOutChecker().
Member Function Documentation
operator=() [1/2]
BailOutChecker & yup::Component::BailOutChecker::operator= (const BailOutChecker & other) default
References BailOutChecker().
operator=() [2/2]
BailOutChecker & yup::Component::BailOutChecker::operator= (BailOutChecker && other) default
References BailOutChecker().
shouldBailOut()
bool yup::Component::BailOutChecker::shouldBailOut () const
Check if the component should bail out.
Returns
True if the component should bail out, false otherwise.