YUP: yup::SpinLock Class Reference
yup::SpinLock Class Reference
A simple spin-lock class that can be used as a simple, low-overhead mutex for uncontended situations.
Public Types
using ScopedLockType = GenericScopedLock<SpinLock>
Provides the type of scoped lock to use for locking a SpinLock.
using ScopedUnlockType = GenericScopedUnlock<SpinLock>
Provides the type of scoped unlocker to use with a SpinLock.
using ScopedTryLockType = GenericScopedTryLock<SpinLock>
Provides the type of scoped try-lock to use for locking a SpinLock.
Public Member Functions
SpinLock ()=default
~SpinLock ()=default
void enter () const noexcept
Acquires the lock.
bool tryEnter () const noexcept
Attempts to acquire the lock, returning true if this was successful.
void exit () const noexcept
Releases the lock.
Detailed Description
A simple spin-lock class that can be used as a simple, low-overhead mutex for uncontended situations.
Note that unlike a CriticalSection, this type of lock is not re-entrant, and may be less efficient when used in a highly contended situation, but it's very small and requires almost no initialisation. It's most appropriate for simple situations where you're only going to hold the lock for a very brief time.
See also
CriticalSection
Member Typedef Documentation
ScopedLockType
using yup::SpinLock::ScopedLockType = GenericScopedLock<SpinLock>
Provides the type of scoped lock to use for locking a SpinLock.
ScopedUnlockType
using yup::SpinLock::ScopedUnlockType = GenericScopedUnlock<SpinLock>
Provides the type of scoped unlocker to use with a SpinLock.
ScopedTryLockType
using yup::SpinLock::ScopedTryLockType = GenericScopedTryLock<SpinLock>
Provides the type of scoped try-lock to use for locking a SpinLock.
Constructor & Destructor Documentation
SpinLock()
yup::SpinLock::SpinLock () default
~SpinLock()
yup::SpinLock::~SpinLock () default
References enter().
Member Function Documentation
enter()
void yup::SpinLock::enter () const noexcept
Acquires the lock.
This will block until the lock has been successfully acquired by this thread. Note that a SpinLock is NOT re-entrant, and is not smart enough to know whether the caller thread already has the lock - so if a thread tries to acquire a lock that it already holds, this method will never return!
It's strongly recommended that you never call this method directly - instead use the ScopedLockType class to manage the locking using an RAII pattern instead.
References tryEnter(), and yup::Thread::yield().
Referenced by ~SpinLock().
tryEnter()
bool yup::SpinLock::tryEnter () const noexcept
Attempts to acquire the lock, returning true if this was successful.
References tryEnter().
Referenced by enter(), and tryEnter().
exit()
void yup::SpinLock::exit () const noexcept
Releases the lock.