YUP: yup::AudioParameterHandle Class Reference
yup::AudioParameterHandle Class Reference
A handle for a parameter of an AudioProcessor.
Public Member Functions
AudioParameterHandle ()=default
Constructs a new AudioParameterHandle.
AudioParameterHandle (AudioParameter &parameter, double sampleRate)
Constructs a new AudioParameterHandle.
AudioParameterHandle (const AudioParameterHandle &other)=default
Constructs a new AudioParameterHandle.
AudioParameterHandle & operator= (const AudioParameterHandle &other)=default
Constructs a new AudioParameterHandle.
~AudioParameterHandle ()=default
Destructs the AudioParameterHandle.
forcedinline bool updateNextAudioBlock () noexcept
Updates the smoothed value of the parameter.
forcedinline float getNextValue () noexcept
Returns the next value of the parameter.
forcedinline float getCurrentValue () const noexcept
Returns the current value of the parameter.
forcedinline float skip (int numSamples) noexcept
Skips the next numSamples samples of the parameter.
Detailed Description
A handle for a parameter of an AudioProcessor.
This class provides a way to access and modify the value of a parameter of an AudioProcessor. It also provides a way to smooth the value of the parameter.
See also
AudioParameter
Constructor & Destructor Documentation
AudioParameterHandle() [1/3]
yup::AudioParameterHandle::AudioParameterHandle () default
Constructs a new AudioParameterHandle.
Referenced by AudioParameterHandle(), and operator=().
AudioParameterHandle() [2/3]
yup::AudioParameterHandle::AudioParameterHandle (AudioParameter & parameter, double sampleRate)
Constructs a new AudioParameterHandle.
AudioParameterHandle() [3/3]
yup::AudioParameterHandle::AudioParameterHandle (const AudioParameterHandle & other) default
Constructs a new AudioParameterHandle.
References AudioParameterHandle().
~AudioParameterHandle()
yup::AudioParameterHandle::~AudioParameterHandle () default
Destructs the AudioParameterHandle.
Member Function Documentation
operator=()
AudioParameterHandle & yup::AudioParameterHandle::operator= (const AudioParameterHandle & other) default
Constructs a new AudioParameterHandle.
References AudioParameterHandle().
updateNextAudioBlock()
forcedinline bool yup::AudioParameterHandle::updateNextAudioBlock () noexcept
Updates the smoothed value of the parameter.
This must be called on the audio thread once per audio block.
Returns
true if the parameter is currently being smoothed, false otherwise.
getNextValue()
forcedinline float yup::AudioParameterHandle::getNextValue () noexcept
Returns the next value of the parameter.
getCurrentValue()
forcedinline float yup::AudioParameterHandle::getCurrentValue () const noexcept
Returns the current value of the parameter.
skip()
forcedinline float yup::AudioParameterHandle::skip (int numSamples) noexcept
Skips the next numSamples samples of the parameter.
This is identical to calling getNextValue numSamples times.
Parameters
numSamples The number of samples to skip.
Returns
The current value of the parameter after skipping the samples.