YUP: yup::SynthesiserVoice Class Reference
yup::SynthesiserVoice Class Reference abstract
Represents a voice that a Synthesiser can use to play a SynthesiserSound.
Public Member Functions
SynthesiserVoice ()
Creates a voice.
virtual ~SynthesiserVoice ()
Destructor.
int getCurrentlyPlayingNote () const noexcept
Returns the midi note that this voice is currently playing.
SynthesiserSound::Ptr getCurrentlyPlayingSound () const noexcept
Returns the sound that this voice is currently playing.
virtual bool canPlaySound (SynthesiserSound *)=0
Must return true if this voice object is capable of playing the given sound.
virtual void startNote (int midiNoteNumber, float velocity, SynthesiserSound *sound, int currentPitchWheelPosition)=0
Called to start a new note.
virtual void stopNote (float velocity, bool allowTailOff)=0
Called to stop a note.
virtual bool isVoiceActive () const
Returns true if this voice is currently busy playing a sound.
virtual void pitchWheelMoved (int newPitchWheelValue)=0
Called to let the voice know that the pitch wheel has been moved.
virtual void controllerMoved (int controllerNumber, int newControllerValue)=0
Called to let the voice know that a midi controller has been moved.
virtual void aftertouchChanged (int newAftertouchValue)
Called to let the voice know that the aftertouch has changed.
virtual void channelPressureChanged (int newChannelPressureValue)
Called to let the voice know that the channel pressure has changed.
virtual void renderNextBlock (AudioBuffer< float > &outputBuffer, int startSample, int numSamples)=0
Renders the next block of data for this voice.
virtual void renderNextBlock (AudioBuffer< double > &outputBuffer, int startSample, int numSamples)
A double-precision version of renderNextBlock()
virtual void setCurrentPlaybackSampleRate (double newRate)
Changes the voice's reference sample rate.
virtual bool isPlayingChannel (int midiChannel) const
Returns true if the voice is currently playing a sound which is mapped to the given midi channel.
double getSampleRate () const noexcept
Returns the current target sample rate at which rendering is being done.
bool isKeyDown () const noexcept
Returns true if the key that triggered this voice is still held down.
void setKeyDown (bool isNowDown) noexcept
Allows you to modify the flag indicating that the key that triggered this voice is still held down.
bool isSustainPedalDown () const noexcept
Returns true if the sustain pedal is currently active for this voice.
void setSustainPedalDown (bool isNowDown) noexcept
Modifies the sustain pedal flag.
bool isSostenutoPedalDown () const noexcept
Returns true if the sostenuto pedal is currently active for this voice.
void setSostenutoPedalDown (bool isNowDown) noexcept
Modifies the sostenuto pedal flag.
bool isPlayingButReleased () const noexcept
Returns true if a voice is sounding in its release phase.
bool wasStartedBefore (const SynthesiserVoice &other) const noexcept
Returns true if this voice started playing its current note before the other voice did.
Protected Member Functions
void clearCurrentNote ()
Resets the state of this voice after a sound has finished playing.
Detailed Description
Represents a voice that a Synthesiser can use to play a SynthesiserSound.
A voice plays a single sound at a time, and a synthesiser holds an array of voices so that it can play polyphonically.
See also
Synthesiser, SynthesiserSound
Constructor & Destructor Documentation
SynthesiserVoice()
yup::SynthesiserVoice::SynthesiserVoice ()
Creates a voice.
Referenced by Synthesiser, and wasStartedBefore().
~SynthesiserVoice()
yup::SynthesiserVoice::~SynthesiserVoice () virtual
Destructor.
Member Function Documentation
getCurrentlyPlayingNote()
int yup::SynthesiserVoice::getCurrentlyPlayingNote () const noexcept
Returns the midi note that this voice is currently playing.
Returns a value less than 0 if no note is playing.
Referenced by yup::Synthesiser::findVoiceToSteal(), isVoiceActive(), and yup::Synthesiser::stopVoice().
getCurrentlyPlayingSound()
SynthesiserSound::Ptr yup::SynthesiserVoice::getCurrentlyPlayingSound () const noexcept
Returns the sound that this voice is currently playing.
Returns nullptr if it's not playing.
Referenced by yup::Synthesiser::stopVoice().
canPlaySound()
virtual bool yup::SynthesiserVoice::canPlaySound (SynthesiserSound *) pure virtual
Must return true if this voice object is capable of playing the given sound.
If there are different classes of sound, and different classes of voice, a voice can choose which ones it wants to take on.
A typical implementation of this method may just return true if there's only one type of voice and sound, or it might check the type of the sound object passed-in and see if it's one that it understands.
startNote()
virtual void yup::SynthesiserVoice::startNote (int midiNoteNumber, float velocity, SynthesiserSound * sound, int currentPitchWheelPosition) pure virtual
Called to start a new note.
This will be called during the rendering callback, so must be fast and thread-safe.
Referenced by yup::Synthesiser::startVoice().
stopNote()
virtual void yup::SynthesiserVoice::stopNote (float velocity, bool allowTailOff) pure virtual
Called to stop a note.
This will be called during the rendering callback, so must be fast and thread-safe.
The velocity indicates how quickly the note was released - 0 is slowly, 1 is quickly.
If allowTailOff is false or the voice doesn't want to tail-off, then it must stop all sound immediately, and must call clearCurrentNote() to reset the state of this voice and allow the synth to reassign it another sound.
If allowTailOff is true and the voice decides to do a tail-off, then it's allowed to begin fading out its sound, and it can stop playing until it's finished. As soon as it finishes playing (during the rendering callback), it must make sure that it calls clearCurrentNote().
References isVoiceActive().
Referenced by yup::Synthesiser::startVoice(), and yup::Synthesiser::stopVoice().
isVoiceActive()
bool yup::SynthesiserVoice::isVoiceActive () const virtual
Returns true if this voice is currently busy playing a sound.
By default this just checks the getCurrentlyPlayingNote() value, but can be overridden for more advanced checking.
References getCurrentlyPlayingNote().
Referenced by isPlayingButReleased(), and stopNote().
pitchWheelMoved()
virtual void yup::SynthesiserVoice::pitchWheelMoved (int newPitchWheelValue) pure virtual
Called to let the voice know that the pitch wheel has been moved.
This will be called during the rendering callback, so must be fast and thread-safe.
controllerMoved()
virtual void yup::SynthesiserVoice::controllerMoved (int controllerNumber, int newControllerValue) pure virtual
Called to let the voice know that a midi controller has been moved.
This will be called during the rendering callback, so must be fast and thread-safe.
References aftertouchChanged(), and channelPressureChanged().
aftertouchChanged()
void yup::SynthesiserVoice::aftertouchChanged (int newAftertouchValue) virtual
Called to let the voice know that the aftertouch has changed.
This will be called during the rendering callback, so must be fast and thread-safe.
Referenced by controllerMoved().
channelPressureChanged()
void yup::SynthesiserVoice::channelPressureChanged (int newChannelPressureValue) virtual
Called to let the voice know that the channel pressure has changed.
This will be called during the rendering callback, so must be fast and thread-safe.
Referenced by controllerMoved().
renderNextBlock() [1/2]
virtual void yup::SynthesiserVoice::renderNextBlock (AudioBuffer< float > & outputBuffer, int startSample, int numSamples) pure virtual
Renders the next block of data for this voice.
The output audio data must be added to the current contents of the buffer provided. Only the region of the buffer between startSample and (startSample + numSamples) should be altered by this method.
If the voice is currently silent, it should just return without doing anything.
If the sound that the voice is playing finishes during the course of this rendered block, it must call clearCurrentNote(), to tell the synthesiser that it has finished.
The size of the blocks that are rendered can change each time it is called, and may involve rendering as little as 1 sample at a time. In between rendering callbacks, the voice's methods will be called to tell it about note and controller events.
References isPlayingChannel(), renderNextBlock(), and setCurrentPlaybackSampleRate().
Referenced by renderNextBlock(), and renderNextBlock().
renderNextBlock() [2/2]
void yup::SynthesiserVoice::renderNextBlock (AudioBuffer< double > & outputBuffer, int startSample, int numSamples) virtual
A double-precision version of renderNextBlock()
References yup::AudioBuffer< Type >::getArrayOfWritePointers(), yup::AudioBuffer< Type >::getNumChannels(), yup::AudioBuffer< Type >::makeCopyOf(), and renderNextBlock().
setCurrentPlaybackSampleRate()
void yup::SynthesiserVoice::setCurrentPlaybackSampleRate (double newRate) virtual
Changes the voice's reference sample rate.
The rate is set so that subclasses know the output rate and can set their pitch accordingly.
This method is called by the synth, and subclasses can access the current rate with the currentSampleRate member.
Referenced by yup::Synthesiser::addVoice(), and renderNextBlock().
isPlayingChannel()
bool yup::SynthesiserVoice::isPlayingChannel (int midiChannel) const virtual
Returns true if the voice is currently playing a sound which is mapped to the given midi channel.
If it's not currently playing, this will return false.
Referenced by renderNextBlock().
getSampleRate()
double yup::SynthesiserVoice::getSampleRate () const noexcept
Returns the current target sample rate at which rendering is being done.
Subclasses may need to know this so that they can pitch things correctly.
isKeyDown()
bool yup::SynthesiserVoice::isKeyDown () const noexcept
Returns true if the key that triggered this voice is still held down.
Note that the voice may still be playing after the key was released (e.g because the sostenuto pedal is down).
Referenced by yup::Synthesiser::findVoiceToSteal(), and isPlayingButReleased().
setKeyDown()
void yup::SynthesiserVoice::setKeyDown (bool isNowDown) noexcept
Allows you to modify the flag indicating that the key that triggered this voice is still held down.
See also
isKeyDown
Referenced by yup::Synthesiser::startVoice().
isSustainPedalDown()
bool yup::SynthesiserVoice::isSustainPedalDown () const noexcept
Returns true if the sustain pedal is currently active for this voice.
Referenced by isPlayingButReleased().
setSustainPedalDown()
void yup::SynthesiserVoice::setSustainPedalDown (bool isNowDown) noexcept
Modifies the sustain pedal flag.
Referenced by yup::Synthesiser::startVoice().
isSostenutoPedalDown()
bool yup::SynthesiserVoice::isSostenutoPedalDown () const noexcept
Returns true if the sostenuto pedal is currently active for this voice.
Referenced by isPlayingButReleased().
setSostenutoPedalDown()
void yup::SynthesiserVoice::setSostenutoPedalDown (bool isNowDown) noexcept
Modifies the sostenuto pedal flag.
Referenced by yup::Synthesiser::startVoice().
isPlayingButReleased()
bool yup::SynthesiserVoice::isPlayingButReleased () const noexcept
Returns true if a voice is sounding in its release phase.
References isKeyDown(), isSostenutoPedalDown(), isSustainPedalDown(), and isVoiceActive().
Referenced by yup::Synthesiser::findVoiceToSteal().
wasStartedBefore()
bool yup::SynthesiserVoice::wasStartedBefore (const SynthesiserVoice & other) const noexcept
Returns true if this voice started playing its current note before the other voice did.
References SynthesiserVoice().
Referenced by yup::Synthesiser::findVoiceToSteal().
clearCurrentNote()
void yup::SynthesiserVoice::clearCurrentNote () protected
Resets the state of this voice after a sound has finished playing.
The subclass must call this when it finishes playing a note and becomes available to play new ones.
It must either call it in the stopNote() method, or if the voice is tailing off, then it should call it later during the renderNextBlock method, as soon as it finishes its tail-off.
It can also be called at any time during the render callback if the sound happens to have finished, e.g. if it's playing a sample and the sample finishes.