YUP: yup::MidiRPNGenerator Class Reference
yup::MidiRPNGenerator Class Reference
Generates an appropriate sequence of MIDI CC messages to represent an RPN or NRPN message.
Static Public Member Functions
static MidiBuffer generate (MidiRPNMessage message)
Generates a MIDI sequence representing the given RPN or NRPN message.
static MidiBuffer generate (int channel, int parameterNumber, int value, bool isNRPN=false, bool use14BitValue=true)
Generates a MIDI sequence representing an RPN or NRPN message with the given parameters.
Detailed Description
Generates an appropriate sequence of MIDI CC messages to represent an RPN or NRPN message.
This sequence (as a MidiBuffer) can then be directly sent to a MidiOutput.
Member Function Documentation
generate() [1/2]
MidiBuffer yup::MidiRPNGenerator::generate (MidiRPNMessage message) static
Generates a MIDI sequence representing the given RPN or NRPN message.
References yup::MidiRPNMessage::channel, generate(), yup::MidiRPNMessage::is14BitValue, yup::MidiRPNMessage::isNRPN, yup::MidiRPNMessage::parameterNumber, and yup::MidiRPNMessage::value.
Referenced by yup::MPEMessages::clearLowerZone(), yup::MPEMessages::clearUpperZone(), generate(), yup::MPEMessages::setLowerZone(), yup::MPEMessages::setLowerZoneMasterPitchbendRange(), yup::MPEMessages::setLowerZonePerNotePitchbendRange(), yup::MPEMessages::setUpperZone(), yup::MPEMessages::setUpperZoneMasterPitchbendRange(), and yup::MPEMessages::setUpperZonePerNotePitchbendRange().
generate() [2/2]
MidiBuffer yup::MidiRPNGenerator::generate (int channel, int parameterNumber, int value, bool isNRPN = false, bool use14BitValue = true) static
Generates a MIDI sequence representing an RPN or NRPN message with the given parameters.
Parameters
channel The MIDI channel of the RPN/NRPN message.
parameterNumber The parameter number, in the range 0 to 16383.
value The parameter value, in the range 0 to 16383, or in the range 0 to 127 if sendAs14BitValue is false.
isNRPN Whether you need a MIDI RPN or NRPN sequence (RPN is default).
use14BitValue If true (default), the value will have 14-bit precision (two MIDI bytes). If false, instead the value will have 7-bit precision (a single MIDI byte).
References yup::MidiBuffer::addEvent().