YUP: yup::Reverb Class Reference
yup::Reverb Class Reference
Performs a simple reverb effect on a stream of audio data.
Classes
struct Parameters
Holds the parameters being used by a Reverb object.
Public Member Functions
Reverb ()
const Parameters & getParameters () const noexcept
Returns the reverb's current parameters.
void setParameters (const Parameters &newParams)
Applies a new set of parameters to the reverb.
void setSampleRate (const double sampleRate)
Sets the sample rate that will be used for the reverb.
void reset ()
Clears the reverb's buffers.
void processStereo (float *const left, float *const right, const int numSamples) noexcept
Applies the reverb to two stereo channels of audio data.
void processMono (float *const samples, const int numSamples) noexcept
Applies the reverb to a single mono channel of audio data.
Detailed Description
Performs a simple reverb effect on a stream of audio data.
This is a simple stereo reverb, based on the technique and tunings used in FreeVerb. Use setSampleRate() to prepare it, and then call processStereo() or processMono() to apply the reverb to your audio data.
See also
ReverbAudioSource
Constructor & Destructor Documentation
Reverb()
yup::Reverb::Reverb ()
References setParameters(), and setSampleRate().
Member Function Documentation
getParameters()
const Parameters & yup::Reverb::getParameters () const noexcept
Returns the reverb's current parameters.
setParameters()
void yup::Reverb::setParameters (const Parameters & newParams)
Applies a new set of parameters to the reverb.
Note that this doesn't attempt to lock the reverb, so if you call this in parallel with the process method, you may get artifacts.
References yup::Reverb::Parameters::dryLevel, yup::Reverb::Parameters::freezeMode, yup::Reverb::Parameters::wetLevel, and yup::Reverb::Parameters::width.
Referenced by Reverb().
setSampleRate()
void yup::Reverb::setSampleRate (const double sampleRate)
Sets the sample rate that will be used for the reverb.
You must call this before the process methods, in order to tell it the correct sample rate.
Referenced by Reverb().
reset()
void yup::Reverb::reset ()
Clears the reverb's buffers.
processStereo()
void yup::Reverb::processStereo (float *const left, float *const right, const int numSamples) noexcept
Applies the reverb to two stereo channels of audio data.
processMono()
void yup::Reverb::processMono (float *const samples, const int numSamples) noexcept
Applies the reverb to a single mono channel of audio data.