YUP: yup::MouseEvent Class Reference
yup::MouseEvent Class Reference
Contains information about a mouse event.
Public Types
enum Buttons {
noButtons = 0x0000 , leftButton = 0x0001 , middleButton = 0x0002 , rightButton = 0x0004 ,
allButtons = leftButton | middleButton | rightButton
}
Constants to indicate which mouse buttons are being held down.
Public Member Functions
MouseEvent () noexcept=default
Creates a default MouseEvent object.
MouseEvent (Buttons newButtons, KeyModifiers newModifiers, const Point< float > &newPosition) noexcept
Creates a MouseEvent object.
MouseEvent (Buttons newButtons, KeyModifiers newModifiers, const Point< float > &newPosition, Component *sourceComponent) noexcept
Creates a MouseEvent object.
MouseEvent (const MouseEvent &other) noexcept=default
Copy constructor.
MouseEvent (MouseEvent &&other) noexcept=default
Move constructor.
MouseEvent & operator= (const MouseEvent &other) noexcept=default
Copy assignment operator.
MouseEvent & operator= (MouseEvent &&other) noexcept=default
Move assignment operator.
bool isLeftButtoDown () const noexcept
Returns true if the left mouse button is currently held down.
bool isMiddleButtonDown () const noexcept
Returns true if the middle mouse button is currently held down.
bool isRightButtonDown () const noexcept
Returns true if the right mouse button is currently held down.
bool isAnyButtonDown () const noexcept
Returns true if any mouse button is currently held down.
Buttons getButtons () const noexcept
Returns the current mouse button state.
MouseEvent withButtons (Buttons buttonsToAdd) const noexcept
Creates a copy of this event with the specified buttons added.
MouseEvent withoutButtons (Buttons buttonsToRemove) const noexcept
Creates a copy of this event with the specified buttons removed.
KeyModifiers getModifiers () const noexcept
Returns the key modifiers associated with this mouse event.
MouseEvent withModifiers (KeyModifiers newModifiers) const noexcept
Creates a copy of this event with different modifiers.
Point< float > getPosition () const noexcept
Returns the mouse position associated with this event.
MouseEvent withPosition (const Point< float > &newPosition) const noexcept
Creates a copy of this event with a different position.
MouseEvent withTranslatedPosition (const Point< float > &translation) const noexcept
Creates a copy of this event with its position offset by the specified amount.
MouseEvent withRelativePositionTo (Component *targetComponent) const noexcept
Creates a copy of this event with its position relative to the specified component.
Point< float > getLastMouseDownPosition () const noexcept
Returns the position at which the last mouse-down event occurred.
MouseEvent withLastMouseDownPosition (const Point< float > &newPosition) const noexcept
Creates a copy of this event with a different last mouse-down position.
yup::Time getLastMouseDownTime () const noexcept
Returns the time at which the last mouse-down event occurred.
MouseEvent withLastMouseDownTime (yup::Time newTime) const noexcept
Creates a copy of this event with a different last mouse-down time.
Component * getSourceComponent () const noexcept
Returns the component that this event applies to.
MouseEvent withSourceComponent (Component *newComponent) const noexcept
Creates a copy of this event with a different source component.
bool operator== (const MouseEvent &other) const noexcept
Compares two MouseEvent objects.
bool operator!= (const MouseEvent &other) const noexcept
Compares two MouseEvent objects.
Detailed Description
Contains information about a mouse event.
This class is used to represent mouse events such as clicks, moves, drags, etc. It contains information about the mouse state, position, and which component the event occurred on.
A MouseEvent object is passed to a component's mouse event methods, where you can query its properties to find out what the user is doing.
See also
Component::mouseMove, Component::mouseEnter, Component::mouseExit, Component::mouseDown, Component::mouseUp, Component::mouseDrag
Member Enumeration Documentation
Buttons
enum yup::MouseEvent::Buttons
Constants to indicate which mouse buttons are being held down.
See also
getButtons, isLeftButtonDown, isRightButtonDown, isMiddleButtonDown
Enumerator
noButtons
No buttons pressed.
leftButton
The left mouse button.
middleButton
The middle mouse button.
rightButton
The right mouse button.
allButtons
Bitmask of all buttons.
Constructor & Destructor Documentation
MouseEvent() [1/5]
yup::MouseEvent::MouseEvent () default noexcept
Creates a default MouseEvent object.
This creates an event describing a mouse movement to position (0, 0), with no buttons pressed and no key modifiers.
References MouseEvent().
Referenced by MouseEvent(), MouseEvent(), MouseEvent(), MouseEvent(), operator!=(), operator=(), operator=(), operator==(), withButtons(), withLastMouseDownPosition(), withLastMouseDownTime(), withModifiers(), withoutButtons(), withPosition(), withRelativePositionTo(), withSourceComponent(), and withTranslatedPosition().
MouseEvent() [2/5]
yup::MouseEvent::MouseEvent (Buttons newButtons, KeyModifiers newModifiers, const Point< float > & newPosition) noexcept
Creates a MouseEvent object.
Parameters
newButtons The buttons that are currently held down
newModifiers The key modifiers that are currently active
newPosition The mouse position, relative to the component that receives the event
References MouseEvent().
MouseEvent() [3/5]
yup::MouseEvent::MouseEvent (Buttons newButtons, KeyModifiers newModifiers, const Point< float > & newPosition, Component * sourceComponent) noexcept
Creates a MouseEvent object.
Parameters
newButtons The buttons that are currently held down
newModifiers The key modifiers that are currently active
newPosition The mouse position, relative to the component that receives the event
sourceComponent The component that the mouse event applies to
MouseEvent() [4/5]
yup::MouseEvent::MouseEvent (const MouseEvent & other) default noexcept
Copy constructor.
References MouseEvent().
MouseEvent() [5/5]
yup::MouseEvent::MouseEvent (MouseEvent && other) default noexcept
Move constructor.
References MouseEvent().
Member Function Documentation
operator=() [1/2]
MouseEvent & yup::MouseEvent::operator= (const MouseEvent & other) default noexcept
Copy assignment operator.
References MouseEvent().
operator=() [2/2]
MouseEvent & yup::MouseEvent::operator= (MouseEvent && other) default noexcept
Move assignment operator.
References getButtons(), getLastMouseDownPosition(), getLastMouseDownTime(), getModifiers(), getPosition(), getSourceComponent(), isAnyButtonDown(), isLeftButtoDown(), isMiddleButtonDown(), isRightButtonDown(), MouseEvent(), noButtons, withButtons(), withLastMouseDownPosition(), withLastMouseDownTime(), withModifiers(), withoutButtons(), withPosition(), withRelativePositionTo(), withSourceComponent(), and withTranslatedPosition().
isLeftButtoDown()
bool yup::MouseEvent::isLeftButtoDown () const noexcept
Returns true if the left mouse button is currently held down.
Returns
true if the left button is down
References leftButton.
Referenced by yup::Artboard::mouseDown(), yup::Artboard::mouseDrag(), and operator=().
isMiddleButtonDown()
bool yup::MouseEvent::isMiddleButtonDown () const noexcept
Returns true if the middle mouse button is currently held down.
Returns
true if the middle button is down
References middleButton.
Referenced by operator=().
isRightButtonDown()
bool yup::MouseEvent::isRightButtonDown () const noexcept
Returns true if the right mouse button is currently held down.
Returns
true if the right button is down
References rightButton.
Referenced by yup::Slider::mouseDrag(), and operator=().
isAnyButtonDown()
bool yup::MouseEvent::isAnyButtonDown () const noexcept
Returns true if any mouse button is currently held down.
Returns
true if any button is down
References allButtons.
Referenced by yup::Slider::mouseUp(), and operator=().
getButtons()
MouseEvent::Buttons yup::MouseEvent::getButtons () const noexcept
Returns the current mouse button state.
Returns
a bitmask of the buttons that are currently held down
See also
Buttons
Referenced by operator=().
withButtons()
MouseEvent yup::MouseEvent::withButtons (Buttons buttonsToAdd) const noexcept
Creates a copy of this event with the specified buttons added.
Parameters
buttonsToAdd the buttons to add to the new event
Returns
a new MouseEvent object
References MouseEvent().
Referenced by operator=().
withoutButtons()
MouseEvent yup::MouseEvent::withoutButtons (Buttons buttonsToRemove) const noexcept
Creates a copy of this event with the specified buttons removed.
Parameters
buttonsToRemove the buttons to remove from the new event
Returns
a new MouseEvent object
References MouseEvent().
Referenced by operator=().
getModifiers()
KeyModifiers yup::MouseEvent::getModifiers () const noexcept
Returns the key modifiers associated with this mouse event.
Returns
the key modifiers currently active
Referenced by yup::TextEditor::mouseDown(), and operator=().
withModifiers()
MouseEvent yup::MouseEvent::withModifiers (KeyModifiers newModifiers) const noexcept
Creates a copy of this event with different modifiers.
Parameters
newModifiers the new modifier flags to use
Returns
a new MouseEvent object
References MouseEvent().
Referenced by operator=().
getPosition()
Point< float > yup::MouseEvent::getPosition () const noexcept
Returns the mouse position associated with this event.
Returns
the mouse position, relative to the component that received the event
Referenced by yup::Artboard::mouseDown(), yup::Artboard::mouseDrag(), yup::Slider::mouseDrag(), yup::Artboard::mouseEnter(), yup::Artboard::mouseExit(), yup::Artboard::mouseMove(), yup::Artboard::mouseUp(), and operator=().
withPosition()
MouseEvent yup::MouseEvent::withPosition (const Point< float > & newPosition) const noexcept
Creates a copy of this event with a different position.
Parameters
newPosition the new position to use
Returns
a new MouseEvent object
References MouseEvent().
Referenced by operator=().
withTranslatedPosition()
MouseEvent yup::MouseEvent::withTranslatedPosition (const Point< float > & translation) const noexcept
Creates a copy of this event with its position offset by the specified amount.
Parameters
translation the offset to apply to the position
Returns
a new MouseEvent object
References MouseEvent().
Referenced by operator=().
withRelativePositionTo()
MouseEvent yup::MouseEvent::withRelativePositionTo (Component * targetComponent) const noexcept
Creates a copy of this event with its position relative to the specified component.
This is used internally by the component system to ensure that mouse events are delivered with coordinates relative to the receiving component.
Parameters
targetComponent the component to make the position relative to
Returns
a new MouseEvent object with position relative to the target component
References MouseEvent().
Referenced by operator=().
getLastMouseDownPosition()
Point< float > yup::MouseEvent::getLastMouseDownPosition () const noexcept
Returns the position at which the last mouse-down event occurred.
Returns
the last mouse-down position, relative to the component that received the event
Referenced by operator=().
withLastMouseDownPosition()
MouseEvent yup::MouseEvent::withLastMouseDownPosition (const Point< float > & newPosition) const noexcept
Creates a copy of this event with a different last mouse-down position.
Parameters
newPosition the new last mouse-down position to use
Returns
a new MouseEvent object
References MouseEvent().
Referenced by operator=().
getLastMouseDownTime()
yup::Time yup::MouseEvent::getLastMouseDownTime () const noexcept
Returns the time at which the last mouse-down event occurred.
Returns
the time of the last mouse-down event
Referenced by operator=().
withLastMouseDownTime()
MouseEvent yup::MouseEvent::withLastMouseDownTime (yup::Time newTime) const noexcept
Creates a copy of this event with a different last mouse-down time.
Parameters
newTime the new time to use
Returns
a new MouseEvent object
References MouseEvent().
Referenced by operator=().
getSourceComponent()
Component * yup::MouseEvent::getSourceComponent () const noexcept
Returns the component that this event applies to.
Returns
the component that the event occurred on
Referenced by operator=().
withSourceComponent()
MouseEvent yup::MouseEvent::withSourceComponent (Component * newComponent) const noexcept
Creates a copy of this event with a different source component.
Parameters
newComponent the new component to use as the source
Returns
a new MouseEvent object
References MouseEvent().
Referenced by operator=().
operator==()
bool yup::MouseEvent::operator== (const MouseEvent & other) const noexcept
Compares two MouseEvent objects.
Parameters
other the other event to compare with
Returns
true if the events are identical
References MouseEvent().
operator!=()
bool yup::MouseEvent::operator!= (const MouseEvent & other) const noexcept
Compares two MouseEvent objects.
Parameters
other the other event to compare with
Returns
true if the events are different
References MouseEvent().