YUP: yup::CharacterFunctions Class Reference
yup::CharacterFunctions Class Reference
A collection of functions for manipulating characters and character strings.
Classes
struct HexParser
Parses a character string, to read a hexadecimal value.
Static Public Member Functions
static yup_wchar toUpperCase (yup_wchar character) noexcept
Converts a character to upper-case.
static yup_wchar toLowerCase (yup_wchar character) noexcept
Converts a character to lower-case.
static bool isUpperCase (yup_wchar character) noexcept
Checks whether a unicode character is upper-case.
static bool isLowerCase (yup_wchar character) noexcept
Checks whether a unicode character is lower-case.
static bool isWhitespace (char character) noexcept
Checks whether a character is whitespace.
static bool isWhitespace (yup_wchar character) noexcept
Checks whether a character is whitespace.
static bool isDigit (char character) noexcept
Checks whether a character is a digit.
static bool isDigit (yup_wchar character) noexcept
Checks whether a character is a digit.
static bool isLetter (char character) noexcept
Checks whether a character is alphabetic.
static bool isLetter (yup_wchar character) noexcept
Checks whether a character is alphabetic.
static bool isLetterOrDigit (char character) noexcept
Checks whether a character is alphabetic or numeric.
static bool isLetterOrDigit (yup_wchar character) noexcept
Checks whether a character is alphabetic or numeric.
static bool isPrintable (char character) noexcept
Checks whether a character is a printable character, i.e.
static bool isPrintable (yup_wchar character) noexcept
Checks whether a character is a printable character, i.e.
static int getHexDigitValue (yup_wchar digit) noexcept
Returns 0 to 16 for '0' to 'F", or -1 for characters that aren't a legal hex digit.
static yup_wchar getUnicodeCharFromWindows1252Codepage (uint8 windows1252Char) noexcept
Converts a byte of Windows 1252 codepage to unicode.
template<typename CharPointerType>
static double readDoubleValue (CharPointerType &text) noexcept
Parses a character string to read a floating-point number.
template<typename CharPointerType>
static double getDoubleValue (CharPointerType text) noexcept
Parses a character string, to read a floating-point value.
template<typename IntType, typename CharPointerType>
static IntType getIntValue (const CharPointerType text) noexcept
Parses a character string, to read an integer value.
template<typename CharPointerType>
static size_t lengthUpTo (CharPointerType text, const size_t maxCharsToCount) noexcept
Counts the number of characters in a given string, stopping if the count exceeds a specified limit.
template<typename CharPointerType>
static size_t lengthUpTo (CharPointerType start, const CharPointerType end) noexcept
Counts the number of characters in a given string, stopping if the count exceeds a specified end-pointer.
template<typename DestCharPointerType, typename SrcCharPointerType>
static void copyAll (DestCharPointerType &dest, SrcCharPointerType src) noexcept
Copies null-terminated characters from one string to another.
template<typename DestCharPointerType, typename SrcCharPointerType>
static size_t copyWithDestByteLimit (DestCharPointerType &dest, SrcCharPointerType src, size_t maxBytesToWrite) noexcept
Copies characters from one string to another, up to a null terminator or a given byte size limit.
template<typename DestCharPointerType, typename SrcCharPointerType>
static void copyWithCharLimit (DestCharPointerType &dest, SrcCharPointerType src, int maxChars) noexcept
Copies characters from one string to another, up to a null terminator or a given maximum number of characters.
static int compare (yup_wchar char1, yup_wchar char2) noexcept
Compares two characters.
template<typename CharPointerType1, typename CharPointerType2>
static int compare (CharPointerType1 s1, CharPointerType2 s2) noexcept
Compares two null-terminated character strings.
template<typename CharPointerType1, typename CharPointerType2>
static int compareUpTo (CharPointerType1 s1, CharPointerType2 s2, int maxChars) noexcept
Compares two null-terminated character strings, up to a given number of characters.
static int compareIgnoreCase (yup_wchar char1, yup_wchar char2) noexcept
Compares two characters, using a case-independant match.
template<typename CharPointerType1, typename CharPointerType2>
static int compareIgnoreCase (CharPointerType1 s1, CharPointerType2 s2) noexcept
Compares two null-terminated character strings, using a case-independant match.
template<typename CharPointerType1, typename CharPointerType2>
static int compareIgnoreCaseUpTo (CharPointerType1 s1, CharPointerType2 s2, int maxChars) noexcept
Compares two null-terminated character strings, using a case-independent match.
template<typename CharPointerType1, typename CharPointerType2>
static int indexOf (CharPointerType1 textToSearch, const CharPointerType2 substringToLookFor) noexcept
Finds the character index of a given substring in another string.
template<typename CharPointerType1, typename CharPointerType2>
static CharPointerType1 find (CharPointerType1 textToSearch, const CharPointerType2 substringToLookFor) noexcept
Returns a pointer to the first occurrence of a substring in a string.
template<typename CharPointerType>
static CharPointerType find (CharPointerType textToSearch, const yup_wchar charToLookFor) noexcept
Returns a pointer to the first occurrence of a substring in a string.
template<typename CharPointerType1, typename CharPointerType2>
static int indexOfIgnoreCase (CharPointerType1 haystack, const CharPointerType2 needle) noexcept
Finds the character index of a given substring in another string, using a case-independent match.
template<typename Type>
static int indexOfChar (Type text, const yup_wchar charToFind) noexcept
Finds the character index of a given character in another string.
template<typename Type>
static int indexOfCharIgnoreCase (Type text, yup_wchar charToFind) noexcept
Finds the character index of a given character in another string, using a case-independent match.
template<typename Type>
static void incrementToEndOfWhitespace (Type &text) noexcept
Increments a pointer until it points to the first non-whitespace character in a string.
template<typename Type>
static Type findEndOfWhitespace (Type text) noexcept
Returns a pointer to the first non-whitespace character in a string.
template<typename Type, typename BreakType>
static Type findEndOfToken (Type text, BreakType breakCharacters, Type quoteCharacters)
Returns a pointer to the first character in the string which is found in the breakCharacters string.
Detailed Description
A collection of functions for manipulating characters and character strings.
Most of these methods are designed for internal use by the String and CharPointer classes, but some of them may be useful to call directly.
See also
String, CharPointer_UTF8, CharPointer_UTF16, CharPointer_UTF32
Member Function Documentation
toUpperCase()
yup_wchar yup::CharacterFunctions::toUpperCase (yup_wchar character) static noexcept
Converts a character to upper-case.
References toUpperCase().
Referenced by compareIgnoreCase(), toUpperCase(), yup::CharPointer_ASCII::toUpperCase(), yup::CharPointer_UTF16::toUpperCase(), yup::CharPointer_UTF32::toUpperCase(), and yup::CharPointer_UTF8::toUpperCase().
toLowerCase()
yup_wchar yup::CharacterFunctions::toLowerCase (yup_wchar character) static noexcept
Converts a character to lower-case.
Referenced by yup::File::getRelativePathFrom(), indexOfCharIgnoreCase(), yup::CharPointer_ASCII::toLowerCase(), yup::CharPointer_UTF16::toLowerCase(), yup::CharPointer_UTF32::toLowerCase(), and yup::CharPointer_UTF8::toLowerCase().
isUpperCase()
bool yup::CharacterFunctions::isUpperCase (yup_wchar character) static noexcept
Checks whether a unicode character is upper-case.
Referenced by yup::CharPointer_ASCII::isUpperCase(), yup::CharPointer_UTF16::isUpperCase(), yup::CharPointer_UTF32::isUpperCase(), and yup::CharPointer_UTF8::isUpperCase().
isLowerCase()
bool yup::CharacterFunctions::isLowerCase (yup_wchar character) static noexcept
Checks whether a unicode character is lower-case.
Referenced by yup::CharPointer_ASCII::isLowerCase(), yup::CharPointer_UTF16::isLowerCase(), yup::CharPointer_UTF32::isLowerCase(), and yup::CharPointer_UTF8::isLowerCase().
isWhitespace() [1/2]
bool yup::CharacterFunctions::isWhitespace (char character) static noexcept
Checks whether a character is whitespace.
Referenced by yup::CharPointer_ASCII::isWhitespace(), yup::CharPointer_UTF16::isWhitespace(), yup::CharPointer_UTF32::isWhitespace(), and yup::CharPointer_UTF8::isWhitespace().
isWhitespace() [2/2]
bool yup::CharacterFunctions::isWhitespace (yup_wchar character) static noexcept
Checks whether a character is whitespace.
isDigit() [1/2]
bool yup::CharacterFunctions::isDigit (char character) static noexcept
Checks whether a character is a digit.
Referenced by yup::File::getNonexistentChildFile(), yup::CharPointer_ASCII::isDigit(), yup::CharPointer_UTF16::isDigit(), yup::CharPointer_UTF32::isDigit(), and yup::URL::isWellFormed().
isDigit() [2/2]
bool yup::CharacterFunctions::isDigit (yup_wchar character) static noexcept
Checks whether a character is a digit.
isLetter() [1/2]
bool yup::CharacterFunctions::isLetter (char character) static noexcept
Checks whether a character is alphabetic.
Referenced by yup::CharPointer_ASCII::isLetter(), yup::CharPointer_UTF16::isLetter(), yup::CharPointer_UTF32::isLetter(), and yup::CharPointer_UTF8::isLetter().
isLetter() [2/2]
bool yup::CharacterFunctions::isLetter (yup_wchar character) static noexcept
Checks whether a character is alphabetic.
isLetterOrDigit() [1/2]
bool yup::CharacterFunctions::isLetterOrDigit (char character) static noexcept
Checks whether a character is alphabetic or numeric.
Referenced by yup::URL::addEscapeChars(), yup::CharPointer_ASCII::isLetterOrDigit(), yup::CharPointer_UTF16::isLetterOrDigit(), yup::CharPointer_UTF32::isLetterOrDigit(), and yup::CharPointer_UTF8::isLetterOrDigit().
isLetterOrDigit() [2/2]
bool yup::CharacterFunctions::isLetterOrDigit (yup_wchar character) static noexcept
Checks whether a character is alphabetic or numeric.
isPrintable() [1/2]
bool yup::CharacterFunctions::isPrintable (char character) static noexcept
Checks whether a character is a printable character, i.e.
alphabetic, numeric, a punctuation character or a space.
isPrintable() [2/2]
bool yup::CharacterFunctions::isPrintable (yup_wchar character) static noexcept
Checks whether a character is a printable character, i.e.
alphabetic, numeric, a punctuation character or a space.
getHexDigitValue()
int yup::CharacterFunctions::getHexDigitValue (yup_wchar digit) static noexcept
Returns 0 to 16 for '0' to 'F", or -1 for characters that aren't a legal hex digit.
Referenced by yup::CharacterFunctions::HexParser< ResultType >::parse(), yup::BigInteger::parseString(), and yup::URL::removeEscapeChars().
getUnicodeCharFromWindows1252Codepage()
yup_wchar yup::CharacterFunctions::getUnicodeCharFromWindows1252Codepage (uint8 windows1252Char) static noexcept
Converts a byte of Windows 1252 codepage to unicode.
readDoubleValue()
template<typename CharPointerType> double yup::CharacterFunctions::readDoubleValue (CharPointerType & text) static noexcept
Parses a character string to read a floating-point number.
Note that this will advance the pointer that is passed in, leaving it at the end of the number.
Referenced by getDoubleValue().
getDoubleValue()
template<typename CharPointerType> double yup::CharacterFunctions::getDoubleValue (CharPointerType text) static noexcept
Parses a character string, to read a floating-point value.
References readDoubleValue().
Referenced by yup::CharPointer_ASCII::getDoubleValue(), yup::CharPointer_UTF16::getDoubleValue(), yup::CharPointer_UTF32::getDoubleValue(), and yup::CharPointer_UTF8::getDoubleValue().
getIntValue()
template<typename IntType, typename CharPointerType> IntType yup::CharacterFunctions::getIntValue (const CharPointerType text) static noexcept
Parses a character string, to read an integer value.
Referenced by yup::CharPointer_UTF16::getIntValue32(), yup::CharPointer_UTF32::getIntValue32(), yup::CharPointer_ASCII::getIntValue64(), yup::CharPointer_UTF16::getIntValue64(), and yup::CharPointer_UTF32::getIntValue64().
lengthUpTo() [1/2]
template<typename CharPointerType> size_t yup::CharacterFunctions::lengthUpTo (CharPointerType text, const size_t maxCharsToCount) static noexcept
Counts the number of characters in a given string, stopping if the count exceeds a specified limit.
Referenced by yup::CharPointer_ASCII::lengthUpTo(), yup::CharPointer_ASCII::lengthUpTo(), yup::CharPointer_UTF16::lengthUpTo(), yup::CharPointer_UTF16::lengthUpTo(), yup::CharPointer_UTF32::lengthUpTo(), yup::CharPointer_UTF32::lengthUpTo(), yup::CharPointer_UTF8::lengthUpTo(), and yup::CharPointer_UTF8::lengthUpTo().
lengthUpTo() [2/2]
template<typename CharPointerType> size_t yup::CharacterFunctions::lengthUpTo (CharPointerType start, const CharPointerType end) static noexcept
Counts the number of characters in a given string, stopping if the count exceeds a specified end-pointer.
References yup::end().
copyAll()
template<typename DestCharPointerType, typename SrcCharPointerType> void yup::CharacterFunctions::copyAll (DestCharPointerType & dest, SrcCharPointerType src) static noexcept
Copies null-terminated characters from one string to another.
Referenced by yup::CharPointer_ASCII::writeAll(), yup::CharPointer_UTF16::writeAll(), yup::CharPointer_UTF32::writeAll(), and yup::CharPointer_UTF8::writeAll().
copyWithDestByteLimit()
template<typename DestCharPointerType, typename SrcCharPointerType> size_t yup::CharacterFunctions::copyWithDestByteLimit (DestCharPointerType & dest, SrcCharPointerType src, size_t maxBytesToWrite) static noexcept
Copies characters from one string to another, up to a null terminator or a given byte size limit.
References yup::getAddressDifference().
Referenced by yup::CharPointer_ASCII::writeWithDestByteLimit(), yup::CharPointer_UTF16::writeWithDestByteLimit(), yup::CharPointer_UTF32::writeWithDestByteLimit(), and yup::CharPointer_UTF8::writeWithDestByteLimit().
copyWithCharLimit()
template<typename DestCharPointerType, typename SrcCharPointerType> void yup::CharacterFunctions::copyWithCharLimit (DestCharPointerType & dest, SrcCharPointerType src, int maxChars) static noexcept
Copies characters from one string to another, up to a null terminator or a given maximum number of characters.
Referenced by yup::CharPointer_ASCII::writeWithCharLimit(), yup::CharPointer_UTF16::writeWithCharLimit(), yup::CharPointer_UTF32::writeWithCharLimit(), and yup::CharPointer_UTF8::writeWithCharLimit().
compare() [1/2]
int yup::CharacterFunctions::compare (yup_wchar char1, yup_wchar char2) static noexcept
Compares two characters.
Referenced by compare(), yup::CharPointer_ASCII::compare(), yup::CharPointer_UTF16::compare(), yup::CharPointer_UTF32::compare(), yup::CharPointer_UTF8::compare(), compareIgnoreCase(), and compareUpTo().
compare() [2/2]
template<typename CharPointerType1, typename CharPointerType2> int yup::CharacterFunctions::compare (CharPointerType1 s1, CharPointerType2 s2) static noexcept
Compares two null-terminated character strings.
References compare().
compareUpTo()
template<typename CharPointerType1, typename CharPointerType2> int yup::CharacterFunctions::compareUpTo (CharPointerType1 s1, CharPointerType2 s2, int maxChars) static noexcept
Compares two null-terminated character strings, up to a given number of characters.
References compare().
Referenced by yup::CharPointer_ASCII::compareUpTo(), yup::CharPointer_UTF16::compareUpTo(), yup::CharPointer_UTF32::compareUpTo(), and yup::CharPointer_UTF8::compareUpTo().
compareIgnoreCase() [1/2]
int yup::CharacterFunctions::compareIgnoreCase (yup_wchar char1, yup_wchar char2) static noexcept
Compares two characters, using a case-independant match.
References compare(), and toUpperCase().
Referenced by compareIgnoreCase(), yup::CharPointer_ASCII::compareIgnoreCase(), yup::CharPointer_ASCII::compareIgnoreCase(), yup::CharPointer_UTF16::compareIgnoreCase(), yup::CharPointer_UTF32::compareIgnoreCase(), yup::CharPointer_UTF8::compareIgnoreCase(), yup::CharPointer_UTF8::compareIgnoreCase(), and compareIgnoreCaseUpTo().
compareIgnoreCase() [2/2]
template<typename CharPointerType1, typename CharPointerType2> int yup::CharacterFunctions::compareIgnoreCase (CharPointerType1 s1, CharPointerType2 s2) static noexcept
Compares two null-terminated character strings, using a case-independant match.
References compareIgnoreCase().
compareIgnoreCaseUpTo()
template<typename CharPointerType1, typename CharPointerType2> int yup::CharacterFunctions::compareIgnoreCaseUpTo (CharPointerType1 s1, CharPointerType2 s2, int maxChars) static noexcept
Compares two null-terminated character strings, using a case-independent match.
References compareIgnoreCase().
Referenced by yup::CharPointer_ASCII::compareIgnoreCaseUpTo(), yup::CharPointer_UTF16::compareIgnoreCaseUpTo(), yup::CharPointer_UTF32::compareIgnoreCaseUpTo(), and yup::CharPointer_UTF8::compareIgnoreCaseUpTo().
indexOf()
template<typename CharPointerType1, typename CharPointerType2> int yup::CharacterFunctions::indexOf (CharPointerType1 textToSearch, const CharPointerType2 substringToLookFor) static noexcept
Finds the character index of a given substring in another string.
Returns -1 if the substring is not found.
Referenced by yup::CharPointer_ASCII::indexOf(), yup::CharPointer_UTF16::indexOf(), yup::CharPointer_UTF32::indexOf(), and yup::CharPointer_UTF8::indexOf().
find() [1/2]
template<typename CharPointerType1, typename CharPointerType2> CharPointerType1 yup::CharacterFunctions::find (CharPointerType1 textToSearch, const CharPointerType2 substringToLookFor) static noexcept
Returns a pointer to the first occurrence of a substring in a string.
If the substring is not found, this will return a pointer to the string's null terminator.
Referenced by yup::MemoryBlock::fromBase64Encoding().
find() [2/2]
template<typename CharPointerType> CharPointerType yup::CharacterFunctions::find (CharPointerType textToSearch, const yup_wchar charToLookFor) static noexcept
Returns a pointer to the first occurrence of a substring in a string.
If the substring is not found, this will return a pointer to the string's null terminator.
indexOfIgnoreCase()
template<typename CharPointerType1, typename CharPointerType2> int yup::CharacterFunctions::indexOfIgnoreCase (CharPointerType1 haystack, const CharPointerType2 needle) static noexcept
Finds the character index of a given substring in another string, using a case-independent match.
Returns -1 if the substring is not found.
Referenced by yup::String::indexOfIgnoreCase(), and yup::String::indexOfIgnoreCase().
indexOfChar()
template<typename Type> int yup::CharacterFunctions::indexOfChar (Type text, const yup_wchar charToFind) static noexcept
Finds the character index of a given character in another string.
Returns -1 if the character is not found.
Referenced by yup::CharPointer_ASCII::indexOf(), yup::CharPointer_UTF16::indexOf(), yup::CharPointer_UTF16::indexOf(), yup::CharPointer_UTF32::indexOf(), yup::CharPointer_UTF8::indexOf(), and yup::CharPointer_UTF8::indexOf().
indexOfCharIgnoreCase()
template<typename Type> int yup::CharacterFunctions::indexOfCharIgnoreCase (Type text, yup_wchar charToFind) static noexcept
Finds the character index of a given character in another string, using a case-independent match.
Returns -1 if the character is not found.
References toLowerCase().
Referenced by yup::CharPointer_ASCII::indexOf(), yup::CharPointer_UTF16::indexOf(), yup::CharPointer_UTF32::indexOf(), and yup::CharPointer_UTF8::indexOf().
incrementToEndOfWhitespace()
template<typename Type> void yup::CharacterFunctions::incrementToEndOfWhitespace (Type & text) static noexcept
Increments a pointer until it points to the first non-whitespace character in a string.
If the string contains only whitespace, the pointer will point to the string's null terminator.
Referenced by findEndOfWhitespace(), yup::CharPointer_ASCII::incrementToEndOfWhitespace(), yup::CharPointer_UTF16::incrementToEndOfWhitespace(), yup::CharPointer_UTF32::incrementToEndOfWhitespace(), and yup::CharPointer_UTF8::incrementToEndOfWhitespace().
findEndOfWhitespace()
template<typename Type> Type yup::CharacterFunctions::findEndOfWhitespace (Type text) static noexcept
Returns a pointer to the first non-whitespace character in a string.
If the string contains only whitespace, this will return a pointer to its null terminator.
References incrementToEndOfWhitespace().
Referenced by yup::CharPointer_ASCII::findEndOfWhitespace(), yup::CharPointer_UTF16::findEndOfWhitespace(), yup::CharPointer_UTF32::findEndOfWhitespace(), and yup::CharPointer_UTF8::findEndOfWhitespace().
findEndOfToken()
template<typename Type, typename BreakType> Type yup::CharacterFunctions::findEndOfToken (Type text, BreakType breakCharacters, Type quoteCharacters) static
Returns a pointer to the first character in the string which is found in the breakCharacters string.
Referenced by yup::StringArray::addTokens().