YUP: yup::MemoryAudioSource Class Reference
yup::MemoryAudioSource Class Reference
An AudioSource which takes some float audio data as an input.
Public Member Functions
MemoryAudioSource (AudioBuffer< float > &audioBuffer, bool copyMemory, bool shouldLoop=false)
Creates a MemoryAudioSource by providing an audio buffer.
void prepareToPlay (int samplesPerBlockExpected, double sampleRate) override
Implementation of the AudioSource method.
void releaseResources () override
Implementation of the AudioSource method.
void getNextAudioBlock (const AudioSourceChannelInfo &bufferToFill) override
Implementation of the AudioSource method.
void setNextReadPosition (int64 newPosition) override
Implementation of the PositionableAudioSource method.
int64 getNextReadPosition () const override
Implementation of the PositionableAudioSource method.
int64 getTotalLength () const override
Implementation of the PositionableAudioSource method.
bool isLooping () const override
Implementation of the PositionableAudioSource method.
void setLooping (bool shouldLoop) override
Implementation of the PositionableAudioSource method.
Public Member Functions inherited from yup::PositionableAudioSource
~PositionableAudioSource () override=default
Destructor.
Public Member Functions inherited from yup::AudioSource
virtual ~AudioSource ()=default
Destructor.
Additional Inherited Members
Protected Member Functions inherited from yup::PositionableAudioSource
PositionableAudioSource ()=default
Creates the PositionableAudioSource.
Protected Member Functions inherited from yup::AudioSource
AudioSource ()=default
Creates an AudioSource.
Detailed Description
An AudioSource which takes some float audio data as an input.
Constructor & Destructor Documentation
MemoryAudioSource()
yup::MemoryAudioSource::MemoryAudioSource (AudioBuffer< float > & audioBuffer, bool copyMemory, bool shouldLoop = false)
Creates a MemoryAudioSource by providing an audio buffer.
If copyMemory is true then the buffer will be copied into an internal buffer which will be owned by the MemoryAudioSource. If copyMemory is false, then you must ensure that the lifetime of the audio buffer is at least as long as the MemoryAudioSource.
References yup::AudioBuffer< Type >::getArrayOfWritePointers(), yup::AudioBuffer< Type >::getNumChannels(), and yup::AudioBuffer< Type >::getNumSamples().
Member Function Documentation
prepareToPlay()
void yup::MemoryAudioSource::prepareToPlay (int samplesPerBlockExpected, double sampleRate) override virtual
Implementation of the AudioSource method.
Implements yup::AudioSource.
releaseResources()
void yup::MemoryAudioSource::releaseResources () override virtual
Implementation of the AudioSource method.
Implements yup::AudioSource.
getNextAudioBlock()
void yup::MemoryAudioSource::getNextAudioBlock (const AudioSourceChannelInfo & bufferToFill) override virtual
Implementation of the AudioSource method.
Implements yup::AudioSource.
References yup::AudioSourceChannelInfo::buffer, yup::AudioSourceChannelInfo::clearActiveBufferRegion(), yup::jmin(), yup::AudioSourceChannelInfo::numSamples, and yup::AudioSourceChannelInfo::startSample.
setNextReadPosition()
void yup::MemoryAudioSource::setNextReadPosition (int64 newPosition) override virtual
Implementation of the PositionableAudioSource method.
Implements yup::PositionableAudioSource.
getNextReadPosition()
int64 yup::MemoryAudioSource::getNextReadPosition () const override virtual
Implementation of the PositionableAudioSource method.
Implements yup::PositionableAudioSource.
getTotalLength()
int64 yup::MemoryAudioSource::getTotalLength () const override virtual
Implementation of the PositionableAudioSource method.
Implements yup::PositionableAudioSource.
isLooping()
bool yup::MemoryAudioSource::isLooping () const override virtual
Implementation of the PositionableAudioSource method.
Implements yup::PositionableAudioSource.
setLooping()
void yup::MemoryAudioSource::setLooping (bool shouldLoop) override virtual
Implementation of the PositionableAudioSource method.
Reimplemented from yup::PositionableAudioSource.