YUP: yup::SHA1 Class Reference
yup::SHA1 Class Reference
SHA-1 UNSECURE hash generator.
Public Member Functions
SHA1 () noexcept
Creates an empty SHA1 object.
~SHA1 () noexcept
Destructor.
SHA1 (const SHA1 &other) noexcept
Creates a copy of another SHA1.
SHA1 & operator= (const SHA1 &other) noexcept
Copies another SHA1.
SHA1 (const MemoryBlock &data)
Creates a hash from a block of raw data.
SHA1 (const void *data, size_t numBytes)
Creates a hash from a block of raw data.
SHA1 (InputStream &input, int64 maxBytesToRead=-1)
Creates a hash from the contents of a stream.
SHA1 (const File &file)
Reads a file and generates the hash of its contents.
SHA1 (CharPointer_UTF8 utf8Text) noexcept
Creates a checksum from a UTF-8 buffer.
Span< const uint8 > getRawData () const
Returns the hash as a 32-byte block of data.
String toHexString () const
Returns the checksum as a 64-digit hex string.
bool operator== (const SHA1 &) const noexcept
bool operator!= (const SHA1 &) const noexcept
Detailed Description
SHA-1 UNSECURE hash generator.
Do not use this class for cryptographic uses.
Create one of these objects from a block of source data or a stream, and it calculates the SHA-1 hash of that data.
You can retrieve the hash as a raw 32-byte block, or as a 64-digit hex string.
See also
MD5, SHA256
Constructor & Destructor Documentation
SHA1() [1/7]
yup::SHA1::SHA1 () noexcept
Creates an empty SHA1 object.
The default constructor just creates a hash filled with zeros. (This is not equal to the hash of an empty block of data).
References yup::zerostruct().
Referenced by operator!=(), operator=(), operator==(), and SHA1().
~SHA1()
yup::SHA1::~SHA1 () noexcept
Destructor.
SHA1() [2/7]
yup::SHA1::SHA1 (const SHA1 & other) noexcept
Creates a copy of another SHA1.
References SHA1().
SHA1() [3/7]
yup::SHA1::SHA1 (const MemoryBlock & data) explicit
Creates a hash from a block of raw data.
References yup::MemoryBlock::getData(), and yup::MemoryBlock::getSize().
SHA1() [4/7]
yup::SHA1::SHA1 (const void * data, size_t numBytes)
Creates a hash from a block of raw data.
SHA1() [5/7]
yup::SHA1::SHA1 (InputStream & input, int64 maxBytesToRead = -1)
Creates a hash from the contents of a stream.
This will read from the stream until the stream is exhausted, or until maxBytesToRead bytes have been read. If maxBytesToRead is negative, the entire stream will be read.
SHA1() [6/7]
yup::SHA1::SHA1 (const File & file) explicit
Reads a file and generates the hash of its contents.
If the file can't be opened, the hash will be left uninitialised (i.e. full of zeros).
References yup::FileInputStream::getStatus(), yup::Result::wasOk(), and yup::zerostruct().
SHA1() [7/7]
yup::SHA1::SHA1 (CharPointer_UTF8 utf8Text) explicit noexcept
Creates a checksum from a UTF-8 buffer.
E.g.
SHA1 checksum (myString.toUTF8());
Member Function Documentation
operator=()
SHA1 & yup::SHA1::operator= (const SHA1 & other) noexcept
Copies another SHA1.
References SHA1().
getRawData()
Span< const uint8 > yup::SHA1::getRawData () const
Returns the hash as a 32-byte block of data.
toHexString()
String yup::SHA1::toHexString () const
Returns the checksum as a 64-digit hex string.
References yup::String::toHexString().
operator==()
bool yup::SHA1::operator== (const SHA1 & other) const noexcept
References SHA1().
operator!=()
bool yup::SHA1::operator!= (const SHA1 & other) const noexcept
References yup::operator==(), and SHA1().