YUP: yup::StringRef Class Reference
yup::StringRef Class Reference final
A simple class for holding temporary references to a string literal or String.
Public Member Functions
StringRef (const char *stringLiteral) noexcept
Creates a StringRef from a raw string literal.
StringRef (String::CharPointerType stringLiteral) noexcept
Creates a StringRef from a raw char pointer.
StringRef (const String &string) noexcept
Creates a StringRef from a String.
StringRef (const std::string &string)
Creates a StringRef from a String.
StringRef () noexcept
Creates a StringRef pointer to an empty string.
operator const String::CharPointerType::CharType * () const noexcept
Returns a raw pointer to the underlying string data.
operator String::CharPointerType () const noexcept
Returns a pointer to the underlying string data as a char pointer object.
bool isEmpty () const noexcept
Returns true if the string is empty.
bool isNotEmpty () const noexcept
Returns true if the string is not empty.
int length () const noexcept
Returns the number of characters in the string.
yup_wchar operator[] (int index) const noexcept
Retrieves a character by index.
bool operator== (const String &s) const noexcept
Compares this StringRef with a String.
bool operator!= (const String &s) const noexcept
Compares this StringRef with a String.
bool operator< (const String &s) const noexcept
Compares this StringRef with a String.
bool operator<= (const String &s) const noexcept
Compares this StringRef with a String.
bool operator> (const String &s) const noexcept
Compares this StringRef with a String.
bool operator>= (const String &s) const noexcept
Compares this StringRef with a String.
bool operator== (StringRef s) const noexcept
Case-sensitive comparison of two StringRefs.
bool operator!= (StringRef s) const noexcept
Case-sensitive comparison of two StringRefs.
Public Attributes
String::CharPointerType text
The text that is referenced.
Detailed Description
A simple class for holding temporary references to a string literal or String.
Unlike a real String object, the StringRef does not allocate any memory or take ownership of the strings you give to it - it simply holds a reference to a string that has been allocated elsewhere. The main purpose of the class is to be used instead of a const String& as the type of function arguments where the caller may pass either a string literal or a String object. This means that when the called uses a string literal, there's no need for an temporary String object to be allocated, and this cuts down overheads substantially.
Because the class is simply a wrapper around a pointer, you should always pass it by value, not by reference.
void myStringFunction1 (const String&);
void myStringFunction2 (StringRef);
myStringFunction1 ("abc"); // Implicitly allocates a temporary String object.
myStringFunction2 ("abc"); // Much faster, as no local allocations are needed.
For examples of it in use, see the XmlElement or StringArray classes.
Bear in mind that there are still many cases where it's better to use an argument which is a const String&. For example if the function stores the string or needs to internally create a String from the argument, then it's better for the original argument to already be a String.
See also
String
Constructor & Destructor Documentation
StringRef() [1/5]
yup::StringRef::StringRef (const char * stringLiteral) noexcept
Creates a StringRef from a raw string literal.
The StringRef object does NOT take ownership or copy this data, so you must ensure that the data does not change during the lifetime of the StringRef. Note that this pointer cannot be null!
References yup::CharPointer_ASCII::isValidString(), and text.
Referenced by operator!=(), operator==(), and StringRef().
StringRef() [2/5]
yup::StringRef::StringRef (String::CharPointerType stringLiteral) noexcept
Creates a StringRef from a raw char pointer.
The StringRef object does NOT take ownership or copy this data, so you must ensure that the data does not change during the lifetime of the StringRef.
References text.
StringRef() [3/5]
yup::StringRef::StringRef (const String & string) noexcept
Creates a StringRef from a String.
The StringRef object does NOT take ownership or copy the data from the String, so you must ensure that the String is not modified or deleted during the lifetime of the StringRef.
References text.
StringRef() [4/5]
yup::StringRef::StringRef (const std::string & string)
Creates a StringRef from a String.
The StringRef object does NOT take ownership or copy the data from the std::string, so you must ensure that the source string object is not modified or deleted during the lifetime of the StringRef.
References StringRef().
StringRef() [5/5]
yup::StringRef::StringRef () noexcept
Creates a StringRef pointer to an empty string.
References operator String::CharPointerType(), text, and yup::unalignedPointerCast().
Member Function Documentation
operator const String::CharPointerType::CharType *()
yup::StringRef::operator const String::CharPointerType::CharType * () const noexcept
Returns a raw pointer to the underlying string data.
References text.
operator String::CharPointerType()
yup::StringRef::operator String::CharPointerType () const noexcept
Returns a pointer to the underlying string data as a char pointer object.
References text.
Referenced by StringRef().
isEmpty()
bool yup::StringRef::isEmpty () const noexcept
Returns true if the string is empty.
References text.
Referenced by yup::StringPool::getPooledString(), and yup::File::hasFileExtension().
isNotEmpty()
bool yup::StringRef::isNotEmpty () const noexcept
Returns true if the string is not empty.
References text.
Referenced by yup::StringArray::addTokens(), yup::Identifier::Identifier(), yup::PropertySet::removeValue(), yup::PropertySet::setValue(), and yup::File::withFileExtension().
length()
int yup::StringRef::length () const noexcept
Returns the number of characters in the string.
References text.
Referenced by yup::String::fromFirstOccurrenceOf(), yup::String::fromLastOccurrenceOf(), yup::Font::getAxisDescription(), yup::Font::getAxisValue(), yup::File::hasFileExtension(), yup::MemoryBlock::loadFromHexString(), yup::String::replace(), yup::String::replaceCharacters(), yup::String::replaceFirstOccurrenceOf(), yup::Font::resetAxisValue(), yup::Font::setAxisValue(), yup::String::upToFirstOccurrenceOf(), yup::String::upToLastOccurrenceOf(), and yup::Font::withAxisValue().
operator[]()
yup_wchar yup::StringRef::operator[] (int index) const noexcept
Retrieves a character by index.
References text.
operator==() [1/2]
bool yup::StringRef::operator== (const String & s) const noexcept
Compares this StringRef with a String.
References text.
operator!=() [1/2]
bool yup::StringRef::operator!= (const String & s) const noexcept
Compares this StringRef with a String.
References text.
operator<()
bool yup::StringRef::operator< (const String & s) const noexcept
Compares this StringRef with a String.
References text.
operator<=()
bool yup::StringRef::operator<= (const String & s) const noexcept
Compares this StringRef with a String.
References text.
operator>()
bool yup::StringRef::operator> (const String & s) const noexcept
Compares this StringRef with a String.
References text.
operator>=()
bool yup::StringRef::operator>= (const String & s) const noexcept
Compares this StringRef with a String.
References text.
operator==() [2/2]
bool yup::StringRef::operator== (StringRef s) const noexcept
Case-sensitive comparison of two StringRefs.
References StringRef(), and text.
operator!=() [2/2]
bool yup::StringRef::operator!= (StringRef s) const noexcept
Case-sensitive comparison of two StringRefs.
References StringRef(), and text.
Member Data Documentation
text
String::CharPointerType yup::StringRef::text
The text that is referenced.
Referenced by yup::StringArray::addLines(), yup::StringArray::addTokens(), yup::Base64::convertFromBase64(), yup::JSON::escapeString(), yup::MemoryBlock::fromBase64Encoding(), yup::Time::fromISO8601(), yup::JSON::fromString(), yup::File::getChildFile(), yup::StringPool::getPooledString(), yup::File::hasFileExtension(), yup::String::initialSectionContainingOnly(), yup::String::initialSectionNotContaining(), yup::File::isAbsolutePath(), isEmpty(), isNotEmpty(), yup::StringArray::joinIntoString(), length(), yup::MemoryBlock::loadFromHexString(), operator const String::CharPointerType::CharType *(), operator String::CharPointerType(), operator!=(), operator!=(), yup::operator+(), yup::operator+(), yup::operator+(), yup::operator+(), operator<(), yup::operator<<(), operator<=(), operator==(), operator==(), operator>(), operator>=(), operator[](), yup::BigInteger::parseString(), yup::String::removeCharacters(), yup::String::repeatedString(), yup::String::replaceCharacters(), yup::String::replaceSection(), yup::String::retainCharacters(), StringRef(), StringRef(), StringRef(), StringRef(), yup::MidiMessage::textMetaEvent(), yup::String::trimCharactersAtEnd(), yup::String::trimCharactersAtStart(), and yup::File::withFileExtension().