YUP: yup::BigInteger Class Reference
yup::BigInteger Class Reference
An arbitrarily large integer class.
Public Member Functions
BigInteger ()
Creates an empty BigInteger.
BigInteger (uint32 value)
Creates a BigInteger containing an integer value in its low bits.
BigInteger (int32 value)
Creates a BigInteger containing an integer value in its low bits.
BigInteger (int64 value)
Creates a BigInteger containing an integer value in its low bits.
BigInteger (const BigInteger &)
Creates a copy of another BigInteger.
BigInteger (BigInteger &&) noexcept
Move constructor.
BigInteger & operator= (BigInteger &&) noexcept
Move assignment operator.
~BigInteger ()
Destructor.
BigInteger & operator= (const BigInteger &)
Copies another BigInteger onto this one.
void swapWith (BigInteger &) noexcept
Swaps the internal contents of this with another object.
bool operator[] (int bit) const noexcept
Returns the value of a specified bit in the number.
bool isZero () const noexcept
Returns true if no bits are set.
bool isOne () const noexcept
Returns true if the value is 1.
int toInteger () const noexcept
Attempts to get the lowest 32 bits of the value as an integer.
int64 toInt64 () const noexcept
Attempts to get the lowest 64 bits of the value as an integer.
BigInteger & clear () noexcept
Resets the value to 0.
BigInteger & clearBit (int bitNumber) noexcept
Clears a particular bit in the number.
BigInteger & setBit (int bitNumber)
Sets a specified bit to 1.
BigInteger & setBit (int bitNumber, bool shouldBeSet)
Sets or clears a specified bit.
BigInteger & setRange (int startBit, int numBits, bool shouldBeSet)
Sets a range of bits to be either on or off.
BigInteger & insertBit (int bitNumber, bool shouldBeSet)
Inserts a bit an a given position, shifting up any bits above it.
BigInteger getBitRange (int startBit, int numBits) const
Returns a range of bits as a new BigInteger.
uint32 getBitRangeAsInt (int startBit, int numBits) const noexcept
Returns a range of bits as an integer value.
BigInteger & setBitRangeAsInt (int startBit, int numBits, uint32 valueToSet)
Sets a range of bits to an integer value.
BigInteger & shiftBits (int howManyBitsLeft, int startBit)
Shifts a section of bits left or right.
int countNumberOfSetBits () const noexcept
Returns the total number of set bits in the value.
int findNextSetBit (int startIndex) const noexcept
Looks for the index of the next set bit after a given starting point.
int findNextClearBit (int startIndex) const noexcept
Looks for the index of the next clear bit after a given starting point.
int getHighestBit () const noexcept
Returns the index of the highest set bit in the number.
bool isNegative () const noexcept
Returns true if the value is less than zero.
void setNegative (bool shouldBeNegative) noexcept
Changes the sign of the number to be positive or negative.
void negate () noexcept
Inverts the sign of the number.
BigInteger & operator+= (const BigInteger &)
BigInteger & operator-= (const BigInteger &)
BigInteger & operator*= (const BigInteger &)
BigInteger & operator/= (const BigInteger &)
BigInteger & operator|= (const BigInteger &)
BigInteger & operator&= (const BigInteger &)
BigInteger & operator^= (const BigInteger &)
BigInteger & operator%= (const BigInteger &)
BigInteger & operator<<= (int numBitsToShift)
BigInteger & operator>>= (int numBitsToShift)
BigInteger & operator++ ()
BigInteger & operator-- ()
BigInteger operator++ (int)
BigInteger operator-- (int)
BigInteger operator- () const
BigInteger operator+ (const BigInteger &) const
BigInteger operator- (const BigInteger &) const
BigInteger operator* (const BigInteger &) const
BigInteger operator/ (const BigInteger &) const
BigInteger operator| (const BigInteger &) const
BigInteger operator& (const BigInteger &) const
BigInteger operator^ (const BigInteger &) const
BigInteger operator% (const BigInteger &) const
BigInteger operator<< (int numBitsToShift) const
BigInteger operator>> (int numBitsToShift) const
bool operator== (const BigInteger &) const noexcept
bool operator!= (const BigInteger &) const noexcept
bool operator< (const BigInteger &) const noexcept
bool operator<= (const BigInteger &) const noexcept
bool operator> (const BigInteger &) const noexcept
bool operator>= (const BigInteger &) const noexcept
int compare (const BigInteger &other) const noexcept
Does a signed comparison of two BigIntegers.
int compareAbsolute (const BigInteger &other) const noexcept
Compares the magnitudes of two BigIntegers, ignoring their signs.
void divideBy (const BigInteger &divisor, BigInteger &remainder)
Divides this value by another one and returns the remainder.
BigInteger findGreatestCommonDivisor (BigInteger other) const
Returns the largest value that will divide both this value and the argument.
void exponentModulo (const BigInteger &exponent, const BigInteger &modulus)
Performs a combined exponent and modulo operation.
void inverseModulo (const BigInteger &modulus)
Performs an inverse modulo on the value.
void montgomeryMultiplication (const BigInteger &other, const BigInteger &modulus, const BigInteger &modulusp, int k)
Performs the Montgomery Multiplication with modulo.
void extendedEuclidean (const BigInteger &a, const BigInteger &b, BigInteger &xOut, BigInteger &yOut)
Performs the Extended Euclidean algorithm.
String toString (int base, int minimumNumCharacters=1) const
Converts the number to a string.
void parseString (StringRef text, int base)
Reads the numeric value from a string.
MemoryBlock toMemoryBlock () const
Turns the number into a block of binary data.
void loadFromMemoryBlock (const MemoryBlock &data)
Converts a block of raw data into a number.
Detailed Description
An arbitrarily large integer class.
A BigInteger can be used in a similar way to a normal integer, but has no size limit (except for memory and performance constraints).
Negative values are possible, but the value isn't stored as 2s-complement, so be careful if you use negative values and look at the values of individual bits.
Constructor & Destructor Documentation
BigInteger() [1/6]
yup::BigInteger::BigInteger ()
Creates an empty BigInteger.
Referenced by BigInteger(), BigInteger(), clear(), clearBit(), compare(), compareAbsolute(), divideBy(), exponentModulo(), extendedEuclidean(), findGreatestCommonDivisor(), getBitRange(), insertBit(), inverseModulo(), montgomeryMultiplication(), operator!=(), operator%(), operator%=(), operator&(), operator&=(), operator*(), operator*=(), operator+(), operator++(), operator++(), operator+=(), operator-(), operator-(), operator--(), operator--(), operator-=(), operator/(), operator/=(), operator<(), operator<<(), operator<<=(), operator<=(), operator=(), operator=(), operator==(), operator>(), operator>=(), operator>>(), operator>>=(), operator^(), operator^=(), operator|(), operator|=(), parseString(), setBit(), setBit(), setBitRangeAsInt(), setRange(), shiftBits(), swapWith(), toString(), and ~BigInteger().
BigInteger() [2/6]
yup::BigInteger::BigInteger (uint32 value)
Creates a BigInteger containing an integer value in its low bits.
The low 32 bits of the number are initialised with this value.
References getHighestBit().
BigInteger() [3/6]
yup::BigInteger::BigInteger (int32 value)
Creates a BigInteger containing an integer value in its low bits.
The low 32 bits of the number are initialised with the absolute value passed in, and its sign is set to reflect the sign of the number.
References getHighestBit().
BigInteger() [4/6]
yup::BigInteger::BigInteger (int64 value)
Creates a BigInteger containing an integer value in its low bits.
The low 64 bits of the number are initialised with the absolute value passed in, and its sign is set to reflect the sign of the number.
References getHighestBit().
BigInteger() [5/6]
yup::BigInteger::BigInteger (const BigInteger & other)
Creates a copy of another BigInteger.
References BigInteger(), and getHighestBit().
BigInteger() [6/6]
yup::BigInteger::BigInteger (BigInteger && other) noexcept
Move constructor.
References BigInteger().
~BigInteger()
yup::BigInteger::~BigInteger () default
Destructor.
References BigInteger(), clear(), clearBit(), compare(), compareAbsolute(), countNumberOfSetBits(), divideBy(), exponentModulo(), extendedEuclidean(), findGreatestCommonDivisor(), findNextClearBit(), findNextSetBit(), getBitRange(), getBitRangeAsInt(), getHighestBit(), insertBit(), inverseModulo(), isNegative(), isOne(), isZero(), loadFromMemoryBlock(), montgomeryMultiplication(), negate(), parseString(), setBit(), setBitRangeAsInt(), setNegative(), setRange(), shiftBits(), swapWith(), toInt64(), toInteger(), toMemoryBlock(), and toString().
Member Function Documentation
operator=() [1/2]
BigInteger & yup::BigInteger::operator= (BigInteger && other) noexcept
Move assignment operator.
References BigInteger().
operator=() [2/2]
BigInteger & yup::BigInteger::operator= (const BigInteger & other)
Copies another BigInteger onto this one.
References BigInteger(), getHighestBit(), and yup::jmax().
swapWith()
void yup::BigInteger::swapWith (BigInteger & other) noexcept
Swaps the internal contents of this with another object.
References BigInteger().
Referenced by divideBy(), exponentModulo(), extendedEuclidean(), findGreatestCommonDivisor(), inverseModulo(), operator%=(), operator*=(), operator-=(), and ~BigInteger().
operator[]()
bool yup::BigInteger::operator[] (int bit) const noexcept
Returns the value of a specified bit in the number.
If the index is out-of-range, the result will be false.
isZero()
bool yup::BigInteger::isZero () const noexcept
Returns true if no bits are set.
References getHighestBit().
Referenced by findGreatestCommonDivisor(), isNegative(), negate(), toString(), and ~BigInteger().
isOne()
bool yup::BigInteger::isOne () const noexcept
Returns true if the value is 1.
References getHighestBit().
Referenced by exponentModulo(), inverseModulo(), and ~BigInteger().
toInteger()
int yup::BigInteger::toInteger () const noexcept
Attempts to get the lowest 32 bits of the value as an integer.
If the value is bigger than the integer limits, this will return only the lower bits.
Referenced by ~BigInteger().
toInt64()
int64 yup::BigInteger::toInt64 () const noexcept
Attempts to get the lowest 64 bits of the value as an integer.
If the value is bigger than the integer limits, this will return only the lower bits.
Referenced by ~BigInteger().
clear()
BigInteger & yup::BigInteger::clear () noexcept
Resets the value to 0.
References BigInteger().
Referenced by divideBy(), extendedEuclidean(), inverseModulo(), operator-=(), operator^=(), parseString(), and ~BigInteger().
clearBit()
BigInteger & yup::BigInteger::clearBit (int bitNumber) noexcept
Clears a particular bit in the number.
References BigInteger(), and getHighestBit().
Referenced by setBit(), and ~BigInteger().
setBit() [1/2]
BigInteger & yup::BigInteger::setBit (int bitNumber)
Sets a specified bit to 1.
References BigInteger().
Referenced by divideBy(), yup::Random::fillBitsRandomly(), insertBit(), setBit(), setBitRangeAsInt(), setRange(), and ~BigInteger().
setBit() [2/2]
BigInteger & yup::BigInteger::setBit (int bitNumber, bool shouldBeSet)
Sets or clears a specified bit.
References BigInteger(), clearBit(), and setBit().
setRange()
BigInteger & yup::BigInteger::setRange (int startBit, int numBits, bool shouldBeSet)
Sets a range of bits to be either on or off.
Parameters
startBit the first bit to change
numBits the number of bits to change
shouldBeSet whether to turn these bits on or off
References BigInteger(), and setBit().
Referenced by yup::AudioChannelSet::ambisonic(), yup::AudioChannelSet::discreteChannels(), montgomeryMultiplication(), and ~BigInteger().
insertBit()
BigInteger & yup::BigInteger::insertBit (int bitNumber, bool shouldBeSet)
Inserts a bit an a given position, shifting up any bits above it.
References BigInteger(), setBit(), and shiftBits().
Referenced by ~BigInteger().
getBitRange()
BigInteger yup::BigInteger::getBitRange (int startBit, int numBits) const
Returns a range of bits as a new BigInteger.
e.g. getBitRangeAsInt (0, 64) would return the lowest 64 bits.
See also
getBitRangeAsInt
References BigInteger(), getBitRangeAsInt(), getHighestBit(), yup::jmax(), and yup::jmin().
Referenced by ~BigInteger().
getBitRangeAsInt()
uint32 yup::BigInteger::getBitRangeAsInt (int startBit, int numBits) const noexcept
Returns a range of bits as an integer value.
e.g. getBitRangeAsInt (0, 32) would return the lowest 32 bits.
Asking for more than 32 bits isn't allowed (obviously) - for that, use getBitRange().
References yup::jmin().
Referenced by getBitRange(), toString(), and ~BigInteger().
setBitRangeAsInt()
BigInteger & yup::BigInteger::setBitRangeAsInt (int startBit, int numBits, uint32 valueToSet)
Sets a range of bits to an integer value.
Copies the given integer onto a range of bits, starting at startBit, and using up to numBits of the available bits.
References BigInteger(), and setBit().
Referenced by yup::Random::fillBitsRandomly(), loadFromMemoryBlock(), and ~BigInteger().
shiftBits()
BigInteger & yup::BigInteger::shiftBits (int howManyBitsLeft, int startBit)
Shifts a section of bits left or right.
Parameters
howManyBitsLeft how far to move the bits (+ve numbers shift it left, -ve numbers shift it right).
startBit the first bit to affect - if this is > 0, only bits above that index will be affected.
References BigInteger().
Referenced by insertBit(), operator<<=(), operator>>=(), and ~BigInteger().
countNumberOfSetBits()
int yup::BigInteger::countNumberOfSetBits () const noexcept
Returns the total number of set bits in the value.
References yup::countNumberOfBits().
Referenced by yup::AudioDeviceManager::setAudioDeviceSetup(), and ~BigInteger().
findNextSetBit()
int yup::BigInteger::findNextSetBit (int startIndex) const noexcept
Looks for the index of the next set bit after a given starting point.
This searches from startIndex (inclusive) upwards for the first set bit, and returns its index. If no set bits are found, it returns -1.
Referenced by ~BigInteger().
findNextClearBit()
int yup::BigInteger::findNextClearBit (int startIndex) const noexcept
Looks for the index of the next clear bit after a given starting point.
This searches from startIndex (inclusive) upwards for the first clear bit, and returns its index.
Referenced by ~BigInteger().
getHighestBit()
int yup::BigInteger::getHighestBit () const noexcept
Returns the index of the highest set bit in the number.
If the value is zero, this will return -1.
References yup::findHighestSetBit().
Referenced by BigInteger(), BigInteger(), BigInteger(), BigInteger(), clearBit(), compareAbsolute(), divideBy(), exponentModulo(), findGreatestCommonDivisor(), getBitRange(), isOne(), isZero(), loadFromMemoryBlock(), yup::Random::nextLargeNumber(), operator&=(), operator*=(), operator+=(), operator-=(), operator=(), operator^=(), operator|=(), toMemoryBlock(), and ~BigInteger().
isNegative()
bool yup::BigInteger::isNegative () const noexcept
Returns true if the value is less than zero.
See also
setNegative, negate
References isZero().
Referenced by compare(), divideBy(), inverseModulo(), montgomeryMultiplication(), operator&=(), operator*=(), operator+=(), operator-=(), operator^=(), operator|=(), toString(), and ~BigInteger().
setNegative()
void yup::BigInteger::setNegative (bool shouldBeNegative) noexcept
Changes the sign of the number to be positive or negative.
See also
isNegative, negate
Referenced by divideBy(), operator*=(), parseString(), and ~BigInteger().
negate()
void yup::BigInteger::negate () noexcept
Inverts the sign of the number.
See also
isNegative, setNegative
References isZero().
Referenced by extendedEuclidean(), operator+=(), operator-=(), and ~BigInteger().
operator+=()
BigInteger & yup::BigInteger::operator+= (const BigInteger & other)
References BigInteger(), compareAbsolute(), getHighestBit(), isNegative(), yup::jmax(), negate(), operator+=(), and operator-=().
Referenced by operator++(), operator++(), operator+=(), and operator-=().
operator-=()
BigInteger & yup::BigInteger::operator-= (const BigInteger & other)
References BigInteger(), clear(), compareAbsolute(), getHighestBit(), isNegative(), negate(), operator+=(), and swapWith().
Referenced by operator+=(), operator--(), and operator--().
operator*=()
BigInteger & yup::BigInteger::operator*= (const BigInteger & other)
References BigInteger(), getHighestBit(), isNegative(), operator*=(), setNegative(), and swapWith().
Referenced by operator*=().
operator/=()
BigInteger & yup::BigInteger::operator/= (const BigInteger & other)
References BigInteger(), and divideBy().
operator|=()
BigInteger & yup::BigInteger::operator|= (const BigInteger & other)
References BigInteger(), getHighestBit(), and isNegative().
operator&=()
BigInteger & yup::BigInteger::operator&= (const BigInteger & other)
References BigInteger(), getHighestBit(), and isNegative().
operator^=()
BigInteger & yup::BigInteger::operator^= (const BigInteger & other)
References BigInteger(), clear(), getHighestBit(), and isNegative().
operator%=()
BigInteger & yup::BigInteger::operator%= (const BigInteger & divisor)
References BigInteger(), divideBy(), and swapWith().
operator<<=()
BigInteger & yup::BigInteger::operator<<= (int numBitsToShift)
References BigInteger(), and shiftBits().
operator>>=()
BigInteger & yup::BigInteger::operator>>= (int numBitsToShift)
References BigInteger(), and shiftBits().
operator++() [1/2]
BigInteger & yup::BigInteger::operator++ ()
References BigInteger(), and operator+=().
operator--() [1/2]
BigInteger & yup::BigInteger::operator-- ()
References BigInteger(), and operator-=().
operator++() [2/2]
BigInteger yup::BigInteger::operator++ (int)
References BigInteger(), and operator+=().
operator--() [2/2]
BigInteger yup::BigInteger::operator-- (int)
References BigInteger(), and operator-=().
operator-() [1/2]
BigInteger yup::BigInteger::operator- () const
References BigInteger().
operator+()
BigInteger yup::BigInteger::operator+ (const BigInteger & other) const
References BigInteger().
operator-() [2/2]
BigInteger yup::BigInteger::operator- (const BigInteger & other) const
References BigInteger().
operator*()
BigInteger yup::BigInteger::operator* (const BigInteger & other) const
References BigInteger().
operator/()
BigInteger yup::BigInteger::operator/ (const BigInteger & other) const
References BigInteger().
operator|()
BigInteger yup::BigInteger::operator| (const BigInteger & other) const
References BigInteger().
operator&()
BigInteger yup::BigInteger::operator& (const BigInteger & other) const
References BigInteger().
operator^()
BigInteger yup::BigInteger::operator^ (const BigInteger & other) const
References BigInteger().
operator%()
BigInteger yup::BigInteger::operator% (const BigInteger & other) const
References BigInteger().
operator<<()
BigInteger yup::BigInteger::operator<< (int numBitsToShift) const
References BigInteger().
operator>>()
BigInteger yup::BigInteger::operator>> (int numBitsToShift) const
References BigInteger().
operator==()
bool yup::BigInteger::operator== (const BigInteger & other) const noexcept
References BigInteger(), and compare().
operator!=()
bool yup::BigInteger::operator!= (const BigInteger & other) const noexcept
References BigInteger(), and compare().
operator<()
bool yup::BigInteger::operator< (const BigInteger & other) const noexcept
References BigInteger(), and compare().
operator<=()
bool yup::BigInteger::operator<= (const BigInteger & other) const noexcept
References BigInteger(), and compare().
operator>()
bool yup::BigInteger::operator> (const BigInteger & other) const noexcept
References BigInteger(), and compare().
operator>=()
bool yup::BigInteger::operator>= (const BigInteger & other) const noexcept
References BigInteger(), and compare().
compare()
int yup::BigInteger::compare (const BigInteger & other) const noexcept
Does a signed comparison of two BigIntegers.
Return values are:
0 if the numbers are the same
< 0 if this number is smaller than the other
> 0 if this number is bigger than the other
References BigInteger(), compareAbsolute(), and isNegative().
Referenced by montgomeryMultiplication(), operator!=(), operator<(), operator<=(), operator==(), operator>(), operator>=(), and ~BigInteger().
compareAbsolute()
int yup::BigInteger::compareAbsolute (const BigInteger & other) const noexcept
Compares the magnitudes of two BigIntegers, ignoring their signs.
Return values are:
0 if the numbers are the same
< 0 if this number is smaller than the other
> 0 if this number is bigger than the other
References BigInteger(), and getHighestBit().
Referenced by compare(), divideBy(), exponentModulo(), extendedEuclidean(), inverseModulo(), operator+=(), operator-=(), and ~BigInteger().
divideBy()
void yup::BigInteger::divideBy (const BigInteger & divisor, BigInteger & remainder)
Divides this value by another one and returns the remainder.
This number is divided by other, leaving the quotient in this number, with the remainder being copied to the other BigInteger passed in.
References BigInteger(), clear(), compareAbsolute(), divideBy(), getHighestBit(), isNegative(), setBit(), setNegative(), and swapWith().
Referenced by divideBy(), findGreatestCommonDivisor(), inverseModulo(), operator%=(), operator/=(), and ~BigInteger().
findGreatestCommonDivisor()
BigInteger yup::BigInteger::findGreatestCommonDivisor (BigInteger other) const
Returns the largest value that will divide both this value and the argument.
References BigInteger(), divideBy(), getHighestBit(), isZero(), and swapWith().
Referenced by inverseModulo(), and ~BigInteger().
exponentModulo()
void yup::BigInteger::exponentModulo (const BigInteger & exponent, const BigInteger & modulus)
Performs a combined exponent and modulo operation.
This BigInteger's value becomes (this ^ exponent) % modulus.
References BigInteger(), compareAbsolute(), extendedEuclidean(), getHighestBit(), isOne(), montgomeryMultiplication(), and swapWith().
Referenced by ~BigInteger().
inverseModulo()
void yup::BigInteger::inverseModulo (const BigInteger & modulus)
Performs an inverse modulo on the value.
i.e. the result is (this ^ -1) mod (modulus).
References BigInteger(), clear(), compareAbsolute(), divideBy(), findGreatestCommonDivisor(), isNegative(), isOne(), and swapWith().
Referenced by ~BigInteger().
montgomeryMultiplication()
void yup::BigInteger::montgomeryMultiplication (const BigInteger & other, const BigInteger & modulus, const BigInteger & modulusp, int k)
Performs the Montgomery Multiplication with modulo.
This object is left containing the result value: ((this * other) * R1) % modulus. To get this result, we need modulus, modulusp and k such as R = 2^k, with modulus * modulusp - R * R1 = GCD(modulus, R) = 1
References BigInteger(), compare(), isNegative(), and setRange().
Referenced by exponentModulo(), and ~BigInteger().
extendedEuclidean()
void yup::BigInteger::extendedEuclidean (const BigInteger & a, const BigInteger & b, BigInteger & xOut, BigInteger & yOut)
Performs the Extended Euclidean algorithm.
This method will set the xOut and yOut arguments such that (a * xOut) - (b * yOut) = GCD (a, b). On return, this object is left containing the value of the GCD.
References yup::Array< ElementType, TypeOfCriticalSectionToUse, minimumAllocatedSize >::add(), BigInteger(), clear(), compareAbsolute(), yup::Array< ElementType, TypeOfCriticalSectionToUse, minimumAllocatedSize >::getReference(), negate(), yup::Array< ElementType, TypeOfCriticalSectionToUse, minimumAllocatedSize >::size(), and swapWith().
Referenced by exponentModulo(), and ~BigInteger().
toString()
String yup::BigInteger::toString (int base, int minimumNumCharacters = 1) const
Converts the number to a string.
Specify a base such as 2 (binary), 8 (octal), 10 (decimal), 16 (hex). If minimumNumCharacters is greater than 0, the returned string will be padded with leading zeros to reach at least that length.
References BigInteger(), yup::String::charToString(), getBitRangeAsInt(), isNegative(), isZero(), and yup::String::paddedLeft().
Referenced by yup::operator<<(), and ~BigInteger().
parseString()
void yup::BigInteger::parseString (StringRef text, int base)
Reads the numeric value from a string.
Specify a base such as 2 (binary), 8 (octal), 10 (decimal), 16 (hex). Any invalid characters will be ignored.
References BigInteger(), clear(), yup::CharPointer_UTF8::findEndOfWhitespace(), yup::CharacterFunctions::getHexDigitValue(), setNegative(), and yup::StringRef::text.
Referenced by ~BigInteger().
toMemoryBlock()
MemoryBlock yup::BigInteger::toMemoryBlock () const
Turns the number into a block of binary data.
The data is arranged as little-endian, so the first byte of data is the low 8 bits of the number, and so on.
See also
loadFromMemoryBlock
References getHighestBit().
Referenced by ~BigInteger().
loadFromMemoryBlock()
void yup::BigInteger::loadFromMemoryBlock (const MemoryBlock & data)
Converts a block of raw data into a number.
The data is arranged as little-endian, so the first byte of data is the low 8 bits of the number, and so on.
See also
toMemoryBlock
References yup::addBytesToPointer(), yup::MemoryBlock::getData(), getHighestBit(), yup::MemoryBlock::getSize(), yup::ByteOrder::littleEndianInt(), and setBitRangeAsInt().
Referenced by ~BigInteger().