YUP: yup::Path Class Reference
yup::Path Class Reference
Represents a 2D geometric path.
Public Member Functions
Path ()
Constructs an empty path.
Path (float x, float y)
Initializes a path and moves to the specified coordinates.
Path (const Point< float > &p)
Initializes a path and moves to the specified point.
Path (const Path &other) noexcept=default
Copy and move constructors and assignment operators.
Path (Path &&other) noexcept=default
Path & operator= (const Path &other) noexcept=default
Path & operator= (Path &&other) noexcept=default
void reserveSpace (int numSegments)
Reserves memory for a specified number of segments.
int size () const
Returns the number of segments in the path.
void clear ()
Clears all the segments from the path.
Path & moveTo (float x, float y)
Moves the current point to specified coordinates, starting a new sub-path.
Path & moveTo (const Point< float > &p)
Moves the current point to a specified point, starting a new sub-path.
Path & lineTo (float x, float y)
Draws a line from the current point to specified coordinates.
Path & lineTo (const Point< float > &p)
Draws a line from the current point to a specified point.
Path & quadTo (float x, float y, float x1, float y1)
Draws a quadratic Bezier curve to specified coordinates with one control point.
Path & quadTo (const Point< float > &p, float x1, float y1)
Draws a quadratic Bezier curve to specified coordinates with one control point.
Path & cubicTo (float x, float y, float x1, float y1, float x2, float y2)
Draws a cubic Bezier curve to specified coordinates with two control points.
Path & cubicTo (const Point< float > &p, float x1, float y1, float x2, float y2)
Draws a cubic Bezier curve to specified coordinates with two control points.
Path & close ()
Closes the current sub-path by drawing a line to the start point of the sub-path.
Path & addLine (const Point< float > &p1, const Point< float > &p2)
Adds a straight line segment to the path between two points.
Path & addLine (const Line< float > &line)
Adds a line segment described by a Line object to the path.
Path & addRectangle (float x, float y, float width, float height)
Adds a rectangle to the path.
Path & addRectangle (const Rectangle< float > &rect)
Adds a rectangle described by a Rectangle object to the path.
Path & addRoundedRectangle (float x, float y, float width, float height, float radiusTopLeft, float radiusTopRight, float radiusBottomLeft, float radiusBottomRight)
Adds a rounded rectangle to the path.
Path & addRoundedRectangle (float x, float y, float width, float height, float radius)
Adds a rounded rectangle to the path.
Path & addRoundedRectangle (const Rectangle< float > &rect, float radiusTopLeft, float radiusTopRight, float radiusBottomLeft, float radiusBottomRight)
Adds a rounded rectangle described by a Rectangle object with specific corner radii to the path.
Path & addRoundedRectangle (const Rectangle< float > &rect, float radius)
Adds a rounded rectangle to the path.
Path & addEllipse (float x, float y, float width, float height)
Adds an ellipse to the path.
Path & addEllipse (const Rectangle< float > &rect)
Adds an ellipse described by a Rectangle object to the path.
Path & addCenteredEllipse (float centerX, float centerY, float radiusX, float radiusY)
Adds a centered ellipse to the path.
Path & addCenteredEllipse (const Point< float > &center, float radiusX, float radiusY)
Adds a centered ellipse to the path.
Path & addCenteredEllipse (const Point< float > &center, const Size< float > &diameter)
Adds a centered ellipse to the path.
Path & addArc (float x, float y, float width, float height, float fromRadians, float toRadians, bool startAsNewSubPath)
Adds an arc to the path.
Path & addArc (const Rectangle< float > &rect, float fromRadians, float toRadians, bool startAsNewSubPath)
Adds an arc described by a Rectangle object to the path.
Path & addCenteredArc (float centerX, float centerY, float radiusX, float radiusY, float rotationOfEllipse, float fromRadians, float toRadians, bool startAsNewSubPath)
Adds a centered arc to the path.
Path & addCenteredArc (const Point< float > &center, float radiusX, float radiusY, float rotationOfEllipse, float fromRadians, float toRadians, bool startAsNewSubPath)
Adds a centered arc described by a Point object to the path.
Path & addCenteredArc (const Point< float > &center, const Size< float > &diameter, float rotationOfEllipse, float fromRadians, float toRadians, bool startAsNewSubPath)
Adds a centered arc described by a Point and Size object to the path.
Path & addPolygon (Point< float > centre, int numberOfSides, float radius, float startAngle=0.0f)
Adds a regular polygon to the path.
Path & addStar (Point< float > centre, int numberOfPoints, float innerRadius, float outerRadius, float startAngle=0.0f)
Adds a star shape to the path.
Path & addBubble (Rectangle< float > bodyArea, Rectangle< float > maximumArea, Point< float > arrowTipPosition, float cornerSize, float arrowBaseWidth)
Adds a speech bubble shape to the path.
Path createStrokePolygon (float strokeWidth) const
Converts the path to a stroke polygon with specified width.
Path withRoundedCorners (float cornerRadius) const
Creates a new path with rounded corners applied to this path.
Path & appendPath (const Path &other)
Appends another path to this one.
Path & appendPath (const Path &other, const AffineTransform &transform)
Appends another path to this one applying a transformation.
void swapWithPath (Path &other) noexcept
Swaps the contents of this path with another path.
Path & transform (const AffineTransform &t)
Transforms the path by applying an affine transformation.
Path transformed (const AffineTransform &t) const
Returns a new path with the specified transformation applied.
void scaleToFit (float x, float y, float width, float height, bool preserveProportions) noexcept
Scales the path to fit within the specified bounds.
Rectangle< float > getBounds () const
Returns the bounding box of this path.
Rectangle< float > getBoundsTransformed (const AffineTransform &transform) const
Returns the bounding box of this path after applying a transformation.
Point< float > getPointAlongPath (float distance) const
Gets a point at a specific position along the path.
bool parsePathData (const String &pathData)
Parses the path data from a string.
auto begin ()
Provides an iterator to the beginning of the path data.
auto begin () const
Provides a constant iterator to the beginning of the path data.
auto end ()
Provides an iterator to the end of the path data.
auto end () const
Provides a constant iterator to the end of the path data.
Path (rive::rcp< rive::RiveRenderPath > newPath)
rive::RiveRenderPath * getRenderPath () const
void appendPath (rive::rcp< rive::RiveRenderPath > other)
void appendPath (rive::rcp< rive::RiveRenderPath > other, const AffineTransform &transform)
Detailed Description
Represents a 2D geometric path.
The Path class encapsulates a series of geometric operations and shapes that can be described using lines, curves, and basic geometric shapes. It provides methods to construct and manipulate these paths with operations such as moving to a point, drawing lines, curves, rectangles, rounded rectangles, ellipses, and arcs. It supports both simple constructs such as lines and complex cubic Bezier curves.
This class uses an internal storage mechanism to keep track of each segment in the path, allowing for efficient modifications and rendering. The Path can be used for drawing operations, hit testing, and bounding box calculations.
Constructor & Destructor Documentation
Path() [1/6]
yup::Path::Path ()
Constructs an empty path.
Referenced by addArc(), addArc(), addBubble(), addCenteredArc(), addCenteredArc(), addCenteredArc(), addCenteredEllipse(), addCenteredEllipse(), addCenteredEllipse(), addEllipse(), addEllipse(), addLine(), addLine(), addPolygon(), addRectangle(), addRectangle(), addRoundedRectangle(), addRoundedRectangle(), addRoundedRectangle(), addRoundedRectangle(), addStar(), appendPath(), appendPath(), close(), createStrokePolygon(), cubicTo(), cubicTo(), lineTo(), lineTo(), moveTo(), moveTo(), operator=(), operator=(), Path(), Path(), Path(), Path(), quadTo(), quadTo(), swapWithPath(), transform(), transformed(), and withRoundedCorners().
Path() [2/6]
yup::Path::Path (float x, float y)
Initializes a path and moves to the specified coordinates.
This constructor creates a path and immediately moves the current point to the coordinates (x, y), starting a new sub-path.
Parameters
x The x-coordinate to move to.
y The y-coordinate to move to.
References moveTo(), and Path().
Path() [3/6]
yup::Path::Path (const Point< float > & p)
Initializes a path and moves to the specified point.
This constructor creates a path and immediately moves the current point to the given point, starting a new sub-path.
Parameters
p The point to move to.
References moveTo(), and Path().
Path() [4/6]
yup::Path::Path (const Path & other) default noexcept
Copy and move constructors and assignment operators.
References Path().
Path() [5/6]
yup::Path::Path (Path && other) default noexcept
References Path().
Path() [6/6]
yup::Path::Path (rive::rcp< rive::RiveRenderPath > newPath) explicit
Member Function Documentation
operator=() [1/2]
Path & yup::Path::operator= (const Path & other) default noexcept
References Path().
operator=() [2/2]
Path & yup::Path::operator= (Path && other) default noexcept
References addArc(), addBubble(), addCenteredArc(), addCenteredEllipse(), addEllipse(), addLine(), addPolygon(), addRectangle(), addRoundedRectangle(), addStar(), appendPath(), clear(), close(), createStrokePolygon(), cubicTo(), getBounds(), getBoundsTransformed(), getPointAlongPath(), lineTo(), moveTo(), parsePathData(), Path(), quadTo(), reserveSpace(), scaleToFit(), size(), swapWithPath(), transform(), transformed(), and withRoundedCorners().
reserveSpace()
void yup::Path::reserveSpace (int numSegments)
Reserves memory for a specified number of segments.
This method allocates memory in advance for a number of segments, potentially improving performance by reducing the number of memory allocations required as segments are added.
Parameters
numSegments The number of segments for which to reserve space.
Referenced by addCenteredEllipse(), addEllipse(), addPolygon(), addRectangle(), addRoundedRectangle(), addStar(), operator=(), and yup::Graphics::strokeLine().
size()
int yup::Path::size () const
Returns the number of segments in the path.
This method counts the total number of segments that have been added to the path, including all types of moves and draws.
Returns
The number of segments in the path.
References size().
Referenced by addCenteredEllipse(), addEllipse(), addPolygon(), addRectangle(), addRoundedRectangle(), addStar(), operator=(), and size().
clear()
void yup::Path::clear ()
Clears all the segments from the path.
This method removes all segments from the path, effectively resetting it to an empty state.
Referenced by operator=().
moveTo() [1/2]
Path & yup::Path::moveTo (float x, float y)
Moves the current point to specified coordinates, starting a new sub-path.
This command does not produce any visible output but updates the current point to the specified coordinates. It starts a new sub-path that subsequent commands are considered part of.
Parameters
x The x-coordinate to move to.
y The y-coordinate to move to.
References moveTo(), and Path().
Referenced by addBubble(), addCenteredArc(), addCenteredEllipse(), addEllipse(), addLine(), addLine(), addPolygon(), addRectangle(), addRoundedRectangle(), addStar(), createStrokePolygon(), moveTo(), moveTo(), operator=(), Path(), Path(), quadTo(), and yup::Graphics::strokeLine().
moveTo() [2/2]
Path & yup::Path::moveTo (const Point< float > & p)
Moves the current point to a specified point, starting a new sub-path.
This command does not produce any visible output but updates the current point to the specified point. It starts a new sub-path that subsequent commands are considered part of.
Parameters
p The point to move to.
References yup::Point< ValueType >::getX(), yup::Point< ValueType >::getY(), moveTo(), and Path().
lineTo() [1/2]
Path & yup::Path::lineTo (float x, float y)
Draws a line from the current point to specified coordinates.
This method draws a straight line from the current point to the coordinates (x, y), then updates the current point to these coordinates.
Parameters
x The x-coordinate of the endpoint.
y The y-coordinate of the endpoint.
References lineTo(), and Path().
Referenced by addBubble(), addCenteredArc(), addLine(), addLine(), addPolygon(), addRectangle(), addRoundedRectangle(), addStar(), createStrokePolygon(), lineTo(), lineTo(), operator=(), and yup::Graphics::strokeLine().
lineTo() [2/2]
Path & yup::Path::lineTo (const Point< float > & p)
Draws a line from the current point to a specified point.
This method draws a straight line from the current point to the specified point, then updates the current point to this new location.
Parameters
p The point to draw the line to.
References yup::Point< ValueType >::getX(), yup::Point< ValueType >::getY(), lineTo(), and Path().
quadTo() [1/2]
Path & yup::Path::quadTo (float x, float y, float x1, float y1)
Draws a quadratic Bezier curve to specified coordinates with one control point.
This method draws a quadratic Bezier curve from the current point to the point (x, y), using (x1, y1) as the control point. The current point is then set to (x, y).
Parameters
x The x-coordinate of the endpoint.
y The y-coordinate of the endpoint.
x1 The x-coordinate of the control point.
y1 The y-coordinate of the control point.
References moveTo(), and Path().
Referenced by operator=(), and quadTo().
quadTo() [2/2]
Path & yup::Path::quadTo (const Point< float > & p, float x1, float y1)
Draws a quadratic Bezier curve to specified coordinates with one control point.
This method draws a quadratic Bezier curve from the current point to the point (x, y), using the given point p as the control point. The current point is then set to (x, y).
Parameters
p The control point.
x1 The x-coordinate of the endpoint.
y1 The y-coordinate of the endpoint.
References yup::Point< ValueType >::getX(), yup::Point< ValueType >::getY(), Path(), and quadTo().
cubicTo() [1/2]
Path & yup::Path::cubicTo (float x, float y, float x1, float y1, float x2, float y2)
Draws a cubic Bezier curve to specified coordinates with two control points.
This method draws a cubic Bezier curve from the current point to the point (x, y), using (x1, y1) and (x2, y2) as the control points. The current point is then updated to (x, y).
Parameters
x The x-coordinate of the endpoint.
y The y-coordinate of the endpoint.
x1 The x-coordinate of the first control point.
y1 The y-coordinate of the first control point.
x2 The x-coordinate of the second control point.
y2 The y-coordinate of the second control point.
References cubicTo(), and Path().
Referenced by addBubble(), addCenteredEllipse(), addEllipse(), addRoundedRectangle(), cubicTo(), cubicTo(), and operator=().
cubicTo() [2/2]
Path & yup::Path::cubicTo (const Point< float > & p, float x1, float y1, float x2, float y2)
Draws a cubic Bezier curve to specified coordinates with two control points.
This method draws a cubic Bezier curve from the current point to the endpoint (x1, y1), using the given point p and (x2, y2) as the control points. The current point is then updated to (x1, y1).
Parameters
p The first control point.
x1 The x-coordinate of the second control point.
y1 The y-coordinate of the second control point.
x2 The x-coordinate of the endpoint.
y2 The y-coordinate of the endpoint.
References cubicTo(), yup::Point< ValueType >::getX(), yup::Point< ValueType >::getY(), and Path().
close()
Path & yup::Path::close ()
Closes the current sub-path by drawing a line to the start point of the sub-path.
This method completes the current sub-path by drawing a line back to the starting point of the sub-path, effectively closing any open figures and making them ready for fill operations. This does not affect the current point.
References close(), and Path().
Referenced by addBubble(), addCenteredEllipse(), addEllipse(), addPolygon(), addStar(), close(), createStrokePolygon(), operator=(), and parsePathData().
addLine() [1/2]
Path & yup::Path::addLine (const Point< float > & p1, const Point< float > & p2)
Adds a straight line segment to the path between two points.
This method appends a line from point p1 to point p2 to the path. This operation updates the current point to p2.
Parameters
p1 The starting point of the line.
p2 The ending point of the line.
References lineTo(), moveTo(), and Path().
Referenced by operator=(), and yup::paintSlider().
addLine() [2/2]
Path & yup::Path::addLine (const Line< float > & line)
Adds a line segment described by a Line object to the path.
This method appends the line specified by the Line object to the path, updating the current point to the end of the line.
Parameters
line The line to add to the path.
References yup::Line< ValueType >::getEnd(), yup::Line< ValueType >::getStart(), lineTo(), moveTo(), and Path().
addRectangle() [1/2]
Path & yup::Path::addRectangle (float x, float y, float width, float height)
Adds a rectangle to the path.
This method appends a rectangle with the specified position and size to the path. The rectangle is added as a closed sub-path, starting and ending at the top-left corner.
Parameters
x The x-coordinate of the top-left corner of the rectangle.
y The y-coordinate of the top-left corner of the rectangle.
width The width of the rectangle.
height The height of the rectangle.
References yup::jmax(), lineTo(), moveTo(), Path(), reserveSpace(), and size().
Referenced by addRectangle(), yup::Graphics::fillAll(), yup::Graphics::fillRect(), operator=(), yup::Graphics::setClipPath(), and yup::Graphics::strokeRect().
addRectangle() [2/2]
Path & yup::Path::addRectangle (const Rectangle< float > & rect)
Adds a rectangle described by a Rectangle object to the path.
This method appends the rectangle specified by the Rectangle object to the path, adding it as a closed sub-path, starting and ending at the top-left corner of the rectangle.
Parameters
rect The rectangle to add to the path.
References addRectangle(), yup::Rectangle< ValueType >::getHeight(), yup::Rectangle< ValueType >::getWidth(), yup::Rectangle< ValueType >::getX(), yup::Rectangle< ValueType >::getY(), and Path().
addRoundedRectangle() [1/4]
Path & yup::Path::addRoundedRectangle (float x, float y, float width, float height, float radiusTopLeft, float radiusTopRight, float radiusBottomLeft, float radiusBottomRight)
Adds a rounded rectangle to the path.
This method appends a rounded rectangle with specified position, size, and corner radii to the path. Each corner can have a different radius, allowing for complex shapes. The rounded rectangle is added as a closed sub-path.
Parameters
x The x-coordinate of the top-left corner.
y The y-coordinate of the top-left corner.
width The width of the rectangle.
height The height of the rectangle.
radiusTopLeft The radius of the top-left corner.
radiusTopRight The radius of the top-right corner.
radiusBottomLeft The radius of the bottom-left corner.
radiusBottomRight The radius of the bottom-right corner.
References cubicTo(), yup::jmax(), yup::jmin(), lineTo(), moveTo(), Path(), reserveSpace(), and size().
Referenced by addBubble(), addRoundedRectangle(), addRoundedRectangle(), addRoundedRectangle(), yup::Graphics::fillRoundedRect(), operator=(), and yup::Graphics::strokeRoundedRect().
addRoundedRectangle() [2/4]
Path & yup::Path::addRoundedRectangle (float x, float y, float width, float height, float radius)
Adds a rounded rectangle to the path.
This method appends a rounded rectangle with specified position, size, and corner radius to the path. Each corner has the same radius, allowing for simple rounded corners. The rounded rectangle is added as a closed sub-path.
Parameters
x The x-coordinate of the top-left corner.
y The y-coordinate of the top-left corner.
width The width of the rectangle.
References addRoundedRectangle(), and Path().
addRoundedRectangle() [3/4]
Path & yup::Path::addRoundedRectangle (const Rectangle< float > & rect, float radiusTopLeft, float radiusTopRight, float radiusBottomLeft, float radiusBottomRight)
Adds a rounded rectangle described by a Rectangle object with specific corner radii to the path.
This method appends a rounded rectangle specified by the Rectangle object and corner radii to the path. Each corner of the rectangle can have a different radius, which provides flexibility in the appearance of the corners. The rounded rectangle is added as a closed sub-path.
Parameters
rect The rectangle to which rounded corners are to be added.
radiusTopLeft The radius of the top-left corner.
radiusTopRight The radius of the top-right corner.
radiusBottomLeft The radius of the bottom-left corner.
radiusBottomRight The radius of the bottom-right corner.
References addRoundedRectangle(), yup::Rectangle< ValueType >::getHeight(), yup::Rectangle< ValueType >::getWidth(), yup::Rectangle< ValueType >::getX(), yup::Rectangle< ValueType >::getY(), and Path().
addRoundedRectangle() [4/4]
Path & yup::Path::addRoundedRectangle (const Rectangle< float > & rect, float radius)
Adds a rounded rectangle to the path.
This method appends a rounded rectangle with specified position, size, and corner radius to the path. Each corner has the same radius, allowing for simple rounded corners. The rounded rectangle is added as a closed sub-path.
Parameters
rect The rectangle to which rounded corners are to be added.
References addRoundedRectangle(), yup::Rectangle< ValueType >::getHeight(), yup::Rectangle< ValueType >::getWidth(), yup::Rectangle< ValueType >::getX(), yup::Rectangle< ValueType >::getY(), and Path().
addEllipse() [1/2]
Path & yup::Path::addEllipse (float x, float y, float width, float height)
Adds an ellipse to the path.
This method appends an ellipse with the specified position and size to the path. The ellipse is defined within a bounding rectangle, starting and ending at the rightmost point of the ellipse.
Parameters
x The x-coordinate of the top-left corner of the bounding rectangle.
y The y-coordinate of the top-left corner of the bounding rectangle.
width The width of the bounding rectangle.
height The height of the bounding rectangle.
References close(), cubicTo(), yup::jmax(), moveTo(), Path(), reserveSpace(), and size().
Referenced by addEllipse(), operator=(), and yup::paintSlider().
addEllipse() [2/2]
Path & yup::Path::addEllipse (const Rectangle< float > & rect)
Adds an ellipse described by a Rectangle object to the path.
This method appends an ellipse defined within the bounding rectangle specified by the Rectangle object to the path. The ellipse starts and ends at the rightmost point of the ellipse, forming a complete and closed sub-path.
Parameters
rect The rectangle that bounds the ellipse.
References addEllipse(), yup::Rectangle< ValueType >::getHeight(), yup::Rectangle< ValueType >::getWidth(), yup::Rectangle< ValueType >::getX(), yup::Rectangle< ValueType >::getY(), and Path().
addCenteredEllipse() [1/3]
Path & yup::Path::addCenteredEllipse (float centerX, float centerY, float radiusX, float radiusY)
Adds a centered ellipse to the path.
This method appends an ellipse centered at (centerX, centerY) with specified radii. The ellipse starts and ends at the rightmost point of the ellipse, forming a complete and closed sub-path.
Parameters
centerX The x-coordinate of the center of the ellipse.
centerY The y-coordinate of the center of the ellipse.
radiusX The horizontal radius of the ellipse.
References close(), cubicTo(), yup::jmax(), moveTo(), Path(), reserveSpace(), and size().
Referenced by addCenteredEllipse(), addCenteredEllipse(), and operator=().
addCenteredEllipse() [2/3]
Path & yup::Path::addCenteredEllipse (const Point< float > & center, float radiusX, float radiusY)
Adds a centered ellipse to the path.
This method appends an ellipse centered at the specified point with given radii. The ellipse starts and ends at the rightmost point of the ellipse, forming a complete and closed sub-path.
Parameters
center The center point of the ellipse.
radiusX The horizontal radius of the ellipse.
References addCenteredEllipse(), yup::Point< ValueType >::getX(), yup::Point< ValueType >::getY(), and Path().
addCenteredEllipse() [3/3]
Path & yup::Path::addCenteredEllipse (const Point< float > & center, const Size< float > & diameter)
Adds a centered ellipse to the path.
This method appends an ellipse centered at the specified point with given diameter. The ellipse starts and ends at the rightmost point of the ellipse, forming a complete and closed sub-path.
Parameters
center The center point of the ellipse.
diameter The diameter of the ellipse.
References addCenteredEllipse(), yup::Size< ValueType >::getHeight(), yup::Size< ValueType >::getWidth(), yup::Point< ValueType >::getX(), yup::Point< ValueType >::getY(), and Path().
addArc() [1/2]
Path & yup::Path::addArc (float x, float y, float width, float height, float fromRadians, float toRadians, bool startAsNewSubPath)
Adds an arc to the path.
This method appends an arc defined within a bounding rectangle, between two radial angles. The arc can optionally start as a new sub-path or continue from the current point.
Parameters
x The x-coordinate of the top-left corner of the bounding rectangle.
y The y-coordinate of the top-left corner of the bounding rectangle.
width The width of the bounding rectangle.
height The height of the bounding rectangle.
fromRadians The starting angle of the arc, in radians.
toRadians The ending angle of the arc, in radians.
startAsNewSubPath Whether to start this as a new sub-path or continue from the current point.
References addCenteredArc(), yup::jmax(), and Path().
Referenced by addArc(), and operator=().
addArc() [2/2]
Path & yup::Path::addArc (const Rectangle< float > & rect, float fromRadians, float toRadians, bool startAsNewSubPath)
Adds an arc described by a Rectangle object to the path.
This method appends an arc that is defined within the bounding rectangle specified by the Rectangle object, between two radial angles. The arc can either start as a new sub-path or connect to the current point depending on the specified boolean.
Parameters
rect The rectangle that bounds the arc.
fromRadians The starting angle of the arc, in radians.
toRadians The ending angle of the arc, in radians.
startAsNewSubPath Whether to start this as a new sub-path or continue from the current point.
References addArc(), yup::Rectangle< ValueType >::getHeight(), yup::Rectangle< ValueType >::getWidth(), yup::Rectangle< ValueType >::getX(), yup::Rectangle< ValueType >::getY(), and Path().
addCenteredArc() [1/3]
Path & yup::Path::addCenteredArc (float centerX, float centerY, float radiusX, float radiusY, float rotationOfEllipse, float fromRadians, float toRadians, bool startAsNewSubPath)
Adds a centered arc to the path.
This method appends an arc centered at (centerX, centerY) with specified radii and rotation, between two radial angles. The arc can start as a new sub-path or continue from the current point.
Parameters
centerX The x-coordinate of the center of the arc.
centerY The y-coordinate of the center of the arc.
radiusX The horizontal radius of the arc.
radiusY The vertical radius of the arc.
rotationOfEllipse The rotation angle of the ellipse, in radians.
fromRadians The starting angle of the arc, in radians.
toRadians The ending angle of the arc, in radians.
startAsNewSubPath Whether to start this as a new sub-path or continue from the current point.
References yup::jlimit(), yup::jmax(), lineTo(), moveTo(), and Path().
Referenced by addArc(), addCenteredArc(), addCenteredArc(), operator=(), and yup::paintSlider().
addCenteredArc() [2/3]
Path & yup::Path::addCenteredArc (const Point< float > & center, float radiusX, float radiusY, float rotationOfEllipse, float fromRadians, float toRadians, bool startAsNewSubPath)
Adds a centered arc described by a Point object to the path.
This method appends an arc centered at the specified point with given radii and rotation, between two radial angles. The arc can either start as a new sub-path or connect to the current point depending on the specified boolean.
Parameters
center The center point of the arc.
radiusX The horizontal radius of the arc.
radiusY The vertical radius of the arc.
rotationOfEllipse The rotation angle of the ellipse, in radians.
fromRadians The starting angle of the arc, in radians.
toRadians The ending angle of the arc, in radians.
startAsNewSubPath Whether to start this as a new sub-path or continue from the current point.
References addCenteredArc(), yup::Point< ValueType >::getX(), yup::Point< ValueType >::getY(), and Path().
addCenteredArc() [3/3]
Path & yup::Path::addCenteredArc (const Point< float > & center, const Size< float > & diameter, float rotationOfEllipse, float fromRadians, float toRadians, bool startAsNewSubPath)
Adds a centered arc described by a Point and Size object to the path.
This method appends an arc centered at the specified point with given diameter and rotation, between two radial angles. The arc can either start as a new sub-path or connect to the current point depending on the specified boolean.
Parameters
center The center point of the arc.
diameter The diameter of the arc.
rotationOfEllipse The rotation angle of the ellipse, in radians.
References addCenteredArc(), yup::Size< ValueType >::getHeight(), yup::Size< ValueType >::getWidth(), yup::Point< ValueType >::getX(), yup::Point< ValueType >::getY(), and Path().
addPolygon()
Path & yup::Path::addPolygon (Point< float > centre, int numberOfSides, float radius, float startAngle = 0.0f)
Adds a regular polygon to the path.
This method appends a regular polygon with the specified number of sides, centered at the given point with the specified radius. The polygon starts at the given angle.
Parameters
centre The center point of the polygon.
numberOfSides The number of sides for the polygon (minimum 3).
radius The radius from the center to each vertex.
startAngle The starting angle in radians (0.0f starts at the right).
References close(), yup::Point< ValueType >::getX(), yup::Point< ValueType >::getY(), yup::jmax(), lineTo(), moveTo(), Path(), reserveSpace(), size(), and yup::MathConstants< FloatType >::twoPi.
Referenced by operator=().
addStar()
Path & yup::Path::addStar (Point< float > centre, int numberOfPoints, float innerRadius, float outerRadius, float startAngle = 0.0f)
Adds a star shape to the path.
This method appends a star shape with the specified number of points, centered at the given point with inner and outer radii. The star starts at the given angle.
Parameters
centre The center point of the star.
numberOfPoints The number of points for the star (minimum 3).
innerRadius The radius from the center to the inner vertices.
outerRadius The radius from the center to the outer vertices.
startAngle The starting angle in radians (0.0f starts at the right).
References close(), yup::Point< ValueType >::getX(), yup::Point< ValueType >::getY(), yup::jmax(), lineTo(), moveTo(), Path(), reserveSpace(), size(), and yup::MathConstants< FloatType >::twoPi.
Referenced by operator=().
addBubble()
Path & yup::Path::addBubble (Rectangle< float > bodyArea, Rectangle< float > maximumArea, Point< float > arrowTipPosition, float cornerSize, float arrowBaseWidth)
Adds a speech bubble shape to the path.
This method creates a rounded rectangle with an arrow pointing to the specified tip position, suitable for speech bubbles or callout shapes.
Parameters
bodyArea The main rectangular area of the bubble.
maximumArea The maximum area the bubble (including arrow) can occupy.
arrowTipPosition The point where the arrow should point to.
cornerSize The radius of the rounded corners.
arrowBaseWidth The width of the arrow at its base.
References addRoundedRectangle(), close(), yup::Rectangle< ValueType >::contains(), cubicTo(), yup::Rectangle< ValueType >::getBottom(), yup::Rectangle< ValueType >::getCenter(), yup::Rectangle< ValueType >::getHeight(), yup::Rectangle< ValueType >::getRight(), yup::Rectangle< ValueType >::getWidth(), yup::Point< ValueType >::getX(), yup::Rectangle< ValueType >::getX(), yup::Point< ValueType >::getY(), yup::Rectangle< ValueType >::getY(), yup::Rectangle< ValueType >::isEmpty(), yup::jlimit(), yup::jmin(), lineTo(), moveTo(), and Path().
Referenced by operator=().
createStrokePolygon()
Path yup::Path::createStrokePolygon (float strokeWidth) const
Converts the path to a stroke polygon with specified width.
This method generates a closed polygon that represents the stroke of this path with the given stroke width. The resulting path can be filled to achieve the appearance of a stroked path.
Parameters
strokeWidth The width of the stroke.
Returns
A new Path representing the stroke as a closed polygon.
References close(), yup::Point< ValueType >::getX(), yup::Point< ValueType >::getY(), lineTo(), yup::Point< ValueType >::magnitude(), moveTo(), yup::Point< ValueType >::normalize(), and Path().
Referenced by operator=().
withRoundedCorners()
Path yup::Path::withRoundedCorners (float cornerRadius) const
Creates a new path with rounded corners applied to this path.
This method generates a new path where sharp corners are replaced with rounded corners of the specified radius.
Parameters
cornerRadius The radius of the rounded corners.
Returns
A new Path with rounded corners applied.
References Path().
Referenced by operator=().
appendPath() [1/4]
Path & yup::Path::appendPath (const Path & other)
Appends another path to this one.
This method appends all segments of another path to this path. It effectively concatenates the other path onto this one, continuing from the current point of this path.
Parameters
other The path to append to this path.
References getRenderPath(), and Path().
Referenced by operator=().
appendPath() [2/4]
Path & yup::Path::appendPath (const Path & other, const AffineTransform & transform)
Appends another path to this one applying a transformation.
This method appends all segments of another path to this path applying an affine transformation to its point before being added.
Parameters
other The path with transformation to append to this path.
References getRenderPath(), Path(), and transform().
swapWithPath()
void yup::Path::swapWithPath (Path & other) noexcept
Swaps the contents of this path with another path.
This method efficiently swaps the internal data of this path with another path.
Parameters
other The path to swap with.
References Path().
Referenced by operator=().
transform()
Path & yup::Path::transform (const AffineTransform & t)
Transforms the path by applying an affine transformation.
This method applies an affine transformation to the path, modifying its shape and position. The transformation is specified by an AffineTransform object.
Parameters
t The affine transformation to apply.
Returns
A reference to this path after the transformation.
References Path(), and yup::AffineTransform::toMat2D().
Referenced by appendPath(), appendPath(), getBoundsTransformed(), operator=(), and scaleToFit().
transformed()
Path yup::Path::transformed (const AffineTransform & t) const
Returns a new path with the specified transformation applied.
This method creates a new path with the same shape as this path, but with the specified transformation applied. The transformation is specified by an AffineTransform object.
Parameters
t The affine transformation to apply.
Returns
A new Path with the transformation applied.
References Path(), and yup::AffineTransform::toMat2D().
Referenced by operator=(), and scaleToFit().
scaleToFit()
void yup::Path::scaleToFit (float x, float y, float width, float height, bool preserveProportions) noexcept
Scales the path to fit within the specified bounds.
This method transforms the path so that it fits within the given rectangular area. If preserveProportions is true, the aspect ratio is maintained.
Parameters
x The x-coordinate of the target area.
y The y-coordinate of the target area.
width The width of the target area.
height The height of the target area.
preserveProportions Whether to maintain the original aspect ratio.
References getBounds(), yup::Rectangle< ValueType >::getHeight(), yup::Rectangle< ValueType >::getWidth(), yup::Rectangle< ValueType >::getX(), yup::Rectangle< ValueType >::getY(), yup::Rectangle< ValueType >::isEmpty(), yup::jmin(), yup::AffineTransform::scaling(), transform(), transformed(), and yup::AffineTransform::translated().
Referenced by operator=().
getBounds()
Rectangle< float > yup::Path::getBounds () const
Returns the bounding box of this path.
Returns
The bounding rectangle that contains all points in this path.
Referenced by getBoundsTransformed(), operator=(), and scaleToFit().
getBoundsTransformed()
Rectangle< float > yup::Path::getBoundsTransformed (const AffineTransform & transform) const
Returns the bounding box of this path after applying a transformation.
Parameters
transform The transformation to apply before calculating the bounds.
Returns
The bounding rectangle that contains all transformed points in this path.
References getBounds(), transform(), and yup::Rectangle< ValueType >::transformed().
Referenced by operator=().
getPointAlongPath()
Point< float > yup::Path::getPointAlongPath (float distance) const
Gets a point at a specific position along the path.
This method returns a point located at the specified normalized distance along the path. The distance parameter should be between 0.0 (start of path) and 1.0 (end of path).
Parameters
distance The normalized distance along the path (0.0 to 1.0).
Returns
The point at the specified distance along the path.
References yup::Point< ValueType >::distanceTo(), end(), yup::jlimit(), and yup::Point< ValueType >::pointBetween().
Referenced by operator=().
parsePathData()
bool yup::Path::parsePathData (const String & pathData)
Parses the path data from a string.
This method parses the path data from a string and updates the path accordingly.
Parameters
pathData The string containing the path data.
Returns
True if the path data was parsed successfully, false otherwise.
References close(), yup::String::getCharPointer(), and yup::CharPointer_UTF8::isEmpty().
Referenced by operator=().
begin() [1/2]
auto yup::Path::begin ()
Provides an iterator to the beginning of the path data.
This method returns an iterator pointing to the first segment in the path's internal data. It allows for iteration over the path's segments from the beginning to the end.
Returns
An iterator to the beginning of the path data.
begin() [2/2]
auto yup::Path::begin () const
Provides a constant iterator to the beginning of the path data.
This method returns a constant iterator pointing to the first segment in the path's internal data. It ensures that the path data cannot be modified during the iteration.
Returns
A constant iterator to the beginning of the path data.
end() [1/2]
auto yup::Path::end ()
Provides an iterator to the end of the path data.
This method returns an iterator pointing just past the last segment in the path's internal data. It is used in conjunction with begin() for range-based iteration over the path's segments.
Returns
An iterator to the end of the path data.
Referenced by getPointAlongPath().
end() [2/2]
auto yup::Path::end () const
Provides a constant iterator to the end of the path data.
This method returns a constant iterator pointing just past the last segment in the path's internal data. It ensures safe iteration over the path segments without modifying them.
Returns
A constant iterator to the end of the path data.
getRenderPath()
rive::RiveRenderPath * yup::Path::getRenderPath () const
Referenced by appendPath(), and appendPath().
appendPath() [3/4]
void yup::Path::appendPath (rive::rcp< rive::RiveRenderPath > other)
appendPath() [4/4]
void yup::Path::appendPath (rive::rcp< rive::RiveRenderPath > other, const AffineTransform & transform)
References transform().