YUP: yup::ChildProcess Class Reference
yup::ChildProcess Class Reference
Launches and monitors a child process.
Public Types
enum StreamFlags { wantStdOut = 1 , wantStdErr = 2 }
These flags are used by the start() methods.
Public Member Functions
ChildProcess ()
Creates a process object.
~ChildProcess ()
Destructor.
bool start (const String &command, int streamFlags=wantStdOut|wantStdErr)
Attempts to launch a child process command.
bool start (const String &command, const StringPairArray &environment, int streamFlags=wantStdOut|wantStdErr)
Attempts to launch a child process command, using a custom environment.
bool start (const StringArray &arguments, int streamFlags=wantStdOut|wantStdErr)
Attempts to launch a child process command.
bool start (const StringArray &arguments, const StringPairArray &environment, int streamFlags=wantStdOut|wantStdErr)
Attempts to launch a child process command, using a custom environment.
bool isRunning () const
Returns true if the child process is alive.
int readProcessOutput (void *destBuffer, int numBytesToRead)
Attempts to read some output from the child process.
String readAllProcessOutput ()
Blocks until the process has finished, and then returns its complete output as a string.
bool waitForProcessToFinish (int timeoutMs) const
Blocks until the process is no longer running.
uint32 getExitCode () const
If the process has finished, this returns its exit code.
bool kill ()
Attempts to kill the child process.
Detailed Description
Launches and monitors a child process.
This class lets you launch an executable, and read its output. You can also use it to check whether the child process has finished.
Member Enumeration Documentation
StreamFlags
enum yup::ChildProcess::StreamFlags
These flags are used by the start() methods.
Enumerator
wantStdOut
wantStdErr
Constructor & Destructor Documentation
ChildProcess()
yup::ChildProcess::ChildProcess ()
Creates a process object.
To actually launch the process, use start().
Referenced by start().
~ChildProcess()
yup::ChildProcess::~ChildProcess ()
Destructor.
Note that deleting this object won't terminate the child process.
Member Function Documentation
start() [1/4]
bool yup::ChildProcess::start (const String & command, int streamFlags = wantStdOut|wantStdErr)
Attempts to launch a child process command.
The command should be the name of the executable file, followed by any arguments that are required. If the process has already been launched, this will launch it again. If a problem occurs, the method will return false. The streamFlags is a combinations of values to indicate which of the child's output streams should be read and returned by readProcessOutput().
References wantStdErr, and wantStdOut.
start() [2/4]
bool yup::ChildProcess::start (const String & command, const StringPairArray & environment, int streamFlags = wantStdOut|wantStdErr)
Attempts to launch a child process command, using a custom environment.
References wantStdErr, and wantStdOut.
start() [3/4]
bool yup::ChildProcess::start (const StringArray & arguments, int streamFlags = wantStdOut|wantStdErr)
Attempts to launch a child process command.
The first argument should be the name of the executable file, followed by any other arguments that are needed. If the process has already been launched, this will launch it again. If a problem occurs, the method will return false. The streamFlags is a combinations of values to indicate which of the child's output streams should be read and returned by readProcessOutput().
References wantStdErr, and wantStdOut.
start() [4/4]
bool yup::ChildProcess::start (const StringArray & arguments, const StringPairArray & environment, int streamFlags = wantStdOut|wantStdErr)
Attempts to launch a child process command, using a custom environment.
References ChildProcess(), getExitCode(), isRunning(), kill(), readAllProcessOutput(), readProcessOutput(), waitForProcessToFinish(), wantStdErr, and wantStdOut.
isRunning()
bool yup::ChildProcess::isRunning () const
Returns true if the child process is alive.
Referenced by start(), and waitForProcessToFinish().
readProcessOutput()
int yup::ChildProcess::readProcessOutput (void * destBuffer, int numBytesToRead)
Attempts to read some output from the child process.
This will attempt to read up to the given number of bytes of data from the process. It returns the number of bytes that were actually read.
Referenced by readAllProcessOutput(), and start().
readAllProcessOutput()
String yup::ChildProcess::readAllProcessOutput ()
Blocks until the process has finished, and then returns its complete output as a string.
References readProcessOutput(), yup::MemoryOutputStream::toString(), and yup::MemoryOutputStream::write().
Referenced by start().
waitForProcessToFinish()
bool yup::ChildProcess::waitForProcessToFinish (int timeoutMs) const
Blocks until the process is no longer running.
References yup::Time::getMillisecondCounter(), isRunning(), and yup::Thread::sleep().
Referenced by start().
getExitCode()
uint32 yup::ChildProcess::getExitCode () const
If the process has finished, this returns its exit code.
Referenced by start().
kill()
bool yup::ChildProcess::kill ()
Attempts to kill the child process.
Returns true if it succeeded. Trying to read from the process after calling this may result in undefined behaviour.
Referenced by start().