YUP: yup::var Class Reference
yup::var Class Reference
A variant class, that can be used to hold a range of primitive values.
Classes
struct NativeFunctionArgs
This structure is passed to a NativeFunction callback, and contains invocation details about the function's arguments and context.
Public Types
using NativeFunction = std::function<var (const NativeFunctionArgs&)>
Public Member Functions
var () noexcept
Creates a void variant.
~var () noexcept
Destructor.
var (const var &valueToCopy)
var (int value) noexcept
var (int64 value) noexcept
var (bool value) noexcept
var (double value) noexcept
var (const char *value)
var (const wchar_t *value)
var (const String &value)
var (StringRef value)
var (const Array< var > &value)
var (const StringArray &value)
var (ReferenceCountedObject *object)
var (std::unique_ptr< DynamicObject > object)
var (NativeFunction method) noexcept
var (const void *binaryData, size_t dataSize)
var (const MemoryBlock &binaryData)
var & operator= (const var &valueToCopy)
var & operator= (int value)
var & operator= (int64 value)
var & operator= (bool value)
var & operator= (double value)
var & operator= (const char *value)
var & operator= (const wchar_t *value)
var & operator= (const String &value)
var & operator= (StringRef value)
var & operator= (const MemoryBlock &value)
var & operator= (const Array< var > &value)
var & operator= (ReferenceCountedObject *object)
var & operator= (std::unique_ptr< DynamicObject > object)
var & operator= (NativeFunction method)
var (var &&) noexcept
var (String &&)
var (MemoryBlock &&)
var (Array< var > &&)
var & operator= (var &&) noexcept
var & operator= (String &&)
void swapWith (var &other) noexcept
operator int () const noexcept
operator int64 () const noexcept
operator bool () const noexcept
operator float () const noexcept
operator double () const noexcept
operator String () const
String toString () const
Array< var > * getArray () const noexcept
If this variant holds an array, this provides access to it.
MemoryBlock * getBinaryData () const noexcept
If this variant holds a memory block, this provides access to it.
ReferenceCountedObject * getObject () const noexcept
DynamicObject * getDynamicObject () const noexcept
bool isVoid () const noexcept
bool isUndefined () const noexcept
bool isInt () const noexcept
bool isInt64 () const noexcept
bool isBool () const noexcept
bool isDouble () const noexcept
bool isString () const noexcept
bool isObject () const noexcept
bool isArray () const noexcept
bool isBinaryData () const noexcept
bool isMethod () const noexcept
bool equals (const var &other) const noexcept
Returns true if this var has the same value as the one supplied.
bool equalsWithSameType (const var &other) const noexcept
Returns true if this var has the same value and type as the one supplied.
bool hasSameTypeAs (const var &other) const noexcept
Returns true if this var has the same type as the one supplied.
var clone () const noexcept
Returns a deep copy of this object.
int size () const
If the var is an array, this returns the number of elements.
const var & operator[] (int arrayIndex) const
If the var is an array, this can be used to return one of its elements.
var & operator[] (int arrayIndex)
If the var is an array, this can be used to return one of its elements.
void append (const var &valueToAppend)
Appends an element to the var, converting it to an array if it isn't already one.
void insert (int index, const var &value)
Inserts an element to the var, converting it to an array if it isn't already one.
void remove (int index)
If the var is an array, this removes one of its elements.
void resize (int numArrayElementsWanted)
Treating the var as an array, this resizes it to contain the specified number of elements.
int indexOf (const var &value) const
If the var is an array, this searches it for the first occurrence of the specified value, and returns its index.
const var & operator[] (const Identifier &propertyName) const
If this variant is an object, this returns one of its properties.
const var & operator[] (const char *propertyName) const
If this variant is an object, this returns one of its properties.
const var & operator[] (StringRef propertyName) const
If this variant is an object, this returns one of its properties.
var getProperty (const Identifier &propertyName, const var &defaultReturnValue) const
If this variant is an object, this returns one of its properties, or a default fallback value if the property is not set.
bool hasProperty (const Identifier &propertyName) const noexcept
Returns true if this variant is an object and if it has the given property.
var getMethod (const Identifier &methodName, const var &defaultReturnValue) const
If this variant is an object, this returns one of its methods, or a default fallback value if the property is not set.
bool hasMethod (const Identifier &methodName) const noexcept
Returns true if this variant is an object and if it has the given method.
var call (const Identifier &method) const
Invokes a named method call with no arguments.
var call (const Identifier &method, const var &arg1) const
Invokes a named method call with one argument.
var call (const Identifier &method, const var &arg1, const var &arg2) const
Invokes a named method call with 2 arguments.
var call (const Identifier &method, const var &arg1, const var &arg2, const var &arg3)
Invokes a named method call with 3 arguments.
var call (const Identifier &method, const var &arg1, const var &arg2, const var &arg3, const var &arg4) const
Invokes a named method call with 4 arguments.
var call (const Identifier &method, const var &arg1, const var &arg2, const var &arg3, const var &arg4, const var &arg5) const
Invokes a named method call with 5 arguments.
var invoke (const Identifier &method, const var *arguments, int numArguments) const
Invokes a named method call with a list of arguments.
NativeFunction getNativeFunction () const
If this object is a method, this returns the function pointer.
void writeToStream (OutputStream &output) const
Writes a binary representation of this value to a stream.
Static Public Member Functions
static var undefined () noexcept
Returns a var object that can be used where you need the javascript "undefined" value.
static var readFromStream (InputStream &input)
Reads back a stored binary representation of a value.
Detailed Description
A variant class, that can be used to hold a range of primitive values.
A var object can hold a range of simple primitive values, strings, or any kind of ReferenceCountedObject. The var class is intended to act like the kind of values used in dynamic scripting languages.
You can save/load var objects either in a small, proprietary binary format using writeToStream()/readFromStream(), or as JSON by using the JSON class.
See also
JSON, DynamicObject
Member Typedef Documentation
NativeFunction
using yup::var::NativeFunction = std::function<var (const NativeFunctionArgs&)>
Constructor & Destructor Documentation
var() [1/21]
yup::var::var () noexcept
Creates a void variant.
Referenced by append(), call(), call(), call(), call(), call(), call(), canCompare, clone(), equals(), equalsWithSameType(), getMethod(), getProperty(), hasSameTypeAs(), indexOf(), insert(), invoke(), yup::var::NativeFunctionArgs::NativeFunctionArgs(), operator=(), operator=(), operator=(), operator=(), operator=(), operator=(), operator=(), operator=(), operator=(), operator=(), operator=(), operator=(), operator=(), operator=(), operator=(), operator=(), operator[](), operator[](), operator[](), operator[](), operator[](), readFromStream(), swapWith(), undefined(), var(), var(), and var().
~var()
yup::var::~var () noexcept
Destructor.
var() [2/21]
yup::var::var (const var & valueToCopy)
References var().
var() [3/21]
yup::var::var (int value) noexcept
var() [4/21]
yup::var::var (int64 value) noexcept
var() [5/21]
yup::var::var (bool value) noexcept
var() [6/21]
yup::var::var (double value) noexcept
var() [7/21]
yup::var::var (const char * value)
var() [8/21]
yup::var::var (const wchar_t * value)
var() [9/21]
yup::var::var (const String & value)
var() [10/21]
yup::var::var (StringRef value)
var() [11/21]
yup::var::var (const Array< var > & value)
var() [12/21]
yup::var::var (const StringArray & value)
References yup::Array< ElementType, TypeOfCriticalSectionToUse, minimumAllocatedSize >::add(), yup::Array< ElementType, TypeOfCriticalSectionToUse, minimumAllocatedSize >::ensureStorageAllocated(), yup::StringArray::size(), and var().
var() [13/21]
yup::var::var (ReferenceCountedObject * object)
References yup::ReferenceCountedObject::incReferenceCount().
var() [14/21]
yup::var::var (std::unique_ptr< DynamicObject > object)
var() [15/21]
yup::var::var (NativeFunction method) noexcept
var() [16/21]
yup::var::var (const void * binaryData, size_t dataSize)
var() [17/21]
yup::var::var (const MemoryBlock & binaryData)
var() [18/21]
yup::var::var (var && other) noexcept
References var().
var() [19/21]
yup::var::var (String && v)
var() [20/21]
yup::var::var (MemoryBlock && v)
var() [21/21]
yup::var::var (Array< var > && v)
Member Function Documentation
operator=() [1/16]
var & yup::var::operator= (const var & valueToCopy)
References var().
operator=() [2/16]
var & yup::var::operator= (int value)
References var().
operator=() [3/16]
var & yup::var::operator= (int64 value)
References var().
operator=() [4/16]
var & yup::var::operator= (bool value)
References var().
operator=() [5/16]
var & yup::var::operator= (double value)
References var().
operator=() [6/16]
var & yup::var::operator= (const char * value)
References var().
operator=() [7/16]
var & yup::var::operator= (const wchar_t * value)
References var().
operator=() [8/16]
var & yup::var::operator= (const String & value)
References var().
operator=() [9/16]
var & yup::var::operator= (StringRef value)
References var().
operator=() [10/16]
var & yup::var::operator= (const MemoryBlock & value)
References var().
operator=() [11/16]
var & yup::var::operator= (const Array< var > & value)
References swapWith(), and var().
operator=() [12/16]
var & yup::var::operator= (ReferenceCountedObject * object)
References swapWith(), and var().
operator=() [13/16]
var & yup::var::operator= (std::unique_ptr< DynamicObject > object)
References swapWith(), and var().
operator=() [14/16]
var & yup::var::operator= (NativeFunction method)
References swapWith(), and var().
operator=() [15/16]
var & yup::var::operator= (var && other) noexcept
References swapWith(), and var().
operator=() [16/16]
var & yup::var::operator= (String && v)
References var().
swapWith()
void yup::var::swapWith (var & other) noexcept
References var().
Referenced by operator=(), operator=(), operator=(), operator=(), and operator=().
undefined()
var yup::var::undefined () static noexcept
Returns a var object that can be used where you need the javascript "undefined" value.
References var().
Referenced by yup::JavascriptEngine::callFunction(), yup::JavascriptEngine::callFunctionObject(), and yup::JavascriptEngine::evaluate().
operator int()
yup::var::operator int () const noexcept
operator int64()
yup::var::operator int64 () const noexcept
operator bool()
yup::var::operator bool () const noexcept
operator float()
yup::var::operator float () const noexcept
operator double()
yup::var::operator double () const noexcept
operator String()
yup::var::operator String () const
toString()
String yup::var::toString () const
Referenced by yup::operator!=(), yup::operator!=(), yup::operator==(), yup::operator==(), yup::PropertySet::setValue(), and yup::JSON::writeToStream().
getArray()
Array< var > * yup::var::getArray () const noexcept
If this variant holds an array, this provides access to it.
NOTE: Beware when you use this - the array pointer is only valid for the lifetime of the variant that returned it, so be very careful not to call this method on temporary var objects that are the return-value of a function, and which may go out of scope before you use the array!
Referenced by yup::JSONUtils::deepEqual(), indexOf(), operator[](), operator[](), remove(), yup::JSONUtils::setPointer(), size(), and yup::JSON::writeToStream().
getBinaryData()
MemoryBlock * yup::var::getBinaryData () const noexcept
If this variant holds a memory block, this provides access to it.
NOTE: Beware when you use this - the MemoryBlock pointer is only valid for the lifetime of the variant that returned it, so be very careful not to call this method on temporary var objects that are the return-value of a function, and which may go out of scope before you use the MemoryBlock!
getObject()
ReferenceCountedObject * yup::var::getObject () const noexcept
Referenced by getDynamicObject().
getDynamicObject()
DynamicObject * yup::var::getDynamicObject () const noexcept
References getObject().
Referenced by yup::JSONUtils::deepEqual(), getMethod(), getProperty(), hasMethod(), hasProperty(), invoke(), operator[](), yup::JSONUtils::setPointer(), and yup::JSON::writeToStream().
isVoid()
bool yup::var::isVoid () const noexcept
Referenced by yup::JSON::writeToStream().
isUndefined()
bool yup::var::isUndefined () const noexcept
Referenced by yup::JSON::writeToStream().
isInt()
bool yup::var::isInt () const noexcept
Referenced by yup::Artboard::setInput().
isInt64()
bool yup::var::isInt64 () const noexcept
Referenced by yup::Artboard::setInput().
isBool()
bool yup::var::isBool () const noexcept
Referenced by yup::Artboard::setInput(), and yup::JSON::writeToStream().
isDouble()
bool yup::var::isDouble () const noexcept
Referenced by yup::Artboard::setInput(), and yup::JSON::writeToStream().
isString()
bool yup::var::isString () const noexcept
Referenced by yup::JSON::writeToStream().
isObject()
bool yup::var::isObject () const noexcept
Referenced by yup::JSON::writeToStream().
isArray()
bool yup::var::isArray () const noexcept
Referenced by yup::JSON::writeToStream().
isBinaryData()
bool yup::var::isBinaryData () const noexcept
Referenced by yup::JSON::writeToStream().
isMethod()
bool yup::var::isMethod () const noexcept
Referenced by getNativeFunction(), yup::DynamicObject::hasMethod(), yup::DynamicObject::hasProperty(), and yup::JSON::writeToStream().
equals()
bool yup::var::equals (const var & other) const noexcept
Returns true if this var has the same value as the one supplied.
Note that this ignores the type, so a string var "123" and an integer var with the value 123 are considered to be equal.
Note that equality checking depends on the "wrapped" type of the object on which equals() is called. That means the following code will convert the right-hand-side argument to a string and compare the string values, because the object on the left-hand-side was initialised from a string:
var ("123").equals (var (123))
However, the following code will convert the right-hand-side argument to a double and compare the values as doubles, because the object on the left-hand-side was initialised from a double:
var (45.6).equals ("45.6000")
See also
equalsWithSameType
References var().
Referenced by equalsWithSameType(), yup::operator!=(), and yup::operator==().
equalsWithSameType()
bool yup::var::equalsWithSameType (const var & other) const noexcept
Returns true if this var has the same value and type as the one supplied.
This differs from equals() because e.g. "123" and 123 will be considered different.
See also
equals
References equals(), hasSameTypeAs(), and var().
hasSameTypeAs()
bool yup::var::hasSameTypeAs (const var & other) const noexcept
Returns true if this var has the same type as the one supplied.
References var().
Referenced by equalsWithSameType().
clone()
var yup::var::clone () const noexcept
Returns a deep copy of this object.
For simple types this just returns a copy, but if the object contains any arrays or DynamicObjects, they will be cloned (recursively).
References clone(), and var().
Referenced by clone().
size()
int yup::var::size () const
If the var is an array, this returns the number of elements.
If the var isn't actually an array, this will return 0.
References getArray().
Referenced by yup::NamedValueSet::remove().
operator[]() [1/5]
const var & yup::var::operator[] (int arrayIndex) const
If the var is an array, this can be used to return one of its elements.
To call this method, you must make sure that the var is actually an array, and that the index is a valid number. If these conditions aren't met, behaviour is undefined. For more control over the array's contents, you can call getArray() and manipulate it directly as an Array<var>.
References getArray(), yup::isPositiveAndBelow(), and var().
Referenced by operator[](), and operator[]().
operator[]() [2/5]
var & yup::var::operator[] (int arrayIndex)
If the var is an array, this can be used to return one of its elements.
To call this method, you must make sure that the var is actually an array, and that the index is a valid number. If these conditions aren't met, behaviour is undefined. For more control over the array's contents, you can call getArray() and manipulate it directly as an Array<var>.
References getArray(), yup::isPositiveAndBelow(), and var().
append()
void yup::var::append (const var & valueToAppend)
Appends an element to the var, converting it to an array if it isn't already one.
If the var isn't an array, it will be converted to one, and if its value was non-void, this value will be kept as the first element of the new array. The parameter value will then be appended to it. For more control over the array's contents, you can call getArray() and manipulate it directly as an Array<var>.
References var().
insert()
void yup::var::insert (int index, const var & value)
Inserts an element to the var, converting it to an array if it isn't already one.
If the var isn't an array, it will be converted to one, and if its value was non-void, this value will be kept as the first element of the new array. The parameter value will then be inserted into it. For more control over the array's contents, you can call getArray() and manipulate it directly as an Array<var>.
References var().
remove()
void yup::var::remove (int index)
If the var is an array, this removes one of its elements.
If the index is out-of-range or the var isn't an array, nothing will be done. For more control over the array's contents, you can call getArray() and manipulate it directly as an Array<var>.
References getArray().
Referenced by yup::DynamicObject::removeProperty().
resize()
void yup::var::resize (int numArrayElementsWanted)
Treating the var as an array, this resizes it to contain the specified number of elements.
If the var isn't an array, it will be converted to one, and if its value was non-void, this value will be kept as the first element of the new array before resizing. For more control over the array's contents, you can call getArray() and manipulate it directly as an Array<var>.
indexOf()
int yup::var::indexOf (const var & value) const
If the var is an array, this searches it for the first occurrence of the specified value, and returns its index.
If the var isn't an array, or if the value isn't found, this returns -1.
References getArray(), and var().
operator[]() [3/5]
const var & yup::var::operator[] (const Identifier & propertyName) const
If this variant is an object, this returns one of its properties.
References getDynamicObject(), getProperty(), and var().
operator[]() [4/5]
const var & yup::var::operator[] (const char * propertyName) const
If this variant is an object, this returns one of its properties.
References operator[](), and var().
operator[]() [5/5]
const var & yup::var::operator[] (StringRef propertyName) const
If this variant is an object, this returns one of its properties.
References operator[](), and var().
getProperty()
var yup::var::getProperty (const Identifier & propertyName, const var & defaultReturnValue) const
If this variant is an object, this returns one of its properties, or a default fallback value if the property is not set.
References getDynamicObject(), and var().
Referenced by operator[]().
hasProperty()
bool yup::var::hasProperty (const Identifier & propertyName) const noexcept
Returns true if this variant is an object and if it has the given property.
References getDynamicObject().
getMethod()
var yup::var::getMethod (const Identifier & methodName, const var & defaultReturnValue) const
If this variant is an object, this returns one of its methods, or a default fallback value if the property is not set.
References getDynamicObject(), and var().
hasMethod()
bool yup::var::hasMethod (const Identifier & methodName) const noexcept
Returns true if this variant is an object and if it has the given method.
References getDynamicObject().
call() [1/6]
var yup::var::call (const Identifier & method) const
Invokes a named method call with no arguments.
References invoke(), and var().
call() [2/6]
var yup::var::call (const Identifier & method, const var & arg1) const
Invokes a named method call with one argument.
References invoke(), and var().
call() [3/6]
var yup::var::call (const Identifier & method, const var & arg1, const var & arg2) const
Invokes a named method call with 2 arguments.
References invoke(), and var().
call() [4/6]
var yup::var::call (const Identifier & method, const var & arg1, const var & arg2, const var & arg3)
Invokes a named method call with 3 arguments.
References invoke(), and var().
call() [5/6]
var yup::var::call (const Identifier & method, const var & arg1, const var & arg2, const var & arg3, const var & arg4) const
Invokes a named method call with 4 arguments.
References invoke(), and var().
call() [6/6]
var yup::var::call (const Identifier & method, const var & arg1, const var & arg2, const var & arg3, const var & arg4, const var & arg5) const
Invokes a named method call with 5 arguments.
References invoke(), and var().
invoke()
var yup::var::invoke (const Identifier & method, const var * arguments, int numArguments) const
Invokes a named method call with a list of arguments.
References getDynamicObject(), and var().
Referenced by call(), call(), call(), call(), call(), and call().
getNativeFunction()
var::NativeFunction yup::var::getNativeFunction () const
If this object is a method, this returns the function pointer.
References isMethod().
writeToStream()
void yup::var::writeToStream (OutputStream & output) const
Writes a binary representation of this value to a stream.
The data can be read back later using readFromStream().
See also
JSON
readFromStream()
var yup::var::readFromStream (InputStream & input) static
Reads back a stored binary representation of a value.
The data in the stream must have been written using writeToStream(), or this will have unpredictable results.
See also
JSON
References yup::MemoryBlock::getData(), yup::InputStream::read(), yup::InputStream::readByte(), yup::InputStream::readCompressedInt(), yup::InputStream::readDouble(), readFromStream(), yup::InputStream::readInt(), yup::InputStream::readInt64(), yup::MemoryBlock::setSize(), yup::InputStream::skipNextBytes(), yup::MemoryOutputStream::toUTF8(), var(), yup::varMarker_Array, yup::varMarker_Binary, yup::varMarker_BoolFalse, yup::varMarker_BoolTrue, yup::varMarker_Double, yup::varMarker_Int, yup::varMarker_Int64, yup::varMarker_String, and yup::MemoryOutputStream::writeFromInputStream().
Referenced by readFromStream().