YUP: yup::Image Class Reference
yup::Image Class Reference
Represents an image using BitmapData.
Public Member Functions
Image ()=default
Default constructor.
Image (int w, int h, PixelFormat fmt=PixelFormat::RGBA)
Constructs an image with specified dimensions and pixel format.
Image (const Image &other)
Copy constructor.
Image (Image &&other) noexcept
Move constructor.
Image & operator= (const Image &other)
Copy assignment operator.
Image & operator= (Image &&other) noexcept
Move assignment operator.
~Image ()=default
Destructor.
bool isValid () const noexcept
int getWidth () const noexcept
Returns the width of the image in pixels.
int getHeight () const noexcept
Returns the height of the image in pixels.
PixelFormat getPixelFormat () const noexcept
Returns the pixel format of the image.
int getPixelStride () const noexcept
Returns the pixel stride of the image.
void setPixel (int x, int y, uint32_t color)
Sets the pixel at (x, y) with the specified color.
uint32_t getPixel (int x, int y) const
Gets the pixel color at (x, y).
void fill (uint32_t color)
Fills the entire image with the specified color.
void clear ()
Clears the image by setting all pixels to zero.
const BitmapData & getBitmapData () const noexcept
Returns a const reference to BitmapData.
BitmapData & getBitmapData () noexcept
Returns a mutable reference to BitmapData.
Span< const uint8 > getRawData () const noexcept
Returns a pointer to the raw pixel data.
Span< uint8 > getRawData () noexcept
Returns a mutable pointer to the raw pixel data.
bool createTextureIfNotPresent (GraphicsContext &context) const
rive::rcp< rive::gpu::Texture > getTexture () const
Static Public Member Functions
static ResultValue< Image > loadFromData (Span< const uint8 > imageData)
Detailed Description
Represents an image using BitmapData.
Provides methods to manipulate and access pixel data through BitmapData.
Constructor & Destructor Documentation
Image() [1/4]
yup::Image::Image () default
Default constructor.
Creates an empty image.
References Image(), and yup::RGBA.
Referenced by Image(), Image(), Image(), loadFromData(), operator=(), operator=(), and ~Image().
Image() [2/4]
yup::Image::Image (int w, int h, PixelFormat fmt = PixelFormat::RGBA)
Constructs an image with specified dimensions and pixel format.
Parameters
w The width of the image in pixels.
h The height of the image in pixels.
fmt The pixel format of the image.
Image() [3/4]
yup::Image::Image (const Image & other)
Copy constructor.
References Image().
Image() [4/4]
yup::Image::Image (Image && other) noexcept
Move constructor.
References Image().
~Image()
yup::Image::~Image () default
Destructor.
References clear(), createTextureIfNotPresent(), fill(), getBitmapData(), getHeight(), getPixel(), getPixelFormat(), getPixelStride(), getRawData(), getTexture(), getWidth(), Image(), loadFromData(), and setPixel().
Member Function Documentation
operator=() [1/2]
Image & yup::Image::operator= (const Image & other)
Copy assignment operator.
References Image().
operator=() [2/2]
Image & yup::Image::operator= (Image && other) noexcept
Move assignment operator.
References Image().
isValid()
bool yup::Image::isValid () const noexcept
getWidth()
int yup::Image::getWidth () const noexcept
Returns the width of the image in pixels.
Referenced by createTextureIfNotPresent(), yup::Graphics::drawImageAt(), and ~Image().
getHeight()
int yup::Image::getHeight () const noexcept
Returns the height of the image in pixels.
Referenced by createTextureIfNotPresent(), yup::Graphics::drawImageAt(), and ~Image().
getPixelFormat()
PixelFormat yup::Image::getPixelFormat () const noexcept
Returns the pixel format of the image.
Referenced by ~Image().
getPixelStride()
int yup::Image::getPixelStride () const noexcept
Returns the pixel stride of the image.
Referenced by ~Image().
setPixel()
void yup::Image::setPixel (int x, int y, uint32_t color)
Sets the pixel at (x, y) with the specified color.
Parameters
x The x-coordinate of the pixel.
y The y-coordinate of the pixel.
color The color value to set.
Referenced by ~Image().
getPixel()
uint32_t yup::Image::getPixel (int x, int y) const
Gets the pixel color at (x, y).
Parameters
x The x-coordinate of the pixel.
y The y-coordinate of the pixel.
Returns
The color value of the pixel.
Referenced by ~Image().
fill()
void yup::Image::fill (uint32_t color)
Fills the entire image with the specified color.
Parameters
color The color value to fill the image with.
Referenced by ~Image().
clear()
void yup::Image::clear ()
Clears the image by setting all pixels to zero.
Referenced by ~Image().
getBitmapData() [1/2]
const BitmapData & yup::Image::getBitmapData () const noexcept
Returns a const reference to BitmapData.
Referenced by ~Image().
getBitmapData() [2/2]
BitmapData & yup::Image::getBitmapData () noexcept
Returns a mutable reference to BitmapData.
getRawData() [1/2]
Span< const uint8 > yup::Image::getRawData () const noexcept
Returns a pointer to the raw pixel data.
Referenced by createTextureIfNotPresent(), and ~Image().
getRawData() [2/2]
Span< uint8 > yup::Image::getRawData () noexcept
Returns a mutable pointer to the raw pixel data.
createTextureIfNotPresent()
bool yup::Image::createTextureIfNotPresent (GraphicsContext & context) const
References getHeight(), getRawData(), getWidth(), and yup::GraphicsContext::renderContext().
Referenced by yup::Graphics::drawImageAt(), and ~Image().
getTexture()
rive::rcp< rive::gpu::Texture > yup::Image::getTexture () const
Referenced by yup::Graphics::drawImageAt(), and ~Image().
loadFromData()
ResultValue< Image > yup::Image::loadFromData (Span< const uint8 > imageData) static
References yup::Span< Value, Extent >::data(), yup::ResultValue< T >::fail(), Image(), yup::ResultValue< T >::ok(), yup::RGB, and yup::RGBA.
Referenced by ~Image().