YUP: yup::Point< ValueType > Class Template Reference
yup::Point< ValueType > Class Template Reference
Represents a 2D point with coordinates of a generic type.
Public Types
using Type = ValueType
Value type of the point.
Public Member Functions
constexpr Point () noexcept=default
Constructs a default point at the origin (0, 0).
constexpr Point (ValueType newX, ValueType newY) noexcept
Constructs a point with specified x and y coordinates.
template<class T, std::enable_if_t<! std::is_same_v< T, ValueType >, int > = 0>
constexpr Point (T newX, T newY) noexcept
Constructs a point from another type, converting the coordinates to the ValueType.
template<class T, std::enable_if_t<! std::is_same_v< T, ValueType >, int > = 0>
constexpr Point (const Point< T > newPoint) noexcept
Constructs a point from another Point type, converting the coordinates to the ValueType.
constexpr Point (const Point &other) noexcept=default
Copy and move constructors and assignment operators.
constexpr Point (Point &&other) noexcept=default
constexpr Point & operator= (const Point &other) noexcept=default
constexpr Point & operator= (Point &&other) noexcept=default
constexpr ValueType getX () const noexcept
Gets the x coordinate of this point.
constexpr Point & setX (ValueType newX) noexcept
constexpr Point withX (ValueType newX) const noexcept
Returns a new point with the x coordinate changed to the specified value, keeping the y coordinate the same.
constexpr ValueType getY () const noexcept
Gets the y coordinate of this point.
constexpr Point & setY (ValueType newY) noexcept
constexpr Point withY (ValueType newY) const noexcept
Returns a new point with the y coordinate changed to the specified value, keeping the x coordinate the same.
constexpr Point withXY (ValueType newX, ValueType newY) const noexcept
Returns a new point with both x and y coordinates changed to the specified values.
constexpr bool isOrigin () const noexcept
Checks if this point is located at the origin (0, 0).
constexpr bool isOnXAxis () const noexcept
Checks if this point is located on the X-axis (y == 0).
constexpr bool isOnYAxis () const noexcept
Checks if this point is located on the Y-axis (x == 0).
template<class T = ValueType>
constexpr auto isFinite () const noexcept -> std::enable_if_t< std::is_floating_point_v< T >, bool >
Checks if the coordinates of this point are finite numbers.
constexpr float distanceTo (const Point &other) const noexcept
Calculates the Euclidean distance between this point and another point.
constexpr ValueType distanceToSquared (const Point &other) const noexcept
Calculates the squared Euclidean distance between this point and another point, avoiding the square root calculation.
constexpr ValueType horizontalDistanceTo (const Point &other) const noexcept
Calculates the horizontal distance between this point and another point.
constexpr ValueType verticalDistanceTo (const Point &other) const noexcept
Calculates the vertical distance between this point and another point.
constexpr ValueType manhattanDistanceTo (const Point &other) const noexcept
Calculates the Manhattan distance between this point and another point.
constexpr float magnitude () const noexcept
Returns the magnitude (length) of this point interpreted as a vector from the origin.
constexpr Point getPointOnCircumference (float radius, float angleRadians) const noexcept
Returns a new point located on the circumference of a circle centered at this point, given a radius and an angle.
constexpr Point getPointOnCircumference (float radiusX, float radiusY, float angleRadians) const noexcept
Returns a new point located on the circumference of an ellipse centered at this point, given radii and an angle.
constexpr Point & translate (ValueType deltaX, ValueType deltaY) noexcept
Translates this point by the specified changes in x and y coordinates.
constexpr Point & translate (const Point &delta) noexcept
Translates this point by another point's coordinates.
constexpr Point translated (ValueType deltaX, ValueType deltaY) const noexcept
Returns a new point translated by specified delta x and delta y values.
constexpr Point translated (const Point &delta) const noexcept
Returns a new point translated by another point's coordinates.
template<class T>
constexpr auto scale (T factor) noexcept -> std::enable_if_t< std::is_floating_point_v< T >, Point & >
Scales this point's coordinates by a uniform factor.
template<class T>
constexpr auto scale (T factorX, T factorY) noexcept -> std::enable_if_t< std::is_floating_point_v< T >, Point & >
Scales this point's coordinates by specified factors along the x and y axes.
template<class T>
constexpr auto scaled (T factor) const noexcept -> std::enable_if_t< std::is_floating_point_v< T >, Point >
Returns a new point scaled by a uniform factor.
template<class T>
constexpr auto scaled (T factorX, T factorY) const noexcept -> std::enable_if_t< std::is_floating_point_v< T >, Point >
Returns a new point scaled by specified factors along the x and y axes.
constexpr Point & rotateClockwise (float angleInRadians) noexcept
Rotates this point clockwise around the origin by a specified angle.
constexpr Point rotatedClockwise (float angleInRadians) const noexcept
Returns a new point rotated clockwise around the origin by a specified angle.
constexpr Point & rotateCounterClockwise (float angleInRadians) noexcept
Rotates this point counterclockwise around the origin by a specified angle.
constexpr Point rotatedCounterClockwise (float angleInRadians) const noexcept
Returns a new point rotated counterclockwise around the origin by a specified angle.
constexpr Point midpoint (const Point &other) const noexcept
Calculates the midpoint between this point and another point.
constexpr Point pointBetween (const Point &other, float delta) const noexcept
Calculates a point linearly interpolated between this point and another point by a specified factor.
constexpr ValueType dotProduct (const Point &other) const noexcept
Calculates the dot product of this point with another point.
constexpr ValueType crossProduct (const Point &other) const noexcept
Calculates the cross product of this point with another point.
constexpr float angleTo (const Point &other) const noexcept
Calculates the angle to another point in radians.
constexpr Point & normalize () noexcept
Normalizes the coordinates of this point to a unit vector.
constexpr Point normalized () const noexcept
Return a normalized point to a unit vector.
constexpr bool isNormalized () const noexcept
Checks if the coordinates of this point represent a unit vector.
constexpr bool isCollinear (const Point &other) const noexcept
Checks if this point is collinear with another point.
constexpr bool isWithinCircle (const Point &center, float radius) const noexcept
Checks if this point is within a circle defined by a center point and radius.
constexpr bool isWithinRectangle (const Point &topLeft, const Point &bottomRight) const noexcept
Checks if this point is within a rectangular area defined by two corner points.
constexpr Point & reflectOverXAxis () noexcept
Reflects this point over the X-axis.
constexpr Point reflectedOverXAxis () const noexcept
Returns a new point reflected over the X-axis.
constexpr Point & reflectOverYAxis () noexcept
Reflects this point over the Y-axis.
constexpr Point reflectedOverYAxis () const noexcept
Returns a new point reflected over the Y-axis.
constexpr Point & reflectOverOrigin () noexcept
Reflects this point over the origin.
constexpr Point reflectedOverOrigin () const noexcept
Returns a new point reflected over the origin.
constexpr Point min (const Point &other) const noexcept
Computes the minimum of this point and another point based on each coordinate.
constexpr Point max (const Point &other) const noexcept
Computes the maximum of this point and another point based on each coordinate.
constexpr Point abs () const noexcept
Returns a new point with the absolute values of the coordinates of this point.
template<class T = ValueType>
constexpr auto floor () const noexcept -> std::enable_if_t< std::is_floating_point_v< T >, Point >
Floors the coordinates of this point.
template<class T = ValueType>
constexpr auto ceil () const noexcept -> std::enable_if_t< std::is_floating_point_v< T >, Point >
Ceils the coordinates of this point.
constexpr Point lerp (const Point &other, float delta) const noexcept
Linearly interpolates between this point and another point by a specified factor.
constexpr Point & transform (const AffineTransform &t) noexcept
constexpr Point transformed (const AffineTransform &t) const noexcept
template<class T>
constexpr Point< T > to () const noexcept
Converts the coordinates of this point to another numeric type.
template<class T = ValueType>
constexpr auto roundToInt () const noexcept -> std::enable_if_t< std::is_floating_point_v< T >, Point< int > >
constexpr Point operator+ (const Point &other) const noexcept
Adds the coordinates of another point to this point and returns the result.
constexpr Point & operator+= (const Point &other) noexcept
Adds the coordinates of another point to this point.
constexpr Point operator+ (ValueType amount) const noexcept
Adds a scalar value to both coordinates of this point and returns the result.
constexpr Point & operator+= (ValueType amount) noexcept
Adds a scalar value to both coordinates of this point.
constexpr Point operator- (const Point &other) const noexcept
Subtracts the coordinates of another point from this point and returns the result.
constexpr Point & operator-= (const Point &other) noexcept
Subtracts the coordinates of another point from this point.
constexpr Point operator- (ValueType amount) const noexcept
Subtracts a scalar value from both coordinates of this point and returns the result.
constexpr Point & operator-= (ValueType amount) noexcept
Subtracts a scalar value from both coordinates of this point.
constexpr Point operator* (const Point &other) const noexcept
Multiplies the coordinates of this point by the coordinates of another point and returns the result.
constexpr Point & operator*= (const Point &other) noexcept
Multiplies the coordinates of this point by the coordinates of another point.
constexpr Point operator* (ValueType scale) const noexcept
Multiplies both coordinates of this point by a scalar value and returns the result.
constexpr Point & operator*= (ValueType scale) noexcept
Multiplies both coordinates of this point by a scalar value.
constexpr Point operator/ (const Point &other) const noexcept
Divides the coordinates of this point by the coordinates of another point and returns the result.
constexpr Point & operator/= (const Point &other) noexcept
Divides the coordinates of this point by the coordinates of another point.
constexpr Point operator/ (ValueType scale) const noexcept
Divides both coordinates of this point by a scalar value and returns the result.
constexpr Point & operator/= (ValueType scale) noexcept
Divides both coordinates of this point by a scalar value.
constexpr Point operator- () const noexcept
Returns a new point with negated coordinates.
constexpr bool approximatelyEqualTo (const Point &other) const noexcept
Returns true if the two points are approximately equal.
constexpr bool operator== (const Point &other) const noexcept
Checks for equality between this point and another point based on their coordinates.
constexpr bool operator!= (const Point &other) const noexcept
Checks for inequality between this point and another point based on their coordinates.
Detailed Description
template<class ValueType>
class yup::Point< ValueType >
Represents a 2D point with coordinates of a generic type.
The Point class template provides a flexible representation of a two-dimensional point using any numeric type. It offers various methods for manipulating the point's position through arithmetic operations, scaling, rotation, and other geometric transformations. The class is designed to be efficient and used in contexts where points as mathematical concepts are needed, such as graphics, physics simulations, and vector calculations.
Template Parameters
ValueType The type of the coordinates, can be any numeric type (int, float, double, etc.).
Member Typedef Documentation
Type
template<class ValueType> using yup::Point< ValueType >::Type = ValueType
Value type of the point.
Constructor & Destructor Documentation
Point() [1/6]
template<class ValueType> yup::Point< ValueType >::Point () constexpr default noexcept
Constructs a default point at the origin (0, 0).
Referenced by abs(), angleTo(), approximatelyEqualTo(), ceil(), crossProduct(), distanceTo(), distanceToSquared(), dotProduct(), floor(), getPointOnCircumference(), getPointOnCircumference(), horizontalDistanceTo(), isCollinear(), isWithinCircle(), isWithinRectangle(), lerp(), manhattanDistanceTo(), max(), midpoint(), min(), normalize(), normalized(), operator!=(), operator*(), operator*(), operator*=(), operator*=(), operator+(), operator+(), operator+=(), operator+=(), operator-(), operator-(), operator-(), operator-=(), operator-=(), operator/(), operator/(), operator/=(), operator/=(), operator=(), operator=(), operator==(), Point(), Point(), Point(), Point(), pointBetween(), reflectedOverOrigin(), reflectedOverXAxis(), reflectedOverYAxis(), reflectOverOrigin(), reflectOverXAxis(), reflectOverYAxis(), rotateClockwise(), rotateCounterClockwise(), rotatedClockwise(), rotatedCounterClockwise(), roundToInt(), scale(), scale(), scaled(), scaled(), setX(), setY(), to(), transform(), transformed(), translate(), translate(), translated(), translated(), verticalDistanceTo(), withX(), withXY(), and withY().
Point() [2/6]
template<class ValueType> yup::Point< ValueType >::Point (ValueType newX, ValueType newY) constexpr noexcept
Constructs a point with specified x and y coordinates.
Parameters
newX The x coordinate of the point.
newY The y coordinate of the point.
References Point().
Point() [3/6]
template<class ValueType> template<class T, std::enable_if_t<! std::is_same_v< T, ValueType >, int > = 0> yup::Point< ValueType >::Point (T newX, T newY) constexpr noexcept
Constructs a point from another type, converting the coordinates to the ValueType.
This constructor allows for points with different coordinate types to be converted into points with this instance's coordinate type, as long as the conversion is valid and does not narrow the type in a way that could lead to loss of data.
Template Parameters
T The type of the original coordinates (must be different from ValueType).
Parameters
newX The x coordinate of the original point.
newY The y coordinate of the original point.
Point() [4/6]
template<class ValueType> template<class T, std::enable_if_t<! std::is_same_v< T, ValueType >, int > = 0> yup::Point< ValueType >::Point (const Point< T > newPoint) constexpr noexcept
Constructs a point from another Point type, converting the coordinates to the ValueType.
Template Parameters
T The type of the original coordinates (must be different from ValueType).
Parameters
newPoint The original point to convert.
References Point().
Point() [5/6]
template<class ValueType> yup::Point< ValueType >::Point (const Point< ValueType > & other) constexpr default noexcept
Copy and move constructors and assignment operators.
References Point().
Point() [6/6]
template<class ValueType> yup::Point< ValueType >::Point (Point< ValueType > && other) constexpr default noexcept
References Point().
Member Function Documentation
operator=() [1/2]
template<class ValueType> Point & yup::Point< ValueType >::operator= (const Point< ValueType > & other) constexpr default noexcept
References Point().
operator=() [2/2]
template<class ValueType> Point & yup::Point< ValueType >::operator= (Point< ValueType > && other) constexpr default noexcept
References Point().
getX()
template<class ValueType> ValueType yup::Point< ValueType >::getX () const nodiscard constexpr noexcept
Gets the x coordinate of this point.
Returns
The x coordinate of the point.
Referenced by yup::Path::addBubble(), yup::Path::addCenteredArc(), yup::Path::addCenteredArc(), yup::Path::addCenteredEllipse(), yup::Path::addCenteredEllipse(), yup::Path::addPolygon(), yup::Path::addStar(), yup::RectangleList< ValueType >::contains(), yup::Path::createStrokePolygon(), yup::Path::cubicTo(), yup::StyledText::getGlyphIndexAtPosition(), yup::Path::lineTo(), yup::Path::moveTo(), yup::Path::quadTo(), and yup::Graphics::strokeLine().
setX()
template<class ValueType> Point & yup::Point< ValueType >::setX (ValueType newX) constexpr noexcept
References Point().
Referenced by yup::StyledText::getOffset().
withX()
template<class ValueType> Point yup::Point< ValueType >::withX (ValueType newX) const nodiscard constexpr noexcept
Returns a new point with the x coordinate changed to the specified value, keeping the y coordinate the same.
Parameters
newX The new x coordinate.
Returns
A new point with the updated x coordinate.
References Point().
getY()
template<class ValueType> ValueType yup::Point< ValueType >::getY () const nodiscard constexpr noexcept
Gets the y coordinate of this point.
Returns
The y coordinate of the point.
Referenced by yup::Path::addBubble(), yup::Path::addCenteredArc(), yup::Path::addCenteredArc(), yup::Path::addCenteredEllipse(), yup::Path::addCenteredEllipse(), yup::Path::addPolygon(), yup::Path::addStar(), yup::RectangleList< ValueType >::contains(), yup::Path::createStrokePolygon(), yup::Path::cubicTo(), yup::StyledText::getGlyphIndexAtPosition(), yup::Path::lineTo(), yup::Path::moveTo(), yup::Path::quadTo(), and yup::Graphics::strokeLine().
setY()
template<class ValueType> Point & yup::Point< ValueType >::setY (ValueType newY) constexpr noexcept
References Point().
Referenced by yup::StyledText::getOffset().
withY()
template<class ValueType> Point yup::Point< ValueType >::withY (ValueType newY) const nodiscard constexpr noexcept
Returns a new point with the y coordinate changed to the specified value, keeping the x coordinate the same.
Parameters
newY The new y coordinate.
Returns
A new point with the updated y coordinate.
References Point().
withXY()
template<class ValueType> Point yup::Point< ValueType >::withXY (ValueType newX, ValueType newY) const nodiscard constexpr noexcept
Returns a new point with both x and y coordinates changed to the specified values.
Parameters
newX The new x coordinate.
newY The new y coordinate.
Returns
A new point with the updated coordinates.
References Point().
isOrigin()
template<class ValueType> bool yup::Point< ValueType >::isOrigin () const nodiscard constexpr noexcept
Checks if this point is located at the origin (0, 0).
Returns
True if the point is at the origin, false otherwise.
References isOnXAxis(), and isOnYAxis().
isOnXAxis()
template<class ValueType> bool yup::Point< ValueType >::isOnXAxis () const nodiscard constexpr noexcept
Checks if this point is located on the X-axis (y == 0).
Returns
True if the point is on the X-axis, false otherwise.
Referenced by isOrigin().
isOnYAxis()
template<class ValueType> bool yup::Point< ValueType >::isOnYAxis () const nodiscard constexpr noexcept
Checks if this point is located on the Y-axis (x == 0).
Returns
True if the point is on the Y-axis, false otherwise.
Referenced by isOrigin().
isFinite()
template<class ValueType> template<class T = ValueType> auto yup::Point< ValueType >::isFinite () const -> std::enable_if_t<std::is_floating_point_v<T>, bool> nodiscard constexpr noexcept
Checks if the coordinates of this point are finite numbers.
This method is only available for floating-point coordinate types and checks if both coordinates are finite values as defined by the standard library function std::isfinite.
Template Parameters
T The type of the coordinates, constrained to floating-point types.
Returns
True if both coordinates are finite, false otherwise.
distanceTo()
template<class ValueType> float yup::Point< ValueType >::distanceTo (const Point< ValueType > & other) const nodiscard constexpr noexcept
Calculates the Euclidean distance between this point and another point.
Parameters
other The point to calculate the distance to.
Returns
The Euclidean distance as a floating-point value.
References distanceToSquared(), and Point().
Referenced by yup::Path::getPointAlongPath(), and isWithinCircle().
distanceToSquared()
template<class ValueType> ValueType yup::Point< ValueType >::distanceToSquared (const Point< ValueType > & other) const nodiscard constexpr noexcept
Calculates the squared Euclidean distance between this point and another point, avoiding the square root calculation.
This method is useful for distance comparisons where the actual distance value is not needed, as it avoids the computationally expensive square root operation.
Parameters
other The point to calculate the squared distance to.
Returns
The squared Euclidean distance as a value of type ValueType.
References Point(), and yup::square().
Referenced by distanceTo().
horizontalDistanceTo()
template<class ValueType> ValueType yup::Point< ValueType >::horizontalDistanceTo (const Point< ValueType > & other) const nodiscard constexpr noexcept
Calculates the horizontal distance between this point and another point.
This method returns the difference in the x coordinates of this point and another point, representing the horizontal component of the distance between them.
Parameters
other The point to calculate the horizontal distance to.
Returns
The horizontal distance as a value of type ValueType.
References Point().
verticalDistanceTo()
template<class ValueType> ValueType yup::Point< ValueType >::verticalDistanceTo (const Point< ValueType > & other) const nodiscard constexpr noexcept
Calculates the vertical distance between this point and another point.
This method returns the difference in the y coordinates of this point and another point, representing the vertical component of the distance between them.
Parameters
other The point to calculate the vertical distance to.
Returns
The vertical distance as a value of type ValueType.
References Point().
manhattanDistanceTo()
template<class ValueType> ValueType yup::Point< ValueType >::manhattanDistanceTo (const Point< ValueType > & other) const nodiscard constexpr noexcept
Calculates the Manhattan distance between this point and another point.
The Manhattan distance is the sum of the absolute differences of their Cartesian coordinates. It is often used in integrated circuits where wires only run parallel to the X or Y axis.
Parameters
other The point to calculate the Manhattan distance to.
Returns
The Manhattan distance as a value of type ValueType.
References Point().
magnitude()
template<class ValueType> float yup::Point< ValueType >::magnitude () const nodiscard constexpr noexcept
Returns the magnitude (length) of this point interpreted as a vector from the origin.
This method calculates the Euclidean norm of the vector represented by the point's coordinates. It is equivalent to the distance from the origin to this point.
Returns
The magnitude of the vector as a floating-point value.
References yup::square().
Referenced by angleTo(), yup::Path::createStrokePolygon(), isNormalized(), and normalize().
getPointOnCircumference() [1/2]
template<class ValueType> Point yup::Point< ValueType >::getPointOnCircumference (float radius, float angleRadians) const nodiscard constexpr noexcept
Returns a new point located on the circumference of a circle centered at this point, given a radius and an angle.
This method calculates the coordinates of a point located on the circumference of a circle with a specified radius and angle from the x-axis, using the polar coordinates transformation.
Parameters
radius The radius of the circle.
angleRadians The angle in radians from the x-axis where the new point will be located.
Returns
A new point on the specified circle.
References Point().
getPointOnCircumference() [2/2]
template<class ValueType> Point yup::Point< ValueType >::getPointOnCircumference (float radiusX, float radiusY, float angleRadians) const nodiscard constexpr noexcept
Returns a new point located on the circumference of an ellipse centered at this point, given radii and an angle.
This method is an extension of getPointOnCircumference that supports elliptical paths by specifying different radii for the x and y axes.
Parameters
radiusX The radius along the x-axis of the ellipse.
radiusY The radius along the y-axis of the ellipse.
angleRadians The angle in radians from the x-axis where the new point will be located.
Returns
A new point on the specified ellipse.
References Point().
translate() [1/2]
template<class ValueType> Point & yup::Point< ValueType >::translate (ValueType deltaX, ValueType deltaY) constexpr noexcept
Translates this point by the specified changes in x and y coordinates.
This method modifies this point's coordinates by adding the specified deltas to them.
Parameters
deltaX The change to apply to the x coordinate.
deltaY The change to apply to the y coordinate.
Returns
A reference to this point after the translation.
References Point().
translate() [2/2]
template<class ValueType> Point & yup::Point< ValueType >::translate (const Point< ValueType > & delta) constexpr noexcept
Translates this point by another point's coordinates.
This method modifies the coordinates of this point by adding the coordinates of another point to its own coordinates. It effectively moves this point by the offset specified by the other point.
Parameters
delta Another Point object whose x and y values are used as the delta values for the translation.
Returns
A reference to this Point object after the translation.
References Point().
translated() [1/2]
template<class ValueType> Point yup::Point< ValueType >::translated (ValueType deltaX, ValueType deltaY) const nodiscard constexpr noexcept
Returns a new point translated by specified delta x and delta y values.
This method creates a new Point object with coordinates that are the result of adding specified delta values to the coordinates of this point. It does not modify this point but returns a new point with the updated coordinates.
Parameters
deltaX The change to be applied to the x-coordinate of the new point.
deltaY The change to be applied to the y-coordinate of the new point.
Returns
A new Point object with the translated coordinates.
References Point().
Referenced by yup::Component::setBottomLeft(), yup::Component::setBottomRight(), yup::Component::setCenter(), and yup::Component::setTopRight().
translated() [2/2]
template<class ValueType> Point yup::Point< ValueType >::translated (const Point< ValueType > & delta) const nodiscard constexpr noexcept
Returns a new point translated by another point's coordinates.
This method creates a new Point object with coordinates that are the result of adding the coordinates of another point to the coordinates of this point. It does not modify this point but returns a new point with the updated coordinates.
Parameters
delta Another Point object whose x and y values are used as the delta values for the translation of the new point.
Returns
A new Point object with the translated coordinates.
References Point().
scale() [1/2]
template<class ValueType> template<class T> auto yup::Point< ValueType >::scale (T factor) -> std::enable_if_t<std::is_floating_point_v<T>, Point&> constexpr noexcept
Scales this point's coordinates by a uniform factor.
This method multiplies both x and y coordinates of this point by a single scale factor. It modifies this point's coordinates and is useful for resizing or scaling operations relative to the origin.
Template Parameters
T The numeric type of the scaling factor, constrained to floating-point types.
Parameters
factor The factor by which the point's coordinates are scaled.
Returns
A reference to this Point object after scaling.
References Point(), and scale().
Referenced by operator*(), operator*=(), operator/(), operator/=(), scale(), scaled(), and scaled().
scale() [2/2]
template<class ValueType> template<class T> auto yup::Point< ValueType >::scale (T factorX, T factorY) -> std::enable_if_t<std::is_floating_point_v<T>, Point&> constexpr noexcept
Scales this point's coordinates by specified factors along the x and y axes.
This method multiplies the x and y coordinates of this point by separate scale factors for the x and y axes respectively. It modifies this point's coordinates and is useful for asymmetric resizing or scaling operations relative to the origin.
Template Parameters
T The numeric type of the scaling factors, constrained to floating-point types.
Parameters
factorX The factor by which the x-coordinate of the point is scaled.
factorY The factor by which the y-coordinate of the point is scaled.
Returns
A reference to this Point object after scaling.
References Point().
scaled() [1/2]
template<class ValueType> template<class T> auto yup::Point< ValueType >::scaled (T factor) const -> std::enable_if_t<std::is_floating_point_v<T>, Point> nodiscard constexpr noexcept
Returns a new point scaled by a uniform factor.
This method creates a new Point object with coordinates that are the result of multiplying this point's coordinates by a single scale factor. It does not modify this point but returns a new point with the scaled coordinates.
Template Parameters
T The numeric type of the scaling factor, constrained to floating-point types.
Parameters
factor The factor by which the coordinates of the new point are scaled.
Returns
A new Point object with the scaled coordinates.
References Point(), and scale().
scaled() [2/2]
template<class ValueType> template<class T> auto yup::Point< ValueType >::scaled (T factorX, T factorY) const -> std::enable_if_t<std::is_floating_point_v<T>, Point> nodiscard constexpr noexcept
Returns a new point scaled by specified factors along the x and y axes.
This method creates a new Point object with coordinates that are the result of multiplying this point's coordinates by separate scale factors for the x and y axes respectively. It does not modify this point but returns a new point with the scaled coordinates.
Template Parameters
T The numeric type of the scaling factors, constrained to floating-point types.
Parameters
factorX The factor by which the x-coordinate of the new point is scaled.
factorY The factor by which the y-coordinate of the new point is scaled.
Returns
A new Point object with the scaled coordinates.
References Point(), and scale().
rotateClockwise()
template<class ValueType> Point & yup::Point< ValueType >::rotateClockwise (float angleInRadians) constexpr noexcept
Rotates this point clockwise around the origin by a specified angle.
This method modifies the coordinates of this point by rotating them clockwise around the origin (0,0). The rotation is defined by an angle in radians, using the standard mathematical rotation matrix. It is useful for operations that involve rotation or angular adjustments in the coordinate system.
Parameters
angleInRadians The angle in radians by which to rotate the point clockwise.
Returns
A reference to this Point object after rotation.
References Point().
rotatedClockwise()
template<class ValueType> Point yup::Point< ValueType >::rotatedClockwise (float angleInRadians) const nodiscard constexpr noexcept
Returns a new point rotated clockwise around the origin by a specified angle.
This method creates a new Point object with coordinates that are the result of rotating this point's coordinates clockwise around the origin by a specified angle. It does not modify this point but returns a new point with the rotated coordinates.
Parameters
angleInRadians The angle in radians by which the new point is rotated clockwise.
Returns
A new Point object with the rotated coordinates.
References Point().
rotateCounterClockwise()
template<class ValueType> Point & yup::Point< ValueType >::rotateCounterClockwise (float angleInRadians) constexpr noexcept
Rotates this point counterclockwise around the origin by a specified angle.
This method modifies the coordinates of this point by rotating them counterclockwise around the origin (0,0). The rotation is defined by an angle in radians, using the standard mathematical rotation matrix reversed. It is useful for operations that involve rotation or angular adjustments in the coordinate system in the opposite direction of the clockwise rotation.
Parameters
angleInRadians The angle in radians by which to rotate the point counterclockwise.
Returns
A reference to this Point object after rotation.
References Point().
rotatedCounterClockwise()
template<class ValueType> Point yup::Point< ValueType >::rotatedCounterClockwise (float angleInRadians) const nodiscard constexpr noexcept
Returns a new point rotated counterclockwise around the origin by a specified angle.
This method creates a new Point object with coordinates that are the result of rotating this point's coordinates counterclockwise around the origin by a specified angle. It does not modify this point but returns a new point with the rotated coordinates.
Parameters
angleInRadians The angle in radians by which the new point is rotated counterclockwise.
Returns
A new Point object with the rotated coordinates.
References Point().
midpoint()
template<class ValueType> Point yup::Point< ValueType >::midpoint (const Point< ValueType > & other) const nodiscard constexpr noexcept
Calculates the midpoint between this point and another point.
This method computes the coordinates of the midpoint between this point and another specified point. The midpoint is calculated by averaging the coordinates of the two points. It is useful in geometry for finding the center point between two points or dividing line segments into equal parts.
Parameters
other Another Point object with which to calculate the midpoint.
Returns
A new Point object representing the midpoint between this point and the other point.
References Point().
pointBetween()
template<class ValueType> Point yup::Point< ValueType >::pointBetween (const Point< ValueType > & other, float delta) const nodiscard constexpr noexcept
Calculates a point linearly interpolated between this point and another point by a specified factor.
This method computes the coordinates of a point that lies a certain way between this point and another point, based on a specified interpolation factor. The interpolation factor should be between 0 and 1, where 0 represents this point and 1 represents the other point. It is useful for smooth transitions or animations between points.
Parameters
other Another Point object to interpolate towards.
delta The interpolation factor, typically between 0.0 and 1.0, representing the position between the two points.
Returns
A new Point object representing the interpolated position between this point and the other point.
References yup::jlimit(), and Point().
Referenced by yup::Path::getPointAlongPath().
dotProduct()
template<class ValueType> ValueType yup::Point< ValueType >::dotProduct (const Point< ValueType > & other) const nodiscard constexpr noexcept
Calculates the dot product of this point with another point.
This method computes the dot product of this point's vector with another point's vector. The dot product is a scalar representation of the vector alignment and length, and is often used in physics and graphics computations.
Parameters
other Another Point object with which to calculate the dot product.
Returns
The dot product of this point with the other point as a ValueType.
References Point().
Referenced by angleTo().
crossProduct()
template<class ValueType> ValueType yup::Point< ValueType >::crossProduct (const Point< ValueType > & other) const nodiscard constexpr noexcept
Calculates the cross product of this point with another point.
This method computes the cross product of this point's vector with another point's vector. The cross product is a vector perpendicular to the plane of the vectors, and its magnitude represents the area of the parallelogram that the vectors span. It is commonly used in physics, engineering, and computer graphics to determine orientation and area.
Parameters
other Another Point object with which to calculate the cross product.
Returns
The cross product of this point with the other point as a ValueType.
References Point().
Referenced by isCollinear().
angleTo()
template<class ValueType> float yup::Point< ValueType >::angleTo (const Point< ValueType > & other) const nodiscard constexpr noexcept
Calculates the angle to another point in radians.
This method computes the angle in radians between this point's vector and another point's vector. The angle is calculated based on the cosine of the angle derived from the dot product and magnitudes of the vectors. It is useful for determining the relative orientation of points or vectors in 2D space.
Parameters
other Another Point object to which the angle is calculated.
Returns
The angle in radians between this point and the other point.
References dotProduct(), magnitude(), and Point().
normalize()
template<class ValueType> Point & yup::Point< ValueType >::normalize () constexpr noexcept
Normalizes the coordinates of this point to a unit vector.
This method modifies the coordinates of this point so that its magnitude (distance from the origin) becomes 1, turning it into a unit vector. It is useful in physics and graphics where unit vectors are needed to represent directions irrespective of length.
Returns
A reference to this Point object after normalization.
References magnitude(), and Point().
Referenced by yup::Path::createStrokePolygon(), and normalized().
normalized()
template<class ValueType> Point yup::Point< ValueType >::normalized () const nodiscard constexpr noexcept
Return a normalized point to a unit vector.
This method returns a new point so that its magnitude (distance from the origin) becomes 1, turning it into a unit vector. It is useful in physics and graphics where unit vectors are needed to represent directions irrespective of length.
Returns
A new Point object representing the normalized version of this point.
References normalize(), and Point().
isNormalized()
template<class ValueType> bool yup::Point< ValueType >::isNormalized () const nodiscard constexpr noexcept
Checks if the coordinates of this point represent a unit vector.
This method determines whether the magnitude of this point is exactly 1, indicating that the point is a unit vector. Unit vectors are often used to represent directions in vector space, where only the direction and not the magnitude is of interest.
Returns
True if this point is a unit vector, false otherwise.
References magnitude().
isCollinear()
template<class ValueType> bool yup::Point< ValueType >::isCollinear (const Point< ValueType > & other) const nodiscard constexpr noexcept
Checks if this point is collinear with another point.
This method determines whether this point and another point lie on a single straight line (i.e., are collinear). Collinearity is checked using the cross product, which is zero if the points are collinear.
Parameters
other Another Point object to check for collinearity.
Returns
True if this point is collinear with the other point, false otherwise.
References crossProduct(), Point(), and yup::yup_abs().
isWithinCircle()
template<class ValueType> bool yup::Point< ValueType >::isWithinCircle (const Point< ValueType > & center, float radius) const nodiscard constexpr noexcept
Checks if this point is within a circle defined by a center point and radius.
This method determines whether this point lies within or on the boundary of a circle defined by a center point and a specified radius. The check is performed using the Euclidean distance from this point to the center point, comparing it with the radius.
Parameters
center The center point of the circle.
radius The radius of the circle.
Returns
True if this point is within the specified circle, false otherwise.
References distanceTo(), and Point().
isWithinRectangle()
template<class ValueType> bool yup::Point< ValueType >::isWithinRectangle (const Point< ValueType > & topLeft, const Point< ValueType > & bottomRight) const nodiscard constexpr noexcept
Checks if this point is within a rectangular area defined by two corner points.
This method determines whether this point lies within or on the boundary of a rectangle defined by its top-left and bottom-right corner points. The check involves comparing this point's coordinates with the coordinates of the corners to ensure it lies within the defined bounds.
Parameters
topLeft The top-left corner point of the rectangle.
bottomRight The bottom-right corner point of the rectangle.
Returns
True if this point is within the specified rectangle, false otherwise.
References Point().
reflectOverXAxis()
template<class ValueType> Point & yup::Point< ValueType >::reflectOverXAxis () constexpr noexcept
Reflects this point over the X-axis.
This method modifies the y-coordinate of this point by negating it, effectively reflecting the point over the X-axis. It is useful for mirroring points in graphical or geometrical transformations.
Returns
A reference to this Point object after reflection over the X-axis.
References Point().
reflectedOverXAxis()
template<class ValueType> Point yup::Point< ValueType >::reflectedOverXAxis () const nodiscard constexpr noexcept
Returns a new point reflected over the X-axis.
This method creates a new Point object with the y-coordinate negated, effectively representing this point reflected over the X-axis. It does not modify this point but returns a new point with the reflected coordinates.
Returns
A new Point object representing this point reflected over the X-axis.
References Point().
reflectOverYAxis()
template<class ValueType> Point & yup::Point< ValueType >::reflectOverYAxis () constexpr noexcept
Reflects this point over the Y-axis.
This method modifies the x-coordinate of this point by negating it, effectively reflecting the point over the Y-axis. It is useful for mirroring points in graphical or geometrical transformations.
Returns
A reference to this Point object after reflection over the Y-axis.
References Point().
reflectedOverYAxis()
template<class ValueType> Point yup::Point< ValueType >::reflectedOverYAxis () const nodiscard constexpr noexcept
Returns a new point reflected over the Y-axis.
This method creates a new Point object with the x-coordinate negated, effectively representing this point reflected over the Y-axis. It does not modify this point but returns a new point with the reflected coordinates.
Returns
A new Point object representing this point reflected over the Y-axis.
References Point().
reflectOverOrigin()
template<class ValueType> Point & yup::Point< ValueType >::reflectOverOrigin () constexpr noexcept
Reflects this point over the origin.
This method modifies both the x and y coordinates of this point by negating them, effectively reflecting the point over the origin. It is useful for mirroring points across both axes in graphical or geometrical transformations.
Returns
A reference to this Point object after reflection over the origin.
References Point().
reflectedOverOrigin()
template<class ValueType> Point yup::Point< ValueType >::reflectedOverOrigin () const nodiscard constexpr noexcept
Returns a new point reflected over the origin.
This method creates a new Point object with both coordinates negated, effectively representing this point reflected over the origin. It does not modify this point but returns a new point with the reflected coordinates.
Returns
A new Point object representing this point reflected over the origin.
References Point().
Referenced by operator-().
min()
template<class ValueType> Point yup::Point< ValueType >::min (const Point< ValueType > & other) const nodiscard constexpr noexcept
Computes the minimum of this point and another point based on each coordinate.
This method compares the coordinates of this point with those of another point and returns a new Point object whose coordinates are the lesser values for each coordinate. It is useful for bounding calculations or reducing values to constraints.
Parameters
other Another Point object to compare against.
Returns
A new Point object with the minimum x and y coordinates from this point and the other point.
References Point().
max()
template<class ValueType> Point yup::Point< ValueType >::max (const Point< ValueType > & other) const nodiscard constexpr noexcept
Computes the maximum of this point and another point based on each coordinate.
This method compares the coordinates of this point with those of another point and returns a new Point object whose coordinates are the greater values for each coordinate. It is useful for bounding calculations or extending values to constraints.
Parameters
other Another Point object to compare against.
Returns
A new Point object with the maximum x and y coordinates from this point and the other point.
References Point().
abs()
template<class ValueType> Point yup::Point< ValueType >::abs () const nodiscard constexpr noexcept
Returns a new point with the absolute values of the coordinates of this point.
This method creates a new Point object whose coordinates are the absolute values of this point's coordinates. It is useful for ensuring non-negative coordinate values in calculations and transformations.
Returns
A new Point object with the absolute values of the x and y coordinates.
References Point().
floor()
template<class ValueType> template<class T = ValueType> auto yup::Point< ValueType >::floor () const -> std::enable_if_t<std::is_floating_point_v<T>, Point> nodiscard constexpr noexcept
Floors the coordinates of this point.
This method modifies the coordinates of this point by applying the floor function to each coordinate, which rounds down to the nearest integer less than or equal to the original coordinate. It is useful for coordinate calculations that require integer values or for aligning points to a grid.
Template Parameters
T The numeric type of the coordinates, constrained to floating-point types.
Returns
A new Point object with the floored coordinates.
References Point().
ceil()
template<class ValueType> template<class T = ValueType> auto yup::Point< ValueType >::ceil () const -> std::enable_if_t<std::is_floating_point_v<T>, Point> nodiscard constexpr noexcept
Ceils the coordinates of this point.
This method modifies the coordinates of this point by applying the ceil function to each coordinate, which rounds up to the nearest integer greater than or equal to the original coordinate. It is useful for coordinate calculations that require integer values or for aligning points to a grid.
Template Parameters
T The numeric type of the coordinates, constrained to floating-point types.
Returns
A new Point object with the ceiled coordinates.
References Point().
lerp()
template<class ValueType> Point yup::Point< ValueType >::lerp (const Point< ValueType > & other, float delta) const nodiscard constexpr noexcept
Linearly interpolates between this point and another point by a specified factor.
This method computes the coordinates of a point that lies a certain way between this point and another point, based on a specified interpolation factor. The interpolation factor should be between 0 and 1, where 0 represents this point and 1 represents the other point. It is useful for smooth transitions or animations between points.
Parameters
other Another Point object to interpolate towards.
delta The interpolation factor, typically between 0.0 and 1.0, representing the position between the two points.
Returns
A new Point object representing the interpolated position between this point and the other point.
References Point().
transform()
template<class ValueType> Point & yup::Point< ValueType >::transform (const AffineTransform & t) constexpr noexcept
References Point().
Referenced by transformed().
transformed()
template<class ValueType> Point yup::Point< ValueType >::transformed (const AffineTransform & t) const nodiscard constexpr noexcept
References Point(), and transform().
to()
template<class ValueType> template<class T> Point< T > yup::Point< ValueType >::to () const nodiscard constexpr noexcept
Converts the coordinates of this point to another numeric type.
This method creates a new Point object with coordinates that are the result of casting this point's coordinates to another specified numeric type. It is useful when working with different numeric types across various calculations or APIs that require specific types.
Template Parameters
T The target numeric type to which the coordinates will be converted.
Returns
A new Point<T> object with the coordinates converted to type T.
References Point().
Referenced by yup::Desktop::getScreenContaining(), yup::Component::setPosition(), and yup::Component::setTopLeft().
roundToInt()
template<class ValueType> template<class T = ValueType> auto yup::Point< ValueType >::roundToInt () const -> std::enable_if_t<std::is_floating_point_v<T>, Point<int>> nodiscard constexpr noexcept
References Point(), and yup::roundToInt().
operator+() [1/2]
template<class ValueType> Point yup::Point< ValueType >::operator+ (const Point< ValueType > & other) const constexpr noexcept
Adds the coordinates of another point to this point and returns the result.
This method creates a new Point object whose coordinates are the result of adding the coordinates of another point to this point's coordinates. It is useful for vector addition or combining shifts in coordinates.
Parameters
other Another Point object whose coordinates are added to this point's coordinates.
Returns
A new Point object representing the sum of this point and the other point.
References Point().
operator+=() [1/2]
template<class ValueType> Point & yup::Point< ValueType >::operator+= (const Point< ValueType > & other) constexpr noexcept
Adds the coordinates of another point to this point.
This operator modifies this point's coordinates by adding the coordinates of another point to it. It is useful for vector addition or combining shifts in coordinates directly on this point.
Parameters
other Another Point object whose coordinates are added to this point's coordinates.
Returns
A reference to this Point object after the coordinates have been added.
References Point().
operator+() [2/2]
template<class ValueType> Point yup::Point< ValueType >::operator+ (ValueType amount) const constexpr noexcept
Adds a scalar value to both coordinates of this point and returns the result.
This method creates a new Point object whose coordinates are the result of adding a scalar value to both coordinates of this point. It is useful for uniform shifts in both x and y coordinates.
Parameters
amount The scalar value to add to both coordinates.
Returns
A new Point object representing the coordinates of this point plus the scalar amount.
References Point().
operator+=() [2/2]
template<class ValueType> Point & yup::Point< ValueType >::operator+= (ValueType amount) constexpr noexcept
Adds a scalar value to both coordinates of this point.
This operator modifies this point's coordinates by adding a scalar value to both coordinates. It is useful for uniform shifts in both x and y coordinates directly on this point.
Parameters
amount The scalar value to add to both coordinates.
Returns
A reference to this Point object after the scalar amount has been added.
References Point().
operator-() [1/3]
template<class ValueType> Point yup::Point< ValueType >::operator- (const Point< ValueType > & other) const constexpr noexcept
Subtracts the coordinates of another point from this point and returns the result.
This method creates a new Point object whose coordinates are the result of subtracting the coordinates of another point from this point's coordinates. It is useful for vector subtraction or determining the relative position between points.
Parameters
other Another Point object whose coordinates are subtracted from this point's coordinates.
Returns
A new Point object representing the difference between this point and the other point.
References Point().
operator-=() [1/2]
template<class ValueType> Point & yup::Point< ValueType >::operator-= (const Point< ValueType > & other) constexpr noexcept
Subtracts the coordinates of another point from this point.
This operator modifies this point's coordinates by subtracting the coordinates of another point from it. It is useful for vector subtraction or adjusting positions based on relative movements.
Parameters
other Another Point object whose coordinates are subtracted from this point's coordinates.
Returns
A reference to this Point object after the coordinates have been subtracted.
References Point().
operator-() [2/3]
template<class ValueType> Point yup::Point< ValueType >::operator- (ValueType amount) const constexpr noexcept
Subtracts a scalar value from both coordinates of this point and returns the result.
This method creates a new Point object whose coordinates are the result of subtracting a scalar value from both coordinates of this point. It is useful for uniform reductions in both x and y coordinates.
Parameters
amount The scalar value to subtract from both coordinates.
Returns
A new Point object representing the coordinates of this point minus the scalar amount.
References Point().
operator-=() [2/2]
template<class ValueType> Point & yup::Point< ValueType >::operator-= (ValueType amount) constexpr noexcept
Subtracts a scalar value from both coordinates of this point.
This operator modifies this point's coordinates by subtracting a scalar value from both coordinates. It is useful for uniform reductions in both x and y coordinates directly on this point.
Parameters
amount The scalar value to subtract from both coordinates.
Returns
A reference to this Point object after the scalar amount has been subtracted.
References Point().
operator*() [1/2]
template<class ValueType> Point yup::Point< ValueType >::operator* (const Point< ValueType > & other) const constexpr noexcept
Multiplies the coordinates of this point by the coordinates of another point and returns the result.
This method creates a new Point object whose coordinates are the result of multiplying the coordinates of this point by those of another point. It is useful for element-wise multiplication of coordinates, often used in scaling or transforming points non-uniformly.
Parameters
other Another Point object whose coordinates are multiplied by this point's coordinates.
Returns
A new Point object representing the product of the coordinates of this point and the other point.
References Point().
operator*=() [1/2]
template<class ValueType> Point & yup::Point< ValueType >::operator*= (const Point< ValueType > & other) constexpr noexcept
Multiplies the coordinates of this point by the coordinates of another point.
This operator modifies this point's coordinates by multiplying them by the coordinates of another point. It is useful for element-wise multiplication of coordinates directly on this point, often used in scaling or transforming points non-uniformly.
Parameters
other Another Point object whose coordinates are multiplied by this point's coordinates.
Returns
A reference to this Point object after the coordinates have been multiplied.
References Point().
operator*() [2/2]
template<class ValueType> Point yup::Point< ValueType >::operator* (ValueType scale) const constexpr noexcept
Multiplies both coordinates of this point by a scalar value and returns the result.
This method creates a new Point object whose coordinates are the result of multiplying both coordinates of this point by a scalar value. It is useful for uniform scaling of points, often used in resizing or adjusting distances.
Parameters
scale The scalar value by which to multiply both coordinates.
Returns
A new Point object representing the scaled coordinates of this point.
References Point(), and scale().
operator*=() [2/2]
template<class ValueType> Point & yup::Point< ValueType >::operator*= (ValueType scale) constexpr noexcept
Multiplies both coordinates of this point by a scalar value.
This operator modifies this point's coordinates by multiplying them by a scalar value. It is useful for uniform scaling of points directly on this point, often used in resizing or adjusting distances.
Parameters
scale The scalar value by which to multiply both coordinates.
Returns
A reference to this Point object after the coordinates have been scaled.
References Point(), and scale().
operator/() [1/2]
template<class ValueType> Point yup::Point< ValueType >::operator/ (const Point< ValueType > & other) const constexpr noexcept
Divides the coordinates of this point by the coordinates of another point and returns the result.
This method creates a new Point object whose coordinates are the result of dividing the coordinates of this point by those of another point. It is useful for element-wise division of coordinates, often used in proportional adjustments or creating ratios.
Parameters
other Another Point object whose coordinates are used as divisors for this point's coordinates.
Returns
A new Point object representing the quotient of the coordinates of this point and the other point.
References Point().
operator/=() [1/2]
template<class ValueType> Point & yup::Point< ValueType >::operator/= (const Point< ValueType > & other) constexpr noexcept
Divides the coordinates of this point by the coordinates of another point.
This operator modifies this point's coordinates by dividing them by the coordinates of another point. It is useful for element-wise division of coordinates directly on this point, often used in proportional adjustments or creating ratios.
Parameters
other Another Point object whose coordinates are used as divisors for this point's coordinates.
Returns
A reference to this Point object after the coordinates have been divided.
References Point().
operator/() [2/2]
template<class ValueType> Point yup::Point< ValueType >::operator/ (ValueType scale) const constexpr noexcept
Divides both coordinates of this point by a scalar value and returns the result.
This method creates a new Point object whose coordinates are the result of dividing both coordinates of this point by a scalar value. It is useful for uniform scaling down of points, often used in resizing or adjusting distances inversely.
Parameters
scale The scalar value by which to divide both coordinates.
Returns
A new Point object representing the scaled-down coordinates of this point.
References Point(), and scale().
operator/=() [2/2]
template<class ValueType> Point & yup::Point< ValueType >::operator/= (ValueType scale) constexpr noexcept
Divides both coordinates of this point by a scalar value.
This operator modifies this point's coordinates by dividing them by a scalar value. It is useful for uniform scaling down of points directly on this point, often used in resizing or adjusting distances inversely.
Parameters
scale The scalar value by which to divide both coordinates.
Returns
A reference to this Point object after the coordinates have been scaled down.
References Point(), and scale().
operator-() [3/3]
template<class ValueType> Point yup::Point< ValueType >::operator- () const constexpr noexcept
Returns a new point with negated coordinates.
This operator creates a new Point object with both coordinates negated, effectively representing this point reflected over the origin. It is useful for creating opposite or inverted points in coordinate transformations.
Returns
A new Point object with negated coordinates.
References Point(), and reflectedOverOrigin().
approximatelyEqualTo()
template<class ValueType> bool yup::Point< ValueType >::approximatelyEqualTo (const Point< ValueType > & other) const constexpr noexcept
Returns true if the two points are approximately equal.
References yup::approximatelyEqual(), and Point().
operator==()
template<class ValueType> bool yup::Point< ValueType >::operator== (const Point< ValueType > & other) const constexpr noexcept
Checks for equality between this point and another point based on their coordinates.
This operator determines if both the x and y coordinates of this point are exactly equal to those of another point. It is used for comparing positions or points in 2D space.
Parameters
other Another Point object to compare against.
Returns
True if the coordinates of both points are equal, false otherwise.
References Point().
operator!=()
template<class ValueType> bool yup::Point< ValueType >::operator!= (const Point< ValueType > & other) const constexpr noexcept
Checks for inequality between this point and another point based on their coordinates.
This operator determines if either the x or y coordinates of this point are not equal to those of another point. It is used for distinguishing positions or points in 2D space.
Parameters
other Another Point object to compare against.
Returns
True if the coordinates of the points are not equal, false if they are equal.
References Point().