YUP: yup::GraphicsContext Class Reference
yup::GraphicsContext Class Reference abstract
Encapsulates a graphics context that abstracts rendering operations across various APIs.
Classes
struct Options
Configuration options for creating a graphics context.
Public Types
enum Api {
Headless , OpenGL , Direct3D , Metal ,
Dawn
}
Enumerates supported graphics APIs.
using LoaderFunction = void* (*) (const char*)
Procedure load function used by GL and Vulkan to locate methods at runtime.
Public Member Functions
GraphicsContext () noexcept=default
Default constructor.
virtual ~GraphicsContext ()=default
Destructor.
GraphicsContext (const GraphicsContext &other) noexcept=delete
Copy and move constructors and assignment operators.
GraphicsContext (GraphicsContext &&other) noexcept=default
GraphicsContext & operator= (const GraphicsContext &other) noexcept=delete
GraphicsContext & operator= (GraphicsContext &&other) noexcept=default
virtual float dpiScale (void *nativeHandle) const =0
Returns the DPI scale associated with a native handle.
virtual rive::Factory * factory ()=0
Provides access to the associated factory for resource creation.
virtual rive::gpu::RenderContext * renderContext ()=0
Gets the PLS render context, if available.
virtual rive::gpu::RenderTarget * renderTarget ()=0
Gets the PLS render target, if available.
virtual std::unique_ptr< rive::Renderer > makeRenderer (int width, int height)=0
Creates a renderer suitable for the specified dimensions.
virtual void onSizeChanged (void *nativeHandle, int width, int height, uint32_t sampleCount)=0
Handles changes in the size of the rendering surface.
virtual void begin (const rive::gpu::RenderContext::FrameDescriptor &)=0
Begins a rendering frame.
virtual void end (void *nativeHandle)=0
Ends a rendering frame.
virtual void tick ()
Performs periodic operations, potentially related to animation or state updates.
Static Public Member Functions
static std::unique_ptr< GraphicsContext > createContext (Api graphicsApi, Options options)
Static factory method to create a graphics context using a specific graphics API.
Detailed Description
Encapsulates a graphics context that abstracts rendering operations across various APIs.
This class serves as a base for implementing specific graphics context functionalities, such as rendering and resource management, across different graphics APIs like OpenGL, Direct3D, Metal, and Dawn. It offers a standardized interface for operations common to all graphics APIs.
Member Typedef Documentation
LoaderFunction
using yup::GraphicsContext::LoaderFunction = void* (*) (const char*)
Procedure load function used by GL and Vulkan to locate methods at runtime.
Member Enumeration Documentation
Api
enum yup::GraphicsContext::Api
Enumerates supported graphics APIs.
Enumerator
Headless
Specifies the use of a headless context for rendering.
OpenGL
Specifies the use of OpenGL for rendering.
Direct3D
Specifies the use of Direct3D for rendering.
Metal
Specifies the use of Metal for rendering.
Dawn
Specifies the use of Dawn, a Vulkan-like API.
Constructor & Destructor Documentation
GraphicsContext() [1/3]
yup::GraphicsContext::GraphicsContext () default noexcept
Default constructor.
References GraphicsContext().
Referenced by GraphicsContext(), GraphicsContext(), GraphicsContext(), operator=(), operator=(), and ~GraphicsContext().
~GraphicsContext()
virtual yup::GraphicsContext::~GraphicsContext () virtual default
Destructor.
References GraphicsContext().
GraphicsContext() [2/3]
yup::GraphicsContext::GraphicsContext (const GraphicsContext & other) delete noexcept
Copy and move constructors and assignment operators.
References GraphicsContext().
GraphicsContext() [3/3]
yup::GraphicsContext::GraphicsContext (GraphicsContext && other) default noexcept
References GraphicsContext().
Member Function Documentation
operator=() [1/2]
GraphicsContext & yup::GraphicsContext::operator= (const GraphicsContext & other) delete noexcept
References GraphicsContext().
operator=() [2/2]
GraphicsContext & yup::GraphicsContext::operator= (GraphicsContext && other) default noexcept
References GraphicsContext().
dpiScale()
virtual float yup::GraphicsContext::dpiScale (void * nativeHandle) const pure virtual
Returns the DPI scale associated with a native handle.
Parameters
nativeHandle A platform-specific handle to the native window or screen.
Returns
The DPI scale factor.
References dpiScale().
Referenced by dpiScale().
factory()
virtual rive::Factory * yup::GraphicsContext::factory () pure virtual
Provides access to the associated factory for resource creation.
Returns
Pointer to a rive::Factory object.
References factory().
Referenced by factory().
renderContext()
virtual rive::gpu::RenderContext * yup::GraphicsContext::renderContext () pure virtual
Gets the PLS render context, if available.
Returns
Pointer to a rive::pls::PLSRenderContext, or nullptr if not available.
References renderContext().
Referenced by yup::Image::createTextureIfNotPresent(), and renderContext().
renderTarget()
virtual rive::gpu::RenderTarget * yup::GraphicsContext::renderTarget () pure virtual
Gets the PLS render target, if available.
Returns
Pointer to a rive::pls::PLSRenderTarget, or nullptr if not available.
References renderTarget().
Referenced by renderTarget().
makeRenderer()
virtual std::unique_ptr< rive::Renderer > yup::GraphicsContext::makeRenderer (int width, int height) pure virtual
Creates a renderer suitable for the specified dimensions.
Parameters
width The width of the render area.
height The height of the render area.
Returns
A unique pointer to a rive::Renderer object.
References makeRenderer().
Referenced by makeRenderer().
onSizeChanged()
virtual void yup::GraphicsContext::onSizeChanged (void * nativeHandle, int width, int height, uint32_t sampleCount) pure virtual
Handles changes in the size of the rendering surface.
Parameters
nativeHandle A platform-specific handle to the native window or screen.
width The new width of the surface.
height The new height of the surface.
sampleCount The number of samples per pixel, for anti-aliasing.
References onSizeChanged().
Referenced by onSizeChanged().
begin()
virtual void yup::GraphicsContext::begin (const rive::gpu::RenderContext::FrameDescriptor &) pure virtual
Begins a rendering frame.
Parameters
descriptor The frame descriptor that contains frame-specific data.
References begin().
Referenced by begin().
end()
virtual void yup::GraphicsContext::end (void * nativeHandle) pure virtual
Ends a rendering frame.
Parameters
nativeHandle A platform-specific handle to the native window or screen.
References end().
Referenced by end().
tick()
virtual void yup::GraphicsContext::tick () virtual
Performs periodic operations, potentially related to animation or state updates.
References tick().
Referenced by tick().
createContext()
std::unique_ptr< GraphicsContext > yup::GraphicsContext::createContext (Api graphicsApi, Options options) static
Static factory method to create a graphics context using a specific graphics API.
Parameters
graphicsApi The graphics API to use.
options Configuration options for the graphics context.
Returns
A unique pointer to a GraphicsContext, using the specified graphics API and configured according to the options.