YUP: yup::Rectangle< ValueType > Class Template Reference
yup::Rectangle< ValueType > Class Template Reference
Represents a rectangle in 2D space.
Public Member Functions
constexpr Rectangle () noexcept=default
Default constructor, initializes a rectangle with default values.
constexpr Rectangle (ValueType x, ValueType y, ValueType width, ValueType height) noexcept
Constructs a rectangle with specified x, y, width, and height.
constexpr Rectangle (ValueType x, ValueType y, const Size< ValueType > &size) noexcept
Constructs a rectangle with specified x, y coordinates and size.
constexpr Rectangle (const Point< ValueType > &xy, ValueType width, ValueType height) noexcept
Constructs a rectangle with specified position as a Point and dimensions.
constexpr Rectangle (const Point< ValueType > &xy, const Size< ValueType > &size) noexcept
Constructs a rectangle with specified position as a Point and size as a Size object.
template<class T, class = std::enable_if_t<! std::is_same_v<T, ValueType>>>
constexpr Rectangle (const Rectangle< T > &other) noexcept
Constructs a rectangle by converting from another type.
template<class T, class = std::enable_if_t<! std::is_same_v<T, ValueType>>>
constexpr Rectangle (const Point< T > &xy, const Size< T > &size) noexcept
Constructs a rectangle by converting from another type position and size.
constexpr Rectangle (const Rectangle &other) noexcept=default
Copy and move constructors and assignment operators.
constexpr Rectangle (Rectangle &&other) noexcept=default
constexpr Rectangle & operator= (const Rectangle &other) noexcept=default
constexpr Rectangle & operator= (Rectangle &&other) noexcept=default
constexpr ValueType getX () const noexcept
Returns the x-coordinate of the rectangle's top-left corner.
constexpr Rectangle & setX (ValueType newX) noexcept
Sets the x-coordinate of the rectangle's top-left corner.
constexpr Rectangle withX (ValueType newX) const noexcept
Returns a new rectangle with the x-coordinate of the top-left corner set to a new value.
constexpr ValueType getY () const noexcept
Returns the y-coordinate of the rectangle's top-left corner.
constexpr Rectangle & setY (ValueType newY) noexcept
Sets the y-coordinate of the rectangle's top-left corner.
constexpr Rectangle withY (ValueType newY) const noexcept
Returns a new rectangle with the y-coordinate of the top-left corner set to a new value.
constexpr ValueType getLeft () const noexcept
Returns the left-coordinate of the rectangle's top-left corner.
constexpr Rectangle withLeft (ValueType amount) const noexcept
Returns a new rectangle with the left-coordinate of the top-left corner set to a new value.
constexpr Rectangle withTrimmedLeft (ValueType amountToTrim) const noexcept
Returns a new rectangle with the left-coordinate of the top-left corner trimmed by a specified amount.
constexpr ValueType getTop () const noexcept
Returns the top-coordinate of the rectangle's top-left corner.
constexpr Rectangle withTop (ValueType amount) const noexcept
Returns a new rectangle with the top-coordinate of the top-left corner set to a new value.
constexpr Rectangle withTrimmedTop (ValueType amountToTrim) const noexcept
Returns a new rectangle with the top-coordinate of the top-left corner trimmed by a specified amount.
constexpr ValueType getRight () const noexcept
Returns the right-coordinate of the rectangle's bottom-right corner.
constexpr Rectangle withTrimmedRight (ValueType amountToTrim) const noexcept
Returns a new rectangle with the right-coordinate of the bottom-right corner trimmed by a specified amount.
constexpr ValueType getBottom () const noexcept
Returns the bottom-coordinate of the rectangle's bottom-right corner.
constexpr Rectangle withTrimmedBottom (ValueType amountToTrim) const noexcept
Returns a new rectangle with the bottom-coordinate of the bottom-right corner trimmed by a specified amount.
constexpr ValueType getWidth () const noexcept
Returns the width of the rectangle.
constexpr Rectangle & setWidth (ValueType newWidth) noexcept
Sets the width of the rectangle.
constexpr Rectangle withWidth (ValueType newWidth) const noexcept
Returns a new rectangle with the width set to a new value.
constexpr ValueType proportionOfWidth (float proportion) const noexcept
Returns a new rectangle with the width set to a specified proportion of the original width.
constexpr ValueType getHeight () const noexcept
Returns the height of the rectangle.
constexpr Rectangle & setHeight (ValueType newHeight) noexcept
Sets the height of the rectangle.
constexpr Rectangle withHeight (ValueType newHeight) const noexcept
Returns a new rectangle with the height set to a new value.
constexpr ValueType proportionOfHeight (float proportion) const noexcept
Returns a new rectangle with the height set to a specified proportion of the original height.
constexpr Point< ValueType > getPosition () const noexcept
Returns the position of the rectangle's top-left corner as a Point.
constexpr Rectangle & setPosition (const Point< ValueType > &newPosition) noexcept
Sets the position of the rectangle's top-left corner.
template<class T>
constexpr Rectangle withPosition (const Point< T > &newPosition) const noexcept
Returns a new rectangle with the specified position.
template<class T>
constexpr Rectangle withPosition (T x, T y) const noexcept
Returns a new rectangle with the specified position coordinates.
constexpr Rectangle withZeroPosition () const noexcept
Returns a new rectangle with its position set to (0, 0).
constexpr Point< ValueType > getTopLeft () const noexcept
Returns the position of the top-left corner of the rectangle.
constexpr Rectangle & setTopLeft (const Point< ValueType > &newPosition) noexcept
Sets the position of the rectangle's top-left corner.
constexpr Rectangle withTopLeft (const Point< ValueType > &newPosition) const noexcept
Sets the position of the rectangle's top-left corner.
constexpr Point< ValueType > getTopRight () const noexcept
Returns the position of the top-right corner of the rectangle.
constexpr Rectangle & setTopRight (const Point< ValueType > &newPosition) noexcept
Sets the position of the rectangle's top-left corner.
constexpr Rectangle withTopRight (const Point< ValueType > &newPosition) const noexcept
Sets the position of the rectangle's top-right corner.
constexpr Point< ValueType > getBottomLeft () const noexcept
Returns the position of the bottom-left corner of the rectangle.
constexpr Rectangle & setBottomLeft (const Point< ValueType > &newPosition) noexcept
Sets the position of the rectangle's bottom-left corner.
constexpr Rectangle withBottomLeft (const Point< ValueType > &newPosition) const noexcept
Sets the position of the rectangle's bottom-left corner.
constexpr Point< ValueType > getBottomRight () const noexcept
Returns the position of the bottom-right corner of the rectangle.
constexpr Rectangle & setBottomRight (const Point< ValueType > &newPosition) noexcept
Sets the position of the rectangle's bottom-right corner.
constexpr Rectangle withBottomRight (const Point< ValueType > &newPosition) const noexcept
Sets the position of the rectangle's bottom-right corner.
constexpr Size< ValueType > getSize () const noexcept
Returns the size of the rectangle.
constexpr Rectangle & setSize (const Size< ValueType > &newSize) noexcept
Sets the size of the rectangle.
template<class T>
constexpr Rectangle withSize (const Size< T > &newSize) const noexcept
Returns a new rectangle with the specified size.
template<class T>
constexpr Rectangle withSize (T width, T height) const noexcept
Returns a new rectangle with the specified dimensions.
template<class T>
constexpr auto withScaledSize (T scaleFactor) const noexcept -> std::enable_if_t< std::is_floating_point_v< T >, Rectangle >
Returns a new rectangle with its size scaled by a factor.
constexpr Rectangle withZeroSize () const noexcept
Returns a new rectangle with its size set to zero.
constexpr Rectangle & setBounds (ValueType x, ValueType y, ValueType width, ValueType height) noexcept
Sets the bounds of the rectangle.
constexpr ValueType getCenterX () const noexcept
Returns the center X of the rectangle.
constexpr Rectangle & setCenterX (ValueType centerX) noexcept
Sets the center X of the rectangle.
constexpr ValueType getCenterY () const noexcept
Returns the center Y of the rectangle.
constexpr Rectangle & setCenterY (ValueType centerY) noexcept
Sets the center Y of the rectangle.
constexpr Point< ValueType > getCenter () const noexcept
Returns the center point of the rectangle.
constexpr Rectangle & setCenter (ValueType centerX, ValueType centerY) noexcept
Sets the center of the rectangle to the specified coordinates.
constexpr Rectangle & setCenter (const Point< ValueType > &center) noexcept
Sets the center of the rectangle to the specified point.
constexpr Rectangle withCenter (ValueType centerX, ValueType centerY) noexcept
Returns a new rectangle with its center set to the specified coordinates.
constexpr Rectangle withCenter (const Point< ValueType > &center) noexcept
Returns a new rectangle with its center set to the specified point.
constexpr Rectangle withCenterX (ValueType centerX) noexcept
Returns a new rectangle with its center X set to the specified value.
constexpr Rectangle withCenterY (ValueType centerY) noexcept
Returns a new rectangle with its center Y set to the specified value.
constexpr bool isEmpty () const noexcept
Checks if the rectangle's size is zero.
constexpr bool isPoint () const noexcept
Checks if the rectangle's size is zero (i.e., it is a point).
constexpr bool isLine () const noexcept
Checks if the rectangle is a line (either horizontal or vertical).
constexpr bool isVerticalLine () const noexcept
Checks if the rectangle is a vertical line.
constexpr bool isHorizontalLine () const noexcept
Checks if the rectangle is a horizontal line.
constexpr Line< ValueType > leftSide () const noexcept
Returns the line representing the left side of the rectangle.
constexpr Line< ValueType > topSide () const noexcept
Returns the line representing the top side of the rectangle.
constexpr Line< ValueType > rightSide () const noexcept
Returns the line representing the right side of the rectangle.
constexpr Line< ValueType > bottomSide () const noexcept
Returns the line representing the bottom side of the rectangle.
constexpr Line< ValueType > diagonalTopToBottom () const noexcept
Returns the diagonal line from the top-left to the bottom-right corner of the rectangle.
constexpr Line< ValueType > diagonalBottomToTop () const noexcept
Returns the diagonal line from the bottom-left to the top-right corner of the rectangle.
constexpr Rectangle & translate (ValueType deltaX, ValueType deltaY) noexcept
Translates the rectangle by the specified x and y offsets.
constexpr Rectangle & translate (const Point< ValueType > &delta) noexcept
Translates the rectangle by the specified point.
constexpr Rectangle< ValueType > translated (ValueType deltaX, ValueType deltaY) const noexcept
Returns a new rectangle translated by the specified x and y offsets.
constexpr Rectangle< ValueType > translated (const Point< ValueType > &delta) const noexcept
Returns a new rectangle translated by the specified point.
constexpr Rectangle & scale (float factor) noexcept
Scales the size of the rectangle uniformly by a given factor.
constexpr Rectangle & scale (float factorX, float factorY) noexcept
Scales the size of the rectangle by the specified x and y factors.
constexpr Rectangle scaled (float factor) const noexcept
Returns a new rectangle with its size scaled uniformly by the specified factor.
constexpr Rectangle scaled (float factorX, float factorY) const noexcept
Returns a new rectangle with its size scaled by the specified x and y factors.
constexpr Rectangle removeFromTop (ValueType delta) noexcept
Removes a specified height from the top of the rectangle, adjusting its size and position.
constexpr Rectangle removeFromLeft (ValueType delta) noexcept
Removes a specified width from the left side of the rectangle, adjusting its size and position.
constexpr Rectangle removeFromBottom (ValueType delta) noexcept
Removes a specified height from the bottom of the rectangle, adjusting its size and position.
constexpr Rectangle removeFromRight (ValueType delta) noexcept
Removes a specified width from the right side of the rectangle, adjusting its size and position.
constexpr Rectangle & reduce (ValueType delta) noexcept
Reduces the size of the rectangle by a uniform amount on all sides.
constexpr Rectangle & reduce (ValueType deltaX, ValueType deltaY) noexcept
Reduces the width and height of the rectangle by different amounts on all sides.
constexpr Rectangle & reduce (ValueType left, ValueType top, ValueType right, ValueType bottom) noexcept
Reduces the size of the rectangle by different amounts on all sides.
constexpr Rectangle reduced (ValueType delta) const noexcept
Returns a new rectangle with its size reduced by a uniform amount on all sides.
constexpr Rectangle reduced (ValueType deltaX, ValueType deltaY) const noexcept
Returns a new rectangle with its width and height reduced by different amounts on all sides.
constexpr Rectangle reduced (ValueType left, ValueType top, ValueType right, ValueType bottom) const noexcept
Returns a new rectangle with its size reduced by different amounts on all sides.
constexpr Rectangle reducedLeft (ValueType delta) const noexcept
Returns a new rectangle with its width reduced by a specified amount on the left side.
constexpr Rectangle reducedTop (ValueType delta) const noexcept
Returns a new rectangle with its height reduced by a specified amount on the top side.
constexpr Rectangle reducedRight (ValueType delta) const noexcept
Returns a new rectangle with its width reduced by a specified amount on the right side.
constexpr Rectangle reducedBottom (ValueType delta) const noexcept
Returns a new rectangle with its height reduced by a specified amount on the bottom side.
constexpr Rectangle & enlarge (ValueType delta) noexcept
Enlarges the size of the rectangle by a uniform amount on all sides.
constexpr Rectangle & enlarge (ValueType deltaX, ValueType deltaY) noexcept
Enlarges the width and height of the rectangle by different amounts on all sides.
constexpr Rectangle & enlarge (ValueType left, ValueType top, ValueType right, ValueType bottom) noexcept
Enlarges the size of the rectangle by different amounts on all sides.
constexpr Rectangle enlarged (ValueType delta) const noexcept
Returns a new rectangle with its size reduced by a uniform amount on all sides.
constexpr Rectangle enlarged (ValueType deltaX, ValueType deltaY) const noexcept
Returns a new rectangle with its width and height reduced by different amounts on all sides.
constexpr Rectangle enlargedLeft (ValueType delta) const noexcept
Returns a new rectangle with its width enlarged by a specified amount on the left side.
constexpr Rectangle enlargedTop (ValueType delta) const noexcept
Returns a new rectangle with its height enlarged by a specified amount on the top side.
constexpr Rectangle enlargedRight (ValueType delta) const noexcept
Returns a new rectangle with its width enlarged by a specified amount on the right side.
constexpr Rectangle enlargedBottom (ValueType delta) const noexcept
Returns a new rectangle with its height enlarged by a specified amount on the bottom side.
constexpr bool contains (ValueType x, ValueType y) const noexcept
Checks if the specified point lies within the bounds of the rectangle.
constexpr bool contains (const Point< ValueType > &p) const noexcept
Checks if the specified point lies within the bounds of the rectangle.
constexpr ValueType area () const noexcept
Calculates the area of the rectangle.
constexpr bool intersects (const Rectangle &other) const noexcept
Checks if this rectangle intersects with another rectangle.
constexpr Rectangle intersection (const Rectangle &other) const noexcept
Returns the intersection of this rectangle with another rectangle.
constexpr Rectangle largestFittingSquare () const noexcept
Returns the largest square that fits within the rectangle.
constexpr Rectangle unionWith (const Rectangle &other) const noexcept
Returns the smallest containing rectangle between this and another rectangle.
constexpr Rectangle centeredRectangleWithSize (const Size< ValueType > &sizeOfRectangleToCenter) const noexcept
Aligns a Size to this rectangle.
Rectangle & transform (const AffineTransform &t) noexcept
Transforms the rectangle by an affine transformation.
Rectangle transformed (const AffineTransform &t) const noexcept
Returns a new rectangle transformed by an affine transformation.
template<class T>
constexpr Rectangle< T > to () const noexcept
Converts the rectangle to a different type.
template<class T = ValueType>
constexpr auto roundToInt () const noexcept -> std::enable_if_t< std::is_floating_point_v< T >, Rectangle< int > >
Rounds the rectangle's position and size to integers.
template<class T>
constexpr auto operator* (T scaleFactor) const noexcept -> std::enable_if_t< std::is_floating_point_v< T >, Rectangle >
Multiplies the size and position of the rectangle by a scale factor.
template<class T>
constexpr auto operator*= (T scaleFactor) noexcept -> std::enable_if_t< std::is_floating_point_v< T >, Rectangle & >
Scales the size and position of the rectangle in place by a scale factor.
template<class T>
constexpr auto operator/ (T scaleFactor) const noexcept -> std::enable_if_t< std::is_floating_point_v< T >, Rectangle >
Divides the size and position of the rectangle by a scale factor.
template<class T>
constexpr auto operator/= (T scaleFactor) noexcept -> std::enable_if_t< std::is_floating_point_v< T >, Rectangle & >
Divides the size and position of the rectangle in place by a scale factor.
constexpr bool approximatelyEqualTo (const Rectangle &other) const noexcept
Returns true if the two rectangles are approximately equal.
constexpr bool operator== (const Rectangle &other) const noexcept
Checks for equality between this rectangle and another rectangle.
constexpr bool operator!= (const Rectangle &other) const noexcept
Checks for inequality between this rectangle and another rectangle.
Rectangle (const rive::AABB &aabb) noexcept
rive::AABB toAABB () const
Detailed Description
template<class ValueType>
class yup::Rectangle< ValueType >
Represents a rectangle in 2D space.
This class template provides a way to store and manipulate rectangles defined by their position (x, y) and size (width, height). The ValueType template parameter determines the type of these values (e.g., int, float). This class includes various methods for rectangle manipulations such as translation, scaling, intersection checks, and transformations among others.
Constructor & Destructor Documentation
Rectangle() [1/10]
template<class ValueType> yup::Rectangle< ValueType >::Rectangle () constexpr default noexcept
Default constructor, initializes a rectangle with default values.
Creates a rectangle where all the dimensions and positions are set to zero.
Referenced by approximatelyEqualTo(), centeredRectangleWithSize(), enlarge(), enlarge(), enlarge(), enlarged(), enlarged(), enlargedBottom(), enlargedLeft(), enlargedRight(), enlargedTop(), intersection(), intersects(), largestFittingSquare(), operator!=(), operator*(), operator*=(), operator/(), operator/=(), operator=(), operator=(), operator==(), Rectangle(), Rectangle(), Rectangle(), Rectangle(), reduce(), reduce(), reduce(), reduced(), reduced(), reduced(), reducedBottom(), reducedLeft(), reducedRight(), reducedTop(), removeFromBottom(), removeFromLeft(), removeFromRight(), removeFromTop(), roundToInt(), scale(), scale(), scaled(), scaled(), setBottomLeft(), setBottomRight(), setBounds(), setCenter(), setCenter(), setCenterX(), setCenterY(), setHeight(), setPosition(), setSize(), setTopLeft(), setTopRight(), setWidth(), setX(), setY(), to(), transform(), transformed(), translate(), translate(), translated(), translated(), unionWith(), withBottomLeft(), withBottomRight(), withCenter(), withCenter(), withCenterX(), withCenterY(), withHeight(), withLeft(), withPosition(), withPosition(), withScaledSize(), withSize(), withSize(), withTop(), withTopLeft(), withTopRight(), withTrimmedBottom(), withTrimmedLeft(), withTrimmedRight(), withTrimmedTop(), withWidth(), withX(), withY(), withZeroPosition(), and withZeroSize().
Rectangle() [2/10]
template<class ValueType> yup::Rectangle< ValueType >::Rectangle (ValueType x, ValueType y, ValueType width, ValueType height) constexpr noexcept
Constructs a rectangle with specified x, y, width, and height.
Parameters
x The x-coordinate of the top-left corner.
y The y-coordinate of the top-left corner.
width The width of the rectangle.
height The height of the rectangle.
References Rectangle().
Rectangle() [3/10]
template<class ValueType> yup::Rectangle< ValueType >::Rectangle (ValueType x, ValueType y, const Size< ValueType > & size) constexpr noexcept
Constructs a rectangle with specified x, y coordinates and size.
Parameters
x The x-coordinate of the top-left corner.
y The y-coordinate of the top-left corner.
size The size of the rectangle as a Size object.
Rectangle() [4/10]
template<class ValueType> yup::Rectangle< ValueType >::Rectangle (const Point< ValueType > & xy, ValueType width, ValueType height) constexpr noexcept
Constructs a rectangle with specified position as a Point and dimensions.
Parameters
xy The position of the top-left corner as a Point.
width The width of the rectangle.
height The height of the rectangle.
Rectangle() [5/10]
template<class ValueType> yup::Rectangle< ValueType >::Rectangle (const Point< ValueType > & xy, const Size< ValueType > & size) constexpr noexcept
Constructs a rectangle with specified position as a Point and size as a Size object.
Parameters
xy The position of the top-left corner as a Point.
size The size of the rectangle.
Rectangle() [6/10]
template<class ValueType> template<class T, class = std::enable_if_t<! std::is_same_v<T, ValueType>>> yup::Rectangle< ValueType >::Rectangle (const Rectangle< T > & other) constexpr noexcept
Constructs a rectangle by converting from another type.
This constructor template allows for the creation of a Rectangle from another Rectangle of a different ValueType, converting the position and size appropriately.
Template Parameters
T The type of the value from the source rectangle.
Parameters
other The source rectangle from which to convert.
References Rectangle(), and to().
Rectangle() [7/10]
template<class ValueType> template<class T, class = std::enable_if_t<! std::is_same_v<T, ValueType>>> yup::Rectangle< ValueType >::Rectangle (const Point< T > & xy, const Size< T > & size) constexpr noexcept
Constructs a rectangle by converting from another type position and size.
Template Parameters
T The type of the value from the source rectangle.
Parameters
other The source rectangle from which to convert.
References to().
Rectangle() [8/10]
template<class ValueType> yup::Rectangle< ValueType >::Rectangle (const Rectangle< ValueType > & other) constexpr default noexcept
Copy and move constructors and assignment operators.
References Rectangle().
Rectangle() [9/10]
template<class ValueType> yup::Rectangle< ValueType >::Rectangle (Rectangle< ValueType > && other) constexpr default noexcept
References Rectangle().
Rectangle() [10/10]
template<class ValueType> yup::Rectangle< ValueType >::Rectangle (const rive::AABB & aabb) noexcept
Member Function Documentation
operator=() [1/2]
template<class ValueType> Rectangle & yup::Rectangle< ValueType >::operator= (const Rectangle< ValueType > & other) constexpr default noexcept
References Rectangle().
operator=() [2/2]
template<class ValueType> Rectangle & yup::Rectangle< ValueType >::operator= (Rectangle< ValueType > && other) constexpr default noexcept
References Rectangle().
getX()
template<class ValueType> ValueType yup::Rectangle< ValueType >::getX () const nodiscard constexpr noexcept
Returns the x-coordinate of the rectangle's top-left corner.
Returns
The x-coordinate value.
Referenced by yup::Path::addArc(), yup::Path::addBubble(), yup::Path::addEllipse(), yup::Path::addRectangle(), yup::Path::addRoundedRectangle(), yup::Path::addRoundedRectangle(), centeredRectangleWithSize(), yup::Graphics::fillRect(), yup::Graphics::fillRoundedRect(), yup::Graphics::fillRoundedRect(), intersection(), intersects(), yup::RectangleList< ValueType >::intersects(), yup::Path::scaleToFit(), yup::Graphics::strokeRect(), yup::Graphics::strokeRoundedRect(), yup::Graphics::strokeRoundedRect(), transform(), and unionWith().
setX()
template<class ValueType> Rectangle & yup::Rectangle< ValueType >::setX (ValueType newX) constexpr noexcept
Sets the x-coordinate of the rectangle's top-left corner.
Parameters
newX The new x-coordinate for the top-left corner.
Returns
A reference to this rectangle to allow method chaining.
References Rectangle().
withX()
template<class ValueType> Rectangle yup::Rectangle< ValueType >::withX (ValueType newX) const nodiscard constexpr noexcept
Returns a new rectangle with the x-coordinate of the top-left corner set to a new value.
This method creates a new rectangle with the same size and y-coordinate, but with the x-coordinate of the top-left corner changed to the specified value.
Parameters
newX The new x-coordinate for the top-left corner.
Returns
A new rectangle with the updated x-coordinate.
References Rectangle().
getY()
template<class ValueType> ValueType yup::Rectangle< ValueType >::getY () const nodiscard constexpr noexcept
Returns the y-coordinate of the rectangle's top-left corner.
Returns
The y-coordinate value.
Referenced by yup::Path::addArc(), yup::Path::addBubble(), yup::Path::addEllipse(), yup::Path::addRectangle(), yup::Path::addRoundedRectangle(), yup::Path::addRoundedRectangle(), centeredRectangleWithSize(), yup::Graphics::fillRect(), yup::Graphics::fillRoundedRect(), yup::Graphics::fillRoundedRect(), intersection(), intersects(), yup::RectangleList< ValueType >::intersects(), yup::Path::scaleToFit(), yup::Graphics::strokeRect(), yup::Graphics::strokeRoundedRect(), yup::Graphics::strokeRoundedRect(), transform(), and unionWith().
setY()
template<class ValueType> Rectangle & yup::Rectangle< ValueType >::setY (ValueType newY) constexpr noexcept
Sets the y-coordinate of the rectangle's top-left corner.
Parameters
newY The new y-coordinate for the top-left corner.
Returns
A reference to this rectangle to allow method chaining.
References Rectangle().
withY()
template<class ValueType> Rectangle yup::Rectangle< ValueType >::withY (ValueType newY) const nodiscard constexpr noexcept
Returns a new rectangle with the y-coordinate of the top-left corner set to a new value.
This method creates a new rectangle with the same size and x-coordinate, but with the y-coordinate of the top-left corner changed to the specified value.
Parameters
newY The new y-coordinate for the top-left corner.
Returns
A new rectangle with the updated y-coordinate.
References Rectangle().
getLeft()
template<class ValueType> ValueType yup::Rectangle< ValueType >::getLeft () const nodiscard constexpr noexcept
Returns the left-coordinate of the rectangle's top-left corner.
Returns
The left-coordinate value.
Referenced by toAABB().
withLeft()
template<class ValueType> Rectangle yup::Rectangle< ValueType >::withLeft (ValueType amount) const nodiscard constexpr noexcept
Returns a new rectangle with the left-coordinate of the top-left corner set to a new value.
This method creates a new rectangle with the same size and y-coordinate, but with the left-coordinate of the top-left corner changed to the specified value.
Parameters
amount The new left-coordinate for the top-left corner.
Returns
A new rectangle with the updated left-coordinate.
References Rectangle().
Referenced by withTrimmedLeft().
withTrimmedLeft()
template<class ValueType> Rectangle yup::Rectangle< ValueType >::withTrimmedLeft (ValueType amountToTrim) const nodiscard constexpr noexcept
Returns a new rectangle with the left-coordinate of the top-left corner trimmed by a specified amount.
This method creates a new rectangle with the same size and y-coordinate, but with the left-coordinate of the top-left corner reduced by the specified amount.
Parameters
amountToTrim The amount to trim from the left-coordinate.
Returns
A new rectangle with the updated left-coordinate.
References Rectangle(), and withLeft().
getTop()
template<class ValueType> ValueType yup::Rectangle< ValueType >::getTop () const nodiscard constexpr noexcept
Returns the top-coordinate of the rectangle's top-left corner.
Returns
The top-coordinate value.
Referenced by toAABB().
withTop()
template<class ValueType> Rectangle yup::Rectangle< ValueType >::withTop (ValueType amount) const nodiscard constexpr noexcept
Returns a new rectangle with the top-coordinate of the top-left corner set to a new value.
This method creates a new rectangle with the same size and x-coordinate, but with the top-coordinate of the top-left corner changed to the specified value.
Parameters
amount The new top-coordinate for the top-left corner.
Returns
A new rectangle with the updated top-coordinate.
References Rectangle().
Referenced by withTrimmedTop().
withTrimmedTop()
template<class ValueType> Rectangle yup::Rectangle< ValueType >::withTrimmedTop (ValueType amountToTrim) const nodiscard constexpr noexcept
Returns a new rectangle with the top-coordinate of the top-left corner trimmed by a specified amount.
This method creates a new rectangle with the same size and x-coordinate, but with the top-coordinate of the top-left corner reduced by the specified amount.
Parameters
amountToTrim The amount to trim from the top-coordinate.
Returns
A new rectangle with the updated top-coordinate.
References Rectangle(), and withTop().
getRight()
template<class ValueType> ValueType yup::Rectangle< ValueType >::getRight () const nodiscard constexpr noexcept
Returns the right-coordinate of the rectangle's bottom-right corner.
Returns
The right-coordinate value.
Referenced by yup::Path::addBubble(), and toAABB().
withTrimmedRight()
template<class ValueType> Rectangle yup::Rectangle< ValueType >::withTrimmedRight (ValueType amountToTrim) const nodiscard constexpr noexcept
Returns a new rectangle with the right-coordinate of the bottom-right corner trimmed by a specified amount.
This method creates a new rectangle with the same size and y-coordinate, but with the right-coordinate of the bottom-right corner reduced by the specified amount.
Parameters
amountToTrim The amount to trim from the right-coordinate.
Returns
A new rectangle with the updated right-coordinate.
References Rectangle(), and withWidth().
getBottom()
template<class ValueType> ValueType yup::Rectangle< ValueType >::getBottom () const nodiscard constexpr noexcept
Returns the bottom-coordinate of the rectangle's bottom-right corner.
Returns
The bottom-coordinate value.
Referenced by yup::Path::addBubble(), and toAABB().
withTrimmedBottom()
template<class ValueType> Rectangle yup::Rectangle< ValueType >::withTrimmedBottom (ValueType amountToTrim) const nodiscard constexpr noexcept
Returns a new rectangle with the bottom-coordinate of the bottom-right corner trimmed by a specified amount.
This method creates a new rectangle with the same size and x-coordinate, but with the bottom-coordinate of the bottom-right corner reduced by the specified amount.
Parameters
amountToTrim The amount to trim from the bottom-coordinate.
Returns
A new rectangle with the updated bottom-coordinate.
References Rectangle(), and withHeight().
getWidth()
template<class ValueType> ValueType yup::Rectangle< ValueType >::getWidth () const nodiscard constexpr noexcept
Returns the width of the rectangle.
Returns
The width value.
Referenced by yup::Path::addArc(), yup::Path::addBubble(), yup::Path::addEllipse(), yup::Path::addRectangle(), yup::Path::addRoundedRectangle(), yup::Path::addRoundedRectangle(), bottomSide(), centeredRectangleWithSize(), diagonalBottomToTop(), diagonalTopToBottom(), yup::Graphics::fillRect(), yup::Graphics::fillRoundedRect(), yup::Graphics::fillRoundedRect(), getBottomRight(), yup::StyledText::getOffset(), getTopRight(), intersection(), yup::RectangleList< ValueType >::intersects(), largestFittingSquare(), rightSide(), yup::Path::scaleToFit(), setTopRight(), yup::Graphics::strokeRect(), yup::Graphics::strokeRoundedRect(), yup::Graphics::strokeRoundedRect(), topSide(), transform(), and unionWith().
setWidth()
template<class ValueType> Rectangle & yup::Rectangle< ValueType >::setWidth (ValueType newWidth) constexpr noexcept
Sets the width of the rectangle.
Parameters
newWidth The new width for the rectangle.
Returns
A reference to this rectangle to allow method chaining.
References Rectangle().
withWidth()
template<class ValueType> Rectangle yup::Rectangle< ValueType >::withWidth (ValueType newWidth) const nodiscard constexpr noexcept
Returns a new rectangle with the width set to a new value.
This method creates a new rectangle with the same position but changes the width to the specified value. The height remains unchanged.
Parameters
newWidth The new width for the rectangle.
Returns
A new rectangle with the updated width.
References Rectangle().
Referenced by withTrimmedRight().
proportionOfWidth()
template<class ValueType> ValueType yup::Rectangle< ValueType >::proportionOfWidth (float proportion) const nodiscard constexpr noexcept
Returns a new rectangle with the width set to a specified proportion of the original width.
This method creates a new rectangle with the same position but changes the width to a specified proportion of the original width. The height remains unchanged.
Parameters
proportion The proportion of the original width to use for the new width.
Returns
The new width value.
getHeight()
template<class ValueType> ValueType yup::Rectangle< ValueType >::getHeight () const nodiscard constexpr noexcept
Returns the height of the rectangle.
Returns
The height value.
Referenced by yup::Path::addArc(), yup::Path::addBubble(), yup::Path::addEllipse(), yup::Path::addRectangle(), yup::Path::addRoundedRectangle(), yup::Path::addRoundedRectangle(), bottomSide(), centeredRectangleWithSize(), diagonalBottomToTop(), diagonalTopToBottom(), yup::Graphics::fillRect(), yup::Graphics::fillRoundedRect(), yup::Graphics::fillRoundedRect(), getBottomLeft(), getBottomRight(), yup::StyledText::getOffset(), intersection(), yup::RectangleList< ValueType >::intersects(), largestFittingSquare(), leftSide(), rightSide(), yup::Path::scaleToFit(), setBottomLeft(), setBottomRight(), yup::Graphics::strokeRect(), yup::Graphics::strokeRoundedRect(), yup::Graphics::strokeRoundedRect(), transform(), and unionWith().
setHeight()
template<class ValueType> Rectangle & yup::Rectangle< ValueType >::setHeight (ValueType newHeight) constexpr noexcept
Sets the height of the rectangle.
Parameters
newHeight The new height for the rectangle.
Returns
A reference to this rectangle to allow method chaining.
References Rectangle().
withHeight()
template<class ValueType> Rectangle yup::Rectangle< ValueType >::withHeight (ValueType newHeight) const nodiscard constexpr noexcept
Returns a new rectangle with the height set to a new value.
This method creates a new rectangle with the same position but changes the height to the specified value. The width remains unchanged.
Parameters
newHeight The new height for the rectangle.
Returns
A new rectangle with the updated height.
References Rectangle().
Referenced by withTrimmedBottom().
proportionOfHeight()
template<class ValueType> ValueType yup::Rectangle< ValueType >::proportionOfHeight (float proportion) const nodiscard constexpr noexcept
Returns a new rectangle with the height set to a specified proportion of the original height.
This method creates a new rectangle with the same position but changes the height to a specified proportion of the original height. The width remains unchanged.
Parameters
proportion The proportion of the original height to use for the new height.
Returns
The new height value.
getPosition()
template<class ValueType> Point< ValueType > yup::Rectangle< ValueType >::getPosition () const nodiscard constexpr noexcept
Returns the position of the rectangle's top-left corner as a Point.
Returns
The position as a Point object.
setPosition()
template<class ValueType> Rectangle & yup::Rectangle< ValueType >::setPosition (const Point< ValueType > & newPosition) constexpr noexcept
Sets the position of the rectangle's top-left corner.
Parameters
newPosition The new position for the top-left corner as a Point.
Returns
A reference to this rectangle to allow method chaining.
References Rectangle().
withPosition() [1/2]
template<class ValueType> template<class T> Rectangle yup::Rectangle< ValueType >::withPosition (const Point< T > & newPosition) const nodiscard constexpr noexcept
Returns a new rectangle with the specified position.
This method creates a new rectangle with the same size but a different position.
Template Parameters
T The type of the value for the new position.
Parameters
newPosition The new position for the rectangle as a Point.
Returns
A new rectangle with the updated position.
References Rectangle(), and to().
withPosition() [2/2]
template<class ValueType> template<class T> Rectangle yup::Rectangle< ValueType >::withPosition (T x, T y) const nodiscard constexpr noexcept
Returns a new rectangle with the specified position coordinates.
This method creates a new rectangle with the same size but different x and y coordinates.
Template Parameters
T The type of the value for the new x and y coordinates.
Parameters
x The new x-coordinate for the top-left corner.
y The new y-coordinate for the top-left corner.
Returns
A new rectangle with the updated position.
References Rectangle().
withZeroPosition()
template<class ValueType> Rectangle yup::Rectangle< ValueType >::withZeroPosition () const nodiscard constexpr noexcept
Returns a new rectangle with its position set to (0, 0).
This method creates a new rectangle with the same size but positioned at the origin.
Returns
A new rectangle positioned at (0, 0).
References Rectangle().
Referenced by yup::Component::getBoundsRelativeToTopLevelComponent(), and yup::Component::getLocalBounds().
getTopLeft()
template<class ValueType> Point< ValueType > yup::Rectangle< ValueType >::getTopLeft () const nodiscard constexpr noexcept
Returns the position of the top-left corner of the rectangle.
Returns
The position of the top-left corner as a Point.
setTopLeft()
template<class ValueType> Rectangle & yup::Rectangle< ValueType >::setTopLeft (const Point< ValueType > & newPosition) constexpr noexcept
Sets the position of the rectangle's top-left corner.
Parameters
newPosition The new position for the top-left corner as a Point.
Returns
A reference to this rectangle to allow method chaining.
References Rectangle().
Referenced by withTopLeft().
withTopLeft()
template<class ValueType> Rectangle yup::Rectangle< ValueType >::withTopLeft (const Point< ValueType > & newPosition) const constexpr noexcept
Sets the position of the rectangle's top-left corner.
Parameters
newPosition The new position for the top-left corner as a Point.
Returns
A reference to this rectangle to allow method chaining.
References Rectangle(), and setTopLeft().
getTopRight()
template<class ValueType> Point< ValueType > yup::Rectangle< ValueType >::getTopRight () const nodiscard constexpr noexcept
Returns the position of the top-right corner of the rectangle.
Returns
The position of the top-right corner as a Point.
References getWidth().
setTopRight()
template<class ValueType> Rectangle & yup::Rectangle< ValueType >::setTopRight (const Point< ValueType > & newPosition) constexpr noexcept
Sets the position of the rectangle's top-left corner.
Parameters
newPosition The new position for the top-left corner as a Point.
Returns
A reference to this rectangle to allow method chaining.
References getWidth(), and Rectangle().
Referenced by withTopRight().
withTopRight()
template<class ValueType> Rectangle yup::Rectangle< ValueType >::withTopRight (const Point< ValueType > & newPosition) const constexpr noexcept
Sets the position of the rectangle's top-right corner.
Parameters
newPosition The new position for the top-right corner as a Point.
Returns
A reference to this rectangle to allow method chaining.
References Rectangle(), and setTopRight().
getBottomLeft()
template<class ValueType> Point< ValueType > yup::Rectangle< ValueType >::getBottomLeft () const nodiscard constexpr noexcept
Returns the position of the bottom-left corner of the rectangle.
Returns
The position of the bottom-left corner as a Point.
References getHeight().
setBottomLeft()
template<class ValueType> Rectangle & yup::Rectangle< ValueType >::setBottomLeft (const Point< ValueType > & newPosition) constexpr noexcept
Sets the position of the rectangle's bottom-left corner.
Parameters
newPosition The new position for the bottom-left corner as a Point.
Returns
A reference to this rectangle to allow method chaining.
References getHeight(), and Rectangle().
Referenced by withBottomLeft().
withBottomLeft()
template<class ValueType> Rectangle yup::Rectangle< ValueType >::withBottomLeft (const Point< ValueType > & newPosition) const constexpr noexcept
Sets the position of the rectangle's bottom-left corner.
Parameters
newPosition The new position for the bottom-left corner as a Point.
Returns
A reference to this rectangle to allow method chaining.
References Rectangle(), and setBottomLeft().
getBottomRight()
template<class ValueType> Point< ValueType > yup::Rectangle< ValueType >::getBottomRight () const nodiscard constexpr noexcept
Returns the position of the bottom-right corner of the rectangle.
Returns
The position of the bottom-right corner as a Point.
References getHeight(), and getWidth().
Referenced by intersects().
setBottomRight()
template<class ValueType> Rectangle & yup::Rectangle< ValueType >::setBottomRight (const Point< ValueType > & newPosition) constexpr noexcept
Sets the position of the rectangle's bottom-right corner.
Parameters
newPosition The new position for the bottom-right corner as a Point.
Returns
A reference to this rectangle to allow method chaining.
References getHeight(), and Rectangle().
Referenced by withBottomRight().
withBottomRight()
template<class ValueType> Rectangle yup::Rectangle< ValueType >::withBottomRight (const Point< ValueType > & newPosition) const constexpr noexcept
Sets the position of the rectangle's bottom-right corner.
Parameters
newPosition The new position for the bottom-right corner as a Point.
Returns
A reference to this rectangle to allow method chaining.
References Rectangle(), and setBottomRight().
getSize()
template<class ValueType> Size< ValueType > yup::Rectangle< ValueType >::getSize () const nodiscard constexpr noexcept
Returns the size of the rectangle.
Returns
The size of the rectangle as a Size object.
setSize()
template<class ValueType> Rectangle & yup::Rectangle< ValueType >::setSize (const Size< ValueType > & newSize) constexpr noexcept
Sets the size of the rectangle.
Parameters
newSize The new size for the rectangle as a Size object.
Returns
A reference to this rectangle to allow method chaining.
References Rectangle().
withSize() [1/2]
template<class ValueType> template<class T> Rectangle yup::Rectangle< ValueType >::withSize (const Size< T > & newSize) const nodiscard constexpr noexcept
Returns a new rectangle with the specified size.
This method creates a new rectangle with the same position but a different size.
Template Parameters
T The type of the value for the new size.
Parameters
newSize The new size for the rectangle as a Size object.
Returns
A new rectangle with the updated size.
References Rectangle(), and to().
Referenced by withScaledSize().
withSize() [2/2]
template<class ValueType> template<class T> Rectangle yup::Rectangle< ValueType >::withSize (T width, T height) const nodiscard constexpr noexcept
Returns a new rectangle with the specified dimensions.
This method creates a new rectangle with the same position but different width and height.
Template Parameters
T The type of the value for the new width and height.
Parameters
width The new width for the rectangle.
height The new height for the rectangle.
Returns
A new rectangle with the updated size.
References Rectangle().
withScaledSize()
template<class ValueType> template<class T> auto yup::Rectangle< ValueType >::withScaledSize (T scaleFactor) const -> std::enable_if_t<std::is_floating_point_v<T>, Rectangle> nodiscard constexpr noexcept
Returns a new rectangle with its size scaled by a factor.
This method creates a new rectangle with the same position but its width and height scaled by the specified factor.
Template Parameters
T The type of the scaling factor (must be a floating-point type).
Parameters
scaleFactor The factor by which to scale the size of the rectangle.
Returns
A new rectangle with the size scaled.
References Rectangle(), and withSize().
withZeroSize()
template<class ValueType> Rectangle yup::Rectangle< ValueType >::withZeroSize () const nodiscard constexpr noexcept
Returns a new rectangle with its size set to zero.
This method creates a new rectangle with the same position but zero width and height.
Returns
A new rectangle with zero size.
References Rectangle().
setBounds()
template<class ValueType> Rectangle & yup::Rectangle< ValueType >::setBounds (ValueType x, ValueType y, ValueType width, ValueType height) constexpr noexcept
Sets the bounds of the rectangle.
Parameters
x The new x-coordinate for the top-left corner.
y The new y-coordinate for the top-left corner.
width The new width of the rectangle.
height The new height of the rectangle.
Returns
A reference to this rectangle to allow method chaining.
References Rectangle().
Referenced by yup::Component::setBounds().
getCenterX()
template<class ValueType> ValueType yup::Rectangle< ValueType >::getCenterX () const nodiscard constexpr noexcept
Returns the center X of the rectangle.
Returns
The center X of the rectangle.
setCenterX()
template<class ValueType> Rectangle & yup::Rectangle< ValueType >::setCenterX (ValueType centerX) constexpr noexcept
Sets the center X of the rectangle.
Parameters
centerX The new center X for the rectangle.
Returns
A reference to this rectangle to allow method chaining.
References Rectangle().
Referenced by withCenterX().
getCenterY()
template<class ValueType> ValueType yup::Rectangle< ValueType >::getCenterY () const nodiscard constexpr noexcept
Returns the center Y of the rectangle.
Returns
The center Y of the rectangle.
setCenterY()
template<class ValueType> Rectangle & yup::Rectangle< ValueType >::setCenterY (ValueType centerY) constexpr noexcept
Sets the center Y of the rectangle.
Parameters
centerY The new center Y for the rectangle.
Returns
A reference to this rectangle to allow method chaining.
References Rectangle().
Referenced by withCenterY().
getCenter()
template<class ValueType> Point< ValueType > yup::Rectangle< ValueType >::getCenter () const nodiscard constexpr noexcept
Returns the center point of the rectangle.
Returns
The center of the rectangle as a Point, calculated as the midpoint between the top-left and bottom-right corners.
Referenced by yup::Path::addBubble(), and yup::paintSlider().
setCenter() [1/2]
template<class ValueType> Rectangle & yup::Rectangle< ValueType >::setCenter (ValueType centerX, ValueType centerY) constexpr noexcept
Sets the center of the rectangle to the specified coordinates.
This method adjusts the position of the rectangle so that its center matches the given coordinates.
Parameters
centerX The x-coordinate of the new center.
centerY The y-coordinate of the new center.
Returns
A reference to this rectangle to allow method chaining.
References Rectangle().
Referenced by setCenter(), withCenter(), and withCenter().
setCenter() [2/2]
template<class ValueType> Rectangle & yup::Rectangle< ValueType >::setCenter (const Point< ValueType > & center) constexpr noexcept
Sets the center of the rectangle to the specified point.
This method adjusts the position of the rectangle so that its center matches the given point.
Parameters
center The new center as a Point.
Returns
A reference to this rectangle to allow method chaining.
References Rectangle(), and setCenter().
withCenter() [1/2]
template<class ValueType> Rectangle yup::Rectangle< ValueType >::withCenter (ValueType centerX, ValueType centerY) nodiscard constexpr noexcept
Returns a new rectangle with its center set to the specified coordinates.
This method creates a new rectangle with the same size but its position adjusted so that its center matches the given coordinates.
Parameters
centerX The x-coordinate of the new center.
centerY The y-coordinate of the new center.
Returns
A new rectangle with the updated center.
References Rectangle(), and setCenter().
withCenter() [2/2]
template<class ValueType> Rectangle yup::Rectangle< ValueType >::withCenter (const Point< ValueType > & center) nodiscard constexpr noexcept
Returns a new rectangle with its center set to the specified point.
This method creates a new rectangle with the same size but its position adjusted so that its center matches the given point.
Parameters
center The new center as a Point.
Returns
A new rectangle with the updated center.
References Rectangle(), and setCenter().
withCenterX()
template<class ValueType> Rectangle yup::Rectangle< ValueType >::withCenterX (ValueType centerX) nodiscard constexpr noexcept
Returns a new rectangle with its center X set to the specified value.
This method creates a new rectangle with the same size but its position adjusted so that its center X matches the given value.
Parameters
centerX The new center X for the rectangle.
Returns
A new rectangle with the updated center X.
References Rectangle(), and setCenterX().
withCenterY()
template<class ValueType> Rectangle yup::Rectangle< ValueType >::withCenterY (ValueType centerY) nodiscard constexpr noexcept
Returns a new rectangle with its center Y set to the specified value.
This method creates a new rectangle with the same size but its position adjusted so that its center Y matches the given value.
Parameters
centerY The new center Y for the rectangle.
Returns
A new rectangle with the updated center Y.
References Rectangle(), and setCenterY().
isEmpty()
template<class ValueType> bool yup::Rectangle< ValueType >::isEmpty () const nodiscard constexpr noexcept
Checks if the rectangle's size is zero.
Returns
True if both the width and height are zero, otherwise false.
Referenced by yup::Path::addBubble(), yup::Component::repaint(), and yup::Path::scaleToFit().
isPoint()
template<class ValueType> bool yup::Rectangle< ValueType >::isPoint () const nodiscard constexpr noexcept
Checks if the rectangle's size is zero (i.e., it is a point).
Returns
True if both the width and height are zero, otherwise false.
isLine()
template<class ValueType> bool yup::Rectangle< ValueType >::isLine () const nodiscard constexpr noexcept
Checks if the rectangle is a line (either horizontal or vertical).
Returns
True if the rectangle is strictly horizontal or vertical (i.e., width or height is zero but not both), otherwise false.
References isHorizontalLine(), and isVerticalLine().
isVerticalLine()
template<class ValueType> bool yup::Rectangle< ValueType >::isVerticalLine () const nodiscard constexpr noexcept
Checks if the rectangle is a vertical line.
Returns
True if the height is non-zero and the width is zero, otherwise false.
Referenced by isLine().
isHorizontalLine()
template<class ValueType> bool yup::Rectangle< ValueType >::isHorizontalLine () const nodiscard constexpr noexcept
Checks if the rectangle is a horizontal line.
Returns
True if the width is non-zero and the height is zero, otherwise false.
Referenced by isLine().
leftSide()
template<class ValueType> Line< ValueType > yup::Rectangle< ValueType >::leftSide () const nodiscard constexpr noexcept
Returns the line representing the left side of the rectangle.
Returns
A Line object representing the left vertical edge of the rectangle.
References getHeight().
topSide()
template<class ValueType> Line< ValueType > yup::Rectangle< ValueType >::topSide () const nodiscard constexpr noexcept
Returns the line representing the top side of the rectangle.
Returns
A Line object representing the top horizontal edge of the rectangle.
References getWidth().
rightSide()
template<class ValueType> Line< ValueType > yup::Rectangle< ValueType >::rightSide () const nodiscard constexpr noexcept
Returns the line representing the right side of the rectangle.
Returns
A Line object representing the right vertical edge of the rectangle.
References getHeight(), and getWidth().
bottomSide()
template<class ValueType> Line< ValueType > yup::Rectangle< ValueType >::bottomSide () const nodiscard constexpr noexcept
Returns the line representing the bottom side of the rectangle.
Returns
A Line object representing the bottom horizontal edge of the rectangle.
References getHeight(), and getWidth().
diagonalTopToBottom()
template<class ValueType> Line< ValueType > yup::Rectangle< ValueType >::diagonalTopToBottom () const nodiscard constexpr noexcept
Returns the diagonal line from the top-left to the bottom-right corner of the rectangle.
Returns
A Line object representing the diagonal crossing the rectangle from top-left to bottom-right.
References getHeight(), and getWidth().
diagonalBottomToTop()
template<class ValueType> Line< ValueType > yup::Rectangle< ValueType >::diagonalBottomToTop () const nodiscard constexpr noexcept
Returns the diagonal line from the bottom-left to the top-right corner of the rectangle.
Returns
A Line object representing the diagonal crossing the rectangle from bottom-left to top-right.
References getHeight(), and getWidth().
translate() [1/2]
template<class ValueType> Rectangle & yup::Rectangle< ValueType >::translate (ValueType deltaX, ValueType deltaY) constexpr noexcept
Translates the rectangle by the specified x and y offsets.
This method adjusts the position of the rectangle by adding the specified deltas to the x and y coordinates.
Parameters
deltaX The amount to add to the x-coordinate.
deltaY The amount to add to the y-coordinate.
Returns
A reference to this rectangle to allow method chaining.
References Rectangle().
translate() [2/2]
template<class ValueType> Rectangle & yup::Rectangle< ValueType >::translate (const Point< ValueType > & delta) constexpr noexcept
Translates the rectangle by the specified point.
This method adjusts the position of the rectangle by adding the point's x and y values to the rectangle's position.
Parameters
delta The point containing the amounts to add to the rectangle's position.
Returns
A reference to this rectangle to allow method chaining.
References Rectangle().
translated() [1/2]
template<class ValueType> Rectangle< ValueType > yup::Rectangle< ValueType >::translated (ValueType deltaX, ValueType deltaY) const nodiscard constexpr noexcept
Returns a new rectangle translated by the specified x and y offsets.
This method creates a new rectangle with the same size but its position adjusted by the specified deltas.
Parameters
deltaX The amount to add to the x-coordinate.
deltaY The amount to add to the y-coordinate.
Returns
A new rectangle with the updated position.
References Rectangle().
Referenced by yup::Component::repaint().
translated() [2/2]
template<class ValueType> Rectangle< ValueType > yup::Rectangle< ValueType >::translated (const Point< ValueType > & delta) const nodiscard constexpr noexcept
Returns a new rectangle translated by the specified point.
This method creates a new rectangle with the same size but its position adjusted by the point's x and y values.
Parameters
delta The point containing the amounts to add to the rectangle's position.
Returns
A new rectangle with the updated position.
References Rectangle().
scale() [1/2]
template<class ValueType> Rectangle & yup::Rectangle< ValueType >::scale (float factor) constexpr noexcept
Scales the size of the rectangle uniformly by a given factor.
This method multiplies both the x, y, width and height of the rectangle by the specified factor.
Parameters
factor The scaling factor to apply to both the x, y, width and height of the rectangle.
Returns
A reference to this rectangle to allow method chaining.
References Rectangle().
scale() [2/2]
template<class ValueType> Rectangle & yup::Rectangle< ValueType >::scale (float factorX, float factorY) constexpr noexcept
Scales the size of the rectangle by the specified x and y factors.
This method adjusts the size of the rectangle by multiplying its x, width and y, height by the given factors.
Parameters
factorX The factor to multiply the x and width by.
factorY The factor to multiply the y and height by.
Returns
A reference to this rectangle to allow method chaining.
References Rectangle().
scaled() [1/2]
template<class ValueType> Rectangle yup::Rectangle< ValueType >::scaled (float factor) const nodiscard constexpr noexcept
Returns a new rectangle with its size scaled uniformly by the specified factor.
This method creates a new rectangle with the same position but with both the x, width and y, height scaled by the given factor.
Parameters
factor The scaling factor to apply to both the x, width and y, height of the rectangle.
Returns
A new rectangle with the scaled size.
References Rectangle().
scaled() [2/2]
template<class ValueType> Rectangle yup::Rectangle< ValueType >::scaled (float factorX, float factorY) const nodiscard constexpr noexcept
Returns a new rectangle with its size scaled by the specified x and y factors.
This method creates a new rectangle with the same position but its x, width and y, height adjusted by the given factors.
Parameters
factorX The factor to multiply the x and width by.
factorY The factor to multiply the y and height by.
Returns
A new rectangle with the scaled size.
References Rectangle().
removeFromTop()
template<class ValueType> Rectangle yup::Rectangle< ValueType >::removeFromTop (ValueType delta) constexpr noexcept
Removes a specified height from the top of the rectangle, adjusting its size and position.
This method reduces the height of the rectangle from the top by the specified amount, moving the top edge downwards.
Parameters
delta The height to remove from the top of the rectangle.
Returns
A new rectangle representing the portion removed from the top.
References yup::jlimit(), and Rectangle().
removeFromLeft()
template<class ValueType> Rectangle yup::Rectangle< ValueType >::removeFromLeft (ValueType delta) constexpr noexcept
Removes a specified width from the left side of the rectangle, adjusting its size and position.
This method reduces the width of the rectangle from the left by the specified amount, moving the left edge to the right.
Parameters
delta The width to remove from the left of the rectangle.
Returns
A new rectangle representing the portion removed from the left.
References yup::jlimit(), and Rectangle().
removeFromBottom()
template<class ValueType> Rectangle yup::Rectangle< ValueType >::removeFromBottom (ValueType delta) constexpr noexcept
Removes a specified height from the bottom of the rectangle, adjusting its size and position.
This method reduces the height of the rectangle from the bottom by the specified amount, moving the bottom edge upwards.
Parameters
delta The height to remove from the bottom of the rectangle.
Returns
A new rectangle representing the portion removed from the bottom.
References yup::jlimit(), and Rectangle().
removeFromRight()
template<class ValueType> Rectangle yup::Rectangle< ValueType >::removeFromRight (ValueType delta) constexpr noexcept
Removes a specified width from the right side of the rectangle, adjusting its size and position.
This method reduces the width of the rectangle from the right by the specified amount, moving the right edge to the left.
Parameters
delta The width to remove from the right of the rectangle.
Returns
A new rectangle representing the portion removed from the right.
References yup::jlimit(), and Rectangle().
reduce() [1/3]
template<class ValueType> Rectangle & yup::Rectangle< ValueType >::reduce (ValueType delta) constexpr noexcept
Reduces the size of the rectangle by a uniform amount on all sides.
This method shrinks the rectangle's width and height by the specified delta, equally reducing the size from all edges.
Parameters
delta The amount to reduce each side by.
Returns
A reference to this rectangle to allow method chaining.
References yup::jmax(), and Rectangle().
Referenced by reduced(), reduced(), reduced(), reducedBottom(), reducedLeft(), reducedRight(), and reducedTop().
reduce() [2/3]
template<class ValueType> Rectangle & yup::Rectangle< ValueType >::reduce (ValueType deltaX, ValueType deltaY) constexpr noexcept
Reduces the width and height of the rectangle by different amounts on all sides.
This method shrinks the rectangle's width by deltaX and height by deltaY, reducing the size from all edges by these respective amounts.
Parameters
deltaX The amount to reduce the width by on each side.
deltaY The amount to reduce the height by on each side.
Returns
A reference to this rectangle to allow method chaining.
References yup::jmax(), and Rectangle().
reduce() [3/3]
template<class ValueType> Rectangle & yup::Rectangle< ValueType >::reduce (ValueType left, ValueType top, ValueType right, ValueType bottom) constexpr noexcept
Reduces the size of the rectangle by different amounts on all sides.
This method shrinks the rectangle's width by left and right, and height by top and bottom, reducing the size from all edges by these respective amounts.
Parameters
left The amount to reduce the width by on the left side.
top The amount to reduce the height by on the top side.
right The amount to reduce the width by on the right side.
bottom The amount to reduce the height by on the bottom side.
Returns
A reference to this rectangle to allow method chaining.
References yup::jmax(), and Rectangle().
reduced() [1/3]
template<class ValueType> Rectangle yup::Rectangle< ValueType >::reduced (ValueType delta) const nodiscard constexpr noexcept
Returns a new rectangle with its size reduced by a uniform amount on all sides.
This method creates a new rectangle with the same position but its width and height shrunk by the specified delta, equally from all edges.
Parameters
delta The amount to reduce each side by.
Returns
A new rectangle with the reduced size.
References Rectangle(), and reduce().
Referenced by yup::TextButton::getTextBounds(), yup::TextEditor::getTextBounds(), and yup::paintSlider().
reduced() [2/3]
template<class ValueType> Rectangle yup::Rectangle< ValueType >::reduced (ValueType deltaX, ValueType deltaY) const nodiscard constexpr noexcept
Returns a new rectangle with its width and height reduced by different amounts on all sides.
This method creates a new rectangle with the same position but its width and height shrunk by the specified deltaX and deltaY, respectively.
Parameters
deltaX The amount to reduce the width by on each side.
deltaY The amount to reduce the height by on each side.
Returns
A new rectangle with the reduced size.
References Rectangle(), and reduce().
reduced() [3/3]
template<class ValueType> Rectangle yup::Rectangle< ValueType >::reduced (ValueType left, ValueType top, ValueType right, ValueType bottom) const nodiscard constexpr noexcept
Returns a new rectangle with its size reduced by different amounts on all sides.
This method creates a new rectangle with the same position but its width and height shrunk by the specified left, top, right, and bottom amounts.
Parameters
left The amount to reduce the width by on the left side.
top The amount to reduce the height by on the top side.
right The amount to reduce the width by on the right side.
bottom The amount to reduce the height by on the bottom side.
Returns
A new rectangle with the reduced size.
References Rectangle(), and reduce().
reducedLeft()
template<class ValueType> Rectangle yup::Rectangle< ValueType >::reducedLeft (ValueType delta) const nodiscard constexpr noexcept
Returns a new rectangle with its width reduced by a specified amount on the left side.
This method creates a new rectangle with the same position but its width shrunk by the specified delta, reducing the size from the left edge.
Parameters
delta The amount to reduce the width by on the left side.
Returns
A new rectangle with the reduced size.
References Rectangle(), and reduce().
reducedTop()
template<class ValueType> Rectangle yup::Rectangle< ValueType >::reducedTop (ValueType delta) const nodiscard constexpr noexcept
Returns a new rectangle with its height reduced by a specified amount on the top side.
This method creates a new rectangle with the same position but its height shrunk by the specified delta, reducing the size from the top edge.
Parameters
delta The amount to reduce the height by on the top side.
Returns
A new rectangle with the reduced size.
References Rectangle(), and reduce().
reducedRight()
template<class ValueType> Rectangle yup::Rectangle< ValueType >::reducedRight (ValueType delta) const nodiscard constexpr noexcept
Returns a new rectangle with its width reduced by a specified amount on the right side.
This method creates a new rectangle with the same position but its width shrunk by the specified delta, reducing the size from the right edge.
Parameters
delta The amount to reduce the width by on the right side.
Returns
A new rectangle with the reduced size.
References Rectangle(), and reduce().
reducedBottom()
template<class ValueType> Rectangle yup::Rectangle< ValueType >::reducedBottom (ValueType delta) const nodiscard constexpr noexcept
Returns a new rectangle with its height reduced by a specified amount on the bottom side.
This method creates a new rectangle with the same position but its height shrunk by the specified delta, reducing the size from the bottom edge.
Parameters
delta The amount to reduce the height by on the bottom side.
Returns
A new rectangle with the reduced size.
References Rectangle(), and reduce().
enlarge() [1/3]
template<class ValueType> Rectangle & yup::Rectangle< ValueType >::enlarge (ValueType delta) constexpr noexcept
Enlarges the size of the rectangle by a uniform amount on all sides.
This method expand the rectangle's width and height by the specified delta, equally increasing the size on all edges.
Parameters
delta The amount to enlarge each side by.
Returns
A reference to this rectangle to allow method chaining.
References yup::jmax(), and Rectangle().
Referenced by enlarged(), enlarged(), enlargedBottom(), enlargedLeft(), enlargedRight(), and enlargedTop().
enlarge() [2/3]
template<class ValueType> Rectangle & yup::Rectangle< ValueType >::enlarge (ValueType deltaX, ValueType deltaY) constexpr noexcept
Enlarges the width and height of the rectangle by different amounts on all sides.
This method expand the rectangle's width by deltaX and height by deltaY, increasing the size on all edges by these respective amounts.
Parameters
deltaX The amount to enlarge the width by on each side.
deltaY The amount to enlarge the height by on each side.
Returns
A reference to this rectangle to allow method chaining.
References yup::jmax(), and Rectangle().
enlarge() [3/3]
template<class ValueType> Rectangle & yup::Rectangle< ValueType >::enlarge (ValueType left, ValueType top, ValueType right, ValueType bottom) constexpr noexcept
Enlarges the size of the rectangle by different amounts on all sides.
This method expands the rectangle's width by left and right, and height by top and bottom, increasing the size on all edges by these respective amounts.
Parameters
left The amount to enlarge the width by on the left side.
top The amount to enlarge the height by on the top side.
right The amount to enlarge the width by on the right side.
bottom The amount to enlarge the height by on the bottom side.
Returns
A reference to this rectangle to allow method chaining.
References yup::jmax(), and Rectangle().
enlarged() [1/2]
template<class ValueType> Rectangle yup::Rectangle< ValueType >::enlarged (ValueType delta) const nodiscard constexpr noexcept
Returns a new rectangle with its size reduced by a uniform amount on all sides.
This method creates a new rectangle with the same position but its width and height shrunk by the specified delta, equally from all edges.
Parameters
delta The amount to reduce each side by.
Returns
A new rectangle with the reduced size.
References enlarge(), and Rectangle().
enlarged() [2/2]
template<class ValueType> Rectangle yup::Rectangle< ValueType >::enlarged (ValueType deltaX, ValueType deltaY) const nodiscard constexpr noexcept
Returns a new rectangle with its width and height reduced by different amounts on all sides.
This method creates a new rectangle with the same position but its width and height shrunk by the specified deltaX and deltaY, respectively.
Parameters
deltaX The amount to reduce the width by on each side.
deltaY The amount to reduce the height by on each side.
Returns
A new rectangle with the reduced size.
References enlarge(), and Rectangle().
enlargedLeft()
template<class ValueType> Rectangle yup::Rectangle< ValueType >::enlargedLeft (ValueType delta) const nodiscard constexpr noexcept
Returns a new rectangle with its width enlarged by a specified amount on the left side.
This method creates a new rectangle with the same position but its width enlarged by the specified delta, increasing the size from the left edge.
Parameters
delta The amount to enlarge the width by on the left side.
Returns
A new rectangle with the enlarged size.
References enlarge(), and Rectangle().
enlargedTop()
template<class ValueType> Rectangle yup::Rectangle< ValueType >::enlargedTop (ValueType delta) const nodiscard constexpr noexcept
Returns a new rectangle with its height enlarged by a specified amount on the top side.
This method creates a new rectangle with the same position but its height enlarged by the specified delta, increasing the size from the top edge.
Parameters
delta The amount to enlarge the height by on the top side.
Returns
A new rectangle with the enlarged size.
References enlarge(), and Rectangle().
enlargedRight()
template<class ValueType> Rectangle yup::Rectangle< ValueType >::enlargedRight (ValueType delta) const nodiscard constexpr noexcept
Returns a new rectangle with its width enlarged by a specified amount on the right side.
This method creates a new rectangle with the same position but its width enlarged by the specified delta, increasing the size from the right edge.
Parameters
delta The amount to enlarge the width by on the right side.
Returns
A new rectangle with the enlarged size.
References enlarge(), and Rectangle().
enlargedBottom()
template<class ValueType> Rectangle yup::Rectangle< ValueType >::enlargedBottom (ValueType delta) const nodiscard constexpr noexcept
Returns a new rectangle with its height enlarged by a specified amount on the bottom side.
This method creates a new rectangle with the same position but its height enlarged by the specified delta, increasing the size from the bottom edge.
Parameters
delta The amount to enlarge the height by on the bottom side.
Returns
A new rectangle with the enlarged size.
References enlarge(), and Rectangle().
contains() [1/2]
template<class ValueType> bool yup::Rectangle< ValueType >::contains (ValueType x, ValueType y) const nodiscard constexpr noexcept
Checks if the specified point lies within the bounds of the rectangle.
Parameters
x The x-coordinate of the point to check.
y The y-coordinate of the point to check.
Returns
True if the point is within the rectangle, otherwise false.
Referenced by yup::Path::addBubble(), and contains().
contains() [2/2]
template<class ValueType> bool yup::Rectangle< ValueType >::contains (const Point< ValueType > & p) const nodiscard constexpr noexcept
Checks if the specified point lies within the bounds of the rectangle.
Parameters
p The point to check.
Returns
True if the point is within the rectangle, otherwise false.
References contains().
area()
template<class ValueType> ValueType yup::Rectangle< ValueType >::area () const nodiscard constexpr noexcept
Calculates the area of the rectangle.
Returns
The area of the rectangle, computed as width multiplied by height.
intersects()
template<class ValueType> bool yup::Rectangle< ValueType >::intersects (const Rectangle< ValueType > & other) const nodiscard constexpr noexcept
Checks if this rectangle intersects with another rectangle.
This method checks for overlap between this rectangle and another, returning true if there is any overlap.
Parameters
other The other rectangle to check against.
Returns
True if the rectangles intersect, otherwise false.
References getBottomRight(), getX(), getY(), and Rectangle().
intersection()
template<class ValueType> Rectangle yup::Rectangle< ValueType >::intersection (const Rectangle< ValueType > & other) const nodiscard constexpr noexcept
Returns the intersection of this rectangle with another rectangle.
This method calculates and returns the area where this rectangle and another rectangle overlap.
Parameters
other The other rectangle to intersect with.
Returns
A Rectangle representing the intersection of the two rectangles, or an empty rectangle if they do not intersect.
References getHeight(), getWidth(), getX(), getY(), yup::jmax(), yup::jmin(), and Rectangle().
largestFittingSquare()
template<class ValueType> Rectangle yup::Rectangle< ValueType >::largestFittingSquare () const nodiscard constexpr noexcept
Returns the largest square that fits within the rectangle.
This method calculates and returns the largest square that can be inscribed within the rectangle.
Returns
A Rectangle representing the largest square that fits inside this rectangle.
References getHeight(), getWidth(), and Rectangle().
unionWith()
template<class ValueType> Rectangle yup::Rectangle< ValueType >::unionWith (const Rectangle< ValueType > & other) const nodiscard constexpr noexcept
Returns the smallest containing rectangle between this and another rectangle.
Returns
A Rectangle representing the smallest containing rectangle of two rectangles.
References getHeight(), getWidth(), getX(), getY(), yup::jmax(), yup::jmin(), and Rectangle().
centeredRectangleWithSize()
template<class ValueType> Rectangle yup::Rectangle< ValueType >::centeredRectangleWithSize (const Size< ValueType > & sizeOfRectangleToCenter) const nodiscard constexpr noexcept
Aligns a Size to this rectangle.
Returns
A Rectangle representing the center aligned rectangle with specificed size..
References getHeight(), getWidth(), getX(), getY(), and Rectangle().
transform()
template<class ValueType> Rectangle & yup::Rectangle< ValueType >::transform (const AffineTransform & t) noexcept
Transforms the rectangle by an affine transformation.
This method applies an affine transformation to the rectangle, modifying its position and size.
Parameters
t The affine transformation to apply.
Returns
A reference to this rectangle to allow method chaining.
References getHeight(), getWidth(), getX(), getY(), yup::jmax(), yup::jmin(), and Rectangle().
Referenced by yup::Graphics::setTransform(), and transformed().
transformed()
template<class ValueType> Rectangle yup::Rectangle< ValueType >::transformed (const AffineTransform & t) const nodiscard noexcept
Returns a new rectangle transformed by an affine transformation.
This method creates a new rectangle with the same position and size, but with its position and size transformed by the given affine transformation.
Parameters
t The affine transformation to apply.
Returns
A new rectangle with the transformed position and size.
References Rectangle(), and transform().
Referenced by yup::Path::getBoundsTransformed().
to()
template<class ValueType> template<class T> Rectangle< T > yup::Rectangle< ValueType >::to () const nodiscard constexpr noexcept
Converts the rectangle to a different type.
This method template converts the rectangle's position and size to another type, and returns a new rectangle of that type.
Template Parameters
T The type to convert the rectangle to.
Returns
A new rectangle of type T, with the position and size converted.
References Rectangle(), and to().
Referenced by Rectangle(), Rectangle(), yup::Component::setBounds(), to(), withPosition(), and withSize().
roundToInt()
template<class ValueType> template<class T = ValueType> auto yup::Rectangle< ValueType >::roundToInt () const -> std::enable_if_t<std::is_floating_point_v<T>, Rectangle<int>> nodiscard constexpr noexcept
Rounds the rectangle's position and size to integers.
This method creates a new rectangle with the same position and size, but with its position and size rounded to integers.
Returns
A new rectangle with the rounded position and size.
References Rectangle().
operator*()
template<class ValueType> template<class T> auto yup::Rectangle< ValueType >::operator* (T scaleFactor) const -> std::enable_if_t<std::is_floating_point_v<T>, Rectangle> constexpr noexcept
Multiplies the size and position of the rectangle by a scale factor.
This operator returns a new rectangle with both the position and size scaled by the given factor.
Template Parameters
T The type of the scaling factor (must be a floating-point type).
Parameters
scaleFactor The factor by which to scale the rectangle.
Returns
A new rectangle scaled by the factor.
References Rectangle().
operator*=()
template<class ValueType> template<class T> auto yup::Rectangle< ValueType >::operator*= (T scaleFactor) -> std::enable_if_t<std::is_floating_point_v<T>, Rectangle&> constexpr noexcept
Scales the size and position of the rectangle in place by a scale factor.
This operator modifies this rectangle, scaling both the position and size by the given factor.
Template Parameters
T The type of the scaling factor (must be a floating-point type).
Parameters
scaleFactor The factor by which to scale the rectangle.
Returns
A reference to this rectangle to allow method chaining.
References Rectangle().
operator/()
template<class ValueType> template<class T> auto yup::Rectangle< ValueType >::operator/ (T scaleFactor) const -> std::enable_if_t<std::is_floating_point_v<T>, Rectangle> constexpr noexcept
Divides the size and position of the rectangle by a scale factor.
This operator returns a new rectangle with both the position and size divided by the given factor.
Template Parameters
T The type of the scaling factor (must be a floating-point type).
Parameters
scaleFactor The factor by which to divide the rectangle.
Returns
A new rectangle divided by the factor.
References Rectangle().
operator/=()
template<class ValueType> template<class T> auto yup::Rectangle< ValueType >::operator/= (T scaleFactor) -> std::enable_if_t<std::is_floating_point_v<T>, Rectangle&> constexpr noexcept
Divides the size and position of the rectangle in place by a scale factor.
This operator modifies this rectangle, dividing both the position and size by the given factor.
Template Parameters
T The type of the scaling factor (must be a floating-point type).
Parameters
scaleFactor The factor by which to divide the rectangle.
Returns
A reference to this rectangle to allow method chaining.
References Rectangle().
approximatelyEqualTo()
template<class ValueType> bool yup::Rectangle< ValueType >::approximatelyEqualTo (const Rectangle< ValueType > & other) const constexpr noexcept
Returns true if the two rectangles are approximately equal.
This method checks if the position and size of this rectangle are approximately equal to those of another rectangle.
Parameters
other The other rectangle to compare against.
Returns
True if the rectangles are approximately equal, otherwise false.
References Rectangle().
operator==()
template<class ValueType> bool yup::Rectangle< ValueType >::operator== (const Rectangle< ValueType > & other) const constexpr noexcept
Checks for equality between this rectangle and another rectangle.
This operator returns true if both the position and size of this rectangle are equal to those of the other rectangle.
Parameters
other The other rectangle to compare against.
Returns
True if the rectangles are equal, otherwise false.
References Rectangle().
operator!=()
template<class ValueType> bool yup::Rectangle< ValueType >::operator!= (const Rectangle< ValueType > & other) const constexpr noexcept
Checks for inequality between this rectangle and another rectangle.
This operator returns true if either the position or size of this rectangle differs from those of the other rectangle.
Parameters
other The other rectangle to compare against.
Returns
True if the rectangles are not equal, otherwise false.
References Rectangle().
toAABB()
template<class ValueType> rive::AABB yup::Rectangle< ValueType >::toAABB () const
References getBottom(), getLeft(), getRight(), and getTop().