YUP: yup::KeyModifiers Class Reference
yup::KeyModifiers Class Reference
Represents modifier keys (like Shift, Ctrl, etc.) pressed during a keyboard event.
Public Member Functions
constexpr KeyModifiers () noexcept=default
Default constructor, initializes with no modifiers active.
constexpr KeyModifiers (int newModifiers) noexcept
Constructs KeyModifiers with a specific set of modifiers.
constexpr KeyModifiers (const KeyModifiers &other) noexcept=default
constexpr KeyModifiers (KeyModifiers &&other) noexcept=default
constexpr KeyModifiers & operator= (const KeyModifiers &other) noexcept=default
constexpr KeyModifiers & operator= (KeyModifiers &&other) noexcept=default
constexpr bool isShiftDown () const noexcept
Checks if the Shift key is down.
constexpr bool isControlDown () const noexcept
Checks if the Control key is down.
constexpr bool isCommandDown () const noexcept
Checks if the Command key is down.
constexpr bool isAltDown () const noexcept
Checks if the Alt key is down.
constexpr bool isSuperDown () const noexcept
Checks if the Super (Windows or Command) key is down.
constexpr bool isCapsLockDown () const noexcept
Checks if the Caps Lock is active.
constexpr bool isNumLockDown () const noexcept
Checks if the Num Lock is active.
constexpr int getFlags () const noexcept
Gets the current flags representing the active modifiers.
constexpr KeyModifiers withFlags (int modifiersToAdd) const noexcept
Returns a new KeyModifiers object with additional flags set.
constexpr KeyModifiers withoutFlags (int modifiersToRemove) const noexcept
Returns a new KeyModifiers object with specific flags removed.
constexpr bool testFlags (int modifiersToTest) const noexcept
Tests if specific modifier flags are active.
constexpr bool operator== (const KeyModifiers &other) const noexcept
Compares this KeyModifiers object to another for equality.
constexpr bool operator!= (const KeyModifiers &other) const noexcept
Compares this KeyModifiers object to another for inequality.
Static Public Attributes
static constexpr int shiftMask = 0x0001
static constexpr int controlMask = 0x0002
static constexpr int commandMask = 0x0004
static constexpr int altMask = 0x0008
static constexpr int superMask = 0x0010
static constexpr int capsLockMask = 0x0020
static constexpr int numLockMask = 0x0040
Detailed Description
Represents modifier keys (like Shift, Ctrl, etc.) pressed during a keyboard event.
This class encapsulates the state of modifier keys during keyboard interactions, providing methods to check if specific modifiers are active and manipulate the modifier state.
Constructor & Destructor Documentation
KeyModifiers() [1/4]
yup::KeyModifiers::KeyModifiers () constexpr default noexcept
Default constructor, initializes with no modifiers active.
Referenced by KeyModifiers(), KeyModifiers(), KeyModifiers(), operator!=(), operator=(), operator=(), operator==(), withFlags(), and withoutFlags().
KeyModifiers() [2/4]
yup::KeyModifiers::KeyModifiers (int newModifiers) constexpr noexcept
Constructs KeyModifiers with a specific set of modifiers.
Parameters
newModifiers An integer bitmask representing the initial state of the modifiers.
References KeyModifiers().
KeyModifiers() [3/4]
yup::KeyModifiers::KeyModifiers (const KeyModifiers & other) constexpr default noexcept
References KeyModifiers().
KeyModifiers() [4/4]
yup::KeyModifiers::KeyModifiers (KeyModifiers && other) constexpr default noexcept
References KeyModifiers().
Member Function Documentation
operator=() [1/2]
KeyModifiers & yup::KeyModifiers::operator= (const KeyModifiers & other) constexpr default noexcept
References KeyModifiers().
operator=() [2/2]
KeyModifiers & yup::KeyModifiers::operator= (KeyModifiers && other) constexpr default noexcept
References KeyModifiers().
isShiftDown()
bool yup::KeyModifiers::isShiftDown () const constexpr noexcept
Checks if the Shift key is down.
Returns
True if Shift is active, false otherwise.
References shiftMask.
Referenced by yup::TextEditor::keyDown(), and yup::TextEditor::mouseDown().
isControlDown()
bool yup::KeyModifiers::isControlDown () const constexpr noexcept
Checks if the Control key is down.
Returns
True if Control is active, false otherwise.
References controlMask.
Referenced by yup::TextEditor::keyDown().
isCommandDown()
bool yup::KeyModifiers::isCommandDown () const constexpr noexcept
Checks if the Command key is down.
Returns
True if Command is active, false otherwise.
References commandMask.
Referenced by yup::TextEditor::keyDown().
isAltDown()
bool yup::KeyModifiers::isAltDown () const constexpr noexcept
Checks if the Alt key is down.
Returns
True if Alt is active, false otherwise.
References altMask.
isSuperDown()
bool yup::KeyModifiers::isSuperDown () const constexpr noexcept
Checks if the Super (Windows or Command) key is down.
Returns
True if Super is active, false otherwise.
References superMask.
isCapsLockDown()
bool yup::KeyModifiers::isCapsLockDown () const constexpr noexcept
Checks if the Caps Lock is active.
Returns
True if Caps Lock is active, false otherwise.
References capsLockMask.
isNumLockDown()
bool yup::KeyModifiers::isNumLockDown () const constexpr noexcept
Checks if the Num Lock is active.
Returns
True if Num Lock is active, false otherwise.
References numLockMask.
getFlags()
int yup::KeyModifiers::getFlags () const constexpr noexcept
Gets the current flags representing the active modifiers.
Returns
The bitmask of active modifiers.
withFlags()
KeyModifiers yup::KeyModifiers::withFlags (int modifiersToAdd) const constexpr noexcept
Returns a new KeyModifiers object with additional flags set.
Parameters
modifiersToAdd The modifier flags to add.
Returns
A new KeyModifiers object with the added flags.
References KeyModifiers().
withoutFlags()
KeyModifiers yup::KeyModifiers::withoutFlags (int modifiersToRemove) const constexpr noexcept
Returns a new KeyModifiers object with specific flags removed.
Parameters
modifiersToRemove The modifier flags to remove.
Returns
A new KeyModifiers object with the removed flags.
References KeyModifiers().
testFlags()
bool yup::KeyModifiers::testFlags (int modifiersToTest) const constexpr noexcept
Tests if specific modifier flags are active.
Parameters
modifiersToTest The modifier flags to test.
Returns
True if all specified flags are active, false otherwise.
operator==()
bool yup::KeyModifiers::operator== (const KeyModifiers & other) const constexpr noexcept
Compares this KeyModifiers object to another for equality.
Parameters
other The other KeyModifiers object to compare against.
Returns
True if the modifiers are the same, false otherwise.
References KeyModifiers().
operator!=()
bool yup::KeyModifiers::operator!= (const KeyModifiers & other) const constexpr noexcept
Compares this KeyModifiers object to another for inequality.
Parameters
other The other KeyModifiers object to compare against.
Returns
True if the modifiers are not the same, false otherwise.
References KeyModifiers().
Member Data Documentation
shiftMask
int yup::KeyModifiers::shiftMask = 0x0001 static constexpr
Referenced by isShiftDown().
controlMask
int yup::KeyModifiers::controlMask = 0x0002 static constexpr
Referenced by isControlDown().
commandMask
int yup::KeyModifiers::commandMask = 0x0004 static constexpr
Referenced by isCommandDown().
altMask
int yup::KeyModifiers::altMask = 0x0008 static constexpr
Referenced by isAltDown().
superMask
int yup::KeyModifiers::superMask = 0x0010 static constexpr
Referenced by isSuperDown().
capsLockMask
int yup::KeyModifiers::capsLockMask = 0x0020 static constexpr
Referenced by isCapsLockDown().
numLockMask
int yup::KeyModifiers::numLockMask = 0x0040 static constexpr
Referenced by isNumLockDown().