YUP: yup::KeyPress Class Reference
yup::KeyPress Class Reference
Represents a single key press, encapsulating information about the key and any associated modifiers.
Public Member Functions
constexpr KeyPress () noexcept=default
Default constructor, initializes a key press with no key or modifiers.
constexpr KeyPress (int newKey) noexcept
Constructs a KeyPress with a specified key code.
constexpr KeyPress (int newKey, KeyModifiers newModifiers) noexcept
Constructs a KeyPress with a specified key code and modifiers.
constexpr KeyPress (int newKey, KeyModifiers newModifiers, char32_t newScancode) noexcept
Constructs a KeyPress with a specified key code, modifiers, and a scancode representing the text character.
constexpr KeyPress (const KeyPress &other) noexcept=default
constexpr KeyPress (KeyPress &&other) noexcept=default
constexpr KeyPress & operator= (const KeyPress &other) noexcept=default
constexpr KeyPress & operator= (KeyPress &&other) noexcept=default
constexpr int getKey () const noexcept
Gets the key code of the key press.
constexpr KeyModifiers getModifiers () const noexcept
Gets the modifiers associated with the key press.
constexpr char32_t getTextCharacter () const noexcept
Gets the Unicode text character produced by the key press, if any.
constexpr bool operator== (const KeyPress &other) const noexcept
Compares two KeyPress objects for equality.
constexpr bool operator!= (const KeyPress &other) const noexcept
Compares two KeyPress objects for inequality.
Static Public Attributes
static constexpr int spaceKey = 32
Aliases for commonly used keys.
static constexpr int apostropheKey = 39
static constexpr int commaKey = 44
static constexpr int minusKey = 45
static constexpr int periodKey = 46
static constexpr int slashKey = 47
static constexpr int number0Key = 48
static constexpr int number1Key = 49
static constexpr int number2Key = 50
static constexpr int number3Key = 51
static constexpr int number4Key = 52
static constexpr int number5Key = 53
static constexpr int number6Key = 54
static constexpr int number7Key = 55
static constexpr int number8Key = 56
static constexpr int number9Key = 57
static constexpr int semicolonKey = 59
static constexpr int equalKey = 61
static constexpr int textAKey = 65
static constexpr int textBKey = 66
static constexpr int textCKey = 67
static constexpr int textDKey = 68
static constexpr int textEKey = 69
static constexpr int textFKey = 70
static constexpr int textGKey = 71
static constexpr int textHKey = 72
static constexpr int textIKey = 73
static constexpr int textJKey = 74
static constexpr int textKKey = 75
static constexpr int textLKey = 76
static constexpr int textMKey = 77
static constexpr int textNKey = 78
static constexpr int textOKey = 79
static constexpr int textPKey = 80
static constexpr int textQKey = 81
static constexpr int textRKey = 82
static constexpr int textSKey = 83
static constexpr int textTKey = 84
static constexpr int textUKey = 85
static constexpr int textVKey = 86
static constexpr int textWKey = 87
static constexpr int textXKey = 88
static constexpr int textYKey = 89
static constexpr int textZKey = 90
static constexpr int leftBracketKey = 91
static constexpr int backslashKey = 92
static constexpr int rightBracketKey = 93
static constexpr int graveAccentKey = 96
static constexpr int world1Key = 161
static constexpr int world2Key = 162
static constexpr int escapeKey = 256
static constexpr int enterKey = 257
static constexpr int tabKey = 258
static constexpr int backspaceKey = 259
static constexpr int insertKey = 260
static constexpr int deleteKey = 261
static constexpr int rightKey = 262
static constexpr int leftKey = 263
static constexpr int downKey = 264
static constexpr int upKey = 265
static constexpr int pageUpKey = 266
static constexpr int pageDownKey = 267
static constexpr int homeKey = 268
static constexpr int endKey = 269
static constexpr int capsLockKey = 280
static constexpr int scrollLockKey = 281
static constexpr int numLockKey = 282
static constexpr int printScreenKey = 283
static constexpr int pauseKey = 284
static constexpr int f1Key = 290
static constexpr int f2Key = 291
static constexpr int f3Key = 292
static constexpr int f4Key = 293
static constexpr int f5Key = 294
static constexpr int f6Key = 295
static constexpr int f7Key = 296
static constexpr int f8Key = 297
static constexpr int f9Key = 298
static constexpr int f10Key = 299
static constexpr int f11Key = 300
static constexpr int f12Key = 301
static constexpr int f13Key = 302
static constexpr int f14Key = 303
static constexpr int f15Key = 304
static constexpr int f16Key = 305
static constexpr int f17Key = 306
static constexpr int f18Key = 307
static constexpr int f19Key = 308
static constexpr int f20Key = 309
static constexpr int f21Key = 310
static constexpr int f22Key = 311
static constexpr int f23Key = 312
static constexpr int f24Key = 313
static constexpr int f25Key = 314
static constexpr int kp0Key = 320
static constexpr int kp1Key = 321
static constexpr int kp2Key = 322
static constexpr int kp3Key = 323
static constexpr int kp4Key = 324
static constexpr int kp5Key = 325
static constexpr int kp6Key = 326
static constexpr int kp7Key = 327
static constexpr int kp8Key = 328
static constexpr int kp9Key = 329
static constexpr int kpDecimalKey = 330
static constexpr int kpDivideKey = 331
static constexpr int kpMultiplyKey = 332
static constexpr int kpSubtractKey = 333
static constexpr int kpAddKey = 334
static constexpr int kpEnterKey = 335
static constexpr int kpEqualKey = 336
static constexpr int leftShiftKey = 340
static constexpr int leftControlKey = 341
static constexpr int leftAltKey = 342
static constexpr int leftSuperKey = 343
static constexpr int rightShiftKey = 344
static constexpr int rightControlKey = 345
static constexpr int rightAltKey = 346
static constexpr int rightSuperKey = 347
static constexpr int menuKey = 348
Detailed Description
Represents a single key press, encapsulating information about the key and any associated modifiers.
This class is designed to represent a key press in a platform-independent manner, storing details about the key code, any modifier keys that were active (like Shift, Ctrl, etc.), and the Unicode character for key presses that generate text.
Constructor & Destructor Documentation
KeyPress() [1/6]
yup::KeyPress::KeyPress () constexpr default noexcept
Default constructor, initializes a key press with no key or modifiers.
Referenced by KeyPress(), KeyPress(), KeyPress(), operator!=(), operator=(), operator=(), and operator==().
KeyPress() [2/6]
yup::KeyPress::KeyPress (int newKey) constexpr noexcept
Constructs a KeyPress with a specified key code.
Parameters
newKey The key code associated with the key press.
References KeyPress().
KeyPress() [3/6]
yup::KeyPress::KeyPress (int newKey, KeyModifiers newModifiers) constexpr noexcept
Constructs a KeyPress with a specified key code and modifiers.
Parameters
newKey The key code for the key press.
newModifiers The modifiers that were active during the key press.
KeyPress() [4/6]
yup::KeyPress::KeyPress (int newKey, KeyModifiers newModifiers, char32_t newScancode) constexpr noexcept
Constructs a KeyPress with a specified key code, modifiers, and a scancode representing the text character.
Parameters
newKey The key code for the key press.
newModifiers The modifiers that were active during the key press.
newScancode The Unicode scancode that represents the text character produced by the key press.
KeyPress() [5/6]
yup::KeyPress::KeyPress (const KeyPress & other) constexpr default noexcept
References KeyPress().
KeyPress() [6/6]
yup::KeyPress::KeyPress (KeyPress && other) constexpr default noexcept
References KeyPress().
Member Function Documentation
operator=() [1/2]
KeyPress & yup::KeyPress::operator= (const KeyPress & other) constexpr default noexcept
References KeyPress().
operator=() [2/2]
KeyPress & yup::KeyPress::operator= (KeyPress && other) constexpr default noexcept
References KeyPress().
getKey()
int yup::KeyPress::getKey () const constexpr noexcept
Gets the key code of the key press.
Returns
The key code.
Referenced by yup::TextEditor::keyDown().
getModifiers()
KeyModifiers yup::KeyPress::getModifiers () const constexpr noexcept
Gets the modifiers associated with the key press.
Returns
The modifiers.
Referenced by yup::TextEditor::keyDown().
getTextCharacter()
char32_t yup::KeyPress::getTextCharacter () const constexpr noexcept
Gets the Unicode text character produced by the key press, if any.
This is typically relevant for key presses that result in a printable character.
Returns
The Unicode character code.
operator==()
bool yup::KeyPress::operator== (const KeyPress & other) const constexpr noexcept
Compares two KeyPress objects for equality.
Two key presses are considered equal if they have the same key code, modifiers, and scancode.
Parameters
other The other KeyPress to compare with.
Returns
True if the KeyPress objects are equal, false otherwise.
References KeyPress().
operator!=()
bool yup::KeyPress::operator!= (const KeyPress & other) const constexpr noexcept
Compares two KeyPress objects for inequality.
Parameters
other The other KeyPress to compare with.
Returns
True if the KeyPress objects are not equal, false otherwise.
References KeyPress().
Member Data Documentation
spaceKey
int yup::KeyPress::spaceKey = 32 static constexpr
Aliases for commonly used keys.
apostropheKey
int yup::KeyPress::apostropheKey = 39 static constexpr
commaKey
int yup::KeyPress::commaKey = 44 static constexpr
minusKey
int yup::KeyPress::minusKey = 45 static constexpr
periodKey
int yup::KeyPress::periodKey = 46 static constexpr
slashKey
int yup::KeyPress::slashKey = 47 static constexpr
number0Key
int yup::KeyPress::number0Key = 48 static constexpr
number1Key
int yup::KeyPress::number1Key = 49 static constexpr
number2Key
int yup::KeyPress::number2Key = 50 static constexpr
number3Key
int yup::KeyPress::number3Key = 51 static constexpr
number4Key
int yup::KeyPress::number4Key = 52 static constexpr
number5Key
int yup::KeyPress::number5Key = 53 static constexpr
number6Key
int yup::KeyPress::number6Key = 54 static constexpr
number7Key
int yup::KeyPress::number7Key = 55 static constexpr
number8Key
int yup::KeyPress::number8Key = 56 static constexpr
number9Key
int yup::KeyPress::number9Key = 57 static constexpr
semicolonKey
int yup::KeyPress::semicolonKey = 59 static constexpr
equalKey
int yup::KeyPress::equalKey = 61 static constexpr
textAKey
int yup::KeyPress::textAKey = 65 static constexpr
Referenced by yup::TextEditor::keyDown().
textBKey
int yup::KeyPress::textBKey = 66 static constexpr
textCKey
int yup::KeyPress::textCKey = 67 static constexpr
Referenced by yup::TextEditor::keyDown().
textDKey
int yup::KeyPress::textDKey = 68 static constexpr
textEKey
int yup::KeyPress::textEKey = 69 static constexpr
textFKey
int yup::KeyPress::textFKey = 70 static constexpr
textGKey
int yup::KeyPress::textGKey = 71 static constexpr
textHKey
int yup::KeyPress::textHKey = 72 static constexpr
textIKey
int yup::KeyPress::textIKey = 73 static constexpr
textJKey
int yup::KeyPress::textJKey = 74 static constexpr
textKKey
int yup::KeyPress::textKKey = 75 static constexpr
textLKey
int yup::KeyPress::textLKey = 76 static constexpr
textMKey
int yup::KeyPress::textMKey = 77 static constexpr
textNKey
int yup::KeyPress::textNKey = 78 static constexpr
textOKey
int yup::KeyPress::textOKey = 79 static constexpr
textPKey
int yup::KeyPress::textPKey = 80 static constexpr
textQKey
int yup::KeyPress::textQKey = 81 static constexpr
textRKey
int yup::KeyPress::textRKey = 82 static constexpr
textSKey
int yup::KeyPress::textSKey = 83 static constexpr
textTKey
int yup::KeyPress::textTKey = 84 static constexpr
textUKey
int yup::KeyPress::textUKey = 85 static constexpr
textVKey
int yup::KeyPress::textVKey = 86 static constexpr
Referenced by yup::TextEditor::keyDown().
textWKey
int yup::KeyPress::textWKey = 87 static constexpr
textXKey
int yup::KeyPress::textXKey = 88 static constexpr
Referenced by yup::TextEditor::keyDown().
textYKey
int yup::KeyPress::textYKey = 89 static constexpr
textZKey
int yup::KeyPress::textZKey = 90 static constexpr
leftBracketKey
int yup::KeyPress::leftBracketKey = 91 static constexpr
backslashKey
int yup::KeyPress::backslashKey = 92 static constexpr
rightBracketKey
int yup::KeyPress::rightBracketKey = 93 static constexpr
graveAccentKey
int yup::KeyPress::graveAccentKey = 96 static constexpr
world1Key
int yup::KeyPress::world1Key = 161 static constexpr
world2Key
int yup::KeyPress::world2Key = 162 static constexpr
escapeKey
int yup::KeyPress::escapeKey = 256 static constexpr
enterKey
int yup::KeyPress::enterKey = 257 static constexpr
Referenced by yup::TextEditor::keyDown().
tabKey
int yup::KeyPress::tabKey = 258 static constexpr
Referenced by yup::TextEditor::keyDown().
backspaceKey
int yup::KeyPress::backspaceKey = 259 static constexpr
Referenced by yup::TextEditor::keyDown().
insertKey
int yup::KeyPress::insertKey = 260 static constexpr
deleteKey
int yup::KeyPress::deleteKey = 261 static constexpr
Referenced by yup::TextEditor::keyDown().
rightKey
int yup::KeyPress::rightKey = 262 static constexpr
Referenced by yup::TextEditor::keyDown().
leftKey
int yup::KeyPress::leftKey = 263 static constexpr
Referenced by yup::TextEditor::keyDown().
downKey
int yup::KeyPress::downKey = 264 static constexpr
Referenced by yup::TextEditor::keyDown().
upKey
int yup::KeyPress::upKey = 265 static constexpr
Referenced by yup::TextEditor::keyDown().
pageUpKey
int yup::KeyPress::pageUpKey = 266 static constexpr
pageDownKey
int yup::KeyPress::pageDownKey = 267 static constexpr
homeKey
int yup::KeyPress::homeKey = 268 static constexpr
Referenced by yup::TextEditor::keyDown().
endKey
int yup::KeyPress::endKey = 269 static constexpr
Referenced by yup::TextEditor::keyDown().
capsLockKey
int yup::KeyPress::capsLockKey = 280 static constexpr
scrollLockKey
int yup::KeyPress::scrollLockKey = 281 static constexpr
numLockKey
int yup::KeyPress::numLockKey = 282 static constexpr
printScreenKey
int yup::KeyPress::printScreenKey = 283 static constexpr
pauseKey
int yup::KeyPress::pauseKey = 284 static constexpr
f1Key
int yup::KeyPress::f1Key = 290 static constexpr
f2Key
int yup::KeyPress::f2Key = 291 static constexpr
f3Key
int yup::KeyPress::f3Key = 292 static constexpr
f4Key
int yup::KeyPress::f4Key = 293 static constexpr
f5Key
int yup::KeyPress::f5Key = 294 static constexpr
f6Key
int yup::KeyPress::f6Key = 295 static constexpr
f7Key
int yup::KeyPress::f7Key = 296 static constexpr
f8Key
int yup::KeyPress::f8Key = 297 static constexpr
f9Key
int yup::KeyPress::f9Key = 298 static constexpr
f10Key
int yup::KeyPress::f10Key = 299 static constexpr
f11Key
int yup::KeyPress::f11Key = 300 static constexpr
f12Key
int yup::KeyPress::f12Key = 301 static constexpr
f13Key
int yup::KeyPress::f13Key = 302 static constexpr
f14Key
int yup::KeyPress::f14Key = 303 static constexpr
f15Key
int yup::KeyPress::f15Key = 304 static constexpr
f16Key
int yup::KeyPress::f16Key = 305 static constexpr
f17Key
int yup::KeyPress::f17Key = 306 static constexpr
f18Key
int yup::KeyPress::f18Key = 307 static constexpr
f19Key
int yup::KeyPress::f19Key = 308 static constexpr
f20Key
int yup::KeyPress::f20Key = 309 static constexpr
f21Key
int yup::KeyPress::f21Key = 310 static constexpr
f22Key
int yup::KeyPress::f22Key = 311 static constexpr
f23Key
int yup::KeyPress::f23Key = 312 static constexpr
f24Key
int yup::KeyPress::f24Key = 313 static constexpr
f25Key
int yup::KeyPress::f25Key = 314 static constexpr
kp0Key
int yup::KeyPress::kp0Key = 320 static constexpr
kp1Key
int yup::KeyPress::kp1Key = 321 static constexpr
kp2Key
int yup::KeyPress::kp2Key = 322 static constexpr
kp3Key
int yup::KeyPress::kp3Key = 323 static constexpr
kp4Key
int yup::KeyPress::kp4Key = 324 static constexpr
kp5Key
int yup::KeyPress::kp5Key = 325 static constexpr
kp6Key
int yup::KeyPress::kp6Key = 326 static constexpr
kp7Key
int yup::KeyPress::kp7Key = 327 static constexpr
kp8Key
int yup::KeyPress::kp8Key = 328 static constexpr
kp9Key
int yup::KeyPress::kp9Key = 329 static constexpr
kpDecimalKey
int yup::KeyPress::kpDecimalKey = 330 static constexpr
kpDivideKey
int yup::KeyPress::kpDivideKey = 331 static constexpr
kpMultiplyKey
int yup::KeyPress::kpMultiplyKey = 332 static constexpr
kpSubtractKey
int yup::KeyPress::kpSubtractKey = 333 static constexpr
kpAddKey
int yup::KeyPress::kpAddKey = 334 static constexpr
kpEnterKey
int yup::KeyPress::kpEnterKey = 335 static constexpr
kpEqualKey
int yup::KeyPress::kpEqualKey = 336 static constexpr
leftShiftKey
int yup::KeyPress::leftShiftKey = 340 static constexpr
leftControlKey
int yup::KeyPress::leftControlKey = 341 static constexpr
leftAltKey
int yup::KeyPress::leftAltKey = 342 static constexpr
leftSuperKey
int yup::KeyPress::leftSuperKey = 343 static constexpr
rightShiftKey
int yup::KeyPress::rightShiftKey = 344 static constexpr
rightControlKey
int yup::KeyPress::rightControlKey = 345 static constexpr
rightAltKey
int yup::KeyPress::rightAltKey = 346 static constexpr
rightSuperKey
int yup::KeyPress::rightSuperKey = 347 static constexpr
menuKey
int yup::KeyPress::menuKey = 348 static constexpr