YUP: yup::WebInputStream::Listener Class Reference
yup::WebInputStream::Listener Class Reference
Used to receive callbacks for POST data send progress.
Public Member Functions
virtual ~Listener ()=default
Destructor.
virtual bool postDataSendProgress (WebInputStream &request, int bytesSent, int totalBytes)
This method will be called periodically with updates on POST data upload progress.
Detailed Description
Used to receive callbacks for POST data send progress.
Pass one of these into the connect() method and its postDataSendProgress() method will be called periodically with updates on POST data upload progress.
Constructor & Destructor Documentation
~Listener()
virtual yup::WebInputStream::Listener::~Listener () virtual default
Destructor.
References postDataSendProgress(), and yup::WebInputStream::WebInputStream().
Member Function Documentation
postDataSendProgress()
bool yup::WebInputStream::Listener::postDataSendProgress (WebInputStream & request, int bytesSent, int totalBytes) virtual
This method will be called periodically with updates on POST data upload progress.
Parameters
request the original request
bytesSent the number of bytes sent so far
totalBytes the total number of bytes to send
Returns
true to continue or false to cancel the upload
References yup::WebInputStream::WebInputStream().
Referenced by ~Listener().