YUP: yup::YUPApplicationBase Class Reference
yup::YUPApplicationBase Class Reference abstract
Abstract base class for application classes.
Public Member Functions
virtual ~YUPApplicationBase ()
Destructor.
virtual const String getApplicationName ()=0
Returns the application's name.
virtual const String getApplicationVersion ()=0
Returns the application's version number.
virtual bool moreThanOneInstanceAllowed ()=0
Checks whether multiple instances of the app are allowed.
virtual void initialise (const String &commandLineParameters)=0
Called when the application starts.
virtual void shutdown ()=0
virtual void anotherInstanceStarted (const String &commandLine)=0
Indicates that the user has tried to start up another instance of the app.
virtual void systemRequestedQuit ()=0
Called when the operating system is trying to close the application.
virtual void suspended ()=0
This method is called when the application is being put into background mode by the operating system.
virtual void resumed ()=0
This method is called when the application is being woken from background mode by the operating system.
virtual void unhandledException (const std::exception *, const String &sourceFilename, int lineNumber)=0
If any unhandled exceptions make it through to the message dispatch loop, this callback will be triggered, in case you want to log them or do some other type of error-handling.
virtual void memoryWarningReceived ()
Called by the operating system to indicate that you should reduce your memory footprint.
virtual bool backButtonPressed ()
This will be called when the back button on a device is pressed.
void setApplicationReturnValue (int newReturnValue) noexcept
Sets the value that should be returned as the application's exit code when the app quits.
int getApplicationReturnValue () const noexcept
Returns the value that has been set as the application's exit code.
bool isInitialising () const noexcept
Returns true if the application hasn't yet completed its initialise() method and entered the main event loop.
Static Public Member Functions
static YUPApplicationBase * getInstance () noexcept
Returns the global instance of the application object that's running.
static void quit ()
Signals that the main message loop should stop and the application should terminate.
static StringArray YUP_CALLTYPE getCommandLineParameterArray ()
Returns the application's command line parameters as a set of strings.
static String YUP_CALLTYPE getCommandLineParameters ()
Returns the application's command line parameters as a single string.
static bool isStandaloneApp () noexcept
Returns true if this executable is running as an app (as opposed to being a plugin or other kind of shared library.
Protected Member Functions
YUPApplicationBase ()
Detailed Description
Abstract base class for application classes.
Note that in the yup_gui module, there's a utility class YUPApplication which derives from YUPApplicationBase, and takes care of a few chores. Most of the time you'll want to derive your class from YUPApplication rather than using YUPApplicationBase directly, but if you're not using the yup_gui_basics module then you might need to go straight to this base class.
Any application that wants to run an event loop must declare a subclass of YUPApplicationBase, and implement its various pure virtual methods.
It then needs to use the START_YUP_APPLICATION macro somewhere in a CPP file to declare an instance of this class and generate suitable platform-specific boilerplate code to launch the app.
e.g.
class MyYUPApp  : public YUPApplication
{
public:
    MyYUPApp()  {}
    ~MyYUPApp() {}
    void initialise (const String& commandLine) override
    {
        myMainWindow.reset (new MyApplicationWindow());
        myMainWindow->setBounds (100, 100, 400, 500);
        myMainWindow->setVisible (true);
    }
    void shutdown() override
    {
        myMainWindow = nullptr;
    }
    const String getApplicationName() override
    {
        return "Super YUP-o-matic";
    }
    const String getApplicationVersion() override
    {
        return "1.0";
    }
private:
    std::unique_ptr<MyApplicationWindow> myMainWindow;
};
// this generates boilerplate code to launch our app class:
START_YUP_APPLICATION (MyYUPApp)
See also
YUPApplication, START_YUP_APPLICATION
Constructor & Destructor Documentation
YUPApplicationBase()
yup::YUPApplicationBase::YUPApplicationBase () protected
References isStandaloneApp().
Referenced by getInstance().
~YUPApplicationBase()
yup::YUPApplicationBase::~YUPApplicationBase () virtual
Destructor.
Member Function Documentation
getInstance()
YUPApplicationBase * yup::YUPApplicationBase::getInstance () static noexcept
Returns the global instance of the application object that's running.
References YUPApplicationBase().
getApplicationName()
virtual const String yup::YUPApplicationBase::getApplicationName () pure virtual
Returns the application's name.
getApplicationVersion()
virtual const String yup::YUPApplicationBase::getApplicationVersion () pure virtual
Returns the application's version number.
moreThanOneInstanceAllowed()
virtual bool yup::YUPApplicationBase::moreThanOneInstanceAllowed () pure virtual
Checks whether multiple instances of the app are allowed.
If your application class returns true for this, more than one instance is permitted to run (except on the Mac where this isn't possible).
If it's false, the second instance won't start, but you will still get a callback to anotherInstanceStarted() to tell you about this - which gives you a chance to react to what the user was trying to do.
See also
anotherInstanceStarted
Implemented in yup::YUPApplication.
initialise()
virtual void yup::YUPApplicationBase::initialise (const String & commandLineParameters) pure virtual
Called when the application starts.
This will be called once to let the application do whatever initialisation it needs, create its windows, etc.
After the method returns, the normal event-dispatch loop will be run, until the quit() method is called, at which point the shutdown() method will be called to let the application clear up anything it needs to delete.
If during the initialise() method, the application decides not to start-up after all, it can just call the quit() method and the event loop won't be run.
Parameters
commandLineParameters the line passed in does not include the name of the executable, just the parameter list. To get the parameters as an array, you can call YUPApplication::getCommandLineParameters()
See also
shutdown, quit
shutdown()
virtual void yup::YUPApplicationBase::shutdown () pure virtual
anotherInstanceStarted()
virtual void yup::YUPApplicationBase::anotherInstanceStarted (const String & commandLine) pure virtual
Indicates that the user has tried to start up another instance of the app.
This will get called even if moreThanOneInstanceAllowed() is false. It is currently only implemented on Windows and Mac.
See also
moreThanOneInstanceAllowed
Implemented in yup::YUPApplication.
systemRequestedQuit()
virtual void yup::YUPApplicationBase::systemRequestedQuit () pure virtual
Called when the operating system is trying to close the application.
The default implementation of this method is to call quit(), but it may be overloaded to ignore the request or do some other special behaviour instead. For example, you might want to offer the user the chance to save their changes before quitting, and give them the chance to cancel.
If you want to send a quit signal to your app, this is the correct method to call, because it means that requests that come from the system get handled in the same way as those from your own application code. So e.g. you'd call this method from a "quit" item on a menu bar.
Implemented in yup::YUPApplication.
suspended()
virtual void yup::YUPApplicationBase::suspended () pure virtual
This method is called when the application is being put into background mode by the operating system.
Implemented in yup::YUPApplication.
resumed()
virtual void yup::YUPApplicationBase::resumed () pure virtual
This method is called when the application is being woken from background mode by the operating system.
Implemented in yup::YUPApplication.
unhandledException()
virtual void yup::YUPApplicationBase::unhandledException (const std::exception * , const String & sourceFilename, int lineNumber) pure virtual
If any unhandled exceptions make it through to the message dispatch loop, this callback will be triggered, in case you want to log them or do some other type of error-handling.
If the type of exception is derived from the std::exception class, the pointer passed-in will be valid. If the exception is of unknown type, this pointer will be null.
Implemented in yup::YUPApplication.
memoryWarningReceived()
virtual void yup::YUPApplicationBase::memoryWarningReceived () virtual
Called by the operating system to indicate that you should reduce your memory footprint.
You should override this method to free up some memory gracefully, if possible, otherwise the host may forcibly kill your app.
At the moment this method is only called on iOS.
backButtonPressed()
virtual bool yup::YUPApplicationBase::backButtonPressed () virtual
This will be called when the back button on a device is pressed.
The return value should be used to indicate whether the back button event has been handled by the application, for example if you want to implement custom navigation instead of the standard behaviour on Android.
This is currently only implemented on Android devices.
Returns
true if the event has been handled, or false if the default OS behaviour should happen
quit()
void yup::YUPApplicationBase::quit () static
Signals that the main message loop should stop and the application should terminate.
This isn't synchronous, it just posts a quit message to the main queue, and when this message arrives, the message loop will stop, the shutdown() method will be called, and the app will exit.
Note that this will cause an unconditional quit to happen, so if you need an extra level before this, e.g. to give the user the chance to save their work and maybe cancel the quit, you'll need to handle this in the systemRequestedQuit() method - see that method's help for more info.
See also
MessageManager
References yup::MessageManager::getInstance(), and yup::MessageManager::stopDispatchLoop().
Referenced by yup::YUPApplication::systemRequestedQuit().
getCommandLineParameterArray()
StringArray yup::YUPApplicationBase::getCommandLineParameterArray () static
Returns the application's command line parameters as a set of strings.
See also
getCommandLineParameters
References yup::StringArray::add(), yup::yup_argc, and yup::yup_argv.
Referenced by getCommandLineParameters().
getCommandLineParameters()
String yup::YUPApplicationBase::getCommandLineParameters () static
Returns the application's command line parameters as a single string.
See also
getCommandLineParameterArray
References getCommandLineParameterArray(), and yup::String::trim().
setApplicationReturnValue()
void yup::YUPApplicationBase::setApplicationReturnValue (int newReturnValue) noexcept
Sets the value that should be returned as the application's exit code when the app quits.
This is the value that's returned by the main() function. Normally you'd leave this as 0 unless you want to indicate an error code.
See also
getApplicationReturnValue
getApplicationReturnValue()
int yup::YUPApplicationBase::getApplicationReturnValue () const noexcept
Returns the value that has been set as the application's exit code.
See also
setApplicationReturnValue
isStandaloneApp()
bool yup::YUPApplicationBase::isStandaloneApp () static noexcept
Returns true if this executable is running as an app (as opposed to being a plugin or other kind of shared library.
Referenced by YUPApplicationBase().
isInitialising()
bool yup::YUPApplicationBase::isInitialising () const noexcept
Returns true if the application hasn't yet completed its initialise() method and entered the main event loop.
This is handy for things like splash screens to know when the app's up-and-running properly.