YUP: yup::MouseWheelData Class Reference
yup::MouseWheelData Class Reference
Public Member Functions
constexpr MouseWheelData () noexcept=default
constexpr MouseWheelData (float deltaX, float deltaY) noexcept
constexpr MouseWheelData (const MouseWheelData &other) noexcept=default
constexpr MouseWheelData (MouseWheelData &&other) noexcept=default
constexpr MouseWheelData & operator= (const MouseWheelData &other) noexcept=default
constexpr MouseWheelData & operator= (MouseWheelData &&other) noexcept=default
constexpr float getDeltaX () const noexcept
constexpr MouseWheelData & setDeltaX (float newDeltaX) noexcept
constexpr MouseWheelData withDeltaX (float newDeltaX) const noexcept
constexpr float getDeltaY () const noexcept
constexpr MouseWheelData & setDeltaY (float newDeltaY) noexcept
constexpr MouseWheelData withDeltaY (float newDeltaY) const noexcept
constexpr bool operator== (const MouseWheelData &other) const noexcept
constexpr bool operator!= (const MouseWheelData &other) const noexcept
Constructor & Destructor Documentation
MouseWheelData() [1/4]
yup::MouseWheelData::MouseWheelData () constexpr default noexcept
Referenced by MouseWheelData(), MouseWheelData(), MouseWheelData(), operator!=(), operator=(), operator=(), operator==(), setDeltaX(), setDeltaY(), withDeltaX(), and withDeltaY().
MouseWheelData() [2/4]
yup::MouseWheelData::MouseWheelData (float deltaX, float deltaY) constexpr noexcept
References MouseWheelData().
MouseWheelData() [3/4]
yup::MouseWheelData::MouseWheelData (const MouseWheelData & other) constexpr default noexcept
References MouseWheelData().
MouseWheelData() [4/4]
yup::MouseWheelData::MouseWheelData (MouseWheelData && other) constexpr default noexcept
References MouseWheelData().
Member Function Documentation
operator=() [1/2]
MouseWheelData & yup::MouseWheelData::operator= (const MouseWheelData & other) constexpr default noexcept
References MouseWheelData().
operator=() [2/2]
MouseWheelData & yup::MouseWheelData::operator= (MouseWheelData && other) constexpr default noexcept
References MouseWheelData().
getDeltaX()
float yup::MouseWheelData::getDeltaX () const constexpr noexcept
Referenced by yup::Slider::mouseWheel().
setDeltaX()
MouseWheelData & yup::MouseWheelData::setDeltaX (float newDeltaX) constexpr noexcept
References MouseWheelData().
withDeltaX()
MouseWheelData yup::MouseWheelData::withDeltaX (float newDeltaX) const constexpr noexcept
References MouseWheelData().
getDeltaY()
float yup::MouseWheelData::getDeltaY () const constexpr noexcept
Referenced by yup::Slider::mouseWheel().
setDeltaY()
MouseWheelData & yup::MouseWheelData::setDeltaY (float newDeltaY) constexpr noexcept
References MouseWheelData().
withDeltaY()
MouseWheelData yup::MouseWheelData::withDeltaY (float newDeltaY) const constexpr noexcept
References MouseWheelData().
operator==()
bool yup::MouseWheelData::operator== (const MouseWheelData & other) const constexpr noexcept
References MouseWheelData().
operator!=()
bool yup::MouseWheelData::operator!= (const MouseWheelData & other) const constexpr noexcept
References MouseWheelData().