YUP: yup::Graphics::SavedState Class Reference
yup::Graphics::SavedState Class Reference
Represents a saved state of the Graphics object.
Public Member Functions
SavedState (Graphics &g)
Constructs a SavedState linked to a specific Graphics object.
SavedState (SavedState &&)
Move constructor and assignment operator.
SavedState & operator= (SavedState &&)
SavedState (const SavedState &)=delete
Deleted copy constructor/assignment operators to avoid unintentional copying.
SavedState & operator= (const SavedState &)=delete
~SavedState ()
Destroys the SavedState, potentially restoring the Graphics state.
Detailed Description
Represents a saved state of the Graphics object.
This class allows Graphics states to be saved and restored, which is useful for complex rendering tasks where temporary changes to the state are made and later reverted.
Constructor & Destructor Documentation
SavedState() [1/3]
yup::Graphics::SavedState::SavedState (Graphics & g)
Constructs a SavedState linked to a specific Graphics object.
Parameters
g Reference to the Graphics object whose state is to be saved.
References yup::Graphics::Graphics().
Referenced by operator=(), operator=(), SavedState(), and SavedState().
SavedState() [2/3]
yup::Graphics::SavedState::SavedState (SavedState && other)
Move constructor and assignment operator.
References SavedState().
SavedState() [3/3]
yup::Graphics::SavedState::SavedState (const SavedState &) delete
Deleted copy constructor/assignment operators to avoid unintentional copying.
References SavedState().
~SavedState()
yup::Graphics::SavedState::~SavedState ()
Destroys the SavedState, potentially restoring the Graphics state.
Member Function Documentation
operator=() [1/2]
Graphics::SavedState & yup::Graphics::SavedState::operator= (SavedState && other)
References SavedState().
operator=() [2/2]
SavedState & yup::Graphics::SavedState::operator= (const SavedState &) delete
References yup::Graphics::Graphics(), and SavedState().