YUP: yup::Desktop Class Reference
yup::Desktop Class Reference
Represents the desktop environment, providing access to screen information and management.
Public Member Functions
~Desktop ()
Destructor for the Desktop class.
int getNumScreens () const
Returns the number of screens connected to the system.
Screen::Ptr getScreen (int screenIndex) const
Retrieves a pointer to the Screen object at the specified index.
Span< const Screen *const > getScreens () const
Retrieves a span of pointers to all Screen objects.
Screen::Ptr getPrimaryScreen () const
Retrieves a pointer to the primary Screen object.
Screen::Ptr getScreenContainingMouseCursor () const
Retries a pointer to the screen containing the mouse cursor.
Screen::Ptr getScreenContaining (const Point< float > &location) const
Retries a pointer to the screen containing an absolute location.
void setMouseCursor (const MouseCursor &cursorToSet)
Sets the mouse cursor to the specified cursor.
MouseCursor getMouseCursor () const
Retrieves the current mouse cursor.
Point< float > getCurrentMouseLocation () const
Retrieves the current absolute mouse location.
void setCurrentMouseLocation (const Point< float > &location)
Retrieves the current absolute mouse location.
void updateScreens ()
Updates the list of screens.
void handleScreenConnected (int screenIndex)
void handleScreenDisconnected (int screenIndex)
void handleScreenMoved (int screenIndex)
void handleScreenOrientationChanged (int screenIndex)
Detailed Description
Represents the desktop environment, providing access to screen information and management.
This class encapsulates functionality related to the desktop environment, including access to multiple screens connected to the system. It allows querying and management of different screen properties through the Screen objects.
Constructor & Destructor Documentation
~Desktop()
yup::Desktop::~Desktop ()
Destructor for the Desktop class.
Member Function Documentation
getNumScreens()
int yup::Desktop::getNumScreens () const
Returns the number of screens connected to the system.
Returns
The number of available screens.
getScreen()
Screen::Ptr yup::Desktop::getScreen (int screenIndex) const
Retrieves a pointer to the Screen object at the specified index.
Parameters
screenIndex The zero-based index of the screen to retrieve.
Returns
A pointer to the Screen object, or nullptr if the index is out of range.
References yup::isPositiveAndBelow().
Referenced by getPrimaryScreen(), and getScreenContaining().
getScreens()
Span< const Screen *const > yup::Desktop::getScreens () const
Retrieves a span of pointers to all Screen objects.
Returns
A span of pointers to all Screen objects.
getPrimaryScreen()
Screen::Ptr yup::Desktop::getPrimaryScreen () const
Retrieves a pointer to the primary Screen object.
The primary screen is typically the main screen of the system where applications are initially screened.
Returns
A pointer to the primary Screen object.
References getScreen().
getScreenContainingMouseCursor()
Screen::Ptr yup::Desktop::getScreenContainingMouseCursor () const
Retries a pointer to the screen containing the mouse cursor.
Returns
A pointer to the Screen object which contains the mouse cursor.
References getCurrentMouseLocation(), and getScreenContaining().
getScreenContaining()
Screen::Ptr yup::Desktop::getScreenContaining (const Point< float > & location) const
Retries a pointer to the screen containing an absolute location.
Returns
A pointer to the Screen object which contains the location.
References getScreen(), and yup::Point< ValueType >::to().
Referenced by getScreenContainingMouseCursor().
setMouseCursor()
void yup::Desktop::setMouseCursor (const MouseCursor & cursorToSet)
Sets the mouse cursor to the specified cursor.
Parameters
cursorToSet The cursor to set.
References getMouseCursor().
getMouseCursor()
MouseCursor yup::Desktop::getMouseCursor () const
Retrieves the current mouse cursor.
Returns
The current mouse cursor.
References yup::MouseCursor::Default.
Referenced by setMouseCursor().
getCurrentMouseLocation()
Point< float > yup::Desktop::getCurrentMouseLocation () const
Retrieves the current absolute mouse location.
Returns
The current absolute mouse location.
Referenced by getScreenContainingMouseCursor().
setCurrentMouseLocation()
void yup::Desktop::setCurrentMouseLocation (const Point< float > & location)
Retrieves the current absolute mouse location.
Returns
The current absolute mouse location.
updateScreens()
void yup::Desktop::updateScreens ()
Updates the list of screens.
References handleScreenConnected(), handleScreenDisconnected(), handleScreenMoved(), and handleScreenOrientationChanged().
Referenced by handleScreenConnected(), handleScreenDisconnected(), handleScreenMoved(), and handleScreenOrientationChanged().
handleScreenConnected()
void yup::Desktop::handleScreenConnected (int screenIndex)
References updateScreens().
Referenced by updateScreens().
handleScreenDisconnected()
void yup::Desktop::handleScreenDisconnected (int screenIndex)
References updateScreens().
Referenced by updateScreens().
handleScreenMoved()
void yup::Desktop::handleScreenMoved (int screenIndex)
References updateScreens().
Referenced by updateScreens().
handleScreenOrientationChanged()
void yup::Desktop::handleScreenOrientationChanged (int screenIndex)
References updateScreens().
Referenced by updateScreens().