YUP: yup::ComponentNative Class Reference
yup::ComponentNative Class Reference abstract
Provides platform-native window and rendering capabilities for Components.
Classes
struct Options
Configuration options for creating a native component.
Public Types
using Flags = FlagSet<uint32, decoratedWindowTag, resizableWindowTag, renderContinuousTag, allowHighDensityDisplayTag>
Type definition for window configuration flags.
Public Member Functions
ComponentNative (Component &newComponent, const Flags &newFlags)
Constructor.
virtual ~ComponentNative ()
Destructor.
virtual void setTitle (const String &title)=0
Sets the window title.
virtual String getTitle () const =0
Gets the current window title.
virtual void setVisible (bool shouldBeVisible)=0
Sets the visibility of the window.
virtual bool isVisible () const =0
Checks whether the window is currently visible.
virtual void setSize (const Size< int > &newSize)=0
Sets the size of the window.
virtual Size< int > getSize () const =0
Gets the current size of the window.
virtual Size< int > getContentSize () const =0
Gets the size of the window's content area.
virtual Point< int > getPosition () const =0
Gets the position of the window.
virtual void setPosition (const Point< int > &newPosition)=0
Sets the position of the window.
virtual Rectangle< int > getBounds () const =0
Gets the bounds of the window.
virtual void setBounds (const Rectangle< int > &newBounds)=0
Sets the bounds of the window.
virtual void setFullScreen (bool shouldBeFullScreen)=0
Sets whether the window should be in fullscreen mode.
virtual bool isFullScreen () const =0
Checks whether the window is currently in fullscreen mode.
virtual bool isDecorated () const =0
Checks whether the window has decorations.
virtual void setOpacity (float opacity)=0
Sets the opacity of the window.
virtual float getOpacity () const =0
Gets the current opacity of the window.
virtual void setFocusedComponent (Component *comp)=0
Sets the focused component.
virtual Component * getFocusedComponent () const =0
Gets the currently focused component.
virtual bool isContinuousRepaintingEnabled () const =0
Checks whether continuous repainting is enabled.
virtual void enableContinuousRepainting (bool shouldBeEnabled)=0
Enables or disables continuous repainting.
virtual bool isAtomicModeEnabled () const =0
Checks whether atomic mode is enabled.
virtual void enableAtomicMode (bool shouldBeEnabled)=0
Enables or disables atomic mode.
virtual bool isWireframeEnabled () const =0
Checks whether wireframe mode is enabled.
virtual void enableWireframe (bool shouldBeEnabld)=0
Enables or disables wireframe mode.
virtual void repaint ()=0
Requests a repaint of the entire component.
virtual void repaint (const Rectangle< float > &rect)=0
Requests a repaint of a specific area of the component.
virtual const RectangleList< float > & getRepaintAreas () const =0
Gets the list of areas that are currently scheduled for repainting.
virtual float getScaleDpi () const =0
Gets the DPI scale factor.
virtual float getCurrentFrameRate () const =0
Gets the current framerate.
virtual float getDesiredFrameRate () const =0
Gets the desired framerate.
virtual void * getNativeHandle () const =0
Gets the native handle for the component.
virtual rive::Factory * getFactory ()=0
Gets the Rive factory associated with this component.
Static Public Member Functions
static std::unique_ptr< ComponentNative > createFor (Component &component, const Options &options, void *parent)
Creates a platform-specific ComponentNative instance.
Static Public Attributes
static constexpr Flags noFlags = Flags()
No flags set.
static constexpr Flags decoratedWindow = Flags::declareValue<decoratedWindowTag>()
Flag to enable window decorations (title bar, borders, etc.).
static constexpr Flags resizableWindow = Flags::declareValue<resizableWindowTag>()
Flag to enable window resizing by the user.
static constexpr Flags renderContinuous = Flags::declareValue<renderContinuousTag>()
Flag to enable continuous rendering mode.
static constexpr Flags allowHighDensityDisplay = Flags::declareValue<allowHighDensityDisplayTag>()
Flag to enable high-density display support.
static constexpr Flags defaultFlags = decoratedWindow | resizableWindow | allowHighDensityDisplay
Default flags combining decoratedWindow, resizableWindow, and allowHighDensityDisplay.
Protected Attributes
Component & component
The Component associated with this native component.
Flags flags
The configuration flags for this native component.
Detailed Description
Provides platform-native window and rendering capabilities for Components.
This class serves as an abstraction layer between the Component class and the platform-specific window management and rendering systems. It handles native window creation, event processing, and rendering pipeline setup across different platforms.
ComponentNative objects are typically created internally by the Component class when a Component needs to be displayed on screen as a top-level window.
See also
Component
Member Typedef Documentation
Flags
using yup::ComponentNative::Flags = FlagSet<uint32, decoratedWindowTag, resizableWindowTag, renderContinuousTag, allowHighDensityDisplayTag>
Type definition for window configuration flags.
Constructor & Destructor Documentation
ComponentNative()
yup::ComponentNative::ComponentNative (Component & newComponent, const Flags & newFlags)
Constructor.
Parameters
newComponent The Component associated with this native component.
newFlags The flags used to configure the native component.
References component, and flags.
Referenced by createFor().
~ComponentNative()
yup::ComponentNative::~ComponentNative () virtual
Destructor.
Member Function Documentation
setTitle()
virtual void yup::ComponentNative::setTitle (const String & title) pure virtual
Sets the window title.
Parameters
title The new title to set.
References setTitle().
Referenced by setTitle().
getTitle()
virtual String yup::ComponentNative::getTitle () const pure virtual
Gets the current window title.
Returns
The current window title.
References getTitle().
Referenced by getTitle().
setVisible()
virtual void yup::ComponentNative::setVisible (bool shouldBeVisible) pure virtual
Sets the visibility of the window.
Parameters
shouldBeVisible True to make the window visible, false to hide it.
References setVisible().
Referenced by setVisible().
isVisible()
virtual bool yup::ComponentNative::isVisible () const pure virtual
Checks whether the window is currently visible.
Returns
True if the window is visible, false otherwise.
References isVisible().
Referenced by isVisible().
setSize()
virtual void yup::ComponentNative::setSize (const Size< int > & newSize) pure virtual
Sets the size of the window.
Parameters
newSize The new size to set.
References setSize().
Referenced by setSize().
getSize()
virtual Size< int > yup::ComponentNative::getSize () const pure virtual
Gets the current size of the window.
Returns
The current window size.
References getSize().
Referenced by getSize().
getContentSize()
virtual Size< int > yup::ComponentNative::getContentSize () const pure virtual
Gets the size of the window's content area.
Returns
The size of the window's content area.
References getContentSize().
Referenced by getContentSize().
getPosition()
virtual Point< int > yup::ComponentNative::getPosition () const pure virtual
Gets the position of the window.
Returns
The current window position.
References getPosition().
Referenced by getPosition().
setPosition()
virtual void yup::ComponentNative::setPosition (const Point< int > & newPosition) pure virtual
Sets the position of the window.
Parameters
newPosition The new position to set.
References setPosition().
Referenced by setPosition().
getBounds()
virtual Rectangle< int > yup::ComponentNative::getBounds () const pure virtual
Gets the bounds of the window.
Returns
The current window bounds.
References getBounds().
Referenced by getBounds().
setBounds()
virtual void yup::ComponentNative::setBounds (const Rectangle< int > & newBounds) pure virtual
Sets the bounds of the window.
Parameters
newBounds The new bounds to set.
References setBounds().
Referenced by setBounds().
setFullScreen()
virtual void yup::ComponentNative::setFullScreen (bool shouldBeFullScreen) pure virtual
Sets whether the window should be in fullscreen mode.
Parameters
shouldBeFullScreen True to make the window fullscreen, false to exit fullscreen.
References setFullScreen().
Referenced by setFullScreen().
isFullScreen()
virtual bool yup::ComponentNative::isFullScreen () const pure virtual
Checks whether the window is currently in fullscreen mode.
Returns
True if the window is fullscreen, false otherwise.
References isFullScreen().
Referenced by isFullScreen().
isDecorated()
virtual bool yup::ComponentNative::isDecorated () const pure virtual
Checks whether the window has decorations.
Returns
True if the window has decorations, false otherwise.
References isDecorated().
Referenced by isDecorated().
setOpacity()
virtual void yup::ComponentNative::setOpacity (float opacity) pure virtual
Sets the opacity of the window.
Parameters
opacity The opacity value, where 0.0 is fully transparent and 1.0 is fully opaque.
References setOpacity().
Referenced by setOpacity().
getOpacity()
virtual float yup::ComponentNative::getOpacity () const pure virtual
Gets the current opacity of the window.
Returns
The current opacity value.
References getOpacity().
Referenced by getOpacity().
setFocusedComponent()
virtual void yup::ComponentNative::setFocusedComponent (Component * comp) pure virtual
Sets the focused component.
Parameters
comp The component to focus, or nullptr to clear focus.
References setFocusedComponent().
Referenced by setFocusedComponent().
getFocusedComponent()
virtual Component * yup::ComponentNative::getFocusedComponent () const pure virtual
Gets the currently focused component.
Returns
The currently focused component, or nullptr if no component has focus.
References getFocusedComponent().
Referenced by getFocusedComponent().
isContinuousRepaintingEnabled()
virtual bool yup::ComponentNative::isContinuousRepaintingEnabled () const pure virtual
Checks whether continuous repainting is enabled.
Returns
True if continuous repainting is enabled, false otherwise.
References isContinuousRepaintingEnabled().
Referenced by isContinuousRepaintingEnabled().
enableContinuousRepainting()
virtual void yup::ComponentNative::enableContinuousRepainting (bool shouldBeEnabled) pure virtual
Enables or disables continuous repainting.
Parameters
shouldBeEnabled True to enable continuous repainting, false to disable.
References enableContinuousRepainting().
Referenced by enableContinuousRepainting().
isAtomicModeEnabled()
virtual bool yup::ComponentNative::isAtomicModeEnabled () const pure virtual
Checks whether atomic mode is enabled.
Returns
True if atomic mode is enabled, false otherwise.
References isAtomicModeEnabled().
Referenced by isAtomicModeEnabled().
enableAtomicMode()
virtual void yup::ComponentNative::enableAtomicMode (bool shouldBeEnabled) pure virtual
Enables or disables atomic mode.
Parameters
shouldBeEnabled True to enable atomic mode, false to disable.
References enableAtomicMode().
Referenced by enableAtomicMode().
isWireframeEnabled()
virtual bool yup::ComponentNative::isWireframeEnabled () const pure virtual
Checks whether wireframe mode is enabled.
Returns
True if wireframe mode is enabled, false otherwise.
References isWireframeEnabled().
Referenced by isWireframeEnabled().
enableWireframe()
virtual void yup::ComponentNative::enableWireframe (bool shouldBeEnabld) pure virtual
Enables or disables wireframe mode.
Parameters
shouldBeEnabld True to enable wireframe mode, false to disable.
References enableWireframe().
Referenced by enableWireframe().
repaint() [1/2]
virtual void yup::ComponentNative::repaint () pure virtual
Requests a repaint of the entire component.
References repaint().
Referenced by repaint(), and repaint().
repaint() [2/2]
virtual void yup::ComponentNative::repaint (const Rectangle< float > & rect) pure virtual
Requests a repaint of a specific area of the component.
Parameters
rect The area to repaint.
References repaint().
getRepaintAreas()
virtual const RectangleList< float > & yup::ComponentNative::getRepaintAreas () const pure virtual
Gets the list of areas that are currently scheduled for repainting.
Returns
The list of areas scheduled for repainting.
References getRepaintAreas().
Referenced by getRepaintAreas().
getScaleDpi()
virtual float yup::ComponentNative::getScaleDpi () const pure virtual
Gets the DPI scale factor.
Returns
The current DPI scale factor.
References getScaleDpi().
Referenced by getScaleDpi().
getCurrentFrameRate()
virtual float yup::ComponentNative::getCurrentFrameRate () const pure virtual
Gets the current framerate.
Returns
The current framerate in frames per second.
References getCurrentFrameRate().
Referenced by getCurrentFrameRate().
getDesiredFrameRate()
virtual float yup::ComponentNative::getDesiredFrameRate () const pure virtual
Gets the desired framerate.
Returns
The desired framerate in frames per second.
References getDesiredFrameRate().
Referenced by getDesiredFrameRate().
getNativeHandle()
virtual void * yup::ComponentNative::getNativeHandle () const pure virtual
Gets the native handle for the component.
Returns
The native handle as a void pointer.
References getNativeHandle().
Referenced by getNativeHandle().
getFactory()
virtual rive::Factory * yup::ComponentNative::getFactory () pure virtual
Gets the Rive factory associated with this component.
Returns
The Rive factory instance.
References getFactory().
Referenced by getFactory().
createFor()
std::unique_ptr< ComponentNative > yup::ComponentNative::createFor (Component & component, const Options & options, void * parent) static
Creates a platform-specific ComponentNative instance.
This factory method creates an appropriate ComponentNative implementation based on the current platform and the provided options.
Parameters
component The Component to associate with the native component.
options The options to configure the native component.
parent Optional pointer to a parent native window, or nullptr for a top-level window.
Returns
A unique_ptr to the created ComponentNative instance.
References component, ComponentNative(), and createFor().
Referenced by yup::Component::addToDesktop(), and createFor().
Member Data Documentation
noFlags
Flags yup::ComponentNative::noFlags = Flags() static constexpr
No flags set.
decoratedWindow
Flags yup::ComponentNative::decoratedWindow = Flags::declareValue<decoratedWindowTag>() static constexpr
Flag to enable window decorations (title bar, borders, etc.).
Referenced by yup::ComponentNative::Options::withDecoration().
resizableWindow
Flags yup::ComponentNative::resizableWindow = Flags::declareValue<resizableWindowTag>() static constexpr
Flag to enable window resizing by the user.
Referenced by yup::ComponentNative::Options::withResizableWindow().
renderContinuous
Flags yup::ComponentNative::renderContinuous = Flags::declareValue<renderContinuousTag>() static constexpr
Flag to enable continuous rendering mode.
Referenced by yup::ComponentNative::Options::withRenderContinuous().
allowHighDensityDisplay
Flags yup::ComponentNative::allowHighDensityDisplay = Flags::declareValue<allowHighDensityDisplayTag>() static constexpr
Flag to enable high-density display support.
Referenced by yup::ComponentNative::Options::withAllowedHighDensityDisplay().
defaultFlags
Flags yup::ComponentNative::defaultFlags = decoratedWindow | resizableWindow | allowHighDensityDisplay static constexpr
Default flags combining decoratedWindow, resizableWindow, and allowHighDensityDisplay.
component
Component& yup::ComponentNative::component protected
The Component associated with this native component.
Referenced by ComponentNative(), and createFor().
flags
Flags yup::ComponentNative::flags protected
The configuration flags for this native component.
Referenced by ComponentNative().