YUP: yup::ChildProcessCoordinator Class Reference
yup::ChildProcessCoordinator Class Reference
Acts as the coordinator in a coordinator/worker pair of connected processes.
Public Member Functions
ChildProcessCoordinator ()
Creates an uninitialised coordinator process object.
virtual ~ChildProcessCoordinator ()
Destructor.
bool launchWorkerProcess (const File &executableToLaunch, const String &commandLineUniqueID, int timeoutMs=0, int streamFlags=ChildProcess::wantStdOut|ChildProcess::wantStdErr)
Attempts to launch and connect to a worker process.
void killWorkerProcess ()
Sends a kill message to the worker, and disconnects from it.
virtual void handleMessageFromWorker (const MemoryBlock &)
This will be called to deliver a message from the worker process.
virtual void handleConnectionLost ()
This will be called when the worker process dies or is somehow disconnected.
bool sendMessageToWorker (const MemoryBlock &)
Attempts to send a message to the worker process.
Detailed Description
Acts as the coordinator in a coordinator/worker pair of connected processes.
The ChildProcessWorker and ChildProcessCoordinator classes make it easy for an app to spawn a child process, and to manage a 2-way messaging connection to control it.
To use the system, you need to create subclasses of both ChildProcessWorker and ChildProcessCoordinator. When you want your coordinator process to launch the worker, you just call launchWorkerProcess(), and it'll attempt to launch the executable that you specify (which may be the same exe), and assuming it has been set-up to correctly parse the command-line parameters (see ChildProcessWorker) then a two-way connection will be created.
See also
ChildProcessWorker, InterprocessConnection, ChildProcess
Constructor & Destructor Documentation
ChildProcessCoordinator()
yup::ChildProcessCoordinator::ChildProcessCoordinator () default
Creates an uninitialised coordinator process object.
Use launchWorkerProcess to launch and connect to a child process.
References ChildProcessCoordinator(), handleConnectionLost(), handleMessageFromWorker(), killWorkerProcess(), launchWorkerProcess(), sendMessageToWorker(), yup::ChildProcess::wantStdErr, and yup::ChildProcess::wantStdOut.
Referenced by ChildProcessCoordinator().
~ChildProcessCoordinator()
yup::ChildProcessCoordinator::~ChildProcessCoordinator () virtual
Destructor.
Note that the destructor calls killWorkerProcess(), but doesn't wait for the child process to finish terminating.
References killWorkerProcess().
Member Function Documentation
launchWorkerProcess()
bool yup::ChildProcessCoordinator::launchWorkerProcess (const File & executableToLaunch, const String & commandLineUniqueID, int timeoutMs = 0, int streamFlags = ChildProcess::wantStdOut | ChildProcess::wantStdErr)
Attempts to launch and connect to a worker process.
This will start the given executable, passing it a special command-line parameter based around the commandLineUniqueID string, which must be a short alphanumeric string (no spaces!) that identifies your app. The exe that gets launched must respond by calling ChildProcessWorker::initialiseFromCommandLine() in its startup code, and must use a matching ID to commandLineUniqueID.
The timeoutMs parameter lets you specify how long the child process is allowed to go without sending a ping before it is considered to have died and handleConnectionLost() will be called. Passing <= 0 for this timeout makes it use a default value.
If this all works, the method returns true, and you can begin sending and receiving messages with the worker process.
If a child process is already running, this will call killWorkerProcess() and start a new one.
References yup::StringArray::add(), yup::defaultTimeoutMs, yup::File::getFullPathName(), yup::SystemStats::getOperatingSystemType(), killWorkerProcess(), yup::SystemStats::Linux, sendMessageToWorker(), yup::specialMessageSize, and yup::String::toHexString().
Referenced by ChildProcessCoordinator().
killWorkerProcess()
void yup::ChildProcessCoordinator::killWorkerProcess ()
Sends a kill message to the worker, and disconnects from it.
Note that this won't wait for it to terminate.
References sendMessageToWorker(), and yup::specialMessageSize.
Referenced by ChildProcessCoordinator(), launchWorkerProcess(), and ~ChildProcessCoordinator().
handleMessageFromWorker()
void yup::ChildProcessCoordinator::handleMessageFromWorker (const MemoryBlock & mb) virtual
This will be called to deliver a message from the worker process.
The call will probably be made on a background thread, so be careful with your thread-safety!
Referenced by ChildProcessCoordinator().
handleConnectionLost()
void yup::ChildProcessCoordinator::handleConnectionLost () virtual
This will be called when the worker process dies or is somehow disconnected.
The call will probably be made on a background thread, so be careful with your thread-safety!
Referenced by ChildProcessCoordinator().
sendMessageToWorker()
bool yup::ChildProcessCoordinator::sendMessageToWorker (const MemoryBlock & mb)
Attempts to send a message to the worker process.
This returns true if the message was dispatched, but doesn't check that it actually gets delivered at the other end. If successful, the data will emerge in a call to your ChildProcessWorker::handleMessageFromCoordinator().
Referenced by ChildProcessCoordinator(), killWorkerProcess(), and launchWorkerProcess().