YUP: yup::MemoryMappedFile Class Reference
yup::MemoryMappedFile Class Reference
Maps a file into virtual memory for easy reading and/or writing.
Public Types
enum AccessMode { readOnly , readWrite }
The read/write flags used when opening a memory mapped file.
Public Member Functions
MemoryMappedFile (const File &file, AccessMode mode, bool exclusive=false)
Opens a file and maps it to an area of virtual memory.
MemoryMappedFile (const File &file, const Range< int64 > &fileRange, AccessMode mode, bool exclusive=false)
Opens a section of a file and maps it to an area of virtual memory.
~MemoryMappedFile ()
Destructor.
void * getData () const noexcept
Returns the address at which this file has been mapped, or a null pointer if the file couldn't be successfully mapped.
size_t getSize () const noexcept
Returns the number of bytes of data that are available for reading or writing.
Range< int64 > getRange () const noexcept
Returns the section of the file at which the mapped memory represents.
Detailed Description
Maps a file into virtual memory for easy reading and/or writing.
Member Enumeration Documentation
AccessMode
enum yup::MemoryMappedFile::AccessMode
The read/write flags used when opening a memory mapped file.
Enumerator
readOnly
Indicates that the memory can only be read.
readWrite
Indicates that the memory can be read and written to - changes that are made will be flushed back to disk at the whim of the OS.
Constructor & Destructor Documentation
MemoryMappedFile() [1/2]
yup::MemoryMappedFile::MemoryMappedFile (const File & file, MemoryMappedFile::AccessMode mode, bool exclusive = false)
Opens a file and maps it to an area of virtual memory.
The file should already exist, and should already be the size that you want to work with when you call this. If the file is resized after being opened, the behaviour is undefined.
If the file exists and the operation succeeds, the getData() and getSize() methods will return the location and size of the data that can be read or written. Note that the entire file is not read into memory immediately - the OS simply creates a virtual mapping, which will lazily pull the data into memory when blocks are accessed.
If the file can't be opened for some reason, the getData() method will return a null pointer.
If exclusive is false then other apps can also open the same memory mapped file and use this mapping as an effective way of communicating. If exclusive is true then the mapped file will be opened exclusively - preventing other apps to access the file which may improve the performance of accessing the file.
References yup::exclusive, and getSize().
MemoryMappedFile() [2/2]
yup::MemoryMappedFile::MemoryMappedFile (const File & file, const Range< int64 > & fileRange, AccessMode mode, bool exclusive = false)
Opens a section of a file and maps it to an area of virtual memory.
The file should already exist, and should already be the size that you want to work with when you call this. If the file is resized after being opened, the behaviour is undefined.
If the file exists and the operation succeeds, the getData() and getSize() methods will return the location and size of the data that can be read or written. Note that the entire file is not read into memory immediately - the OS simply creates a virtual mapping, which will lazily pull the data into memory when blocks are accessed.
If the file can't be opened for some reason, the getData() method will return a null pointer.
NOTE: The start of the actual range used may be rounded-down to a multiple of the OS's page-size, so do not assume that the mapped memory will begin at exactly the position you requested - always use getRange() to check the actual range that is being used.
References yup::exclusive, and getSize().
~MemoryMappedFile()
yup::MemoryMappedFile::~MemoryMappedFile ()
Destructor.
Member Function Documentation
getData()
void * yup::MemoryMappedFile::getData () const noexcept
Returns the address at which this file has been mapped, or a null pointer if the file couldn't be successfully mapped.
getSize()
size_t yup::MemoryMappedFile::getSize () const noexcept
Returns the number of bytes of data that are available for reading or writing.
This will normally be the size of the file.
Referenced by MemoryMappedFile(), and MemoryMappedFile().
getRange()
Range< int64 > yup::MemoryMappedFile::getRange () const noexcept
Returns the section of the file at which the mapped memory represents.