YUP: yup::TextEditor Class Reference
yup::TextEditor Class Reference
A component that allows editing text with cursor movement and selection.
Classes
struct Colors
Color identifiers used by the text editor.
Public Member Functions
TextEditor (StringRef componentID={})
Creates a text editor with an optional component ID.
String getText () const
Returns the editor's current text.
void setText (String newText, NotificationType notification=sendNotification)
Changes the editor's text.
void insertText (const String &textToInsert, NotificationType notification=sendNotification)
Inserts text at the current caret position.
bool isMultiLine () const noexcept
Returns whether this editor supports multiple lines.
void setMultiLine (bool shouldBeMultiLine)
Sets whether this editor should support multiple lines.
bool isReadOnly () const noexcept
Returns whether the editor is read-only.
void setReadOnly (bool shouldBeReadOnly)
Sets whether the editor should be read-only.
int getCaretPosition () const noexcept
Returns the current caret position in the text.
void setCaretPosition (int newPosition)
Sets the caret position.
bool isCaretVisible () const noexcept
Returns whether the caret is visible.
void moveCaretUp (bool extendSelection=false)
Moves the caret up.
void moveCaretDown (bool extendSelection=false)
Moves the caret down.
void moveCaretLeft (bool extendSelection=false)
Moves the caret left.
void moveCaretRight (bool extendSelection=false)
Moves the caret right.
void moveCaretToStartOfLine (bool extendSelection=false)
Moves the caret to the start of the line.
void moveCaretToEndOfLine (bool extendSelection=false)
Moves the caret to the end of the line.
void moveCaretToStart (bool extendSelection=false)
Moves the caret to the start of the text.
void moveCaretToEnd (bool extendSelection=false)
Moves the caret to the end of the text.
Range< int > getSelection () const
Gets the current selection range.
void setSelection (const Range< int > &newSelection)
Sets the selection range.
void selectAll ()
Selects all text in the editor.
bool hasSelection () const
Returns true if any text is currently selected.
std::vector< Rectangle< float > > getSelectedTextAreas () const
Returns the selection rectangles, usable for knowing where the selection is.
String getSelectedText () const
Returns the currently selected text.
void deleteSelectedText (NotificationType notification=sendNotification)
Deletes the currently selected text.
void copy ()
Copies the selected text to the clipboard.
void cut ()
Cuts the selected text to the clipboard.
void paste ()
Pastes text from the clipboard at the current caret position.
std::optional< Font > getFont () const
Returns the current font.
void setFont (Font newFont)
Sets the font to use.
void resetFont ()
Reset the font to the theme one.
std::optional< float > getFontSize () const
Returns the current font size.
void setFontSize (float newFontSize)
Sets the font size.
void resetFontSize ()
Reset the font size to the theme one.
Rectangle< float > getTextBounds () const
Returns the bounds of the text.
Rectangle< float > getCaretBounds () const
Returns the bounds of the caret.
Point< float > getScrollOffset () const noexcept
Get the scroll offset.
void paint (Graphics &g) override
Paint the component.
void resized () override
Called when the size of the component changes.
void focusGained () override
Called when the component gains focus.
void focusLost () override
Called when the component loses focus.
void mouseDown (const MouseEvent &event) override
Called when the mouse button is pressed.
void mouseDrag (const MouseEvent &event) override
Called when the mouse is dragged.
void mouseUp (const MouseEvent &event) override
Called when the mouse button is released.
void mouseDoubleClick (const MouseEvent &event) override
Called when the mouse button is double clicked.
void keyDown (const KeyPress &key, const Point< float > &position) override
Called when a key is pressed.
void textInput (const String &text) override
Called when text is input.
StyledText & getStyledText () const noexcept
Public Member Functions inherited from yup::Component
Component ()
Constructor for the Component class.
Component (StringRef componentID)
Constructor for the Component class.
virtual ~Component ()
Destructor for the Component class.
String getComponentID () const
Get the ID of the component.
bool isEnabled () const
Check if the component is enabled.
void setEnabled (bool shouldBeEnabled)
Set the enabled state of the component.
virtual void enablementChanged ()
Called when the enabled state of the component changes.
bool isVisible () const
Check if the component is visible.
void setVisible (bool shouldBeVisible)
Set the visible state of the component.
bool isShowing () const
Check if the component is showing.
virtual void visibilityChanged ()
Called when the visible state of the component changes.
String getTitle () const
Get the title of the component.
void setTitle (const String &title)
Set the title of the component.
Point< float > getPosition () const
Get the position of the component relative to its parent.
void setPosition (const Point< float > &newPosition)
Set the position of the component relative to its parent.
float getX () const
Get the x position of the component relative to its parent.
float getY () const
Get the y position of the component relative to its parent.
float getLeft () const
Get the left position of the component relative to its parent.
float getTop () const
Get the top position of the component relative to its parent.
float getRight () const
Get the right position of the component relative to its parent.
float getBottom () const
Get the bottom position of the component relative to its parent.
Point< float > getTopLeft () const
void setTopLeft (const Point< float > &newTopLeft)
Point< float > getBottomLeft () const
void setBottomLeft (const Point< float > &newBottomLeft)
Point< float > getTopRight () const
void setTopRight (const Point< float > &newTopRight)
Point< float > getBottomRight () const
void setBottomRight (const Point< float > &newBottomRight)
Point< float > getCenter () const
void setCenter (const Point< float > &newCenter)
float getCenterX () const
void setCenterX (float newCenterX)
float getCenterY () const
void setCenterY (float newCenterY)
virtual void moved ()
Called when the position of the component changes.
Size< float > getSize () const
Get the size of the component.
void setSize (const Size< float > &newSize)
Set the size of the component.
float getWidth () const
Get the width of the component.
float getHeight () const
Get the height of the component.
float proportionOfWidth (float proportion) const
Get the width of the component as a proportion of the parent's width.
float proportionOfHeight (float proportion) const
Get the height of the component as a proportion of the parent's height.
void setBounds (const Rectangle< float > &newBounds)
Set the bounds of the component.
Rectangle< float > getBounds () const
Get the bounds of the component, relative to its parent.
Rectangle< float > getLocalBounds () const
Get the local bounds of the component, with zero position.
Rectangle< float > getBoundsRelativeToTopLevelComponent () const
Get the bounds of the component relative to its top level component.
void setTransform (const AffineTransform &transform)
AffineTransform getTransform () const
bool isTransformed () const
virtual void transformChanged ()
void setFullScreen (bool shouldBeFullScreen)
Set the full screen state of the component.
bool isFullScreen () const
Check if the component is full screen.
virtual void displayChanged ()
Called when the component changes display.
float getScaleDpi () const
Get the scale factor of the component.
virtual void contentScaleChanged (float dpiScale)
Called when the content scale of the component changes.
float getOpacity () const
Get the opacity of the component.
void setOpacity (float opacity)
Set the opacity of the component.
virtual void enableRenderingUnclipped (bool shouldBeEnabled)
Enable or disable unclipped rendering for the component.
bool isRenderingUnclipped () const
Check if the component is rendering unclipped.
void repaint ()
Repaint the component.
void repaint (const Rectangle< float > &rect)
Repaint the component.
void * getNativeHandle () const
Get the native handle of the component.
ComponentNative * getNativeComponent ()
Get the native component of the component.
const ComponentNative * getNativeComponent () const
Get the native component of the component.
virtual void attachedToNative ()
Called when this component is attached to a native window.
virtual void detachedFromNative ()
Called when this component is detached from its native window.
bool isOnDesktop () const
Check if the component is on the desktop.
void addToDesktop (const ComponentNative::Options &nativeOptions, void *parent=nullptr)
Add the component to the desktop.
void removeFromDesktop ()
Remove the component from the desktop.
virtual void userTriedToCloseWindow ()
Called when the user tries to close the window.
void toFront (bool shouldGainKeyboardFocus)
Bring the component to the front.
void toBack ()
Bring the component to the back.
void raiseAbove (Component *component)
Raises this component above the specified component in the z-order.
void lowerBelow (Component *component)
Lowers this component below the specified component in the z-order.
void raiseBy (int indexToRaise)
Raises this component by a number of positions in the z-order.
void lowerBy (int indexToLower)
Lowers this component by a number of positions in the z-order.
void setMouseCursor (const MouseCursor &cursorType)
Set the mouse cursor of the component.
virtual MouseCursor getMouseCursor () const
Get the mouse cursor of the component.
void setWantsKeyboardFocus (bool wantsFocus)
Set if the component wants keyboard focus.
void takeKeyboardFocus ()
Take the focus.
void leaveKeyboardFocus ()
Leave the focus.
bool hasKeyboardFocus () const
Check if the component has focus.
Component * getParentComponent ()
Get the parent of the component.
const Component * getParentComponent () const
Get the parent of the component.
template<class T>
T * getParentComponentWithType ()
Get the parent of the component of a given type.
template<class T>
const T * getParentComponentWithType () const
Get the parent of the component of a given type.
void addChildComponent (Component &component, int index=-1)
Add a child component to the component.
void addChildComponent (Component *component, int index=-1)
Add a child component to the component.
void addAndMakeVisible (Component &component, int index=-1)
Add a child component to the component and make it visible.
void addAndMakeVisible (Component *component, int index=-1)
Add a child component to the component and make it visible.
void removeChildComponent (Component &component)
Remove a child component from the component.
void removeChildComponent (Component *component)
Remove a child component from the component.
void removeChildComponent (int index)
Remove a child component from the component at a specified index.
void removeAllChildren ()
Removes all child components from this component.
virtual void parentHierarchyChanged ()
Called when the parent hierarchy of this component changes.
virtual void childrenChanged ()
Called when the child components of this component change.
int getNumChildComponents () const
Get the number of child components of the component.
Component * getComponentAt (int index) const
Get the child component at a given index.
int getIndexOfChildComponent (Component *component) const
Returns the index of a child component, or -1 if not found.
Component * findComponentAt (const Point< float > &p)
Find the child component at a given point.
Component * getTopLevelComponent ()
Returns the top level component.
NamedValueSet & getProperties ()
Get the properties of the component.
const NamedValueSet & getProperties () const
Get the properties of the component.
virtual void paintOverChildren (Graphics &g)
Paint the component over its children.
virtual void refreshDisplay (double lastFrameTimeSeconds)
Refresh the display of the component.
virtual void mouseEnter (const MouseEvent &event)
Called when the mouse enters the component.
virtual void mouseExit (const MouseEvent &event)
Called when the mouse exits the component.
virtual void mouseMove (const MouseEvent &event)
Called when the mouse is moved.
virtual void mouseWheel (const MouseEvent &event, const MouseWheelData &wheelData)
Called when the mouse wheel is scrolled.
void addMouseListener (MouseListener *listener)
Add a mouse listener to the component.
void removeMouseListener (MouseListener *listener)
Remove a mouse listener from the component.
virtual void keyUp (const KeyPress &keys, const Point< float > &position)
Called when a key is released.
void setStyle (ComponentStyle::Ptr newStyle)
Sets the style for this component.
ComponentStyle::Ptr getStyle () const
Returns the current style of this component.
virtual void styleChanged ()
Called when the component's style changes.
void setColor (const Identifier &colorId, const std::optional< Color > &color)
Set a color for the component.
std::optional< Color > getColor (const Identifier &colorId) const
Get the color of the component.
std::optional< Color > findColor (const Identifier &colorId) const
Find the color of the component.
Public Attributes
std::function< void()> onTextChange
Sets a callback function to be called when the text changes.
Detailed Description
A component that allows editing text with cursor movement and selection.
The TextEditor component provides a complete text editing interface including:
Single line and multiline text editing
Cursor movement using arrow keys and mouse clicks
Text selection using mouse drag or shift+arrow keys
Copy, cut, and paste operations
Customizable styling through ApplicationTheme
Example usage:
auto editor = std::make_unique<TextEditor>("myEditor");
editor->setText("Hello World");
editor->setMultiLine(true);
editor->setBounds(10, 10, 200, 100);
addAndMakeVisible(*editor);
See also
Component, StyledText
Constructor & Destructor Documentation
TextEditor()
yup::TextEditor::TextEditor (StringRef componentID = {})
Creates a text editor with an optional component ID.
References yup::Component::Component(), yup::dontSendNotification, yup::Component::setMouseCursor(), setText(), yup::Component::setWantsKeyboardFocus(), yup::MouseCursor::Text, and TextEditor().
Referenced by TextEditor().
Member Function Documentation
getText()
String yup::TextEditor::getText () const
Returns the editor's current text.
Returns
The text currently displayed in the editor
setText()
void yup::TextEditor::setText (String newText, NotificationType notification = sendNotification)
Changes the editor's text.
Parameters
newText The new text to display
notification Whether to trigger a change notification
References yup::jmin(), onTextChange, yup::Component::repaint(), and yup::sendNotification.
Referenced by TextEditor().
insertText()
void yup::TextEditor::insertText (const String & textToInsert, NotificationType notification = sendNotification)
Inserts text at the current caret position.
Parameters
textToInsert The text to insert
notification Whether to trigger a change notification
References deleteSelectedText(), yup::String::length(), onTextChange, yup::Component::repaint(), yup::String::replaceCharacters(), yup::sendNotification, and yup::String::substring().
Referenced by keyDown(), paste(), and textInput().
isMultiLine()
bool yup::TextEditor::isMultiLine () const noexcept
Returns whether this editor supports multiple lines.
Returns
True if multiline editing is enabled
setMultiLine()
void yup::TextEditor::setMultiLine (bool shouldBeMultiLine)
Sets whether this editor should support multiple lines.
Parameters
shouldBeMultiLine True to enable multiline editing
References yup::Component::repaint().
isReadOnly()
bool yup::TextEditor::isReadOnly () const noexcept
Returns whether the editor is read-only.
Returns
True if the editor is read-only
setReadOnly()
void yup::TextEditor::setReadOnly (bool shouldBeReadOnly)
Sets whether the editor should be read-only.
Parameters
shouldBeReadOnly True to make the editor read-only
References yup::MouseCursor::Default, yup::Component::setMouseCursor(), and yup::MouseCursor::Text.
getCaretPosition()
int yup::TextEditor::getCaretPosition () const noexcept
Returns the current caret position in the text.
Returns
The character index of the caret position
setCaretPosition()
void yup::TextEditor::setCaretPosition (int newPosition)
Sets the caret position.
Parameters
newPosition The new character index for the caret
References yup::jlimit(), and yup::Component::repaint().
isCaretVisible()
bool yup::TextEditor::isCaretVisible () const noexcept
Returns whether the caret is visible.
Referenced by yup::paintTextEditor().
moveCaretUp()
void yup::TextEditor::moveCaretUp (bool extendSelection = false)
Moves the caret up.
Parameters
extendSelection Whether to extend the selection to the caret position
References getCaretBounds(), getTextBounds(), yup::jlimit(), and moveCaretToStart().
Referenced by keyDown().
moveCaretDown()
void yup::TextEditor::moveCaretDown (bool extendSelection = false)
Moves the caret down.
Parameters
extendSelection Whether to extend the selection to the caret position
References getCaretBounds(), getTextBounds(), yup::jlimit(), and moveCaretToEnd().
Referenced by keyDown().
moveCaretLeft()
void yup::TextEditor::moveCaretLeft (bool extendSelection = false)
Moves the caret left.
Parameters
extendSelection Whether to extend the selection to the caret position
Referenced by keyDown().
moveCaretRight()
void yup::TextEditor::moveCaretRight (bool extendSelection = false)
Moves the caret right.
Parameters
extendSelection Whether to extend the selection to the caret position
Referenced by keyDown().
moveCaretToStartOfLine()
void yup::TextEditor::moveCaretToStartOfLine (bool extendSelection = false)
Moves the caret to the start of the line.
Parameters
extendSelection Whether to extend the selection to the caret position
Referenced by keyDown().
moveCaretToEndOfLine()
void yup::TextEditor::moveCaretToEndOfLine (bool extendSelection = false)
Moves the caret to the end of the line.
Parameters
extendSelection Whether to extend the selection to the caret position
Referenced by keyDown().
moveCaretToStart()
void yup::TextEditor::moveCaretToStart (bool extendSelection = false)
Moves the caret to the start of the text.
Parameters
extendSelection Whether to extend the selection to the caret position
Referenced by keyDown(), and moveCaretUp().
moveCaretToEnd()
void yup::TextEditor::moveCaretToEnd (bool extendSelection = false)
Moves the caret to the end of the text.
Parameters
extendSelection Whether to extend the selection to the caret position
Referenced by keyDown(), and moveCaretDown().
getSelection()
Range< int > yup::TextEditor::getSelection () const
Gets the current selection range.
Returns
A Range indicating the selected text (start, length)
References yup::end(), yup::jmax(), and yup::jmin().
setSelection()
void yup::TextEditor::setSelection (const Range< int > & newSelection)
Sets the selection range.
Parameters
newSelection The new selection range
References yup::end(), yup::Range< ValueType >::getEnd(), yup::Range< ValueType >::getStart(), yup::jlimit(), and yup::Component::repaint().
Referenced by selectAll().
selectAll()
void yup::TextEditor::selectAll ()
Selects all text in the editor.
References setSelection().
Referenced by keyDown(), and mouseDoubleClick().
hasSelection()
bool yup::TextEditor::hasSelection () const
Returns true if any text is currently selected.
Referenced by copy(), cut(), deleteSelectedText(), getSelectedText(), and yup::paintTextEditor().
getSelectedTextAreas()
std::vector< Rectangle< float > > yup::TextEditor::getSelectedTextAreas () const
Returns the selection rectangles, usable for knowing where the selection is.
References yup::end(), yup::jmax(), and yup::jmin().
Referenced by yup::paintTextEditor().
getSelectedText()
String yup::TextEditor::getSelectedText () const
Returns the currently selected text.
Returns
The selected text as a String
References yup::end(), hasSelection(), yup::jmax(), and yup::jmin().
Referenced by copy().
deleteSelectedText()
void yup::TextEditor::deleteSelectedText (NotificationType notification = sendNotification)
Deletes the currently selected text.
Parameters
notification Whether to trigger a change notification
References yup::end(), hasSelection(), yup::jmax(), yup::jmin(), onTextChange, yup::Component::repaint(), and yup::sendNotification.
Referenced by cut(), and insertText().
copy()
void yup::TextEditor::copy ()
Copies the selected text to the clipboard.
References yup::SystemClipboard::copyTextToClipboard(), getSelectedText(), and hasSelection().
Referenced by cut(), and keyDown().
cut()
void yup::TextEditor::cut ()
Cuts the selected text to the clipboard.
References copy(), deleteSelectedText(), and hasSelection().
Referenced by keyDown().
paste()
void yup::TextEditor::paste ()
Pastes text from the clipboard at the current caret position.
References yup::SystemClipboard::getTextFromClipboard(), insertText(), and yup::String::isNotEmpty().
Referenced by keyDown().
getFont()
std::optional< Font > yup::TextEditor::getFont () const
Returns the current font.
Returns
The font used to display the text
setFont()
void yup::TextEditor::setFont (Font newFont)
Sets the font to use.
Parameters
newFont The new font to use
References yup::Component::repaint().
resetFont()
void yup::TextEditor::resetFont ()
Reset the font to the theme one.
References yup::Component::repaint().
getFontSize()
std::optional< float > yup::TextEditor::getFontSize () const
Returns the current font size.
setFontSize()
void yup::TextEditor::setFontSize (float newFontSize)
Sets the font size.
Parameters
newFontSize The new font size to use
References yup::approximatelyEqual(), and yup::Component::repaint().
resetFontSize()
void yup::TextEditor::resetFontSize ()
Reset the font size to the theme one.
References yup::Component::repaint().
getTextBounds()
Rectangle< float > yup::TextEditor::getTextBounds () const
Returns the bounds of the text.
References yup::Component::getLocalBounds(), and yup::Rectangle< ValueType >::reduced().
Referenced by getCaretBounds(), moveCaretDown(), moveCaretUp(), and yup::paintTextEditor().
getCaretBounds()
Rectangle< float > yup::TextEditor::getCaretBounds () const
Returns the bounds of the caret.
References getTextBounds().
Referenced by moveCaretDown(), moveCaretUp(), and yup::paintTextEditor().
getScrollOffset()
Point< float > yup::TextEditor::getScrollOffset () const noexcept
Get the scroll offset.
Referenced by yup::paintTextEditor().
paint()
void yup::TextEditor::paint (Graphics & g) override virtual
Paint the component.
Parameters
g The graphics context to paint the component on.
Reimplemented from yup::Component.
References yup::ApplicationTheme::findComponentStyle(), and yup::ApplicationTheme::getGlobalTheme().
resized()
void yup::TextEditor::resized () override virtual
Called when the size of the component changes.
Reimplemented from yup::Component.
focusGained()
void yup::TextEditor::focusGained () override virtual
Called when the component gains focus.
Reimplemented from yup::Component.
References yup::Component::repaint().
focusLost()
void yup::TextEditor::focusLost () override virtual
Called when the component loses focus.
Reimplemented from yup::Component.
References yup::Component::repaint().
mouseDown()
void yup::TextEditor::mouseDown (const MouseEvent & event) override virtual
Called when the mouse button is pressed.
Parameters
event The mouse event.
Reimplemented from yup::Component.
References yup::MouseEvent::getModifiers(), yup::Component::hasKeyboardFocus(), yup::KeyModifiers::isShiftDown(), yup::Component::repaint(), and yup::Component::takeKeyboardFocus().
mouseDrag()
void yup::TextEditor::mouseDrag (const MouseEvent & event) override virtual
Called when the mouse is dragged.
Parameters
event The mouse event.
Reimplemented from yup::Component.
References yup::Component::repaint().
mouseUp()
void yup::TextEditor::mouseUp (const MouseEvent & event) override virtual
Called when the mouse button is released.
Parameters
event The mouse event.
Reimplemented from yup::Component.
mouseDoubleClick()
void yup::TextEditor::mouseDoubleClick (const MouseEvent & event) override virtual
Called when the mouse button is double clicked.
Parameters
event The mouse event.
Reimplemented from yup::Component.
References selectAll().
keyDown()
void yup::TextEditor::keyDown (const KeyPress & keys, const Point< float > & position) override virtual
Called when a key is pressed.
Parameters
keys The key press.
position The position of the key press.
Reimplemented from yup::Component.
References yup::KeyPress::backspaceKey, copy(), cut(), yup::KeyPress::deleteKey, yup::KeyPress::downKey, yup::KeyPress::endKey, yup::KeyPress::enterKey, yup::KeyPress::getKey(), yup::KeyPress::getModifiers(), yup::KeyPress::homeKey, insertText(), yup::KeyModifiers::isCommandDown(), yup::KeyModifiers::isControlDown(), yup::KeyModifiers::isShiftDown(), yup::KeyPress::leftKey, moveCaretDown(), moveCaretLeft(), moveCaretRight(), moveCaretToEnd(), moveCaretToEndOfLine(), moveCaretToStart(), moveCaretToStartOfLine(), moveCaretUp(), paste(), yup::Component::repaint(), yup::KeyPress::rightKey, selectAll(), yup::KeyPress::tabKey, yup::KeyPress::textAKey, yup::KeyPress::textCKey, yup::KeyPress::textVKey, yup::KeyPress::textXKey, and yup::KeyPress::upKey.
textInput()
void yup::TextEditor::textInput (const String & text) override virtual
Called when text is input.
Parameters
text The text input.
Reimplemented from yup::Component.
References insertText(), and yup::String::isNotEmpty().
getStyledText()
StyledText & yup::TextEditor::getStyledText () const noexcept
Referenced by yup::paintTextEditor().
Member Data Documentation
onTextChange
std::function<void()> yup::TextEditor::onTextChange
Sets a callback function to be called when the text changes.
Parameters
callback The function to call when text changes
Referenced by deleteSelectedText(), insertText(), and setText().