YUP: yup::AudioParameterBuilder Class Reference
yup::AudioParameterBuilder Class Reference
A builder class for constructing AudioProcessorParameter instances using a fluent-style API.
Public Member Functions
AudioParameterBuilder ()=default
Constructs a new AudioParameterBuilder.
AudioParameterBuilder & withID (const String &paramID)
Sets the parameter ID (used in the state tree and automation).
AudioParameterBuilder & withName (const String &paramName)
Sets the parameter display name.
AudioParameterBuilder & withRange (float minValue, float maxValue)
Sets the parameter's value range.
AudioParameterBuilder & withRange (NormalisableRange< float > valueRange)
Sets the parameter's value range.
AudioParameterBuilder & withDefault (float defaultValue)
Sets the parameter's default value.
AudioParameterBuilder & withValueToString (AudioParameter::ValueToString fn)
Sets the value-to-string display conversion function.
AudioParameterBuilder & withStringToValue (AudioParameter::StringToValue fn)
Sets the string-to-value parsing function.
AudioParameterBuilder & withSmoothing (float smoothingTimeMs)
Sets the smoothing time for the parameter.
AudioParameter::Ptr build () const
Finalizes the builder and returns a fully constructed AudioProcessorParameter instance.
Detailed Description
A builder class for constructing AudioProcessorParameter instances using a fluent-style API.
This class simplifies the creation of AudioProcessorParameter objects by allowing you to configure each aspect step-by-step, including type, range, mapping functions, string conversion, and optional smoothing.
Example:
auto gainParam = AudioParameterBuilder{}
    .withID ("gain")
    .withName ("Gain")
    .withRange (0.0f, 1.0f)
    .withDefault (0.5f)
    .withSmoothing (100.0f)
    .build();
See also
AudioProcessorParameter
Constructor & Destructor Documentation
AudioParameterBuilder()
yup::AudioParameterBuilder::AudioParameterBuilder () default
Constructs a new AudioParameterBuilder.
References AudioParameterBuilder().
Referenced by AudioParameterBuilder(), withDefault(), withID(), withName(), withRange(), withRange(), withSmoothing(), withStringToValue(), and withValueToString().
Member Function Documentation
withID()
AudioParameterBuilder & yup::AudioParameterBuilder::withID (const String & paramID)
Sets the parameter ID (used in the state tree and automation).
References AudioParameterBuilder().
withName()
AudioParameterBuilder & yup::AudioParameterBuilder::withName (const String & paramName)
Sets the parameter display name.
References AudioParameterBuilder().
withRange() [1/2]
AudioParameterBuilder & yup::AudioParameterBuilder::withRange (float minValue, float maxValue)
Sets the parameter's value range.
Parameters
min The minimum allowed value.
max The maximum allowed value.
References AudioParameterBuilder().
withRange() [2/2]
AudioParameterBuilder & yup::AudioParameterBuilder::withRange (NormalisableRange< float > valueRange)
Sets the parameter's value range.
Parameters
valueRange The allowed value range.
References AudioParameterBuilder().
withDefault()
AudioParameterBuilder & yup::AudioParameterBuilder::withDefault (float defaultValue)
Sets the parameter's default value.
Parameters
defaultVal The default value.
References AudioParameterBuilder().
withValueToString()
AudioParameterBuilder & yup::AudioParameterBuilder::withValueToString (AudioParameter::ValueToString fn)
Sets the value-to-string display conversion function.
References AudioParameterBuilder().
withStringToValue()
AudioParameterBuilder & yup::AudioParameterBuilder::withStringToValue (AudioParameter::StringToValue fn)
Sets the string-to-value parsing function.
References AudioParameterBuilder().
withSmoothing()
AudioParameterBuilder & yup::AudioParameterBuilder::withSmoothing (float smoothingTimeMs)
Sets the smoothing time for the parameter.
References AudioParameterBuilder().
build()
AudioParameter::Ptr yup::AudioParameterBuilder::build () const
Finalizes the builder and returns a fully constructed AudioProcessorParameter instance.
Returns
A shared_ptr to the constructed AudioProcessorParameter.