YUP: yup::Slider Class Reference
yup::Slider Class Reference
Public Member Functions
Slider (StringRef componentID)
void setValue (float newValue, NotificationType notification=sendNotification)
float getValue () const
void setValueNormalised (float newValue, NotificationType notification=sendNotification)
float getValueNormalised () const
virtual void valueChanged ()
bool isMouseOver () const
void setDefaultValue (float newDefaultValue)
float getDefaultValue () const
void setRange (const Range< float > &newRange)
Range< float > getRange () const
void resized () override
Called when the size of the component changes.
void paint (Graphics &g) override
Paint the component.
void mouseEnter (const MouseEvent &event) override
Called when the mouse enters the component.
void mouseExit (const MouseEvent &event) override
Called when the mouse exits the component.
void mouseDown (const MouseEvent &event) override
Called when the mouse button is pressed.
void mouseUp (const MouseEvent &event) override
Called when the mouse button is released.
void mouseDrag (const MouseEvent &event) override
Called when the mouse is dragged.
void mouseWheel (const MouseEvent &event, const MouseWheelData &data) override
Called when the mouse wheel is scrolled.
Public Member Functions inherited from yup::Component
Component ()
Constructor for the Component class.
Component (StringRef componentID)
Constructor for the Component class.
virtual ~Component ()
Destructor for the Component class.
String getComponentID () const
Get the ID of the component.
bool isEnabled () const
Check if the component is enabled.
void setEnabled (bool shouldBeEnabled)
Set the enabled state of the component.
virtual void enablementChanged ()
Called when the enabled state of the component changes.
bool isVisible () const
Check if the component is visible.
void setVisible (bool shouldBeVisible)
Set the visible state of the component.
bool isShowing () const
Check if the component is showing.
virtual void visibilityChanged ()
Called when the visible state of the component changes.
String getTitle () const
Get the title of the component.
void setTitle (const String &title)
Set the title of the component.
Point< float > getPosition () const
Get the position of the component relative to its parent.
void setPosition (const Point< float > &newPosition)
Set the position of the component relative to its parent.
float getX () const
Get the x position of the component relative to its parent.
float getY () const
Get the y position of the component relative to its parent.
float getLeft () const
Get the left position of the component relative to its parent.
float getTop () const
Get the top position of the component relative to its parent.
float getRight () const
Get the right position of the component relative to its parent.
float getBottom () const
Get the bottom position of the component relative to its parent.
Point< float > getTopLeft () const
void setTopLeft (const Point< float > &newTopLeft)
Point< float > getBottomLeft () const
void setBottomLeft (const Point< float > &newBottomLeft)
Point< float > getTopRight () const
void setTopRight (const Point< float > &newTopRight)
Point< float > getBottomRight () const
void setBottomRight (const Point< float > &newBottomRight)
Point< float > getCenter () const
void setCenter (const Point< float > &newCenter)
float getCenterX () const
void setCenterX (float newCenterX)
float getCenterY () const
void setCenterY (float newCenterY)
virtual void moved ()
Called when the position of the component changes.
Size< float > getSize () const
Get the size of the component.
void setSize (const Size< float > &newSize)
Set the size of the component.
float getWidth () const
Get the width of the component.
float getHeight () const
Get the height of the component.
float proportionOfWidth (float proportion) const
Get the width of the component as a proportion of the parent's width.
float proportionOfHeight (float proportion) const
Get the height of the component as a proportion of the parent's height.
void setBounds (const Rectangle< float > &newBounds)
Set the bounds of the component.
Rectangle< float > getBounds () const
Get the bounds of the component, relative to its parent.
Rectangle< float > getLocalBounds () const
Get the local bounds of the component, with zero position.
Rectangle< float > getBoundsRelativeToTopLevelComponent () const
Get the bounds of the component relative to its top level component.
void setTransform (const AffineTransform &transform)
AffineTransform getTransform () const
bool isTransformed () const
virtual void transformChanged ()
void setFullScreen (bool shouldBeFullScreen)
Set the full screen state of the component.
bool isFullScreen () const
Check if the component is full screen.
virtual void displayChanged ()
Called when the component changes display.
float getScaleDpi () const
Get the scale factor of the component.
virtual void contentScaleChanged (float dpiScale)
Called when the content scale of the component changes.
float getOpacity () const
Get the opacity of the component.
void setOpacity (float opacity)
Set the opacity of the component.
virtual void enableRenderingUnclipped (bool shouldBeEnabled)
Enable or disable unclipped rendering for the component.
bool isRenderingUnclipped () const
Check if the component is rendering unclipped.
void repaint ()
Repaint the component.
void repaint (const Rectangle< float > &rect)
Repaint the component.
void * getNativeHandle () const
Get the native handle of the component.
ComponentNative * getNativeComponent ()
Get the native component of the component.
const ComponentNative * getNativeComponent () const
Get the native component of the component.
virtual void attachedToNative ()
Called when this component is attached to a native window.
virtual void detachedFromNative ()
Called when this component is detached from its native window.
bool isOnDesktop () const
Check if the component is on the desktop.
void addToDesktop (const ComponentNative::Options &nativeOptions, void *parent=nullptr)
Add the component to the desktop.
void removeFromDesktop ()
Remove the component from the desktop.
virtual void userTriedToCloseWindow ()
Called when the user tries to close the window.
void toFront (bool shouldGainKeyboardFocus)
Bring the component to the front.
void toBack ()
Bring the component to the back.
void raiseAbove (Component *component)
Raises this component above the specified component in the z-order.
void lowerBelow (Component *component)
Lowers this component below the specified component in the z-order.
void raiseBy (int indexToRaise)
Raises this component by a number of positions in the z-order.
void lowerBy (int indexToLower)
Lowers this component by a number of positions in the z-order.
void setMouseCursor (const MouseCursor &cursorType)
Set the mouse cursor of the component.
virtual MouseCursor getMouseCursor () const
Get the mouse cursor of the component.
void setWantsKeyboardFocus (bool wantsFocus)
Set if the component wants keyboard focus.
void takeKeyboardFocus ()
Take the focus.
void leaveKeyboardFocus ()
Leave the focus.
bool hasKeyboardFocus () const
Check if the component has focus.
virtual void focusGained ()
Called when the component gains focus.
virtual void focusLost ()
Called when the component loses focus.
Component * getParentComponent ()
Get the parent of the component.
const Component * getParentComponent () const
Get the parent of the component.
template<class T>
T * getParentComponentWithType ()
Get the parent of the component of a given type.
template<class T>
const T * getParentComponentWithType () const
Get the parent of the component of a given type.
void addChildComponent (Component &component, int index=-1)
Add a child component to the component.
void addChildComponent (Component *component, int index=-1)
Add a child component to the component.
void addAndMakeVisible (Component &component, int index=-1)
Add a child component to the component and make it visible.
void addAndMakeVisible (Component *component, int index=-1)
Add a child component to the component and make it visible.
void removeChildComponent (Component &component)
Remove a child component from the component.
void removeChildComponent (Component *component)
Remove a child component from the component.
void removeChildComponent (int index)
Remove a child component from the component at a specified index.
void removeAllChildren ()
Removes all child components from this component.
virtual void parentHierarchyChanged ()
Called when the parent hierarchy of this component changes.
virtual void childrenChanged ()
Called when the child components of this component change.
int getNumChildComponents () const
Get the number of child components of the component.
Component * getComponentAt (int index) const
Get the child component at a given index.
int getIndexOfChildComponent (Component *component) const
Returns the index of a child component, or -1 if not found.
Component * findComponentAt (const Point< float > &p)
Find the child component at a given point.
Component * getTopLevelComponent ()
Returns the top level component.
NamedValueSet & getProperties ()
Get the properties of the component.
const NamedValueSet & getProperties () const
Get the properties of the component.
virtual void paintOverChildren (Graphics &g)
Paint the component over its children.
virtual void refreshDisplay (double lastFrameTimeSeconds)
Refresh the display of the component.
virtual void mouseMove (const MouseEvent &event)
Called when the mouse is moved.
virtual void mouseDoubleClick (const MouseEvent &event)
Called when the mouse button is double clicked.
void addMouseListener (MouseListener *listener)
Add a mouse listener to the component.
void removeMouseListener (MouseListener *listener)
Remove a mouse listener from the component.
virtual void keyDown (const KeyPress &keys, const Point< float > &position)
Called when a key is pressed.
virtual void keyUp (const KeyPress &keys, const Point< float > &position)
Called when a key is released.
virtual void textInput (const String &text)
Called when text is input.
void setStyle (ComponentStyle::Ptr newStyle)
Sets the style for this component.
ComponentStyle::Ptr getStyle () const
Returns the current style of this component.
virtual void styleChanged ()
Called when the component's style changes.
void setColor (const Identifier &colorId, const std::optional< Color > &color)
Set a color for the component.
std::optional< Color > getColor (const Identifier &colorId) const
Get the color of the component.
std::optional< Color > findColor (const Identifier &colorId) const
Find the color of the component.
Public Attributes
std::function< void(float)> onValueChanged
std::function< void(const MouseEvent &)> onDragStart
std::function< void(const MouseEvent &)> onDragEnd
Constructor & Destructor Documentation
Slider()
yup::Slider::Slider (StringRef componentID)
References yup::Component::Component(), yup::dontSendNotification, yup::MouseCursor::Hand, yup::Component::setMouseCursor(), and setValue().
Member Function Documentation
setValue()
void yup::Slider::setValue (float newValue, NotificationType notification = sendNotification)
References yup::Component::repaint().
Referenced by setRange(), setValueNormalised(), and Slider().
getValue()
float yup::Slider::getValue () const
setValueNormalised()
void yup::Slider::setValueNormalised (float newValue, NotificationType notification = sendNotification)
References yup::jlimit(), and setValue().
Referenced by mouseDrag(), and mouseWheel().
getValueNormalised()
float yup::Slider::getValueNormalised () const
Referenced by mouseDrag(), mouseWheel(), and yup::paintSlider().
valueChanged()
void yup::Slider::valueChanged () virtual
isMouseOver()
bool yup::Slider::isMouseOver () const
Referenced by yup::paintSlider().
setDefaultValue()
void yup::Slider::setDefaultValue (float newDefaultValue)
Referenced by setRange().
getDefaultValue()
float yup::Slider::getDefaultValue () const
setRange()
void yup::Slider::setRange (const Range< float > & newRange)
References yup::dontSendNotification, setDefaultValue(), and setValue().
getRange()
Range< float > yup::Slider::getRange () const
resized()
void yup::Slider::resized () override virtual
Called when the size of the component changes.
Reimplemented from yup::Component.
paint()
void yup::Slider::paint (Graphics & g) override virtual
Paint the component.
Parameters
g The graphics context to paint the component on.
Reimplemented from yup::Component.
References yup::ApplicationTheme::findComponentStyle(), and yup::ApplicationTheme::getGlobalTheme().
mouseEnter()
void yup::Slider::mouseEnter (const MouseEvent & event) override virtual
Called when the mouse enters the component.
Parameters
event The mouse event.
Reimplemented from yup::Component.
References yup::Component::repaint().
mouseExit()
void yup::Slider::mouseExit (const MouseEvent & event) override virtual
Called when the mouse exits the component.
Parameters
event The mouse event.
Reimplemented from yup::Component.
References yup::Component::repaint().
mouseDown()
void yup::Slider::mouseDown (const MouseEvent & event) override virtual
Called when the mouse button is pressed.
Parameters
event The mouse event.
Reimplemented from yup::Component.
References onDragStart, yup::Component::repaint(), and yup::Component::takeKeyboardFocus().
mouseUp()
void yup::Slider::mouseUp (const MouseEvent & event) override virtual
Called when the mouse button is released.
Parameters
event The mouse event.
Reimplemented from yup::Component.
References yup::MouseEvent::isAnyButtonDown(), and onDragEnd.
mouseDrag()
void yup::Slider::mouseDrag (const MouseEvent & event) override virtual
Called when the mouse is dragged.
Parameters
event The mouse event.
Reimplemented from yup::Component.
References yup::MouseEvent::getPosition(), getValueNormalised(), yup::MouseEvent::isRightButtonDown(), and setValueNormalised().
mouseWheel()
void yup::Slider::mouseWheel (const MouseEvent & event, const MouseWheelData & wheelData) override virtual
Called when the mouse wheel is scrolled.
Parameters
event The mouse event.
wheelData The mouse wheel data.
Reimplemented from yup::Component.
References yup::MouseWheelData::getDeltaX(), yup::MouseWheelData::getDeltaY(), getValueNormalised(), and setValueNormalised().
Member Data Documentation
onValueChanged
std::function<void (float)> yup::Slider::onValueChanged
onDragStart
std::function<void (const MouseEvent&)> yup::Slider::onDragStart
Referenced by mouseDown().
onDragEnd
std::function<void (const MouseEvent&)> yup::Slider::onDragEnd
Referenced by mouseUp().