YUP: yup::Component Class Reference
yup::Component Class Reference
The Component class is the base class for all GUI components.
Classes
class BailOutChecker
A bail out checker for the component.
Public Member Functions
Component ()
Constructor for the Component class.
Component (StringRef componentID)
Constructor for the Component class.
virtual ~Component ()
Destructor for the Component class.
String getComponentID () const
Get the ID of the component.
bool isEnabled () const
Check if the component is enabled.
void setEnabled (bool shouldBeEnabled)
Set the enabled state of the component.
virtual void enablementChanged ()
Called when the enabled state of the component changes.
bool isVisible () const
Check if the component is visible.
void setVisible (bool shouldBeVisible)
Set the visible state of the component.
bool isShowing () const
Check if the component is showing.
virtual void visibilityChanged ()
Called when the visible state of the component changes.
String getTitle () const
Get the title of the component.
void setTitle (const String &title)
Set the title of the component.
Point< float > getPosition () const
Get the position of the component relative to its parent.
void setPosition (const Point< float > &newPosition)
Set the position of the component relative to its parent.
float getX () const
Get the x position of the component relative to its parent.
float getY () const
Get the y position of the component relative to its parent.
float getLeft () const
Get the left position of the component relative to its parent.
float getTop () const
Get the top position of the component relative to its parent.
float getRight () const
Get the right position of the component relative to its parent.
float getBottom () const
Get the bottom position of the component relative to its parent.
Point< float > getTopLeft () const
void setTopLeft (const Point< float > &newTopLeft)
Point< float > getBottomLeft () const
void setBottomLeft (const Point< float > &newBottomLeft)
Point< float > getTopRight () const
void setTopRight (const Point< float > &newTopRight)
Point< float > getBottomRight () const
void setBottomRight (const Point< float > &newBottomRight)
Point< float > getCenter () const
void setCenter (const Point< float > &newCenter)
float getCenterX () const
void setCenterX (float newCenterX)
float getCenterY () const
void setCenterY (float newCenterY)
virtual void moved ()
Called when the position of the component changes.
Size< float > getSize () const
Get the size of the component.
void setSize (const Size< float > &newSize)
Set the size of the component.
float getWidth () const
Get the width of the component.
float getHeight () const
Get the height of the component.
float proportionOfWidth (float proportion) const
Get the width of the component as a proportion of the parent's width.
float proportionOfHeight (float proportion) const
Get the height of the component as a proportion of the parent's height.
virtual void resized ()
Called when the size of the component changes.
void setBounds (const Rectangle< float > &newBounds)
Set the bounds of the component.
Rectangle< float > getBounds () const
Get the bounds of the component, relative to its parent.
Rectangle< float > getLocalBounds () const
Get the local bounds of the component, with zero position.
Rectangle< float > getBoundsRelativeToTopLevelComponent () const
Get the bounds of the component relative to its top level component.
void setTransform (const AffineTransform &transform)
AffineTransform getTransform () const
bool isTransformed () const
virtual void transformChanged ()
void setFullScreen (bool shouldBeFullScreen)
Set the full screen state of the component.
bool isFullScreen () const
Check if the component is full screen.
virtual void displayChanged ()
Called when the component changes display.
float getScaleDpi () const
Get the scale factor of the component.
virtual void contentScaleChanged (float dpiScale)
Called when the content scale of the component changes.
float getOpacity () const
Get the opacity of the component.
void setOpacity (float opacity)
Set the opacity of the component.
virtual void enableRenderingUnclipped (bool shouldBeEnabled)
Enable or disable unclipped rendering for the component.
bool isRenderingUnclipped () const
Check if the component is rendering unclipped.
void repaint ()
Repaint the component.
void repaint (const Rectangle< float > &rect)
Repaint the component.
void * getNativeHandle () const
Get the native handle of the component.
ComponentNative * getNativeComponent ()
Get the native component of the component.
const ComponentNative * getNativeComponent () const
Get the native component of the component.
virtual void attachedToNative ()
Called when this component is attached to a native window.
virtual void detachedFromNative ()
Called when this component is detached from its native window.
bool isOnDesktop () const
Check if the component is on the desktop.
void addToDesktop (const ComponentNative::Options &nativeOptions, void *parent=nullptr)
Add the component to the desktop.
void removeFromDesktop ()
Remove the component from the desktop.
virtual void userTriedToCloseWindow ()
Called when the user tries to close the window.
void toFront (bool shouldGainKeyboardFocus)
Bring the component to the front.
void toBack ()
Bring the component to the back.
void raiseAbove (Component *component)
Raises this component above the specified component in the z-order.
void lowerBelow (Component *component)
Lowers this component below the specified component in the z-order.
void raiseBy (int indexToRaise)
Raises this component by a number of positions in the z-order.
void lowerBy (int indexToLower)
Lowers this component by a number of positions in the z-order.
void setMouseCursor (const MouseCursor &cursorType)
Set the mouse cursor of the component.
virtual MouseCursor getMouseCursor () const
Get the mouse cursor of the component.
void setWantsKeyboardFocus (bool wantsFocus)
Set if the component wants keyboard focus.
void takeKeyboardFocus ()
Take the focus.
void leaveKeyboardFocus ()
Leave the focus.
bool hasKeyboardFocus () const
Check if the component has focus.
virtual void focusGained ()
Called when the component gains focus.
virtual void focusLost ()
Called when the component loses focus.
Component * getParentComponent ()
Get the parent of the component.
const Component * getParentComponent () const
Get the parent of the component.
template<class T>
T * getParentComponentWithType ()
Get the parent of the component of a given type.
template<class T>
const T * getParentComponentWithType () const
Get the parent of the component of a given type.
void addChildComponent (Component &component, int index=-1)
Add a child component to the component.
void addChildComponent (Component *component, int index=-1)
Add a child component to the component.
void addAndMakeVisible (Component &component, int index=-1)
Add a child component to the component and make it visible.
void addAndMakeVisible (Component *component, int index=-1)
Add a child component to the component and make it visible.
void removeChildComponent (Component &component)
Remove a child component from the component.
void removeChildComponent (Component *component)
Remove a child component from the component.
void removeChildComponent (int index)
Remove a child component from the component at a specified index.
void removeAllChildren ()
Removes all child components from this component.
virtual void parentHierarchyChanged ()
Called when the parent hierarchy of this component changes.
virtual void childrenChanged ()
Called when the child components of this component change.
int getNumChildComponents () const
Get the number of child components of the component.
Component * getComponentAt (int index) const
Get the child component at a given index.
int getIndexOfChildComponent (Component *component) const
Returns the index of a child component, or -1 if not found.
Component * findComponentAt (const Point< float > &p)
Find the child component at a given point.
Component * getTopLevelComponent ()
Returns the top level component.
NamedValueSet & getProperties ()
Get the properties of the component.
const NamedValueSet & getProperties () const
Get the properties of the component.
virtual void paint (Graphics &g)
Paint the component.
virtual void paintOverChildren (Graphics &g)
Paint the component over its children.
virtual void refreshDisplay (double lastFrameTimeSeconds)
Refresh the display of the component.
virtual void mouseEnter (const MouseEvent &event)
Called when the mouse enters the component.
virtual void mouseExit (const MouseEvent &event)
Called when the mouse exits the component.
virtual void mouseDown (const MouseEvent &event)
Called when the mouse button is pressed.
virtual void mouseMove (const MouseEvent &event)
Called when the mouse is moved.
virtual void mouseDrag (const MouseEvent &event)
Called when the mouse is dragged.
virtual void mouseUp (const MouseEvent &event)
Called when the mouse button is released.
virtual void mouseDoubleClick (const MouseEvent &event)
Called when the mouse button is double clicked.
virtual void mouseWheel (const MouseEvent &event, const MouseWheelData &wheelData)
Called when the mouse wheel is scrolled.
void addMouseListener (MouseListener *listener)
Add a mouse listener to the component.
void removeMouseListener (MouseListener *listener)
Remove a mouse listener from the component.
virtual void keyDown (const KeyPress &keys, const Point< float > &position)
Called when a key is pressed.
virtual void keyUp (const KeyPress &keys, const Point< float > &position)
Called when a key is released.
virtual void textInput (const String &text)
Called when text is input.
void setStyle (ComponentStyle::Ptr newStyle)
Sets the style for this component.
ComponentStyle::Ptr getStyle () const
Returns the current style of this component.
virtual void styleChanged ()
Called when the component's style changes.
void setColor (const Identifier &colorId, const std::optional< Color > &color)
Set a color for the component.
std::optional< Color > getColor (const Identifier &colorId) const
Get the color of the component.
std::optional< Color > findColor (const Identifier &colorId) const
Find the color of the component.
Detailed Description
The Component class is the base class for all GUI components.
It provides a common interface for all components, and is used to create and manage GUI components. It is a lightweight class that is used to create and manage GUI components.
Constructor & Destructor Documentation
Component() [1/2]
yup::Component::Component ()
Constructor for the Component class.
Parameters
componentID The ID of the component.
References optionsValue.
Referenced by addAndMakeVisible(), addAndMakeVisible(), addChildComponent(), addChildComponent(), yup::Artboard::Artboard(), yup::Artboard::Artboard(), yup::Component::BailOutChecker::BailOutChecker(), yup::Button::Button(), findComponentAt(), getComponentAt(), getIndexOfChildComponent(), getParentComponent(), getParentComponent(), getTopLevelComponent(), yup::Label::Label(), lowerBelow(), raiseAbove(), removeChildComponent(), removeChildComponent(), SDL2ComponentNative, yup::Slider::Slider(), and yup::TextEditor::TextEditor().
Component() [2/2]
yup::Component::Component (StringRef componentID)
Constructor for the Component class.
Parameters
componentID The ID of the component.
References optionsValue.
~Component()
yup::Component::~Component () virtual
Destructor for the Component class.
References options, and removeFromDesktop().
Member Function Documentation
getComponentID()
String yup::Component::getComponentID () const
Get the ID of the component.
Returns
The ID of the component.
isEnabled()
bool yup::Component::isEnabled () const
Check if the component is enabled.
Returns
True if the component is enabled, false otherwise.
References options.
setEnabled()
void yup::Component::setEnabled (bool shouldBeEnabled)
Set the enabled state of the component.
Parameters
shouldBeEnabled True if the component should be enabled, false otherwise.
References enablementChanged(), hasKeyboardFocus(), and options.
enablementChanged()
void yup::Component::enablementChanged () virtual
Called when the enabled state of the component changes.
Referenced by setEnabled().
isVisible()
bool yup::Component::isVisible () const
Check if the component is visible.
Returns
True if the component is visible, false otherwise.
References options.
Referenced by isShowing(), and SDL2ComponentNative.
setVisible()
void yup::Component::setVisible (bool shouldBeVisible)
Set the visible state of the component.
Parameters
shouldBeVisible True if the component should be visible, false otherwise.
References options, repaint(), and visibilityChanged().
Referenced by addAndMakeVisible().
isShowing()
bool yup::Component::isShowing () const
Check if the component is showing.
A component is showing if it is visible and all of its parents are also visible.
Returns
True if the component is showing, false otherwise.
References getParentComponent(), and isVisible().
visibilityChanged()
void yup::Component::visibilityChanged () virtual
Called when the visible state of the component changes.
Referenced by setVisible().
getTitle()
String yup::Component::getTitle () const
Get the title of the component.
Returns
The title of the component.
setTitle()
void yup::Component::setTitle (const String & title)
Set the title of the component.
Parameters
title The new title of the component.
References options.
getPosition()
Point< float > yup::Component::getPosition () const
Get the position of the component relative to its parent.
Returns
The position of the component relative to its parent.
setPosition()
void yup::Component::setPosition (const Point< float > & newPosition)
Set the position of the component relative to its parent.
Parameters
newPosition The new position of the component relative to its parent.
References moved(), options, and yup::Point< ValueType >::to().
getX()
float yup::Component::getX () const
Get the x position of the component relative to its parent.
Returns
The x position of the component relative to its parent.
getY()
float yup::Component::getY () const
Get the y position of the component relative to its parent.
Returns
The y position of the component relative to its parent.
getLeft()
float yup::Component::getLeft () const
Get the left position of the component relative to its parent.
Returns
The left position of the component relative to its parent.
getTop()
float yup::Component::getTop () const
Get the top position of the component relative to its parent.
Returns
The top position of the component relative to its parent.
getRight()
float yup::Component::getRight () const
Get the right position of the component relative to its parent.
Returns
The right position of the component relative to its parent.
getBottom()
float yup::Component::getBottom () const
Get the bottom position of the component relative to its parent.
Returns
The bottom position of the component relative to its parent.
getTopLeft()
Point< float > yup::Component::getTopLeft () const
Referenced by repaint().
setTopLeft()
void yup::Component::setTopLeft (const Point< float > & newTopLeft)
References moved(), options, and yup::Point< ValueType >::to().
getBottomLeft()
Point< float > yup::Component::getBottomLeft () const
setBottomLeft()
void yup::Component::setBottomLeft (const Point< float > & newBottomLeft)
References getHeight(), moved(), options, and yup::Point< ValueType >::translated().
getTopRight()
Point< float > yup::Component::getTopRight () const
setTopRight()
void yup::Component::setTopRight (const Point< float > & newTopRight)
References getWidth(), moved(), options, and yup::Point< ValueType >::translated().
getBottomRight()
Point< float > yup::Component::getBottomRight () const
setBottomRight()
void yup::Component::setBottomRight (const Point< float > & newBottomRight)
References getHeight(), getWidth(), moved(), options, and yup::Point< ValueType >::translated().
getCenter()
Point< float > yup::Component::getCenter () const
setCenter()
void yup::Component::setCenter (const Point< float > & newCenter)
References getHeight(), getWidth(), moved(), options, and yup::Point< ValueType >::translated().
getCenterX()
float yup::Component::getCenterX () const
setCenterX()
void yup::Component::setCenterX (float newCenterX)
References getWidth(), moved(), and options.
getCenterY()
float yup::Component::getCenterY () const
setCenterY()
void yup::Component::setCenterY (float newCenterY)
References getHeight(), moved(), and options.
moved()
void yup::Component::moved () virtual
Called when the position of the component changes.
Referenced by setBottomLeft(), setBottomRight(), setBounds(), setCenter(), setCenterX(), setCenterY(), setPosition(), setTopLeft(), and setTopRight().
getSize()
Size< float > yup::Component::getSize () const
Get the size of the component.
References options, and yup::Size< ValueType >::to().
setSize()
void yup::Component::setSize (const Size< float > & newSize)
Set the size of the component.
Parameters
newSize The new size of the component.
References options, resized(), and yup::Size< ValueType >::to().
Referenced by yup::DocumentWindow::centreWithSize().
getWidth()
float yup::Component::getWidth () const
Get the width of the component.
Returns
The width of the component.
Referenced by proportionOfWidth(), setBottomRight(), setCenter(), setCenterX(), and setTopRight().
getHeight()
float yup::Component::getHeight () const
Get the height of the component.
Returns
The height of the component.
Referenced by proportionOfHeight(), yup::TextButton::resized(), setBottomLeft(), setBottomRight(), setCenter(), and setCenterY().
proportionOfWidth()
float yup::Component::proportionOfWidth (float proportion) const
Get the width of the component as a proportion of the parent's width.
Parameters
proportion The proportion of the parent's width to get.
Returns
The width of the component as a proportion of the parent's width.
References getWidth().
Referenced by yup::TextButton::getTextBounds(), and yup::paintSlider().
proportionOfHeight()
float yup::Component::proportionOfHeight (float proportion) const
Get the height of the component as a proportion of the parent's height.
Parameters
proportion The proportion of the parent's height to get.
Returns
The height of the component as a proportion of the parent's height.
References getHeight().
resized()
void yup::Component::resized () virtual
Called when the size of the component changes.
Reimplemented in yup::Artboard, yup::Label, yup::Slider, yup::TextButton, and yup::TextEditor.
Referenced by setBounds(), and setSize().
setBounds()
void yup::Component::setBounds (const Rectangle< float > & newBounds)
Set the bounds of the component.
Parameters
newBounds The new bounds of the component.
References moved(), options, resized(), yup::Rectangle< ValueType >::setBounds(), and yup::Rectangle< ValueType >::to().
Referenced by addToDesktop(), and yup::DocumentWindow::centreWithSize().
getBounds()
Rectangle< float > yup::Component::getBounds () const
Get the bounds of the component, relative to its parent.
Returns
The bounds of the component.
Referenced by addToDesktop(), repaint(), and yup::Artboard::resized().
getLocalBounds()
Rectangle< float > yup::Component::getLocalBounds () const
Get the local bounds of the component, with zero position.
Returns
The local bounds of the component.
References yup::Rectangle< ValueType >::withZeroPosition().
Referenced by yup::TextButton::getTextBounds(), yup::TextEditor::getTextBounds(), yup::paintLabel(), yup::paintSlider(), yup::paintTextButton(), and yup::paintTextEditor().
getBoundsRelativeToTopLevelComponent()
Rectangle< float > yup::Component::getBoundsRelativeToTopLevelComponent () const
Get the bounds of the component relative to its top level component.
Returns
The bounds of the component relative to its top most component (on desktop).
References getParentComponent(), options, and yup::Rectangle< ValueType >::withZeroPosition().
Referenced by repaint(), and repaint().
setTransform()
void yup::Component::setTransform (const AffineTransform & transform)
References transformChanged().
getTransform()
AffineTransform yup::Component::getTransform () const
isTransformed()
bool yup::Component::isTransformed () const
References yup::AffineTransform::isIdentity().
transformChanged()
void yup::Component::transformChanged () virtual
Referenced by setTransform().
setFullScreen()
void yup::Component::setFullScreen (bool shouldBeFullScreen)
Set the full screen state of the component.
Parameters
shouldBeFullScreen True if the component should be full screen, false otherwise.
References options.
isFullScreen()
bool yup::Component::isFullScreen () const
Check if the component is full screen.
References options.
Referenced by SDL2ComponentNative.
displayChanged()
void yup::Component::displayChanged () virtual
Called when the component changes display.
getScaleDpi()
float yup::Component::getScaleDpi () const
Get the scale factor of the component.
Returns
The scale factor of the component.
Referenced by yup::Artboard::resized().
contentScaleChanged()
void yup::Component::contentScaleChanged (float dpiScale) virtual
Called when the content scale of the component changes.
Parameters
dpiScale The new scale factor of the component.
Reimplemented in yup::Artboard.
getOpacity()
float yup::Component::getOpacity () const
Get the opacity of the component.
Returns
The opacity of the component.
setOpacity()
void yup::Component::setOpacity (float opacity)
Set the opacity of the component.
Parameters
opacity The new opacity of the component.
References yup::jlimit().
enableRenderingUnclipped()
void yup::Component::enableRenderingUnclipped (bool shouldBeEnabled) virtual
Enable or disable unclipped rendering for the component.
Parameters
shouldBeEnabled True if the component should be rendered unclipped, false otherwise.
References options.
isRenderingUnclipped()
bool yup::Component::isRenderingUnclipped () const
Check if the component is rendering unclipped.
Returns
True if the component is rendering unclipped, false otherwise.
References options.
repaint() [1/2]
void yup::Component::repaint ()
Repaint the component.
References getBounds(), getBoundsRelativeToTopLevelComponent(), getNativeComponent(), and options.
Referenced by yup::TextEditor::deleteSelectedText(), yup::TextEditor::focusGained(), yup::TextEditor::focusLost(), yup::TextEditor::insertText(), yup::TextEditor::keyDown(), yup::Artboard::mouseDown(), yup::Button::mouseDown(), yup::Slider::mouseDown(), yup::TextEditor::mouseDown(), yup::Artboard::mouseDrag(), yup::TextEditor::mouseDrag(), yup::Artboard::mouseEnter(), yup::Button::mouseEnter(), yup::Slider::mouseEnter(), yup::Artboard::mouseExit(), yup::Button::mouseExit(), yup::Slider::mouseExit(), yup::Artboard::mouseMove(), yup::Artboard::mouseUp(), yup::Button::mouseUp(), yup::TextEditor::resetFont(), yup::TextEditor::resetFontSize(), yup::Artboard::setBoolInput(), yup::TextEditor::setCaretPosition(), yup::TextEditor::setFont(), yup::TextEditor::setFontSize(), yup::TextEditor::setMultiLine(), yup::Artboard::setNumberInput(), yup::Artboard::setPaused(), yup::TextEditor::setSelection(), yup::Label::setStrokeWidth(), setStyle(), yup::TextEditor::setText(), yup::Slider::setValue(), setVisible(), and yup::Artboard::triggerInput().
repaint() [2/2]
void yup::Component::repaint (const Rectangle< float > & rect)
Repaint the component.
Parameters
rect The rectangle to repaint.
References getBoundsRelativeToTopLevelComponent(), getNativeComponent(), getTopLeft(), yup::Rectangle< ValueType >::isEmpty(), options, and yup::Rectangle< ValueType >::translated().
getNativeHandle()
void * yup::Component::getNativeHandle () const
Get the native handle of the component.
Returns
The native handle of the component.
References options.
getNativeComponent() [1/2]
ComponentNative * yup::Component::getNativeComponent ()
Get the native component of the component.
Returns
The native component of the component.
References ComponentNative.
Referenced by hasKeyboardFocus(), leaveKeyboardFocus(), repaint(), repaint(), setMouseCursor(), and takeKeyboardFocus().
getNativeComponent() [2/2]
const ComponentNative * yup::Component::getNativeComponent () const
Get the native component of the component.
Returns
The native component of the component.
References ComponentNative.
attachedToNative()
void yup::Component::attachedToNative () virtual
Called when this component is attached to a native window.
Override this to perform any setup required when the component gets a native window.
Referenced by addToDesktop().
detachedFromNative()
void yup::Component::detachedFromNative () virtual
Called when this component is detached from its native window.
Override this to perform any cleanup when the component loses its native window.
Referenced by removeFromDesktop().
isOnDesktop()
bool yup::Component::isOnDesktop () const
Check if the component is on the desktop.
Returns
True if the component is on the desktop, false otherwise.
References options.
addToDesktop()
void yup::Component::addToDesktop (const ComponentNative::Options & nativeOptions, void * parent = nullptr)
Add the component to the desktop.
Parameters
nativeOptions The native options of the component.
parent The parent of the component.
References attachedToNative(), yup::ComponentNative::createFor(), getBounds(), options, removeFromDesktop(), and setBounds().
Referenced by yup::DocumentWindow::DocumentWindow().
removeFromDesktop()
void yup::Component::removeFromDesktop ()
Remove the component from the desktop.
References detachedFromNative(), and options.
Referenced by addToDesktop(), and ~Component().
userTriedToCloseWindow()
void yup::Component::userTriedToCloseWindow () virtual
Called when the user tries to close the window.
Reimplemented in yup::DocumentWindow.
toFront()
void yup::Component::toFront (bool shouldGainKeyboardFocus)
Bring the component to the front.
References options, and takeKeyboardFocus().
toBack()
void yup::Component::toBack ()
Bring the component to the back.
raiseAbove()
void yup::Component::raiseAbove (Component * component)
Raises this component above the specified component in the z-order.
Parameters
component The component to raise above.
References Component(), and yup::jmin().
lowerBelow()
void yup::Component::lowerBelow (Component * component)
Lowers this component below the specified component in the z-order.
Parameters
component The component to lower below.
References Component(), and yup::jmax().
raiseBy()
void yup::Component::raiseBy (int indexToRaise)
Raises this component by a number of positions in the z-order.
Parameters
indexToRaise The number of positions to raise by.
References yup::jmin().
lowerBy()
void yup::Component::lowerBy (int indexToLower)
Lowers this component by a number of positions in the z-order.
Parameters
indexToLower The number of positions to lower by.
References yup::jmax().
setMouseCursor()
void yup::Component::setMouseCursor (const MouseCursor & cursorType)
Set the mouse cursor of the component.
Parameters
cursorType The new mouse cursor of the component.
References getNativeComponent().
Referenced by yup::TextEditor::setReadOnly(), yup::Slider::Slider(), yup::TextButton::TextButton(), and yup::TextEditor::TextEditor().
getMouseCursor()
MouseCursor yup::Component::getMouseCursor () const virtual
Get the mouse cursor of the component.
Returns
The mouse cursor of the component.
setWantsKeyboardFocus()
void yup::Component::setWantsKeyboardFocus (bool wantsFocus)
Set if the component wants keyboard focus.
Parameters
wantsFocus True if the component wants keyboard focus, false otherwise.
References options.
Referenced by yup::TextButton::TextButton(), and yup::TextEditor::TextEditor().
takeKeyboardFocus()
void yup::Component::takeKeyboardFocus ()
Take the focus.
References getNativeComponent(), and options.
Referenced by yup::Button::mouseDown(), yup::Slider::mouseDown(), yup::TextEditor::mouseDown(), and toFront().
leaveKeyboardFocus()
void yup::Component::leaveKeyboardFocus ()
Leave the focus.
References getNativeComponent().
hasKeyboardFocus()
bool yup::Component::hasKeyboardFocus () const
Check if the component has focus.
Returns
True if the component has focus, false otherwise.
References getNativeComponent(), and options.
Referenced by yup::TextEditor::mouseDown(), yup::paintSlider(), yup::paintTextButton(), yup::paintTextEditor(), and setEnabled().
focusGained()
void yup::Component::focusGained () virtual
Called when the component gains focus.
Reimplemented in yup::TextEditor.
focusLost()
void yup::Component::focusLost () virtual
Called when the component loses focus.
Reimplemented in yup::TextEditor.
getParentComponent() [1/2]
Component * yup::Component::getParentComponent ()
Get the parent of the component.
Returns
The parent of the component.
References Component().
Referenced by getBoundsRelativeToTopLevelComponent(), getTopLevelComponent(), and isShowing().
getParentComponent() [2/2]
const Component * yup::Component::getParentComponent () const
Get the parent of the component.
Returns
The parent of the component.
References Component().
getParentComponentWithType() [1/2]
template<class T> T * yup::Component::getParentComponentWithType ()
Get the parent of the component of a given type.
Returns
The parent of the component of the given type.
getParentComponentWithType() [2/2]
template<class T> const T * yup::Component::getParentComponentWithType () const
Get the parent of the component of a given type.
Returns
The parent of the component of the given type.
addChildComponent() [1/2]
void yup::Component::addChildComponent (Component & component, int index = -1)
Add a child component to the component.
Parameters
component The child component to add.
References addChildComponent(), and Component().
Referenced by addAndMakeVisible(), and addChildComponent().
addChildComponent() [2/2]
void yup::Component::addChildComponent (Component * component, int index = -1)
Add a child component to the component.
Parameters
component The child component to add.
References childrenChanged(), Component(), and yup::isPositiveAndBelow().
addAndMakeVisible() [1/2]
void yup::Component::addAndMakeVisible (Component & component, int index = -1)
Add a child component to the component and make it visible.
Parameters
component The child component to add.
References addAndMakeVisible(), and Component().
Referenced by addAndMakeVisible().
addAndMakeVisible() [2/2]
void yup::Component::addAndMakeVisible (Component * component, int index = -1)
Add a child component to the component and make it visible.
Parameters
component The child component to add.
References addChildComponent(), Component(), and setVisible().
removeChildComponent() [1/3]
void yup::Component::removeChildComponent (Component & component)
Remove a child component from the component.
Parameters
component The child component to remove.
References Component(), and removeChildComponent().
Referenced by removeAllChildren(), removeChildComponent(), and removeChildComponent().
removeChildComponent() [2/3]
void yup::Component::removeChildComponent (Component * component)
Remove a child component from the component.
Parameters
component The child component to remove.
References Component(), and removeChildComponent().
removeChildComponent() [3/3]
void yup::Component::removeChildComponent (int index)
Remove a child component from the component at a specified index.
Parameters
index The child component index to remove.
References childrenChanged(), and yup::isPositiveAndBelow().
removeAllChildren()
void yup::Component::removeAllChildren ()
Removes all child components from this component.
The removed components will be deleted if not referenced elsewhere.
References removeChildComponent().
parentHierarchyChanged()
void yup::Component::parentHierarchyChanged () virtual
Called when the parent hierarchy of this component changes.
This happens when the component is added to or removed from a parent component.
childrenChanged()
void yup::Component::childrenChanged () virtual
Called when the child components of this component change.
This happens when child components are added or removed.
Referenced by addChildComponent(), and removeChildComponent().
getNumChildComponents()
int yup::Component::getNumChildComponents () const
Get the number of child components of the component.
getComponentAt()
Component * yup::Component::getComponentAt (int index) const
Get the child component at a given index.
Parameters
index The index of the child component to get.
References Component().
getIndexOfChildComponent()
int yup::Component::getIndexOfChildComponent (Component * component) const
Returns the index of a child component, or -1 if not found.
References Component().
findComponentAt()
Component * yup::Component::findComponentAt (const Point< float > & p)
Find the child component at a given point.
Parameters
p The point to find the child component at.
References Component(), and options.
getTopLevelComponent()
Component * yup::Component::getTopLevelComponent ()
Returns the top level component.
References Component(), and getParentComponent().
getProperties() [1/2]
NamedValueSet & yup::Component::getProperties ()
Get the properties of the component.
Returns
The properties of the component.
getProperties() [2/2]
const NamedValueSet & yup::Component::getProperties () const
Get the properties of the component.
Returns
The properties of the component.
paint()
void yup::Component::paint (Graphics & g) virtual
Paint the component.
Parameters
g The graphics context to paint the component on.
Reimplemented in yup::Artboard, yup::Button, yup::DocumentWindow, yup::Label, yup::Slider, and yup::TextEditor.
paintOverChildren()
void yup::Component::paintOverChildren (Graphics & g) virtual
Paint the component over its children.
Parameters
g The graphics context to paint the component on.
refreshDisplay()
void yup::Component::refreshDisplay (double lastFrameTimeSeconds) virtual
Refresh the display of the component.
Parameters
lastFrameTimeSeconds The time since the last frame.
Reimplemented in yup::Artboard.
mouseEnter()
void yup::Component::mouseEnter (const MouseEvent & event) virtual
Called when the mouse enters the component.
Parameters
event The mouse event.
Reimplemented in yup::Artboard, yup::Button, and yup::Slider.
mouseExit()
void yup::Component::mouseExit (const MouseEvent & event) virtual
Called when the mouse exits the component.
Parameters
event The mouse event.
Reimplemented in yup::Artboard, yup::Button, and yup::Slider.
mouseDown()
void yup::Component::mouseDown (const MouseEvent & event) virtual
Called when the mouse button is pressed.
Parameters
event The mouse event.
Reimplemented in yup::Artboard, yup::Button, yup::Slider, and yup::TextEditor.
mouseMove()
void yup::Component::mouseMove (const MouseEvent & event) virtual
Called when the mouse is moved.
Parameters
event The mouse event.
Reimplemented in yup::Artboard.
mouseDrag()
void yup::Component::mouseDrag (const MouseEvent & event) virtual
Called when the mouse is dragged.
Parameters
event The mouse event.
Reimplemented in yup::Artboard, yup::Slider, and yup::TextEditor.
mouseUp()
void yup::Component::mouseUp (const MouseEvent & event) virtual
Called when the mouse button is released.
Parameters
event The mouse event.
Reimplemented in yup::Artboard, yup::Button, yup::Slider, and yup::TextEditor.
mouseDoubleClick()
void yup::Component::mouseDoubleClick (const MouseEvent & event) virtual
Called when the mouse button is double clicked.
Parameters
event The mouse event.
Reimplemented in yup::TextEditor.
mouseWheel()
void yup::Component::mouseWheel (const MouseEvent & event, const MouseWheelData & wheelData) virtual
Called when the mouse wheel is scrolled.
Parameters
event The mouse event.
wheelData The mouse wheel data.
Reimplemented in yup::Slider.
addMouseListener()
void yup::Component::addMouseListener (MouseListener * listener)
Add a mouse listener to the component.
Parameters
listener The mouse listener to add.
removeMouseListener()
void yup::Component::removeMouseListener (MouseListener * listener)
Remove a mouse listener from the component.
Parameters
listener The mouse listener to remove.
References yup::NamedValueSet::remove().
keyDown()
void yup::Component::keyDown (const KeyPress & keys, const Point< float > & position) virtual
Called when a key is pressed.
Parameters
keys The key press.
position The position of the key press.
Reimplemented in yup::TextEditor.
keyUp()
void yup::Component::keyUp (const KeyPress & keys, const Point< float > & position) virtual
Called when a key is released.
Parameters
keys The key press.
position The position of the key press.
textInput()
void yup::Component::textInput (const String & text) virtual
Called when text is input.
Parameters
text The text input.
Reimplemented in yup::TextEditor.
setStyle()
void yup::Component::setStyle (ComponentStyle::Ptr newStyle)
Sets the style for this component.
Parameters
newStyle The new style to apply to the component.
References repaint(), and styleChanged().
getStyle()
ComponentStyle::Ptr yup::Component::getStyle () const
Returns the current style of this component.
Returns
The component's current style.
styleChanged()
void yup::Component::styleChanged () virtual
Called when the component's style changes.
Override this to perform custom actions when the style is modified.
Referenced by setStyle().
setColor()
void yup::Component::setColor (const Identifier & colorId, const std::optional< Color > & color)
Set a color for the component.
Parameters
colorId The identifier of the color to set.
color The color to set.
getColor()
std::optional< Color > yup::Component::getColor (const Identifier & colorId) const
Get the color of the component.
Parameters
colorId The identifier of the color to get.
References yup::Color.
Referenced by findColor().
findColor()
std::optional< Color > yup::Component::findColor (const Identifier & colorId) const
Find the color of the component.
Parameters
colorId The identifier of the color to find.
Returns
The color of the component.
References getColor().
Referenced by yup::paintLabel(), yup::paintTextButton(), and yup::paintTextEditor().
Member Data Documentation
optionsValue
uint32 yup::Component::optionsValue
Referenced by Component(), and Component().
options
Options yup::Component::options
Referenced by addToDesktop(), yup::DocumentWindow::DocumentWindow(), enableRenderingUnclipped(), findComponentAt(), getBoundsRelativeToTopLevelComponent(), getNativeHandle(), getSize(), hasKeyboardFocus(), isEnabled(), isFullScreen(), isOnDesktop(), isRenderingUnclipped(), isVisible(), removeFromDesktop(), repaint(), repaint(), setBottomLeft(), setBottomRight(), setBounds(), setCenter(), setCenterX(), setCenterY(), setEnabled(), setFullScreen(), setPosition(), setSize(), setTitle(), setTopLeft(), setTopRight(), setVisible(), setWantsKeyboardFocus(), takeKeyboardFocus(), toFront(), and ~Component().