YUP: yup::Uuid Class Reference
yup::Uuid Class Reference
A universally unique 128-bit identifier.
Public Member Functions
Uuid ()
Creates a new unique ID, compliant with RFC 4122 version 4.
~Uuid () noexcept
Destructor.
Uuid (const Uuid &) noexcept
Creates a copy of another UUID.
Uuid & operator= (const Uuid &) noexcept
Copies another UUID.
bool isNull () const noexcept
Returns true if the ID is zero.
bool operator== (const Uuid &) const noexcept
bool operator!= (const Uuid &) const noexcept
bool operator< (const Uuid &) const noexcept
bool operator> (const Uuid &) const noexcept
bool operator<= (const Uuid &) const noexcept
bool operator>= (const Uuid &) const noexcept
String toString () const
Returns a stringified version of this UUID.
String toDashedString () const
Returns a stringified version of this UUID, separating it into sections with dashes.
String toArrayString () const
Returns a stringified version of this UUID, declared as a initializer-list array.
Uuid (const String &uuidString)
Creates an ID from an encoded string version.
Uuid & operator= (const String &uuidString)
Copies from a stringified UUID.
uint32 getPart (size_t section) const noexcept
Returns an indexed section of the UUID.
uint32 getTimeLow () const noexcept
Returns the time-low section of the UUID.
uint16 getTimeMid () const noexcept
Returns the time-mid section of the UUID.
uint16 getTimeHighAndVersion () const noexcept
Returns the time-high-and-version section of the UUID.
uint8 getClockSeqAndReserved () const noexcept
Returns the clock-seq-and-reserved section of the UUID.
uint8 getClockSeqLow () const noexcept
Returns the clock-seq-low section of the UUID.
uint64 getNode () const noexcept
Returns the node section of the UUID.
uint64 hash () const noexcept
Returns a hash of the UUID.
const uint8 * getRawData () const noexcept
Returns a pointer to the internal binary representation of the ID.
Uuid (const uint8 *rawData) noexcept
Creates a UUID from a 16-byte array.
Uuid & operator= (const uint8 *rawData) noexcept
Sets this UUID from 16-bytes of raw data.
Static Public Member Functions
static Uuid null () noexcept
Returns a null Uuid object.
static const size_t getRawDataSize () noexcept
Returns the Raw Data Size, which is always 16.
static Uuid fromSHA1 (const SHA1 &hash)
Creates a deterministic unique ID based on a SHA-1 hash.
static Uuid fromSHA1 (const MemoryBlock &hash)
static Uuid fromHexStringSHA1 (const String &hash)
Creates a deterministic unique ID based on the string representation of a SHA-1 hash.
static Uuid fromMD5 (const MemoryBlock &hash)
Creates a deterministic unique ID based on an MD5 hash.
static Uuid fromHexStringMD5 (const String &hash)
Creates a deterministic unique ID based on the string representation of an MD5 hash.
Static Public Attributes
static const Uuid namespaceDns = Uuid ("6ba7b810-9dad-11d1-80b4-00c04fd430c8")
Returns a name space ID for when the 'name string is a fully-qualified domain name' as defined in RFC 4122 Appendix C.
static const Uuid namespaceUrl = Uuid ("6ba7b811-9dad-11d1-80b4-00c04fd430c8")
Returns a name space ID for when the 'name string is a URL' as defined in RFC 4122 Appendix C.
static const Uuid namespaceIsoOid = Uuid ("6ba7b812-9dad-11d1-80b4-00c04fd430c8")
Returns a name space ID for when the 'name string is an ISO OID' as defined in RFC 4122 Appendix C.
static const Uuid namespaceX500Dn = Uuid ("6ba7b814-9dad-11d1-80b4-00c04fd430c8")
Returns a name space ID for when the 'name string is an X.500 DN (in DER or a text output format)' as defined in RFC 4122 Appendix C.
Detailed Description
A universally unique 128-bit identifier.
This class generates very random unique numbers. It's vanishingly unlikely that two identical UUIDs would ever be created by chance. The values are formatted to meet the RFC 4122 version 4 standard.
The class includes methods for saving the ID as a string or as raw binary data.
Constructor & Destructor Documentation
Uuid() [1/4]
yup::Uuid::Uuid ()
Creates a new unique ID, compliant with RFC 4122 version 4.
References yup::Random::nextInt().
Referenced by fromHexStringMD5(), fromHexStringSHA1(), fromMD5(), fromSHA1(), fromSHA1(), null(), operator!=(), operator<(), operator<=(), operator=(), operator=(), operator=(), operator==(), operator>(), operator>=(), and Uuid().
~Uuid()
yup::Uuid::~Uuid () noexcept
Destructor.
Uuid() [2/4]
yup::Uuid::Uuid (const Uuid & other) noexcept
Creates a copy of another UUID.
References Uuid().
Uuid() [3/4]
yup::Uuid::Uuid (const String & uuidString)
Creates an ID from an encoded string version.
See also
toString
References operator=().
Uuid() [4/4]
yup::Uuid::Uuid (const uint8 * rawData) noexcept
Creates a UUID from a 16-byte array.
See also
getRawData
Member Function Documentation
operator=() [1/3]
Uuid & yup::Uuid::operator= (const Uuid & other) noexcept
Copies another UUID.
References Uuid().
Referenced by Uuid().
isNull()
bool yup::Uuid::isNull () const noexcept
Returns true if the ID is zero.
null()
Uuid yup::Uuid::null () static noexcept
Returns a null Uuid object.
References Uuid().
operator==()
bool yup::Uuid::operator== (const Uuid & other) const noexcept
References Uuid().
operator!=()
bool yup::Uuid::operator!= (const Uuid & other) const noexcept
References yup::operator==(), and Uuid().
operator<()
bool yup::Uuid::operator< (const Uuid & other) const noexcept
References Uuid().
operator>()
bool yup::Uuid::operator> (const Uuid & other) const noexcept
References Uuid().
operator<=()
bool yup::Uuid::operator<= (const Uuid & other) const noexcept
References Uuid().
operator>=()
bool yup::Uuid::operator>= (const Uuid & other) const noexcept
References Uuid().
toString()
String yup::Uuid::toString () const
Returns a stringified version of this UUID.
A Uuid object can later be reconstructed from this string using operator= or the constructor that takes a string parameter.
Returns
a 32 character hex string.
toDashedString()
String yup::Uuid::toDashedString () const
Returns a stringified version of this UUID, separating it into sections with dashes.
Returns
a string in the format: xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx
toArrayString()
String yup::Uuid::toArrayString () const
Returns a stringified version of this UUID, declared as a initializer-list array.
Returns
a string in the format: { xx, xx, xx, xx, xx, xx, xx, xx, xx, xx, xx, xx, xx, xx, xx, xx }
operator=() [2/3]
Uuid & yup::Uuid::operator= (const String & uuidString)
Copies from a stringified UUID.
The string passed in should be one that was created with the toString() method.
References yup::MemoryBlock::copyTo(), yup::MemoryBlock::ensureSize(), yup::MemoryBlock::loadFromHexString(), and Uuid().
getPart()
uint32 yup::Uuid::getPart (size_t section) const noexcept
Returns an indexed section of the UUID.
Section might be inside the range [0..3].
References yup::ByteOrder::bigEndianInt().
getTimeLow()
uint32 yup::Uuid::getTimeLow () const noexcept
Returns the time-low section of the UUID.
References yup::ByteOrder::bigEndianInt().
getTimeMid()
uint16 yup::Uuid::getTimeMid () const noexcept
Returns the time-mid section of the UUID.
References yup::ByteOrder::bigEndianShort().
getTimeHighAndVersion()
uint16 yup::Uuid::getTimeHighAndVersion () const noexcept
Returns the time-high-and-version section of the UUID.
References yup::ByteOrder::bigEndianShort().
getClockSeqAndReserved()
uint8 yup::Uuid::getClockSeqAndReserved () const noexcept
Returns the clock-seq-and-reserved section of the UUID.
getClockSeqLow()
uint8 yup::Uuid::getClockSeqLow () const noexcept
Returns the clock-seq-low section of the UUID.
getNode()
uint64 yup::Uuid::getNode () const noexcept
Returns the node section of the UUID.
References yup::ByteOrder::bigEndianInt(), and yup::ByteOrder::bigEndianShort().
hash()
uint64 yup::Uuid::hash () const noexcept
Returns a hash of the UUID.
Referenced by fromHexStringMD5(), fromHexStringSHA1(), fromMD5(), fromSHA1(), and fromSHA1().
getRawData()
const uint8 * yup::Uuid::getRawData () const noexcept
Returns a pointer to the internal binary representation of the ID.
This is an array of 16 bytes. To reconstruct a Uuid from its data, use the constructor or operator= method that takes an array of uint8s.
getRawDataSize()
const size_t yup::Uuid::getRawDataSize () static noexcept
Returns the Raw Data Size, which is always 16.
operator=() [3/3]
Uuid & yup::Uuid::operator= (const uint8 * rawData) noexcept
Sets this UUID from 16-bytes of raw data.
References Uuid(), and yup::zeromem().
fromSHA1() [1/2]
Uuid yup::Uuid::fromSHA1 (const SHA1 & hash) static
Creates a deterministic unique ID based on a SHA-1 hash.
You can use this function to make a RFC 4122 version 5 compliant Uuid if you concatenate a Uuid defining a 'namespace' wih the 'name' (the data you are using) as follows.
String test ("www.example.org");
MemoryBlock block;
block.append (Uuid::namespaceDns.getRawData(), Uuid::getRawDataSize());
block.append (test.toRawUTF8(), test.getNumBytesAsUTF8());
SHA1 hash (block);
Uuid uuid = Uuid::fromSHA1 (hash);
References hash(), and Uuid().
Referenced by fromHexStringSHA1().
fromSHA1() [2/2]
Uuid yup::Uuid::fromSHA1 (const MemoryBlock & hash) static
References hash(), and Uuid().
fromHexStringSHA1()
Uuid yup::Uuid::fromHexStringSHA1 (const String & hash) static
Creates a deterministic unique ID based on the string representation of a SHA-1 hash.
You can use this function to make a RFC 4122 version 5 compliant Uuid.
See also
fromSHA1
References fromSHA1(), hash(), yup::MemoryBlock::loadFromHexString(), and Uuid().
fromMD5()
Uuid yup::Uuid::fromMD5 (const MemoryBlock & hash) static
Creates a deterministic unique ID based on an MD5 hash.
You can use this function to make a RFC 4122 version 3 compliant Uuid. SHA-1 based (version 5) are preferred.
See also
fromSHA1
References hash(), and Uuid().
Referenced by fromHexStringMD5().
fromHexStringMD5()
Uuid yup::Uuid::fromHexStringMD5 (const String & hash) static
Creates a deterministic unique ID based on the string representation of an MD5 hash.
You can use this function to make a RFC 4122 version 3 compliant Uuid. SHA-1 based (version 5) are preferred.
See also
fromSHA1
References fromMD5(), hash(), yup::MemoryBlock::loadFromHexString(), and Uuid().
Member Data Documentation
namespaceDns
const Uuid yup::Uuid::namespaceDns = Uuid ("6ba7b810-9dad-11d1-80b4-00c04fd430c8") static
Returns a name space ID for when the 'name string is a fully-qualified domain name' as defined in RFC 4122 Appendix C.
See also
fromSHA1
namespaceUrl
const Uuid yup::Uuid::namespaceUrl = Uuid ("6ba7b811-9dad-11d1-80b4-00c04fd430c8") static
Returns a name space ID for when the 'name string is a URL' as defined in RFC 4122 Appendix C.
See also
fromSHA1
namespaceIsoOid
const Uuid yup::Uuid::namespaceIsoOid = Uuid ("6ba7b812-9dad-11d1-80b4-00c04fd430c8") static
Returns a name space ID for when the 'name string is an ISO OID' as defined in RFC 4122 Appendix C.
See also
fromSHA1
namespaceX500Dn
const Uuid yup::Uuid::namespaceX500Dn = Uuid ("6ba7b814-9dad-11d1-80b4-00c04fd430c8") static
Returns a name space ID for when the 'name string is an X.500 DN (in DER or a text output format)' as defined in RFC 4122 Appendix C.
See also
fromSHA1