YUP: yup::UnitTest Class Reference
yup::UnitTest Class Reference abstract
This is a base class for classes that perform a unit test.
Public Member Functions
UnitTest (const String &name, const String &category=String())
Creates a test with the given name and optionally places it in a category.
virtual ~UnitTest ()
Destructor.
const String & getName () const noexcept
Returns the name of the test.
const String & getCategory () const noexcept
Returns the category of the test.
void performTest (UnitTestRunner *runner)
Runs the test, using the specified UnitTestRunner.
virtual void initialise ()
You can optionally implement this method to set up your test.
virtual void shutdown ()
You can optionally implement this method to clear up after your test has been run.
virtual void runTest ()=0
Implement this method in your subclass to actually run your tests.
void beginTest (const String &testName)
Tells the system that a new subsection of tests is beginning.
void expect (bool testResult, const String &failureMessage=String())
Checks that the result of a test is true, and logs this result.
template<class ValueType>
void expectEquals (ValueType actual, ValueType expected, String failureMessage=String())
Compares a value to an expected value.
template<class ValueType>
void expectNotEquals (ValueType value, ValueType valueToCompareTo, String failureMessage=String())
Checks whether a value is not equal to a comparison value.
template<class ValueType>
void expectGreaterThan (ValueType value, ValueType valueToCompareTo, String failureMessage=String())
Checks whether a value is greater than a comparison value.
template<class ValueType>
void expectLessThan (ValueType value, ValueType valueToCompareTo, String failureMessage=String())
Checks whether a value is less than a comparison value.
template<class ValueType>
void expectGreaterOrEqual (ValueType value, ValueType valueToCompareTo, String failureMessage=String())
Checks whether a value is greater or equal to a comparison value.
template<class ValueType>
void expectLessOrEqual (ValueType value, ValueType valueToCompareTo, String failureMessage=String())
Checks whether a value is less or equal to a comparison value.
template<class ValueType>
void expectWithinAbsoluteError (ValueType actual, ValueType expected, ValueType maxAbsoluteError, String failureMessage=String())
Computes the difference between a value and a comparison value, and if it is larger than a specified maximum value, prints out a message containing the actual and comparison values and the maximum allowed error.
void logMessage (const String &message)
Writes a message to the test log.
Random getRandom () const
Returns a shared RNG that all unit tests should use.
Static Public Member Functions
static Array< UnitTest * > & getAllTests ()
Returns the set of all UnitTest objects that currently exist.
static Array< UnitTest * > getTestsInCategory (const String &category)
Returns the set of UnitTests in a specified category.
static StringArray getAllCategories ()
Returns a StringArray containing all of the categories of UnitTests that have been registered.
Detailed Description
This is a base class for classes that perform a unit test.
To write a test using this class, your code should look something like this:
class MyTest  : public UnitTest
{
public:
    MyTest()  : UnitTest ("Foobar testing") {}
    void runTest() override
    {
        beginTest ("Part 1");
        expect (myFoobar.doesSomething());
        expect (myFoobar.doesSomethingElse());
        beginTest ("Part 2");
        expect (myOtherFoobar.doesSomething());
        expect (myOtherFoobar.doesSomethingElse());
        ...etc..
    }
};
// Creating a static instance will automatically add the instance to the array
// returned by UnitTest::getAllTests(), so the test will be included when you call
// UnitTestRunner::runAllTests()
static MyTest test;
To run a test, use the UnitTestRunner class.
See also
UnitTestRunner
Constructor & Destructor Documentation
UnitTest()
yup::UnitTest::UnitTest (const String & name, const String & category = String()) explicit
Creates a test with the given name and optionally places it in a category.
References getAllTests().
~UnitTest()
yup::UnitTest::~UnitTest () virtual
Destructor.
References getAllTests().
Member Function Documentation
getName()
const String & yup::UnitTest::getName () const noexcept
Returns the name of the test.
getCategory()
const String & yup::UnitTest::getCategory () const noexcept
Returns the category of the test.
performTest()
void yup::UnitTest::performTest (UnitTestRunner * runner)
Runs the test, using the specified UnitTestRunner.
You shouldn't need to call this method directly - use UnitTestRunner::runTests() instead.
References initialise(), runTest(), and shutdown().
getAllTests()
Array< UnitTest * > & yup::UnitTest::getAllTests () static
Returns the set of all UnitTest objects that currently exist.
Referenced by getAllCategories(), getTestsInCategory(), yup::UnitTestRunner::runAllTests(), UnitTest(), and ~UnitTest().
getTestsInCategory()
Array< UnitTest * > yup::UnitTest::getTestsInCategory (const String & category) static
Returns the set of UnitTests in a specified category.
References yup::Array< ElementType, TypeOfCriticalSectionToUse, minimumAllocatedSize >::add(), and getAllTests().
Referenced by yup::UnitTestRunner::runTestsInCategory().
getAllCategories()
StringArray yup::UnitTest::getAllCategories () static
Returns a StringArray containing all of the categories of UnitTests that have been registered.
References yup::StringArray::addIfNotAlreadyThere(), and getAllTests().
initialise()
void yup::UnitTest::initialise () virtual
You can optionally implement this method to set up your test.
This method will be called before runTest().
Referenced by performTest().
shutdown()
void yup::UnitTest::shutdown () virtual
You can optionally implement this method to clear up after your test has been run.
This method will be called after runTest() has returned.
Referenced by performTest().
runTest()
virtual void yup::UnitTest::runTest () pure virtual
Implement this method in your subclass to actually run your tests.
The content of your implementation should call beginTest() and expect() to perform the tests.
References beginTest(), and expect().
Referenced by performTest().
beginTest()
void yup::UnitTest::beginTest (const String & testName)
Tells the system that a new subsection of tests is beginning.
This should be called from your runTest() method, and may be called as many times as you like, to demarcate different sets of tests.
Referenced by runTest().
expect()
void yup::UnitTest::expect (bool testResult, const String & failureMessage = String())
Checks that the result of a test is true, and logs this result.
In your runTest() method, you should call this method for each condition that you want to check, e.g.
void runTest()
{
    beginTest ("basic tests");
    expect (x + y == 2);
    expect (getThing() == someThing);
    ...etc...
}
If testResult is true, a pass is logged; if it's false, a failure is logged. If the failure message is specified, it will be written to the log if the test fails.
Referenced by runTest().
expectEquals()
template<class ValueType> void yup::UnitTest::expectEquals (ValueType actual, ValueType expected, String failureMessage = String())
Compares a value to an expected value.
If they are not equal, prints out a message containing the expected and actual values.
References yup::exactlyEqual().
expectNotEquals()
template<class ValueType> void yup::UnitTest::expectNotEquals (ValueType value, ValueType valueToCompareTo, String failureMessage = String())
Checks whether a value is not equal to a comparison value.
If this check fails, prints out a message containing the actual and comparison values.
References yup::exactlyEqual().
expectGreaterThan()
template<class ValueType> void yup::UnitTest::expectGreaterThan (ValueType value, ValueType valueToCompareTo, String failureMessage = String())
Checks whether a value is greater than a comparison value.
If this check fails, prints out a message containing the actual and comparison values.
expectLessThan()
template<class ValueType> void yup::UnitTest::expectLessThan (ValueType value, ValueType valueToCompareTo, String failureMessage = String())
Checks whether a value is less than a comparison value.
If this check fails, prints out a message containing the actual and comparison values.
expectGreaterOrEqual()
template<class ValueType> void yup::UnitTest::expectGreaterOrEqual (ValueType value, ValueType valueToCompareTo, String failureMessage = String())
Checks whether a value is greater or equal to a comparison value.
If this check fails, prints out a message containing the actual and comparison values.
expectLessOrEqual()
template<class ValueType> void yup::UnitTest::expectLessOrEqual (ValueType value, ValueType valueToCompareTo, String failureMessage = String())
Checks whether a value is less or equal to a comparison value.
If this check fails, prints out a message containing the actual and comparison values.
expectWithinAbsoluteError()
template<class ValueType> void yup::UnitTest::expectWithinAbsoluteError (ValueType actual, ValueType expected, ValueType maxAbsoluteError, String failureMessage = String())
Computes the difference between a value and a comparison value, and if it is larger than a specified maximum value, prints out a message containing the actual and comparison values and the maximum allowed error.
logMessage()
void yup::UnitTest::logMessage (const String & message)
Writes a message to the test log.
This can only be called from within your runTest() method.
getRandom()
Random yup::UnitTest::getRandom () const
Returns a shared RNG that all unit tests should use.
If a test needs random numbers, it's important that when an error is found, the exact circumstances can be re-created in order to re-test the problem, by repeating the test with the same random seed value. To make this possible, the UnitTestRunner class creates a master seed value for the run, writes this number to the log, and then this method returns a Random object based on that seed. All tests should only use this method to create any Random objects that they need.
Note that this method will return an identical object each time it's called for a given run, so if you need several different Random objects, the best way to do that is to call Random::combineSeed() on the result to permute it with a constant value.