YUP: yup::MidiOutput Class Reference
yup::MidiOutput Class Reference final
Represents a midi output device.
Public Member Functions
~MidiOutput () override
Destructor.
MidiDeviceInfo getDeviceInfo () const noexcept
Returns the MidiDeviceInfo struct containing some information about this device.
String getIdentifier () const noexcept
Returns the identifier of this device.
String getName () const noexcept
Returns the name of this device.
void setName (const String &newName) noexcept
Sets a custom name for the device.
void sendMessageNow (const MidiMessage &message)
Sends out a MIDI message immediately.
void sendBlockOfMessagesNow (const MidiBuffer &buffer)
Sends out a sequence of MIDI messages immediately.
void sendBlockOfMessages (const MidiBuffer &buffer, double millisecondCounterToStartAt, double samplesPerSecondForBuffer)
This lets you supply a block of messages that will be sent out at some point in the future.
void clearAllPendingMessages ()
Gets rid of any midi messages that had been added by sendBlockOfMessages().
void startBackgroundThread ()
Starts up a background thread so that the device can send blocks of data.
void stopBackgroundThread ()
Stops the background thread, and clears any pending midi events.
bool isBackgroundThreadRunning () const noexcept
Returns true if the background thread used to send blocks of data is running.
Static Public Member Functions
static Array< MidiDeviceInfo > getAvailableDevices ()
Returns a list of the available midi output devices.
static MidiDeviceInfo getDefaultDevice ()
Returns the MidiDeviceInfo of the default midi output device to use.
static std::unique_ptr< MidiOutput > openDevice (const String &deviceIdentifier)
Tries to open one of the midi output devices.
static std::unique_ptr< MidiOutput > createNewDevice (const String &deviceName)
This will try to create a new midi output device (only available on Linux, macOS and iOS).
Detailed Description
Represents a midi output device.
To create one of these, use the static getAvailableDevices() method to find out what outputs are available, and then use the openDevice() method to try to open one.
See also
MidiInput
Constructor & Destructor Documentation
~MidiOutput()
yup::MidiOutput::~MidiOutput () override
Destructor.
Member Function Documentation
getAvailableDevices()
Array< MidiDeviceInfo > yup::MidiOutput::getAvailableDevices () static
Returns a list of the available midi output devices.
You can open one of the devices by passing its identifier into the openDevice() method.
See also
MidiDeviceInfo, getDevices, getDefaultDeviceIndex, openDevice
getDefaultDevice()
MidiDeviceInfo yup::MidiOutput::getDefaultDevice () static
Returns the MidiDeviceInfo of the default midi output device to use.
openDevice()
std::unique_ptr< MidiOutput > yup::MidiOutput::openDevice (const String & deviceIdentifier) static
Tries to open one of the midi output devices.
This will return a MidiOutput object if it manages to open it, you can then send messages to this device.
If the device can't be opened, this will return an empty object.
Parameters
deviceIdentifier the ID of the device to open - use the getAvailableDevices() method to find the available devices that can be opened
See also
getDevices
Referenced by yup::AudioDeviceManager::setDefaultMidiOutputDevice().
createNewDevice()
std::unique_ptr< MidiOutput > yup::MidiOutput::createNewDevice (const String & deviceName) static
This will try to create a new midi output device (only available on Linux, macOS and iOS).
This will attempt to create a new midi output device with the specified name that other apps can connect to and use as their midi input.
NB - if you are calling this method on iOS you must have enabled the "Audio Background Capability" setting in the iOS exporter otherwise this method will fail.
Returns an empty object if a device can't be created.
Parameters
deviceName the name of the device to create
getDeviceInfo()
MidiDeviceInfo yup::MidiOutput::getDeviceInfo () const noexcept
Returns the MidiDeviceInfo struct containing some information about this device.
getIdentifier()
String yup::MidiOutput::getIdentifier () const noexcept
Returns the identifier of this device.
getName()
String yup::MidiOutput::getName () const noexcept
Returns the name of this device.
setName()
void yup::MidiOutput::setName (const String & newName) noexcept
Sets a custom name for the device.
sendMessageNow()
void yup::MidiOutput::sendMessageNow (const MidiMessage & message)
Sends out a MIDI message immediately.
References clearAllPendingMessages(), sendBlockOfMessages(), sendBlockOfMessagesNow(), startBackgroundThread(), and stopBackgroundThread().
Referenced by sendBlockOfMessagesNow().
sendBlockOfMessagesNow()
void yup::MidiOutput::sendBlockOfMessagesNow (const MidiBuffer & buffer)
Sends out a sequence of MIDI messages immediately.
References sendMessageNow().
Referenced by sendMessageNow().
sendBlockOfMessages()
void yup::MidiOutput::sendBlockOfMessages (const MidiBuffer & buffer, double millisecondCounterToStartAt, double samplesPerSecondForBuffer)
This lets you supply a block of messages that will be sent out at some point in the future.
The MidiOutput class has an internal thread that can send out timestamped messages - this appends a set of messages to its internal buffer, ready for sending.
This will only work if you've already started the thread with startBackgroundThread().
A time is specified, at which the block of messages should be sent. This time uses the same time base as Time::getMillisecondCounter(), and must be in the future.
The samplesPerSecondForBuffer parameter indicates the number of samples per second used by the MidiBuffer. Each event in a MidiBuffer has a sample position, and the samplesPerSecondForBuffer value is needed to convert this sample position to a real time.
References yup::Thread::isThreadRunning(), and yup::Thread::notify().
Referenced by sendMessageNow().
clearAllPendingMessages()
void yup::MidiOutput::clearAllPendingMessages ()
Gets rid of any midi messages that had been added by sendBlockOfMessages().
Referenced by sendMessageNow().
startBackgroundThread()
void yup::MidiOutput::startBackgroundThread ()
Starts up a background thread so that the device can send blocks of data.
Call this to get the device ready, before using sendBlockOfMessages().
References yup::Thread::startThread().
Referenced by sendMessageNow().
stopBackgroundThread()
void yup::MidiOutput::stopBackgroundThread ()
Stops the background thread, and clears any pending midi events.
See also
startBackgroundThread
References yup::Thread::stopThread().
Referenced by sendMessageNow().
isBackgroundThreadRunning()
bool yup::MidiOutput::isBackgroundThreadRunning () const noexcept
Returns true if the background thread used to send blocks of data is running.
See also
startBackgroundThread, stopBackgroundThread
References yup::Thread::isThreadRunning().