YUP: yup::MPEZoneLayout Class Reference
yup::MPEZoneLayout Class Reference
This class represents the current MPE zone layout of a device capable of handling MPE.
Classes
class Listener
Listener class.
Public Member Functions
MPEZoneLayout ()=default
Creates a layout with inactive upper and lower zones.
MPEZoneLayout (MPEZone lower, MPEZone upper)
Creates a layout with the given upper and lower zones.
MPEZoneLayout (MPEZone singleZone)
Creates a layout with a single upper or lower zone, leaving the other zone uninitialised.
MPEZoneLayout (const MPEZoneLayout &other)
MPEZoneLayout & operator= (const MPEZoneLayout &other)
bool operator== (const MPEZoneLayout &other) const
bool operator!= (const MPEZoneLayout &other) const
MPEZone getLowerZone () const noexcept
Returns a struct representing the lower MPE zone.
MPEZone getUpperZone () const noexcept
Returns a struct representing the upper MPE zone.
void setLowerZone (int numMemberChannels=0, int perNotePitchbendRange=48, int masterPitchbendRange=2) noexcept
Sets the lower zone of this layout.
void setUpperZone (int numMemberChannels=0, int perNotePitchbendRange=48, int masterPitchbendRange=2) noexcept
Sets the upper zone of this layout.
void clearAllZones ()
Clears the lower and upper zones of this layout, making them both inactive and disabling MPE mode.
bool isActive () const
Returns true if either of the zones are active.
void processNextMidiEvent (const MidiMessage &message)
Pass incoming MIDI messages to an object of this class if you want the zone layout to properly react to MPE RPN messages like an MPE device.
void processNextMidiBuffer (const MidiBuffer &buffer)
Pass incoming MIDI buffers to an object of this class if you want the zone layout to properly react to MPE RPN messages like an MPE device.
void addListener (Listener *const listenerToAdd) noexcept
Adds a listener.
void removeListener (Listener *const listenerToRemove) noexcept
Removes a listener.
Detailed Description
This class represents the current MPE zone layout of a device capable of handling MPE.
An MPE device can have up to two zones: a lower zone with master channel 1 and allocated MIDI channels increasing from channel 2, and an upper zone with master channel 16 and allocated MIDI channels decreasing from channel 15. MPE mode is enabled on a device when one of these zones is active and disabled when both are inactive.
Use the MPEMessages helper class to convert the zone layout represented by this object to MIDI message sequences that you can send to an Expressive MIDI device to set its zone layout, add zones etc.
See also
MPEInstrument
Constructor & Destructor Documentation
MPEZoneLayout() [1/4]
yup::MPEZoneLayout::MPEZoneLayout () default
Creates a layout with inactive upper and lower zones.
References MPEZoneLayout().
Referenced by MPEZoneLayout(), MPEZoneLayout(), operator!=(), operator=(), operator==(), and yup::MPEZoneLayout::Listener::zoneLayoutChanged().
MPEZoneLayout() [2/4]
yup::MPEZoneLayout::MPEZoneLayout (MPEZone lower, MPEZone upper)
Creates a layout with the given upper and lower zones.
MPEZoneLayout() [3/4]
yup::MPEZoneLayout::MPEZoneLayout (MPEZone singleZone)
Creates a layout with a single upper or lower zone, leaving the other zone uninitialised.
MPEZoneLayout() [4/4]
yup::MPEZoneLayout::MPEZoneLayout (const MPEZoneLayout & other)
References MPEZoneLayout().
Member Function Documentation
operator=()
MPEZoneLayout & yup::MPEZoneLayout::operator= (const MPEZoneLayout & other)
References MPEZoneLayout().
operator==()
bool yup::MPEZoneLayout::operator== (const MPEZoneLayout & other) const
References MPEZoneLayout().
operator!=()
bool yup::MPEZoneLayout::operator!= (const MPEZoneLayout & other) const
References MPEZoneLayout().
getLowerZone()
MPEZone yup::MPEZoneLayout::getLowerZone () const noexcept
Returns a struct representing the lower MPE zone.
Referenced by yup::MPEMessages::setZoneLayout().
getUpperZone()
MPEZone yup::MPEZoneLayout::getUpperZone () const noexcept
Returns a struct representing the upper MPE zone.
Referenced by yup::MPEMessages::setZoneLayout().
setLowerZone()
void yup::MPEZoneLayout::setLowerZone (int numMemberChannels = 0, int perNotePitchbendRange = 48, int masterPitchbendRange = 2) noexcept
Sets the lower zone of this layout.
setUpperZone()
void yup::MPEZoneLayout::setUpperZone (int numMemberChannels = 0, int perNotePitchbendRange = 48, int masterPitchbendRange = 2) noexcept
Sets the upper zone of this layout.
clearAllZones()
void yup::MPEZoneLayout::clearAllZones ()
Clears the lower and upper zones of this layout, making them both inactive and disabling MPE mode.
References yup::MPEZone::lower, and yup::MPEZone::upper.
isActive()
bool yup::MPEZoneLayout::isActive () const
Returns true if either of the zones are active.
References isActive().
Referenced by isActive().
processNextMidiEvent()
void yup::MPEZoneLayout::processNextMidiEvent (const MidiMessage & message)
Pass incoming MIDI messages to an object of this class if you want the zone layout to properly react to MPE RPN messages like an MPE device.
MPEMessages::rpnNumber will add or remove zones; RPN 0 will set the per-note or master pitchbend ranges.
Any other MIDI messages will be ignored by this class.
See also
MPEMessages
References yup::MidiMessage::getChannel(), yup::MidiMessage::getControllerNumber(), yup::MidiMessage::getControllerValue(), and yup::MidiMessage::isController().
Referenced by processNextMidiBuffer().
processNextMidiBuffer()
void yup::MPEZoneLayout::processNextMidiBuffer (const MidiBuffer & buffer)
Pass incoming MIDI buffers to an object of this class if you want the zone layout to properly react to MPE RPN messages like an MPE device.
MPEMessages::rpnNumber will add or remove zones; RPN 0 will set the per-note or master pitchbend ranges.
Any other MIDI messages will be ignored by this class.
See also
MPEMessages
References processNextMidiEvent().
addListener()
void yup::MPEZoneLayout::addListener (Listener *const listenerToAdd) noexcept
Adds a listener.
removeListener()
void yup::MPEZoneLayout::removeListener (Listener *const listenerToRemove) noexcept
Removes a listener.