YUP: yup::StyledText Class Reference
yup::StyledText Class Reference
Classes
struct RenderStyle
struct TextModifier
Public Types
enum HorizontalAlign : uint8_t { left , center , right , justified }
enum VerticalAlign : uint8_t { top , middle , bottom }
enum TextOverflow : uint8_t { visible , ellipsis }
enum TextOrigin : uint8_t { topOrigin , baseline }
enum TextWrap : uint8_t { wrap = 0 , noWrap = 1 }
Public Member Functions
StyledText ()
bool isEmpty () const
bool needsUpdate () const
TextModifier startUpdate ()
TextOverflow getOverflow () const
HorizontalAlign getHorizontalAlign () const
VerticalAlign getVerticalAlign () const
Size< float > getMaxSize () const
float getParagraphSpacing () const
TextWrap getWrap () const
Rectangle< float > getComputedTextBounds () const
Point< float > getOffset (const Rectangle< float > &area) const
Span< const rive::OrderedLine > getOrderedLines () const
Span< const RenderStyle *const > getRenderStyles () const
int getGlyphIndexAtPosition (const Point< float > &position) const
Find the glyph index at a given position in the text area.
Rectangle< float > getCaretBounds (int characterIndex) const
Get the bounds of the caret at a given character position.
std::vector< Rectangle< float > > getSelectionRectangles (int startIndex, int endIndex) const
Returns all selection rectangles for multiline selections.
bool isValidCharacterIndex (int characterIndex) const
Validates if a character index is within valid bounds.
Member Enumeration Documentation
HorizontalAlign
enum yup::StyledText::HorizontalAlign : uint8_t
Enumerator
left
center
right
justified
VerticalAlign
enum yup::StyledText::VerticalAlign : uint8_t
Enumerator
top
middle
bottom
TextOverflow
enum yup::StyledText::TextOverflow : uint8_t
Enumerator
visible
ellipsis
TextOrigin
enum yup::StyledText::TextOrigin : uint8_t
Enumerator
topOrigin
baseline
TextWrap
enum yup::StyledText::TextWrap : uint8_t
Enumerator
wrap
noWrap
Constructor & Destructor Documentation
StyledText()
yup::StyledText::StyledText ()
Referenced by yup::StyledText::TextModifier::TextModifier().
Member Function Documentation
isEmpty()
bool yup::StyledText::isEmpty () const
Referenced by yup::Graphics::fillFittedText(), and yup::Graphics::strokeFittedText().
needsUpdate()
bool yup::StyledText::needsUpdate () const
Referenced by yup::Graphics::fillFittedText(), and yup::Graphics::strokeFittedText().
startUpdate()
StyledText::TextModifier yup::StyledText::startUpdate ()
getOverflow()
StyledText::TextOverflow yup::StyledText::getOverflow () const
getHorizontalAlign()
StyledText::HorizontalAlign yup::StyledText::getHorizontalAlign () const
Referenced by getOffset().
getVerticalAlign()
StyledText::VerticalAlign yup::StyledText::getVerticalAlign () const
Referenced by getOffset().
getMaxSize()
Size< float > yup::StyledText::getMaxSize () const
getParagraphSpacing()
float yup::StyledText::getParagraphSpacing () const
getWrap()
StyledText::TextWrap yup::StyledText::getWrap () const
getComputedTextBounds()
Rectangle< float > yup::StyledText::getComputedTextBounds () const
getOffset()
Point< float > yup::StyledText::getOffset (const Rectangle< float > & area) const
References bottom, center, yup::Rectangle< ValueType >::getHeight(), getHorizontalAlign(), getVerticalAlign(), yup::Rectangle< ValueType >::getWidth(), middle, right, yup::Point< ValueType >::setX(), and yup::Point< ValueType >::setY().
getOrderedLines()
Span< const rive::OrderedLine > yup::StyledText::getOrderedLines () const
getRenderStyles()
Span< const StyledText::RenderStyle *const > yup::StyledText::getRenderStyles () const
getGlyphIndexAtPosition()
int yup::StyledText::getGlyphIndexAtPosition (const Point< float > & position) const
Find the glyph index at a given position in the text area.
Parameters
position The position to check
Returns
The glyph index at the position, or -1 if not found
References yup::Point< ValueType >::getX(), yup::Point< ValueType >::getY(), and yup::jlimit().
getCaretBounds()
Rectangle< float > yup::StyledText::getCaretBounds (int characterIndex) const
Get the bounds of the caret at a given character position.
Parameters
characterIndex The character index to get bounds for
Returns
Rectangle representing the caret bounds
getSelectionRectangles()
std::vector< Rectangle< float > > yup::StyledText::getSelectionRectangles (int startIndex, int endIndex) const
Returns all selection rectangles for multiline selections.
Parameters
startIndex The start character index
endIndex The end character index
Returns
A vector of rectangles representing the selection
isValidCharacterIndex()
bool yup::StyledText::isValidCharacterIndex (int characterIndex) const
Validates if a character index is within valid bounds.
Parameters
characterIndex The character index to validate
Returns
True if the index is valid