codecov:
  require_ci_to_pass: yes

coverage:
  precision: 2
  round: down
  range: "70...100"

  status:
    project:
      default:
        informational: true
        base: auto
        target: 80%
        threshold: 5%
        flags:
          - cpp
    patch:
      default:
        informational: true
        base: auto
        target: 80%
        threshold: 5%

flags:
  cpp: { paths: [modules/], carryforward: true }

ignore:
  - "thirdparty/**/*"
  - "examples/**/*"
  - "tests/**/*"
  - "tools/**/*"
  - "cmake/**/*"
  - "docs/**/*"
  - "modules/*/native/**/*"

comment:
  layout: "header, reach, diff, flags, files, footer"
  behavior: default
  require_changes: false
