YUP: yup::Colors Namespace Reference
yup::Colors Namespace Reference
Functions
std::optional< Color > getNamedColor (StringRef colorName)
Return one of the named colors.
Variables
constexpr Color black = Color (0xff000000)
constexpr Color white = Color (0xffffffff)
constexpr Color transparentBlack = Color (0x00000000)
constexpr Color transparentWhite = Color (0x00ffffff)
constexpr Color aliceblue = Color (0xfff0f8ff)
constexpr Color antiquewhite = Color (0xfffaebd7)
constexpr Color aqua = Color (0xff00ffff)
constexpr Color aquamarine = Color (0xff7fffd4)
constexpr Color azure = Color (0xfff0ffff)
constexpr Color beige = Color (0xfff5f5dc)
constexpr Color bisque = Color (0xffffe4c4)
constexpr Color blanchedalmond = Color (0xffffebcd)
constexpr Color blue = Color (0xff0000ff)
constexpr Color blueviolet = Color (0xff8a2be2)
constexpr Color brown = Color (0xffa52a2a)
constexpr Color burlywood = Color (0xffdeb887)
constexpr Color cadetblue = Color (0xff5f9ea0)
constexpr Color chartreuse = Color (0xff7fff00)
constexpr Color chocolate = Color (0xffd2691e)
constexpr Color coral = Color (0xffff7f50)
constexpr Color cornflowerblue = Color (0xff6495ed)
constexpr Color cornsilk = Color (0xfffff8dc)
constexpr Color crimson = Color (0xffdc143c)
constexpr Color cyan = Color (0xff00ffff)
constexpr Color darkblue = Color (0xff00008b)
constexpr Color darkcyan = Color (0xff008b8b)
constexpr Color darkgoldenrod = Color (0xffb8860b)
constexpr Color darkgray = Color (0xffa9a9a9)
constexpr Color darkgreen = Color (0xff006400)
constexpr Color darkkhaki = Color (0xffbdb76b)
constexpr Color darkmagenta = Color (0xff8b008b)
constexpr Color darkolivegreen = Color (0xff556b2f)
constexpr Color darkorange = Color (0xffff8c00)
constexpr Color darkorchid = Color (0xff9932cc)
constexpr Color darkred = Color (0xff8b0000)
constexpr Color darksalmon = Color (0xffe9967a)
constexpr Color darkseagreen = Color (0xff8fbc8f)
constexpr Color darkslateblue = Color (0xff483d8b)
constexpr Color darkslategray = Color (0xff2f4f4f)
constexpr Color darkturquoise = Color (0xff00ced1)
constexpr Color darkviolet = Color (0xff9400d3)
constexpr Color deeppink = Color (0xffff1493)
constexpr Color deepskyblue = Color (0xff00bfff)
constexpr Color dimgray = Color (0xff696969)
constexpr Color dodgerblue = Color (0xff1e90ff)
constexpr Color firebrick = Color (0xffb22222)
constexpr Color floralwhite = Color (0xfffffaf0)
constexpr Color forestgreen = Color (0xff228b22)
constexpr Color fuchsia = Color (0xffff00ff)
constexpr Color gainsboro = Color (0xffdcdcdc)
constexpr Color ghostwhite = Color (0xfff8f8ff)
constexpr Color gold = Color (0xffffd700)
constexpr Color goldenrod = Color (0xffdaa520)
constexpr Color gray = Color (0xff808080)
constexpr Color green = Color (0xff008000)
constexpr Color greenyellow = Color (0xffadff2f)
constexpr Color honeydew = Color (0xfff0fff0)
constexpr Color hotpink = Color (0xffff69b4)
constexpr Color indianred = Color (0xffcd5c5c)
constexpr Color indigo = Color (0xff4b0082)
constexpr Color ivory = Color (0xffffff40)
constexpr Color khaki = Color (0xfff0e68c)
constexpr Color lavender = Color (0xffe6e6fa)
constexpr Color lavenderblush = Color (0xfffff0f5)
constexpr Color lawngreen = Color (0xff7cfc00)
constexpr Color lemonchiffon = Color (0xfffffacd)
constexpr Color lightblue = Color (0xffadd8e6)
constexpr Color lightcoral = Color (0xfff08080)
constexpr Color lightcyan = Color (0xffe0ffff)
constexpr Color lightgoldenrodyellow = Color (0xfffafad2)
constexpr Color lightgray = Color (0xffd3d3d3)
constexpr Color lightgreen = Color (0xff90ee90)
constexpr Color lightpink = Color (0xffffb6c1)
constexpr Color lightsalmon = Color (0xffffa07a)
constexpr Color lightseagreen = Color (0xff20b2aa)
constexpr Color lightskyblue = Color (0xff87cefa)
constexpr Color lightslategray = Color (0xff778899)
constexpr Color lightsteelblue = Color (0xffb0c4de)
constexpr Color lightyellow = Color (0xffffff80)
constexpr Color lime = Color (0xff00ff00)
constexpr Color limegreen = Color (0xff32cd32)
constexpr Color linen = Color (0xfffaf0e6)
constexpr Color magenta = Color (0xffff00ff)
constexpr Color maroon = Color (0xff800000)
constexpr Color mediumaquamarine = Color (0xff66cdaa)
constexpr Color mediumblue = Color (0xff0000cd)
constexpr Color mediumorchid = Color (0xffba55d3)
constexpr Color mediumpurple = Color (0xff9370db)
constexpr Color mediumseagreen = Color (0xff3cb371)
constexpr Color mediumslateblue = Color (0xff7b68ee)
constexpr Color mediumspringgreen = Color (0xff00fa9a)
constexpr Color mediumturquoise = Color (0xff48d1cc)
constexpr Color mediumvioletred = Color (0xffc71585)
constexpr Color midnightblue = Color (0xff191970)
constexpr Color mintcream = Color (0xfff5fffa)
constexpr Color mistyrose = Color (0xffffe4e1)
constexpr Color moccasin = Color (0xffffe4b5)
constexpr Color navajowhite = Color (0xffffdead)
constexpr Color navy = Color (0xff000080)
constexpr Color oldlace = Color (0xfffdf5e6)
constexpr Color olive = Color (0xff808000)
constexpr Color olivedrab = Color (0xff6b8e23)
constexpr Color orange = Color (0xffffa500)
constexpr Color orangered = Color (0xffff4500)
constexpr Color orchid = Color (0xffda70d6)
constexpr Color palegoldenrod = Color (0xffeee8aa)
constexpr Color palegreen = Color (0xff98fb98)
constexpr Color paleturquoise = Color (0xffafeeee)
constexpr Color palevioletred = Color (0xffdb7093)
constexpr Color papayawhip = Color (0xffffefd5)
constexpr Color peachpuff = Color (0xffffdab9)
constexpr Color peru = Color (0xffcd853f)
constexpr Color pink = Color (0xffffc0cb)
constexpr Color plum = Color (0xffdda0dd)
constexpr Color powderblue = Color (0xffb0e0e6)
constexpr Color purple = Color (0xff800080)
constexpr Color red = Color (0xffff0000)
constexpr Color rosybrown = Color (0xffbc8f8f)
constexpr Color royalblue = Color (0xff4169e1)
constexpr Color saddlebrown = Color (0xff8b4513)
constexpr Color salmon = Color (0xfffa8072)
constexpr Color sandybrown = Color (0xfff4a460)
constexpr Color seagreen = Color (0xff2e8b57)
constexpr Color seashell = Color (0xfffff5ee)
constexpr Color sienna = Color (0xffa0522d)
constexpr Color silver = Color (0xffc0c0c0)
constexpr Color skyblue = Color (0xff87ceeb)
constexpr Color slateblue = Color (0xff6a5acd)
constexpr Color slategray = Color (0xff708090)
constexpr Color snow = Color (0xfffffafa)
constexpr Color springgreen = Color (0xff00ff7f)
constexpr Color steelblue = Color (0xff4682b4)
constexpr Color tan = Color (0xffd2b48c)
constexpr Color teal = Color (0xff008080)
constexpr Color thistle = Color (0xffd8bfd8)
constexpr Color tomato = Color (0xffff6347)
constexpr Color turquoise = Color (0xff40e0d0)
constexpr Color violet = Color (0xffee82ee)
constexpr Color wheat = Color (0xfff5deb3)
constexpr Color whitesmoke = Color (0xfff5f5f5)
constexpr Color yellow = Color (0xffffff00)
constexpr Color yellowgreen = Color (0xff9acd32)
Function Documentation
getNamedColor()
std::optional< Color > yup::Colors::getNamedColor (StringRef colorName)
Return one of the named colors.
References aliceblue, antiquewhite, aqua, aquamarine, azure, beige, bisque, black, blanchedalmond, blue, blueviolet, brown, burlywood, cadetblue, chartreuse, chocolate, coral, cornflowerblue, cornsilk, crimson, cyan, darkblue, darkcyan, darkgoldenrod, darkgray, darkgreen, darkkhaki, darkmagenta, darkolivegreen, darkorange, darkorchid, darkred, darksalmon, darkseagreen, darkslateblue, darkslategray, darkturquoise, darkviolet, deeppink, deepskyblue, dimgray, dodgerblue, firebrick, floralwhite, forestgreen, fuchsia, gainsboro, ghostwhite, gold, goldenrod, gray, green, greenyellow, honeydew, hotpink, indianred, indigo, ivory, khaki, lavender, lavenderblush, lawngreen, lemonchiffon, lightblue, lightcoral, lightcyan, lightgoldenrodyellow, lightgray, lightgreen, lightpink, lightsalmon, lightseagreen, lightskyblue, lightslategray, lightsteelblue, lightyellow, lime, limegreen, linen, magenta, maroon, mediumaquamarine, mediumblue, mediumorchid, mediumpurple, mediumseagreen, mediumslateblue, mediumspringgreen, mediumturquoise, mediumvioletred, midnightblue, mintcream, mistyrose, moccasin, navajowhite, navy, oldlace, olive, olivedrab, orange, orangered, orchid, palegoldenrod, palegreen, paleturquoise, palevioletred, papayawhip, peachpuff, peru, pink, plum, powderblue, purple, red, rosybrown, royalblue, saddlebrown, salmon, sandybrown, seagreen, seashell, sienna, silver, skyblue, slateblue, slategray, snow, springgreen, steelblue, tan, teal, thistle, tomato, turquoise, violet, wheat, white, whitesmoke, yellow, and yellowgreen.
Variable Documentation
black
Color yup::Colors::black = Color (0xff000000) constexpr
Referenced by getNamedColor(), and yup::paintTextEditor().
white
Color yup::Colors::white = Color (0xffffffff) constexpr
Referenced by yup::createThemeVersion1(), getNamedColor(), yup::paintLabel(), yup::paintTextButton(), and yup::paintTextEditor().
transparentBlack
Color yup::Colors::transparentBlack = Color (0x00000000) constexpr
Referenced by yup::createThemeVersion1().
transparentWhite
Color yup::Colors::transparentWhite = Color (0x00ffffff) constexpr
aliceblue
Color yup::Colors::aliceblue = Color (0xfff0f8ff) constexpr
Referenced by getNamedColor().
antiquewhite
Color yup::Colors::antiquewhite = Color (0xfffaebd7) constexpr
Referenced by getNamedColor().
aqua
Color yup::Colors::aqua = Color (0xff00ffff) constexpr
Referenced by getNamedColor().
aquamarine
Color yup::Colors::aquamarine = Color (0xff7fffd4) constexpr
Referenced by getNamedColor().
azure
Color yup::Colors::azure = Color (0xfff0ffff) constexpr
Referenced by getNamedColor().
beige
Color yup::Colors::beige = Color (0xfff5f5dc) constexpr
Referenced by getNamedColor().
bisque
Color yup::Colors::bisque = Color (0xffffe4c4) constexpr
Referenced by getNamedColor().
blanchedalmond
Color yup::Colors::blanchedalmond = Color (0xffffebcd) constexpr
Referenced by getNamedColor().
blue
Color yup::Colors::blue = Color (0xff0000ff) constexpr
Referenced by getNamedColor().
blueviolet
Color yup::Colors::blueviolet = Color (0xff8a2be2) constexpr
Referenced by getNamedColor().
brown
Color yup::Colors::brown = Color (0xffa52a2a) constexpr
Referenced by getNamedColor().
burlywood
Color yup::Colors::burlywood = Color (0xffdeb887) constexpr
Referenced by getNamedColor().
cadetblue
Color yup::Colors::cadetblue = Color (0xff5f9ea0) constexpr
Referenced by getNamedColor().
chartreuse
Color yup::Colors::chartreuse = Color (0xff7fff00) constexpr
Referenced by getNamedColor().
chocolate
Color yup::Colors::chocolate = Color (0xffd2691e) constexpr
Referenced by getNamedColor().
coral
Color yup::Colors::coral = Color (0xffff7f50) constexpr
Referenced by getNamedColor().
cornflowerblue
Color yup::Colors::cornflowerblue = Color (0xff6495ed) constexpr
Referenced by getNamedColor(), yup::paintTextButton(), and yup::paintTextEditor().
cornsilk
Color yup::Colors::cornsilk = Color (0xfffff8dc) constexpr
Referenced by getNamedColor().
crimson
Color yup::Colors::crimson = Color (0xffdc143c) constexpr
Referenced by getNamedColor().
cyan
Color yup::Colors::cyan = Color (0xff00ffff) constexpr
Referenced by getNamedColor().
darkblue
Color yup::Colors::darkblue = Color (0xff00008b) constexpr
Referenced by getNamedColor().
darkcyan
Color yup::Colors::darkcyan = Color (0xff008b8b) constexpr
Referenced by getNamedColor().
darkgoldenrod
Color yup::Colors::darkgoldenrod = Color (0xffb8860b) constexpr
Referenced by getNamedColor().
darkgray
Color yup::Colors::darkgray = Color (0xffa9a9a9) constexpr
Referenced by getNamedColor().
darkgreen
Color yup::Colors::darkgreen = Color (0xff006400) constexpr
Referenced by getNamedColor().
darkkhaki
Color yup::Colors::darkkhaki = Color (0xffbdb76b) constexpr
Referenced by getNamedColor().
darkmagenta
Color yup::Colors::darkmagenta = Color (0xff8b008b) constexpr
Referenced by getNamedColor().
darkolivegreen
Color yup::Colors::darkolivegreen = Color (0xff556b2f) constexpr
Referenced by getNamedColor().
darkorange
Color yup::Colors::darkorange = Color (0xffff8c00) constexpr
Referenced by getNamedColor().
darkorchid
Color yup::Colors::darkorchid = Color (0xff9932cc) constexpr
Referenced by getNamedColor().
darkred
Color yup::Colors::darkred = Color (0xff8b0000) constexpr
Referenced by getNamedColor().
darksalmon
Color yup::Colors::darksalmon = Color (0xffe9967a) constexpr
Referenced by getNamedColor().
darkseagreen
Color yup::Colors::darkseagreen = Color (0xff8fbc8f) constexpr
Referenced by getNamedColor().
darkslateblue
Color yup::Colors::darkslateblue = Color (0xff483d8b) constexpr
Referenced by getNamedColor().
darkslategray
Color yup::Colors::darkslategray = Color (0xff2f4f4f) constexpr
Referenced by getNamedColor().
darkturquoise
Color yup::Colors::darkturquoise = Color (0xff00ced1) constexpr
Referenced by getNamedColor().
darkviolet
Color yup::Colors::darkviolet = Color (0xff9400d3) constexpr
Referenced by getNamedColor().
deeppink
Color yup::Colors::deeppink = Color (0xffff1493) constexpr
Referenced by getNamedColor().
deepskyblue
Color yup::Colors::deepskyblue = Color (0xff00bfff) constexpr
Referenced by getNamedColor().
dimgray
Color yup::Colors::dimgray = Color (0xff696969) constexpr
Referenced by getNamedColor(), and yup::paintTextButton().
dodgerblue
Color yup::Colors::dodgerblue = Color (0xff1e90ff) constexpr
Referenced by getNamedColor().
firebrick
Color yup::Colors::firebrick = Color (0xffb22222) constexpr
Referenced by getNamedColor().
floralwhite
Color yup::Colors::floralwhite = Color (0xfffffaf0) constexpr
Referenced by getNamedColor().
forestgreen
Color yup::Colors::forestgreen = Color (0xff228b22) constexpr
Referenced by getNamedColor().
fuchsia
Color yup::Colors::fuchsia = Color (0xffff00ff) constexpr
Referenced by getNamedColor().
gainsboro
Color yup::Colors::gainsboro = Color (0xffdcdcdc) constexpr
Referenced by getNamedColor().
ghostwhite
Color yup::Colors::ghostwhite = Color (0xfff8f8ff) constexpr
Referenced by getNamedColor().
gold
Color yup::Colors::gold = Color (0xffffd700) constexpr
Referenced by getNamedColor().
goldenrod
Color yup::Colors::goldenrod = Color (0xffdaa520) constexpr
Referenced by getNamedColor().
gray
Color yup::Colors::gray = Color (0xff808080) constexpr
Referenced by getNamedColor(), yup::paintTextButton(), and yup::paintTextEditor().
green
Color yup::Colors::green = Color (0xff008000) constexpr
Referenced by getNamedColor().
greenyellow
Color yup::Colors::greenyellow = Color (0xffadff2f) constexpr
Referenced by getNamedColor().
honeydew
Color yup::Colors::honeydew = Color (0xfff0fff0) constexpr
Referenced by getNamedColor().
hotpink
Color yup::Colors::hotpink = Color (0xffff69b4) constexpr
Referenced by getNamedColor().
indianred
Color yup::Colors::indianred = Color (0xffcd5c5c) constexpr
Referenced by getNamedColor().
indigo
Color yup::Colors::indigo = Color (0xff4b0082) constexpr
Referenced by getNamedColor().
ivory
Color yup::Colors::ivory = Color (0xffffff40) constexpr
Referenced by getNamedColor().
khaki
Color yup::Colors::khaki = Color (0xfff0e68c) constexpr
Referenced by getNamedColor().
lavender
Color yup::Colors::lavender = Color (0xffe6e6fa) constexpr
Referenced by getNamedColor().
lavenderblush
Color yup::Colors::lavenderblush = Color (0xfffff0f5) constexpr
Referenced by getNamedColor().
lawngreen
Color yup::Colors::lawngreen = Color (0xff7cfc00) constexpr
Referenced by getNamedColor().
lemonchiffon
Color yup::Colors::lemonchiffon = Color (0xfffffacd) constexpr
Referenced by getNamedColor().
lightblue
Color yup::Colors::lightblue = Color (0xffadd8e6) constexpr
Referenced by getNamedColor().
lightcoral
Color yup::Colors::lightcoral = Color (0xfff08080) constexpr
Referenced by getNamedColor().
lightcyan
Color yup::Colors::lightcyan = Color (0xffe0ffff) constexpr
Referenced by getNamedColor().
lightgoldenrodyellow
Color yup::Colors::lightgoldenrodyellow = Color (0xfffafad2) constexpr
Referenced by getNamedColor().
lightgray
Color yup::Colors::lightgray = Color (0xffd3d3d3) constexpr
Referenced by getNamedColor().
lightgreen
Color yup::Colors::lightgreen = Color (0xff90ee90) constexpr
Referenced by getNamedColor().
lightpink
Color yup::Colors::lightpink = Color (0xffffb6c1) constexpr
Referenced by getNamedColor().
lightsalmon
Color yup::Colors::lightsalmon = Color (0xffffa07a) constexpr
Referenced by getNamedColor().
lightseagreen
Color yup::Colors::lightseagreen = Color (0xff20b2aa) constexpr
Referenced by getNamedColor().
lightskyblue
Color yup::Colors::lightskyblue = Color (0xff87cefa) constexpr
Referenced by getNamedColor().
lightslategray
Color yup::Colors::lightslategray = Color (0xff778899) constexpr
Referenced by getNamedColor().
lightsteelblue
Color yup::Colors::lightsteelblue = Color (0xffb0c4de) constexpr
Referenced by getNamedColor().
lightyellow
Color yup::Colors::lightyellow = Color (0xffffff80) constexpr
Referenced by getNamedColor().
lime
Color yup::Colors::lime = Color (0xff00ff00) constexpr
Referenced by getNamedColor().
limegreen
Color yup::Colors::limegreen = Color (0xff32cd32) constexpr
Referenced by getNamedColor().
linen
Color yup::Colors::linen = Color (0xfffaf0e6) constexpr
Referenced by getNamedColor().
magenta
Color yup::Colors::magenta = Color (0xffff00ff) constexpr
Referenced by getNamedColor().
maroon
Color yup::Colors::maroon = Color (0xff800000) constexpr
Referenced by getNamedColor().
mediumaquamarine
Color yup::Colors::mediumaquamarine = Color (0xff66cdaa) constexpr
Referenced by getNamedColor().
mediumblue
Color yup::Colors::mediumblue = Color (0xff0000cd) constexpr
Referenced by getNamedColor().
mediumorchid
Color yup::Colors::mediumorchid = Color (0xffba55d3) constexpr
Referenced by getNamedColor().
mediumpurple
Color yup::Colors::mediumpurple = Color (0xff9370db) constexpr
Referenced by getNamedColor().
mediumseagreen
Color yup::Colors::mediumseagreen = Color (0xff3cb371) constexpr
Referenced by getNamedColor().
mediumslateblue
Color yup::Colors::mediumslateblue = Color (0xff7b68ee) constexpr
Referenced by getNamedColor().
mediumspringgreen
Color yup::Colors::mediumspringgreen = Color (0xff00fa9a) constexpr
Referenced by getNamedColor().
mediumturquoise
Color yup::Colors::mediumturquoise = Color (0xff48d1cc) constexpr
Referenced by getNamedColor().
mediumvioletred
Color yup::Colors::mediumvioletred = Color (0xffc71585) constexpr
Referenced by getNamedColor().
midnightblue
Color yup::Colors::midnightblue = Color (0xff191970) constexpr
Referenced by getNamedColor().
mintcream
Color yup::Colors::mintcream = Color (0xfff5fffa) constexpr
Referenced by getNamedColor().
mistyrose
Color yup::Colors::mistyrose = Color (0xffffe4e1) constexpr
Referenced by getNamedColor().
moccasin
Color yup::Colors::moccasin = Color (0xffffe4b5) constexpr
Referenced by getNamedColor().
navajowhite
Color yup::Colors::navajowhite = Color (0xffffdead) constexpr
Referenced by getNamedColor().
navy
Color yup::Colors::navy = Color (0xff000080) constexpr
Referenced by getNamedColor().
oldlace
Color yup::Colors::oldlace = Color (0xfffdf5e6) constexpr
Referenced by getNamedColor().
olive
Color yup::Colors::olive = Color (0xff808000) constexpr
Referenced by getNamedColor().
olivedrab
Color yup::Colors::olivedrab = Color (0xff6b8e23) constexpr
Referenced by getNamedColor().
orange
Color yup::Colors::orange = Color (0xffffa500) constexpr
Referenced by getNamedColor().
orangered
Color yup::Colors::orangered = Color (0xffff4500) constexpr
Referenced by getNamedColor().
orchid
Color yup::Colors::orchid = Color (0xffda70d6) constexpr
Referenced by getNamedColor().
palegoldenrod
Color yup::Colors::palegoldenrod = Color (0xffeee8aa) constexpr
Referenced by getNamedColor().
palegreen
Color yup::Colors::palegreen = Color (0xff98fb98) constexpr
Referenced by getNamedColor().
paleturquoise
Color yup::Colors::paleturquoise = Color (0xffafeeee) constexpr
Referenced by getNamedColor().
palevioletred
Color yup::Colors::palevioletred = Color (0xffdb7093) constexpr
Referenced by getNamedColor().
papayawhip
Color yup::Colors::papayawhip = Color (0xffffefd5) constexpr
Referenced by getNamedColor().
peachpuff
Color yup::Colors::peachpuff = Color (0xffffdab9) constexpr
Referenced by getNamedColor().
peru
Color yup::Colors::peru = Color (0xffcd853f) constexpr
Referenced by getNamedColor().
pink
Color yup::Colors::pink = Color (0xffffc0cb) constexpr
Referenced by getNamedColor().
plum
Color yup::Colors::plum = Color (0xffdda0dd) constexpr
Referenced by getNamedColor().
powderblue
Color yup::Colors::powderblue = Color (0xffb0e0e6) constexpr
Referenced by getNamedColor().
purple
Color yup::Colors::purple = Color (0xff800080) constexpr
Referenced by getNamedColor().
red
Color yup::Colors::red = Color (0xffff0000) constexpr
Referenced by getNamedColor().
rosybrown
Color yup::Colors::rosybrown = Color (0xffbc8f8f) constexpr
Referenced by getNamedColor().
royalblue
Color yup::Colors::royalblue = Color (0xff4169e1) constexpr
Referenced by getNamedColor().
saddlebrown
Color yup::Colors::saddlebrown = Color (0xff8b4513) constexpr
Referenced by getNamedColor().
salmon
Color yup::Colors::salmon = Color (0xfffa8072) constexpr
Referenced by getNamedColor().
sandybrown
Color yup::Colors::sandybrown = Color (0xfff4a460) constexpr
Referenced by getNamedColor().
seagreen
Color yup::Colors::seagreen = Color (0xff2e8b57) constexpr
Referenced by getNamedColor().
seashell
Color yup::Colors::seashell = Color (0xfffff5ee) constexpr
Referenced by getNamedColor().
sienna
Color yup::Colors::sienna = Color (0xffa0522d) constexpr
Referenced by getNamedColor().
silver
Color yup::Colors::silver = Color (0xffc0c0c0) constexpr
Referenced by getNamedColor().
skyblue
Color yup::Colors::skyblue = Color (0xff87ceeb) constexpr
Referenced by getNamedColor().
slateblue
Color yup::Colors::slateblue = Color (0xff6a5acd) constexpr
Referenced by getNamedColor().
slategray
Color yup::Colors::slategray = Color (0xff708090) constexpr
Referenced by getNamedColor().
snow
Color yup::Colors::snow = Color (0xfffffafa) constexpr
Referenced by getNamedColor().
springgreen
Color yup::Colors::springgreen = Color (0xff00ff7f) constexpr
Referenced by getNamedColor().
steelblue
Color yup::Colors::steelblue = Color (0xff4682b4) constexpr
Referenced by getNamedColor().
tan
Color yup::Colors::tan = Color (0xffd2b48c) constexpr
Referenced by getNamedColor().
teal
Color yup::Colors::teal = Color (0xff008080) constexpr
Referenced by getNamedColor().
thistle
Color yup::Colors::thistle = Color (0xffd8bfd8) constexpr
Referenced by getNamedColor().
tomato
Color yup::Colors::tomato = Color (0xffff6347) constexpr
Referenced by getNamedColor().
turquoise
Color yup::Colors::turquoise = Color (0xff40e0d0) constexpr
Referenced by getNamedColor().
violet
Color yup::Colors::violet = Color (0xffee82ee) constexpr
Referenced by getNamedColor().
wheat
Color yup::Colors::wheat = Color (0xfff5deb3) constexpr
Referenced by getNamedColor().
whitesmoke
Color yup::Colors::whitesmoke = Color (0xfff5f5f5) constexpr
Referenced by getNamedColor().
yellow
Color yup::Colors::yellow = Color (0xffffff00) constexpr
Referenced by getNamedColor().
yellowgreen
Color yup::Colors::yellowgreen = Color (0xff9acd32) constexpr
Referenced by getNamedColor().