YUP: yup::MidiHelpers Namespace Reference
yup::MidiHelpers Namespace Reference
Functions
uint8 initialByte (const int type, const int channel) noexcept
uint8 validVelocity (const int v) noexcept
Function Documentation
initialByte()
uint8 yup::MidiHelpers::initialByte (const int type, const int channel) noexcept
References yup::jlimit().
Referenced by yup::MidiMessage::aftertouchChange(), yup::MidiMessage::channelPressureChange(), yup::MidiMessage::controllerEvent(), yup::MidiMessage::noteOff(), yup::MidiMessage::noteOff(), yup::MidiMessage::noteOn(), yup::MidiMessage::pitchWheel(), and yup::MidiMessage::programChange().
validVelocity()
uint8 yup::MidiHelpers::validVelocity (const int v) noexcept
References yup::jlimit().
Referenced by yup::MidiMessage::floatValueToMidiByte(), yup::MidiMessage::multiplyVelocity(), yup::MidiMessage::noteOff(), and yup::MidiMessage::noteOn().