YUP: yup::SocketHelpers Namespace Reference
yup::SocketHelpers Namespace Reference
Functions
bool isValidPortNumber (int port) noexcept
Function Documentation
isValidPortNumber()
bool yup::SocketHelpers::isValidPortNumber (int port) noexcept
References yup::isPositiveAndBelow().
Referenced by yup::DatagramSocket::bindToPort(), yup::StreamingSocket::bindToPort(), yup::StreamingSocket::connect(), yup::StreamingSocket::createListener(), and yup::DatagramSocket::write().