YUP: yup Namespace Reference
yup Namespace Reference
Namespaces
namespace Colors
namespace FloatVectorHelpers
namespace MidiBufferHelpers
namespace MidiFileHelpers
namespace MidiHelpers
namespace NumberToStringConverters
namespace SampleRateHelpers
namespace SocketHelpers
namespace StringHelpers
namespace TimeHelpers
namespace TokenTypes
namespace TypeHelpers
This namespace contains a few template classes for helping work out class type variations.
namespace UnitTestCategories
namespace universal_midi_packets
namespace URLHelpers
namespace ValueSmoothingTypes
A namespace containing a set of types used for specifying the smoothing behaviour of the SmoothedValue class.
namespace XmlIdentifierChars
namespace XmlOutputFunctions
Classes
class AbstractFifo
Encapsulates the logic required to implement a lock-free FIFO.
class ActionBroadcaster
Manages a list of ActionListeners, and can send them messages.
class ActionListener
Interface class for delivery of events that are sent by an ActionBroadcaster.
class ADSR
A very simple ADSR envelope class.
class AffineTransform
Class representing a 2D affine transformation.
class AndroidDocument
Provides access to a document on Android devices.
class AndroidDocumentInfo
Some information about a document.
class AndroidDocumentInputSource
An InputSource backed by an AndroidDocument.
class AndroidDocumentIterator
An iterator that visits child documents in a directory.
class AndroidDocumentPermission
Represents a permission granted to an application to read and/or write to a particular document or tree.
class ApplicationTheme
Manages the application-wide theme settings.
struct ArgumentList
Holds a list of command-line arguments, and provides useful methods for searching and operating on them.
class Array
Holds a resizable array of primitive or copy-by-value objects.
class ArrayAllocationBase
Implements some basic array storage allocation functions.
class ArrayBase
A basic object container.
class Artboard
Represents a Rive artboard.
class ArtboardFile
Represents a Rive file.
class AsyncUpdater
Has a callback method that is triggered asynchronously.
struct Atomic
A simple wrapper around std::atomic.
class AudioBuffer
A multi-channel buffer containing floating point audio samples.
class AudioBus
Describes a single audio, MIDI, or CV bus for plugin I/O.
class AudioBusLayout
Represents the full input/output bus layout of a plugin processor.
class AudioChannelSet
Represents a set of audio channel types.
class AudioData
This class a container which holds all the classes pertaining to the AudioData::Pointer audio sample format class.
class AudioDeviceManager
Manages the state of some audio and midi i/o devices.
class AudioIODevice
Base class for an audio device with synchronised input and output channels.
class AudioIODeviceCallback
One of these is passed to an AudioIODevice object to stream the audio data in and out.
struct AudioIODeviceCallbackContext
Additional information that may be passed to the AudioIODeviceCallback.
class AudioIODeviceType
Represents a type of audio driver, such as DirectSound, ASIO, CoreAudio, etc.
class AudioParameter
A flexible, thread-safe parameter class with support for custom mapping, string conversion, smoothing, and different parameter types (linear, log, dB, enum, etc).
class AudioParameterBuilder
A builder class for constructing AudioProcessorParameter instances using a fluent-style API.
class AudioParameterHandle
A handle for a parameter of an AudioProcessor.
class AudioPlayHead
A subclass of AudioPlayHead can supply information about the position and status of a moving play head during audio playback.
class AudioProcessLoadMeasurer
Maintains an ongoing measurement of the proportion of time which is being spent inside an audio callback.
class AudioProcessor
Base class for all audio processors.
class AudioProcessorEditor
class AudioSource
Base class for objects that can produce a continuous stream of audio.
struct AudioSourceChannelInfo
Used by AudioSource::getNextAudioBlock().
class AudioSourcePlayer
Wrapper class to continuously stream audio from an audio source to an AudioIODevice.
class AudioTransportSource
An AudioSource that takes a PositionableAudioSource and allows it to be played, stopped, started, etc.
class AudioWorkgroup
A handle to an audio workgroup, which is a collection of realtime threads working together to produce audio by a common deadline.
struct Base64
Contains some static methods for converting between binary and the standard base-64 encoding format.
class BigInteger
An arbitrarily large integer class.
class BitmapData
Represents bitmap pixel data with accessors.
class BufferedInputStream
Wraps another input stream, and reads from it using an intermediate buffer.
class BufferingAudioSource
An AudioSource which takes another source as input, and buffers it using a thread.
class Button
class ByteOrder
Contains static methods for converting the byte order between different endiannesses.
class CallbackMessage
A message that invokes a callback method when it gets delivered.
class ChangeBroadcaster
Holds a list of ChangeListeners, and sends messages to them when instructed.
class ChangeListener
Receives change event callbacks that are sent out by a ChangeBroadcaster.
class ChannelRemappingAudioSource
An AudioSource that takes the audio from another source, and re-maps its input and output channels to a different arrangement.
class CharacterFunctions
A collection of functions for manipulating characters and character strings.
class CharPointer_ASCII
Wraps a pointer to a null-terminated ASCII character string, and provides various methods to operate on the data.
class CharPointer_UTF16
Wraps a pointer to a null-terminated UTF-16 character string, and provides various methods to operate on the data.
class CharPointer_UTF32
Wraps a pointer to a null-terminated UTF-32 character string, and provides various methods to operate on the data.
class CharPointer_UTF8
Wraps a pointer to a null-terminated UTF-8 character string, and provides various methods to operate on the data.
class ChildProcess
Launches and monitors a child process.
class ChildProcessCoordinator
Acts as the coordinator in a coordinator/worker pair of connected processes.
class ChildProcessManager
Manages a set of ChildProcesses and periodically checks their return value.
class ChildProcessWorker
Acts as the worker end of a coordinator/worker pair of connected processes.
class Color
Represents an RGBA color for graphical use.
class ColorGradient
Represents a gradient for graphical use, defined by two colors and their positions.
class Component
The Component class is the base class for all GUI components.
class ComponentNative
Provides platform-native window and rendering capabilities for Components.
class ComponentStyle
The ComponentStyle class is the base class for all components styles.
struct ConsoleApplication
Represents a the set of commands that a console app can perform, and provides helper functions for performing them.
struct ContainerDeletePolicy
Used by container classes as an indirect way to delete an object of a particular type.
class CriticalSection
A re-entrant mutex.
class DatagramSocket
A wrapper for a datagram (UDP) socket.
class Decibels
This class contains some helpful static methods for dealing with decibel values.
class DefaultElementComparator
A simple ElementComparator class that can be used to sort an array of objects that support the '<' operator.
struct DefaultHashFunctions
A simple class to generate hash functions for some primitive types, intended for use with the HashMap class.
class DeletedAtShutdown
Classes derived from this will be automatically deleted when the application exits.
class Desktop
Represents the desktop environment, providing access to screen information and management.
class DirectoryEntry
Describes the attributes of a file or folder.
class DocumentWindow
class DummyCriticalSection
A class that can be used in place of a real CriticalSection object, but which doesn't perform any locking.
class DynamicLibrary
Handles the opening and closing of DLLs.
class DynamicObject
Represents a dynamically implemented object.
struct Enumerated
Returned when dereferencing an EnumerateIterator.
class EnumerateIterator
An iterator that wraps some other iterator, keeping track of the relative position of that iterator based on calls to arithmetic operators such as operator++(), operator--(), operator+(), and operator-().
class ErasedScopeGuard
A ScopeGuard that uses a std::function internally to allow type erasure.
class Expression
A class for dynamically evaluating simple numeric expressions.
class File
Represents a local file or directory.
class FileChooser
A cross-platform file chooser dialog that allows users to select files or directories.
class FileFilter
Interface for deciding which files are suitable for something.
class FileInputSource
A type of InputSource that represents a normal file.
class FileInputStream
An input stream that reads from a local file.
class FileLogger
A simple implementation of a Logger that writes to a file.
class FileOutputStream
An output stream that writes into a local file.
class FileSearchPath
Represents a set of folders that make up a search path.
class FixedSizeFunction< len, Ret(Args...)>
A type similar to std::function that holds a callable object.
class FlagSet
Manages a set of flags using integral types.
class FloatVectorOperations
A collection of simple vector operations on arrays of floating point numbers, accelerated with SIMD instructions where possible and providing all methods from FloatVectorOperationsBase.
struct FloatVectorOperationsBase
A collection of simple vector operations on arrays of floating point numbers, accelerated with SIMD instructions where possible, usually accessed from the FloatVectorOperations class.
class Font
class FromVar
Allows converting a var to an object of arbitrary type.
class GenericInterpolator
An interpolator base class for resampling streams of floats.
class GenericScopedLock
Automatically locks and unlocks a mutex object.
class GenericScopedTryLock
Automatically locks and unlocks a mutex object.
class GenericScopedUnlock
Automatically unlocks and re-locks a mutex object.
class Graphics
A graphical interface for drawing operations within a defined rendering context.
class GraphicsContext
Encapsulates a graphics context that abstracts rendering operations across various APIs.
class GZIPCompressorOutputStream
A stream which uses zlib to compress the data written into it.
class GZIPDecompressorInputStream
This stream will decompress a source-stream using zlib.
class HashMap
Holds a set of mappings between some key/value pairs.
class HeapBlock
Very simple container class to hold a pointer to some data on the heap.
class HeavyweightLeakedObjectDetector
This class is a useful way of tracking down hard to find memory leaks when the regular LeakedObjectDetector isn't enough.
class HighResolutionTimer
A high-resolution periodic timer.
class Identifier
Represents a string identifier, designed for accessing properties by name.
class IIRCoefficients
A set of coefficients for use in an IIRFilter object.
class IIRFilter
An IIR filter that can perform low, high, or band-pass filtering on an audio signal, and which attempts to implement basic thread-safety.
class IIRFilterAudioSource
An AudioSource that performs an IIR filter on another source.
class IIRFilterBase
An IIR filter that can perform low, high, or band-pass filtering on an audio signal.
class Image
Represents an image using BitmapData.
class InputSource
A lightweight object that can create a stream to read some kind of resource.
class InputStream
The base class for streams that read data.
class Interpolators
A collection of different interpolators for resampling streams of floats.
class InterprocessConnection
Manages a simple two-way messaging connection to another process, using either a socket or a named pipe as the transport medium.
class InterprocessConnectionServer
An object that waits for client sockets to connect to a port on this host, and creates InterprocessConnection objects for each one.
class InterProcessLock
Acts as a critical section which processes can use to block each other.
class IPAddress
Represents an IP address.
class IteratorPair
Wraps a pair of iterators, providing member begin() and end() functions that return those iterators.
class JavascriptEngine
A simple javascript interpreter!
class JSON
Contains static methods for converting JSON-formatted text to and from var objects.
struct JSONUtils
A mini namespace to hold utility functions for working with yup::vars.
class KeyModifiers
Represents modifier keys (like Shift, Ctrl, etc.) pressed during a keyboard event.
class KeyPress
Represents a single key press, encapsulating information about the key and any associated modifiers.
class Label
A component that displays text.
class LeakedObjectDetector
Embedding an instance of this class inside another class can be used as a low-overhead way of detecting leaked instances.
class Line
Defines a class for a geometric line in a 2D space.
class LinkedListPointer
Helps to manipulate singly-linked lists of objects.
class ListenerList
Holds a set of objects and can invoke a member function callback on each object in the set with a single call.
class LocalisedStrings
Used to convert strings to localised foreign-language versions.
class LockingAsyncUpdater
A bit like an AsyncUpdater, but guarantees that after cancelPendingUpdate() returns, the async function will never be called until triggerAsyncUpdate() is called again.
class Logger
Acts as an application-wide logging class.
class MACAddress
Represents a MAC network card adapter address ID.
struct MathConstants
Commonly used mathematical constants.
class MemoryAudioSource
An AudioSource which takes some float audio data as an input.
class MemoryBlock
A class to hold a resizable block of raw data.
class MemoryInputStream
Allows a block of data to be accessed as a stream.
class MemoryMappedFile
Maps a file into virtual memory for easy reading and/or writing.
class MemoryOutputStream
Writes data to an internal memory buffer, which grows as required.
class Message
The base class for objects that can be sent to a MessageListener.
class MessageListener
MessageListener subclasses can post and receive Message objects.
class MessageManager
This class is in charge of the application's event-dispatch loop.
class MessageManagerLock
Used to make sure that the calling thread has exclusive access to the message loop.
class MidiBuffer
Holds a sequence of time-stamped midi events.
class MidiBufferIterator
An iterator to move over contiguous raw MIDI data, which Allows iterating over a MidiBuffer using C++11 range-for syntax.
class MidiDataConcatenator
Helper class that takes chunks of incoming midi bytes, packages them into messages, and dispatches them to a midi callback.
struct MidiDeviceInfo
This struct contains information about a MIDI input or output device.
class MidiDeviceListConnection
To find out when the available MIDI devices change, call MidiDeviceListConnection::make(), passing a lambda that will be called on each configuration change.
class MidiFile
Reads/writes standard midi format files.
class MidiInput
Represents a midi input device.
class MidiInputCallback
Receives incoming messages from a physical MIDI input device.
class MidiKeyboardState
Represents a piano keyboard, keeping track of which keys are currently pressed.
class MidiMessage
Encapsulates a MIDI message.
class MidiMessageCollector
Collects incoming realtime MIDI messages and turns them into blocks suitable for processing by a block-based audio callback.
struct MidiMessageMetadata
A view of MIDI message data stored in a contiguous buffer.
class MidiMessageSequence
A sequence of timestamped midi messages.
class MidiOutput
Represents a midi output device.
class MidiRPNDetector
Parses a stream of MIDI data to assemble RPN and NRPN messages from their constituent MIDI CC messages.
class MidiRPNGenerator
Generates an appropriate sequence of MIDI CC messages to represent an RPN or NRPN message.
struct MidiRPNMessage
Represents a MIDI RPN (registered parameter number) or NRPN (non-registered parameter number) message.
class MixerAudioSource
An AudioSource that mixes together the output of a set of other AudioSources.
class MountedVolumeListChangeDetector
An instance of this class will provide callbacks when drives are mounted or unmounted on the system.
class MouseCursor
Represents a mouse cursor image.
class MouseEvent
Contains information about a mouse event.
class MouseListener
class MouseWheelData
class MPEChannelAssigner
This class handles the assignment of new MIDI notes to member channels of an active MPE zone.
class MPEChannelRemapper
This class handles the logic for remapping MIDI note messages from multiple MPE sources onto a specified MPE zone.
class MPEInstrument
This class represents an instrument handling MPE.
class MPEMessages
This helper class contains the necessary helper functions to generate MIDI messages that are exclusive to MPE, such as defining the upper and lower MPE zones and setting per-note and master pitchbend ranges.
struct MPENote
This struct represents a playing MPE note.
class MPESynthesiser
Base class for an MPE-compatible musical device that can play sounds.
struct MPESynthesiserBase
Derive from this class to create a basic audio generator capable of MPE.
class MPESynthesiserVoice
Represents an MPE voice that an MPESynthesiser can use to play a sound.
class MPEValue
This class represents a single value for any of the MPE dimensions of control.
struct MPEZone
This struct represents an MPE zone.
class MPEZoneLayout
This class represents the current MPE zone layout of a device capable of handling MPE.
class MultiTimer
A type of timer class that can run multiple timers with different frequencies, all of which share a single callback.
struct Named
Combines an object with a name.
class NamedPipe
A cross-process pipe that can have data written to and read from it.
class NamedValueSet
Holds a set of named var objects.
struct NetworkServiceDiscovery
Contains classes that implement a simple protocol for broadcasting the availability and location of a discoverable service on the local network, and for maintaining a list of known services.
class NewLine
This class is used for represent a new-line character sequence.
struct NoneSuch
class NormalisableRange
Represents a mapping between an arbitrary range of values and a normalised 0->1 range.
struct NullCheckedInvocation
Some helper methods for checking a callable object before invoking with the specified arguments.
class Optional
A simple optional type.
class OptionalScopedPointer
Holds a pointer to an object which can optionally be deleted when this pointer goes out of scope.
class OutputStream
The base class for streams that write data to some kind of destination.
class OwnedArray
An array designed for holding objects.
class Path
Represents a 2D geometric path.
class PerformanceCounter
A timer for measuring performance of code and dumping the results to a file.
class Point
Represents a 2D point with coordinates of a generic type.
class PositionableAudioSource
A type of AudioSource which can be repositioned.
class Process
Represents the current executable's process.
class PropertySet
A set of named property values, which can be strings, integers, floating point, etc.
class Random
A random number generator.
class Range
A general-purpose range object, that simply represents any linear range with a start and end point.
class RangedDirectoryIterator
Allows iterating over files and folders using C++11 range-for syntax.
class ReadWriteLock
A critical section that allows multiple simultaneous readers.
class Rectangle
Represents a rectangle in 2D space.
class RectangleList
A class that manages a list of rectangles.
class ReferenceCountedArray
Holds a list of objects derived from ReferenceCountedObject, or which implement basic reference-count handling methods.
class ReferenceCountedObject
A base class which provides methods for reference-counting.
class ReferenceCountedObjectPtr
A smart-pointer class which points to a reference-counted object.
class RelativeTime
A relative measure of time.
class ResamplingAudioSource
A type of AudioSource that takes an input source and changes its sample rate.
struct Reservoir
Helper functions for managing buffered readers.
class Result
Represents the 'success' or 'failure' of an operation, and holds an associated error message to describe the error when there's a failure.
class ResultValue
Represents the 'success' or 'failure' of an operation that returns a value, and holds an associated error message to describe the error when there's a failure.
class Reverb
Performs a simple reverb effect on a stream of audio data.
class ReverbAudioSource
An AudioSource that uses the Reverb class to apply a reverb to another AudioSource.
class RuntimePermissions
class ScopedAutoReleasePool
A handy C++ wrapper that creates and deletes an NSAutoreleasePool object using RAII.
class ScopedNoDenormals
Helper class providing an RAII-based mechanism for temporarily disabling denormals on your CPU.
class ScopedReadLock
Automatically locks and unlocks a ReadWriteLock object.
class ScopedTimeMeasurement
Simple RAII class for measuring the time spent in a scope.
class ScopedTryReadLock
Automatically locks and unlocks a ReadWriteLock object.
class ScopedTryWriteLock
Automatically locks and unlocks a ReadWriteLock object.
class ScopedValueSetter
Helper class providing an RAII-based mechanism for temporarily setting and then re-setting a value.
class ScopedWriteLock
Automatically locks and unlocks a ReadWriteLock object.
class ScopedYupInitialiser_GUI
A utility object that helps you initialise and shutdown YUP correctly using an RAII pattern.
struct ScopeGuard
An easy way to ensure that a function is called at the end of the current scope.
class Screen
Represents a screen device.
struct SerialisationSize
Holds a reference to some kind of size value, used to indicate that an object being marshalled is of variable size (e.g.
struct SerialisationTraits
Allows serialisation functions to be attached to a specific type without having to modify the declaration of that type.
class SHA1
SHA-1 UNSECURE hash generator.
class SharedResourcePointer
A smart-pointer that automatically creates and manages the lifetime of a shared static instance of a class.
class SingleThreadedAbstractFifo
Encapsulates the logic for a single-threaded FIFO.
class SingleThreadedIIRFilter
An IIR filter that can perform low, high, or band-pass filtering on an audio signal, with no thread-safety guarantees.
class SingleThreadedReferenceCountedObject
Adds reference-counting to an object.
struct SingletonHolder
Used by the YUP_DECLARE_SINGLETON macros to manage a static pointer to a singleton instance.
class Size
Represents a 2D size with width and height.
class Slider
class SmoothedValue
A utility class for values that need smoothing to avoid audio glitches.
class SmoothedValueBase
A base class for the smoothed value classes.
class SocketOptions
Options used for the configuration of the underlying system socket in the StreamingSocket and DatagramSocket classes.
class SortedSet
Holds a set of unique primitive objects, such as ints or doubles.
class Span
A non-owning view over contiguous objects stored in an Array or vector or other similar container.
class SparseSet
Holds a set of primitive values, storing them as a set of ranges.
class SpinLock
A simple spin-lock class that can be used as a simple, low-overhead mutex for uncontended situations.
class StatisticsAccumulator
A class that measures various statistics about a series of floating point values that it is given.
class StreamingSocket
A wrapper for a streaming (TCP) socket.
struct StrictVariantConverter
A helper type that can be used to implement specialisations of VariantConverter that use FromVar::convert and ToVar::convert internally.
class String
The YUP String class!
class StringArray
A special array for holding a list of strings.
class StringPairArray
A container for holding a set of strings which are keyed by another string.
class StringPool
A StringPool holds a set of shared strings, which reduces storage overheads and improves comparison speed when dealing with many duplicate strings.
class StringRef
A simple class for holding temporary references to a string literal or String.
class StyledText
class SubregionStream
Wraps another input stream, and reads from a specific part of it.
class Synthesiser
Base class for a musical device that can play sounds.
class SynthesiserSound
Describes one of the sounds that a Synthesiser can play.
class SynthesiserVoice
Represents a voice that a Synthesiser can use to play a SynthesiserSound.
class SystemAudioVolume
Contains functions to control the system's master volume.
class SystemClipboard
class SystemStats
Contains methods for finding out about the current hardware and OS configuration.
class TemporaryFile
Manages a temporary file, which will be deleted when this object is deleted.
class TextButton
class TextDiff
Calculates and applies a sequence of changes to convert one text string into another.
class TextEditor
A component that allows editing text with cursor movement and selection.
class Thread
Encapsulates a thread.
class ThreadLocalValue
Provides cross-platform support for thread-local objects.
class ThreadPool
A set of threads that will run a list of jobs.
class ThreadPoolJob
A task that is executed by a ThreadPool object.
struct ThreadPoolOptions
A set of threads that will run a list of jobs.
class ThreadValueInitialiser
class Time
Holds an absolute date and time.
class TimedCallback
Utility class wrapping a single non-null callback called by a Timer.
class TimeoutDetector
Detects if a specified timeout duration has been reached.
class Timer
Makes repeated callbacks to a virtual method at a specified time interval.
class TimeSliceClient
Used by the TimeSliceThread class.
class TimeSliceThread
A thread that keeps a list of clients, and calls each one in turn, giving them all a chance to run some sort of short task.
class Tolerance
A class encapsulating both relative and absolute tolerances for use in floating-point comparisons.
class ToneGeneratorAudioSource
A simple AudioSource that generates a sine wave.
class ToVar
Allows converting an object of arbitrary type to var.
class ToVarOptions
Options that control conversion from arbitrary types to yup::var.
class UndoableAction
The base class for all actions in the timeline.
class UndoManager
Manages undo and redo functionality for a set of actions.
class UnitTest
This is a base class for classes that perform a unit test.
class UnitTestRunner
Runs a set of unit tests.
class URL
Represents a URL and has a bunch of useful functions to manipulate it.
class URLInputSource
A type of InputSource that represents a URL.
class Uuid
A universally unique 128-bit identifier.
class var
A variant class, that can be used to hold a range of primitive values.
struct VariantConverter
This template-overloaded class can be used to convert between var and custom types.
class WaitableEvent
Allows threads to wait for events triggered by other threads.
class Watchdog
Watches a folder in the file system for changes.
class WeakReference
This class acts as a pointer which will automatically become null if the object to which it points is deleted.
class WebInputStream
An InputStream which can be used to read from a given URL.
class WildcardFileFilter
A type of FileFilter that works by wildcard pattern matching.
class WindowsRegistry
Contains some static helper functions for manipulating the MS Windows registry (Only available on Windows, of course!)
class WorkgroupToken
Created by AudioWorkgroup to join the calling thread to a workgroup.
class XmlDocument
Parses a text-based XML document and creates an XmlElement object from it.
class XmlElement
Used to build a tree of elements representing an XML document.
class YUPApplication
Main application class for the YUPApplication, extending YUP application functionality.
class YUPApplicationBase
Abstract base class for application classes.
class ZipFile
Decodes a ZIP file from a stream.
Typedefs
using AudioSampleBuffer = AudioBuffer<float>
A multi-channel buffer of 32-bit floating point audio samples.
using MidiKeyboardStateListener = MidiKeyboardState::Listener
using WindowedSincInterpolator = Interpolators::WindowedSinc
An interpolator for resampling a stream of floats using high order windowed (hann) sinc interpolation, recommended for high quality resampling.
using LagrangeInterpolator = Interpolators::Lagrange
An interpolator for resampling a stream of floats using 4-point lagrange interpolation.
using CatmullRomInterpolator = Interpolators::CatmullRom
An interpolator for resampling a stream of floats using Catmull-Rom interpolation.
using LinearInterpolator = Interpolators::Linear
An interpolator for resampling a stream of floats using linear interpolation.
using ZeroOrderHoldInterpolator = Interpolators::ZeroOrderHold
An interpolator for resampling a stream of floats using zero order hold interpolation.
template<typename FloatType>
using LinearSmoothedValue = SmoothedValue<FloatType, ValueSmoothingTypes::Linear>
using Nullopt = std::nullopt_t
using int8 = signed char
A platform-independent 8-bit signed integer type.
using uint8 = unsigned char
A platform-independent 8-bit unsigned integer type.
using int16 = signed short
A platform-independent 16-bit signed integer type.
using uint16 = unsigned short
A platform-independent 16-bit unsigned integer type.
using int32 = signed int
A platform-independent 32-bit signed integer type.
using uint32 = unsigned int
A platform-independent 32-bit unsigned integer type.
using int64 = long long
A platform-independent 64-bit integer type.
using uint64 = unsigned long long
A platform-independent 64-bit unsigned integer type.
using pointer_sized_int = int
A signed integer type that's guaranteed to be large enough to hold a pointer without truncating it.
using pointer_sized_uint = unsigned int
An unsigned integer type that's guaranteed to be large enough to hold a pointer without truncating it.
template<typename A, typename B>
using DisableIfSameOrDerived = std::enable_if_t<! std::is_base_of_v<A, std::remove_reference_t<B>>>
Can be used to disable template constructors that would otherwise cause ambiguity with compiler-generated copy and move constructors.
template<template< class... > class Op, class... Args>
using detectedType = typename detail::Detector<NoneSuch, void, Op, Args...>::Type
template<class Default, template< class... > class Op, class... Args>
using detectedOr = typename detail::detectedOr<Default, Op, Args...>::Type
using yup_socklen_t = socklen_t
using yup_recvsend_size_t = size_t
using SocketHandle = int
using yup_wchar = wchar_t
A platform-independent 32-bit unicode character type.
using CharPointer_wchar_t = CharPointer_UTF32
using ScopedLock = CriticalSection::ScopedLockType
Automatically locks and unlocks a CriticalSection object.
using ScopedUnlock = CriticalSection::ScopedUnlockType
Automatically unlocks and re-locks a CriticalSection object.
using ScopedTryLock = CriticalSection::ScopedTryLockType
Automatically tries to lock and unlock a CriticalSection object.
using MessageCallbackFunction = void*(void* userData)
See MessageManager::callFunctionOnMessageThread() for use of this function type.
Enumerations
enum class WASAPIDeviceMode { shared , exclusive , sharedLowLatency }
Available modes for the WASAPI audio device.
enum VariantStreamMarkers {
varMarker_Int = 1 , varMarker_BoolTrue = 2 , varMarker_BoolFalse = 3 , varMarker_Double = 4 ,
varMarker_String = 5 , varMarker_Int64 = 6 , varMarker_Array = 7 , varMarker_Binary = 8 ,
varMarker_Undefined = 9
}
enum class UndoableActionState { Undo , Redo }
enum { magicCoordWorkerConnectionHeader = 0x712baf04 }
enum { specialMessageSize = 8 , defaultTimeoutMs = 8000 }
enum NotificationType { dontSendNotification = 0 , sendNotification = 1 , sendNotificationSync , sendNotificationAsync }
These enums are used in various classes to indicate whether a notification event should be sent out.
enum class BlendMode : uint8 {
SrcOver , Screen , Overlay , Darken ,
Lighten , ColorDodge , ColorBurn , HardLight ,
SoftLight , Difference , Exclusion , Multiply ,
Hue , Saturation , Color , Luminosity
}
enum class StrokeCap : unsigned int { Butt = 0 , Round = 1 , Square = 2 }
Defines types of stroke caps used in graphical contexts.
enum class StrokeJoin : unsigned int { Miter = 0 , Round = 1 , Bevel = 2 }
Defines types of stroke joins used in graphical contexts.
enum class PixelFormat { Grayscale , RGB , RGBA }
Supported pixel formats.
Functions
template<typename Type>
bool operator== (const AudioBuffer< Type > &a, const AudioBuffer< Type > &b)
template<typename Type>
bool operator!= (const AudioBuffer< Type > &a, const AudioBuffer< Type > &b)
std::optional< MidiMessage > clapEventToMidiNoteMessage (const clap_event_header_t *event)
void clapEventToParameterChange (const clap_event_header_t *event, AudioProcessor &audioProcessor)
AudioPluginProcessorCLAP * getWrapper (const clap_plugin_t *plugin)
template<typename Begin, typename End = Begin>
constexpr auto makeRange (Begin begin, End end)
Given two iterators "begin" and "end", returns an IteratorPair with a member begin() and end() function.
template<typename Range, typename Index = detail::withAdlSize::AdlSignedSize<Range>>
constexpr auto enumerate (Range &&range, Index startingValue={})
Given a range and an optional starting offset, returns an IteratorPair that holds EnumerateIterators wrapping the begin() and end() of the range.
template<size_t len, typename T>
bool operator!= (const FixedSizeFunction< len, T > &fn, std::nullptr_t)
template<size_t len, typename T>
bool operator!= (std::nullptr_t, const FixedSizeFunction< len, T > &fn)
template<size_t len, typename T>
bool operator== (const FixedSizeFunction< len, T > &fn, std::nullptr_t)
template<size_t len, typename T>
bool operator== (std::nullptr_t, const FixedSizeFunction< len, T > &fn)
template<typename Value>
Optional< std::decay_t< Value > > makeOptional (Value &&v)
template<typename T, typename End>
Span (T, End) -> Span< std::remove_pointer_t< decltype(detail::toAddress(std::declval< T >()))> >
template<typename T, size_t N>
Span (T(&)[N]) -> Span< T, N >
template<typename T, size_t N>
Span (std::array< T, N > &) -> Span< T, N >
template<typename T, size_t N>
Span (const std::array< T, N > &) -> Span< const T, N >
template<typename Range>
Span (Range &&r) -> Span< std::remove_pointer_t< decltype(std::data(r))> >
bool canCompare (const var &v1, const var &v2)
bool operator== (const var &, const var &)
Compares the values of two var objects, using the var::equals() comparison.
bool operator!= (const var &, const var &)
Compares the values of two var objects, using the var::equals() comparison.
bool operator< (const var &, const var &)
Compares the values of two var objects, using the var::equals() comparison.
bool operator> (const var &, const var &)
Compares the values of two var objects, using the var::equals() comparison.
bool operator<= (const var &, const var &)
Compares the values of two var objects, using the var::equals() comparison.
bool operator>= (const var &, const var &)
Compares the values of two var objects, using the var::equals() comparison.
bool operator== (const var &v1, const String &v2)
bool operator!= (const var &v1, const String &v2)
bool operator== (const var &v1, const char *v2)
bool operator!= (const var &v1, const char *v2)
int64 yup_fileSetPosition (void *handle, int64 pos)
const DirectoryEntry & operator* (const DirectoryEntry &e) noexcept
A convenience operator so that the expression *it++ works correctly when it is an instance of RangedDirectoryIterator.
RangedDirectoryIterator begin (const RangedDirectoryIterator &it)
Returns the iterator that was passed in.
RangedDirectoryIterator end (const RangedDirectoryIterator &)
Returns a default-constructed sentinel value.
int findHighestSetBit (uint32 n) noexcept
Returns the index of the highest set bit in a (non-zero) number.
OutputStream &YUP_CALLTYPE operator<< (OutputStream &stream, const BigInteger &value)
Writes a BigInteger to an OutputStream as a UTF8 decimal string.
void writeLittleEndianBitsInBuffer (void *targetBuffer, uint32 startBit, uint32 numBits, uint32 value) noexcept
Writes a number of bits into a memory buffer at a given bit index.
uint32 readLittleEndianBitsInBuffer (const void *sourceBuffer, uint32 startBit, uint32 numBits) noexcept
Reads a number of bits from a buffer at a given bit index.
template<typename... Types>
constexpr void ignoreUnused (Types &&...) noexcept
Handy function for avoiding unused variables warning.
template<typename Type, size_t N>
constexpr int numElementsInArray (Type(&)[N]) noexcept
Handy function for getting the number of elements in a simple const C array.
template<typename Type>
Type yup_hypot (Type a, Type b) noexcept
Using yup_hypot is easier than dealing with the different types of hypot function that are provided by the various platforms and compilers.
template<typename Type>
constexpr Type yup_abs (Type v) noexcept
Constexpr enabled abs.
template<typename FloatType>
constexpr FloatType degreesToRadians (FloatType degrees) noexcept
Converts an angle in degrees to radians.
template<typename FloatType>
constexpr FloatType radiansToDegrees (FloatType radians) noexcept
Converts an angle in radians to degrees.
template<typename NumericType>
bool yup_isfinite (NumericType value) noexcept
The isfinite() method seems to vary between platforms, so this is a platform-independent function for it.
template<typename Type>
constexpr bool exactlyEqual (Type a, Type b)
Equivalent to operator==, but suppresses float-equality warnings.
template<typename Type>
constexpr Tolerance< Type > absoluteTolerance (Type tolerance)
Returns a type deduced Tolerance object containing only an absolute tolerance.
template<typename Type>
constexpr Tolerance< Type > relativeTolerance (Type tolerance)
Returns a type deduced Tolerance object containing only a relative tolerance.
template<typename Type, std::enable_if_t< std::is_floating_point_v< Type >, int > = 0>
constexpr bool approximatelyEqual (Type a, Type b, Tolerance< Type > tolerance=Tolerance< Type > {}.withAbsolute(std::numeric_limits< Type >::min()).withRelative(std::numeric_limits< Type >::epsilon()))
Returns true if the two floating-point numbers are approximately equal.
template<typename Type, std::enable_if_t<! std::is_floating_point_v< Type >, int > = 0>
constexpr bool approximatelyEqual (Type a, Type b)
Special case for non-floating-point types that returns true if both are exactly equal.
template<typename FloatType>
FloatType nextFloatUp (FloatType value) noexcept
Returns the next representable value by FloatType in the direction of the largest representable value.
template<typename FloatType>
FloatType nextFloatDown (FloatType value) noexcept
Returns the next representable value by FloatType in the direction of the lowest representable value.
template<typename Type>
constexpr Type jmax (Type a, Type b)
Returns the larger of two values.
template<typename Type>
constexpr Type jmax (Type a, Type b, Type c)
Returns the larger of three values.
template<typename Type>
constexpr Type jmax (Type a, Type b, Type c, Type d)
Returns the larger of four values.
template<typename Type>
constexpr Type jmin (Type a, Type b)
Returns the smaller of two values.
template<typename Type>
constexpr Type jmin (Type a, Type b, Type c)
Returns the smaller of three values.
template<typename Type>
constexpr Type jmin (Type a, Type b, Type c, Type d)
Returns the smaller of four values.
template<typename Type>
constexpr Type jmap (Type value0To1, Type targetRangeMin, Type targetRangeMax)
Remaps a normalised value (between 0 and 1) to a target range.
template<typename Type>
constexpr Type jmap (Type sourceValue, Type sourceRangeMin, Type sourceRangeMax, Type targetRangeMin, Type targetRangeMax)
Remaps a value from a source range to a target range.
template<typename Type>
Type mapToLog10 (Type value0To1, Type logRangeMin, Type logRangeMax)
Remaps a normalised value (between 0 and 1) to a logarithmic target range.
template<typename Type>
Type mapFromLog10 (Type valueInLogRange, Type logRangeMin, Type logRangeMax)
Remaps a logarithmic value in a target range to a normalised value (between 0 and 1).
template<typename Type, typename Size>
constexpr Type findMinimum (const Type *data, Size numValues)
Scans an array of values, returning the minimum value that it contains.
template<typename Type, typename Size>
constexpr Type findMaximum (const Type *values, Size numValues)
Scans an array of values, returning the maximum value that it contains.
template<typename Type>
void findMinAndMax (const Type *values, int numValues, Type &lowest, Type &highest)
Scans an array of values, returning the minimum and maximum values that it contains.
template<typename Type>
constexpr Type jlimit (Type lowerLimit, Type upperLimit, Type valueToConstrain) noexcept
Constrains a value to keep it within a given range.
template<typename Type1, typename Type2>
constexpr bool isPositiveAndBelow (Type1 valueToTest, Type2 upperLimit) noexcept
Returns true if a value is at least zero, and also below a specified upper limit.
template<typename Type>
constexpr bool isPositiveAndBelow (int valueToTest, Type upperLimit) noexcept
template<typename Type1, typename Type2>
constexpr bool isPositiveAndNotGreaterThan (Type1 valueToTest, Type2 upperLimit) noexcept
Returns true if a value is at least zero, and also less than or equal to a specified upper limit.
template<typename Type>
constexpr bool isPositiveAndNotGreaterThan (int valueToTest, Type upperLimit) noexcept
template<typename Type>
constexpr bool isWithin (Type a, Type b, Type tolerance) noexcept
Computes the absolute difference between two values and returns true if it is less than or equal to a given tolerance, otherwise it returns false.
template<typename FloatType>
int roundToInt (const FloatType value) noexcept
Fast floating-point-to-integer conversion.
int roundToInt (int value) noexcept
int roundToIntAccurate (double value) noexcept
Fast floating-point-to-integer conversion.
template<typename FloatType>
constexpr unsigned int truncatePositiveToUnsignedInt (FloatType value) noexcept
Truncates a positive floating-point number to an unsigned int.
template<typename IntegerType>
constexpr bool isPowerOfTwo (IntegerType value)
Returns true if the specified integer is a power-of-two.
constexpr int nextPowerOfTwo (int n) noexcept
Returns the smallest power-of-two which is equal to or greater than the given integer.
constexpr int countNumberOfBits (uint32 n) noexcept
Returns the number of bits in a 32-bit integer.
constexpr int countNumberOfBits (uint64 n) noexcept
Returns the number of bits in a 64-bit integer.
template<typename IntegerType>
constexpr IntegerType negativeAwareModulo (IntegerType dividend, const IntegerType divisor) noexcept
Performs a modulo operation, but can cope with the dividend being negative.
template<typename NumericType>
constexpr NumericType square (NumericType n) noexcept
Returns the square of its argument.
template<typename FloatType>
constexpr auto modulo (FloatType x, FloatType y) -> std::enable_if_t< std::is_floating_point_v< FloatType >, FloatType >
Returns the modulo of floating point types.
template<typename IntegerType>
constexpr auto modulo (IntegerType x, IntegerType y) -> std::enable_if_t<! std::is_floating_point_v< IntegerType >, IntegerType >
Returns the modulo of integral types.
template<typename T>
constexpr auto toUnderlyingType (T t) -> std::enable_if_t< std::is_enum_v< T >, std::underlying_type_t< T > >
Converts an enum to its underlying integral type.
template<typename T>
String getTemplatedMathsFunctionUnitTestName (const String &functionName)
void zeromem (void *memory, size_t numBytes) noexcept
Fills a block of memory with zeros.
template<typename Type>
void zerostruct (Type &structure) noexcept
Overwrites a structure or object with zeros.
template<typename Type>
void deleteAndZero (Type &pointer)
Delete an object pointer, and sets the pointer to null.
template<typename Type, typename IntegerType>
Type * snapPointerToAlignment (Type *basePointer, IntegerType alignmentBytes) noexcept
A handy function to round up a pointer to the nearest multiple of a given number of bytes.
template<typename Type1, typename Type2>
int getAddressDifference (Type1 *pointer1, Type2 *pointer2) noexcept
A handy function which returns the difference between any two pointers, in bytes.
template<class Type>
Type * createCopyIfNotNull (const Type *objectToCopy)
If a pointer is non-null, this returns a new copy of the object that it points to, or safely returns nullptr if the pointer is null.
template<typename Type>
Type readUnaligned (const void *srcPtr) noexcept
A handy function to read un-aligned memory without a performance penalty or bus-error.
template<typename Type>
void writeUnaligned (void *dstPtr, Type value) noexcept
A handy function to write un-aligned memory without a performance penalty or bus-error.
template<typename Type>
Type unalignedPointerCast (void *ptr) noexcept
Casts a pointer to another type via void*, which suppresses the cast-align warning which sometimes arises when casting pointers to types with different alignment.
template<typename Type>
Type unalignedPointerCast (const void *ptr) noexcept
Casts a pointer to another type via void*, which suppresses the cast-align warning which sometimes arises when casting pointers to types with different alignment.
template<typename Type, typename IntegerType>
Type * addBytesToPointer (Type *basePointer, IntegerType bytes) noexcept
A handy function which adds a number of bytes to any type of pointer and returns the result.
template<typename Type, typename IntegerType>
const Type * addBytesToPointer (const Type *basePointer, IntegerType bytes) noexcept
A handy function which adds a number of bytes to any type of pointer and returns the result.
template<typename T>
std::unique_ptr< T > rawToUniquePtr (T *ptr)
Converts an owning raw pointer into a unique_ptr, deriving the type of the unique_ptr automatically.
template<typename Type>
bool operator== (const Type *object1, const ReferenceCountedObjectPtr< Type > &object2) noexcept
Compares two ReferenceCountedObjectPtrs.
template<typename Type>
bool operator!= (const Type *object1, const ReferenceCountedObjectPtr< Type > &object2) noexcept
Compares two ReferenceCountedObjectPtrs.
template<typename EnumType, std::enable_if_t< std::is_enum_v< EnumType >, int > = 0>
constexpr bool hasBitValueSet (EnumType enumValue, EnumType valueToLookFor) noexcept
template<typename EnumType, std::enable_if_t< std::is_enum_v< EnumType >, int > = 0>
constexpr EnumType withBitValueSet (EnumType enumValue, EnumType valueToAdd) noexcept
template<typename EnumType, std::enable_if_t< std::is_enum_v< EnumType >, int > = 0>
constexpr EnumType withBitValueCleared (EnumType enumValue, EnumType valueToRemove) noexcept
template<typename Object, typename OtherObject, typename Member, typename Other>
Object withMember (Object copy, Member OtherObject::*member, Other &&value)
Copies an object, sets one of the copy's members to the specified value, and then returns the copy.
template<typename Fn>
ScopeGuard (Fn) -> ScopeGuard< Fn >
void setURLBookmark (URL &u, void *bookmark)
void * getURLBookmark (URL &u)
template<typename T>
constexpr auto named (std::string_view c, T &t)
Produces a Named instance that holds a mutable reference.
template<typename T>
constexpr auto named (std::string_view c, const T &t)
Produces a Named instance that holds an immutable reference.
template<typename T>
constexpr auto serialisationSize (T &t) -> std::enable_if_t< std::is_integral_v< T >, SerialisationSize< T > >
Produces a SerialisationSize instance that holds a mutable reference to a size value.
template<typename T>
constexpr auto serialisationSize (const T &t) -> std::enable_if_t< std::is_integral_v< T >, SerialisationSize< const T > >
Produces a SerialisationSize instance that holds an immutable reference to a size value.
OutputStream &YUP_CALLTYPE operator<< (OutputStream &stream, const MemoryOutputStream &streamToRead)
Copies all the data that has been written to a MemoryOutputStream into another stream.
YUP_API OutputStream &YUP_CALLTYPE operator<< (OutputStream &stream, int number)
Writes a number to a stream as 8-bit characters in the default system encoding.
YUP_API OutputStream &YUP_CALLTYPE operator<< (OutputStream &stream, int64 number)
Writes a number to a stream as 8-bit characters in the default system encoding.
YUP_API OutputStream &YUP_CALLTYPE operator<< (OutputStream &stream, double number)
Writes a number to a stream as 8-bit characters in the default system encoding.
YUP_API OutputStream &YUP_CALLTYPE operator<< (OutputStream &stream, char character)
Writes a character to a stream.
YUP_API OutputStream &YUP_CALLTYPE operator<< (OutputStream &stream, const char *text)
Writes a null-terminated text string to a stream.
YUP_API OutputStream &YUP_CALLTYPE operator<< (OutputStream &stream, const MemoryBlock &data)
Writes a block of data from a MemoryBlock to a stream.
YUP_API OutputStream &YUP_CALLTYPE operator<< (OutputStream &stream, const File &fileToRead)
Writes the contents of a file to a stream.
YUP_API OutputStream &YUP_CALLTYPE operator<< (OutputStream &stream, InputStream &streamToRead)
Writes the complete contents of an input stream to an output stream.
YUP_API OutputStream &YUP_CALLTYPE operator<< (OutputStream &stream, const NewLine &)
Writes a new-line to a stream.
constexpr bool isConstantEvaluated () noexcept
String getLegacyUniqueDeviceID ()
int yup_siginterrupt (int sig, int flag)
YUP_API String translate (const String &stringLiteral)
Uses the LocalisedStrings class to translate the given string literal.
YUP_API String translate (const char *stringLiteral)
Uses the LocalisedStrings class to translate the given string literal.
YUP_API String translate (CharPointer_UTF8 stringLiteral)
Uses the LocalisedStrings class to translate the given string literal.
YUP_API String translate (const String &stringLiteral, const String &resultIfNotFound)
Uses the LocalisedStrings class to translate the given string literal.
String & operator<< (String &string1, const NewLine &)
Writes a new-line sequence to a string.
String & operator+= (String &s1, const NewLine &)
String operator+ (const NewLine &, const NewLine &)
String operator+ (String s1, const NewLine &)
String operator+ (const NewLine &, const char *s2)
YUP_API bool YUP_CALLTYPE operator== (const String &string1, const String &string2) noexcept
Case-sensitive comparison of two strings.
YUP_API bool YUP_CALLTYPE operator!= (const String &string1, const String &string2) noexcept
Case-sensitive comparison of two strings.
YUP_API bool YUP_CALLTYPE operator== (const String &string1, const char *string2) noexcept
Case-sensitive comparison of two strings.
YUP_API bool YUP_CALLTYPE operator!= (const String &string1, const char *string2) noexcept
Case-sensitive comparison of two strings.
YUP_API bool YUP_CALLTYPE operator== (const String &string1, const wchar_t *string2) noexcept
Case-sensitive comparison of two strings.
YUP_API bool YUP_CALLTYPE operator!= (const String &string1, const wchar_t *string2) noexcept
Case-sensitive comparison of two strings.
YUP_API bool YUP_CALLTYPE operator== (const String &string1, StringRef string2) noexcept
Case-sensitive comparison of two strings.
YUP_API bool YUP_CALLTYPE operator!= (const String &string1, StringRef string2) noexcept
Case-sensitive comparison of two strings.
YUP_API bool YUP_CALLTYPE operator< (const String &string1, StringRef string2) noexcept
Case-sensitive comparison of two strings.
YUP_API bool YUP_CALLTYPE operator<= (const String &string1, StringRef string2) noexcept
Case-sensitive comparison of two strings.
YUP_API bool YUP_CALLTYPE operator> (const String &string1, StringRef string2) noexcept
Case-sensitive comparison of two strings.
YUP_API bool YUP_CALLTYPE operator>= (const String &string1, StringRef string2) noexcept
Case-sensitive comparison of two strings.
YUP_API bool YUP_CALLTYPE operator== (const String &string1, CharPointer_UTF8 string2) noexcept
Case-sensitive comparison of two strings.
YUP_API bool YUP_CALLTYPE operator!= (const String &string1, CharPointer_UTF8 string2) noexcept
Case-sensitive comparison of two strings.
YUP_API bool YUP_CALLTYPE operator== (const String &string1, CharPointer_UTF16 string2) noexcept
Case-sensitive comparison of two strings.
YUP_API bool YUP_CALLTYPE operator!= (const String &string1, CharPointer_UTF16 string2) noexcept
Case-sensitive comparison of two strings.
YUP_API bool YUP_CALLTYPE operator== (const String &string1, CharPointer_UTF32 string2) noexcept
Case-sensitive comparison of two strings.
YUP_API bool YUP_CALLTYPE operator!= (const String &string1, CharPointer_UTF32 string2) noexcept
Case-sensitive comparison of two strings.
YUP_API String YUP_CALLTYPE operator+ (const char *string1, const String &string2)
Concatenates two strings.
YUP_API String YUP_CALLTYPE operator+ (const wchar_t *string1, const String &string2)
Concatenates two strings.
YUP_API String YUP_CALLTYPE operator+ (char string1, const String &string2)
Concatenates two strings.
YUP_API String YUP_CALLTYPE operator+ (wchar_t string1, const String &string2)
Concatenates two strings.
YUP_API String YUP_CALLTYPE operator+ (String string1, const String &string2)
Concatenates two strings.
YUP_API String YUP_CALLTYPE operator+ (String string1, const char *string2)
Concatenates two strings.
YUP_API String YUP_CALLTYPE operator+ (String string1, const wchar_t *string2)
Concatenates two strings.
YUP_API String YUP_CALLTYPE operator+ (String string1, const std::string &string2)
Concatenates two strings.
YUP_API String YUP_CALLTYPE operator+ (String string1, char characterToAppend)
Concatenates two strings.
YUP_API String YUP_CALLTYPE operator+ (String string1, wchar_t characterToAppend)
Concatenates two strings.
YUP_API String &YUP_CALLTYPE operator<< (String &string1, wchar_t characterToAppend)
Appends a character at the end of a string.
YUP_API String &YUP_CALLTYPE operator<< (String &string1, char characterToAppend)
Appends a character at the end of a string.
YUP_API String &YUP_CALLTYPE operator<< (String &string1, const char *string2)
Appends a string to the end of the first one.
YUP_API String &YUP_CALLTYPE operator<< (String &string1, const wchar_t *string2)
Appends a string to the end of the first one.
YUP_API String &YUP_CALLTYPE operator<< (String &string1, const String &string2)
Appends a string to the end of the first one.
YUP_API String &YUP_CALLTYPE operator<< (String &string1, StringRef string2)
Appends a string to the end of the first one.
YUP_API String &YUP_CALLTYPE operator<< (String &string1, const std::string &string2)
Appends a string to the end of the first one.
YUP_API String &YUP_CALLTYPE operator<< (String &string1, uint8 number)
Appends a decimal number to the end of a string.
YUP_API String &YUP_CALLTYPE operator<< (String &string1, short number)
Appends a decimal number to the end of a string.
YUP_API String &YUP_CALLTYPE operator<< (String &string1, int number)
Appends a decimal number to the end of a string.
YUP_API String &YUP_CALLTYPE operator<< (String &string1, long number)
Appends a decimal number to the end of a string.
YUP_API String &YUP_CALLTYPE operator<< (String &string1, unsigned long number)
Appends a decimal number to the end of a string.
YUP_API String &YUP_CALLTYPE operator<< (String &string1, int64 number)
Appends a decimal number to the end of a string.
YUP_API String &YUP_CALLTYPE operator<< (String &string1, uint64 number)
Appends a decimal number to the end of a string.
YUP_API String &YUP_CALLTYPE operator<< (String &string1, float number)
Appends a decimal number to the end of a string.
YUP_API String &YUP_CALLTYPE operator<< (String &string1, double number)
Appends a decimal number to the end of a string.
YUP_API OutputStream &YUP_CALLTYPE operator<< (OutputStream &stream, const String &stringToWrite)
Writes a string to an OutputStream as UTF8.
YUP_API OutputStream &YUP_CALLTYPE operator<< (OutputStream &stream, StringRef stringToWrite)
Writes a string to an OutputStream as UTF8.
String reduceLengthOfFloatString (const String &input)
String serialiseDouble (double input, int maxDecimalPlaces=0)
template<class traits>
std::basic_ostream< char, traits > &YUP_CALLTYPE operator<< (std::basic_ostream< char, traits > &stream, const String &stringToWrite)
This operator allows you to write a yup String directly to std output streams.
template<class traits>
std::basic_ostream< wchar_t, traits > &YUP_CALLTYPE operator<< (std::basic_ostream< wchar_t, traits > &stream, const String &stringToWrite)
This operator allows you to write a yup String directly to std output streams.
String operator+ (String s1, StringRef s2)
String operator+ (StringRef s1, const String &s2)
String operator+ (const char *s1, StringRef s2)
String operator+ (StringRef s1, const char *s2)
void YUP_API yup_threadEntryPoint (void *userData)
YUP_API RelativeTime YUP_CALLTYPE operator+ (RelativeTime t1, RelativeTime t2) noexcept
Adds two RelativeTimes together.
YUP_API RelativeTime YUP_CALLTYPE operator- (RelativeTime t1, RelativeTime t2) noexcept
Subtracts two RelativeTimes.
YUP_API bool YUP_CALLTYPE operator== (RelativeTime t1, RelativeTime t2) noexcept
Compares two RelativeTimes.
YUP_API bool YUP_CALLTYPE operator!= (RelativeTime t1, RelativeTime t2) noexcept
Compares two RelativeTimes.
YUP_API bool YUP_CALLTYPE operator> (RelativeTime t1, RelativeTime t2) noexcept
Compares two RelativeTimes.
YUP_API bool YUP_CALLTYPE operator< (RelativeTime t1, RelativeTime t2) noexcept
Compares two RelativeTimes.
YUP_API bool YUP_CALLTYPE operator>= (RelativeTime t1, RelativeTime t2) noexcept
Compares two RelativeTimes.
YUP_API bool YUP_CALLTYPE operator<= (RelativeTime t1, RelativeTime t2) noexcept
Compares two RelativeTimes.
uint32 yup_millisecondsSinceStartup () noexcept
Time operator+ (Time time, RelativeTime delta) noexcept
Adds a RelativeTime to a Time.
Time operator- (Time time, RelativeTime delta) noexcept
Subtracts a RelativeTime from a Time.
Time operator+ (RelativeTime delta, Time time) noexcept
Adds a RelativeTime to a Time.
RelativeTime operator- (Time time1, Time time2) noexcept
Returns the relative time difference between two times.
bool operator== (Time time1, Time time2) noexcept
Compares two Time objects.
bool operator!= (Time time1, Time time2) noexcept
Compares two Time objects.
bool operator< (Time time1, Time time2) noexcept
Compares two Time objects.
bool operator> (Time time1, Time time2) noexcept
Compares two Time objects.
bool operator<= (Time time1, Time time2) noexcept
Compares two Time objects.
bool operator>= (Time time1, Time time2) noexcept
Compares two Time objects.
std::unique_ptr< XmlElement > parseXML (const String &textToParse)
Attempts to parse some XML text, returning a new XmlElement if it was valid.
std::unique_ptr< XmlElement > parseXML (const File &fileToParse)
Attempts to parse some XML text, returning a new XmlElement if it was valid.
std::unique_ptr< XmlElement > parseXMLIfTagMatches (const String &textToParse, StringRef requiredTag)
Does an inexpensive check to see whether the top-level element has the given tag name, and if that's true, does a full parse and returns the result.
std::unique_ptr< XmlElement > parseXMLIfTagMatches (const File &fileToParse, StringRef requiredTag)
Does an inexpensive check to see whether the top-level element has the given tag name, and if that's true, does a full parse and returns the result.
bool yup_isRunningUnderDebugger () noexcept
< This macro is added to all YUP public class declarations.
void logAssertion (const char *file, int line) noexcept
< This macro is added to all YUP public class declarations.
void logAssertion (const wchar_t *file, int line) noexcept
< This macro is added to all YUP public class declarations.
uint16 readUnalignedLittleEndianShort (const void *buffer)
uint32 readUnalignedLittleEndianInt (const void *buffer)
int64 readUnalignedLittleEndianInt64 (const void *buffer)
void acquireMulticastLock ()
void releaseMulticastLock ()
void initialiseNSApplication ()
jint JNIEXPORT yup_JNI_OnLoad (JavaVM *vm, void *)
YUP_API void YUP_CALLTYPE initialiseYup_GUI ()
Initialises YUP's GUI classes.
YUP_API void YUP_CALLTYPE shutdownYup_GUI ()
Clears up any static data being used by YUP's GUI classes.
template<std::size_t I>
constexpr float get (const AffineTransform &transform) noexcept
template<class ValueType>
YUP_API String &YUP_CALLTYPE operator<< (String &string1, const Line< ValueType > &l)
Stream output operator for Line objects.
template<std::size_t I, class ValueType>
constexpr ValueType get (const Line< ValueType > &line) noexcept
template<class ValueType>
YUP_API String &YUP_CALLTYPE operator<< (String &string1, const Point< ValueType > &p)
Stream output operator for Point objects.
template<std::size_t I, class ValueType>
constexpr ValueType get (const Point< ValueType > &point) noexcept
template<class ValueType>
YUP_API String &YUP_CALLTYPE operator<< (String &string1, const Rectangle< ValueType > &r)
Stream insertion operator for rectangles.
template<std::size_t I, class ValueType>
constexpr ValueType get (const Rectangle< ValueType > &point) noexcept
template<class ValueType>
YUP_API String &YUP_CALLTYPE operator<< (String &string1, const Size< ValueType > &s)
Stream insertion operator.
template<std::size_t I, class ValueType>
constexpr ValueType get (const Size< ValueType > &point) noexcept
void initialiseYup_Windowing ()
These are called automatically by the YUPApplication class but must be called by plugins.
void shutdownYup_Windowing ()
void paintSlider (Graphics &g, const ApplicationTheme &theme, const Slider &s)
void paintTextEditor (Graphics &g, const ApplicationTheme &theme, const TextEditor &t)
void paintTextButton (Graphics &g, const ApplicationTheme &theme, const TextButton &b)
void paintLabel (Graphics &g, const ApplicationTheme &theme, const Label &l)
ApplicationTheme::Ptr createThemeVersion1 ()
Variables
constexpr auto minimumDecibels = -300.0f
const auto YupPlugin_Category = Vst::PlugType::kFx
constexpr auto nullopt = std::nullopt
constexpr auto dynamicExtent = std::numeric_limits<size_t>::max()
template<bool Value, auto... Args>
constexpr bool dependentBoolValue = Value
template<auto... Args>
constexpr bool dependentFalse = dependentBoolValue<false, Args...>
template<template< class... > class Op, class... Args>
constexpr bool isDetected = detail::isDetected<Op, Args...>::value
template<class Expected, template< class... > class Op, class... Args>
constexpr bool isDetectedExact = detail::isDetectedExact<Expected, Op, Args...>::value
template<class To, template< class... > class Op, class... Args>
constexpr bool isDetectedConvertible = detail::isDetectedConvertible<To, Op, Args...>::value
uint64_t yup_compilationUniqueId = constexprRandomImplementation (__FILE__, __LINE__)
NewLine newLine
A predefined object representing a new-line, which can be written to a string or stream.
constexpr StringHolder emptyString
const char * yup_compilationDate = __DATE__
const char * yup_compilationTime = __TIME__
const char *const * yup_argv = nullptr
int yup_argc = 0
template<class ValueType>
class YUP_API Line
class YUP_API Component
const uint8_t RobotoFlexFont_data []
const std::size_t RobotoFlexFont_size = sizeof (RobotoFlexFont_data)
Typedef Documentation
AudioSampleBuffer
using yup::AudioSampleBuffer = AudioBuffer<float>
A multi-channel buffer of 32-bit floating point audio samples.
This type is here for backwards compatibility with the older AudioSampleBuffer class, which was fixed for 32-bit data, but is otherwise the same as the new templated AudioBuffer class.
See also
AudioBuffer
MidiKeyboardStateListener
using yup::MidiKeyboardStateListener = MidiKeyboardState::Listener
WindowedSincInterpolator
using yup::WindowedSincInterpolator = Interpolators::WindowedSinc
An interpolator for resampling a stream of floats using high order windowed (hann) sinc interpolation, recommended for high quality resampling.
Note that the resampler is stateful, so when there's a break in the continuity of the input stream you're feeding it, you should call reset() before feeding it any new data. And like with any other stateful filter, if you're resampling multiple channels, make sure each one uses its own WindowedSincInterpolator object.
See also
GenericInterpolator
LagrangeInterpolator, CatmullRomInterpolator, LinearInterpolator, ZeroOrderHoldInterpolator
LagrangeInterpolator
using yup::LagrangeInterpolator = Interpolators::Lagrange
An interpolator for resampling a stream of floats using 4-point lagrange interpolation.
Note that the resampler is stateful, so when there's a break in the continuity of the input stream you're feeding it, you should call reset() before feeding it any new data. And like with any other stateful filter, if you're resampling multiple channels, make sure each one uses its own LagrangeInterpolator object.
See also
GenericInterpolator
CatmullRomInterpolator, WindowedSincInterpolator, LinearInterpolator, ZeroOrderHoldInterpolator
CatmullRomInterpolator
using yup::CatmullRomInterpolator = Interpolators::CatmullRom
An interpolator for resampling a stream of floats using Catmull-Rom interpolation.
Note that the resampler is stateful, so when there's a break in the continuity of the input stream you're feeding it, you should call reset() before feeding it any new data. And like with any other stateful filter, if you're resampling multiple channels, make sure each one uses its own CatmullRomInterpolator object.
See also
GenericInterpolator
LagrangeInterpolator, WindowedSincInterpolator, LinearInterpolator, ZeroOrderHoldInterpolator
LinearInterpolator
using yup::LinearInterpolator = Interpolators::Linear
An interpolator for resampling a stream of floats using linear interpolation.
Note that the resampler is stateful, so when there's a break in the continuity of the input stream you're feeding it, you should call reset() before feeding it any new data. And like with any other stateful filter, if you're resampling multiple channels, make sure each one uses its own LinearInterpolator object.
See also
GenericInterpolator
LagrangeInterpolator, CatmullRomInterpolator, WindowedSincInterpolator, ZeroOrderHoldInterpolator
ZeroOrderHoldInterpolator
using yup::ZeroOrderHoldInterpolator = Interpolators::ZeroOrderHold
An interpolator for resampling a stream of floats using zero order hold interpolation.
Note that the resampler is stateful, so when there's a break in the continuity of the input stream you're feeding it, you should call reset() before feeding it any new data. And like with any other stateful filter, if you're resampling multiple channels, make sure each one uses its own ZeroOrderHoldInterpolator object.
See also
GenericInterpolator
LagrangeInterpolator, CatmullRomInterpolator, WindowedSincInterpolator, LinearInterpolator
LinearSmoothedValue
template<typename FloatType> using yup::LinearSmoothedValue = SmoothedValue<FloatType, ValueSmoothingTypes::Linear>
Nullopt
using yup::Nullopt = std::nullopt_t
int8
using yup::int8 = signed char
A platform-independent 8-bit signed integer type.
uint8
using yup::uint8 = unsigned char
A platform-independent 8-bit unsigned integer type.
int16
using yup::int16 = signed short
A platform-independent 16-bit signed integer type.
uint16
using yup::uint16 = unsigned short
A platform-independent 16-bit unsigned integer type.
int32
using yup::int32 = signed int
A platform-independent 32-bit signed integer type.
uint32
using yup::uint32 = unsigned int
A platform-independent 32-bit unsigned integer type.
int64
using yup::int64 = long long
A platform-independent 64-bit integer type.
uint64
using yup::uint64 = unsigned long long
A platform-independent 64-bit unsigned integer type.
pointer_sized_int
using yup::pointer_sized_int = int
A signed integer type that's guaranteed to be large enough to hold a pointer without truncating it.
pointer_sized_uint
using yup::pointer_sized_uint = unsigned int
An unsigned integer type that's guaranteed to be large enough to hold a pointer without truncating it.
DisableIfSameOrDerived
template<typename A, typename B> using yup::DisableIfSameOrDerived = std::enable_if_t<! std::is_base_of_v<A, std::remove_reference_t<B>>>
Can be used to disable template constructors that would otherwise cause ambiguity with compiler-generated copy and move constructors.
Adapted from https://ericniebler.com/2013/08/07/universal-references-and-the-copy-constructo/
detectedType
template<template< class... > class Op, class... Args> using yup::detectedType = typename detail::Detector<NoneSuch, void, Op, Args...>::Type
detectedOr
template<class Default, template< class... > class Op, class... Args> using yup::detectedOr = typename detail::detectedOr<Default, Op, Args...>::Type
yup_socklen_t
using yup::yup_socklen_t = socklen_t
yup_recvsend_size_t
using yup::yup_recvsend_size_t = size_t
SocketHandle
using yup::SocketHandle = int
yup_wchar
using yup::yup_wchar = wchar_t
A platform-independent 32-bit unicode character type.
CharPointer_wchar_t
using yup::CharPointer_wchar_t = CharPointer_UTF32
ScopedLock
using yup::ScopedLock = CriticalSection::ScopedLockType
Automatically locks and unlocks a CriticalSection object.
You can use a ScopedLock as a local variable to provide RAII-based locking of a CriticalSection.
e.g.
struct MyObject
{
    CriticalSection objectLock;
    // assuming that this example function will be called by multiple threads
    void foo()
    {
        const ScopedLock myScopedLock (objectLock);
        // objectLock is now locked..
        ...do some thread-safe work here...
        // ..and objectLock gets unlocked here, as myScopedLock goes out of
        // scope at the end of the block
    }
};
See also
CriticalSection, ScopedUnlock
ScopedUnlock
using yup::ScopedUnlock = CriticalSection::ScopedUnlockType
Automatically unlocks and re-locks a CriticalSection object.
This is the reverse of a ScopedLock object - instead of locking the critical section for the lifetime of this object, it unlocks it.
Make sure you don't try to unlock critical sections that aren't actually locked!
e.g.
struct MyObject
{
    CriticalSection objectLock;
    void foo()
    {
        {
            const ScopedLock myScopedLock (objectLock);
            // objectLock is now locked..
            {
                ScopedUnlock myUnlocker (objectLock);
                // ..and now unlocked..
            }
            // ..and now locked again..
        }
        // ..and finally unlocked.
    }
};
See also
CriticalSection, ScopedLock
ScopedTryLock
using yup::ScopedTryLock = CriticalSection::ScopedTryLockType
Automatically tries to lock and unlock a CriticalSection object.
Use one of these as a local variable to control access to a CriticalSection.
e.g.
struct MyObject
{
    CriticalSection objectLock;
    void foo()
    {
        const ScopedTryLock myScopedTryLock (objectLock);
        // Unlike using a ScopedLock, this may fail to actually get the lock, so you
        // must call the isLocked() method before making any assumptions..
        if (myScopedTryLock.isLocked())
        {
           ...safely do some work...
        }
        else
        {
            // If we get here, then our attempt at locking failed because another thread had already locked it..
        }
    }
};
See also
CriticalSection::tryEnter, ScopedLock, ScopedUnlock, ScopedReadLock
MessageCallbackFunction
using yup::MessageCallbackFunction = void*(void* userData)
See MessageManager::callFunctionOnMessageThread() for use of this function type.
Enumeration Type Documentation
WASAPIDeviceMode
enum class yup::WASAPIDeviceMode strong
Available modes for the WASAPI audio device.
Pass one of these to the AudioIODeviceType::createAudioIODeviceType_WASAPI() method to create a WASAPI AudioIODeviceType object in this mode.
Enumerator
shared
exclusive
sharedLowLatency
VariantStreamMarkers
enum yup::VariantStreamMarkers
Enumerator
varMarker_Int
varMarker_BoolTrue
varMarker_BoolFalse
varMarker_Double
varMarker_String
varMarker_Int64
varMarker_Array
varMarker_Binary
varMarker_Undefined
UndoableActionState
enum class yup::UndoableActionState strong
Enumerator
Undo
Indicates that the action should be undone.
Redo
Indicates that the action should be redone.
anonymous enum
anonymous enum
Enumerator
magicCoordWorkerConnectionHeader
anonymous enum
anonymous enum
Enumerator
specialMessageSize
defaultTimeoutMs
NotificationType
enum yup::NotificationType
These enums are used in various classes to indicate whether a notification event should be sent out.
Enumerator
dontSendNotification
No notification message should be sent.
sendNotification
Requests a notification message, either synchronous or not.
sendNotificationSync
Requests a synchronous notification.
sendNotificationAsync
Requests an asynchronous notification.
BlendMode
enum class yup::BlendMode : uint8 strong
Enumerator
SrcOver
Screen
Overlay
Darken
Lighten
ColorDodge
ColorBurn
HardLight
SoftLight
Difference
Exclusion
Multiply
Hue
Saturation
Color
Luminosity
StrokeCap
enum class yup::StrokeCap : unsigned int strong
Defines types of stroke caps used in graphical contexts.
This enumeration specifies the style of caps that could be applied to the ends of lines in a graphical drawing context. Each cap style provides a different appearance for the ends of lines.
Enumerator
Butt
A butt cap displays the end of the line exactly at the end point with no extension.
Round
A round cap extends the line with a half-circle that is centered at the end point of the line.
Square
A square cap extends the line by adding a square outline that projects beyond the end point.
StrokeJoin
enum class yup::StrokeJoin : unsigned int strong
Defines types of stroke joins used in graphical contexts.
This enumeration specifies the style of joins that could be applied where two lines meet in a graphical drawing context. Each join type affects how the corner is shaped.
Enumerator
Miter
A miter join creates a sharp corner or a clipped corner if the join angle is too sharp.
Round
A round join creates a rounded corner that smooths the meeting point of the lines.
Bevel
A bevel join creates a flattened corner by connecting the outer corners of the stroke.
PixelFormat
enum class yup::PixelFormat strong
Supported pixel formats.
Enumerator
Grayscale
8-bit grayscale.
RGB
24-bit RGB.
RGBA
32-bit RGBA.
Function Documentation
operator==() [1/16]
template<typename Type> bool yup::operator== (const AudioBuffer< Type > & a, const AudioBuffer< Type > & b)
References begin(), end(), and yup::AudioBuffer< Type >::getNumChannels().
Referenced by yup::ArgumentList::Argument::operator!=(), yup::Expression::Symbol::operator!=(), yup::MACAddress::operator!=(), yup::MemoryBlock::operator!=(), yup::MouseCursor::operator!=(), yup::MPEValue::operator!=(), yup::NamedValueSet::operator!=(), yup::SHA1::operator!=(), yup::SortedSet< ElementType, TypeOfCriticalSectionToUse >::operator!=(), yup::StringArray::operator!=(), and yup::Uuid::operator!=().
operator!=() [1/16]
template<typename Type> bool yup::operator!= (const AudioBuffer< Type > & a, const AudioBuffer< Type > & b)
clapEventToMidiNoteMessage()
std::optional< MidiMessage > yup::clapEventToMidiNoteMessage (const clap_event_header_t * event)
References yup::MidiMessage::noteOff(), and yup::MidiMessage::noteOn().
clapEventToParameterChange()
void yup::clapEventToParameterChange (const clap_event_header_t * event, AudioProcessor & audioProcessor)
References yup::AudioProcessor::getParameters(), and isPositiveAndBelow().
getWrapper()
AudioPluginProcessorCLAP * yup::getWrapper (const clap_plugin_t * plugin)
makeRange()
template<typename Begin, typename End = Begin> auto yup::makeRange (Begin begin, End end) nodiscard constexpr
Given two iterators "begin" and "end", returns an IteratorPair with a member begin() and end() function.
This pair can be used in contexts that expect an iterable range, the most significant of which is ranged-for loops. This automatically deduces the Begin and End types, so it is more concise to use than directly calling the IteratorPair constructor.
References begin(), and end().
enumerate()
template<typename Range, typename Index = detail::withAdlSize::AdlSignedSize<Range>> auto yup::enumerate (Range && range, Index startingValue = {}) nodiscard constexpr
Given a range and an optional starting offset, returns an IteratorPair that holds EnumerateIterators wrapping the begin() and end() of the range.
This is useful in situations where you need to iterate some range, but also query the position of each item in the range.
A simple usage might look like this:
std::list<int> elements { 10, 20, 30, 40, 50 };
for (const auto pair : enumerate (elements))
    std::cout << pair.index << ' ' << pair.value << ' ';
// output: 0 10 1 20 2 30 3 40 4 50
You can also use structured bindings to concisely destructure each Enumerated instance:
for (const auto [index, value] : enumerate (elements))
    std::cout << index << ' ' << value << ' ';
Note that the Enumerated instance is returned by value. This is because each Enumerated instance is created on-demand when the iterator is dereferenced. As a result, the following will result in a dangling reference, and will probably trigger a compiler warning:
// BAD IDEA: creating a reference to a temporary Enumerated instance
for (auto& [index, value] : enumerate (elements))
    ...
The 'value' member of Enumerated automatically assumes the same type as dereferencing the wrapped iterator, which is normally a reference to an element of a container. In the following snippet, the type of '[index, value]' is 'const Enumerated<ptrdiff_t, int&>', the type of 'index' is 'ptrdiff_t', and the type of 'value' is 'int&'.
std::vector<int> elements { 10, 20, 30, 40, 50 };
for (const auto [index, value] : enumerate (elements))
    ...
By default, the constness of pair.value will match the constness of the range passed to enumerate. If you pass a mutable lvalue reference to enumerate, then each value will also be mutable. If you pass a constant lvalue reference to enumerate, then each value will be const. If you know that you don't need the iterated elements to be mutable, it's good practice to wrap the range with std::as_const before passing it to enumerate:
for (const auto [index, value] : enumerate (std::as_const (elements)))
{
    // value is immutable here
}
operator!=() [2/16]
template<size_t len, typename T> bool yup::operator!= (const FixedSizeFunction< len, T > & fn, std::nullptr_t)
operator!=() [3/16]
template<size_t len, typename T> bool yup::operator!= (std::nullptr_t , const FixedSizeFunction< len, T > & fn)
operator==() [2/16]
template<size_t len, typename T> bool yup::operator== (const FixedSizeFunction< len, T > & fn, std::nullptr_t)
operator==() [3/16]
template<size_t len, typename T> bool yup::operator== (std::nullptr_t , const FixedSizeFunction< len, T > & fn)
makeOptional()
template<typename Value> Optional< std::decay_t< Value > > yup::makeOptional (Value && v)
Span() [1/5]
template<typename T, typename End> yup::Span (T , End) -> Span< std::remove_pointer_t< decltype(detail::toAddress(std::declval< T >()))> >
Span() [2/5]
template<typename T, size_t N> yup::Span (T(&) [N]) -> Span< T, N >
Span() [3/5]
template<typename T, size_t N> yup::Span (std::array< T, N > &) -> Span< T, N >
Span() [4/5]
template<typename T, size_t N> yup::Span (const std::array< T, N > &) -> Span< const T, N >
Span() [5/5]
template<typename Range> yup::Span (Range && r) -> Span< std::remove_pointer_t< decltype(std::data(r))> >
canCompare()
bool yup::canCompare (const var & v1, const var & v2)
Referenced by operator<(), operator<=(), operator>(), and operator>=().
operator==() [4/16]
YUP_API bool yup::operator== (const var & v1, const var & v2)
Compares the values of two var objects, using the var::equals() comparison.
References yup::var::equals().
operator!=() [4/16]
YUP_API bool yup::operator!= (const var & v1, const var & v2)
Compares the values of two var objects, using the var::equals() comparison.
References yup::var::equals().
operator<() [1/4]
YUP_API bool yup::operator< (const var & v1, const var & v2)
Compares the values of two var objects, using the var::equals() comparison.
References canCompare().
operator>() [1/4]
YUP_API bool yup::operator> (const var & v1, const var & v2)
Compares the values of two var objects, using the var::equals() comparison.
References canCompare().
operator<=() [1/4]
YUP_API bool yup::operator<= (const var & v1, const var & v2)
Compares the values of two var objects, using the var::equals() comparison.
References canCompare().
operator>=() [1/4]
YUP_API bool yup::operator>= (const var & v1, const var & v2)
Compares the values of two var objects, using the var::equals() comparison.
References canCompare().
operator==() [5/16]
YUP_API bool yup::operator== (const var & v1, const String & v2)
References yup::var::toString().
operator!=() [5/16]
YUP_API bool yup::operator!= (const var & v1, const String & v2)
References yup::var::toString().
operator==() [6/16]
YUP_API bool yup::operator== (const var & v1, const char * v2)
References yup::var::toString().
operator!=() [6/16]
YUP_API bool yup::operator!= (const var & v1, const char * v2)
References yup::var::toString().
yup_fileSetPosition()
int64 yup::yup_fileSetPosition (void * handle, int64 pos)
Referenced by yup::FileInputStream::setPosition(), and yup::FileOutputStream::setPosition().
operator*()
const DirectoryEntry & yup::operator* (const DirectoryEntry & e) noexcept
A convenience operator so that the expression *it++ works correctly when it is an instance of RangedDirectoryIterator.
begin()
RangedDirectoryIterator yup::begin (const RangedDirectoryIterator & it)
Returns the iterator that was passed in.
Provided for range-for compatibility.
Referenced by makeRange(), and operator==().
end()
RangedDirectoryIterator yup::end (const RangedDirectoryIterator &)
Returns a default-constructed sentinel value.
Provided for range-for compatibility.
Referenced by yup::TextEditor::deleteSelectedText(), yup::StringPool::getPooledString(), yup::TextEditor::getSelectedText(), yup::TextEditor::getSelectedTextAreas(), yup::TextEditor::getSelection(), yup::Identifier::Identifier(), yup::CharacterFunctions::lengthUpTo(), yup::CharPointer_ASCII::lengthUpTo(), yup::CharPointer_UTF16::lengthUpTo(), yup::CharPointer_UTF32::lengthUpTo(), yup::CharPointer_UTF8::lengthUpTo(), makeRange(), yup::StringHelpers::operationAddAssign(), operator==(), yup::SparseSet< Type >::operator[](), yup::String::paddedRight(), reduceLengthOfFloatString(), and yup::TextEditor::setSelection().
findHighestSetBit()
int yup::findHighestSetBit (uint32 n) noexcept
Returns the index of the highest set bit in a (non-zero) number.
So for n=3 this would return 1, for n=7 it returns 2, etc. An input value of 0 is illegal!
References countNumberOfBits().
Referenced by yup::BigInteger::getHighestBit().
operator<<() [1/36]
OutputStream &YUP_CALLTYPE yup::operator<< (OutputStream & stream, const BigInteger & value)
Writes a BigInteger to an OutputStream as a UTF8 decimal string.
References yup::BigInteger::toString().
Referenced by operator<<().
writeLittleEndianBitsInBuffer()
void yup::writeLittleEndianBitsInBuffer (void * targetBuffer, uint32 startBit, uint32 numBits, uint32 value) noexcept
Writes a number of bits into a memory buffer at a given bit index.
The buffer is treated as a sequence of 8-bit bytes, and the value is encoded in little-endian order, so for example if startBit = 10, and numBits = 11 then the lower 6 bits of the value would be written into bits 2-8 of targetBuffer[1], and the upper 5 bits of value into bits 0-5 of targetBuffer[2].
See also
readLittleEndianBitsInBuffer
readLittleEndianBitsInBuffer()
uint32 yup::readLittleEndianBitsInBuffer (const void * sourceBuffer, uint32 startBit, uint32 numBits) noexcept
Reads a number of bits from a buffer at a given bit index.
The buffer is treated as a sequence of 8-bit bytes, and the value is encoded in little-endian order, so for example if startBit = 10, and numBits = 11 then the lower 6 bits of the result would be read from bits 2-8 of sourceBuffer[1], and the upper 5 bits of the result from bits 0-5 of sourceBuffer[2].
See also
writeLittleEndianBitsInBuffer
ignoreUnused()
template<typename... Types> void yup::ignoreUnused (Types && ...) constexpr noexcept
Handy function for avoiding unused variables warning.
Referenced by yup::YUPApplication::anotherInstanceStarted(), yup::AudioIODeviceType::createAudioIODeviceType_WASAPI(), yup::YUPApplication::unhandledException(), and yup_isfinite().
numElementsInArray()
template<typename Type, size_t N> int yup::numElementsInArray (Type(&) [N]) constexpr noexcept
Handy function for getting the number of elements in a simple const C array.
E.g.
static int myArray[] = { 1, 2, 3 };
int numElements = numElementsInArray (myArray) // returns 3
Referenced by yup::AudioBuffer< float >::AudioBuffer(), yup::AudioSourcePlayer::audioDeviceIOCallbackWithContext(), yup::MemoryBlock::fromBase64Encoding(), yup::MidiMessage::getControllerName(), yup::MidiMessage::getGMInstrumentBankName(), yup::MidiMessage::getGMInstrumentName(), yup::SystemStats::getStackBacktrace(), yup::StringHelpers::operationAddAssign(), yup::AudioBuffer< float >::operator=(), yup::SystemStats::setApplicationCrashHandler(), and yup::Synthesiser::Synthesiser().
yup_hypot()
template<typename Type> Type yup::yup_hypot (Type a, Type b) noexcept
Using yup_hypot is easier than dealing with the different types of hypot function that are provided by the various platforms and compilers.
yup_abs()
template<typename Type> Type yup::yup_abs (Type v) constexpr noexcept
Constexpr enabled abs.
References isConstantEvaluated().
Referenced by yup::AffineTransform::getScaleFactor(), yup::Point< ValueType >::isCollinear(), isWithin(), yup::Tolerance< Type >::withAbsolute(), and yup::Tolerance< Type >::withRelative().
degreesToRadians()
template<typename FloatType> FloatType yup::degreesToRadians (FloatType degrees) constexpr noexcept
Converts an angle in degrees to radians.
References yup::MathConstants< FloatType >::pi.
Referenced by paintSlider().
radiansToDegrees()
template<typename FloatType> FloatType yup::radiansToDegrees (FloatType radians) constexpr noexcept
Converts an angle in radians to degrees.
References yup::MathConstants< FloatType >::pi.
yup_isfinite()
template<typename NumericType> bool yup::yup_isfinite (NumericType value) noexcept
The isfinite() method seems to vary between platforms, so this is a platform-independent function for it.
References ignoreUnused().
Referenced by yup::StatisticsAccumulator< FloatType >::addValue(), and yup::JSON::writeToStream().
exactlyEqual()
template<typename Type> bool yup::exactlyEqual (Type a, Type b) constexpr
Equivalent to operator==, but suppresses float-equality warnings.
This allows code to be explicit about float-equality checks that are known to have the correct semantics.
Referenced by yup::Array< ElementType, TypeOfCriticalSectionToUse, minimumAllocatedSize >::contains(), yup::NormalisableRange< ValueType >::convertFrom0to1(), yup::NormalisableRange< ValueType >::convertTo0to1(), yup::UnitTest::expectEquals(), yup::UnitTest::expectNotEquals(), yup::Array< ElementType, TypeOfCriticalSectionToUse, minimumAllocatedSize >::indexOf(), yup::Range< ValueType >::isEmpty(), yup::ArrayBase< ElementType, TypeOfCriticalSectionToUse >::operator==(), operator==(), serialiseDouble(), and yup::String::toDecimalStringWithSignificantFigures().
absoluteTolerance()
template<typename Type> Tolerance< Type > yup::absoluteTolerance (Type tolerance) constexpr
Returns a type deduced Tolerance object containing only an absolute tolerance.
See also
Tolerance::withAbsolute, approximatelyEqual
References yup::Tolerance< Type >::withAbsolute().
relativeTolerance()
template<typename Type> Tolerance< Type > yup::relativeTolerance (Type tolerance) constexpr
Returns a type deduced Tolerance object containing only a relative tolerance.
See also
Tolerance::withRelative, approximatelyEqual
References yup::Tolerance< Type >::withRelative().
approximatelyEqual() [1/2]
template<typename Type, std::enable_if_t< std::is_floating_point_v< Type >, int > = 0> bool yup::approximatelyEqual (Type a, Type b, Tolerance< Type > tolerance = Tolerance<Type> {}.withAbsolute (std::numeric_limits<Type>::min()).withRelative (std::numeric_limits<Type>::epsilon())) constexpr
Returns true if the two floating-point numbers are approximately equal.
If either a or b are not finite, returns exactlyEqual (a, b).
The default absolute tolerance is equal to the minimum normal value. This ensures differences that are subnormal are always considered equal. It is highly recommend this value is reviewed depending on the calculation being carried out. In general specifying an absolute value is useful when considering values close to zero. For example you might expect sin (pi) to return 0, but what it actually returns is close to the error of the value pi. Therefore, in this example it might be better to set the absolute tolerance to sin (pi).
The default relative tolerance is equal to the machine epsilon which is the difference between 1.0 and the next floating-point value that can be represented by Type. In most cases this value is probably reasonable. This value is multiplied by the largest absolute value of a and b so as to scale relatively according to the input parameters. For example, specifying a relative value of 0.05 will ensure values return equal if the difference between them is less than or equal to 5% of the larger of the two absolute values.
Parameters
a The first number to compare.
b The second number to compare.
tolerance An object that represents both absolute and relative tolerances when evaluating if a and b are equal.
See also
exactlyEqual
Referenced by yup::MidiMessageCollector::addMessageToQueue(), yup::MidiMessageSequence::addTimeToMessages(), yup::Point< ValueType >::approximatelyEqualTo(), yup::Size< ValueType >::approximatelyEqualTo(), yup::ResamplingAudioSource::getNextAudioBlock(), yup::ToneGeneratorAudioSource::getNextAudioBlock(), yup::AffineTransform::inverted(), jmap(), yup::BufferingAudioSource::prepareToPlay(), yup::MPESynthesiserBase::renderNextBlock(), yup::MPESynthesiserBase::setCurrentPlaybackSampleRate(), yup::Synthesiser::setCurrentPlaybackSampleRate(), yup::TextEditor::setFontSize(), yup::SmoothedValue< FloatType, ValueSmoothingTypes::Linear >::setTargetValue(), and yup::SmoothedValue< FloatType, ValueSmoothingTypes::Linear >::SmoothedValue().
approximatelyEqual() [2/2]
template<typename Type, std::enable_if_t<! std::is_floating_point_v< Type >, int > = 0> bool yup::approximatelyEqual (Type a, Type b) constexpr
Special case for non-floating-point types that returns true if both are exactly equal.
nextFloatUp()
template<typename FloatType> FloatType yup::nextFloatUp (FloatType value) noexcept
Returns the next representable value by FloatType in the direction of the largest representable value.
nextFloatDown()
template<typename FloatType> FloatType yup::nextFloatDown (FloatType value) noexcept
Returns the next representable value by FloatType in the direction of the lowest representable value.
jmax() [1/3]
template<typename Type> Type yup::jmax (Type a, Type b) constexpr
Returns the larger of two values.
Referenced by yup::Path::addArc(), yup::Path::addCenteredArc(), yup::Path::addCenteredEllipse(), yup::Path::addEllipse(), yup::Path::addPolygon(), yup::Path::addRectangle(), yup::PerformanceCounter::Statistics::addResult(), yup::Path::addRoundedRectangle(), yup::Path::addStar(), yup::BufferingAudioSource::BufferingAudioSource(), yup::File::createLegalFileName(), yup::TextEditor::deleteSelectedText(), yup::String::dropLastCharacters(), yup::Rectangle< ValueType >::enlarge(), yup::Rectangle< ValueType >::enlarge(), yup::Rectangle< ValueType >::enlarge(), yup::Expression::Scope::evaluateFunction(), yup::FileOutputStream::FileOutputStream(), yup::Decibels::gainToDecibels(), yup::Decibels::gainWithLowerBound(), yup::BigInteger::getBitRange(), yup::Color::getHue(), yup::Range< ValueType >::getIntersectionWith(), yup::String::getLastCharacters(), yup::MidiFile::getLastTimestamp(), yup::Color::getLuminance(), yup::AudioBuffer< float >::getMagnitude(), yup::AudioBuffer< float >::getMagnitude(), yup::MidiMessage::getMetaEventLength(), yup::MixerAudioSource::getNextAudioBlock(), yup::Color::getSaturation(), yup::TextEditor::getSelectedText(), yup::TextEditor::getSelectedTextAreas(), yup::TextEditor::getSelection(), yup::Range< ValueType >::getUnionWith(), yup::Range< ValueType >::getUnionWith(), yup::AudioDeviceManager::getXRunCount(), yup::Rectangle< ValueType >::intersection(), jmax(), yup::Component::lowerBelow(), yup::Component::lowerBy(), yup::IIRCoefficients::makeHighShelf(), yup::IIRCoefficients::makePeakFilter(), yup::BigInteger::operator+=(), yup::BigInteger::operator=(), yup::BufferingAudioSource::prepareToPlay(), yup::Range< ValueType >::Range(), yup::Rectangle< ValueType >::reduce(), yup::Rectangle< ValueType >::reduce(), yup::Rectangle< ValueType >::reduce(), yup::MidiMessageCollector::removeNextBlockOfMessages(), yup::Graphics::setFeather(), yup::Range< ValueType >::setLength(), yup::BufferedInputStream::setPosition(), yup::SubregionStream::setPosition(), yup::ResamplingAudioSource::setResamplingRatio(), yup::Graphics::setStrokeWidth(), yup::Timer::startTimer(), yup::ThreadPool::ThreadPool(), yup::Color::toHSL(), yup::Color::toHSV(), yup::Rectangle< ValueType >::transform(), yup::Rectangle< ValueType >::unionWith(), and yup::Range< ValueType >::withStart().
jmax() [2/3]
template<typename Type> Type yup::jmax (Type a, Type b, Type c) constexpr
Returns the larger of three values.
jmax() [3/3]
template<typename Type> Type yup::jmax (Type a, Type b, Type c, Type d) constexpr
Returns the larger of four values.
References jmax().
jmin() [1/3]
template<typename Type> Type yup::jmin (Type a, Type b) constexpr
Returns the smaller of two values.
Referenced by yup::Path::addBubble(), yup::PerformanceCounter::Statistics::addResult(), yup::Path::addRoundedRectangle(), yup::TextEditor::deleteSelectedText(), yup::Expression::Scope::evaluateFunction(), yup::FlagSet< uint32, decoratedWindowTag, resizableWindowTag, renderContinuousTag, allowHighDensityDisplayTag >::fromString(), yup::BigInteger::getBitRange(), yup::MemoryBlock::getBitRange(), yup::BigInteger::getBitRangeAsInt(), yup::Color::getHue(), yup::Range< ValueType >::getIntersectionWith(), yup::Color::getLuminance(), yup::MidiMessage::getMetaEventLength(), yup::AudioTransportSource::getNextAudioBlock(), yup::BufferingAudioSource::getNextAudioBlock(), yup::MemoryAudioSource::getNextAudioBlock(), yup::ResamplingAudioSource::getNextAudioBlock(), yup::Color::getSaturation(), yup::TextEditor::getSelectedText(), yup::TextEditor::getSelectedTextAreas(), yup::TextEditor::getSelection(), yup::SubregionStream::getTotalLength(), yup::Range< ValueType >::getUnionWith(), yup::Range< ValueType >::getUnionWith(), yup::MemoryBlock::insert(), yup::Rectangle< ValueType >::intersection(), jmin(), yup::StringArray::joinIntoString(), yup::MidiMessage::MidiMessage(), yup::Random::nextFloat(), yup::BufferingAudioSource::prepareToPlay(), yup::AbstractFifo::prepareToRead(), yup::AbstractFifo::prepareToWrite(), yup::Component::raiseAbove(), yup::Component::raiseBy(), yup::MemoryInputStream::read(), yup::SingleThreadedAbstractFifo::read(), yup::SubregionStream::read(), yup::MidiMessage::readVariableLengthValue(), yup::Path::scaleToFit(), yup::MemoryBlock::setBitRange(), yup::AudioBuffer< float >::setSize(), yup::TextEditor::setText(), yup::InputStream::skipNextBytes(), yup::Color::toHSL(), yup::Color::toHSV(), yup::Rectangle< ValueType >::transform(), yup::Rectangle< ValueType >::unionWith(), yup::Time::waitForMillisecondCounter(), yup::Range< ValueType >::withEnd(), yup::SingleThreadedAbstractFifo::write(), and yup::OutputStream::writeFromInputStream().
jmin() [2/3]
template<typename Type> Type yup::jmin (Type a, Type b, Type c) constexpr
Returns the smaller of three values.
jmin() [3/3]
template<typename Type> Type yup::jmin (Type a, Type b, Type c, Type d) constexpr
Returns the smaller of four values.
References jmin().
jmap() [1/2]
template<typename Type> Type yup::jmap (Type value0To1, Type targetRangeMin, Type targetRangeMax) constexpr
Remaps a normalised value (between 0 and 1) to a target range.
This effectively returns (targetRangeMin + value0To1 * (targetRangeMax - targetRangeMin)).
Referenced by yup::MPEValue::asSignedFloat(), yup::MPEValue::asUnsignedFloat(), yup::MPEValue::from7BitInt(), and yup::MidiMessage::pitchbendToPitchwheelPos().
jmap() [2/2]
template<typename Type> Type yup::jmap (Type sourceValue, Type sourceRangeMin, Type sourceRangeMax, Type targetRangeMin, Type targetRangeMax) constexpr
Remaps a value from a source range to a target range.
References approximatelyEqual().
mapToLog10()
template<typename Type> Type yup::mapToLog10 (Type value0To1, Type logRangeMin, Type logRangeMax)
Remaps a normalised value (between 0 and 1) to a logarithmic target range.
The entire target range must be greater than zero.
See also
mapFromLog10
mapToLog10 (0.5, 0.4, 40.0) == 4.0
mapFromLog10()
template<typename Type> Type yup::mapFromLog10 (Type valueInLogRange, Type logRangeMin, Type logRangeMax)
Remaps a logarithmic value in a target range to a normalised value (between 0 and 1).
The entire target range must be greater than zero.
See also
mapToLog10
mapFromLog10 (4.0, 0.4, 40.0) == 0.5
findMinimum()
template<typename Type, typename Size> Type yup::findMinimum (const Type * data, Size numValues) constexpr
Scans an array of values, returning the minimum value that it contains.
findMaximum()
template<typename Type, typename Size> Type yup::findMaximum (const Type * values, Size numValues) constexpr
Scans an array of values, returning the maximum value that it contains.
findMinAndMax()
template<typename Type> void yup::findMinAndMax (const Type * values, int numValues, Type & lowest, Type & highest)
Scans an array of values, returning the minimum and maximum values that it contains.
jlimit()
template<typename Type> Type yup::jlimit (Type lowerLimit, Type upperLimit, Type valueToConstrain) constexpr noexcept
Constrains a value to keep it within a given range.
This will check that the specified value lies between the lower and upper bounds specified, and if not, will return the nearest value that would be in-range. Effectively, it's like calling jmax (lowerLimit, jmin (upperLimit, value)).
Note that it expects that lowerLimit <= upperLimit. If this isn't true, the results will be unpredictable.
Parameters
lowerLimit the minimum value to return
upperLimit the maximum value to return
valueToConstrain the value to try to return
Returns
the closest value to valueToConstrain which lies between lowerLimit and upperLimit (inclusive)
See also
jmin, jmax, jmap
Referenced by yup::Path::addBubble(), yup::Path::addCenteredArc(), yup::Range< ValueType >::clipValue(), yup::Range< ValueType >::constrainRange(), yup::Color::contrasting(), yup::Graphics::drawImageAt(), yup::StyledText::getGlyphIndexAtPosition(), yup::AudioProcessLoadMeasurer::getLoadAsProportion(), yup::Path::getPointAlongPath(), yup::MidiHelpers::initialByte(), yup::Line< ValueType >::keepOnlyEnd(), yup::Line< ValueType >::keepOnlyStart(), yup::MidiMessage::masterVolume(), yup::MidiMessage::midiChannelMetaEvent(), yup::TextEditor::moveCaretDown(), yup::TextEditor::moveCaretUp(), yup::Point< ValueType >::pointBetween(), yup::MidiKeyboardState::processNextMidiBuffer(), yup::Rectangle< ValueType >::removeFromBottom(), yup::Rectangle< ValueType >::removeFromLeft(), yup::Rectangle< ValueType >::removeFromRight(), yup::Rectangle< ValueType >::removeFromTop(), yup::MidiMessageCollector::removeNextBlockOfMessages(), yup::Array< ElementType, TypeOfCriticalSectionToUse, minimumAllocatedSize >::removeRange(), yup::OwnedArray< ObjectClass, TypeOfCriticalSectionToUse >::removeRange(), yup::ReferenceCountedArray< UndoableAction >::removeRange(), yup::Font::setAxisValue(), yup::Font::setAxisValue(), yup::Font::setAxisValues(), yup::TextEditor::setCaretPosition(), yup::Component::setOpacity(), yup::Graphics::setOpacity(), yup::MemoryInputStream::setPosition(), yup::MemoryOutputStream::setPosition(), yup::TextEditor::setSelection(), yup::Slider::setValueNormalised(), yup::MidiHelpers::validVelocity(), yup::Font::withAxisValues(), and yup::Thread::RealtimeOptions::withPriority().
isPositiveAndBelow() [1/2]
template<typename Type1, typename Type2> bool yup::isPositiveAndBelow (Type1 valueToTest, Type2 upperLimit) constexpr noexcept
Returns true if a value is at least zero, and also below a specified upper limit.
This is basically a quicker way to write:
valueToTest >= 0 && valueToTest < upperLimit
Referenced by yup::Component::addChildComponent(), yup::AudioBuffer< float >::addFrom(), yup::AudioBuffer< float >::addFrom(), yup::AudioBuffer< float >::addFromWithRamp(), yup::AudioBuffer< float >::addSample(), yup::MidiMessage::aftertouchChange(), yup::AudioChannelSet::ambisonic(), yup::AudioBuffer< float >::applyGain(), yup::AudioBuffer< float >::applyGainRamp(), yup::UndoManager::canRedo(), yup::UndoManager::canUndo(), yup::MidiMessage::channelPressureChange(), clapEventToParameterChange(), yup::AudioBuffer< float >::clear(), yup::AudioBuffer< float >::copyFrom(), yup::AudioBuffer< float >::copyFrom(), yup::AudioBuffer< float >::copyFrom(), yup::AudioBuffer< float >::copyFromWithRamp(), yup::MidiMessageSequence::deleteEvent(), yup::AudioBuffer< float >::findMinMax(), yup::MemoryBlock::fromBase64Encoding(), yup::Font::getAxisDescription(), yup::Font::getAxisValue(), yup::MidiMessage::getControllerName(), yup::MidiMessage::getGMInstrumentBankName(), yup::MidiMessage::getGMInstrumentName(), yup::AudioBuffer< float >::getMagnitude(), yup::MidiMessage::getMidiNoteName(), yup::NamedValueSet::getName(), yup::AudioBuffer< float >::getReadPointer(), yup::AudioBuffer< float >::getReadPointer(), yup::RectangleList< ValueType >::getRectangle(), yup::AudioBuffer< float >::getRMSLevel(), yup::AudioBuffer< float >::getSample(), yup::Desktop::getScreen(), yup::UndoManager::getTransactionName(), yup::NamedValueSet::getValueAt(), yup::ArrayBase< ElementType, TypeOfCriticalSectionToUse >::getValueWithDefault(), yup::NamedValueSet::getVarPointerAt(), yup::NamedValueSet::getVarPointerAt(), yup::AudioBuffer< float >::getWritePointer(), yup::AudioBuffer< float >::getWritePointer(), yup::MidiKeyboardState::isNoteOn(), yup::MidiKeyboardState::isNoteOnForChannels(), yup::SocketHelpers::isValidPortNumber(), yup::HashMap< KeyType, ValueType, HashFunctionType, TypeOfCriticalSectionToUse >::Iterator, yup::ArrayBase< ElementType, TypeOfCriticalSectionToUse >::move(), yup::MidiMessage::noteOff(), yup::MidiMessage::noteOff(), yup::MidiKeyboardState::noteOn(), yup::MidiMessage::noteOn(), yup::ArrayBase< ElementType, TypeOfCriticalSectionToUse >::operator[](), yup::ArrayBase< ElementType, TypeOfCriticalSectionToUse >::operator[](), yup::StringArray::operator[](), yup::var::operator[](), yup::var::operator[](), yup::MidiMessage::pitchWheel(), yup::Array< ElementType, TypeOfCriticalSectionToUse, minimumAllocatedSize >::remove(), yup::Array< ElementType, TypeOfCriticalSectionToUse, minimumAllocatedSize >::remove(), yup::OwnedArray< ObjectClass, TypeOfCriticalSectionToUse >::remove(), yup::ReferenceCountedArray< UndoableAction >::remove(), yup::Array< ElementType, TypeOfCriticalSectionToUse, minimumAllocatedSize >::removeAndReturn(), yup::OwnedArray< ObjectClass, TypeOfCriticalSectionToUse >::removeAndReturn(), yup::ReferenceCountedArray< UndoableAction >::removeAndReturn(), yup::Component::removeChildComponent(), yup::Font::resetAxisValue(), yup::AudioBuffer< float >::reverse(), yup::Font::setAxisValue(), yup::JSONUtils::setPointer(), yup::AudioBuffer< float >::setSample(), yup::Array< ElementType, TypeOfCriticalSectionToUse, minimumAllocatedSize >::setUnchecked(), yup::ArrayBase< ElementType, TypeOfCriticalSectionToUse >::swap(), yup::ReferenceCountedArray< UndoableAction >::swap(), and yup::Font::withAxisValue().
isPositiveAndBelow() [2/2]
template<typename Type> bool yup::isPositiveAndBelow (int valueToTest, Type upperLimit) constexpr noexcept
isPositiveAndNotGreaterThan() [1/2]
template<typename Type1, typename Type2> bool yup::isPositiveAndNotGreaterThan (Type1 valueToTest, Type2 upperLimit) constexpr noexcept
Returns true if a value is at least zero, and also less than or equal to a specified upper limit.
This is basically a quicker way to write:
valueToTest >= 0 && valueToTest <= upperLimit
Referenced by yup::Thread::RealtimeOptions::withPriority().
isPositiveAndNotGreaterThan() [2/2]
template<typename Type> bool yup::isPositiveAndNotGreaterThan (int valueToTest, Type upperLimit) constexpr noexcept
isWithin()
template<typename Type> bool yup::isWithin (Type a, Type b, Type tolerance) constexpr noexcept
Computes the absolute difference between two values and returns true if it is less than or equal to a given tolerance, otherwise it returns false.
References yup_abs().
roundToInt() [1/2]
template<typename FloatType> int yup::roundToInt (const FloatType value) noexcept
Fast floating-point-to-integer conversion.
This is faster than using the normal c++ cast to convert a float to an int, and it will round the value to the nearest integer, rather than rounding it down like the normal cast does.
Note that this routine gets its speed at the expense of some accuracy, and when rounding values whose floating point component is exactly 0.5, odd numbers and even numbers will be rounded up or down differently.
Referenced by yup::MidiMessage::floatValueToMidiByte(), yup::MPEValue::fromSignedFloat(), yup::MPEValue::fromUnsignedFloat(), yup::ResamplingAudioSource::getNextAudioBlock(), yup::MidiMessage::masterVolume(), yup::MidiMessage::multiplyVelocity(), yup::ResamplingAudioSource::prepareToPlay(), yup::MidiKeyboardState::processNextMidiBuffer(), yup::MidiMessageCollector::removeNextBlockOfMessages(), yup::Point< ValueType >::roundToInt(), yup::Size< ValueType >::roundToInt(), and roundToIntAccurate().
roundToInt() [2/2]
int yup::roundToInt (int value) noexcept
roundToIntAccurate()
int yup::roundToIntAccurate (double value) noexcept
Fast floating-point-to-integer conversion.
This is a slightly slower and slightly more accurate version of roundToInt(). It works fine for values above zero, but negative numbers are rounded the wrong way.
References roundToInt().
truncatePositiveToUnsignedInt()
template<typename FloatType> unsigned int yup::truncatePositiveToUnsignedInt (FloatType value) constexpr noexcept
Truncates a positive floating-point number to an unsigned int.
This is generally faster than static_cast<unsigned int> (std::floor (x)) but it only works for positive numbers small enough to be represented as an unsigned int.
isPowerOfTwo()
template<typename IntegerType> bool yup::isPowerOfTwo (IntegerType value) constexpr
Returns true if the specified integer is a power-of-two.
Referenced by yup::SingleThreadedAbstractFifo::SingleThreadedAbstractFifo().
nextPowerOfTwo()
int yup::nextPowerOfTwo (int n) constexpr noexcept
Returns the smallest power-of-two which is equal to or greater than the given integer.
countNumberOfBits() [1/2]
int yup::countNumberOfBits (uint32 n) constexpr noexcept
Returns the number of bits in a 32-bit integer.
Referenced by countNumberOfBits(), yup::BigInteger::countNumberOfSetBits(), and findHighestSetBit().
countNumberOfBits() [2/2]
int yup::countNumberOfBits (uint64 n) constexpr noexcept
Returns the number of bits in a 64-bit integer.
References countNumberOfBits().
negativeAwareModulo()
template<typename IntegerType> IntegerType yup::negativeAwareModulo (IntegerType dividend, const IntegerType divisor) constexpr noexcept
Performs a modulo operation, but can cope with the dividend being negative.
The divisor must be greater than zero.
square()
template<typename NumericType> NumericType yup::square (NumericType n) constexpr noexcept
Returns the square of its argument.
Referenced by yup::AudioChannelSet::ambisonic(), yup::ColorGradient::ColorGradient(), yup::Point< ValueType >::distanceToSquared(), yup::AudioChannelSet::getAmbisonicOrderForNumChannels(), and yup::Point< ValueType >::magnitude().
modulo() [1/2]
template<typename FloatType> auto yup::modulo (FloatType x, FloatType y) -> std::enable_if_t<std::is_floating_point_v<FloatType>, FloatType> constexpr
Returns the modulo of floating point types.
Referenced by yup::Color::contrasting(), and yup::Color::fromHSV().
modulo() [2/2]
template<typename IntegerType> auto yup::modulo (IntegerType x, IntegerType y) -> std::enable_if_t<! std::is_floating_point_v<IntegerType>, IntegerType> constexpr
Returns the modulo of integral types.
toUnderlyingType()
template<typename T> auto yup::toUnderlyingType (T t) -> std::enable_if_t<std::is_enum_v<T>, std::underlying_type_t<T>> constexpr
Converts an enum to its underlying integral type.
Similar to std::to_underlying, which is only available in C++23 and above.
getTemplatedMathsFunctionUnitTestName()
template<typename T> String yup::getTemplatedMathsFunctionUnitTestName (const String & functionName)
zeromem()
void yup::zeromem (void * memory, size_t numBytes) noexcept
Fills a block of memory with zeros.
Referenced by yup::AudioSourcePlayer::audioDeviceIOCallbackWithContext(), yup::HeapBlock< char, true >::clear(), yup::MemoryBlock::copyTo(), yup::IIRCoefficients::IIRCoefficients(), yup::MACAddress::MACAddress(), yup::MACAddress::MACAddress(), yup::Uuid::operator=(), yup::AudioSourcePlayer::prepareToPlay(), yup::ResamplingAudioSource::ResamplingAudioSource(), and yup::MemoryBlock::setSize().
zerostruct()
template<typename Type> void yup::zerostruct (Type & structure) noexcept
Overwrites a structure or object with zeros.
Referenced by yup::SystemStats::getStackBacktrace(), yup::MidiKeyboardState::MidiKeyboardState(), yup::MidiKeyboardState::reset(), yup::SHA1::SHA1(), and yup::SHA1::SHA1().
deleteAndZero()
template<typename Type> void yup::deleteAndZero (Type & pointer)
Delete an object pointer, and sets the pointer to null.
Remember that it's not good c++ practice to use delete directly - always try to use a std::unique_ptr or other automatic lifetime-management system rather than resorting to deleting raw pointers!
Referenced by yup::MessageManager::deleteInstance().
snapPointerToAlignment()
template<typename Type, typename IntegerType> Type * yup::snapPointerToAlignment (Type * basePointer, IntegerType alignmentBytes) noexcept
A handy function to round up a pointer to the nearest multiple of a given number of bytes.
alignmentBytes must be a power of two.
getAddressDifference()
template<typename Type1, typename Type2> int yup::getAddressDifference (Type1 * pointer1, Type2 * pointer2) noexcept
A handy function which returns the difference between any two pointers, in bytes.
The address of the second pointer is subtracted from the first, and the difference in bytes is returned.
Referenced by yup::String::appendCharPointer(), and yup::CharacterFunctions::copyWithDestByteLimit().
createCopyIfNotNull()
template<class Type> Type * yup::createCopyIfNotNull (const Type * objectToCopy)
If a pointer is non-null, this returns a new copy of the object that it points to, or safely returns nullptr if the pointer is null.
Referenced by yup::OwnedArray< ObjectClass, TypeOfCriticalSectionToUse >::addCopiesOf(), yup::LocalisedStrings::LocalisedStrings(), and yup::LocalisedStrings::operator=().
readUnaligned()
template<typename Type> Type yup::readUnaligned (const void * srcPtr) noexcept
A handy function to read un-aligned memory without a performance penalty or bus-error.
Referenced by yup::MidiBufferHelpers::getEventDataSize(), yup::MidiBufferHelpers::getEventTime(), readUnalignedLittleEndianInt(), readUnalignedLittleEndianInt64(), and readUnalignedLittleEndianShort().
writeUnaligned()
template<typename Type> void yup::writeUnaligned (void * dstPtr, Type value) noexcept
A handy function to write un-aligned memory without a performance penalty or bus-error.
Referenced by yup::MidiBuffer::addEvent().
unalignedPointerCast() [1/2]
template<typename Type> Type yup::unalignedPointerCast (void * ptr) noexcept
Casts a pointer to another type via void*, which suppresses the cast-align warning which sometimes arises when casting pointers to types with different alignment.
You should only use this when you know for a fact that the input pointer points to a region that has suitable alignment for Type, e.g. regions returned from malloc/calloc that should be suitable for any non-over-aligned type.
Referenced by addBytesToPointer(), addBytesToPointer(), yup::String::createStringFromData(), yup::String::replaceSection(), yup::AudioBuffer< float >::setSize(), and yup::StringRef::StringRef().
unalignedPointerCast() [2/2]
template<typename Type> Type yup::unalignedPointerCast (const void * ptr) noexcept
Casts a pointer to another type via void*, which suppresses the cast-align warning which sometimes arises when casting pointers to types with different alignment.
You should only use this when you know for a fact that the input pointer points to a region that has suitable alignment for Type, e.g. regions returned from malloc/calloc that should be suitable for any non-over-aligned type.
addBytesToPointer() [1/2]
template<typename Type, typename IntegerType> Type * yup::addBytesToPointer (Type * basePointer, IntegerType bytes) noexcept
A handy function which adds a number of bytes to any type of pointer and returns the result.
This can be useful to avoid casting pointers to a char* and back when you want to move them by a specific number of bytes,
References unalignedPointerCast().
Referenced by yup::String::appendCharPointer(), yup::String::appendCharPointer(), yup::String::appendCharPointer(), yup::AudioData::ConverterInstance< SourceSampleType, DestSampleType >::convertSamples(), yup::AudioData::deinterleaveSamples(), yup::AudioData::interleaveSamples(), yup::BigInteger::loadFromMemoryBlock(), yup::InputStream::read(), and yup::MemoryInputStream::read().
addBytesToPointer() [2/2]
template<typename Type, typename IntegerType> const Type * yup::addBytesToPointer (const Type * basePointer, IntegerType bytes) noexcept
A handy function which adds a number of bytes to any type of pointer and returns the result.
This can be useful to avoid casting pointers to a char* and back when you want to move them by a specific number of bytes,
References unalignedPointerCast().
rawToUniquePtr()
template<typename T> std::unique_ptr< T > yup::rawToUniquePtr (T * ptr)
Converts an owning raw pointer into a unique_ptr, deriving the type of the unique_ptr automatically.
This should only be used with pointers to single objects. Do NOT pass a pointer to an array to this function, as the destructor of the unique_ptr will incorrectly call delete instead of delete[] on the pointer.
operator==() [7/16]
template<typename Type> bool yup::operator== (const Type * object1, const ReferenceCountedObjectPtr< Type > & object2) noexcept
Compares two ReferenceCountedObjectPtrs.
operator!=() [7/16]
template<typename Type> bool yup::operator!= (const Type * object1, const ReferenceCountedObjectPtr< Type > & object2) noexcept
Compares two ReferenceCountedObjectPtrs.
hasBitValueSet()
template<typename EnumType, std::enable_if_t< std::is_enum_v< EnumType >, int > = 0> bool yup::hasBitValueSet (EnumType enumValue, EnumType valueToLookFor) constexpr noexcept
Referenced by yup::SystemStats::getMachineIdentifiers().
withBitValueSet()
template<typename EnumType, std::enable_if_t< std::is_enum_v< EnumType >, int > = 0> EnumType yup::withBitValueSet (EnumType enumValue, EnumType valueToAdd) constexpr noexcept
withBitValueCleared()
template<typename EnumType, std::enable_if_t< std::is_enum_v< EnumType >, int > = 0> EnumType yup::withBitValueCleared (EnumType enumValue, EnumType valueToRemove) constexpr noexcept
withMember()
template<typename Object, typename OtherObject, typename Member, typename Other> Object yup::withMember (Object copy, Member OtherObject::* member, Other && value) nodiscard
Copies an object, sets one of the copy's members to the specified value, and then returns the copy.
Referenced by yup::Tolerance< Type >::withAbsolute(), yup::ThreadPoolOptions::withDesiredThreadPriority(), yup::ToVarOptions::withExplicitVersion(), yup::JSON::FormatOptions::withIndentLevel(), yup::JSON::FormatOptions::withMaxDecimalPlaces(), yup::Thread::RealtimeOptions::withMaximumProcessingTimeMs(), yup::ThreadPoolOptions::withNumberOfThreads(), yup::Thread::RealtimeOptions::withPeriodMs(), yup::Thread::RealtimeOptions::withPriority(), yup::Thread::RealtimeOptions::withProcessingTimeMs(), yup::SocketOptions::withReceiveBufferSize(), yup::Tolerance< Type >::withRelative(), yup::SocketOptions::withSendBufferSize(), yup::JSON::FormatOptions::withSpacing(), yup::ThreadPoolOptions::withThreadName(), yup::ThreadPoolOptions::withThreadStackSizeBytes(), and yup::ToVarOptions::withVersionIncluded().
ScopeGuard()
template<typename Fn> yup::ScopeGuard (Fn) -> ScopeGuard< Fn >
setURLBookmark()
void yup::setURLBookmark (URL & u, void * bookmark)
getURLBookmark()
void * yup::getURLBookmark (URL & u)
named() [1/2]
template<typename T> auto yup::named (std::string_view c, T & t) constexpr
Produces a Named instance that holds a mutable reference.
Referenced by yup::universal_midi_packets::DeviceInfo::serialise().
named() [2/2]
template<typename T> auto yup::named (std::string_view c, const T & t) constexpr
Produces a Named instance that holds an immutable reference.
serialisationSize() [1/2]
template<typename T> auto yup::serialisationSize (T & t) -> std::enable_if_t<std::is_integral_v<T>, SerialisationSize<T>> constexpr
Produces a SerialisationSize instance that holds a mutable reference to a size value.
serialisationSize() [2/2]
template<typename T> auto yup::serialisationSize (const T & t) -> std::enable_if_t<std::is_integral_v<T>, SerialisationSize<const T>> constexpr
Produces a SerialisationSize instance that holds an immutable reference to a size value.
operator<<() [2/36]
OutputStream &YUP_CALLTYPE yup::operator<< (OutputStream & stream, const MemoryOutputStream & streamToRead)
Copies all the data that has been written to a MemoryOutputStream into another stream.
References yup::MemoryOutputStream::getData(), yup::MemoryOutputStream::getDataSize(), and yup::OutputStream::write().
operator<<() [3/36]
YUP_API OutputStream &YUP_CALLTYPE yup::operator<< (OutputStream & stream, const int number)
Writes a number to a stream as 8-bit characters in the default system encoding.
operator<<() [4/36]
YUP_API OutputStream &YUP_CALLTYPE yup::operator<< (OutputStream & stream, const int64 number)
Writes a number to a stream as 8-bit characters in the default system encoding.
operator<<() [5/36]
YUP_API OutputStream &YUP_CALLTYPE yup::operator<< (OutputStream & stream, const double number)
Writes a number to a stream as 8-bit characters in the default system encoding.
operator<<() [6/36]
YUP_API OutputStream &YUP_CALLTYPE yup::operator<< (OutputStream & stream, const char character)
Writes a character to a stream.
References yup::OutputStream::writeByte().
operator<<() [7/36]
YUP_API OutputStream &YUP_CALLTYPE yup::operator<< (OutputStream & stream, const char *const text)
Writes a null-terminated text string to a stream.
References yup::OutputStream::write().
operator<<() [8/36]
YUP_API OutputStream &YUP_CALLTYPE yup::operator<< (OutputStream & stream, const MemoryBlock & data)
Writes a block of data from a MemoryBlock to a stream.
References yup::MemoryBlock::getData(), yup::MemoryBlock::getSize(), yup::MemoryBlock::isEmpty(), and yup::OutputStream::write().
operator<<() [9/36]
YUP_API OutputStream &YUP_CALLTYPE yup::operator<< (OutputStream & stream, const File & fileToRead)
Writes the contents of a file to a stream.
References yup::FileInputStream::openedOk().
operator<<() [10/36]
YUP_API OutputStream &YUP_CALLTYPE yup::operator<< (OutputStream & stream, InputStream & streamToRead)
Writes the complete contents of an input stream to an output stream.
References yup::OutputStream::writeFromInputStream().
operator<<() [11/36]
YUP_API OutputStream &YUP_CALLTYPE yup::operator<< (OutputStream & stream, const NewLine &)
Writes a new-line to a stream.
You can use the predefined symbol 'newLine' to invoke this, e.g.
myOutputStream << "Hello World" << newLine << newLine;
See also
OutputStream::setNewLineString
References yup::OutputStream::getNewLineString().
isConstantEvaluated()
bool yup::isConstantEvaluated () constexpr noexcept
Referenced by yup_abs().
getLegacyUniqueDeviceID()
String yup::getLegacyUniqueDeviceID ()
Referenced by yup::SystemStats::getMachineIdentifiers().
yup_siginterrupt()
int yup::yup_siginterrupt (int sig, int flag)
Referenced by yup::SystemStats::setApplicationCrashHandler().
translate() [1/4]
YUP_API String yup::translate (const String & stringLiteral)
Uses the LocalisedStrings class to translate the given string literal.
See also
LocalisedStrings
References translate().
Referenced by translate(), translate(), translate(), yup::LocalisedStrings::translateWithCurrentMappings(), and yup::LocalisedStrings::translateWithCurrentMappings().
translate() [2/4]
YUP_API String yup::translate (const char * stringLiteral)
Uses the LocalisedStrings class to translate the given string literal.
See also
LocalisedStrings
References translate().
translate() [3/4]
YUP_API String yup::translate (CharPointer_UTF8 stringLiteral)
Uses the LocalisedStrings class to translate the given string literal.
See also
LocalisedStrings
References translate().
translate() [4/4]
YUP_API String yup::translate (const String & stringLiteral, const String & resultIfNotFound)
Uses the LocalisedStrings class to translate the given string literal.
See also
LocalisedStrings
References yup::LocalisedStrings::getCurrentMappings().
operator<<() [12/36]
String & yup::operator<< (String & string1, const NewLine &)
Writes a new-line sequence to a string.
You can use the predefined object 'newLine' to invoke this, e.g.
myString << "Hello World" << newLine << newLine;
References yup::NewLine::getDefault().
operator+=()
String & yup::operator+= (String & s1, const NewLine &)
References yup::NewLine::getDefault().
Referenced by yup::String::operator+=(), yup::String::operator+=(), yup::String::operator+=(), and yup::String::operator+=().
operator+() [1/20]
String yup::operator+ (const NewLine & , const NewLine &)
References yup::NewLine::getDefault().
operator+() [2/20]
String yup::operator+ (String s1, const NewLine &)
References yup::NewLine::getDefault().
operator+() [3/20]
String yup::operator+ (const NewLine & , const char * s2)
References yup::NewLine::getDefault().
operator==() [8/16]
YUP_API bool YUP_CALLTYPE yup::operator== (const String & s1, const String & s2) noexcept
Case-sensitive comparison of two strings.
operator!=() [8/16]
YUP_API bool YUP_CALLTYPE yup::operator!= (const String & s1, const String & s2) noexcept
Case-sensitive comparison of two strings.
operator==() [9/16]
YUP_API bool YUP_CALLTYPE yup::operator== (const String & s1, const char * s2) noexcept
Case-sensitive comparison of two strings.
operator!=() [9/16]
YUP_API bool YUP_CALLTYPE yup::operator!= (const String & s1, const char * s2) noexcept
Case-sensitive comparison of two strings.
operator==() [10/16]
YUP_API bool YUP_CALLTYPE yup::operator== (const String & s1, const wchar_t * s2) noexcept
Case-sensitive comparison of two strings.
operator!=() [10/16]
YUP_API bool YUP_CALLTYPE yup::operator!= (const String & s1, const wchar_t * s2) noexcept
Case-sensitive comparison of two strings.
operator==() [11/16]
YUP_API bool YUP_CALLTYPE yup::operator== (const String & s1, StringRef s2) noexcept
Case-sensitive comparison of two strings.
operator!=() [11/16]
YUP_API bool YUP_CALLTYPE yup::operator!= (const String & s1, StringRef s2) noexcept
Case-sensitive comparison of two strings.
operator<() [2/4]
YUP_API bool YUP_CALLTYPE yup::operator< (const String & s1, StringRef s2) noexcept
Case-sensitive comparison of two strings.
operator<=() [2/4]
YUP_API bool YUP_CALLTYPE yup::operator<= (const String & s1, StringRef s2) noexcept
Case-sensitive comparison of two strings.
operator>() [2/4]
YUP_API bool YUP_CALLTYPE yup::operator> (const String & s1, StringRef s2) noexcept
Case-sensitive comparison of two strings.
operator>=() [2/4]
YUP_API bool YUP_CALLTYPE yup::operator>= (const String & s1, StringRef s2) noexcept
Case-sensitive comparison of two strings.
operator==() [12/16]
YUP_API bool YUP_CALLTYPE yup::operator== (const String & s1, const CharPointer_UTF8 s2) noexcept
Case-sensitive comparison of two strings.
operator!=() [12/16]
YUP_API bool YUP_CALLTYPE yup::operator!= (const String & s1, const CharPointer_UTF8 s2) noexcept
Case-sensitive comparison of two strings.
operator==() [13/16]
YUP_API bool YUP_CALLTYPE yup::operator== (const String & s1, const CharPointer_UTF16 s2) noexcept
Case-sensitive comparison of two strings.
operator!=() [13/16]
YUP_API bool YUP_CALLTYPE yup::operator!= (const String & s1, const CharPointer_UTF16 s2) noexcept
Case-sensitive comparison of two strings.
operator==() [14/16]
YUP_API bool YUP_CALLTYPE yup::operator== (const String & s1, const CharPointer_UTF32 s2) noexcept
Case-sensitive comparison of two strings.
operator!=() [14/16]
YUP_API bool YUP_CALLTYPE yup::operator!= (const String & s1, const CharPointer_UTF32 s2) noexcept
Case-sensitive comparison of two strings.
operator+() [4/20]
YUP_API String YUP_CALLTYPE yup::operator+ (const char * s1, const String & s2)
Concatenates two strings.
operator+() [5/20]
YUP_API String YUP_CALLTYPE yup::operator+ (const wchar_t * s1, const String & s2)
Concatenates two strings.
operator+() [6/20]
YUP_API String YUP_CALLTYPE yup::operator+ (char s1, const String & s2)
Concatenates two strings.
References yup::String::charToString().
operator+() [7/20]
YUP_API String YUP_CALLTYPE yup::operator+ (wchar_t s1, const String & s2)
Concatenates two strings.
References yup::String::charToString().
operator+() [8/20]
YUP_API String YUP_CALLTYPE yup::operator+ (String s1, const String & s2)
Concatenates two strings.
operator+() [9/20]
YUP_API String YUP_CALLTYPE yup::operator+ (String s1, const char * s2)
Concatenates two strings.
operator+() [10/20]
YUP_API String YUP_CALLTYPE yup::operator+ (String s1, const wchar_t * s2)
Concatenates two strings.
operator+() [11/20]
YUP_API String YUP_CALLTYPE yup::operator+ (String s1, const std::string & s2)
Concatenates two strings.
operator+() [12/20]
YUP_API String YUP_CALLTYPE yup::operator+ (String s1, char s2)
Concatenates two strings.
operator+() [13/20]
YUP_API String YUP_CALLTYPE yup::operator+ (String s1, wchar_t s2)
Concatenates two strings.
operator<<() [13/36]
YUP_API String &YUP_CALLTYPE yup::operator<< (String & s1, yup_wchar s2)
Appends a character at the end of a string.
operator<<() [14/36]
YUP_API String &YUP_CALLTYPE yup::operator<< (String & s1, char s2)
Appends a character at the end of a string.
operator<<() [15/36]
YUP_API String &YUP_CALLTYPE yup::operator<< (String & s1, const char * s2)
Appends a string to the end of the first one.
operator<<() [16/36]
YUP_API String &YUP_CALLTYPE yup::operator<< (String & s1, const wchar_t * s2)
Appends a string to the end of the first one.
operator<<() [17/36]
YUP_API String &YUP_CALLTYPE yup::operator<< (String & s1, const String & s2)
Appends a string to the end of the first one.
operator<<() [18/36]
YUP_API String &YUP_CALLTYPE yup::operator<< (String & s1, StringRef s2)
Appends a string to the end of the first one.
operator<<() [19/36]
YUP_API String &YUP_CALLTYPE yup::operator<< (String & s1, const std::string & s2)
Appends a string to the end of the first one.
operator<<() [20/36]
YUP_API String &YUP_CALLTYPE yup::operator<< (String & s1, uint8 number)
Appends a decimal number to the end of a string.
operator<<() [21/36]
YUP_API String &YUP_CALLTYPE yup::operator<< (String & s1, short number)
Appends a decimal number to the end of a string.
operator<<() [22/36]
YUP_API String &YUP_CALLTYPE yup::operator<< (String & s1, int number)
Appends a decimal number to the end of a string.
operator<<() [23/36]
YUP_API String &YUP_CALLTYPE yup::operator<< (String & s1, long number)
Appends a decimal number to the end of a string.
operator<<() [24/36]
YUP_API String &YUP_CALLTYPE yup::operator<< (String & s1, unsigned long number)
Appends a decimal number to the end of a string.
operator<<() [25/36]
YUP_API String &YUP_CALLTYPE yup::operator<< (String & s1, int64 number)
Appends a decimal number to the end of a string.
operator<<() [26/36]
YUP_API String &YUP_CALLTYPE yup::operator<< (String & s1, uint64 number)
Appends a decimal number to the end of a string.
operator<<() [27/36]
YUP_API String &YUP_CALLTYPE yup::operator<< (String & s1, float number)
Appends a decimal number to the end of a string.
operator<<() [28/36]
YUP_API String &YUP_CALLTYPE yup::operator<< (String & s1, double number)
Appends a decimal number to the end of a string.
operator<<() [29/36]
YUP_API OutputStream &YUP_CALLTYPE yup::operator<< (OutputStream & stream, const String & text)
Writes a string to an OutputStream as UTF8.
References operator<<().
operator<<() [30/36]
YUP_API OutputStream &YUP_CALLTYPE yup::operator<< (OutputStream & stream, StringRef text)
Writes a string to an OutputStream as UTF8.
References yup::CharPointer_UTF8::getAddress(), yup::CharPointer_UTF8::getBytesRequiredFor(), yup::StringRef::text, yup::OutputStream::write(), and yup::CharPointer_UTF8::writeAll().
reduceLengthOfFloatString()
String yup::reduceLengthOfFloatString (const String & input)
References end(), yup::String::getCharPointer(), and yup::String::length().
Referenced by serialiseDouble().
serialiseDouble()
String yup::serialiseDouble (double input, int maxDecimalPlaces = 0)
References exactlyEqual(), and reduceLengthOfFloatString().
Referenced by yup::XmlElement::setAttribute(), and yup::JSON::writeToStream().
operator<<() [31/36]
template<class traits> std::basic_ostream< char, traits > &YUP_CALLTYPE yup::operator<< (std::basic_ostream< char, traits > & stream, const String & stringToWrite)
This operator allows you to write a yup String directly to std output streams.
This is handy for writing strings to std::cout, std::cerr, etc.
References yup::String::toRawUTF8().
operator<<() [32/36]
template<class traits> std::basic_ostream< wchar_t, traits > &YUP_CALLTYPE yup::operator<< (std::basic_ostream< wchar_t, traits > & stream, const String & stringToWrite)
This operator allows you to write a yup String directly to std output streams.
This is handy for writing strings to std::wcout, std::wcerr, etc.
References yup::String::toWideCharPointer().
operator+() [14/20]
String yup::operator+ (String s1, StringRef s2)
References yup::StringRef::text.
operator+() [15/20]
String yup::operator+ (StringRef s1, const String & s2)
References yup::StringRef::text.
operator+() [16/20]
String yup::operator+ (const char * s1, StringRef s2)
References yup::StringRef::text.
operator+() [17/20]
String yup::operator+ (StringRef s1, const char * s2)
References yup::StringRef::text.
yup_threadEntryPoint()
void YUP_API yup::yup_threadEntryPoint (void * userData)
operator+() [18/20]
YUP_API RelativeTime YUP_CALLTYPE yup::operator+ (RelativeTime t1, RelativeTime t2) noexcept
Adds two RelativeTimes together.
operator-() [1/3]
YUP_API RelativeTime YUP_CALLTYPE yup::operator- (RelativeTime t1, RelativeTime t2) noexcept
Subtracts two RelativeTimes.
operator==() [15/16]
YUP_API bool YUP_CALLTYPE yup::operator== (RelativeTime t1, RelativeTime t2) noexcept
Compares two RelativeTimes.
References exactlyEqual().
operator!=() [15/16]
YUP_API bool YUP_CALLTYPE yup::operator!= (RelativeTime t1, RelativeTime t2) noexcept
Compares two RelativeTimes.
operator>() [3/4]
YUP_API bool YUP_CALLTYPE yup::operator> (RelativeTime t1, RelativeTime t2) noexcept
Compares two RelativeTimes.
operator<() [3/4]
YUP_API bool YUP_CALLTYPE yup::operator< (RelativeTime t1, RelativeTime t2) noexcept
Compares two RelativeTimes.
operator>=() [3/4]
YUP_API bool YUP_CALLTYPE yup::operator>= (RelativeTime t1, RelativeTime t2) noexcept
Compares two RelativeTimes.
operator<=() [3/4]
YUP_API bool YUP_CALLTYPE yup::operator<= (RelativeTime t1, RelativeTime t2) noexcept
Compares two RelativeTimes.
yup_millisecondsSinceStartup()
uint32 yup::yup_millisecondsSinceStartup () noexcept
Referenced by yup::Time::getMillisecondCounter().
operator+() [19/20]
YUP_API Time yup::operator+ (Time time, RelativeTime delta) noexcept
Adds a RelativeTime to a Time.
operator-() [2/3]
YUP_API Time yup::operator- (Time time, RelativeTime delta) noexcept
Subtracts a RelativeTime from a Time.
operator+() [20/20]
YUP_API Time yup::operator+ (RelativeTime delta, Time time) noexcept
Adds a RelativeTime to a Time.
operator-() [3/3]
YUP_API RelativeTime yup::operator- (Time time1, Time time2) noexcept
Returns the relative time difference between two times.
References yup::RelativeTime::milliseconds().
operator==() [16/16]
YUP_API bool yup::operator== (Time time1, Time time2) noexcept
Compares two Time objects.
operator!=() [16/16]
YUP_API bool yup::operator!= (Time time1, Time time2) noexcept
Compares two Time objects.
operator<() [4/4]
YUP_API bool yup::operator< (Time time1, Time time2) noexcept
Compares two Time objects.
operator>() [4/4]
YUP_API bool yup::operator> (Time time1, Time time2) noexcept
Compares two Time objects.
operator<=() [4/4]
YUP_API bool yup::operator<= (Time time1, Time time2) noexcept
Compares two Time objects.
operator>=() [4/4]
YUP_API bool yup::operator>= (Time time1, Time time2) noexcept
Compares two Time objects.
parseXML() [1/2]
std::unique_ptr< XmlElement > yup::parseXML (const String & textToParse)
Attempts to parse some XML text, returning a new XmlElement if it was valid.
If the parse fails, this will return a nullptr - if you need more information about errors or more parsing options, see the XmlDocument class instead.
See also
XmlDocument, parseXMLIfTagMatches
References yup::XmlDocument::getDocumentElement().
Referenced by yup::PropertySet::getXmlValue(), and yup::URL::readEntireXmlStream().
parseXML() [2/2]
std::unique_ptr< XmlElement > yup::parseXML (const File & fileToParse)
Attempts to parse some XML text, returning a new XmlElement if it was valid.
If the parse fails, this will return a nullptr - if you need more information about errors or more parsing options, see the XmlDocument class instead.
See also
XmlDocument, parseXMLIfTagMatches
References yup::XmlDocument::getDocumentElement().
parseXMLIfTagMatches() [1/2]
std::unique_ptr< XmlElement > yup::parseXMLIfTagMatches (const String & textToParse, StringRef requiredTag)
Does an inexpensive check to see whether the top-level element has the given tag name, and if that's true, does a full parse and returns the result.
If the outer tag doesn't match, or the XML has errors, this will return nullptr;
See also
parseXML
References yup::XmlDocument::getDocumentElementIfTagMatches().
parseXMLIfTagMatches() [2/2]
std::unique_ptr< XmlElement > yup::parseXMLIfTagMatches (const File & fileToParse, StringRef requiredTag)
Does an inexpensive check to see whether the top-level element has the given tag name, and if that's true, does a full parse and returns the result.
If the outer tag doesn't match, or the XML has errors, this will return nullptr;
See also
parseXML
References yup::XmlDocument::getDocumentElementIfTagMatches().
yup_isRunningUnderDebugger()
bool yup::yup_isRunningUnderDebugger () extern noexcept
< This macro is added to all YUP public class declarations.
Referenced by yup::Process::isRunningUnderDebugger().
logAssertion() [1/2]
void yup::logAssertion (const char * file, int line) extern noexcept
< This macro is added to all YUP public class declarations.
References logAssertion().
Referenced by logAssertion(), and logAssertion().
logAssertion() [2/2]
void yup::logAssertion (const wchar_t * file, int line) extern noexcept
< This macro is added to all YUP public class declarations.
References logAssertion().
readUnalignedLittleEndianShort()
uint16 yup::readUnalignedLittleEndianShort (const void * buffer)
References yup::ByteOrder::littleEndianShort(), and readUnaligned().
readUnalignedLittleEndianInt()
uint32 yup::readUnalignedLittleEndianInt (const void * buffer)
References yup::ByteOrder::littleEndianInt(), and readUnaligned().
readUnalignedLittleEndianInt64()
int64 yup::readUnalignedLittleEndianInt64 (const void * buffer)
References yup::ByteOrder::littleEndianInt64(), and readUnaligned().
acquireMulticastLock()
void yup::acquireMulticastLock () extern
Referenced by yup::NetworkServiceDiscovery::AvailableServiceList::AvailableServiceList().
releaseMulticastLock()
void yup::releaseMulticastLock () extern
Referenced by yup::NetworkServiceDiscovery::AvailableServiceList::~AvailableServiceList().
initialiseNSApplication()
void yup::initialiseNSApplication () extern
yup_JNI_OnLoad()
jint JNIEXPORT yup::yup_JNI_OnLoad (JavaVM * vm, void *)
initialiseYup_GUI()
YUP_API void YUP_CALLTYPE yup::initialiseYup_GUI ()
Initialises YUP's GUI classes.
If you're embedding YUP into an application that uses its own event-loop rather than using the START_YUP_APPLICATION macro, call this function before making any YUP calls, to make sure things are initialised correctly.
Note that if you're creating a YUP DLL for Windows, you may also need to call the Process::setCurrentModuleInstanceHandle() method.
See also
shutdownYup_GUI()
References yup::MessageManager::getInstance().
Referenced by yup::ScopedYupInitialiser_GUI::ScopedYupInitialiser_GUI().
shutdownYup_GUI()
YUP_API void YUP_CALLTYPE yup::shutdownYup_GUI ()
Clears up any static data being used by YUP's GUI classes.
If you're embedding YUP into an application that uses its own event-loop rather than using the START_YUP_APPLICATION macro, call this function in your shutdown code to clean up any YUP objects that might be lying around.
See also
initialiseYup_GUI()
References yup::DeletedAtShutdown::deleteAll(), and yup::MessageManager::deleteInstance().
Referenced by yup::ScopedYupInitialiser_GUI::~ScopedYupInitialiser_GUI().
get() [1/5]
template<std::size_t I> float yup::get (const AffineTransform & transform) constexpr noexcept
References dependentFalse.
Referenced by yup::Artboard::getAllInputs(), yup::XmlElement::getAttributeName(), yup::XmlElement::getAttributeValue(), yup::Time::getMillisecondCounter(), and yup::LocalisedStrings::LocalisedStrings().
operator<<() [33/36]
template<class ValueType> YUP_API String &YUP_CALLTYPE yup::operator<< (String & string1, const Line< ValueType > & l)
Stream output operator for Line objects.
This operator allows Line objects to be written to output streams in a formatted manner. It is useful for logging, debugging, or any other scenario where points need to be output to streams.
Template Parameters
ValueType The numeric type of the line's coordinates.
Parameters
string1 The output stream to which the line's coordinates are written.
The Line object whose coordinates are written to the stream.
Returns
A reference to the output stream after the line's coordinates have been written.
get() [2/5]
template<std::size_t I, class ValueType> ValueType yup::get (const Line< ValueType > & line) constexpr noexcept
References dependentFalse.
operator<<() [34/36]
template<class ValueType> YUP_API String &YUP_CALLTYPE yup::operator<< (String & string1, const Point< ValueType > & p)
Stream output operator for Point objects.
This operator allows Point objects to be written to output streams in a formatted manner. It is useful for logging, debugging, or any other scenario where points need to be output to streams.
Template Parameters
ValueType The numeric type of the point's coordinates.
Parameters
string1 The output stream to which the point's coordinates are written.
p The Point object whose coordinates are written to the stream.
Returns
A reference to the output stream after the point's coordinates have been written.
get() [3/5]
template<std::size_t I, class ValueType> ValueType yup::get (const Point< ValueType > & point) nodiscard constexpr noexcept
References dependentFalse.
operator<<() [35/36]
template<class ValueType> YUP_API String &YUP_CALLTYPE yup::operator<< (String & string1, const Rectangle< ValueType > & r)
Stream insertion operator for rectangles.
This operator allows for rectangles to be easily printed to a stream. It outputs the rectangle's position and size in the format "x, y, width, height".
Template Parameters
ValueType The type of the values stored in the rectangle.
Parameters
string1 The stream to which the rectangle will be inserted.
r The rectangle to be inserted into the stream.
Returns
A reference to the modified stream.
get() [4/5]
template<std::size_t I, class ValueType> ValueType yup::get (const Rectangle< ValueType > & point) constexpr noexcept
References dependentFalse.
operator<<() [36/36]
template<class ValueType> YUP_API String &YUP_CALLTYPE yup::operator<< (String & string1, const Size< ValueType > & s)
Stream insertion operator.
Inserts the width and height of the Size object into the provided String object, formatting them as a comma-separated pair.
Parameters
string1 The String object to which the width and height will be appended.
s The Size object whose dimensions are to be inserted into the String.
Returns
A reference to the updated String object containing the formatted dimensions.
get() [5/5]
template<std::size_t I, class ValueType> ValueType yup::get (const Size< ValueType > & point) constexpr noexcept
References dependentFalse.
initialiseYup_Windowing()
void yup::initialiseYup_Windowing ()
These are called automatically by the YUPApplication class but must be called by plugins.
Referenced by yup::YUPApplication::YUPApplication().
shutdownYup_Windowing()
void yup::shutdownYup_Windowing ()
Referenced by yup::YUPApplication::~YUPApplication().
paintSlider()
void yup::paintSlider (Graphics & g, const ApplicationTheme & theme, const Slider & s)
References yup::Path::addCenteredArc(), yup::Path::addEllipse(), yup::Path::addLine(), degreesToRadians(), yup::Graphics::fillPath(), yup::Rectangle< ValueType >::getCenter(), yup::Component::getLocalBounds(), yup::Slider::getValueNormalised(), yup::Component::hasKeyboardFocus(), yup::Slider::isMouseOver(), yup::Component::proportionOfWidth(), yup::Rectangle< ValueType >::reduced(), Round, yup::Graphics::setFillColor(), yup::Graphics::setStrokeCap(), yup::Graphics::setStrokeColor(), yup::Graphics::setStrokeWidth(), yup::Graphics::strokePath(), and yup::Graphics::strokeRect().
Referenced by createThemeVersion1().
paintTextEditor()
void yup::paintTextEditor (Graphics & g, const ApplicationTheme & theme, const TextEditor & t)
References yup::TextEditor::Colors::backgroundColorId, yup::Colors::black, yup::TextEditor::Colors::caretColorId, yup::Colors::cornflowerblue, yup::Graphics::fillFittedText(), yup::Graphics::fillRect(), yup::Graphics::fillRoundedRect(), yup::Component::findColor(), yup::TextEditor::Colors::focusedOutlineColorId, yup::TextEditor::getCaretBounds(), yup::Component::getLocalBounds(), yup::TextEditor::getScrollOffset(), yup::TextEditor::getSelectedTextAreas(), yup::TextEditor::getStyledText(), yup::TextEditor::getTextBounds(), yup::Colors::gray, yup::Component::hasKeyboardFocus(), yup::TextEditor::hasSelection(), yup::TextEditor::isCaretVisible(), yup::TextEditor::Colors::outlineColorId, yup::TextEditor::Colors::selectionColorId, yup::Graphics::setFillColor(), yup::Graphics::setStrokeColor(), yup::Graphics::setStrokeWidth(), yup::Graphics::strokeRoundedRect(), yup::TextEditor::Colors::textColorId, and yup::Colors::white.
Referenced by createThemeVersion1().
paintTextButton()
void yup::paintTextButton (Graphics & g, const ApplicationTheme & theme, const TextButton & b)
References yup::TextButton::Colors::backgroundColorId, yup::TextButton::Colors::backgroundPressedColorId, yup::Color::brighter(), yup::Colors::cornflowerblue, yup::Colors::dimgray, yup::Graphics::fillFittedText(), yup::Graphics::fillRoundedRect(), yup::Component::findColor(), yup::Component::getLocalBounds(), yup::TextButton::getStyledText(), yup::TextButton::getTextBounds(), yup::Colors::gray, yup::Component::hasKeyboardFocus(), yup::Button::isButtonDown(), yup::Button::isButtonOver(), yup::TextButton::Colors::outlineColorId, yup::TextButton::Colors::outlineFocusedColorId, yup::Graphics::setFillColor(), yup::Graphics::setStrokeColor(), yup::Graphics::setStrokeWidth(), yup::Graphics::strokeRoundedRect(), yup::TextButton::Colors::textColorId, yup::TextButton::Colors::textPressedColorId, and yup::Colors::white.
Referenced by createThemeVersion1().
paintLabel()
void yup::paintLabel (Graphics & g, const ApplicationTheme & theme, const Label & l)
References yup::Label::Colors::fillColorId, yup::Graphics::fillFittedText(), yup::Component::findColor(), yup::Component::getLocalBounds(), yup::Label::getStrokeWidth(), yup::Label::getStyledText(), yup::Graphics::setFillColor(), yup::Graphics::setStrokeColor(), yup::Graphics::setStrokeWidth(), yup::Label::Colors::strokeColorId, yup::Graphics::strokeFittedText(), and yup::Colors::white.
Referenced by createThemeVersion1().
createThemeVersion1()
ApplicationTheme::Ptr yup::createThemeVersion1 ()
References yup::ComponentStyle::createStyle(), yup::Result::failed(), yup::Label::Colors::fillColorId, yup::Font::loadFromData(), yup::Logger::outputDebugString(), paintLabel(), paintSlider(), paintTextButton(), paintTextEditor(), RobotoFlexFont_data, RobotoFlexFont_size, yup::ApplicationTheme::setColor(), yup::ApplicationTheme::setComponentStyle(), yup::ApplicationTheme::setDefaultFont(), yup::Label::Colors::strokeColorId, yup::Colors::transparentBlack, and yup::Colors::white.
Variable Documentation
minimumDecibels
auto yup::minimumDecibels = -300.0f constexpr
Referenced by yup::IIRCoefficients::makeHighShelf(), yup::IIRCoefficients::makePeakFilter(), and yup::IIRFilterBase< SpinLock >::processSamples().
YupPlugin_Category
const auto yup::YupPlugin_Category = Vst::PlugType::kFx
nullopt
auto yup::nullopt = std::nullopt constexpr
dynamicExtent
auto yup::dynamicExtent = std::numeric_limits<size_t>::max() constexpr
dependentBoolValue
template<bool Value, auto... Args> bool yup::dependentBoolValue = Value constexpr
dependentFalse
template<auto... Args> bool yup::dependentFalse = dependentBoolValue<false, Args...> constexpr
Referenced by get(), get(), get(), get(), and get().
isDetected
template<template< class... > class Op, class... Args> bool yup::isDetected = detail::isDetected<Op, Args...>::value constexpr
isDetectedExact
template<class Expected, template< class... > class Op, class... Args> bool yup::isDetectedExact = detail::isDetectedExact<Expected, Op, Args...>::value constexpr
isDetectedConvertible
template<class To, template< class... > class Op, class... Args> bool yup::isDetectedConvertible = detail::isDetectedConvertible<To, Op, Args...>::value constexpr
yup_compilationUniqueId
uint64_t yup::yup_compilationUniqueId = constexprRandomImplementation (__FILE__, __LINE__)
Referenced by yup::SystemStats::getCompileUniqueId().
newLine
NewLine yup::newLine
A predefined object representing a new-line, which can be written to a string or stream.
To write a new-line to a stream, you can use the predefined 'newLine' variable like this:
myOutputStream << "Hello World" << newLine << newLine;
Referenced by yup::FileLogger::FileLogger(), yup::SystemStats::getStackBacktrace(), yup::FileLogger::logMessage(), yup::PerformanceCounter::Statistics::toString(), and yup::DynamicObject::writeAsJSON().
emptyString
StringHolder yup::emptyString constexpr
Referenced by yup::String::clear(), yup::String::String(), and yup::String::String().
yup_compilationDate
const char * yup::yup_compilationDate = __DATE__
Referenced by yup::Time::getCompilationDate().
yup_compilationTime
const char * yup::yup_compilationTime = __TIME__
Referenced by yup::Time::getCompilationDate().
yup_argv
const char* const* yup::yup_argv = nullptr
Referenced by yup::YUPApplicationBase::getCommandLineParameterArray().
yup_argc
int yup::yup_argc = 0
Referenced by yup::YUPApplicationBase::getCommandLineParameterArray().
Line
template<class ValueType> class YUP_API yup::Line
Component
class YUP_API yup::Component
RobotoFlexFont_data
const uint8_t yup::RobotoFlexFont_data
Initial value:
= {
}
Referenced by createThemeVersion1().
RobotoFlexFont_size
const std::size_t yup::RobotoFlexFont_size = sizeof (RobotoFlexFont_data)
Referenced by createThemeVersion1().