YUP: yup::MidiBufferHelpers Namespace Reference
yup::MidiBufferHelpers Namespace Reference
Functions
int getEventTime (const void *d) noexcept
uint16 getEventDataSize (const void *d) noexcept
uint16 getEventTotalSize (const void *d) noexcept
Function Documentation
getEventTime()
int yup::MidiBufferHelpers::getEventTime (const void * d) noexcept
References yup::readUnaligned().
Referenced by yup::MidiBuffer::getFirstEventTime(), yup::MidiBuffer::getLastEventTime(), and yup::MidiBufferIterator::operator*().
getEventDataSize()
uint16 yup::MidiBufferHelpers::getEventDataSize (const void * d) noexcept
References yup::readUnaligned().
Referenced by getEventTotalSize(), yup::MidiBufferIterator::operator*(), and yup::MidiBufferIterator::operator++().
getEventTotalSize()
uint16 yup::MidiBufferHelpers::getEventTotalSize (const void * d) noexcept
References getEventDataSize().
Referenced by yup::MidiBuffer::getLastEventTime(), and yup::MidiBuffer::getNumEvents().