YUP: yup::StringHelpers Namespace Reference
yup::StringHelpers Namespace Reference
Functions
template<typename T>
String & operationAddAssign (String &str, const T number)
Function Documentation
operationAddAssign()
template<typename T> String & yup::StringHelpers::operationAddAssign (String & str, const T number)
References yup::String::appendCharPointer(), yup::end(), yup::numElementsInArray(), and operationAddAssign().
Referenced by operationAddAssign(), yup::String::operator+=(), yup::String::operator+=(), yup::String::operator+=(), and yup::String::operator+=().