YUP: yup::UndoManager::ScopedTransaction Struct Reference
yup::UndoManager::ScopedTransaction Struct Reference
Helper class to ensure that certain actions are grouped as a single action.
Public Member Functions
ScopedTransaction (UndoManager &undoManager)
Constructs a ScopedTransaction object.
ScopedTransaction (UndoManager &undoManager, StringRef transactionName)
Constructs a ScopedTransaction object.
~ScopedTransaction ()
Destructs the ScopedTransaction object.
Detailed Description
Helper class to ensure that certain actions are grouped as a single action.
By default, the undo manager groups all actions within a 500ms time window into one action. If you need to have a separate item in the timeline for certain actions, you can use this class.
Example usage:
void doSomething()
{
    UndoManager::ScopedTransaction transaction (um);
    um.perform (action1);
    um.perform (action2);
}
Constructor & Destructor Documentation
ScopedTransaction() [1/2]
yup::UndoManager::ScopedTransaction::ScopedTransaction (UndoManager & undoManager)
Constructs a ScopedTransaction object.
Parameters
undoManager The UndoManager to be used.
References ScopedTransaction(), and yup::UndoManager::UndoManager().
Referenced by ScopedTransaction().
ScopedTransaction() [2/2]
yup::UndoManager::ScopedTransaction::ScopedTransaction (UndoManager & undoManager, StringRef transactionName)
Constructs a ScopedTransaction object.
Parameters
undoManager The UndoManager to be used.
transactionName The name of the transaction.
References yup::UndoManager::UndoManager().
~ScopedTransaction()
yup::UndoManager::ScopedTransaction::~ScopedTransaction ()
Destructs the ScopedTransaction object.