YUP: yup::MathConstants< FloatType > Struct Template Reference
yup::MathConstants< FloatType > Struct Template Reference
Commonly used mathematical constants.
Static Public Attributes
static constexpr FloatType pi = static_cast<FloatType> (3.141592653589793238L)
A predefined value for Pi.
static constexpr FloatType twoPi = static_cast<FloatType> (2.0L * 3.141592653589793238L)
A predefined value for 2 * Pi.
static constexpr FloatType halfPi = static_cast<FloatType> (3.141592653589793238L / 2.0L)
A predefined value for Pi / 2.
static constexpr FloatType euler = static_cast<FloatType> (2.71828182845904523536L)
A predefined value for Euler's number.
static constexpr FloatType sqrt2 = static_cast<FloatType> (1.4142135623730950488L)
A predefined value for sqrt (2)
Detailed Description
template<typename FloatType>
struct yup::MathConstants< FloatType >
Commonly used mathematical constants.
Member Data Documentation
pi
template<typename FloatType> FloatType yup::MathConstants< FloatType >::pi = static_cast<FloatType> (3.141592653589793238L) static constexpr
A predefined value for Pi.
Referenced by yup::degreesToRadians(), yup::IIRCoefficients::makeBandPass(), yup::IIRCoefficients::makeHighPass(), yup::IIRFilterBase< SpinLock >::makeInactive(), yup::IIRCoefficients::makeLowPass(), yup::IIRCoefficients::makeNotchFilter(), and yup::radiansToDegrees().
twoPi
template<typename FloatType> FloatType yup::MathConstants< FloatType >::twoPi = static_cast<FloatType> (2.0L * 3.141592653589793238L) static constexpr
A predefined value for 2 * Pi.
Referenced by yup::Path::addPolygon(), yup::Path::addStar(), yup::ToneGeneratorAudioSource::getNextAudioBlock(), yup::IIRCoefficients::makeHighShelf(), yup::IIRCoefficients::makePeakFilter(), yup::AudioDeviceManager::playTestSound(), and yup::IIRFilterBase< SpinLock >::processSingleSampleRaw().
halfPi
template<typename FloatType> FloatType yup::MathConstants< FloatType >::halfPi = static_cast<FloatType> (3.141592653589793238L / 2.0L) static constexpr
A predefined value for Pi / 2.
euler
template<typename FloatType> FloatType yup::MathConstants< FloatType >::euler = static_cast<FloatType> (2.71828182845904523536L) static constexpr
A predefined value for Euler's number.
sqrt2
template<typename FloatType> FloatType yup::MathConstants< FloatType >::sqrt2 = static_cast<FloatType> (1.4142135623730950488L) static constexpr
A predefined value for sqrt (2)
Referenced by yup::IIRCoefficients::makeAllPass(), yup::IIRCoefficients::makeBandPass(), yup::IIRCoefficients::makeLowPass(), and yup::IIRCoefficients::makeNotchFilter().