YUP: yup::Base64 Struct Reference
yup::Base64 Struct Reference
Contains some static methods for converting between binary and the standard base-64 encoding format.
Static Public Member Functions
static bool convertToBase64 (OutputStream &base64Result, const void *sourceData, size_t sourceDataSize)
Converts a binary block of data into a base-64 string.
static bool convertFromBase64 (OutputStream &binaryOutput, StringRef base64TextInput)
Converts a base-64 string back to its binary representation.
static String toBase64 (const void *sourceData, size_t sourceDataSize)
Converts a block of binary data to a base-64 string.
static String toBase64 (const String &textToEncode)
Converts a string's UTF-8 representation to a base-64 string.
Detailed Description
Contains some static methods for converting between binary and the standard base-64 encoding format.
Member Function Documentation
convertToBase64()
bool yup::Base64::convertToBase64 (OutputStream & base64Result, const void * sourceData, size_t sourceDataSize) static
Converts a binary block of data into a base-64 string.
This will write the resulting string data to the given stream. If a write error occurs with the stream, the method will terminate and return false.
References yup::OutputStream::write().
Referenced by toBase64().
convertFromBase64()
bool yup::Base64::convertFromBase64 (OutputStream & binaryOutput, StringRef base64TextInput) static
Converts a base-64 string back to its binary representation.
This will write the decoded binary data to the given stream. If the string is not valid base-64, the method will terminate and return false.
References yup::CharPointer_UTF8::isEmpty(), yup::StringRef::text, and yup::OutputStream::writeByte().
toBase64() [1/2]
String yup::Base64::toBase64 (const void * sourceData, size_t sourceDataSize) static
Converts a block of binary data to a base-64 string.
References convertToBase64(), and yup::MemoryOutputStream::toString().
Referenced by toBase64().
toBase64() [2/2]
String yup::Base64::toBase64 (const String & textToEncode) static
Converts a string's UTF-8 representation to a base-64 string.
References toBase64(), and yup::String::toRawUTF8().