YUP: yup::ArgumentList::Argument Struct Reference
yup::ArgumentList::Argument Struct Reference
One of the arguments in an ArgumentList.
Public Member Functions
File resolveAsFile () const
Resolves this argument as an absolute File, using the current working directory as a base for resolving relative paths, and stripping quotes, etc.
File resolveAsExistingFile () const
Resolves this argument as an absolute File, using the current working directory as a base for resolving relative paths, and also doing a check to make sure the file exists.
File resolveAsExistingFolder () const
Resolves a user-supplied folder name into an absolute File, using the current working directory as a base for resolving relative paths, and also doing a check to make sure the folder exists.
bool isLongOption () const
Returns true if this argument starts with a double dash.
bool isShortOption () const
Returns true if this argument starts with a single dash.
bool isLongOption (const String &optionRoot) const
Returns true if this argument starts with a double dash, followed by the given string.
String getLongOptionValue () const
If this argument is a long option with a value, this returns the value.
bool isShortOption (char shortOptionCharacter) const
Returns true if this argument starts with a single dash and then contains the given character somewhere inside it.
bool isOption () const
Returns true if this argument starts with one or more dashes.
bool operator== (StringRef stringToCompare) const
Compares this argument against a string.
bool operator!= (StringRef stringToCompare) const
Compares this argument against a string.
Public Attributes
String text
The original text of this argument.
Detailed Description
One of the arguments in an ArgumentList.
Member Function Documentation
resolveAsFile()
File yup::ArgumentList::Argument::resolveAsFile () const
Resolves this argument as an absolute File, using the current working directory as a base for resolving relative paths, and stripping quotes, etc.
References text.
Referenced by resolveAsExistingFile(), and resolveAsExistingFolder().
resolveAsExistingFile()
File yup::ArgumentList::Argument::resolveAsExistingFile () const
Resolves this argument as an absolute File, using the current working directory as a base for resolving relative paths, and also doing a check to make sure the file exists.
If the file doesn't exist, this will call fail() with a suitable error.
See also
resolveAsFile, resolveAsExistingFolder
References resolveAsFile().
resolveAsExistingFolder()
File yup::ArgumentList::Argument::resolveAsExistingFolder () const
Resolves a user-supplied folder name into an absolute File, using the current working directory as a base for resolving relative paths, and also doing a check to make sure the folder exists.
If the folder doesn't exist, this will call fail() with a suitable error.
See also
resolveAsFile, resolveAsExistingFile
References yup::ConsoleApplication::fail(), and resolveAsFile().
isLongOption() [1/2]
bool yup::ArgumentList::Argument::isLongOption () const
Returns true if this argument starts with a double dash.
References text.
Referenced by getLongOptionValue(), isLongOption(), and operator==().
isShortOption() [1/2]
bool yup::ArgumentList::Argument::isShortOption () const
Returns true if this argument starts with a single dash.
References text.
Referenced by isShortOption(), and operator==().
isLongOption() [2/2]
bool yup::ArgumentList::Argument::isLongOption (const String & optionRoot) const
Returns true if this argument starts with a double dash, followed by the given string.
References isLongOption(), and text.
getLongOptionValue()
String yup::ArgumentList::Argument::getLongOptionValue () const
If this argument is a long option with a value, this returns the value.
e.g. for "--foo=bar", this would return 'bar'.
References isLongOption(), and text.
isShortOption() [2/2]
bool yup::ArgumentList::Argument::isShortOption (char shortOptionCharacter) const
Returns true if this argument starts with a single dash and then contains the given character somewhere inside it.
References isShortOption(), and text.
isOption()
bool yup::ArgumentList::Argument::isOption () const
Returns true if this argument starts with one or more dashes.
References text.
operator==()
bool yup::ArgumentList::Argument::operator== (StringRef stringToCompare) const
Compares this argument against a string.
The string may be a pipe-separated list of options, e.g. "--help|-h"
References yup::StringArray::fromTokens(), isLongOption(), isShortOption(), and text.
operator!=()
bool yup::ArgumentList::Argument::operator!= (StringRef stringToCompare) const
Compares this argument against a string.
The string may be a pipe-separated list of options, e.g. "--help|-h"
References yup::operator==().
Member Data Documentation
text
String yup::ArgumentList::Argument::text
The original text of this argument.
Referenced by getLongOptionValue(), isLongOption(), isLongOption(), isOption(), isShortOption(), isShortOption(), operator==(), and resolveAsFile().