YUP: yup::MidiDeviceInfo Struct Reference
yup::MidiDeviceInfo Struct Reference
This struct contains information about a MIDI input or output device.
Public Member Functions
MidiDeviceInfo ()=default
MidiDeviceInfo (const String &deviceName, const String &deviceIdentifier)
auto tie () const
bool operator== (const MidiDeviceInfo &other) const noexcept
bool operator!= (const MidiDeviceInfo &other) const noexcept
Public Attributes
String name
The name of this device.
String identifier
The identifier for this device.
Detailed Description
This struct contains information about a MIDI input or output device.
You can get one of these structs by calling the static getAvailableDevices() or getDefaultDevice() methods of MidiInput and MidiOutput or by calling getDeviceInfo() on an instance of these classes. Devices can be opened by passing the identifier to the openDevice() method.
Constructor & Destructor Documentation
MidiDeviceInfo() [1/2]
yup::MidiDeviceInfo::MidiDeviceInfo () default
Referenced by operator!=(), and operator==().
MidiDeviceInfo() [2/2]
yup::MidiDeviceInfo::MidiDeviceInfo (const String & deviceName, const String & deviceIdentifier)
References identifier, and name.
Member Function Documentation
tie()
auto yup::MidiDeviceInfo::tie () const
References identifier, and name.
Referenced by operator!=(), and operator==().
operator==()
bool yup::MidiDeviceInfo::operator== (const MidiDeviceInfo & other) const noexcept
References MidiDeviceInfo(), and tie().
operator!=()
bool yup::MidiDeviceInfo::operator!= (const MidiDeviceInfo & other) const noexcept
References MidiDeviceInfo(), and tie().
Member Data Documentation
name
String yup::MidiDeviceInfo::name
The name of this device.
This will be provided by the OS unless the device has been created with the createNewDevice() method.
Note that the name is not guaranteed to be unique and two devices with the same name will be indistinguishable. If you want to address a specific device it is better to use the identifier.
Referenced by MidiDeviceInfo(), and tie().
identifier
String yup::MidiDeviceInfo::identifier
The identifier for this device.
This will be provided by the OS and it's format will differ on different systems e.g. on macOS it will be a number whereas on Windows it will be a long alphanumeric string.
Referenced by MidiDeviceInfo(), and tie().