YUP: yup::NamedValueSet::NamedValue Struct Reference
yup::NamedValueSet::NamedValue Struct Reference
Structure for a named var object.
Public Member Functions
NamedValue () noexcept
~NamedValue () noexcept
NamedValue (const Identifier &name, const var &value)
NamedValue (const Identifier &name, var &&value) noexcept
NamedValue (Identifier &&name, var &&value) noexcept
NamedValue (const NamedValue &)
NamedValue (NamedValue &&) noexcept
NamedValue & operator= (NamedValue &&) noexcept
bool operator== (const NamedValue &) const noexcept
bool operator!= (const NamedValue &) const noexcept
Public Attributes
Identifier name
var value
Detailed Description
Structure for a named var object.
Constructor & Destructor Documentation
NamedValue() [1/6]
yup::NamedValueSet::NamedValue::NamedValue () noexcept
Referenced by NamedValue(), NamedValue(), operator!=(), operator=(), and operator==().
~NamedValue()
yup::NamedValueSet::NamedValue::~NamedValue () noexcept
NamedValue() [2/6]
yup::NamedValueSet::NamedValue::NamedValue (const Identifier & name, const var & value)
References name, and value.
NamedValue() [3/6]
yup::NamedValueSet::NamedValue::NamedValue (const Identifier & name, var && value) noexcept
References name, and value.
NamedValue() [4/6]
yup::NamedValueSet::NamedValue::NamedValue (Identifier && name, var && value) noexcept
References name, and value.
NamedValue() [5/6]
yup::NamedValueSet::NamedValue::NamedValue (const NamedValue & other)
References name, NamedValue(), and value.
NamedValue() [6/6]
yup::NamedValueSet::NamedValue::NamedValue (NamedValue && other) noexcept
References NamedValue().
Member Function Documentation
operator=()
NamedValueSet::NamedValue & yup::NamedValueSet::NamedValue::operator= (NamedValue && other) noexcept
References name, NamedValue(), and value.
operator==()
bool yup::NamedValueSet::NamedValue::operator== (const NamedValue & other) const noexcept
References name, NamedValue(), and value.
operator!=()
bool yup::NamedValueSet::NamedValue::operator!= (const NamedValue & other) const noexcept
References NamedValue(), and yup::NamedValueSet::operator==().
Member Data Documentation
name
Identifier yup::NamedValueSet::NamedValue::name
Referenced by NamedValue(), NamedValue(), NamedValue(), NamedValue(), operator=(), and operator==().
value
var yup::NamedValueSet::NamedValue::value
Referenced by NamedValue(), NamedValue(), NamedValue(), NamedValue(), operator=(), and operator==().