YUP: yup::AudioProcessLoadMeasurer::ScopedTimer Struct Reference
yup::AudioProcessLoadMeasurer::ScopedTimer Struct Reference
This class measures the time between its construction and destruction and adds it to an AudioProcessLoadMeasurer.
Public Member Functions
ScopedTimer (AudioProcessLoadMeasurer &)
ScopedTimer (AudioProcessLoadMeasurer &, int numSamplesInBlock)
~ScopedTimer ()
Detailed Description
This class measures the time between its construction and destruction and adds it to an AudioProcessLoadMeasurer.
e.g.
{
    AudioProcessLoadMeasurer::ScopedTimer timer (myProcessLoadMeasurer);
    myCallback->doTheCallback();
}
Constructor & Destructor Documentation
ScopedTimer() [1/2]
yup::AudioProcessLoadMeasurer::ScopedTimer::ScopedTimer (AudioProcessLoadMeasurer & p)
References yup::AudioProcessLoadMeasurer::AudioProcessLoadMeasurer(), and ScopedTimer().
Referenced by ScopedTimer().
ScopedTimer() [2/2]
yup::AudioProcessLoadMeasurer::ScopedTimer::ScopedTimer (AudioProcessLoadMeasurer & p, int numSamplesInBlock)
References yup::AudioProcessLoadMeasurer::AudioProcessLoadMeasurer().
~ScopedTimer()
yup::AudioProcessLoadMeasurer::ScopedTimer::~ScopedTimer ()
References yup::Time::getMillisecondCounterHiRes().