YUP: yup::ComponentNative::Options Struct Reference
yup::ComponentNative::Options Struct Reference
Configuration options for creating a native component.
Public Member Functions
constexpr Options () noexcept=default
Default constructor, initializes the options with default values.
Options & withFlags (Flags newFlags) noexcept
Sets the flags for the native component.
Options & withDecoration (bool shouldHaveDecoration) noexcept
Sets whether the window should have decorations.
Options & withResizableWindow (bool shouldAllowResizing) noexcept
Sets whether the window should be resizable.
Options & withRenderContinuous (bool shouldRenderContinuous) noexcept
Sets whether the component should render continuously.
Options & withAllowedHighDensityDisplay (bool shouldAllowHighDensity) noexcept
Sets whether high-density display should be allowed.
Options & withGraphicsApi (std::optional< GraphicsContext::Api > newGraphicsApi) noexcept
Sets the graphics API to be used for rendering.
Options & withFramerateRedraw (std::optional< float > newFramerateRedraw) noexcept
Sets the target framerate for continuous rendering.
Options & withClearColor (std::optional< Color > newClearColor) noexcept
Sets the clear color used when rendering.
Options & withDoubleClickTime (std::optional< RelativeTime > newDoubleClickTime) noexcept
Sets the double-click detection time.
Options & withUpdateOnlyFocused (bool onlyWhenFocused) noexcept
Sets whether updates should only happen when the window is focused.
Public Attributes
Flags flags = defaultFlags
The configuration flags for the component.
std::optional< GraphicsContext::Api > graphicsApi
The graphics API to use for rendering.
std::optional< float > framerateRedraw
The target framerate for continuous rendering.
std::optional< Color > clearColor
The clear color to use when rendering.
std::optional< RelativeTime > doubleClickTime
The maximum time between clicks to be considered a double-click.
bool updateOnlyWhenFocused = false
Whether updates should only happen when the window is focused.
Detailed Description
Configuration options for creating a native component.
This structure encapsulates all the configuration options that can be used when creating a new ComponentNative instance. It provides a fluent interface for setting options.
Constructor & Destructor Documentation
Options()
yup::ComponentNative::Options::Options () constexpr default noexcept
Default constructor, initializes the options with default values.
References Options(), withAllowedHighDensityDisplay(), withClearColor(), withDecoration(), withDoubleClickTime(), withFlags(), withFramerateRedraw(), withGraphicsApi(), withRenderContinuous(), withResizableWindow(), and withUpdateOnlyFocused().
Referenced by Options().
Member Function Documentation
withFlags()
ComponentNative::Options & yup::ComponentNative::Options::withFlags (Flags newFlags) noexcept
Sets the flags for the native component.
Parameters
newFlags The flags to set.
Returns
Reference to this Options object for method chaining.
References flags.
Referenced by Options().
withDecoration()
ComponentNative::Options & yup::ComponentNative::Options::withDecoration (bool shouldHaveDecoration) noexcept
Sets whether the window should have decorations.
Parameters
shouldHaveDecoration True to enable window decorations, false to disable.
Returns
Reference to this Options object for method chaining.
References yup::ComponentNative::decoratedWindow, and flags.
Referenced by Options().
withResizableWindow()
ComponentNative::Options & yup::ComponentNative::Options::withResizableWindow (bool shouldAllowResizing) noexcept
Sets whether the window should be resizable.
Parameters
shouldAllowResizing True to enable window resizing, false to disable.
Returns
Reference to this Options object for method chaining.
References flags, and yup::ComponentNative::resizableWindow.
Referenced by Options().
withRenderContinuous()
ComponentNative::Options & yup::ComponentNative::Options::withRenderContinuous (bool shouldRenderContinuous) noexcept
Sets whether the component should render continuously.
Parameters
shouldRenderContinuous True to enable continuous rendering, false to use on-demand rendering.
Returns
Reference to this Options object for method chaining.
References flags, and yup::ComponentNative::renderContinuous.
Referenced by Options().
withAllowedHighDensityDisplay()
ComponentNative::Options & yup::ComponentNative::Options::withAllowedHighDensityDisplay (bool shouldAllowHighDensity) noexcept
Sets whether high-density display should be allowed.
Parameters
shouldAllowHighDensity True to enable high-density display support, false to disable.
Returns
Reference to this Options object for method chaining.
References yup::ComponentNative::allowHighDensityDisplay, and flags.
Referenced by Options().
withGraphicsApi()
ComponentNative::Options & yup::ComponentNative::Options::withGraphicsApi (std::optional< GraphicsContext::Api > newGraphicsApi) noexcept
Sets the graphics API to be used for rendering.
Parameters
newGraphicsApi The graphics API to use, or std::nullopt to use the default.
Returns
Reference to this Options object for method chaining.
References graphicsApi.
Referenced by Options().
withFramerateRedraw()
ComponentNative::Options & yup::ComponentNative::Options::withFramerateRedraw (std::optional< float > newFramerateRedraw) noexcept
Sets the target framerate for continuous rendering.
Parameters
newFramerateRedraw The target framerate, or std::nullopt to use the default.
Returns
Reference to this Options object for method chaining.
References framerateRedraw.
Referenced by Options().
withClearColor()
ComponentNative::Options & yup::ComponentNative::Options::withClearColor (std::optional< Color > newClearColor) noexcept
Sets the clear color used when rendering.
Parameters
newClearColor The clear color, or std::nullopt to use the default.
Returns
Reference to this Options object for method chaining.
References clearColor.
Referenced by Options().
withDoubleClickTime()
ComponentNative::Options & yup::ComponentNative::Options::withDoubleClickTime (std::optional< RelativeTime > newDoubleClickTime) noexcept
Sets the double-click detection time.
Parameters
newDoubleClickTime The maximum time between clicks to be considered a double-click, or std::nullopt to use the default.
Returns
Reference to this Options object for method chaining.
References doubleClickTime.
Referenced by Options().
withUpdateOnlyFocused()
ComponentNative::Options & yup::ComponentNative::Options::withUpdateOnlyFocused (bool onlyWhenFocused) noexcept
Sets whether updates should only happen when the window is focused.
Parameters
onlyWhenFocused True to only update when focused, false to update regardless of focus state.
Returns
Reference to this Options object for method chaining.
References updateOnlyWhenFocused.
Referenced by Options().
Member Data Documentation
flags
Flags yup::ComponentNative::Options::flags = defaultFlags
The configuration flags for the component.
Referenced by withAllowedHighDensityDisplay(), withDecoration(), withFlags(), withRenderContinuous(), and withResizableWindow().
graphicsApi
std::optional<GraphicsContext::Api> yup::ComponentNative::Options::graphicsApi
The graphics API to use for rendering.
Referenced by withGraphicsApi().
framerateRedraw
std::optional<float> yup::ComponentNative::Options::framerateRedraw
The target framerate for continuous rendering.
Referenced by withFramerateRedraw().
clearColor
std::optional<Color> yup::ComponentNative::Options::clearColor
The clear color to use when rendering.
Referenced by withClearColor().
doubleClickTime
std::optional<RelativeTime> yup::ComponentNative::Options::doubleClickTime
The maximum time between clicks to be considered a double-click.
Referenced by withDoubleClickTime().
updateOnlyWhenFocused
bool yup::ComponentNative::Options::updateOnlyWhenFocused = false
Whether updates should only happen when the window is focused.
Referenced by withUpdateOnlyFocused().