YUP: yup::NoneSuch Struct Reference
yup::NoneSuch Struct Reference
Public Member Functions
NoneSuch ()=delete
~NoneSuch ()=delete
NoneSuch (const NoneSuch &)=delete
void operator= (const NoneSuch &)=delete
NoneSuch (NoneSuch &&)=delete
void operator= (NoneSuch &&)=delete
Constructor & Destructor Documentation
NoneSuch() [1/3]
yup::NoneSuch::NoneSuch () delete
Referenced by NoneSuch(), NoneSuch(), operator=(), and operator=().
~NoneSuch()
yup::NoneSuch::~NoneSuch () delete
NoneSuch() [2/3]
yup::NoneSuch::NoneSuch (const NoneSuch &) delete
References NoneSuch().
NoneSuch() [3/3]
yup::NoneSuch::NoneSuch (NoneSuch &&) delete
References NoneSuch().
Member Function Documentation
operator=() [1/2]
void yup::NoneSuch::operator= (const NoneSuch &) delete
References NoneSuch().
operator=() [2/2]
void yup::NoneSuch::operator= (NoneSuch &&) delete
References NoneSuch().