YUP: yup::ArgumentList Struct Reference
yup::ArgumentList Struct Reference
Holds a list of command-line arguments, and provides useful methods for searching and operating on them.
Classes
struct Argument
One of the arguments in an ArgumentList.
Public Member Functions
ArgumentList (String executable, StringArray arguments)
Creates an argument list for a given executable.
ArgumentList (int argc, char *argv[])
Parses a standard argv/argc pair to create an argument list.
ArgumentList (const String &executable, const String &arguments)
Tokenises a string containing all the arguments to create an argument list.
ArgumentList (const ArgumentList &)=default
ArgumentList & operator= (const ArgumentList &)=default
int size () const
Returns the number of arguments in the list.
Argument operator[] (int index) const
Returns one of the arguments.
void checkMinNumArguments (int expectedMinNumberOfArgs) const
Throws an error unless there are at least the given number of arguments.
bool containsOption (StringRef option) const
Returns true if the given string matches one of the arguments.
bool removeOptionIfFound (StringRef option)
Returns true if the given string matches one of the arguments, and also removes the argument from the list if found.
int indexOfOption (StringRef option) const
Returns the index of the given string if it matches one of the arguments, or -1 if it doesn't.
void failIfOptionIsMissing (StringRef option) const
Throws an error unless the given option is found in the argument list.
String getValueForOption (StringRef option) const
Looks for a given argument and returns either its assigned value (for long options) or the string that follows it (for short options).
String removeValueForOption (StringRef option)
Looks for a given argument and returns either its assigned value (for long options) or the string that follows it (for short options).
File getFileForOption (StringRef option) const
Looks for the value of argument using getValueForOption() and tries to parse that value as a file.
File getFileForOptionAndRemove (StringRef option)
Looks for the value of argument using getValueForOption() and tries to parse that value as a file.
File getExistingFileForOption (StringRef option) const
Looks for a file argument using getFileForOption() and fails with a suitable error if the file doesn't exist.
File getExistingFileForOptionAndRemove (StringRef option)
Looks for a file argument using getFileForOption() and fails with a suitable error if the file doesn't exist.
File getExistingFolderForOption (StringRef option) const
Looks for a filename argument using getFileForOption() and fails with a suitable error if the file isn't a folder that exists.
File getExistingFolderForOptionAndRemove (StringRef option)
Looks for a filename argument using getFileForOption() and fails with a suitable error if the file isn't a folder that exists.
Public Attributes
String executableName
The name or path of the executable that was invoked, as it was specified on the command-line.
Array< Argument > arguments
The list of arguments (not including the name of the executable that was invoked).
Detailed Description
Holds a list of command-line arguments, and provides useful methods for searching and operating on them.
You can create an ArgumentList manually, or give it some argv/argc values from a main() function to parse.
See also
ConsoleApplication
Constructor & Destructor Documentation
ArgumentList() [1/4]
yup::ArgumentList::ArgumentList (String executable, StringArray arguments)
Creates an argument list for a given executable.
References arguments, executableName, yup::StringArray::removeEmptyStrings(), and yup::StringArray::trim().
Referenced by ArgumentList(), ArgumentList(), ArgumentList(), and operator=().
ArgumentList() [2/4]
yup::ArgumentList::ArgumentList (int argc, char * argv[])
Parses a standard argv/argc pair to create an argument list.
References ArgumentList().
ArgumentList() [3/4]
yup::ArgumentList::ArgumentList (const String & executable, const String & arguments)
Tokenises a string containing all the arguments to create an argument list.
References ArgumentList().
ArgumentList() [4/4]
yup::ArgumentList::ArgumentList (const ArgumentList &) default
References ArgumentList().
Member Function Documentation
operator=()
ArgumentList & yup::ArgumentList::operator= (const ArgumentList &) default
References ArgumentList().
size()
int yup::ArgumentList::size () const
Returns the number of arguments in the list.
References arguments.
Referenced by checkMinNumArguments().
operator[]()
ArgumentList::Argument yup::ArgumentList::operator[] (int index) const
Returns one of the arguments.
References arguments.
checkMinNumArguments()
void yup::ArgumentList::checkMinNumArguments (int expectedMinNumberOfArgs) const
Throws an error unless there are at least the given number of arguments.
References yup::ConsoleApplication::fail(), and size().
containsOption()
bool yup::ArgumentList::containsOption (StringRef option) const
Returns true if the given string matches one of the arguments.
The option can also be a list of different versions separated by pipes, e.g. "--help|-h"
See also
removeOptionIfFound
References indexOfOption().
removeOptionIfFound()
bool yup::ArgumentList::removeOptionIfFound (StringRef option)
Returns true if the given string matches one of the arguments, and also removes the argument from the list if found.
The option can also be a list of different versions separated by pipes, e.g. "--help|-h"
See also
containsOption
References arguments, and indexOfOption().
indexOfOption()
int yup::ArgumentList::indexOfOption (StringRef option) const
Returns the index of the given string if it matches one of the arguments, or -1 if it doesn't.
The option can also be a list of different versions separated by pipes, e.g. "--help|-h"
References arguments.
Referenced by containsOption(), failIfOptionIsMissing(), yup::ConsoleApplication::findCommand(), and removeOptionIfFound().
failIfOptionIsMissing()
void yup::ArgumentList::failIfOptionIsMissing (StringRef option) const
Throws an error unless the given option is found in the argument list.
References yup::ConsoleApplication::fail(), and indexOfOption().
getValueForOption()
String yup::ArgumentList::getValueForOption (StringRef option) const
Looks for a given argument and returns either its assigned value (for long options) or the string that follows it (for short options).
The option can also be a list of different versions separated by pipes, e.g. "--help|-h" If it finds a long option, it will look for an assignment with a '=' sign, e.g. "--file=foo.txt", and will return the string following the '='. If there's no '=', it will return an empty string. If it finds a short option, it will attempt to return the argument that follows it, unless it's another option. If the argument isn't found, this returns an empty string.
References arguments.
Referenced by getFileForOption().
removeValueForOption()
String yup::ArgumentList::removeValueForOption (StringRef option)
Looks for a given argument and returns either its assigned value (for long options) or the string that follows it (for short options).
This works like getValueForOption() but also removes the option argument (and any value arguments) from the list if they are found.
References arguments.
Referenced by getFileForOptionAndRemove().
getFileForOption()
File yup::ArgumentList::getFileForOption (StringRef option) const
Looks for the value of argument using getValueForOption() and tries to parse that value as a file.
If the option isn't found, or if the value can't be parsed as a filename, it will throw an error.
References getValueForOption().
Referenced by getExistingFileForOption(), and getExistingFolderForOption().
getFileForOptionAndRemove()
File yup::ArgumentList::getFileForOptionAndRemove (StringRef option)
Looks for the value of argument using getValueForOption() and tries to parse that value as a file.
This works like getFileForOption() but also removes the option argument (and any value arguments) from the list if they are found.
References removeValueForOption().
Referenced by getExistingFileForOptionAndRemove(), and getExistingFolderForOptionAndRemove().
getExistingFileForOption()
File yup::ArgumentList::getExistingFileForOption (StringRef option) const
Looks for a file argument using getFileForOption() and fails with a suitable error if the file doesn't exist.
References getFileForOption().
getExistingFileForOptionAndRemove()
File yup::ArgumentList::getExistingFileForOptionAndRemove (StringRef option)
Looks for a file argument using getFileForOption() and fails with a suitable error if the file doesn't exist.
This works like getExistingFileForOption() but also removes the option argument (and any value arguments) from the list if they are found.
References getFileForOptionAndRemove().
getExistingFolderForOption()
File yup::ArgumentList::getExistingFolderForOption (StringRef option) const
Looks for a filename argument using getFileForOption() and fails with a suitable error if the file isn't a folder that exists.
References getFileForOption().
getExistingFolderForOptionAndRemove()
File yup::ArgumentList::getExistingFolderForOptionAndRemove (StringRef option)
Looks for a filename argument using getFileForOption() and fails with a suitable error if the file isn't a folder that exists.
This works like getExistingFolderForOption() but also removes the option argument (and any value arguments) from the list if they are found.
References getFileForOptionAndRemove().
Member Data Documentation
executableName
String yup::ArgumentList::executableName
The name or path of the executable that was invoked, as it was specified on the command-line.
Referenced by ArgumentList().
arguments
Array<Argument> yup::ArgumentList::arguments
The list of arguments (not including the name of the executable that was invoked).
Referenced by ArgumentList(), getValueForOption(), indexOfOption(), operator[](), removeOptionIfFound(), removeValueForOption(), and size().