YUP: yup::CharacterFunctions::HexParser< ResultType > Struct Template Reference
yup::CharacterFunctions::HexParser< ResultType > Struct Template Reference
Parses a character string, to read a hexadecimal value.
Static Public Member Functions
template<typename CharPointerType>
static ResultType parse (CharPointerType t) noexcept
Detailed Description
template<typename ResultType>
struct yup::CharacterFunctions::HexParser< ResultType >
Parses a character string, to read a hexadecimal value.
Member Function Documentation
parse()
template<typename ResultType> template<typename CharPointerType> ResultType yup::CharacterFunctions::HexParser< ResultType >::parse (CharPointerType t) static noexcept
References yup::CharacterFunctions::getHexDigitValue().
Referenced by yup::String::getHexValue32(), yup::String::getHexValue64(), and yup::IPAddress::IPAddress().