YUP: yup::Expression::Symbol Struct Reference
yup::Expression::Symbol Struct Reference
Represents a symbol that is used in an Expression.
Public Member Functions
Symbol (const String &scopeUID, const String &symbolName)
bool operator== (const Symbol &) const noexcept
bool operator!= (const Symbol &) const noexcept
Public Attributes
String scopeUID
The unique ID of the Scope that contains this symbol.
String symbolName
The name of the symbol.
Detailed Description
Represents a symbol that is used in an Expression.
Constructor & Destructor Documentation
Symbol()
yup::Expression::Symbol::Symbol (const String & scopeUID, const String & symbolName)
References scopeUID, yup::Expression::symbol(), and symbolName.
Referenced by operator!=(), and operator==().
Member Function Documentation
operator==()
bool yup::Expression::Symbol::operator== (const Symbol & other) const noexcept
References scopeUID, Symbol(), and symbolName.
operator!=()
bool yup::Expression::Symbol::operator!= (const Symbol & other) const noexcept
References yup::operator==(), and Symbol().
Member Data Documentation
scopeUID
String yup::Expression::Symbol::scopeUID
The unique ID of the Scope that contains this symbol.
Referenced by operator==(), and Symbol().
symbolName
String yup::Expression::Symbol::symbolName
The name of the symbol.
Referenced by operator==(), Symbol(), and yup::Expression::withRenamedSymbol().