YUP: yup::NetworkServiceDiscovery::AvailableServiceList Struct Reference
yup::NetworkServiceDiscovery::AvailableServiceList Struct Reference
Watches the network for broadcasts from Advertiser objects, and keeps a list of all the currently active instances.
Public Member Functions
AvailableServiceList (const String &serviceTypeUID, int broadcastPort)
Creates an AvailableServiceList that will bind to the given port number and watch the network for Advertisers broadcasting the given service type.
~AvailableServiceList () override
Destructor.
std::vector< Service > getServices () const
Returns a list of the currently known services.
Public Attributes
std::function< void()> onChange
A lambda that can be set to receive a callback when the list changes.
Detailed Description
Watches the network for broadcasts from Advertiser objects, and keeps a list of all the currently active instances.
Just create an instance of AvailableServiceList and it will start listening - you can register a callback with its onChange member to find out when services appear/disappear, and you can call getServices() to find out the current list.
See also
Service, Advertiser
Constructor & Destructor Documentation
AvailableServiceList()
yup::NetworkServiceDiscovery::AvailableServiceList::AvailableServiceList (const String & serviceTypeUID, int broadcastPort)
Creates an AvailableServiceList that will bind to the given port number and watch the network for Advertisers broadcasting the given service type.
This will only detect broadcasts from an Advertiser object with a matching serviceTypeUID value, and where the broadcastPort matches.
References yup::acquireMulticastLock(), yup::Thread::startThread(), and yup::Thread::Thread().
~AvailableServiceList()
yup::NetworkServiceDiscovery::AvailableServiceList::~AvailableServiceList () override
Destructor.
References yup::releaseMulticastLock(), and yup::Thread::stopThread().
Member Function Documentation
getServices()
std::vector< NetworkServiceDiscovery::Service > yup::NetworkServiceDiscovery::AvailableServiceList::getServices () const
Returns a list of the currently known services.
Member Data Documentation
onChange
std::function<void()> yup::NetworkServiceDiscovery::AvailableServiceList::onChange
A lambda that can be set to receive a callback when the list changes.