YUP: yup::File::NaturalFileComparator Struct Reference
yup::File::NaturalFileComparator Struct Reference
Comparator for files.
Public Member Functions
NaturalFileComparator (bool shouldPutFoldersFirst) noexcept
int compareElements (const File &firstFile, const File &secondFile) const
Public Attributes
bool foldersFirst
Detailed Description
Comparator for files.
Constructor & Destructor Documentation
NaturalFileComparator()
yup::File::NaturalFileComparator::NaturalFileComparator (bool shouldPutFoldersFirst) noexcept
References foldersFirst.
Member Function Documentation
compareElements()
int yup::File::NaturalFileComparator::compareElements (const File & firstFile, const File & secondFile) const
References yup::String::compareNatural(), yup::File::File(), foldersFirst, yup::File::getFullPathName(), and yup::File::isDirectory().
Member Data Documentation
foldersFirst
bool yup::File::NaturalFileComparator::foldersFirst
Referenced by compareElements(), and NaturalFileComparator().