/*
  ==============================================================================

   This file is part of the YUP library.
   Copyright (c) 2025 - kunitoki@gmail.com

   YUP is an open source library subject to open-source licensing.

   The code included in this file is provided under the terms of the ISC license
   http://www.isc.org/downloads/software-support-policy/isc-license. Permission
   to use, copy, modify, and/or distribute this software for any purpose with or
   without fee is hereby granted provided that the above copyright notice and
   this permission notice appear in all copies.

   YUP IS PROVIDED "AS IS" WITHOUT ANY WARRANTY, AND ALL WARRANTIES, WHETHER
   EXPRESSED OR IMPLIED, INCLUDING MERCHANTABILITY AND FITNESS FOR PURPOSE, ARE
   DISCLAIMED.

  ==============================================================================
*/

#include "../mocks/yup_core.h"

#include "yup_AbstractFifo.cpp"
#include "yup_ArrayBase.cpp"
#include "yup_Atomic.cpp"
#include "yup_Base64.cpp"
#include "yup_BigInteger.cpp"
#include "yup_BufferedInputStream.cpp"
#include "yup_CancelToken.cpp"
#include "yup_CancelTokenSource.cpp"
#include "yup_CharacterFunctions.cpp"
#include "yup_ChildProcess.cpp"
#include "yup_ConsoleApplication.cpp"
#include "yup_DynamicLibrary.cpp"
#include "yup_DynamicObject.cpp"
#include "yup_ElementComparator.cpp"
#include "yup_Enumerate.cpp"
#include "yup_EnumHelpers.cpp"
#include "yup_Expression.cpp"
#include "yup_File.cpp"
#include "yup_FileInputStream.cpp"
#include "yup_FileSearchPath.cpp"
#include "yup_FixedSizeFunction.cpp"
#include "yup_FlagSet.cpp"
#include "yup_Functional.cpp"
#include "yup_GZIPCompressorOutputStream.cpp"
#include "yup_GZIPDecompressorInputStream.cpp"
#include "yup_HashMap.cpp"
#include "yup_HighResolutionTimer.cpp"
#include "yup_Identifier.cpp"
#include "yup_InterProcessLock.cpp"
#include "yup_IPAddress.cpp"
#include "yup_JavascriptEngine.cpp"
#include "yup_JSON.cpp"
#include "yup_JSONSerialisation.cpp"
#include "yup_JSONUtils.cpp"
#include "yup_LinkedListPointer.cpp"
#include "yup_ListenerList.cpp"
#include "yup_LocalisedStrings.cpp"
#include "yup_Logger.cpp"
#include "yup_MACAddress.cpp"
#include "yup_MathFunctions.cpp"
#include "yup_Memory.cpp"
#include "yup_MemoryInputStream.cpp"
#include "yup_MemoryMappedFile.cpp"
#include "yup_MemoryOutputStream.cpp"
#include "yup_MetaProgramming.cpp"
#include "yup_MimeTypes.cpp"
#include "yup_NamedPipe.cpp"
#include "yup_NormalisableRange.cpp"
#include "yup_OwnedArray.cpp"
#include "yup_PerformanceCounter.cpp"
#include "yup_PlatformDefs.cpp"
#include "yup_Process.cpp"
#include "yup_Profiler.cpp"
#include "yup_PropertySet.cpp"
#include "yup_Random.cpp"
#include "yup_RecursiveSpinLock.cpp"
#include "yup_ReferenceCountedArray.cpp"
#include "yup_ReferenceCountedObject.cpp"
#include "yup_Reservoir.cpp"
#include "yup_Result.cpp"
#include "yup_ResultValue.cpp"
#include "yup_ScopedValueSetter.cpp"
#include "yup_ScopeGuard.cpp"
#include "yup_SHA1.cpp"
#include "yup_SharedResourcePointer.cpp"
#include "yup_Singleton.cpp"
#include "yup_Socket.cpp"
#include "yup_SortedSet.cpp"
#include "yup_Span.cpp"
#include "yup_SparseSet.cpp"
#include "yup_SpinLock.cpp"
#include "yup_SqliteDatabase.cpp"
#include "yup_StatisticsAccumulator.cpp"
#include "yup_String.cpp"
#include "yup_StringArray.cpp"
#include "yup_StringPairArray.cpp"
#include "yup_StringPool.cpp"
#include "yup_SubregionStream.cpp"
#include "yup_SystemStats.cpp"
#include "yup_TextDiff.cpp"
#include "yup_Thread.cpp"
#include "yup_ThreadLocalValue.cpp"
#include "yup_ThreadPool.cpp"
#include "yup_Time.cpp"
#include "yup_TimeSliceThread.cpp"
#include "yup_TypeErasedObject.cpp"
#include "yup_URL.cpp"
#include "yup_Uuid.cpp"
#include "yup_Variant.cpp"
#include "yup_WaitableTimer.cpp"
#include "yup_Watchdog.cpp"
#include "yup_WebInputStream.cpp"
#include "yup_XmlDocument.cpp"
#include "yup_XmlElement.cpp"
#include "yup_YAML.cpp"
#include "yup_ZipFile.cpp"
