name: iOS

on:
  workflow_call:
    inputs:
    examples:
      description: JSON array of the examples to build
      type: string
      default: "[]"
    example_targets:
      description: JSON object mapping each example to its space-separated build targets
      type: string
      default: "{}"

env:
  ACTION_RUNNER: github-actions
  IOS_PLATFORM: OS64

jobs:
  configure:
    runs-on: macos-latest
    if: inputs.examples != '[]'
    steps:
    - uses: actions/checkout@v6
    - name: Configure
      run: |
        cmake ${{ github.workspace }} -G "Ninja Multi-Config" -DCMAKE_TOOLCHAIN_FILE=cmake/toolchains/ios.cmake \
          -DPLATFORM=${{ env.IOS_PLATFORM }} -B ${{ runner.workspace }}/build -DYUP_BUILD_EXAMPLES=ON
    - name: Build SDL
      run: |
        cmake --build ${{ runner.workspace }}/build --config Debug --target SDL3-static
        cmake --build ${{ runner.workspace }}/build --config Release --target SDL3-static
    - name: Cache Configure
      id: cache-build
      uses: actions/cache/save@v5
      with:
        path: ${{ runner.workspace }}/build
        key: ios-build-${{ github.sha }}-${{ github.run_id }}

  build_examples:
    runs-on: macos-latest
    needs: [configure]
    if: inputs.examples != '[]'
    strategy:
      fail-fast: false
      matrix:
        example: ${{ fromJson(inputs.examples) }}
    steps:
    - uses: actions/checkout@v6
    - uses: actions/cache/restore@v5
      id: cache-restore
      with:
        path: ${{ runner.workspace }}/build
        key: ios-build-${{ github.sha }}-${{ github.run_id }}
    - name: Configure If Cache Missed
      if: steps.cache-restore.outputs.cache-hit != 'true'
      run: |
        cmake ${{ github.workspace }} -G "Ninja Multi-Config" -DCMAKE_TOOLCHAIN_FILE=cmake/toolchains/ios.cmake \
          -DPLATFORM=${{ env.IOS_PLATFORM }} -B ${{ runner.workspace }}/build -DYUP_BUILD_EXAMPLES=ON
    - run: cmake --build ${{ runner.workspace }}/build --config Debug --target ${{ fromJson(inputs.example_targets)[matrix.example] }}
    - run: cmake --build ${{ runner.workspace }}/build --config Release --target ${{ fromJson(inputs.example_targets)[matrix.example] }}
