name: Clang Format

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  format:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get -y install clang-format
          clang-format --version

      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v44
        with:
          files: |
            **/*.c
            **/*.cpp
            **/*.h
            **/*.hpp
            **/*.mm
            !**/thirdparty/**

      - name: Run clang-format
        working-directory: ${{ github.workspace }}
        env:
          ALL_CHANGED_FILES: ${{ steps.changed-files.outputs.all_changed_files }}
        run: |
          echo $ALL_CHANGED_FILES
          clang-format -style=file -i $ALL_CHANGED_FILES
          git diff

      - name: Push changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: Code formatting
          commit_user_name: Yup Bot
          commit_user_email: yup-bot@users.noreply.github.com
          commit_author: Yup Bot <yup-bot@users.noreply.github.com>
